Repository department-of-veterans-affairs/caseflow, pull requests merged in 2018-07, with the labels that each got.

#6069 Remove feature flag and smooth out syncing
  app/controllers/api/v1/jobs_controller.rb
  app/jobs/sync_intake_job.rb
  app/jobs/sync_reviews_job.rb
  app/models/ramp_closed_appeal.rb
  app/models/ramp_election.rb
  spec/jobs/sync_intake_job_spec.rb
  spec/jobs/sync_reviews_job_spec.rb
  spec/models/ramp_closed_appeal_spec.rb
Labels: In-Progress, Ready-to-Merge

#6057 Ignores missing first names
  client/app/queue/JudgeReviewTaskTable.jsx
Labels: In-Progress, Ready-to-Merge

#6072 Bug fixes for Dropdown Button
  app/assets/images/icons/icon-down-arrow.svg
  app/assets/stylesheets/_commons.scss
  client/app/components/DropdownButton.jsx
Labels: In-Progress

#6060 Adding POA and AOD to AMA case details
  app/models/appeal.rb
  app/models/legacy_appeal.rb
  app/models/power_of_attorney.rb
  app/models/serializers/work_queue/appeal_serializer.rb
  app/services/bgs_power_of_attorney.rb
  client/app/reader/ClaimsFolderDetails.jsx
  db/migrate/20180628195002_add_aod_to_appeal_table.rb
  db/schema.rb
  db/seeds.rb
  lib/fakes/bgs_service.rb
  spec/feature/queue/ama_queue_spec.rb
  spec/models/legacy_appeal_spec.rb
  spec/models/power_of_attorney_spec.rb
Labels: In-Progress

#6090 Use consistent metrics naming
  app/services/prometheus_service.rb
Labels: Ready-to-Merge

#6075 Update RAMP eligibility logic
  app/models/legacy_appeal.rb
  app/services/appeal_repository.rb
  client/app/intake/pages/search.jsx
  spec/feature/intake/ramp_election_spec.rb
  spec/models/legacy_appeal_spec.rb
  spec/models/ramp_election_intake_spec.rb
  spec/services/appeals_repository_spec.rb
Labels: In-Progress, Ready-to-Merge

#6073 Queue | Add work product validation in judge check out
  app/models/legacy_tasks/judge_legacy_task.rb
  app/models/legacy_tasks/legacy_task.rb
  app/models/serializers/work_queue/legacy_task_serializer.rb
  app/models/vacols/case_assignment.rb
  app/models/vacols/decass.rb
  client/app/queue/components/JudgeStartCheckoutFlowDropdown.jsx
  client/app/queue/constants.js
  client/constants/DECASS_WORK_PRODUCT_TYPES.json
  lib/constants/decass_work_product_types.rb
  spec/factories/vacols/case.rb
  spec/factories/vacols/decass.rb
  spec/feature/queue/queue_spec.rb
Labels: In-Progress, Ready-to-Merge

#6100 Reorganize queue tests
  spec/feature/queue/case_details_spec.rb
  spec/feature/queue/checkout_flows_spec.rb
  spec/feature/queue/queue_spec.rb
  spec/feature/queue/search_spec.rb
  spec/feature/queue/task_queue_spec.rb
Labels: In-Progress, Ready-to-Merge

#6091 Remove establishes end product
  app/controllers/intakes_controller.rb
  app/models/ama_review.rb
  app/models/concerns/establishes_end_product.rb
  app/models/end_product_establishment.rb
  app/models/higher_level_review.rb
  app/models/ramp_review.rb
  app/models/supplemental_claim.rb
  spec/models/end_product_establishment_spec.rb
  spec/models/ramp_election_spec.rb
Labels: In-Progress

#6087 Caseflow | Sets up Flow
  client/.babelrc
  client/.eslintignore
  client/.flowconfig
  client/app/queue/CaseDetail/CaseDetailReducer.js
  client/app/queue/reducers.js
  client/app/queue/types.js
  client/app/queue/uiReducer/uiReducer.js
  client/app/queue/utils.js
  client/flow-typed/npm/lodash_v4.x.x.js
  client/package.json
  client/yarn.lock
  lib/tasks/lint.rake
Labels: In-Progress, Ready-to-Merge

#6104 Store raven extra application context as string
  app/jobs/application_job.rb
Labels: In-Progress, Ready-to-Merge

#6058 Upload page
  client/COPY.json
  client/app/hearingSchedule/HearingScheduleApp.jsx
  client/app/hearingSchedule/actions.js
  client/app/hearingSchedule/components/BuildSchedule.jsx
  client/app/hearingSchedule/components/BuildScheduleUpload.jsx
  client/app/hearingSchedule/constants.js
  client/app/hearingSchedule/containers/BuildScheduleUploadContainer.jsx
  client/app/hearingSchedule/reducers.js
  client/test/karma/hearingSchedule/components/BuildSchedule-test.js
  client/test/karma/hearingSchedule/components/BuildScheduleUpload-test.js
  config/routes.rb
Labels: In-Progress

#6102 Reduce queries to VACOLS::Staff
  app/services/appeal_repository.rb
Labels: In-Progress, Ready-to-Merge

#6109 Add comment for #6102
  app/services/appeal_repository.rb
Labels: Ready-to-Merge

#6113 Ignore vulnerability for a week
  Gemfile
  Gemfile.lock
  lib/tasks/security.rake
Labels: In-Progress

#6110 Add static is_legacy_appeal attribute to Appeal serializers
  app/models/serializers/work_queue/appeal_serializer.rb
  app/models/serializers/work_queue/legacy_appeal_serializer.rb
Labels: In-Progress, Ready-to-Merge

#6115 Queue | Fix sorting tasks by docket date
  client/app/queue/types.js
  client/app/queue/utils.js
Labels: In-Progress

#6105 Migrate case search to FACOLS
  spec/factories/legacy_appeal.rb
  spec/factories/vacols/folder.rb
  spec/feature/queue/search_spec.rb
Labels: In-Progress, Ready-to-Merge

#6106 Move personalized task queue test to FACOLS
  spec/feature/queue/task_queue_spec.rb
Labels: In-Progress, Ready-to-Merge

#6112 Attorney Queue | Adds days waiting column
  client/COPY.json
  client/app/components/Table.jsx
  client/app/queue/AttorneyTaskTable.jsx
Labels: In-Progress, Ready-to-Merge

#6119 Implement endpoint to return tasks for colocated admin
  app/controllers/application_controller.rb
  app/controllers/tasks_controller.rb
  app/models/queues/co_located_admin_queue.rb
  scripts/enable_features_dev.rb
  spec/controllers/tasks_controller_spec.rb
  spec/factories/vacols/staff.rb
Labels: In-Progress, Ready-to-Merge

#6054 Redesign case details issues section
  client/app/queue/CaseDetailsView.jsx
  client/app/queue/components/CaseDetailsIssueList.jsx
  client/app/queue/components/LegacyIssueListItem.jsx
  spec/feature/queue/case_details_spec.rb
Labels: In-Progress, Ready-to-Merge

#6133 adding ro allocation helper methods used in GenerateHearingDaysSchedule
  app/services/hearing_schedule/ro_allocation.rb
  spec/services/hearing_schedule/ro_allocation_spec.rb
Labels: In-Progress, Ready-to-Merge

#6107 Disable bg Scroll on Modal
  client/app/components/Modal.jsx
  client/package.json
  client/yarn.lock
Labels: In-Progress, Ready-to-Merge

#6117 Date selector
  app/assets/stylesheets/_commons.scss
  client/app/components/DateSelector.jsx
  client/app/hearingSchedule/actions.js
  client/app/hearingSchedule/components/BuildSchedule.jsx
  client/app/hearingSchedule/components/BuildScheduleUpload.jsx
  client/app/hearingSchedule/components/UploadDateSelector.jsx
  client/app/hearingSchedule/constants.js
  client/app/hearingSchedule/containers/BuildScheduleUploadContainer.jsx
  client/app/hearingSchedule/reducers.js
  client/test/karma/hearingSchedule/components/BuildScheduleUpload-test.js
Labels: In-Progress, Ready-to-Merge

#6122 Judge queue | Refactors AssignWidget
  client/app/components/AssignWidget.jsx
  client/app/queue/AssignedCasesPage.jsx
  client/app/queue/QueueActions.js
  client/app/queue/UnassignedCasesPage.jsx
  client/app/queue/components/AssignWidget.jsx
  client/app/queue/reducers.js
  client/app/queue/types.js
  client/app/queue/uiReducer/uiActions.js
  client/app/queue/uiReducer/uiConstants.js
  client/app/queue/uiReducer/uiReducer.js
Labels: In-Progress, Ready-to-Merge

#6128 Return all active attorneys in VACOLS
  app/controllers/users_controller.rb
  app/models/attorney.rb
  app/repositories/attorney_repository.rb
  client/app/queue/constants.js
  client/constants/USER_ROLE_TYPES.json
  spec/controllers/users_controller_spec.rb
Labels: In-Progress, Ready-to-Merge

#6132 adding methods for ro distribution used as helper methods
  app/services/hearing_schedule/ro_distribution.rb
  spec/services/hearing_schedule/ro_distribution_spec.rb
Labels: In-Progress, Ready-to-Merge

#6138 Adds Component to styleguide
  client/app/containers/StyleGuide/ComponentLinks.jsx
  client/app/containers/StyleGuide/StyleGuideDropdownButton.jsx
  client/app/containers/StyleGuide/StyleGuideIndex.jsx
  client/app/containers/StyleGuide/StyleGuideSearchableDropdown.jsx
Labels: In-Progress, Ready-to-Merge

#6140 establish_claim_spec.rb moved to facols!
  spec/models/establish_claim_spec.rb
Labels: In-Progress, Ready-to-Merge

#6127 Allow closing only the compensation issues for a RAMP VACOLS appeal
  app/mappers/issue_mapper.rb
  app/models/issue.rb
  app/models/legacy_appeal.rb
  app/models/ramp_closed_appeal.rb
  app/models/ramp_election_intake.rb
  app/services/appeal_repository.rb
  db/migrate/20180703225343_add_partial_closure_issue_ids.rb
  db/migrate/20180705173803_add_closed_on_to_ramp_closed_appeals.rb
  db/schema.rb
  spec/factories/vacols/case.rb
  spec/feature/intake/ramp_election_spec.rb
  spec/models/appeal_series_alerts_spec.rb
  spec/models/legacy_appeal_spec.rb
  spec/models/ramp_closed_appeal_spec.rb
  spec/models/ramp_election_intake_spec.rb
Labels: In-Progress, Ready-to-Merge

#6126 Review option data retained for AMA
  app/models/ama_review.rb
  app/models/appeal_intake.rb
  app/models/higher_level_review_intake.rb
  app/models/supplemental_claim_intake.rb
  client/app/intake/components/SelectClaimant.jsx
  client/app/intake/pages/higherLevelReview/review.jsx
  client/app/intake/reducers/appeal.js
  client/app/intake/reducers/higherLevelReview.js
  client/app/intake/reducers/supplementalClaim.js
  spec/feature/intake/appeal_spec.rb
  spec/feature/intake/higher_level_review_spec.rb
  spec/feature/intake/supplemental_claim_spec.rb
  spec/models/higher_level_review_spec.rb
Labels: In-Progress, Ready-to-Merge

#6125 Judges | (Re)assign cases | Confirmation
  client/app/queue/AssignedCasesPage.jsx
  client/app/queue/UnassignedCasesPage.jsx
  client/app/queue/components/AssignWidget.jsx
  client/app/queue/types.js
Labels: In-Progress, Ready-to-Merge

#6056 Queue | use appealId instead of vacolsId
  client/app/queue/AddEditIssueView.jsx
  client/app/queue/AssignedCasesPage.jsx
  client/app/queue/AttorneyTaskTable.jsx
  client/app/queue/BeaamTable.jsx
  client/app/queue/CaseDetailsView.jsx
  client/app/queue/CaseSnapshot.jsx
  client/app/queue/CaseTitle.jsx
  client/app/queue/EvaluateDecisionView.jsx
  client/app/queue/JudgeAssignTaskListView.jsx
  client/app/queue/JudgeReviewTaskTable.jsx
  client/app/queue/QueueActions.js
  client/app/queue/QueueApp.jsx
  client/app/queue/QueueLoadingScreen.jsx
  client/app/queue/ReaderLink.jsx
  client/app/queue/SelectDispositionsView.jsx
  client/app/queue/SubmitDecisionView.jsx
  client/app/queue/components/DecisionViewBase.jsx
  client/app/queue/components/JudgeStartCheckoutFlowDropdown.jsx
  client/app/queue/components/SelectCheckoutFlowDropdown.jsx
  client/app/queue/components/SelectIssueDispositionDropdown.jsx
  client/app/queue/reducers.js
  client/app/queue/types.js
  client/app/queue/uiReducer/uiActions.js
  client/app/queue/utils.js
  client/test/karma/queue/QueueLoadingScreen-test.js
  spec/feature/queue/checkout_flows_spec.rb
Labels: In-Progress

#6121 Endpoint to update task for a colocated user
  app/controllers/application_controller.rb
  app/controllers/tasks_controller.rb
  app/models/task.rb
  config/routes.rb
  scripts/enable_features_dev.rb
  spec/controllers/tasks_controller_spec.rb
  spec/factories/task.rb
  spec/factories/vacols/staff.rb
  spec/models/co_located_admin_action_spec.rb
Labels: In-Progress, Ready-to-Merge

#6134 Connect sidecar health check to /health-check endpoint
  Gemfile
  Gemfile.lock
  app/controllers/health_checks_controller.rb
  config/environments/staging.rb
  config/environments/test.rb
  spec/requests/health_checks_spec.rb
Labels: In-Progress, Ready-to-Merge

#6147 Fix overall quality in judge checkout
  app/mappers/queue_mapper.rb
  client/app/queue/EvaluateDecisionView.jsx
  spec/mappers/queue_mapper_spec.rb
Labels: In-Progress, Ready-to-Merge

#6141 File upload component
  client/app/components/FileUpload.jsx
  client/app/hearingSchedule/actions.js
  client/app/hearingSchedule/components/BuildScheduleUpload.jsx
  client/app/hearingSchedule/constants.js
  client/app/hearingSchedule/containers/BuildScheduleUploadContainer.jsx
  client/app/hearingSchedule/reducers.js
  client/test/karma/components/FileUpload-test.js
Labels: In-Progress, Ready-to-Merge

#6143 Removes error message from empty unassigned cases page
  client/COPY.json
  client/app/queue/UnassignedCasesPage.jsx
Labels: In-Progress, Ready-to-Merge

#6139 Queue | Fix validating new issue dispositions
  client/app/queue/SelectDispositionsView.jsx
Labels: In-Progress, Ready-to-Merge

#6157 Move Intake tests to FACOLS
  spec/feature/intake/appeal_spec.rb
  spec/feature/intake/higher_level_review_spec.rb
  spec/feature/intake/intake_manager_spec.rb
  spec/feature/intake/intake_spec.rb
  spec/feature/intake/intake_stats_spec.rb
  spec/feature/intake/ramp_election_spec.rb
  spec/feature/intake/ramp_refiling_spec.rb
  spec/feature/intake/supplemental_claim_spec.rb
  spec/models/appeal_intake_spec.rb
  spec/models/claimant_spec.rb
  spec/models/higher_level_review_intake_spec.rb
  spec/models/higher_level_review_spec.rb
  spec/models/intake_spec.rb
  spec/models/intake_stats_spec.rb
  spec/models/legacy_appeal_spec.rb
  spec/models/ramp_closed_appeal_spec.rb
  spec/models/ramp_election_intake_spec.rb
  spec/models/ramp_election_rollback_spec.rb
  spec/models/ramp_election_spec.rb
  spec/models/ramp_issue_spec.rb
  spec/models/ramp_refiling_intake_spec.rb
  spec/models/ramp_refiling_spec.rb
  spec/models/rating_issue_spec.rb
  spec/models/supplemental_claim_intake_spec.rb
  spec/models/supplemental_claim_spec.rb
Labels: In-Progress

#6160 Remove all relations between ramp election and ramp refiling
  app/models/ramp_election.rb
  app/models/ramp_refiling.rb
  spec/models/ramp_election_spec.rb
Labels: In-Progress, Ready-to-Merge

#6154 Change tasks controller create action to allow creation of multiple t…
  app/controllers/tasks_controller.rb
  app/models/tasks/co_located_admin_action.rb
  spec/controllers/tasks_controller_spec.rb
  spec/models/co_located_admin_action_spec.rb
Labels: In-Progress, Ready-to-Merge

#6061 Allow ROs to have non-availability dates
  app/models/hearings/ro_non_availability.rb
  app/services/hearing_schedule/validate_ro_spreadsheet.rb
  spec/models/hearings/ro_non_availability_spec.rb
  spec/support/validRoSpreadsheet.xlsx
Labels: In-Progress, Ready-to-Merge

#6155 remove ramp election from refilings
  db/migrate/20180706224911_remove_ramp_election_from_refilings.rb
  db/schema.rb
Labels: In-Progress

#6066 RO allocations for hearing schedule
  app/models/regional_office.rb
  app/models/schedule_period.rb
  app/services/hearing_schedule/generate_hearing_days_schedule.rb
  spec/factories/allocation.rb
  spec/factories/vacols/travel_board_schedule.rb
  spec/fake_date_helper.rb
  spec/services/hearing_schedule/generate_hearing_days_schedule_spec.rb
Labels: In-Progress, Ready-to-Merge

#6164 Anya/6151 hold duration
  app/controllers/tasks_controller.rb
  app/models/task.rb
  db/migrate/20180710144303_add_on_hold_duration_to_tasks.rb
  db/schema.rb
  spec/controllers/tasks_controller_spec.rb
  spec/models/co_located_admin_action_spec.rb
Labels: In-Progress, Ready-to-Merge

#6161 Adds the field judge_css_id to User
  app/models/user.rb
  spec/controllers/users_controller_spec.rb
Labels: In-Progress, Ready-to-Merge

#6176 Add end product establishment table and create on performing
  app/models/end_product_establishment.rb
  app/models/higher_level_review.rb
  app/models/ramp_review.rb
  app/models/supplemental_claim.rb
  db/migrate/20180710214914_create_end_product_establishments.rb
  db/schema.rb
  spec/models/end_product_establishment_spec.rb
Labels: In-Progress

#6175 Add dep on immutable to resolve peer dependency from react-draft-wysiwyg
  client/package.json
  client/yarn.lock
Labels: In-Progress, Ready-to-Merge

#6178 Claimant copy change
  client/app/intake/components/SelectClaimant.jsx
Labels: In-Progress, Ready-to-Merge

#6142 Flow 2 | View Schedule | View Schedule List
  app/controllers/hearings/hearing_day_controller.rb
  app/mappers/hearing_day_mapper.rb
  app/views/hearing_schedule/index.html.erb
  client/COPY.json
  client/app/components/BasicDateRangeSelector.jsx
  client/app/hearingSchedule/HearingScheduleApp.jsx
  client/app/hearingSchedule/actions.js
  client/app/hearingSchedule/components/BuildSchedule.jsx
  client/app/hearingSchedule/components/BuildScheduleUpload.jsx
  client/app/hearingSchedule/components/ListSchedule.jsx
  client/app/hearingSchedule/components/LoadingScreen.jsx
  client/app/hearingSchedule/components/UploadDateSelector.jsx
  client/app/hearingSchedule/constants.js
  client/app/hearingSchedule/containers/ListScheduleContainer.jsx
  client/app/hearingSchedule/reducers.js
  config/routes.rb
  spec/requests/hearing_day_spec.rb
Labels: In-Progress, Ready-to-Merge

#6173 Removing loading screen
  client/app/hearingSchedule/HearingScheduleApp.jsx
  client/app/hearingSchedule/components/LoadingScreen.jsx
  client/app/hearingSchedule/containers/BuildScheduleContainer.jsx
Labels: In-Progress, Ready-to-Merge

#6179 Mwf update readme
  README.md
Labels: In-Progress, Ready-to-Merge

#6156 Upload backend functionality
  app/controllers/hearings/schedule_periods_controller.rb
  client/app/hearingSchedule/HearingScheduleApp.jsx
  client/app/hearingSchedule/actions.js
  client/app/hearingSchedule/components/BuildSchedule.jsx
  client/app/hearingSchedule/components/BuildScheduleUpload.jsx
  client/app/hearingSchedule/components/ShowSchedulePeriod.jsx
  client/app/hearingSchedule/constants.js
  client/app/hearingSchedule/containers/BuildScheduleUploadContainer.jsx
  client/app/hearingSchedule/containers/ShowSchedulePeriodContainer.jsx
  client/app/hearingSchedule/reducers.js
  config/routes.rb
  spec/controllers/hearings/schedule_periods_controller_spec.rb
Labels: In-Progress, Ready-to-Merge

#6182 Checking access on a per user basis for BEAAM
  app/controllers/appeals_controller.rb
  app/controllers/beaam_appeals_controller.rb
Labels: In-Progress, Ready-to-Merge

#6153 Removes console error table footer row
  client/app/components/Table.jsx
Labels: In-Progress, Ready-to-Merge

#6159 Move case details test to FACOLS
  spec/controllers/legacy_tasks_controller_spec.rb
  spec/controllers/tasks_controller_spec.rb
  spec/controllers/users_controller_spec.rb
  spec/factories/vacols/case_hearing.rb
  spec/factories/vacols/staff.rb
  spec/feature/queue/case_details_spec.rb
  spec/repositories/user_repository_spec.rb
Labels: In-Progress, Ready-to-Merge

#6180 backfill end product establishments during ramp election syncs
  app/models/end_product_establishment.rb
  app/models/ramp_election.rb
  app/models/ramp_review.rb
  spec/models/end_product_establishment_spec.rb
  spec/models/ramp_election_spec.rb
Labels: In-Progress, Ready-to-Merge

#6174 Queue | Set character limit for attorney case review comments
  app/models/attorney_case_review.rb
  client/app/components/TextareaField.jsx
  client/app/queue/SubmitDecisionView.jsx
  client/app/queue/constants.js
  spec/feature/queue/checkout_flows_spec.rb
Labels: In-Progress, Ready-to-Merge

#6190 Review assignments page
  app/controllers/hearings/schedule_periods_controller.rb
  client/COPY.json
  client/app/hearingSchedule/HearingScheduleApp.jsx
  client/app/hearingSchedule/actions.js
  client/app/hearingSchedule/components/ReviewAssignments.jsx
  client/app/hearingSchedule/components/ShowSchedulePeriod.jsx
  client/app/hearingSchedule/constants.js
  client/app/hearingSchedule/containers/ReviewAssignmentsContainer.jsx
  client/app/hearingSchedule/containers/ShowSchedulePeriodContainer.jsx
  client/app/hearingSchedule/reducers.js
  client/test/karma/hearingSchedule/components/ReviewAssignments-test.js
  config/routes.rb
Labels: In-Progress, Ready-to-Merge

#6172 Migrate checkout flows tests to FACOLS
  spec/feature/queue/checkout_flows_spec.rb
Labels: In-Progress, Ready-to-Merge

#6103 Spreadsheet Validation | co-non-availability-days
  app/models/hearings/co_non_availability.rb
  app/services/hearing_schedule/validate_ro_spreadsheet.rb
  spec/models/hearings/ro_non_availability_spec.rb
  spec/support/validRoSpreadsheet.xlsx
Labels: In-Progress, Ready-to-Merge

#6201 Remove breadcrumbs from queue
  client/COPY.json
  client/app/queue/CaseDetailsView.jsx
  client/app/queue/CaseListTable.jsx
  client/app/queue/EvaluateDecisionView.jsx
  client/app/queue/QueueApp.jsx
  client/app/queue/SelectDispositionsView.jsx
  client/app/queue/SelectRemandReasonsView.jsx
  client/app/queue/SubmitDecisionView.jsx
  client/app/queue/components/BreadcrumbManager.jsx
  client/app/queue/components/DecisionViewBase.jsx
  client/app/queue/components/JudgeStartCheckoutFlowDropdown.jsx
  client/app/queue/components/SelectCheckoutFlowDropdown.jsx
  client/app/queue/types.js
  client/app/queue/uiReducer/uiActions.js
  client/app/queue/uiReducer/uiConstants.js
  client/app/queue/uiReducer/uiReducer.js
  spec/feature/queue/checkout_flows_spec.rb
  spec/feature/queue/search_spec.rb
Labels: In-Progress, Ready-to-Merge

#5208 Add more information to case details power of attorney
  app/controllers/appeals_controller.rb
  app/models/appeal_series.rb
  app/models/appeal_series_alerts.rb
  app/models/form8.rb
  app/models/legacy_appeal.rb
  app/models/serializers/work_queue/appeal_serializer.rb
  app/models/serializers/work_queue/legacy_appeal_serializer.rb
  app/services/appeal_repository.rb
  client/app/queue/CaseDetailsView.jsx
  lib/fakes/data/appeal_data.rb
  lib/fakes/power_of_attorney_repository.rb
  lib/generators/appeal.rb
  lib/generators/legacy_appeal.rb
  spec/factories/vacols/case.rb
  spec/factories/vacols/correspondent.rb
  spec/models/appeal_series_spec.rb
  spec/services/appeals_repository_spec.rb
Labels: In-Progress, Ready-to-Merge

#6203 Confirm assignments modal
  client/COPY.json
  client/app/hearingSchedule/actions.js
  client/app/hearingSchedule/components/ReviewAssignments.jsx
  client/app/hearingSchedule/constants.js
  client/app/hearingSchedule/containers/ReviewAssignmentsContainer.jsx
  client/app/hearingSchedule/reducers.js
  client/test/karma/hearingSchedule/components/ReviewAssignments-test.js
Labels: In-Progress, Ready-to-Merge

#6198 Moving to include npm package via hash
  client/package.json
  client/yarn.lock
Labels: In-Progress, Ready-to-Merge

#6165 Fix asset pipeline to enable uploading sourcemaps
  .gitignore
  app/assets/javascripts/application.js
  app/assets/javascripts/dropdown.js
  app/assets/javascripts/webpack-loader.js.erb
  app/views/dispatch/establish_claims/work_assignments.html.erb
  app/views/layouts/application.html.erb
  app/views/test/users/index.html.erb
  client/app/manageEstablishClaim/ManageEstablishClaim.jsx
  client/app/test/TestUsers.jsx
  client/webpack.config.js
  config/environments/production.rb
  config/initializers/assets.rb
  spec/feature/intake/appeal_spec.rb
  spec/feature/log_in_as_user_spec.rb
Labels: In-Progress

#6144 Judges | Assign cases | Assign to 'Other'
  client/COPY.json
  client/app/queue/JudgeAssignTaskListView.jsx
  client/app/queue/QueueActions.js
  client/app/queue/components/AssignWidget.jsx
  client/app/queue/constants.js
  client/app/queue/reducers.js
  client/app/queue/types.js
  client/app/queue/uiReducer/uiActions.js
  client/app/queue/uiReducer/uiConstants.js
  client/app/queue/uiReducer/uiReducer.js
Labels: In-Progress, Ready-to-Merge

#6209 Queue | Annotates action creators with types
  client/app/queue/AddEditIssueView.jsx
  client/app/queue/QueueActions.js
  client/app/queue/types.js
Labels: In-Progress, Ready-to-Merge

#6217 Assignments table
  app/controllers/hearings/schedule_periods_controller.rb
  client/app/hearingSchedule/components/ReviewAssignments.jsx
  client/app/hearingSchedule/containers/ReviewAssignmentsContainer.jsx
  spec/controllers/hearings/schedule_periods_controller_spec.rb
Labels: In-Progress, Ready-to-Merge

#6220 Translated codes to values
  app/controllers/hearings/hearing_day_controller.rb
  app/mappers/hearing_day_mapper.rb
  app/models/hearing_day.rb
  app/models/hearing_rooms.rb
  app/models/serializers/hearings/hearing_day_create_serializer.rb
  app/models/serializers/hearings/hearing_day_serializer.rb
  app/models/vacols/case_hearing.rb
  client/app/hearingSchedule/components/ListSchedule.jsx
  spec/requests/hearing_day_spec.rb
Labels: In-Progress, Ready-to-Merge

#6228 VACOLS upload success page
  client/COPY.json
  client/app/hearingSchedule/actions.js
  client/app/hearingSchedule/components/BuildSchedule.jsx
  client/app/hearingSchedule/constants.js
  client/app/hearingSchedule/containers/BuildScheduleContainer.jsx
  client/app/hearingSchedule/containers/ReviewAssignmentsContainer.jsx
  client/app/hearingSchedule/reducers.js
  client/test/karma/hearingSchedule/components/BuildSchedule-test.js
Labels: In-Progress

#6227 Fetch non-availability days from schedule period
  app/models/schedule_period.rb
  app/services/hearing_schedule/generate_hearing_days_schedule.rb
  spec/services/hearing_schedule/generate_hearing_days_schedule_spec.rb
Labels: In-Progress

#6230 Cache schedule generated results for Hearing days
  app/models/schedule_period.rb
  app/services/hearing_schedule/ro_allocation.rb
  spec/models/schedule_period_spec.rb
  spec/services/hearing_schedule/generate_hearing_days_schedule_spec.rb
Labels: In-Progress, Ready-to-Merge

#6166 Queue | Add ability to sort by Days Waiting
  client/app/components/Table.jsx
  client/app/queue/AttorneyTaskTable.jsx
  client/app/queue/CaseDetail/CaseDetailReducer.js
  client/app/queue/QueueActions.js
  client/app/queue/components/AssignWidget.jsx
  client/app/queue/types/models.js
  client/app/queue/types/state.js
  client/app/queue/uiReducer/uiReducer.js
  client/app/queue/utils.js
  spec/feature/queue/task_queue_spec.rb
Labels: In-Progress, Ready-to-Merge

#6219 Updates to Readme
  README.md
Labels: In-Progress, Ready-to-Merge

#6237 Issue6202c
  client/app/hearingSchedule/components/BuildSchedule.jsx
  client/app/util/DateUtil.js
  client/test/karma/hearingSchedule/components/BuildSchedule-test.js
Labels: In-Progress, Ready-to-Merge

#6233 Hearing-Schedule Update feedback URL
  app/controllers/application_controller.rb
  client/app/hearingSchedule/HearingScheduleApp.jsx
Labels: In-Progress, Ready-to-Merge

#6241 Forking access check
  Gemfile
  Gemfile.lock
  app/services/external_api/bgs_service.rb
Labels: In-Progress

#6240 Fixing a bunch of frontend sentry errors
  client/app/components/Highlight.jsx
  client/app/queue/components/LegacyIssueListItem.jsx
  client/app/reader/Documents/DocumentsActions.js
  client/app/reader/Documents/DocumentsReducer.js
  client/app/reader/Pdf.jsx
  client/app/reader/PdfFile.jsx
  client/app/reader/PdfPage.jsx
  client/app/reader/PdfSidebar.jsx
  client/app/reader/SideBarIssueTags.jsx
  client/test/karma/reader/reducers/DocumentsReducer-test.js
  spec/feature/queue/ama_queue_spec.rb
Labels: In-Progress, Ready-to-Merge

#6242 Edit Docker preferences in README
  README.md
Labels: In-Progress, Ready-to-Merge

#6244 Judge Evaluate Decision | Fix case quality option ordering
  client/COPY.json
  client/app/queue/EvaluateDecisionView.jsx
  spec/feature/queue/checkout_flows_spec.rb
Labels: In-Progress, Ready-to-Merge

#6245 Case Details | Shows actions dropdown if the case is assigned to the user
  app/controllers/legacy_tasks_controller.rb
  client/app/queue/QueueLoadingScreen.jsx
Labels: In-Progress, Ready-to-Merge

#6252 Rename queue feature toggles to make more clear
  app/controllers/application_controller.rb
  app/views/queue/index.html.erb
  app/views/queue/show.html.erb
  client/app/queue/AssignedCasesPage.jsx
  client/app/queue/CaseSnapshot.jsx
  client/app/queue/UnassignedCasesPage.jsx
  scripts/enable_features_dev.rb
  spec/controllers/legacy_tasks_controller_spec.rb
  spec/controllers/tasks_controller_spec.rb
  spec/feature/queue/case_details_spec.rb
  spec/feature/queue/checkout_flows_spec.rb
Labels: In-Progress, Ready-to-Merge

#6255 Remove efolder_docs_api flag
  app/models/document.rb
  scripts/enable_features_dev.rb
  spec/models/document_spec.rb
Labels: In-Progress, Ready-to-Merge

#6193 Queue | Add document ID validations during attorney check out
  client/COPY.json
  client/app/queue/AddEditIssueView.jsx
  client/app/queue/AttorneyTaskTable.jsx
  client/app/queue/SubmitDecisionView.jsx
  client/app/queue/components/SelectIssueDispositionDropdown.jsx
  client/app/queue/constants.js
  client/app/queue/types/models.js
  client/app/queue/utils.js
  spec/feature/queue/checkout_flows_spec.rb
Labels: In-Progress, Ready-to-Merge

#6248 AssignWidget | Extracts selected tasks logic
  client/app/queue/AssignedCasesPage.jsx
  client/app/queue/UnassignedCasesPage.jsx
  client/app/queue/components/AssignWidget.jsx
  client/app/queue/utils.js
Labels: In-Progress, Ready-to-Merge

#6256 Remove efolder v1 service and VBMS old service
  app/models/document.rb
  app/services/external_api/efolder_service.rb
  app/services/external_api/vbms_service.rb
  scripts/enable_features_dev.rb
  spec/feature/reader/reader_spec.rb
  spec/models/document_spec.rb
  spec/services/external_api/efolder_service_spec.rb
Labels: In-Progress, Ready-to-Merge

#6261 Remove dispatch feature toggles
  scripts/enable_features_dev.rb
  spec/feature/api/v1/appeals_spec.rb
  spec/feature/api/v2/appeals_spec.rb
  spec/jobs/create_establish_claim_tasks_job_spec.rb
Labels: In-Progress, Ready-to-Merge

#6260 AssignWidget | Removes unused props
  client/app/queue/components/AssignWidget.jsx
Labels: In-Progress, Ready-to-Merge

#6262 Printing program for debug purposes
  client/app/queue/components/LegacyIssueListItem.jsx
  client/app/queue/utils.js
Labels: In-Progress, Ready-to-Merge

#6265 Clean up queue_welcome_gate
  scripts/enable_features_dev.rb
Labels: In-Progress, Ready-to-Merge

#6226 Add new file indicator
  app/controllers/appeals_controller.rb
  app/models/appeal.rb
  app/models/document.rb
  app/models/legacy_appeal.rb
  app/services/document_fetcher.rb
  client/app/components/RenderFunctions.jsx
  client/app/queue/CaseTitle.jsx
  client/app/queue/QueueActions.js
  client/app/queue/ReaderLink.jsx
  client/app/queue/components/NewFile.jsx
  client/app/queue/constants.js
  client/app/queue/reducers.js
  client/app/queue/types/models.js
  config/routes.rb
  lib/generators/document.rb
  spec/feature/queue/ama_queue_spec.rb
  spec/feature/queue/case_details_spec.rb
  spec/services/document_fetcher_spec.rb
Labels: In-Progress

#6264 Creates IDT auth framework
  app/controllers/idt/api/v1/appeals_controller.rb
  app/controllers/idt/api/v1/tokens_controller.rb
  app/controllers/idt/authentications_controller.rb
  app/models/idt/token.rb
  config/routes.rb
  lib/caseflow/error.rb
  spec/controllers/idt/api/appeals_controller_spec.rb
  spec/controllers/idt/authentications_controller_spec.rb
  spec/models/idt/token.rb
Labels: In-Progress, Ready-to-Merge

#6266 Remove queue_phase_two and judge_queue feature toggles because they w…
  app/controllers/application_controller.rb
  app/controllers/case_reviews_controller.rb
  app/controllers/issues_controller.rb
  app/views/queue/index.html.erb
  app/views/queue/show.html.erb
  client/app/queue/AttorneyTaskTable.jsx
  client/app/queue/CaseSnapshot.jsx
  scripts/enable_features_dev.rb
  spec/controllers/case_reviews_controller_spec.rb
  spec/controllers/home_controller_spec.rb
  spec/controllers/issues_controller_spec.rb
  spec/controllers/legacy_tasks_controller_spec.rb
  spec/controllers/tasks_controller_spec.rb
  spec/feature/queue/case_details_spec.rb
  spec/feature/queue/checkout_flows_spec.rb
  spec/feature/queue/search_spec.rb
  spec/feature/queue/task_queue_spec.rb
Labels: In-Progress, Ready-to-Merge

#6281 Queue | fix ime / vha document id validation
  client/app/queue/utils.js
  spec/feature/queue/checkout_flows_spec.rb
Labels: In-Progress, Ready-to-Merge

#6282 update karma to use local webpack config
  client/karma.conf.js
Labels: In-Progress, Ready-to-Merge

#6283 Adding organization
  app/models/organization.rb
  app/models/task.rb
  app/models/user.rb
  db/migrate/20180719153039_create_organizations_table.rb
  db/migrate/20180719153446_make_assigned_to_on_task_polymorphic.rb
  db/schema.rb
Labels: In-Progress, Ready-to-Merge

#6284 Remove search flag
  spec/feature/reader/reader_spec.rb
Labels: In-Progress, Ready-to-Merge

#6267 Queue | Adds endpoint to get tasks by VACOLS ID
  app/controllers/appeals_controller.rb
  app/controllers/concerns/errors.rb
  app/controllers/legacy_tasks_controller.rb
  app/controllers/tasks_controller.rb
  app/models/queues/legacy_work_queue.rb
  app/models/vacols/case_assignment.rb
  app/repositories/queue_repository.rb
  client/constants/ROLES.json
  config/routes.rb
  spec/controllers/appeals_controller_spec.rb
  spec/factories/user.rb
  spec/models/queues/legacy_work_queue_spec.rb
Labels: In-Progress, Ready-to-Merge

#6292 Queue | Hide CaseSnapshot dropdown in EvaluateDecisionView
  client/app/queue/CaseSnapshot.jsx
  client/app/queue/EvaluateDecisionView.jsx
Labels: In-Progress, Ready-to-Merge

#6289 removes redirect
  app/controllers/home_controller.rb
  spec/controllers/home_controller_spec.rb
  spec/feature/queue/case_details_spec.rb
  spec/feature/queue/checkout_flows_spec.rb
Labels: In-Progress

#6293 Improving Test User Page
  app/controllers/test/users_controller.rb
  client/app/test/TestUsers.jsx
  config/routes.rb
  db/seeds.rb
  lib/tasks/local/vacols.rake
Labels: In-Progress, Ready-to-Merge

#6272 Validation request fixes
  app/models/end_product.rb
  app/views/intake_stats/show.html.erb
  client/app/help/components/IntakeHelp.jsx
  client/app/intake/constants.js
  client/app/intake/pages/higherLevelReview/completed.jsx
  client/app/intake/pages/rampElection/review.jsx
  client/app/intake/pages/rampRefiling/finish.jsx
  client/app/intake/pages/search.jsx
  spec/feature/intake/higher_level_review_spec.rb
  spec/feature/intake/intake_spec.rb
  spec/feature/intake/intake_stats_spec.rb
  spec/feature/intake/ramp_election_spec.rb
  spec/feature/intake/ramp_refiling_spec.rb
  spec/models/higher_level_review_intake_spec.rb
  spec/models/higher_level_review_spec.rb
  spec/models/ramp_refiling_spec.rb
Labels: In-Progress, Ready-to-Merge

#6238 Implmenet endpoint to allow co-located admin to complete the task
  app/models/task.rb
  spec/controllers/tasks_controller_spec.rb
  spec/models/co_located_admin_action_spec.rb
Labels: In-Progress, Ready-to-Merge

#6304 Change Vacols location for BVA dispatch
  app/models/legacy_appeal.rb
  spec/models/judge_case_review_spec.rb
Labels: In-Progress, Ready-to-Merge

#6297 Added FY2019 hearing schedule to CaseHearing and TravelBoard FACOLS data
  local/vacols/VACOLS::CaseHearing_dump.csv
  local/vacols/VACOLS::TravelBoardSchedule_dump.csv
Labels: In-Progress, Ready-to-Merge

#6194 Imports spreadsheet
  app/controllers/hearings/schedule_periods_controller.rb
  app/models/hearings/allocation.rb
  app/models/judge_schedule_period.rb
  app/models/ro_schedule_period.rb
  app/services/base64_service.rb
  client/app/components/FileUpload.jsx
  client/app/hearingSchedule/components/BuildScheduleUpload.jsx
  client/app/hearingSchedule/containers/BuildScheduleUploadContainer.jsx
  client/test/karma/components/FileUpload-test.js
  spec/controllers/hearings/schedule_periods_controller_spec.rb
  spec/factories/judge_schedule_period.rb
  spec/factories/ro_schedule_period.rb
  spec/models/hearings/allocation_spec.rb
  spec/models/hearings/co_non_availability_spec.rb
  spec/models/hearings/judge_non_availability_spec.rb
  spec/models/hearings/ro_non_availability_spec.rb
  spec/models/judge_schedule_period_spec.rb
  spec/models/ro_schedule_period_spec.rb
  spec/models/schedule_period_spec.rb
  spec/services/hearing_schedule/generate_hearing_days_schedule_spec.rb
Labels: In-Progress

#6300 Queue | Fix space in Remand Reasons text
  client/COPY.json
  client/app/queue/SelectRemandReasonsView.jsx
Labels: In-Progress, Ready-to-Merge

#6306 Table | Fix sort direction indicators
  client/app/components/Table.jsx
  client/app/queue/AttorneyTaskTable.jsx
  spec/feature/queue/task_queue_spec.rb
Labels: In-Progress, Ready-to-Merge

#6310 Hearing-Schedule removed semi-colon
  client/app/hearingSchedule/containers/ListScheduleContainer.jsx
Labels: In-Progress, Ready-to-Merge

#6316 Removing CO allocation from spreadsheet template
  app/models/hearings/allocation.rb
  app/services/hearing_schedule/get_spreadsheet_data.rb
  app/services/hearing_schedule/validate_ro_spreadsheet.rb
  public/ROAssignmentTemplate.xlsx
  spec/services/hearing_schedule/validate_ro_spreadsheet_spec.rb
  spec/support/allocationDuplicateRo.xlsx
  spec/support/allocationTemplateNotFollowed.xlsx
  spec/support/allocationWrongCoLocation.xlsx
  spec/support/allocationWrongDataType.xlsx
  spec/support/validRoSpreadsheet.xlsx
Labels: In-Progress, Ready-to-Merge

#6313 Loading spinners
  app/controllers/hearings/schedule_periods_controller.rb
  client/app/hearingSchedule/containers/BuildScheduleContainer.jsx
  client/app/hearingSchedule/containers/ReviewAssignmentsContainer.jsx
  config/routes.rb
Labels: In-Progress, Ready-to-Merge

#6088 VACOLS::Case: Adds error log statement
  app/models/vacols/case.rb
  app/repositories/queue_repository.rb
Labels: In-Progress, Ready-to-Merge

#6263 Queue | Move state.queue.loadedQueue tasks/appeals into state.queue
  client/app/queue/AssignedCasesPage.jsx
  client/app/queue/AttorneyTaskListView.jsx
  client/app/queue/AttorneyTaskTable.jsx
  client/app/queue/BeaamTable.jsx
  client/app/queue/CaseDetailsView.jsx
  client/app/queue/CaseSnapshot.jsx
  client/app/queue/EvaluateDecisionView.jsx
  client/app/queue/JudgeAssignTaskListView.jsx
  client/app/queue/JudgeReviewTaskListView.jsx
  client/app/queue/JudgeReviewTaskTable.jsx
  client/app/queue/QueueActions.js
  client/app/queue/QueueApp.jsx
  client/app/queue/QueueLoadingScreen.jsx
  client/app/queue/UnassignedCasesPage.jsx
  client/app/queue/components/JudgeStartCheckoutFlowDropdown.jsx
  client/app/queue/components/SelectCheckoutFlowDropdown.jsx
  client/app/queue/reducers.js
  client/app/queue/selectors.js
  client/app/queue/types/models.js
  client/app/queue/types/state.js
  client/app/queue/uiReducer/uiActions.js
  client/app/queue/uiReducer/uiConstants.js
  client/app/queue/uiReducer/uiReducer.js
  client/app/queue/utils.js
Labels: In-Progress, Ready-to-Merge

#6320 API | Fixes added_by_css_id and removes unused field
  app/models/vacols/case_assignment.rb
Labels: In-Progress, Ready-to-Merge

#6291 Adding VSO as an organization and a new organizational tasks controller
  Gemfile
  Gemfile.lock
  app/controllers/organizations/tasks_controller.rb
  app/controllers/organizations_controller.rb
  app/mappers/power_of_attorney_mapper.rb
  app/models/organization.rb
  app/models/organizations/vso.rb
  app/models/tasks/vso_task.rb
  app/services/external_api/bgs_service.rb
  config/routes.rb
  db/seeds.rb
  lib/fakes/bgs_service.rb
  spec/controllers/organizations/tasks_controller_spec.rb
  spec/mappers/power_of_attorney_mapper_spec.rb
  spec/models/organization_spec.rb
  spec/models/vso_spec.rb
Labels: In-Progress

#6328 Queue | Add ability to sort by days waiting for Judge queues
  client/app/queue/JudgeAssignTaskTable.jsx
  client/app/queue/JudgeReviewTaskTable.jsx
  client/app/queue/utils.js
Labels: In-Progress, Ready-to-Merge

#6323 VACOLS Upload Success Page
  client/COPY.json
  client/app/hearingSchedule/components/BuildSchedule.jsx
Labels: In-Progress, Ready-to-Merge

#6331 Add appeal data to the tasks controller
  app/controllers/tasks_controller.rb
  app/models/serializers/work_queue/task_serializer.rb
  spec/controllers/tasks_controller_spec.rb
Labels: In-Progress, Ready-to-Merge

#6332 Seed local environment with sample ama tasks
  .rubocop.yml
  Gemfile
  Gemfile.lock
  app/models/task.rb
  app/models/tasks/attorney_task.rb
  app/models/tasks/co_located_admin_action.rb
  app/models/tasks/judge_task.rb
  db/migrate/20180724145953_add_parent_id_to_tasks.rb
  db/schema.rb
  db/seeds.rb
  spec/factories/task.rb
Labels: In-Progress, Ready-to-Merge

#6329 Queue | Fix sorting attorney tasks by type
  client/app/components/Table.jsx
  client/app/queue/AttorneyTaskTable.jsx
  spec/feature/queue/task_queue_spec.rb
Labels: In-Progress, Ready-to-Merge

#6338 Queue | Fix backwards navigation in checkout flow
  client/app/queue/EvaluateDecisionView.jsx
  client/app/queue/QueueApp.jsx
  client/app/queue/SubmitDecisionView.jsx
  client/app/queue/components/DecisionViewBase.jsx
Labels: In-Progress, Ready-to-Merge

#6334 Queue | Only update remand reasons in redux on go to next page
  client/app/queue/SelectRemandReasonsView.jsx
  client/app/queue/components/IssueRemandReasonsOptions.jsx
Labels: In-Progress, Ready-to-Merge

#6325 Persist derived hearing schedule for schedule period
  app/controllers/hearings/hearing_day_controller.rb
  app/controllers/hearings/schedule_periods_controller.rb
  app/mappers/hearing_day_mapper.rb
  app/models/hearing_day.rb
  app/models/judge_schedule_period.rb
  app/models/ro_schedule_period.rb
  app/models/schedule_period.rb
  app/models/vacols/case_hearing.rb
  app/repositories/hearing_day_repository.rb
  client/app/hearingSchedule/containers/ListScheduleContainer.jsx
  spec/controllers/hearings/schedule_periods_controller_spec.rb
  spec/models/hearing_day_spec.rb
Labels: In-Progress, Ready-to-Merge

#6342 Queue API | Fixes the assignee of created and updated tasks
  app/controllers/legacy_tasks_controller.rb
Labels: In-Progress, Ready-to-Merge

#6349 update yarn lock to FE latest
  client/package.json
  client/yarn.lock
Labels: In-Progress

#6348 Rename CoLocatedAdminAction to ColocatedTask to stay consistent with …
  app/controllers/tasks_controller.rb
  app/models/queues/attorney_queue.rb
  app/models/queues/co_located_admin_queue.rb
  app/models/queues/colocated_queue.rb
  app/models/tasks/colocated_task.rb
  spec/controllers/tasks_controller_spec.rb
  spec/factories/task.rb
  spec/models/colocated_task_spec.rb
  spec/models/queues/attorney_queue_spec.rb
Labels: In-Progress, Ready-to-Merge

#6363 Change AMA date
  app/models/ama_review.rb
Labels: In-Progress, Ready-to-Merge

#6327 Upload validation and error handling
  app/controllers/hearings/schedule_periods_controller.rb
  app/models/judge_schedule_period.rb
  app/models/ro_schedule_period.rb
  app/models/schedule_period.rb
  app/services/base64_service.rb
  app/services/hearing_schedule/validate_judge_spreadsheet.rb
  app/services/hearing_schedule/validate_ro_spreadsheet.rb
  client/app/components/FileUpload.jsx
  client/app/hearingSchedule/actions.js
  client/app/hearingSchedule/components/BuildScheduleUpload.jsx
  client/app/hearingSchedule/constants.js
  client/app/hearingSchedule/containers/BuildScheduleUploadContainer.jsx
  client/app/hearingSchedule/reducers.js
  client/test/karma/hearingSchedule/components/BuildScheduleUpload-test.js
  spec/controllers/hearings/schedule_periods_controller_spec.rb
  spec/factories/judge_schedule_period.rb
  spec/factories/ro_schedule_period.rb
  spec/models/hearing_day_spec.rb
  spec/models/judge_schedule_period_spec.rb
  spec/models/schedule_period_spec.rb
  spec/services/hearing_schedule/generate_hearing_days_schedule_spec.rb
  spec/services/hearing_schedule/validate_judge_spreadsheet_spec.rb
  spec/services/hearing_schedule/validate_ro_spreadsheet_spec.rb
  spec/support/blankRoSpreadsheet.xlsx
  spec/support/coDuplicateDates.xlsx
  spec/support/coOutOfRange.xlsx
  spec/support/coWrongDataType.xlsx
  spec/support/roDuplicateDates.xlsx
  spec/support/roNotInSystem.xlsx
  spec/support/roNotListed.xlsx
  spec/support/roOutOfRange.xlsx
  spec/support/roTemplateNotFollowed.xlsx
  spec/support/roWrongDataType.xlsx
Labels: In-Progress

#6192 Remove double writing of end product reference id on reviews
  app/controllers/higher_level_reviews_controller.rb
  app/controllers/supplemental_claims_controller.rb
  app/models/ama_review.rb
  app/models/end_product_establishment.rb
  app/models/higher_level_review.rb
  app/models/ramp_election.rb
  app/models/ramp_refiling.rb
  app/models/ramp_review.rb
  app/models/supplemental_claim.rb
  lib/fakes/bgs_service.rb
  spec/factories/ramp_election.rb
  spec/feature/intake/higher_level_review_spec.rb
  spec/feature/intake/intake_stats_spec.rb
  spec/feature/intake/ramp_election_spec.rb
  spec/feature/intake/ramp_refiling_spec.rb
  spec/feature/intake/supplemental_claim_spec.rb
  spec/jobs/ramp_election_sync_job_spec.rb
  spec/models/end_product_establishment_spec.rb
  spec/models/higher_level_review_intake_spec.rb
  spec/models/higher_level_review_spec.rb
  spec/models/ramp_closed_appeal_spec.rb
  spec/models/ramp_election_intake_spec.rb
  spec/models/ramp_election_rollback_spec.rb
  spec/models/ramp_election_spec.rb
  spec/models/ramp_refiling_intake_spec.rb
  spec/models/ramp_refiling_spec.rb
  spec/models/supplemental_claim_intake_spec.rb
  spec/models/supplemental_claim_spec.rb
Labels: In-Progress

#6372 Queue | limit document id field length
  client/app/queue/SubmitDecisionView.jsx
  client/app/queue/constants.js
  spec/feature/queue/checkout_flows_spec.rb
Labels: In-Progress

#6366 Added validations to not update unless finalized == false and cached …
  app/controllers/hearings/schedule_periods_controller.rb
  app/models/schedule_period.rb
  spec/controllers/hearings/schedule_periods_controller_spec.rb
Labels: In-Progress, Ready-to-Merge

#6322 Refactoring tasks and appeals
  client/COPY.json
  client/app/components/Table.jsx
  client/app/queue/AssignedCasesPage.jsx
  client/app/queue/AttorneyTaskListView.jsx
  client/app/queue/AttorneyTaskTable.jsx
  client/app/queue/BeaamAppealListView.jsx
  client/app/queue/BeaamTable.jsx
  client/app/queue/CaseSnapshot.jsx
  client/app/queue/JudgeAssignTaskListView.jsx
  client/app/queue/JudgeAssignTaskTable.jsx
  client/app/queue/JudgeReviewTaskListView.jsx
  client/app/queue/JudgeReviewTaskTable.jsx
  client/app/queue/UnassignedCasesPage.jsx
  client/app/queue/components/TaskTable.jsx
  client/app/queue/reducers.js
  client/app/queue/selectors.js
  client/app/queue/types/models.js
  client/app/queue/types/state.js
  spec/feature/queue/checkout_flows_spec.rb
  spec/feature/queue/task_queue_spec.rb
Labels: In-Progress, Ready-to-Merge

#6382 Use date assigned to location for judges
  app/models/legacy_tasks/judge_legacy_task.rb
  spec/models/legacy_tasks/judge_legacy_task_spec.rb
Labels: In-Progress, Ready-to-Merge

#6386 Add decision date to non-rated issues
  app/assets/stylesheets/_intake.scss
  app/models/request_issue.rb
  client/app/intake/actions/ama.js
  client/app/intake/components/NonRatedIssues.jsx
  client/app/intake/constants.js
  client/app/intake/pages/appeal/finish.jsx
  client/app/intake/pages/higherLevelReview/finish.jsx
  client/app/intake/pages/supplementalClaim/finish.jsx
  client/app/intake/reducers/appeal.js
  client/app/intake/reducers/higherLevelReview.js
  client/app/intake/reducers/supplementalClaim.js
  client/app/intake/util/index.js
  db/migrate/20180710180018_add_decision_date_to_request_issues.rb
  db/schema.rb
  spec/feature/intake/appeal_spec.rb
  spec/feature/intake/higher_level_review_spec.rb
  spec/feature/intake/supplemental_claim_spec.rb
  spec/models/appeal_intake_spec.rb
  spec/models/higher_level_review_intake_spec.rb
  spec/models/higher_level_review_spec.rb
  spec/models/supplemental_claim_intake_spec.rb
  spec/models/supplemental_claim_spec.rb
Labels: In-Progress, Ready-to-Merge

#6373 adds real appeal data to endpoint
  app/controllers/idt/api/v1/appeals_controller.rb
  app/controllers/idt/api/v1/tokens_controller.rb
  app/controllers/idt/authentications_controller.rb
  app/models/idt/token.rb
  app/models/legacy_appeal.rb
  app/models/serializers/idt/v1/appeal_serializer.rb
  spec/controllers/idt/api/appeals_controller_spec.rb
  spec/controllers/idt/authentications_controller_spec.rb
  spec/models/idt/token.rb
Labels: In-Progress, Ready-to-Merge

#6378 Return AMA tasks for a judge
  app/controllers/tasks_controller.rb
  app/models/appeal.rb
  app/models/legacy_appeal.rb
  app/models/queues/judge_queue.rb
  app/models/serializers/work_queue/task_serializer.rb
  spec/controllers/tasks_controller_spec.rb
  spec/factories/appeal.rb
  spec/factories/task.rb
Labels: In-Progress, Ready-to-Merge

#6399 Fixing reader link
  app/models/serializers/idt/v1/appeal_serializer.rb
  client/app/queue/components/TaskTable.jsx
Labels: In-Progress, Ready-to-Merge

#6359 update pointer to webpack for local tests
  client/package.json
  client/webpack.hot.config.js
  config/initializers/react_on_rails.rb
  spec/rails_helper.rb
Labels: In-Progress, Ready-to-Merge

#6398 Moving tests to FACOLS
  spec/models/claim_establishment_spec.rb
  spec/models/establish_claim_spec.rb
Labels: In-Progress, Ready-to-Merge

#6394 Anya/update colocated seeds
  app/models/appeal.rb
  app/models/serializers/idt/v1/appeal_serializer.rb
  app/models/serializers/work_queue/task_serializer.rb
  db/seeds.rb
  spec/controllers/idt/api/appeals_controller_spec.rb
  spec/controllers/tasks_controller_spec.rb
  spec/factories/task.rb
Labels: In-Progress, Ready-to-Merge

#6406 Fix feature toggle bug
  app/controllers/intakes_controller.rb
  app/models/appeal_intake.rb
  app/models/higher_level_review_intake.rb
  app/models/intake.rb
  app/models/ramp_election_intake.rb
  app/models/ramp_refiling_intake.rb
  app/models/supplemental_claim_intake.rb
  app/views/intakes/index.html.erb
  spec/controllers/intakes_controller_spec.rb
  spec/feature/intake/appeal_spec.rb
Labels: In-Progress, Ready-to-Merge

#6387 Implement download link
  app/controllers/hearings/schedule_periods_controller.rb
  client/app/hearingSchedule/components/BuildSchedule.jsx
  config/brakeman.ignore
  config/routes.rb
  spec/controllers/hearings/schedule_periods_controller_spec.rb
Labels: In-Progress, Ready-to-Merge

#6409 Change of home page
  app/controllers/test/users_controller.rb
  client/COPY.json
  client/app/hearingSchedule/HearingScheduleApp.jsx
  client/app/hearingSchedule/components/BuildSchedule.jsx
  client/app/hearingSchedule/components/ListSchedule.jsx
  spec/feature/out_of_service_spec.rb
Labels: In-Progress

#6380 Hearing Schedule Table header color
  client/app/hearingSchedule/components/ReviewAssignments.jsx
Labels: In-Progress, Ready-to-Merge

#6412 Video records should be type "C" in the VACOLS DB.
  app/models/vacols/case_hearing.rb
Labels: In-Progress, Ready-to-Merge

#6405 Fixing appeal factory
  spec/factories/appeal.rb
Labels: In-Progress, Ready-to-Merge

#5955 Moving final appeals status test to facols
  app/models/vacols/case.rb
  app/services/appeal_repository.rb
  spec/feature/api/v1/appeals_spec.rb
  spec/feature/api/v2/appeals_spec.rb
  spec/models/appeal_series_spec.rb
  spec/models/docket_tracer_spec.rb
Labels: In-Progress, Ready-to-Merge
