Repository department-of-veterans-affairs/caseflow, pull requests merged in 2018-09, with the labels that each got.

#6808 Update rubyzip (CVE-2018-1000544)
  Gemfile
  Gemfile.lock
Labels: In-Progress

#6747 Queue | Better manage browser history during checkout flows
  client/COPY.json
  client/app/queue/CaseSnapshot.jsx
  client/app/queue/SubmitDecisionView.jsx
  client/app/queue/components/AttorneyActionsDropdown.jsx
  client/app/queue/components/DecisionViewBase.jsx
  client/app/queue/components/JudgeActionsDropdown.jsx
  client/app/queue/reducers.js
Labels: In-Progress

#6765 AMA attorney checkout flow works
  app/models/concerns/case_review_concern.rb
  client/COPY.json
  client/app/queue/AddEditIssueView.jsx
  client/app/queue/SelectDispositionsView.jsx
  client/app/queue/components/AttorneyActionsDropdown.jsx
  client/app/queue/components/SelectIssueDispositionDropdown.jsx
  client/app/queue/constants.js
  client/app/queue/reducers.js
  client/app/queue/types/models.js
  client/app/queue/utils.js
  spec/controllers/case_reviews_controller_spec.rb
  spec/feature/queue/checkout_flows_spec.rb
Labels: In-Progress

#6806 Move AppealsController#tasks to TasksController#for_appeal
  app/controllers/appeals_controller.rb
  app/controllers/application_controller.rb
  app/controllers/intakes_controller.rb
  app/controllers/tasks_controller.rb
  config/routes.rb
  spec/controllers/appeals_controller_spec.rb
  spec/controllers/tasks_controller_spec.rb
  spec/feature/hearing_schedule/build_schedule_spec.rb
Labels: In-Progress, Ready-to-Merge

#6769 Download hearing schedule
  client/COPY.json
  client/app/hearingSchedule/components/ListSchedule.jsx
  client/package.json
  client/yarn.lock
Labels: In-Progress, Ready-to-Merge

#6807 Refactor how end product establishments are handled on claim reviews
  app/models/ama_review.rb
  app/models/appeal.rb
  app/models/claim_review.rb
  app/models/end_product_establishment.rb
  app/models/higher_level_review.rb
  app/models/higher_level_review_intake.rb
  app/models/intake.rb
  app/models/ramp_review.rb
  app/models/request_issue.rb
  app/models/request_issues_update.rb
  app/models/supplemental_claim.rb
  app/models/supplemental_claim_intake.rb
  db/migrate/20180831162601_add_end_product_establishment_id_to_request_issues.rb
  db/schema.rb
  spec/feature/intake/edit_spec.rb
  spec/feature/intake/higher_level_review_spec.rb
  spec/feature/intake/supplemental_claim_spec.rb
  spec/models/claim_review_spec.rb
  spec/models/end_product_establishment_spec.rb
  spec/models/higher_level_review_intake_spec.rb
  spec/models/higher_level_review_spec.rb
  spec/models/request_issues_update_spec.rb
  spec/models/supplemental_claim_intake_spec.rb
  spec/models/supplemental_claim_spec.rb
Labels: In-Progress, Ready-to-Merge

#6801 Sync dispositions on end product becoming cleared
  app/models/claim_review.rb
  app/models/end_product_establishment.rb
  lib/fakes/vbms_service.rb
  lib/generators/contention.rb
  spec/models/claim_review_spec.rb
  spec/models/higher_level_review_spec.rb
  spec/models/supplemental_claim_spec.rb
Labels: In-Progress, Ready-to-Merge

#6827 Add organization test user
  db/seeds.rb
Labels: In-Progress, Ready-to-Merge

#6829 Adding font awesome back in
  client/app/styles/app.scss
  client/package.json
  client/yarn.lock
Labels: In-Progress, Ready-to-Merge

#6828 Allow VSO users access to switch user screen
  app/controllers/test/users_controller.rb
Labels: In-Progress

#6826 Updates outline classname to secondary button.
  client/app/components/DropdownButton.jsx
  client/app/components/ToggleButton.jsx
  client/app/containers/EstablishClaimPage/EstablishClaimAssociateEP.jsx
  client/app/containers/EstablishClaimPage/EstablishClaimEmail.jsx
  client/app/containers/EstablishClaimPage/EstablishClaimNote.jsx
  client/app/containers/StyleGuide/StyleGuideButton.jsx
  client/app/containers/StyleGuide/StyleGuideIndex.jsx
  client/app/containers/StyleGuide/StyleGuideModal.jsx
  client/app/hearingSchedule/components/ListSchedule.jsx
  client/app/hearings/HearingWorksheet.jsx
  client/app/hearings/components/HearingWorksheetStream.jsx
  client/app/hearings/components/WorksheetHeader.jsx
  client/app/intakeCommon/components/NonRatedIssues.jsx
  client/app/queue/components/DecisionViewBase.jsx
  client/app/styles/_commons.scss
  client/app/styles/react/_toggle_button.scss
Labels: In-Progress, Ready-to-Merge

#6815 Implement IDT AMA details - version 1
  app/controllers/idt/api/v1/appeals_controller.rb
  app/models/appeal.rb
  app/models/claimant.rb
  app/models/legacy_appeal.rb
  app/models/proper_name.rb
  app/models/serializers/idt/v1/appeal_details_serializer.rb
  app/models/serializers/work_queue/appeal_serializer.rb
  spec/controllers/idt/api/appeals_controller_spec.rb
Labels: In-Progress, Ready-to-Merge

#6835 fix table header borderless padding
  client/app/styles/_commons.scss
Labels: In-Progress, Ready-to-Merge

#6837 Move period inside quotations
  client/app/intake/pages/search.jsx
Labels: In-Progress, Ready-to-Merge

#6819 Queue | Adapt AMA attorney checkout flow for RAMP appeals
  app/models/legacy_tasks/judge_legacy_task.rb
  app/models/legacy_tasks/legacy_task.rb
  app/models/serializers/work_queue/legacy_task_serializer.rb
  client/app/queue/AddEditIssueView.jsx
  client/app/queue/AttorneyTaskListView.jsx
  client/app/queue/QueueApp.jsx
  client/app/queue/SelectDispositionsView.jsx
  client/app/queue/SelectRemandReasonsView.jsx
  client/app/queue/SubmitDecisionView.jsx
  client/app/queue/components/IssueList.jsx
  client/app/queue/components/IssueRemandReasonsOptions.jsx
  client/app/queue/components/JudgeActionsDropdown.jsx
  client/app/queue/components/SelectIssueDispositionDropdown.jsx
  client/app/queue/reducers.js
  client/app/queue/selectors.js
  client/app/queue/types/models.js
  client/app/queue/utils.js
  client/test/karma/queue/QueueLoadingScreen-test.js
  spec/models/legacy_tasks/judge_legacy_task_spec.rb
Labels: In-Progress

#6848 update karma/mocha lib versions
  client/package.json
  client/yarn.lock
Labels: In-Progress

#6850 Queue | Fix displaying assign vs review judge task views
  client/app/queue/QueueApp.jsx
Labels: In-Progress

#6852 Searchable input
  client/app/styles/app.scss
  client/app/styles/react/_select-dropdown.scss
Labels: In-Progress

#6861 Removes redundant spec and skips one that fails
  spec/feature/certification/cancel_certification_spec.rb
Labels: In-Progress, Ready-to-Merge

#6832 Move pdf_viewer sym
  app/assets/stylesheets/_pdf_viewer.css
  app/assets/stylesheets/application.css
  client/app/index.js
  client/webpack.config.js
Labels: In-Progress, Ready-to-Merge

#6841 Add committed_at to EndProductEstablishments
  app/models/claim_review.rb
  app/models/end_product_establishment.rb
  app/models/ramp_refiling.rb
  app/models/ramp_review.rb
  db/migrate/20180905163350_add_committed_at_to_end_product_establishments.rb
  db/schema.rb
  spec/models/claim_review_spec.rb
  spec/models/end_product_establishment_spec.rb
  spec/models/ramp_election_spec.rb
  spec/models/ramp_refiling_spec.rb
Labels: In-Progress, Ready-to-Merge

#6849 Determine if veteran is deceased
  app/models/appeal.rb
  app/models/veteran.rb
  lib/generators/veteran.rb
  spec/controllers/idt/api/appeals_controller_spec.rb
  spec/factories/veteran.rb
  spec/models/veteran_spec.rb
Labels: In-Progress, Ready-to-Merge

#6840 Delete issues on cancel
  app/models/ama_review.rb
  app/models/ramp_election.rb
  app/models/ramp_review.rb
  spec/models/appeal_intake_spec.rb
  spec/models/higher_level_review_intake_spec.rb
  spec/models/ramp_election_intake_spec.rb
  spec/models/ramp_election_rollback_spec.rb
  spec/models/ramp_refiling_intake_spec.rb
  spec/models/supplemental_claim_intake_spec.rb
Labels: In-Progress, Ready-to-Merge

#6853 Make ColocatedActionsDropdown redirect to URL onChange
  client/app/queue/QueueApp.jsx
  client/app/queue/TriggerModal.jsx
  client/app/queue/components/ColocatedActionsDropdown.jsx
Labels: In-Progress, Ready-to-Merge

#6818 Building tasks from intake
  app/models/appeal.rb
  app/models/appeal_intake.rb
  app/models/claimant.rb
  app/models/organizations/bva.rb
  app/models/tasks/root_task.rb
  app/models/tasks/vso_task.rb
  app/services/bgs_power_of_attorney.rb
  db/seeds.rb
  lib/fakes/bgs_service.rb
  spec/controllers/organizations/tasks_controller_spec.rb
  spec/factories/task.rb
  spec/feature/queue/ama_queue_spec.rb
  spec/models/appeal_intake_spec.rb
  spec/models/appeal_spec.rb
  spec/models/tasks/root_task_spec.rb
Labels: In-Progress, Ready-to-Merge

#6844 Anya/first last names for appelant
  app/mappers/address_mapper.rb
  app/models/appeal.rb
  app/models/claimant.rb
  app/models/proper_name.rb
  app/models/serializers/idt/v1/appeal_details_serializer.rb
  app/services/external_api/bgs_service.rb
  lib/fakes/bgs_service.rb
  spec/mappers/address_mapper_spec.rb
  spec/models/claimant_spec.rb
Labels: In-Progress, Ready-to-Merge

#6858 Add fields for idempotency work
  app/models/higher_level_review.rb
  app/models/higher_level_review_intake.rb
  app/models/supplemental_claim.rb
  app/models/supplemental_claim_intake.rb
  db/migrate/20180907003818_add_claim_establishment_idempotency_fields.rb
  db/schema.rb
  spec/feature/intake/edit_spec.rb
  spec/models/claim_review_spec.rb
  spec/models/higher_level_review_intake_spec.rb
  spec/models/higher_level_review_spec.rb
  spec/models/supplemental_claim_intake_spec.rb
  spec/models/supplemental_claim_spec.rb
  spec/models/temporary_appeal_spec.rb
Labels: In-Progress, Ready-to-Merge

#6859 changes to the judge algorithm - Assign all hearing days first based on UA
  app/services/hearing_schedule/assign_judges_to_hearing_days.rb
  spec/fake_date_helper.rb
  spec/models/judge_schedule_period_spec.rb
  spec/support/singleNonAvailJudgeSpreadsheet.xlsx
Labels: In-Progress

#6839 Add generic mark task complete action
  app/controllers/application_controller.rb
  app/controllers/organizations/tasks_controller.rb
  app/controllers/tasks_controller.rb
  app/models/serializers/work_queue/beaam_serializer.rb
  app/models/serializers/work_queue/legacy_task_serializer.rb
  app/models/serializers/work_queue/task_serializer.rb
  app/models/task.rb
  app/models/tasks/generic_task.rb
  app/models/user.rb
  client/app/queue/CaseSnapshot.jsx
  client/app/queue/MarkTaskCompleteView.jsx
  client/app/queue/OrganizationQueueLoadingScreen.jsx
  client/app/queue/QueueActions.js
  client/app/queue/QueueApp.jsx
  client/app/queue/components/DecisionViewBase.jsx
  client/app/queue/components/GenericTaskActionsDropdown.jsx
  client/app/queue/constants.js
  client/app/queue/reducers.js
  client/app/queue/selectors.js
  client/app/queue/types/models.js
  client/app/queue/types/state.js
  client/app/queue/uiReducer/uiActions.js
  client/app/queue/utils.js
  client/test/karma/queue/ColocatedTaskListView-test.js
  client/test/karma/queue/QueueLoadingScreen-test.js
  db/seeds.rb
Labels: In-Progress, Ready-to-Merge

#6879 Handle non poa responses
  app/mappers/power_of_attorney_mapper.rb
  app/models/appeal.rb
  spec/mappers/power_of_attorney_mapper_spec.rb
  spec/models/appeal_spec.rb
Labels: In-Progress, Ready-to-Merge

#6891 Ignore CVE-2018-1000201 for a week
  lib/tasks/security.rake
Labels: In-Progress, Ready-to-Merge

#6885 Hide links to Reader from VSO employees
  app/views/organizations/show.html.erb
  app/views/queue/index.html.erb
  client/app/queue/CaseTitle.jsx
  client/app/queue/QueueApp.jsx
  client/app/queue/components/TaskTable.jsx
  client/app/queue/types/state.js
  client/app/queue/uiReducer/uiActions.js
  client/app/queue/uiReducer/uiConstants.js
  client/app/queue/uiReducer/uiReducer.js
Labels: In-Progress, Ready-to-Merge

#6889 Add colocated to pilot
  lib/constants/co_located_teams.rb
Labels: In-Progress, Ready-to-Merge

#6894 Makes ratings specific to each veteran
  client/app/intakeCommon/util/index.js
  lib/fakes/initializer.rb
  lib/generators/rating.rb
Labels: In-Progress

#6872 Record issue removed_at and rating_associated_at timestamps
  app/models/claim_review.rb
  app/models/end_product_establishment.rb
  spec/feature/intake/higher_level_review_spec.rb
  spec/feature/intake/supplemental_claim_spec.rb
  spec/models/claim_review_spec.rb
  spec/models/end_product_establishment_spec.rb
  spec/models/higher_level_review_intake_spec.rb
  spec/models/request_issues_update_spec.rb
  spec/models/supplemental_claim_intake_spec.rb
Labels: In-Progress, Ready-to-Merge

#6906 Increase timeout for claim_establishment idempotency migration
  db/migrate/20180907003818_add_claim_establishment_idempotency_fields.rb
Labels: In-Progress

#6901 Allow system admin roles access to queue
  app/controllers/application_controller.rb
Labels: In-Progress, Ready-to-Merge

#6868 Queue | Colocated tweaks
  app/controllers/tasks_controller.rb
  client/COPY.json
  client/app/containers/StyleGuide/StyleGuideSearchableDropdown.jsx
  client/app/queue/ColocatedPlaceHoldView.jsx
  client/app/queue/ColocatedTaskListView.jsx
  client/app/queue/components/AttorneyActionsDropdown.jsx
  client/app/queue/components/ColocatedActionsDropdown.jsx
  client/app/queue/selectors.js
  client/app/queue/utils.js
  client/test/karma/queue/ColocatedTaskListView-test.js
  spec/feature/queue/checkout_flows_spec.rb
Labels: In-Progress, Ready-to-Merge

#6909 Update connect_vbms version
  Gemfile
  Gemfile.lock
Labels: In-Progress, Ready-to-Merge

#6893 Hold open diary updates
  app/models/vacols/case_hearing.rb
  app/models/vacols/note.rb
Labels: In-Progress, Ready-to-Merge

#6910 Remove unnecessary check on reopening appeals
  app/services/appeal_repository.rb
Labels: In-Progress, Ready-to-Merge

#6871 Adding special issue page
  app/controllers/issues_controller.rb
  app/controllers/special_issues_controller.rb
  app/models/appeal.rb
  app/models/attorney_case_review.rb
  app/models/judge_case_review.rb
  app/models/special_issue_list.rb
  app/models/user.rb
  client/COPY.json
  client/app/constants/SpecialIssues.js
  client/app/queue/QueueActions.js
  client/app/queue/QueueApp.jsx
  client/app/queue/SelectSpecialIssuesView.jsx
  client/app/queue/SpecialIssueLoadingScreen.jsx
  client/app/queue/components/DecisionViewBase.jsx
  client/app/queue/constants.js
  client/app/queue/reducers.js
  client/app/queue/types/state.js
  config/routes.rb
  db/migrate/20180907184617_add_special_issue_lists_table.rb
  db/schema.rb
  spec/factories/task.rb
  spec/models/user_spec.rb
Labels: In-Progress, Ready-to-Merge

#6912 Fix migration file
  client/test/karma/queue/ColocatedTaskListView-test.js
  db/migrate/20180907003818_add_claim_establishment_idempotency_fields.rb
Labels: In-Progress, Ready-to-Merge

#6911 adding notes on how to fix connection issue
  README.md
  docs/oracle-debugging.md
Labels: In-Progress, Ready-to-Merge

#6802 Queue | Set cases to in_progress on enter Case Details
  client/app/queue/CaseDetailsLink.jsx
  client/app/queue/components/TaskTable.jsx
  client/app/queue/selectors.js
  spec/feature/queue/search_spec.rb
Labels: In-Progress, Ready-to-Merge

#6867 Review Assignments | Back link is broken
  client/app/hearingSchedule/components/ReviewAssignments.jsx
  client/app/styles/_commons.scss
  client/package.json
  client/yarn.lock
Labels: In-Progress, Ready-to-Merge

#6922 Add seed data for BVA Dispatch tasks
  db/seeds.rb
  spec/factories/task.rb
Labels: In-Progress, Ready-to-Merge

#6928 Queue | Only set task to 'in_progress' if task exists
  client/app/queue/CaseDetailsLink.jsx
Labels: In-Progress

#6924 Review Remand Reasons | Hides fields that aren't applicable
  client/app/queue/components/IssueRemandReasonsOptions.jsx
  client/app/queue/types/models.js
  client/app/queue/utils.js
  db/seeds.rb
Labels: In-Progress, Ready-to-Merge

#6918 Test special issues flow
  client/app/constants/SpecialIssues.js
  client/app/queue/QueueApp.jsx
  client/app/queue/SelectDispositionsView.jsx
  client/app/queue/SelectSpecialIssuesView.jsx
  client/app/queue/components/AttorneyActionsDropdown.jsx
  client/app/queue/components/JudgeActionsDropdown.jsx
  client/app/queue/constants.js
  spec/feature/queue/checkout_flows_spec.rb
  spec/services/hearing_schedule/generate_hearing_days_schedule_spec.rb
Labels: In-Progress, Ready-to-Merge

#6881 Schedule remove comma when Judge is not set
  app/mappers/hearing_day_mapper.rb
  app/models/serializers/hearings/hearing_day_serializer.rb
  app/models/vacols/case_hearing.rb
  client/app/hearingSchedule/components/ListSchedule.jsx
Labels: In-Progress

#6836 Determine AOD by grants or age
  app/models/advance_on_docket_grant.rb
  app/models/appeal.rb
  app/models/claimant.rb
  app/services/external_api/bgs_service.rb
  db/migrate/20180905201441_index_claimants_on_date_of_birth.rb
  db/migrate/20180905214036_remove_advanced_on_docket_from_appeals.rb
  db/migrate/20180911203611_create_advanced_on_docket_grants.rb
  db/migrate/20180911205053_add_birthdate_to_claimant_table.rb
  db/schema.rb
  lib/fakes/bgs_service.rb
  spec/controllers/tasks_controller_spec.rb
  spec/factories/advance_on_docket_grant.rb
  spec/factories/appeal.rb
  spec/feature/queue/ama_queue_spec.rb
  spec/models/appeal_spec.rb
  spec/models/claimant_spec.rb
Labels: In-Progress, Ready-to-Merge

#6917 Update COPY.json - attorney queue title + case snapshot days waiting
  client/COPY.json
Labels: In-Progress, Ready-to-Merge

#6899 onboarding readme fixes
  README.md
  lib/tasks/local/build.rake
Labels: In-Progress, Ready-to-Merge

#6919 Retry RampRefilings in partially completed state
  app/jobs/ramp_election_sync_job.rb
  app/jobs/sync_reviews_job.rb
  app/models/ramp_refiling.rb
  app/models/ramp_refiling_intake.rb
  spec/jobs/sync_reviews_job_spec.rb
  spec/models/ramp_refiling_intake_spec.rb
  spec/models/ramp_refiling_spec.rb
Labels: In-Progress, Ready-to-Merge

#6949 [ci skip] Updating the migraiton location
  db/migrate/201809112051441_index_claimants_on_date_of_birth.rb
  db/schema.rb
Labels: In-Progress

#6951 The keyword "connects" triggers validation
  PULL_REQUEST_TEMPLATE.md
Labels: In-Progress, Ready-to-Merge

#6927 VBMS benefit_type_code based on date_of_death
  app/models/end_product.rb
  app/models/end_product_establishment.rb
  spec/models/end_product_establishment_spec.rb
  spec/models/end_product_spec.rb
Labels: In-Progress, Ready-to-Merge

#6956 Remove web-console gem
  Gemfile
  Gemfile.lock
  spec/models/request_issues_update_spec.rb
Labels: In-Progress, Ready-to-Merge

#6816 S3 configs
  app/controllers/hearings/schedule_periods_controller.rb
  app/models/schedule_period.rb
  app/services/form8_pdf_service.rb
  spec/factories/judge_schedule_period.rb
  spec/factories/ro_schedule_period.rb
Labels: In-Progress, Ready-to-Merge

#6845 Queue | Add new Fiduciary issues
  client/constants/ISSUE_INFO.json
  lib/tasks/local/vacols.rake
  spec/factories/vacols/issref.rb
Labels: In-Progress, Ready-to-Merge

#6962 Fix issue with the RampRefiling process script
  app/models/ramp_refiling_intake.rb
  spec/models/ramp_refiling_intake_spec.rb
Labels: In-Progress, Ready-to-Merge

#6967 Reader logo links to /queue
  client/app/reader/DecisionReviewer.jsx
  client/package.json
  client/yarn.lock
  spec/feature/reader/reader_spec.rb
Labels: In-Progress, Ready-to-Merge

#6968 Moving tests to FACOLS
  spec/factories/vacols/case.rb
  spec/jobs/prepare_establish_claim_tasks_job_spec.rb
Labels: In-Progress, Ready-to-Merge

#6908 Return veteran suffix name, return veteran death date, return outstan…
  app/models/appeal.rb
  app/models/legacy_appeal.rb
  app/models/serializers/idt/v1/appeal_details_serializer.rb
  app/models/vacols/mail.rb
  app/models/veteran.rb
  app/services/appeal_repository.rb
  lib/generators/veteran.rb
  spec/controllers/idt/api/appeals_controller_spec.rb
  spec/factories/legacy_appeal.rb
  spec/factories/vacols/correspondent.rb
  spec/factories/veteran.rb
  spec/models/legacy_appeal_spec.rb
  spec/models/veteran_spec.rb
Labels: In-Progress, Ready-to-Merge

#6945 Add ability to select non-compensation LOBs for benefit_type
  app/models/higher_level_review.rb
  app/models/higher_level_review_intake.rb
  app/models/supplemental_claim.rb
  app/models/supplemental_claim_intake.rb
  client/app/intake/actions/ama.js
  client/app/intake/components/BenefitType.jsx
  client/app/intake/constants.js
  client/app/intake/pages/higherLevelReview/review.jsx
  client/app/intake/pages/supplementalClaim/review.jsx
  client/app/intake/reducers/higherLevelReview.js
  client/app/intake/reducers/supplementalClaim.js
  client/app/intake/util/index.js
  client/constants/BENEFIT_TYPES.json
  db/migrate/20180912224413_add_benefit_type_to_claim_review.rb
  db/schema.rb
  spec/feature/intake/higher_level_review_spec.rb
  spec/feature/intake/supplemental_claim_spec.rb
  spec/models/higher_level_review_intake_spec.rb
  spec/models/higher_level_review_spec.rb
  spec/models/supplemental_claim_intake_spec.rb
  spec/models/supplemental_claim_spec.rb
Labels: In-Progress, Ready-to-Merge

#6907 Preparing the case details page for AMA appeals
  app/controllers/tasks_controller.rb
  app/models/serializers/work_queue/appeal_serializer.rb
  app/models/serializers/work_queue/task_serializer.rb
  app/models/task.rb
  client/COPY.json
  client/app/components/CopyTextButton.jsx
  client/app/queue/CaseSnapshot.jsx
  client/app/queue/CaseTitle.jsx
  client/app/queue/components/TaskTable.jsx
  client/app/queue/types/models.js
  client/app/queue/utils.js
  client/app/util/StringUtil.js
  client/test/karma/queue/ColocatedTaskListView-test.js
  client/test/karma/queue/QueueLoadingScreen-test.js
  spec/feature/queue/ama_queue_spec.rb
  spec/models/task_spec.rb
Labels: In-Progress, Ready-to-Merge

#6978 Fixing tests
  lib/generators/vacols/case_hearing.rb
  spec/controllers/hearings/schedule_periods_controller_spec.rb
  spec/controllers/idt/api/appeals_controller_spec.rb
  spec/feature/queue/checkout_flows_spec.rb
  spec/services/hearing_schedule/assign_judges_to_hearing_days_spec.rb
Labels: In-Progress

#6950 Schedule Prevent 5 digit years
  client/app/components/DateSelector.jsx
  client/app/components/TextField.jsx
Labels: In-Progress

#6972 Colocated | Remove Substitution Determination colocated task
  client/constants/CO_LOCATED_ADMIN_ACTIONS.json
  spec/controllers/tasks_controller_spec.rb
Labels: In-Progress, Ready-to-Merge

#6979 Fixing more tests
  lib/generators/vacols/case.rb
  spec/feature/reader/reader_spec.rb
  spec/services/hearing_schedule/assign_judges_to_hearing_days_spec.rb
Labels: In-Progress

#6954 Assign Hearings Skeleton
  app/controllers/hearing_schedule_controller.rb
  app/controllers/hearings/schedule_periods_controller.rb
  client/app/hearingSchedule/HearingScheduleApp.jsx
  client/app/hearingSchedule/components/AssignHearings.jsx
  client/app/hearingSchedule/containers/AssignHearingsContainer.jsx
  config/routes.rb
  spec/controllers/hearing_schedule_controller_spec.rb
Labels: In-Progress, Ready-to-Merge

#6969 AMA | Evaluate Decision | Show the date that the case was assigned to an attorney
  app/models/serializers/work_queue/task_serializer.rb
  app/models/task.rb
  app/models/tasks/judge_task.rb
  client/app/queue/utils.js
  db/seeds.rb
  lib/caseflow/error.rb
  spec/factories/task.rb
  spec/models/tasks/judge_task_spec.rb
Labels: In-Progress, Ready-to-Merge

#6976 Revert 3f98c3aeac6536d11e90b8a91a0aed19f8dc036e
  PULL_REQUEST_TEMPLATE.md
Labels: In-Progress, Ready-to-Merge

#6985 Set current_user for sync reviews job
  app/jobs/sync_reviews_job.rb
Labels: In-Progress, Ready-to-Merge

#6983 Queue | Add tooltip to days waiting column
  client/app/queue/components/TaskTable.jsx
Labels: In-Progress, Ready-to-Merge

#6994 Reading form_8s from their new location
  app/models/form8.rb
  app/services/form8_pdf_service.rb
  spec/services/form8_pdf_service_spec.rb
Labels: In-Progress

#6870 Judges can view AMA cases to assign and assign/reassign them between attorneys
  client/app/queue/JudgeAssignTaskListView.jsx
  client/app/queue/QueueActions.js
  client/app/queue/selectors.js
  client/app/queue/types/models.js
  client/app/queue/utils.js
  client/test/karma/queue/ColocatedTaskListView-test.js
  client/test/karma/queue/QueueLoadingScreen-test.js
  spec/feature/queue/judge_assignment_spec.rb
Labels: In-Progress, Ready-to-Merge

#6996 Fixing up VSO queues and search -> case details page
  app/models/serializers/work_queue/task_serializer.rb
  client/app/queue/CaseSnapshot.jsx
  db/seeds.rb
Labels: In-Progress, Ready-to-Merge

#6936 Caseflow | Adds test data
  db/seeds.rb
Labels: In-Progress, Ready-to-Merge

#6980 Add endpoint for completing BvaDispatchTasks through the IDT API
  app/controllers/idt/api/v1/appeals_controller.rb
  app/models/tasks/bva_dispatch_task.rb
  config/routes.rb
  lib/caseflow/error.rb
  spec/controllers/idt/api/appeals_controller_spec.rb
  spec/models/tasks/bva_dispatch_task_spec.rb
Labels: In-Progress, Ready-to-Merge

#6997 Show case details page for cases with tasks not assigned to anyone
  client/app/queue/CaseSnapshot.jsx
Labels: In-Progress, Ready-to-Merge

#6896 6351 add name to veteran table
  app/models/veteran.rb
  db/migrate/20180910195448_add_name_to_veteran.rb
  db/schema.rb
  lib/fakes/appeal_repository.rb
  lib/generators/veteran.rb
  spec/controllers/idt/api/appeals_controller_spec.rb
  spec/factories/legacy_appeal.rb
  spec/factories/veteran.rb
  spec/feature/intake/intake_spec.rb
  spec/feature/queue/ama_queue_spec.rb
  spec/models/claim_review_spec.rb
  spec/models/end_product_establishment_spec.rb
  spec/models/ramp_election_spec.rb
  spec/models/veteran_spec.rb
Labels: In-Progress

#6989 Schedule validation for case-sensitivity
  app/services/hearing_schedule/validate_judge_spreadsheet.rb
Labels: In-Progress

#6993 Queue | Add tooltip to hearing worksheet link
  client/COPY.json
  client/app/queue/CaseHearingsDetail.jsx
  spec/feature/queue/case_details_spec.rb
Labels: In-Progress, Ready-to-Merge

#7001 Update attorney_judge_teams.rb - Remove duplicate attorneys for BVARKESSEL
  lib/constants/attorney_judge_teams.rb
Labels: In-Progress, Ready-to-Merge

#7005 Queue | Fix returning Promise from initialAssignTasksToUser
  client/app/queue/QueueActions.js
Labels: In-Progress, Ready-to-Merge

#6935 Adding address to IDT
  app/controllers/idt/api/v1/appeals_controller.rb
  app/models/claimant.rb
  app/models/serializers/idt/v1/appeal_details_serializer.rb
  app/services/bgs_address_service.rb
  app/services/bgs_power_of_attorney.rb
  spec/controllers/idt/api/appeals_controller_spec.rb
Labels: In-Progress, Ready-to-Merge

#6995 ColocatedTaskListView Test | Re-enables test
  client/test/karma/queue/ColocatedTaskListView-test.js
Labels: In-Progress, Ready-to-Merge

#6999 Assign hearings header
  app/controllers/regional_offices_controller.rb
  client/COPY.json
  client/app/hearingSchedule/actions.js
  client/app/hearingSchedule/components/AssignHearings.jsx
  client/app/hearingSchedule/components/RoSelectorDropdown.jsx
  client/app/hearingSchedule/constants.js
  client/app/hearingSchedule/containers/AssignHearingsContainer.jsx
  client/app/hearingSchedule/reducers.js
  client/test/karma/hearingSchedule/components/AssignHearings-test.js
  config/routes.rb
  spec/controllers/regional_offices_controller_spec.rb
Labels: In-Progress, Ready-to-Merge

#6932 Fix case search access control
  app/controllers/application_controller.rb
  app/controllers/case_reviews_controller.rb
  app/controllers/legacy_tasks_controller.rb
  app/controllers/queue_controller.rb
  app/controllers/reader/appeal_controller.rb
  app/controllers/tasks_controller.rb
  app/controllers/users_controller.rb
  app/views/organizations/show.html.erb
  app/views/queue/index.html.erb
  app/views/queue/show.html.erb
  app/views/reader/appeal/index.html.erb
  client/app/queue/CaseDetailsLoadingScreen.jsx
  client/app/queue/QueueApp.jsx
  client/app/queue/QueueLoadingScreen.jsx
  client/app/reader/DecisionReviewer.jsx
  db/seeds.rb
  spec/controllers/legacy_tasks_controller_spec.rb
  spec/feature/reader/reader_spec.rb
Labels: In-Progress, Ready-to-Merge

#7008 Add docket type badge to queue table item
  client/COPY.json
  client/app/queue/components/TaskTable.jsx
  spec/feature/queue/task_queue_spec.rb
Labels: In-Progress, Ready-to-Merge

#7011 Amprokop fix assign bug
  app/models/task.rb
  client/app/queue/selectors.js
  db/seeds.rb
Labels: In-Progress, Ready-to-Merge

#6998 SearchableDropdown | Make component type-safe
  client/app/components/SearchableDropdown.jsx
  client/app/queue/AddColocatedTaskView.jsx
  client/app/queue/ColocatedPlaceHoldView.jsx
  client/app/queue/JudgeSelectComponent.jsx
  client/app/queue/components/AssignWidget.jsx
  client/app/queue/components/AttorneyActionsDropdown.jsx
  client/app/queue/components/ColocatedActionsDropdown.jsx
  client/app/queue/components/GenericTaskActionsDropdown.jsx
  client/app/queue/components/JudgeActionsDropdown.jsx
  client/app/queue/components/SelectIssueDispositionDropdown.jsx
Labels: In-Progress, Ready-to-Merge

#7019 updates ffi
  Gemfile.lock
Labels: In-Progress, Ready-to-Merge

#7022 Queue | Use appeal.isLegacyAppeal over docketName
  client/app/queue/AddColocatedTaskView.jsx
  client/app/queue/CaseDetailsView.jsx
  client/app/queue/SelectDispositionsView.jsx
  client/app/queue/components/AttorneyActionsDropdown.jsx
  client/app/queue/components/ColocatedActionsDropdown.jsx
  client/app/queue/components/IssueRemandReasonsOptions.jsx
  client/app/queue/components/JudgeActionsDropdown.jsx
  client/app/queue/components/SelectIssueDispositionDropdown.jsx
  client/app/queue/components/TaskTable.jsx
  client/app/queue/selectors.js
  client/app/queue/types/models.js
  client/app/queue/utils.js
  client/test/karma/queue/ColocatedTaskListView-test.js
Labels: In-Progress

#7021 Queue | Fix serializing request_issues count for ama appeals
  app/models/appeal.rb
  app/models/legacy_appeal.rb
  app/models/serializers/work_queue/task_serializer.rb
Labels: In-Progress, Ready-to-Merge

#7025 Add docket type badge to case details page
  app/models/serializers/work_queue/appeal_serializer.rb
  client/app/queue/CaseSnapshot.jsx
  client/app/queue/components/DocketTypeBadge.jsx
  client/app/queue/components/TaskTable.jsx
Labels: In-Progress, Ready-to-Merge

#6959 Removes table styles overwrites
  client/app/components/Table.jsx
  client/app/styles/_commons.scss
  client/app/styles/reader/_reviewer.scss
Labels: In-Progress

#7033 Removing migration
  db/migrate/201809112051441_index_claimants_on_date_of_birth.rb
  db/schema.rb
Labels: In-Progress, Ready-to-Merge

#7027 Only reopen closed appeals when rolling back ramp elections
  app/models/ramp_election_rollback.rb
  spec/models/ramp_election_rollback_spec.rb
Labels: In-Progress, Ready-to-Merge

#6925 HearingDay Data Model Implementation
  app/controllers/hearings/hearing_day_controller.rb
  app/mappers/hearing_day_mapper.rb
  app/models/hearing_day.rb
  app/models/judge_schedule_period.rb
  app/models/serializers/hearings/hearing_day_create_serializer.rb
  app/models/serializers/hearings/hearing_day_serializer.rb
  app/repositories/hearing_day_repository.rb
  app/services/hearing_schedule/assign_judges_to_hearing_days.rb
  db/migrate/20180912142310_create_hearing_days.rb
  db/schema.rb
  lib/generators/vacols/staff.rb
  lib/generators/vacols/travel_board_schedule.rb
  spec/models/hearing_day_spec.rb
  spec/models/judge_schedule_period_spec.rb
  spec/models/ro_schedule_period_spec.rb
  spec/requests/hearing_day_spec.rb
  spec/services/hearing_schedule/assign_judges_to_hearing_days_spec.rb
Labels: In-Progress, Ready-to-Merge

#7024 Anya/bva dispatch idt
  app/controllers/idt/api/v1/appeals_controller.rb
  app/controllers/idt/api/v1/base_controller.rb
  app/controllers/tasks_controller.rb
  db/seeds.rb
  lib/constants/bva_dispatch_teams.rb
  spec/controllers/idt/api/appeals_controller_spec.rb
  spec/controllers/legacy_tasks_controller_spec.rb
  spec/controllers/tasks_controller_spec.rb
Labels: In-Progress, Ready-to-Merge

#7043 add --parallel to speed up rubocop
  lib/tasks/lint.rake
Labels: In-Progress, Ready-to-Merge

#7040 Only set task status to 'in_progress' for newly 'assigned' tasks when opening case details
  client/app/queue/CaseDetailsLink.jsx
  spec/feature/queue/case_details_spec.rb
Labels: In-Progress, Ready-to-Merge

#7047 Show 'Place hold' action for tasks already on hold
  client/app/queue/components/ColocatedActionsDropdown.jsx
Labels: In-Progress, Ready-to-Merge

#7048 Set current user in the request store for BGS to work
  app/controllers/idt/api/v1/base_controller.rb
  spec/controllers/idt/api/appeals_controller_spec.rb
Labels: In-Progress, Ready-to-Merge

#7049 Queue | Update SearchableDropdown usages
  client/app/queue/AddEditIssueView.jsx
  client/app/queue/utils.js
Labels: In-Progress, Ready-to-Merge

#7042 add bootsnap gem for faster rails boot
  Gemfile
  Gemfile.lock
  config/boot.rb
Labels: In-Progress, Ready-to-Merge

#7058 Allow CAVC appeals to be reopened
  app/services/appeal_repository.rb
Labels: In-Progress, Ready-to-Merge

#7050 Check if veteran is accessible
  app/models/veteran.rb
Labels: In-Progress, Ready-to-Merge

#7067 --parallel and --auto-correct are incompatible so unbreak local linting
  lib/tasks/lint.rake
Labels: In-Progress

#7070 Queue | Fixes flakey test
  spec/feature/queue/checkout_flows_spec.rb
Labels: In-Progress, Ready-to-Merge

#7039 Search bar text update
  client/app/intake/pages/search.jsx
  spec/feature/intake/appeal_spec.rb
  spec/feature/intake/higher_level_review_spec.rb
  spec/feature/intake/intake_spec.rb
  spec/feature/intake/ramp_election_spec.rb
  spec/feature/intake/ramp_refiling_spec.rb
  spec/feature/intake/supplemental_claim_spec.rb
Labels: In-Progress, Ready-to-Merge

#7006 Adding requested features to IDT
  app/controllers/idt/api/v1/appeals_controller.rb
  app/mappers/address_mapper.rb
  app/mappers/power_of_attorney_mapper.rb
  app/models/claimant.rb
  app/models/legacy_appeal.rb
  app/models/power_of_attorney.rb
  app/models/serializers/idt/v1/appeal_details_serializer.rb
  app/models/vacols/mail.rb
  app/models/vacols/representative.rb
  app/repositories/judge_repository.rb
  app/services/power_of_attorney_repository.rb
  spec/controllers/idt/api/appeals_controller_spec.rb
  spec/factories/vacols/case.rb
  spec/models/legacy_appeal_spec.rb
  spec/models/power_of_attorney_spec.rb
Labels: In-Progress, Ready-to-Merge

#7059 Queue | Removes references to DAS
  client/COPY.json
  client/app/queue/AddColocatedTaskView.jsx
  client/app/queue/EvaluateDecisionView.jsx
  client/app/queue/QueueApp.jsx
  client/app/queue/components/DispatchSuccessDetail.jsx
  client/app/queue/types/state.js
  client/app/queue/uiReducer/uiActions.js
  client/app/queue/uiReducer/uiConstants.js
  client/app/queue/uiReducer/uiReducer.js
Labels: In-Progress, Ready-to-Merge

#7060 Do not overwrite Task instructions when updating Task
  app/models/task.rb
  client/app/queue/CaseSnapshot.jsx
  client/app/queue/types/models.js
  db/migrate/20180919213618_change_task_instructions_field_type.rb
  db/schema.rb
  spec/controllers/tasks_controller_spec.rb
  spec/factories/task.rb
  spec/feature/queue/case_details_spec.rb
  spec/feature/queue/checkout_flows_spec.rb
Labels: In-Progress, Ready-to-Merge

#7046 Change status of on_hold ColocatedTasks to in_progress if hold has expired
  app/models/queues/colocated_queue.rb
  app/models/tasks/colocated_task.rb
  spec/models/queues/colocated_queue_spec.rb
Labels: In-Progress, Ready-to-Merge

#7071 Update org queue title naming
  client/COPY.json
Labels: In-Progress, Ready-to-Merge

#7034 Judges | Queue | Adds basic tests
  spec/feature/queue/judge_assignment_spec.rb
Labels: In-Progress, Ready-to-Merge

#7045 Remove unwanted para before field input
  client/app/intake/pages/selectForm.jsx
Labels: In-Progress, Ready-to-Merge

#7087 Fix db/schema mistake I committed earlier
  db/schema.rb
Labels: In-Progress, Ready-to-Merge

#6992 Create supplemental review on DTA error
  app/models/claim_review.rb
  app/models/end_product.rb
  app/models/higher_level_review.rb
  app/models/supplemental_claim.rb
  db/migrate/20180914201526_add_parent_request_id_to_request_issue.rb
  db/migrate/20180919144814_add_is_dta_to_supplemental_claim.rb
  db/schema.rb
  spec/feature/intake/supplemental_claim_spec.rb
  spec/models/claim_review_spec.rb
Labels: In-Progress

#7080 Filter tasks that are assigned for a judge (IDT)
  app/controllers/idt/api/v1/appeals_controller.rb
  spec/controllers/idt/api/appeals_controller_spec.rb
Labels: In-Progress, Ready-to-Merge

#7017 Edit request issues on claims
  app/controllers/higher_level_reviews_controller.rb
  app/controllers/supplemental_claims_controller.rb
  app/models/end_product_establishment.rb
  app/models/request_issues_update.rb
  client/app/intake/IntakeFrame.jsx
  client/app/intake/components/CancelButton.jsx
  client/app/intake/constants.js
  client/app/intake/pages/appeal/finish.jsx
  client/app/intake/pages/appeal/review.jsx
  client/app/intake/pages/higherLevelReview/finish.jsx
  client/app/intake/pages/higherLevelReview/review.jsx
  client/app/intake/pages/rampElection/finish.jsx
  client/app/intake/pages/rampElection/review.jsx
  client/app/intake/pages/rampRefiling/finish.jsx
  client/app/intake/pages/rampRefiling/review.jsx
  client/app/intake/pages/search.jsx
  client/app/intake/pages/supplementalClaim/finish.jsx
  client/app/intake/pages/supplementalClaim/review.jsx
  client/app/intake/reducers/appeal.js
  client/app/intake/reducers/higherLevelReview.js
  client/app/intake/reducers/intake.js
  client/app/intake/reducers/rampElection.js
  client/app/intake/reducers/rampRefiling.js
  client/app/intake/reducers/supplementalClaim.js
  client/app/intakeCommon/constants.js
  client/app/intakeCommon/util/index.js
  client/app/intakeEdit/IntakeEditFrame.jsx
  client/app/intakeEdit/actions/selectIssues.js
  client/app/intakeEdit/components/CancelOrSave.jsx
  client/app/intakeEdit/components/RequestIssuesUpdateErrorAlert.jsx
  client/app/intakeEdit/constants.js
  client/app/intakeEdit/pages/selectIssues.jsx
  client/app/intakeEdit/reducers/index.js
  config/routes.rb
  spec/feature/intake/edit_spec.rb
  spec/models/request_issues_update_spec.rb
Labels: In-Progress, Ready-to-Merge

#7068 set require directive for ruby-oci8 gem to silence warning
  Gemfile
Labels: In-Progress, Ready-to-Merge

#7066 odds and ends
  app/controllers/idt/api/v1/appeals_controller.rb
  app/models/serializers/idt/v1/appeal_details_serializer.rb
  app/models/serializers/idt/v1/appeal_serializer.rb
  db/seeds.rb
  spec/factories/task.rb
Labels: In-Progress, Ready-to-Merge

#7084 Add test for veteran name backfill fix in #7050
  spec/models/veteran_spec.rb
Labels: In-Progress, Ready-to-Merge

#7032 Update Alerts styles
  client/app/components/Alert.jsx
  client/app/containers/StyleGuide/StyleGuideAlerts.jsx
  client/app/intake/IntakeFrame.jsx
  client/app/intake/components/CompleteIntakeErrorAlert.jsx
  client/app/intake/components/ErrorAlert.jsx
  client/app/intake/pages/rampRefiling/review.jsx
  client/app/intake/pages/search.jsx
  client/app/reader/SideBarDocumentInformation.jsx
  client/app/styles/_commons.scss
  client/app/styles/_main.scss
  client/app/styles/_style_guide.scss
  client/app/styles/app.scss
  client/app/styles/react/_alerts.scss
  client/app/styles/react/_react_styles_root.scss
  client/app/styles/react/_tabs.scss
  client/app/styles/reader/_reviewer.scss
Labels: In-Progress

#7013 Assign hearings date selector
  app/controllers/hearings/hearing_day_controller.rb
  app/mappers/hearing_day_mapper.rb
  app/models/hearing_day.rb
  app/models/vacols/case_hearing.rb
  app/repositories/hearing_day_repository.rb
  client/app/hearingSchedule/actions.js
  client/app/hearingSchedule/components/AssignHearings.jsx
  client/app/hearingSchedule/components/RoSelectorDropdown.jsx
  client/app/hearingSchedule/constants.js
  client/app/hearingSchedule/containers/AssignHearingsContainer.jsx
  client/app/hearingSchedule/reducers.js
  config/routes.rb
  spec/controllers/hearings/hearing_day_controller_spec.rb
  spec/repositories/hearing_day_repository_spec.rb
Labels: In-Progress, Ready-to-Merge

#7078 Modifying "Attorneys Assigning Colocated Task" Confirmation copy
  client/COPY.json
Labels: In-Progress, Ready-to-Merge

#7092 remove appeals_repository from dangerfile
  Dangerfile
Labels: In-Progress, Ready-to-Merge

#7061 Add to case details
  app/controllers/appeals_controller.rb
  app/models/claimant.rb
  app/models/serializers/work_queue/appeal_serializer.rb
  app/services/bgs_address_service.rb
  client/COPY.json
  client/app/queue/AppellantDetail.jsx
  client/app/queue/CaseDetailsView.jsx
  client/app/queue/PowerOfAttorneyDetail.jsx
  client/app/queue/QueueActions.js
  client/app/queue/VeteranDetail.jsx
  client/app/queue/components/Address.jsx
  client/app/queue/constants.js
  client/app/queue/reducers.js
  client/app/queue/types/models.js
  client/app/queue/types/state.js
  client/app/queue/utils.js
  config/routes.rb
  db/seeds.rb
  lib/fakes/bgs_service.rb
  lib/generators/veteran.rb
  spec/factories/veteran.rb
  spec/feature/queue/ama_queue_spec.rb
Labels: In-Progress, Ready-to-Merge

#7085 Configure CircleCI to use new ruby
  .circleci/config.yml
  ci-bin/circle_docker_container/Dockerfile
  ci-bin/circle_docker_container/build_and_push.sh
Labels: Ready-to-Merge

#7086 Display judge and attorney assigned to case in case snapshot
  app/models/appeal.rb
  app/models/concerns/taskable.rb
  app/models/legacy_appeal.rb
  app/models/serializers/work_queue/appeal_serializer.rb
  app/models/serializers/work_queue/legacy_appeal_serializer.rb
  client/COPY.json
  client/app/queue/CaseSnapshot.jsx
  client/app/queue/types/models.js
  client/app/queue/utils.js
  client/test/karma/queue/ColocatedTaskListView-test.js
Labels: In-Progress, Ready-to-Merge

#7089 Enable task actions for VSOs
  app/controllers/organizations/tasks_controller.rb
  app/controllers/tasks_controller.rb
  client/COPY.json
  client/app/queue/CaseSnapshot.jsx
  client/app/queue/MarkTaskCompleteView.jsx
  client/app/queue/selectors.js
  spec/factories/task.rb
  spec/factories/user.rb
  spec/feature/queue/task_queue_spec.rb
Labels: In-Progress, Ready-to-Merge

#7096 Do not return ratings with no issues
  app/models/ama_review.rb
  app/models/rating.rb
  lib/fakes/bgs_service.rb
  lib/generators/rating.rb
  spec/models/rating_spec.rb
Labels: In-Progress

#7007 Anya/6953 create remand reasons
  app/controllers/issues_controller.rb
  app/models/concerns/case_review_concern.rb
  app/models/decision_issue.rb
  app/models/remand_reason.rb
  app/models/request_issue.rb
  app/models/serializers/idt/v1/appeal_details_serializer.rb
  app/models/serializers/work_queue/appeal_serializer.rb
  app/models/serializers/work_queue/legacy_appeal_serializer.rb
  app/models/serializers/work_queue/legacy_issue_serializer.rb
  client/app/queue/EvaluateDecisionView.jsx
  client/app/queue/SelectDispositionsView.jsx
  client/app/queue/SelectRemandReasonsView.jsx
  client/app/queue/SubmitDecisionView.jsx
  client/app/queue/components/CaseDetailsIssueList.jsx
  client/app/queue/components/IssueList.jsx
  client/app/queue/components/IssueListItem.jsx
  client/app/queue/components/IssueRemandReasonsOptions.jsx
  client/app/queue/components/JudgeActionsDropdown.jsx
  client/app/queue/components/SelectIssueDispositionDropdown.jsx
  client/app/queue/constants.js
  client/app/queue/types/models.js
  client/app/queue/utils.js
  client/app/reader/ClaimsFolderDetails.jsx
  client/constants/ISSUE_DISPOSITIONS_BY_ID.json
  db/migrate/20180913171645_create_remand_reasons.rb
  db/schema.rb
  spec/factories/remand_reason.rb
  spec/models/attorney_case_review_spec.rb
Labels: In-Progress, Ready-to-Merge

#5792 Add instructions to impersonate user
  README.md
Labels: In-Progress, Ready-to-Merge

#7082 Mapped more attorneys to judges, deleted names as requested, and added 2 acting judges.
  lib/constants/attorney_judge_teams.rb
Labels: In-Progress, Ready-to-Merge, caseflow-queue, foxtrot

#7101 Queue | Fix sending ama appeal issues in AttorneyCaseReview payload
  client/app/queue/SubmitDecisionView.jsx
Labels: In-Progress, Ready-to-Merge

#7097 allow nil city and state for veterans with military addresses
  app/models/veteran.rb
  spec/models/veteran_spec.rb
Labels: In-Progress, Ready-to-Merge

#7104 Queue | Days waiting calculation, AppealSerializer type updates
  app/models/serializers/work_queue/appeal_serializer.rb
  client/app/queue/CaseSnapshot.jsx
Labels: In-Progress, Ready-to-Merge

#7051 adding appeals id to AppealNotValidToReopen
  app/services/appeal_repository.rb
Labels: In-Progress, Ready-to-Merge

#7098 Anya/7009 create person
  app/models/advance_on_docket_grant.rb
  app/models/claimant.rb
  app/models/person.rb
  db/migrate/20180921145533_create_persons.rb
  db/migrate/20180924131352_rename_claimant_id_to_person_id_in_aod_grants.rb
  db/schema.rb
  spec/factories/appeal.rb
  spec/factories/claimant.rb
  spec/factories/person.rb
  spec/models/appeal_spec.rb
  spec/models/claimant_spec.rb
  spec/models/person_spec.rb
Labels: In-Progress, Ready-to-Merge

#7074 Idempotent end product artifact processing
  app/models/claim_review.rb
  app/models/end_product_establishment.rb
  app/models/higher_level_review.rb
  app/models/supplemental_claim.rb
  spec/models/claim_review_spec.rb
  spec/models/end_product_establishment_spec.rb
Labels: In-Progress, Ready-to-Merge

#7112 New s3 bucket
  app/models/document.rb
  spec/jobs/prepare_establish_claim_tasks_job_spec.rb
  spec/models/establish_claim_spec.rb
Labels: In-Progress, Ready-to-Merge

#7115 Raise error when there are no available modifiers
  app/models/end_product_establishment.rb
  spec/models/end_product_establishment_spec.rb
Labels: In-Progress, Ready-to-Merge

#7079 Updates Forms styles
  client/app/components/CFRichTextEditor.jsx
  client/app/components/Checkbox.jsx
  client/app/components/CheckboxGroup.jsx
  client/app/components/Dropdown.jsx
  client/app/components/InlineForm.jsx
  client/app/components/Modal.jsx
  client/app/components/RadioField.jsx
  client/app/components/TextField.jsx
  client/app/containers/EstablishClaimPage/CanceledTasksIndex.jsx
  client/app/containers/EstablishClaimPage/EstablishClaimAssociateEP.jsx
  client/app/containers/EstablishClaimPage/UnpreparedTasksIndex.jsx
  client/app/hearingSchedule/components/BuildScheduleUpload.jsx
  client/app/queue/EvaluateDecisionView.jsx
  client/app/queue/SubmitDecisionView.jsx
  client/app/styles/_commons.scss
  client/app/styles/_main.scss
  client/app/styles/dispatch/_dispatch.scss
  client/app/styles/hearings/_hearings.scss
  client/app/styles/reader/_reviewer.scss
  spec/feature/intake/intake_spec.rb
  spec/feature/queue/checkout_flows_spec.rb
Labels: In-Progress

#7120 Queue | Update colocated actions
  client/app/queue/components/ColocatedActionsDropdown.jsx
Labels: In-Progress
