Repository department-of-veterans-affairs/caseflow, pull requests merged in 2018-12, with the labels that each got.

#8075 Flaky test fixes
  spec/controllers/hearings/schedule_periods_controller_spec.rb
  spec/models/hearing_day_spec.rb
Labels: In-Progress, Ready-to-Merge

#8082 Add created/updated_at columns to OrganizationsUsers table
  db/migrate/20181203174849_add_datetime_cols_to_organizations_users.rb
  db/schema.rb
Labels: In-Progress, Ready-to-Merge

#8072 Creates subclasses of JudgeTask for two actions
  .gitignore
  app/controllers/idt/api/v1/appeals_controller.rb
  app/controllers/tasks_controller.rb
  app/models/appeal.rb
  app/models/concerns/taskable.rb
  app/models/distribution.rb
  app/models/task.rb
  app/models/tasks/attorney_task.rb
  app/models/tasks/judge_assign_task.rb
  app/models/tasks/judge_review_task.rb
  app/models/tasks/judge_task.rb
  client/COPY.json
  client/constants/TASK_ACTIONS.json
  db/seeds.rb
  spec/controllers/case_reviews_controller_spec.rb
  spec/controllers/idt/api/appeals_controller_spec.rb
  spec/factories/task.rb
  spec/feature/queue/case_details_spec.rb
  spec/feature/queue/checkout_flows_spec.rb
  spec/feature/queue/judge_assignment_spec.rb
  spec/models/appeal_spec.rb
  spec/models/tasks/judge_task_spec.rb
  spec/models/tasks/quality_review_task_spec.rb
Labels: In-Progress, Ready-to-Merge

#8086 Move slow VBMS call outside the psql transaction to avoid timeout
  app/models/end_product_establishment.rb
  app/models/ramp_election.rb
Labels: In-Progress, Ready-to-Merge

#8074 update developer setup instructions
  README.md
Labels: In-Progress, Ready-to-Merge

#8073 adding benefit type
  app/models/appeal.rb
  app/models/claim_review.rb
  app/models/request_issue.rb
  db/migrate/20181130224517_add_benefit_type_to_issues.rb
  db/schema.rb
  spec/factories/request_issue.rb
  spec/feature/intake/appeal_spec.rb
  spec/feature/intake/higher_level_review_spec.rb
  spec/models/request_issue_spec.rb
Labels: In-Progress

#8056 Finishing up editing issues
  app/models/serializers/work_queue/appeal_serializer.rb
  client/COPY.json
  client/app/components/SearchableDropdown.jsx
  client/app/queue/SelectDispositionsView.jsx
  client/app/queue/SubmitDecisionView.jsx
  client/app/queue/components/ContestedIssues.jsx
  client/app/queue/components/IssueRemandReasonsOptions.jsx
  client/app/queue/components/SelectIssueDispositionDropdown.jsx
  spec/feature/queue/checkout_flows_spec.rb
Labels: In-Progress, Ready-to-Merge

#8097 Postponing hearings with caseflow parent records
  app/repositories/hearing_repository.rb
Labels: In-Progress

#8089 filters JudgeTeam organizations from queue selector
  app/models/organization.rb
  app/models/organizations/judge_team.rb
  app/models/user.rb
  app/views/queue/index.html.erb
  spec/feature/queue/task_queue_spec.rb
  spec/feature/queue/user_organization_spec.rb
  spec/models/user_spec.rb
Labels: In-Progress, Ready-to-Merge

#8094 adds queue dropdown selector to attorney queue table views
  client/app/queue/AttorneyTaskListView.jsx
  spec/feature/queue/task_queue_spec.rb
Labels: In-Progress, Ready-to-Merge

#8091 Add approx_decision_date to DecisionIssue
  app/models/decision_issue.rb
  app/models/end_product.rb
  app/models/request_issue.rb
  db/migrate/20181203231527_add_last_action_date_to_decision_issues.rb
  db/schema.rb
  spec/factories/decision_issue.rb
  spec/factories/end_product_establishment.rb
  spec/models/decision_issue_spec.rb
  spec/models/request_issue_spec.rb
Labels: In-Progress, Ready-to-Merge

#8102 adding contestable issues
  app/models/appeal.rb
  app/models/claim_review.rb
  app/models/contestable_issue.rb
  app/models/decision_issue.rb
  app/models/decision_review.rb
  app/models/request_issue.rb
  db/migrate/20181203223308_add_contested_decision_issue_id_to_request_issues.rb
  db/schema.rb
  spec/models/contestable_issue_spec.rb
  spec/models/decision_review_spec.rb
Labels: In-Progress

#8108 Add option to complete JudgeTasks created by Quality Review
  app/models/tasks/judge_assign_task.rb
  app/models/tasks/judge_task.rb
  spec/feature/queue/task_queue_spec.rb
Labels: In-Progress, Ready-to-Merge

#8088 Removing a hearing day
  app/controllers/hearings/hearing_day_controller.rb
  app/models/hearing_day.rb
  client/app/hearingSchedule/actions.js
  client/app/hearingSchedule/components/DailyDocket.jsx
  client/app/hearingSchedule/constants.js
  client/app/hearingSchedule/containers/DailyDocketContainer.jsx
  client/app/hearingSchedule/containers/ListScheduleContainer.jsx
  client/app/hearingSchedule/reducers.js
  config/routes.rb
  db/migrate/20181203195219_add_deleted_at_to_hearing_day.rb
  db/schema.rb
  spec/factories/hearing_day.rb
  spec/requests/hearing_day_spec.rb
Labels: In-Progress

#8112 include id of RampClosedAppeal in error details
  app/jobs/sync_intake_job.rb
Labels: In-Progress, Ready-to-Merge

#8076 Assign Hearings Modal | Time should be required
  client/app/hearingSchedule/components/AssignHearings.jsx
  client/app/queue/components/AssignHearingModal.jsx
Labels: In-Progress, Ready-to-Merge

#8110 Daily Docket | Add AMA lane tag hover tool tip
  app/models/hearing.rb
  client/app/components/DocketTypeBadge.jsx
  client/app/hearingSchedule/components/DailyDocket.jsx
  client/app/queue/CaseListTable.jsx
  client/app/queue/CaseSnapshot.jsx
  client/app/queue/components/TaskTable.jsx
Labels: In-Progress, Ready-to-Merge

#8114 Add back in dta supplemental claims
  app/models/decision_issue.rb
  app/models/decision_review.rb
  app/models/end_product_establishment.rb
  app/models/higher_level_review.rb
  app/models/ramp_review.rb
  app/models/request_issue.rb
  spec/factories/decision_issue.rb
  spec/models/claim_review_spec.rb
  spec/models/decision_issue_spec.rb
  spec/models/end_product_establishment_spec.rb
  spec/models/higher_level_review_spec.rb
Labels: In-Progress, Ready-to-Merge

#8120 Subclass transient BGSSyncErrors
  app/models/end_product_establishment.rb
  spec/models/end_product_establishment_spec.rb
Labels: In-Progress, Ready-to-Merge

#8101 Schedule Veterans on Action Click
  app/controllers/regional_offices_controller.rb
  app/controllers/tasks_controller.rb
  app/models/tasks/root_task.rb
  app/models/tasks/schedule_hearing_task.rb
  client/app/components/HearingDayDropdown.jsx
  client/app/components/RoSelectorDropdown.jsx
  client/app/components/common/actionTypes.js
  client/app/components/common/actions.js
  client/app/components/common/reducers.js
  client/app/hearingSchedule/components/AssignHearings.jsx
  client/app/queue/QueueApp.jsx
  client/app/queue/components/AssignHearingModal.jsx
  client/app/queue/types/state.js
  spec/controllers/regional_offices_controller_spec.rb
  spec/controllers/tasks_controller_spec.rb
  spec/models/tasks/root_task_spec.rb
Labels: In-Progress

#8013 Move access check inside Task.update_from_params
  app/controllers/tasks_controller.rb
  app/models/task.rb
  spec/controllers/tasks_controller_spec.rb
Labels: In-Progress, Ready-to-Merge

#8129 Default RO Value on Assign Hearings Page
  client/app/hearingSchedule/containers/AssignHearingsContainer.jsx
  client/app/queue/components/AssignHearingModal.jsx
Labels: In-Progress, Ready-to-Merge

#8134 populate fake ratings with unique issue ids
  lib/generators/rating.rb
Labels: In-Progress, Ready-to-Merge

#8127 Alternate Hearing Location ExternalAPIs Setup
  app/services/external_api/facilities_locator_service.rb
  app/services/external_api/vets360_service.rb
  config/initializers/facilities_locator.rb
  config/initializers/vets360.rb
  lib/fakes/facilities_locator_service.rb
  lib/fakes/vets360_service.rb
  spec/services/external_api/facilities_locator_service_spec.rb
  spec/services/external_api/vets360_service_spec.rb
Labels: In-Progress, Ready-to-Merge

#8116 remove now-obsolete JudgeTask action references
  app/controllers/idt/api/v1/appeals_controller.rb
  app/controllers/tasks_controller.rb
  app/models/distribution.rb
  app/models/tasks/judge_task.rb
  spec/controllers/idt/api/appeals_controller_spec.rb
  spec/models/tasks/judge_task_spec.rb
Labels: In-Progress, Ready-to-Merge

#8137 Add full_address to Veteran model
  app/models/veteran.rb
Labels: In-Progress, Ready-to-Merge

#8147 fix detection of non-body transient errors
  app/models/end_product_establishment.rb
  spec/models/end_product_establishment_spec.rb
Labels: In-Progress

#8151 Revert "Lowell/7903 universal case title (#8118)"
  client/app/constants/AppConstants.js
  client/app/queue/AppealDocumentCount.jsx
  client/app/queue/CaseDetailsView.jsx
  client/app/queue/CaseSnapshot.jsx
  client/app/queue/CaseTitle.jsx
  client/app/queue/CaseTitleDetails.jsx
  client/app/queue/ReaderLink.jsx
  client/app/queue/components/AodBadge.jsx
  client/app/queue/components/HearingBadge.jsx
  client/app/queue/components/SpecialtyCaseBadge.jsx
  client/app/queue/components/TaskTable.jsx
  spec/feature/queue/ama_queue_spec.rb
  spec/feature/queue/case_details_spec.rb
Labels: In-Progress, Ready-to-Merge

#8093 Adding where to find documentation to the Caseflow README
  README.md
  doc/created.rid
Labels: In-Progress, Ready-to-Merge

#8104 Legacy opt-in UI
  app/jobs/claim_review_process_job.rb
  app/jobs/legacy_optin_process_job.rb
  app/models/appeal.rb
  app/models/claim_review.rb
  app/models/concerns/legacy_optinable.rb
  app/models/decision_review.rb
  app/models/issue.rb
  app/models/request_issue.rb
  client/app/intake/components/AddedIssue.jsx
  client/app/intake/pages/addIssues.jsx
  client/app/intake/pages/decisionReviewIntakeCompleted.jsx
  client/app/intake/util/issues.js
  client/app/styles/_intake.scss
  client/constants/INTAKE_STRINGS.json
  client/constants/VACOLS_DISPOSITIONS_BY_ID.json
  db/seeds.rb
  lib/fakes/bgs_service.rb
  lib/fakes/end_product_store.rb
  spec/factories/vacols/case_issue.rb
  spec/feature/intake/appeal_spec.rb
  spec/feature/intake/edit_spec.rb
  spec/feature/intake/higher_level_review_spec.rb
  spec/feature/intake/supplemental_claim_spec.rb
  spec/models/appeal_event_spec.rb
  spec/models/appeal_intake_spec.rb
  spec/models/appeal_spec.rb
  spec/models/end_product_establishment_spec.rb
  spec/models/higher_level_review_intake_spec.rb
  spec/models/higher_level_review_spec.rb
  spec/models/issue_spec.rb
  spec/models/legacy_appeal_spec.rb
  spec/models/legacy_issue_optin_spec.rb
  spec/models/request_issue_spec.rb
  spec/support/intake_helpers.rb
Labels: In-Progress, Ready-to-Merge

#8149 Update rubocop target ruby version (tomas/8148)
  .rubocop.yml
  app/controllers/application_controller.rb
  app/controllers/hearings/dockets_controller.rb
  app/controllers/home_controller.rb
  app/controllers/legacy_tasks_controller.rb
  app/controllers/organizations_controller.rb
  app/controllers/test/users_controller.rb
  app/jobs/fetch_documents_for_reader_user_job.rb
  app/jobs/sync_intake_job.rb
  app/jobs/sync_reviews_job.rb
  app/models/appeal.rb
  app/models/concerns/case_review_concern.rb
  app/models/decision_issue.rb
  app/models/decision_review.rb
  app/models/dispatch/task.rb
  app/models/document.rb
  app/models/end_product_establishment.rb
  app/models/establish_claim.rb
  app/models/form8.rb
  app/models/higher_level_review.rb
  app/models/intake.rb
  app/models/judge_case_assignment_to_attorney.rb
  app/models/legacy_appeal.rb
  app/models/legacy_tasks/legacy_task.rb
  app/models/ramp_election.rb
  app/models/ramp_election_intake.rb
  app/models/ramp_election_rollback.rb
  app/models/ramp_refiling.rb
  app/models/rating_issue.rb
  app/models/regional_office.rb
  app/models/request_issue.rb
  app/models/serializers/work_queue/appeal_serializer.rb
  app/models/supplemental_claim.rb
  app/models/task.rb
  app/models/tasks/attorney_task.rb
  app/models/tasks/bva_dispatch_task.rb
  app/models/tasks/generic_task.rb
  app/models/user_quota.rb
  app/models/vacols/case_hearing.rb
  app/models/veteran.rb
  app/services/document_fetcher.rb
  app/services/external_api/vbms_service.rb
  app/services/form8_pdf_service.rb
  bin/yarn
  ci-bin/concatenate-log.rb
  lib/helpers/sanitizers.rb
  spec/factories/vacols/case.rb
  spec/factories/vacols/staff.rb
  spec/models/ramp_refiling_intake_spec.rb
  spec/rails_helper.rb
  spec/support/intake_helpers.rb
Labels: In-Progress, Ready-to-Merge

#8161 include useful error context for AppealNotValidToClose
  app/services/appeal_repository.rb
Labels: In-Progress, Ready-to-Merge

#8136 add contestable issues
  app/models/contestable_issue.rb
  app/models/decision_review.rb
  app/models/decision_review_intake.rb
  app/models/request_issue.rb
  client/app/intake/actions/addIssues.js
  client/app/intake/components/AddIssuesModal.jsx
  client/app/intake/components/LegacyOptInModal.jsx
  client/app/intake/components/UntimelyExemptionModal.jsx
  client/app/intake/reducers/appeal.js
  client/app/intake/reducers/higherLevelReview.js
  client/app/intake/reducers/supplementalClaim.js
  client/app/intake/util/issues.js
  client/app/intakeEdit/reducers/index.js
  spec/factories/supplemental_claim.rb
  spec/feature/intake/appeal_spec.rb
  spec/feature/intake/edit_spec.rb
  spec/feature/intake/higher_level_review_spec.rb
  spec/feature/intake/supplemental_claim_spec.rb
  spec/models/contestable_issue_spec.rb
  spec/models/decision_review_spec.rb
Labels: In-Progress, Ready-to-Merge

#8123 Allow attorneys and judges to update benefit type for decision issues
  app/controllers/case_reviews_controller.rb
  app/models/concerns/case_review_concern.rb
  app/models/decision_issue.rb
  client/app/queue/SelectDispositionsView.jsx
  spec/controllers/case_reviews_controller_spec.rb
  spec/feature/queue/checkout_flows_spec.rb
Labels: In-Progress, Ready-to-Merge

#8158 hide completed tasks
  client/app/queue/selectors.js
Labels: In-Progress, Ready-to-Merge

#8159 Rename variable and add a TODO
  app/models/issue.rb
Labels: In-Progress, Ready-to-Merge

#8153 Fix judge decision issues
  app/controllers/case_reviews_controller.rb
  app/models/concerns/case_review_concern.rb
  client/app/components/RadioField.jsx
  client/app/queue/CaseDetailsView.jsx
  client/app/queue/EvaluateDecisionView.jsx
  client/app/queue/SelectDispositionsContainer.jsx
  client/app/queue/SelectRemandReasonsView.jsx
  client/app/queue/SubmitDecisionView.jsx
  client/app/queue/components/IssueRemandReasonsOptions.jsx
  spec/feature/queue/checkout_flows_spec.rb
  spec/rails_helper.rb
Labels: In-Progress, Ready-to-Merge

#8164 Fix bug that prevented colocated tasks from updating parent status
  app/models/task.rb
  app/models/tasks/quality_review_task.rb
  app/models/tasks/schedule_hearing_task.rb
  spec/feature/queue/colocated_task_queue_spec.rb
  spec/models/task_spec.rb
  spec/models/tasks/generic_task_spec.rb
Labels: In-Progress, Ready-to-Merge

#8099 Fixing lack of time in hearings
  app/controllers/hearings_controller.rb
  app/repositories/hearing_repository.rb
  client/app/hearingSchedule/containers/DailyDocketContainer.jsx
  spec/controllers/hearings_controller_spec.rb
  spec/repositories/hearing_repository_spec.rb
Labels: In-Progress, Ready-to-Merge

#8167 Prevent SCT cases from being distributed
  app/models/vacols/case.rb
  app/models/vacols/case_docket.rb
  spec/models/vacols/case_docket_spec.rb
Labels: In-Progress, Ready-to-Merge

#8166 Fix only one remand reason gets sent
  client/app/queue/SelectRemandReasonsView.jsx
  client/app/queue/components/ContestedIssues.jsx
  client/app/queue/components/IssueRemandReasonsOptions.jsx
  spec/feature/queue/checkout_flows_spec.rb
Labels: In-Progress, Ready-to-Merge

#8168 Set timeout to 5 min (new_documents and document_count) and catch error properly
  client/app/queue/AppealDocumentCount.jsx
  client/app/queue/QueueActions.js
  client/app/queue/constants.js
  client/app/queue/reducers.js
Labels: In-Progress, Ready-to-Merge

#8121 Locking hearing day
  app/controllers/hearings/hearing_day_controller.rb
  app/models/hearing_day.rb
  app/repositories/hearing_day_repository.rb
  app/repositories/hearing_repository.rb
  client/app/hearingSchedule/HearingScheduleApp.jsx
  client/app/hearingSchedule/actions.js
  client/app/hearingSchedule/components/DailyDocket.jsx
  client/app/hearingSchedule/constants.js
  client/app/hearingSchedule/containers/DailyDocketContainer.jsx
  client/app/hearingSchedule/reducers.js
  config/routes.rb
  db/migrate/20181205201428_add_lock_to_hearing_day.rb
  db/schema.rb
  spec/models/hearing_day_spec.rb
  spec/requests/hearing_day_spec.rb
Labels: In-Progress, Ready-to-Merge

#8117 Tomas/8063 move to judge team model
  app/models/distribution.rb
  app/models/judge.rb
  app/models/organizations/judge_team.rb
  app/models/task.rb
  app/models/user.rb
  db/seeds.rb
  lib/constants/attorney_judge_teams.rb
  spec/controllers/users_controller_spec.rb
  spec/feature/queue/judge_assignment_spec.rb
  spec/models/distribution_spec.rb
  spec/models/judge_spec.rb
  spec/models/judge_team_spec.rb
  spec/models/user_spec.rb
Labels: In-Progress, Ready-to-Merge

#8193 New task loading indicator on AssignHearingsModal
  client/app/queue/components/AssignHearingModal.jsx
  client/app/queue/components/EditModalBase.jsx
Labels: In-Progress, Ready-to-Merge

#8143 Delete hearing day | Error handling
  client/app/hearingSchedule/actions.js
  client/app/hearingSchedule/components/DailyDocket.jsx
  client/app/hearingSchedule/constants.js
  client/app/hearingSchedule/containers/DailyDocketContainer.jsx
  client/app/hearingSchedule/reducers.js
Labels: In-Progress, Ready-to-Merge

#8154 Assigns video hearings to all video hearing rooms
  app/services/hearing_schedule/generate_hearing_days_schedule.rb
Labels: In-Progress, Ready-to-Merge

#8198 Fix flakey judge assignment test
  spec/feature/queue/judge_assignment_spec.rb
Labels: In-Progress, Ready-to-Merge

#8160 Move cases with assigned admin actions to attorneys on hold tab for legacy cases
  client/app/queue/AttorneyTaskListView.jsx
  client/app/queue/selectors.js
  spec/feature/queue/ama_queue_spec.rb
  spec/feature/queue/case_assignment_spec.rb
Labels: In-Progress, Ready-to-Merge

#8205 Bugfix: Restrict membership of Hearings Management team
  app/models/organizations/hearings_management.rb
  spec/controllers/tasks_controller_spec.rb
  spec/models/tasks/schedule_hearing_task_spec.rb
Labels: In-Progress, Ready-to-Merge

#8208 Prevent Scheduling Hearings if there is an Open Hearing
  app/models/tasks/root_task.rb
  client/app/queue/components/AssignHearingModal.jsx
Labels: In-Progress, Ready-to-Merge

#8203 Remove old AMA Intake finish page code
  app/models/appeal_intake.rb
  app/models/claim_review_intake.rb
  app/views/intakes/index.html.erb
  client/app/intake/IntakeFrame.jsx
  client/app/intake/pages/appeal/finish.jsx
  client/app/intake/pages/finish.jsx
  client/app/intake/pages/higherLevelReview/finish.jsx
  client/app/intake/pages/review.jsx
  client/app/intake/pages/supplementalClaim/finish.jsx
  client/app/intake/reducers/appeal.js
  client/app/intake/reducers/featureToggles.js
  client/app/intake/reducers/higherLevelReview.js
  client/app/intake/reducers/supplementalClaim.js
  client/app/intake/util/index.js
  spec/feature/intake/appeal_spec.rb
  spec/feature/intake/higher_level_review_spec.rb
  spec/feature/intake/ramp_election_spec.rb
  spec/feature/intake/ramp_refiling_spec.rb
  spec/feature/intake/supplemental_claim_spec.rb
  spec/models/appeal_intake_spec.rb
  spec/models/higher_level_review_intake_spec.rb
  spec/models/supplemental_claim_intake_spec.rb
  spec/support/intake_helpers.rb
Labels: In-Progress, Ready-to-Merge

#8165 save contested decision issues
  app/controllers/regional_offices_controller.rb
  app/models/contestable_issue.rb
  app/models/rating_issue.rb
  app/models/request_issue.rb
  app/models/request_issues_update.rb
  client/app/intake/actions/addIssues.js
  client/app/intake/components/AddedIssue.jsx
  client/app/intake/pages/addIssues.jsx
  client/app/intake/reducers/appeal.js
  client/app/intake/reducers/higherLevelReview.js
  client/app/intake/reducers/supplementalClaim.js
  client/app/intake/util/issues.js
  client/app/intakeEdit/reducers/index.js
  spec/controllers/regional_offices_controller_spec.rb
  spec/feature/intake/edit_spec.rb
  spec/feature/intake/higher_level_review_spec.rb
  spec/models/appeal_intake_spec.rb
  spec/models/contestable_issue_spec.rb
  spec/models/decision_review_spec.rb
  spec/models/higher_level_review_intake_spec.rb
  spec/models/request_issue_spec.rb
  spec/models/request_issues_update_spec.rb
  spec/models/supplemental_claim_intake_spec.rb
  spec/support/intake_helpers.rb
Labels: In-Progress, Ready-to-Merge

#8200 Add docs for Asyncable model and rationale
  app/models/concerns/asyncable.rb
  docs/asyncable-models.md
Labels: In-Progress, Ready-to-Merge

#8219 Return an Error object instead of hash
  client/app/queue/EvaluateDecisionView.jsx
  client/app/queue/QueueActions.js
  client/app/queue/uiReducer/uiActions.js
Labels: In-Progress, Ready-to-Merge

#8100 Add / Edit a Hearing Day
  app/controllers/hearings/hearing_day_controller.rb
  app/controllers/users_controller.rb
  app/mappers/hearing_day_mapper.rb
  app/models/hearing_day.rb
  app/models/user.rb
  app/models/vacols/case_hearing.rb
  app/repositories/user_repository.rb
  client/app/components/RoSelectorDropdown.jsx
  client/app/hearingSchedule/actions.js
  client/app/hearingSchedule/components/DailyDocket.jsx
  client/app/hearingSchedule/components/HearingDayAddModal.jsx
  client/app/hearingSchedule/components/HearingDayEditModal.jsx
  client/app/hearingSchedule/components/ListSchedule.jsx
  client/app/hearingSchedule/constants.js
  client/app/hearingSchedule/containers/DailyDocketContainer.jsx
  client/app/hearingSchedule/containers/ListScheduleContainer.jsx
  client/app/hearingSchedule/reducers.js
  client/app/hearingSchedule/utils.js
  client/constants/USER_ROLE_TYPES.json
  db/migrate/20181206130120_add_notes_to_hearing_day.rb
  db/schema.rb
  db/seeds.rb
  lib/constants/ramp_judges.rb
  spec/controllers/users_controller_spec.rb
  spec/factories/vacols/staff.rb
  spec/requests/hearing_day_spec.rb
Labels: In-Progress

#8230 Rename ClaimReviewProcessJob to DecisionReviewProcessJob
  app/jobs/decision_review_process_job.rb
  app/jobs/sync_reviews_job.rb
  app/models/appeal.rb
  app/models/claim_review.rb
  app/models/claim_review_intake.rb
  app/models/decision_review.rb
  app/models/higher_level_review.rb
  app/models/request_issues_update.rb
  spec/feature/intake/edit_spec.rb
  spec/jobs/decision_review_process_job_spec.rb
  spec/jobs/sync_reviews_job_spec.rb
  spec/models/claim_review_spec.rb
  spec/models/higher_level_review_intake_spec.rb
  spec/models/supplemental_claim_intake_spec.rb
Labels: In-Progress, Ready-to-Merge

#8237 Fix disposition error
  client/app/queue/SelectRemandReasonsView.jsx
Labels: In-Progress, Ready-to-Merge

#8243 Reduce the number of items copied from parent payload to child payload.
  app/repositories/hearing_repository.rb
Labels: In-Progress

#8232 Asyncable appeals
  app/models/appeal.rb
  app/models/appeal_intake.rb
  app/models/claim_review.rb
  app/models/decision_review.rb
  db/migrate/20181212150819_add_asyncable_to_appeals.rb
  db/schema.rb
  spec/models/appeal_intake_spec.rb
  spec/models/appeal_spec.rb
Labels: In-Progress, Ready-to-Merge

#8250 Modal does not close when clicking the X. Due to missing…
  client/app/hearingSchedule/components/HearingDayEditModal.jsx
Labels: In-Progress

#8246 Add BVATWARNER to Hearings Management Organization in Local Seed
  db/seeds.rb
Labels: In-Progress

#8254 Bump connect_vbms version to get XML escaping fix for RAMP contentions
  Gemfile
  Gemfile.lock
Labels: In-Progress, Ready-to-Merge

#8209 Backend cleanup
  app/controllers/hearings/hearing_day_controller.rb
  app/controllers/regional_offices_controller.rb
  app/mappers/hearing_day_mapper.rb
  app/mappers/hearing_mapper.rb
  app/models/hearing.rb
  app/models/hearing_day.rb
  app/models/ro_schedule_period.rb
  app/models/serializers/hearings/hearing_day_serializer.rb
  app/models/vacols/case_hearing.rb
  app/repositories/hearing_day_repository.rb
  app/repositories/hearing_repository.rb
  app/services/hearing_schedule/assign_judges_to_hearing_days.rb
  client/app/hearingSchedule/components/AssignHearings.jsx
  client/app/hearingSchedule/components/ListSchedule.jsx
  client/app/hearingSchedule/components/ReviewAssignments.jsx
  client/app/hearingSchedule/containers/DailyDocketContainer.jsx
  db/migrate/20181211201506_rename_room_info.rb
  db/schema.rb
  spec/controllers/hearings_controller_spec.rb
  spec/factories/hearing_day.rb
  spec/models/hearing_day_spec.rb
  spec/models/judge_schedule_period_spec.rb
  spec/models/schedule_period_spec.rb
  spec/requests/hearing_day_spec.rb
  spec/services/hearing_schedule/assign_judges_to_hearing_days_spec.rb
Labels: In-Progress, Ready-to-Merge

#8256 Refactor way we are uploading hearing coordinators
  app/repositories/user_repository.rb
Labels: In-Progress

#8248 Tomas/8015 Simplify task auth logic
  app/models/task.rb
  app/models/tasks/colocated_task.rb
  app/models/tasks/generic_task.rb
  app/models/tasks/judge_task.rb
  app/models/tasks/mail_task.rb
  app/models/tasks/root_task.rb
  app/models/tasks/schedule_hearing_task.rb
  spec/controllers/tasks_controller_spec.rb
  spec/models/task_spec.rb
  spec/models/tasks/generic_task_spec.rb
  spec/spec_helper.rb
Labels: In-Progress, Ready-to-Merge

#8285 Implement hearing room list as a json file that may be shared by both front-end and back-end code.
  app/models/hearing_rooms.rb
  client/app/hearingSchedule/components/HearingDayEditModal.jsx
  client/constants/HEARING_ROOMS_LIST.json
Labels: In-Progress

#8115 Add methods to find all AOD and all non-AOD appeals
  app/models/advance_on_docket_motion.rb
  app/models/appeal.rb
  app/models/claimant.rb
  app/models/person.rb
  spec/controllers/tasks_controller_spec.rb
  spec/factories/appeal.rb
  spec/factories/claimant.rb
  spec/factories/person.rb
  spec/feature/queue/ama_queue_spec.rb
  spec/models/appeal_spec.rb
  spec/models/claimant_spec.rb
Labels: In-Progress, Ready-to-Merge

#8264 decision issue nonrating
  app/models/appeal.rb
  app/models/claim_review.rb
  app/models/contestable_issue.rb
  app/models/decision_issue.rb
  spec/factories/request_issue.rb
  spec/feature/intake/edit_spec.rb
  spec/models/decision_issue_spec.rb
  spec/models/decision_review_spec.rb
  spec/support/intake_helpers.rb
Labels: In-Progress, Ready-to-Merge

#8290 epe does not have run_async
  app/models/end_product_establishment.rb
Labels: In-Progress, Ready-to-Merge

#8293 convert established_at to date to work with rating api
  app/models/end_product_establishment.rb
Labels: In-Progress, Ready-to-Merge

#8292 ineligible decision issues
  app/models/contestable_issue.rb
  app/models/decision_issue.rb
  app/models/request_issue.rb
  spec/factories/higher_level_review.rb
  spec/feature/intake/edit_spec.rb
Labels: In-Progress, Ready-to-Merge

#8297 Fix bug with creating decision issues from dispositions
  app/models/request_issue.rb
Labels: In-Progress

#8298 Fix another bug with dispositions
  app/models/request_issue.rb
Labels: In-Progress

#8282 Remove extra RootTask method
  app/models/tasks/root_task.rb
  spec/factories/task.rb
  spec/models/tasks/schedule_hearing_task_spec.rb
Labels: In-Progress

#8302 Fix flakey Legacy automatic case distribution test
  spec/models/vacols/case_docket_spec.rb
Labels: In-Progress

#8309 Flakey test fix, array order nondeterministic
  spec/models/claim_review_spec.rb
Labels: In-Progress

#8105 Enable VLJ support staff to send all ColocatedTasks to Privacy Team
  app/models/organizations/privacy_team.rb
  app/models/task.rb
  app/models/tasks/colocated_task.rb
  client/app/queue/AssignToView.jsx
  client/app/queue/QueueApp.jsx
  client/constants/TASK_ACTIONS.json
  lib/caseflow/error.rb
  spec/controllers/tasks_controller_spec.rb
  spec/feature/queue/privacy_team_spec.rb
  spec/models/task_spec.rb
Labels: In-Progress

#8287 Don’t show AMA decision Note section when empty
  client/app/queue/components/ContestedIssues.jsx
  spec/feature/queue/case_details_spec.rb
Labels: In-Progress

#8322 Creating legacy hearings table
  app/models/legacy_hearing.rb
  db/migrate/20181217195658_create_legacy_hearings.rb
  db/schema.rb
Labels: In-Progress

#8325 used wrong method
  app/models/contestable_issue.rb
Labels: In-Progress, Ready-to-Merge

#8315 Use receipt_date to determine legacy eligibility
  app/models/decision_review.rb
  app/models/issue.rb
  app/models/legacy_appeal.rb
  app/models/request_issue.rb
  client/app/intake/components/LegacyOptInModal.jsx
  spec/feature/intake/appeal_spec.rb
  spec/feature/intake/higher_level_review_spec.rb
  spec/feature/intake/supplemental_claim_spec.rb
  spec/models/legacy_appeal_spec.rb
Labels: In-Progress, Ready-to-Merge

#8252 Permission checks
  app/controllers/hearings/hearing_day_controller.rb
  app/repositories/hearing_repository.rb
Labels: In-Progress, Ready-to-Merge

#8274 Add AHLs to RegionalOffice model
  app/models/regional_office.rb
Labels: In-Progress, Ready-to-Merge

#8305 detect more transient bgs errors, encode as utf-8
  app/models/end_product_establishment.rb
Labels: In-Progress, Ready-to-Merge

#8314 Better Schedule Hearing Modal Validation
  client/app/components/HearingDayDropdown.jsx
  client/app/queue/components/AssignHearingModal.jsx
Labels: In-Progress, Ready-to-Merge

#8324 Fix symbol value to :central to coincide with value in the declared constant HEARING_TYPES.
  app/mappers/hearing_mapper.rb
  app/models/hearing.rb
  spec/mappers/hearing_mapper_spec.rb
  spec/models/hearing_spec.rb
  spec/requests/hearing_day_spec.rb
Labels: In-Progress, Ready-to-Merge

#8291 No End Products on non-comp SC and HLR
  app/models/appeal.rb
  app/models/claim_review.rb
  app/models/decision_review.rb
  app/models/decision_review_intake.rb
  client/app/intake/pages/higherLevelReview/finish.jsx
  client/app/intake/pages/supplementalClaim/finish.jsx
  client/app/intake/reducers/appeal.js
  client/app/intake/reducers/higherLevelReview.js
  client/app/intake/reducers/supplementalClaim.js
  spec/factories/higher_level_review.rb
  spec/factories/supplemental_claim.rb
  spec/feature/intake/higher_level_review_spec.rb
  spec/feature/intake/supplemental_claim_spec.rb
  spec/models/claim_review_spec.rb
  spec/models/higher_level_review_intake_spec.rb
  spec/models/supplemental_claim_intake_spec.rb
Labels: In-Progress, Ready-to-Merge

#8304 capture RampRefiling id when reprocessing fails
  app/jobs/sync_reviews_job.rb
Labels: In-Progress, Ready-to-Merge

#8327 Writing to legacy_hearings and hearings
  app/models/hearing.rb
  app/models/legacy_hearing.rb
  spec/models/hearing_spec.rb
Labels: In-Progress, Ready-to-Merge

#8332 Fix decision issues being sent to server
  client/app/queue/SelectRemandReasonsView.jsx
Labels: In-Progress, Ready-to-Merge

#8342 Removed restrictions for displaying additional hearing attributes when no disposition set.
  client/app/queue/CaseHearingsDetail.jsx
Labels: In-Progress

#8267 Feature Tests | Slotting veterans
  spec/factories/vacols/case.rb
  spec/feature/hearing_schedule/schedule_veteran_spec.rb
Labels: In-Progress, Ready-to-Merge

#8301 adding active nonrating issues to modal
  app/models/appeal.rb
  app/models/claim_review.rb
  app/models/decision_review.rb
  app/models/decision_review_intake.rb
  app/models/request_issue.rb
  client/app/intake/actions/addIssues.js
  client/app/intake/components/AddedIssue.jsx
  client/app/intake/components/NonratingRequestIssueModal.jsx
  client/app/intake/pages/decisionReviewIntakeCompleted.jsx
  client/app/intake/reducers/appeal.js
  client/app/intake/reducers/higherLevelReview.js
  client/app/intake/reducers/supplementalClaim.js
  client/app/intake/util/issues.js
  client/app/intakeEdit/reducers/index.js
  client/app/styles/_intake.scss
  client/constants/INELIGIBLE_REQUEST_ISSUES.json
  db/migrate/20181218214242_request_issue_enum_rename_reason.rb
  db/migrate/20181219005124_add_veteran_participant_id_to_request_issues.rb
  db/schema.rb
  spec/factories/request_issue.rb
  spec/feature/intake/appeal_spec.rb
  spec/feature/intake/edit_spec.rb
  spec/feature/intake/higher_level_review_spec.rb
  spec/feature/intake/supplemental_claim_spec.rb
  spec/models/request_issue_spec.rb
  spec/support/intake_helpers.rb
Labels: In-Progress, Ready-to-Merge

#8355 Tomas/create feature helper module
  spec/feature/hearing_schedule/schedule_veteran_spec.rb
  spec/feature/queue/case_assignment_spec.rb
  spec/feature/queue/checkout_flows_spec.rb
  spec/feature/queue/judge_assignment_spec.rb
  spec/rails_helper.rb
  spec/support/feature_helper.rb
Labels: In-Progress, Ready-to-Merge

#8312 Add more BE validations for judge checkout
  app/models/appeal.rb
  app/models/attorney_case_review.rb
  app/models/concerns/case_review_concern.rb
  app/models/concerns/issue_updater.rb
  app/models/decision_issue.rb
  app/models/judge_case_review.rb
  app/repositories/remand_reason_repository.rb
  lib/caseflow/error.rb
  spec/controllers/case_reviews_controller_spec.rb
  spec/models/appeal_spec.rb
  spec/models/attorney_case_review_spec.rb
  spec/models/decision_review_spec.rb
  spec/repositories/remand_reason_repository_spec.rb
Labels: In-Progress, Ready-to-Merge

#8347 Rename Decision to DecisionDocument
  app/models/appeal.rb
  app/models/decision_document.rb
  app/models/tasks/bva_dispatch_task.rb
  db/migrate/20181218173534_rename_decisions_to_decision_documents.rb
  db/schema.rb
  spec/models/decision_document_spec.rb
  spec/models/tasks/bva_dispatch_task_spec.rb
Labels: In-Progress, Ready-to-Merge

#8311 Fix alignment of errors in the reader sidebar
  client/app/reader/SideBarComments.jsx
  client/app/styles/reader/_reviewer.scss
Labels: In-Progress, Ready-to-Merge

#8350 Drop rating_issues table
  db/migrate/20181218214725_drop_rating_issues.rb
  db/schema.rb
Labels: In-Progress, Ready-to-Merge

#8362 Flakey schedule veteran feature test
  spec/feature/hearing_schedule/schedule_veteran_spec.rb
Labels: In-Progress, Ready-to-Merge

#8345 Non comp reviews landing page
  app/controllers/decision_reviews_controller.rb
  app/models/appeal.rb
  app/models/decision_review.rb
  app/models/organizations/business_line.rb
  app/models/serializers/work_queue/decision_review_serializer.rb
  app/models/serializers/work_queue/task_serializer.rb
  app/models/tasks/decision_review_task.rb
  config/routes.rb
  db/seeds.rb
  scripts/enable_features_dev.rb
  spec/controllers/decision_reviews_controller_spec.rb
  spec/factories/organization.rb
  spec/factories/task.rb
  spec/models/tasks/decision_review_task_spec.rb
Labels: In-Progress, Ready-to-Merge

#8351 Tomas/7935 Return user to case details page after creating mail task
  client/COPY.json
  client/app/queue/AssignToView.jsx
  client/app/queue/QueueApp.jsx
  client/app/queue/components/EditModalBase.jsx
  db/seeds.rb
  spec/feature/queue/task_queue_spec.rb
Labels: In-Progress, Ready-to-Merge

#8378 remove bootsnap to debug deployments
  Gemfile
  Gemfile.lock
  config/boot.rb
Labels: In-Progress, Ready-to-Merge

#8384 Revert "remove bootsnap to debug deployments (#8378)"
  Gemfile
  Gemfile.lock
  config/boot.rb
Labels: In-Progress, Ready-to-Merge

#8385 update veteran not found error message
  client/app/intake/pages/search.jsx
Labels: In-Progress

#8387 View Schedule | Dates include the day
  client/app/hearingSchedule/components/ListSchedule.jsx
Labels: In-Progress

#8356 Remove rails_stdout_logging gem
  Gemfile
  Gemfile.lock
Labels: Ready-to-Merge

#8353 Code cleanup to prep for AMA hearing schedule
  app/controllers/appeals_controller.rb
  app/controllers/hearings/hearing_day_controller.rb
  client/app/hearingSchedule/actions.js
  client/app/hearingSchedule/components/AssignHearings.jsx
  client/app/hearingSchedule/constants.js
  client/app/hearingSchedule/containers/AssignHearingsContainer.jsx
  client/app/hearingSchedule/reducers.js
  config/routes.rb
  spec/controllers/appeals_controller_spec.rb
  spec/requests/hearing_day_spec.rb
Labels: In-Progress, Ready-to-Merge

#8392 Schedule flakey test
  spec/feature/hearing_schedule/schedule_veteran_spec.rb
Labels: In-Progress

#8383 make task table work with custom fields
  client/app/nonComp/components/NonCompTabs.jsx
  client/app/nonComp/components/TaskTableColumns.jsx
  client/app/queue/components/TaskTable.jsx
Labels: In-Progress, Ready-to-Merge

#8260 Add Pension EP codes
  app/models/claim_review.rb
  app/models/end_product.rb
  app/models/higher_level_review.rb
  app/models/supplemental_claim.rb
  spec/feature/intake/edit_spec.rb
  spec/feature/intake/higher_level_review_spec.rb
  spec/models/claim_review_spec.rb
  spec/models/end_product_establishment_spec.rb
  spec/models/higher_level_review_intake_spec.rb
  spec/models/higher_level_review_spec.rb
  spec/models/request_issue_spec.rb
  spec/models/supplemental_claim_spec.rb
Labels: In-Progress, Ready-to-Merge

#8272 Lock hearing day | Error handling
  client/app/hearingSchedule/actions.js
  client/app/hearingSchedule/components/DailyDocket.jsx
  client/app/hearingSchedule/constants.js
  client/app/hearingSchedule/containers/DailyDocketContainer.jsx
  client/app/hearingSchedule/reducers.js
Labels: In-Progress

#8349 Convert decass notes to ASCII before saving to DB
  Gemfile
  Gemfile.lock
  app/mappers/queue_mapper.rb
  app/repositories/queue_repository.rb
  spec/mappers/queue_mapper_spec.rb
  spec/models/attorney_case_review_spec.rb
  spec/repositories/queue_repository_spec.rb
Labels: In-Progress

#8381 Process decision document upload in separate job
  app/jobs/process_decision_document_job.rb
  app/jobs/sync_reviews_job.rb
  app/models/concerns/asyncable.rb
  app/models/decision_document.rb
  app/models/tasks/bva_dispatch_task.rb
  db/migrate/20181219153145_add_asyncable_columns_to_decision_document.rb
  db/schema.rb
  spec/controllers/idt/api/appeals_controller_spec.rb
  spec/factories/decision_document.rb
  spec/jobs/process_decision_document_job_spec.rb
  spec/jobs/sync_reviews_job_spec.rb
  spec/models/decision_document_spec.rb
  spec/models/tasks/bva_dispatch_task_spec.rb
  spec/rails_helper.rb
Labels: In-Progress, Ready-to-Merge

#8400 Formatting Assign Hearings page for AMA appeals
  client/app/hearingSchedule/components/AssignHearings.jsx
  spec/feature/hearing_schedule/schedule_veteran_spec.rb
Labels: In-Progress, Ready-to-Merge

#8181 UI for multiple request issue <-> single decision issue
  app/models/serializers/work_queue/appeal_serializer.rb
  client/COPY.json
  client/app/components/RenderFunctions.jsx
  client/app/queue/SelectDispositionsView.jsx
  client/app/queue/components/ContestedIssues.jsx
  client/app/queue/components/IssueRemandReasonsOptions.jsx
  client/app/queue/components/SelectIssueDispositionDropdown.jsx
  client/app/queue/types/models.js
  spec/feature/queue/checkout_flows_spec.rb
Labels: In-Progress, Ready-to-Merge

#8398 Edit Modal - Initial state was not being set properly. Options were not being passed in correct format.
  client/app/hearingSchedule/containers/DailyDocketContainer.jsx
Labels: In-Progress

#8407 [bugfix] Show correct actions if judge assigns a QR task to an attorney
  app/models/tasks/judge_assign_task.rb
  app/models/tasks/judge_review_task.rb
  app/models/tasks/judge_task.rb
  spec/models/tasks/judge_task_spec.rb
Labels: In-Progress, Ready-to-Merge

#8389 Serialize decision review tasks with ActiveSerializer
  app/controllers/decision_reviews_controller.rb
  app/models/serializers/work_queue/decision_review_task_serializer.rb
  app/models/tasks/decision_review_task.rb
  app/views/decision_reviews/index.html.erb
  spec/feature/non_comp/non_comp_spec.rb
  spec/models/serializers/work_queue/decision_review_task_serializer_spec.rb
Labels: In-Progress, Ready-to-Merge

#8404 stop disappearing tasks attached to appeals w/documents
  app/models/queues/attorney_queue.rb
  client/app/queue/selectors.js
  spec/feature/queue/task_queue_spec.rb
Labels: In-Progress, Ready-to-Merge

#8346 Reading from legacy hearings
  app/controllers/hearings/worksheets_controller.rb
  app/controllers/hearings_controller.rb
  app/models/appeal_stream_snapshot.rb
  app/models/concerns/hearing_concern.rb
  app/models/hearing.rb
  app/models/hearing_view.rb
  app/models/judge.rb
  app/models/legacy_appeal.rb
  app/models/legacy_hearing.rb
  app/models/tasks/schedule_hearing_task.rb
  app/models/user.rb
  app/repositories/hearing_repository.rb
  app/repositories/queue_repository.rb
  app/services/appeal_repository.rb
  lib/generators/legacy_hearing.rb
  spec/controllers/hearings/worksheets_controller_spec.rb
  spec/controllers/hearings_controller_spec.rb
  spec/factories/legacy_hearing.rb
  spec/feature/hearings_spec.rb
  spec/models/appeal_event_spec.rb
  spec/models/hearing_docket_spec.rb
  spec/models/judge_spec.rb
  spec/models/legacy_hearing_spec.rb
  spec/repositories/hearing_repository_spec.rb
Labels: In-Progress, Ready-to-Merge

#8406 Add Modal state bugs.
  client/app/hearingSchedule/containers/DailyDocketContainer.jsx
  client/app/hearingSchedule/containers/ListScheduleContainer.jsx
Labels: In-Progress, Ready-to-Merge

#8281 7682/task snapshot component mvp
  client/COPY.json
  client/app/queue/CaseDetailsView.jsx
  client/app/queue/CaseTitleDetails.jsx
  client/app/queue/EvaluateDecisionView.jsx
  client/app/queue/StickyNavContentArea.jsx
  client/app/queue/TaskSnapshot.jsx
  spec/feature/queue/case_details_spec.rb
  spec/feature/queue/task_queue_spec.rb
Labels: In-Progress, Ready-to-Merge

#8343 Remove Reader Welcome Gate
  app/controllers/reader/appeal_controller.rb
  client/app/reader/CaseSelect.jsx
  client/app/reader/CaseSelectLoadingScreen.jsx
  client/app/reader/CaseSelectSearch.jsx
  client/app/reader/DecisionReviewer.jsx
  spec/controllers/reader/appeal_controller_spec.rb
  spec/requests/appeal_controller_spec.rb
Labels: In-Progress, Ready-to-Merge

#8413 Updating increment value on legacy_hearings
  db/migrate/20181221164327_update_legacy_hearing_increment.rb
  db/schema.rb
Labels: In-Progress

#8409 Dropping hearings :joy:
  app/models/hearing.rb
  app/models/legacy_hearing.rb
  db/migrate/20181221151935_drop_hearings_table.rb
  db/schema.rb
  spec/models/legacy_hearing_spec.rb
Labels: In-Progress

#8419 Create Transcription team organization
  app/models/organizations/transcription_team.rb
Labels: In-Progress, Ready-to-Merge

#8422 CO Room Logic.
  app/controllers/hearings/hearing_day_controller.rb
  spec/requests/hearing_day_spec.rb
Labels: In-Progress

#8403 Add non-compensation issue categories
  client/app/intake/components/NonratingRequestIssueModal.jsx
  client/app/intake/components/NonratingRequestIssues.jsx
  client/app/intake/components/RatingRequestIssues.jsx
  client/app/intake/constants.js
  client/constants/ISSUE_CATEGORIES.json
  spec/feature/intake/higher_level_review_spec.rb
  spec/feature/intake/nonrating_request_issue_modal_spec.rb
  spec/feature/intake/supplemental_claim_spec.rb
  spec/support/intake_helpers.rb
Labels: In-Progress, Ready-to-Merge

#8276 [WIP] Alert for VVA and VBMS document list retrievals
  app/services/document_fetcher.rb
  client/app/reader/LastRetrievalAlert.jsx
  client/app/reader/LastRetrievalInfo.jsx
  client/app/reader/PdfListView.jsx
  config/initializers/vbms.rb
  spec/feature/reader/reader_spec.rb
  spec/services/document_fetcher_spec.rb
  spec/services/external_api/efolder_service_spec.rb
Labels: In-Progress, Ready-to-Merge

#8424 Noncomp landing page
  app/models/serializers/work_queue/decision_review_task_serializer.rb
  client/app/nonComp/components/NonCompTabs.jsx
  client/app/nonComp/components/TaskTableColumns.jsx
  client/app/nonComp/pages/NonCompPage.jsx
  client/app/nonComp/reducers/index.js
  client/app/nonComp/util/index.js
  spec/feature/non_comp/non_comp_spec.rb
  spec/models/serializers/work_queue/decision_review_task_serializer_spec.rb
Labels: In-Progress, Ready-to-Merge

#8294 Reopen closed legacy issues if request issue is removed
  app/mappers/issue_mapper.rb
  app/models/appeal.rb
  app/models/claim_review.rb
  app/models/concerns/legacy_optinable.rb
  app/models/decision_review.rb
  app/models/issue.rb
  app/models/legacy_appeal.rb
  app/models/legacy_issue_optin.rb
  app/models/request_issue.rb
  app/models/request_issues_update.rb
  app/repositories/remand_reason_repository.rb
  app/services/appeal_repository.rb
  app/services/legacy_optin_manager.rb
  db/migrate/20181213191137_add_vacols_issue_and_disposition_to_legacy_issue_opt_ins.rb
  db/migrate/20181214003212_add_index_to_prevent_duplicate_legacy_issue_opt_ins.rb
  db/schema.rb
  spec/factories/legacy_issue_optin.rb
  spec/factories/vacols/case.rb
  spec/factories/vacols/case_issue.rb
  spec/feature/intake/edit_spec.rb
  spec/feature/intake/higher_level_review_spec.rb
  spec/models/appeal_intake_spec.rb
  spec/models/appeal_spec.rb
  spec/models/higher_level_review_intake_spec.rb
  spec/models/higher_level_review_spec.rb
  spec/models/issue_spec.rb
  spec/models/request_issues_update_spec.rb
  spec/models/supplemental_claim_intake_spec.rb
  spec/models/supplemental_claim_spec.rb
  spec/services/legacy_optin_manager_spec.rb
Labels: In-Progress, Ready-to-Merge

#8427 Reduce number of VACOLS requests when calling tasks endpoints
  app/controllers/tasks_controller.rb
  app/services/appeal_repository.rb
Labels: In-Progress

#8391 Display link to edit request issues
  app/controllers/appeals_controller.rb
  app/models/appeal.rb
  app/models/serializers/work_queue/appeal_serializer.rb
  app/models/user.rb
  client/COPY.json
  client/app/queue/CaseDetailsView.jsx
  client/app/queue/StickyNavContentArea.jsx
  client/app/queue/utils.js
  spec/feature/queue/checkout_flows_spec.rb
  spec/models/user_spec.rb
Labels: In-Progress, Ready-to-Merge

#8441 Move condition to decide if we show/hide task action dropdown to backend
  app/models/legacy_tasks/attorney_legacy_task.rb
  client/app/queue/TaskSnapshot.jsx
  spec/feature/queue/case_details_spec.rb
Labels: In-Progress, Ready-to-Merge

#8412 Persist legacy and Caseflow tasks when loading case details page (PR)
  app/controllers/tasks_controller.rb
  app/models/legacy_tasks/legacy_task.rb
  app/models/task.rb
  client/app/queue/CaseDetailsLoadingScreen.jsx
  spec/controllers/tasks_controller_spec.rb
  spec/feature/queue/case_details_spec.rb
Labels: In-Progress, Ready-to-Merge

#8443 Remove unused response status
  app/controllers/tasks_controller.rb
  spec/controllers/tasks_controller_spec.rb
Labels: In-Progress, Ready-to-Merge

#8446 Add padding to new file icon
  client/app/queue/ReaderLink.jsx
Labels: In-Progress

#8444 Only return tasks from LegacyWorkQueue methods
  app/controllers/idt/api/v1/appeals_controller.rb
  app/controllers/legacy_tasks_controller.rb
  app/controllers/tasks_controller.rb
  app/models/queues/legacy_work_queue.rb
  spec/feature/queue/case_details_spec.rb
  spec/models/queues/legacy_work_queue_spec.rb
Labels: In-Progress, Ready-to-Merge

#8449 Schedule veteran test
  spec/feature/hearing_schedule/schedule_veteran_spec.rb
Labels: In-Progress

#8445 Consolidate Queue classes
  app/controllers/tasks_controller.rb
  app/models/queues/colocated_queue.rb
  app/models/queues/generic_queue.rb
  app/models/queues/judge_queue.rb
  app/models/task.rb
  app/models/tasks/colocated_task.rb
  spec/controllers/tasks_controller_spec.rb
  spec/feature/queue/task_queue_spec.rb
  spec/models/queues/generic_queue_spec.rb
Labels: In-Progress, Ready-to-Merge

#8450 Anya/8339 checkout test snow flake
  spec/feature/queue/checkout_flows_spec.rb
Labels: In-Progress, Ready-to-Merge

#8452 Remove role parameter from request to tasks endpoint
  app/controllers/tasks_controller.rb
  client/app/queue/QueueActions.js
Labels: In-Progress, Ready-to-Merge

#8457 Strip whitespaces document ID
  app/models/attorney_case_review.rb
  spec/models/attorney_case_review_spec.rb
Labels: In-Progress, Ready-to-Merge

#8326 Show multiple tasks in active tasks component
  client/app/queue/TaskSnapshot.jsx
  spec/feature/queue/case_details_spec.rb
Labels: In-Progress

#8380 [WIP] Improve document count and new documents performance
  app/jobs/fetch_documents_for_reader_user_job.rb
  spec/jobs/fetch_documents_for_reader_user_spec.rb
Labels: In-Progress, Ready-to-Merge

#7742 Improve appearance of on hold label for tasks with no on_hold_duratio…
  client/app/queue/components/OnHoldLabel.jsx
Labels: In-Progress, Ready-to-Merge

#8465 shallow clone
  Jenkinsfile
Labels: In-Progress, Ready-to-Merge

#8469 Remove unused feature toggles
  scripts/enable_features_dev.rb
  spec/controllers/tasks_controller_spec.rb
  spec/feature/intake/supplemental_claim_spec.rb
  spec/feature/queue/case_details_spec.rb
  spec/feature/queue/colocated_checkout_flow_spec.rb
Labels: In-Progress, Ready-to-Merge

#8466 Remove redundant date from legacy cases
  client/app/queue/TaskSnapshot.jsx
  spec/feature/queue/case_details_spec.rb
Labels: In-Progress, Ready-to-Merge
