Repository department-of-veterans-affairs/caseflow, pull requests merged in 2018-08, with the labels that each got.

#6453 Flow | Annotates CaseSnapshot
  client/app/queue/CaseSnapshot.jsx
  client/app/queue/components/JudgeActionsDropdown.jsx
Labels: In-Progress

#6458 Add rbenv to our CircleCI build container.
  ci-bin/circle_docker_container/Dockerfile
Labels: In-Progress, Ready-to-Merge

#6390 Allow AMA intakes when Veteran has no rated issues
  app/models/rating.rb
  client/app/intake/components/RatedIssues.jsx
  spec/feature/intake/appeal_spec.rb
  spec/feature/intake/higher_level_review_spec.rb
  spec/feature/intake/supplemental_claim_spec.rb
Labels: In-Progress, Ready-to-Merge

#6463 Handle single EP responses from bgs
  Gemfile
  Gemfile.lock
Labels: In-Progress

#6460 VLJ # in spreadsheet instead of css_id
  app/models/hearings/judge_non_availability.rb
  app/models/user.rb
  app/repositories/user_repository.rb
  app/services/hearing_schedule/get_spreadsheet_data.rb
  app/services/hearing_schedule/validate_judge_spreadsheet.rb
  db/seeds.rb
  public/JudgeAssignmentTemplate.xlsx
  spec/factories/judge_schedule_period.rb
  spec/services/hearing_schedule/validate_judge_spreadsheet_spec.rb
  spec/support/blankJudgeSpreadsheet.xlsx
  spec/support/judgeDuplicateDates.xlsx
  spec/support/judgeNotInDb.xlsx
  spec/support/judgeWrongDataType.xlsx
  spec/support/validJudgeSpreadsheet.xlsx
Labels: In-Progress

#6456 fix multiple date bug and fix some tests
  app/services/hearing_schedule/assign_judges_to_hearing_days.rb
  spec/fake_date_helper.rb
  spec/services/hearing_schedule/assign_judges_to_hearing_days_spec.rb
Labels: In-Progress, Ready-to-Merge

#6466 Caseflow API | Adds external_id field to Task
  app/models/appeal.rb
  app/models/legacy_appeal.rb
  app/models/serializers/work_queue/task_serializer.rb
Labels: In-Progress, Ready-to-Merge

#6465 Adding fake judge for demo
  app/models/user.rb
  app/repositories/user_repository.rb
  app/services/hearing_schedule/validate_judge_spreadsheet.rb
Labels: In-Progress, Ready-to-Merge

#6462 changing how days are allocated for Hearing Sched
  app/services/hearing_schedule/generate_hearing_days_schedule.rb
  spec/services/hearing_schedule/assign_judges_to_hearing_days_spec.rb
  spec/services/hearing_schedule/generate_hearing_days_schedule_spec.rb
Labels: In-Progress, Ready-to-Merge

#6414 Attorney Queue | Add admin action
  app/views/queue/index.html.erb
  app/views/queue/show.html.erb
  client/COPY.json
  client/app/queue/AddColocatedTaskView.jsx
  client/app/queue/AddEditIssueView.jsx
  client/app/queue/QueueApp.jsx
  client/app/queue/components/DecisionViewBase.jsx
  client/app/queue/components/SelectCheckoutFlowDropdown.jsx
  client/app/queue/constants.js
  client/app/queue/types/state.js
  client/app/queue/uiReducer/uiReducer.js
  client/constants/CO_LOCATED_ADMIN_ACTIONS.json
  lib/constants/co_located_teams.rb
  spec/controllers/tasks_controller_spec.rb
  spec/feature/queue/case_assignment_spec.rb
Labels: In-Progress, Ready-to-Merge

#6455 First pass at creating a way for users to enable/disable global feature toggle
  app/controllers/test/users_controller.rb
  app/views/test/users/index.html.erb
  client/app/test/TestUsers.jsx
  config/routes.rb
Labels: In-Progress, Ready-to-Merge

#6473 Flaky test fixes
  app/models/ro_schedule_period.rb
  app/services/hearing_schedule/assign_judges_to_hearing_days.rb
  spec/controllers/hearings/schedule_periods_controller_spec.rb
  spec/models/judge_schedule_period_spec.rb
  spec/services/hearing_schedule/assign_judges_to_hearing_days_spec.rb
  spec/services/hearing_schedule/generate_hearing_days_schedule_spec.rb
Labels: In-Progress, Ready-to-Merge

#6464 Mwf teach circleci to use rbenv
  .circleci/config.yml
Labels: In-Progress, Ready-to-Merge

#6469 Co-located table | Establish table for co-located users
  app/controllers/tasks_controller.rb
  app/models/appeal.rb
  client/COPY.json
  client/app/queue/ColocatedTaskListView.jsx
  client/app/queue/QueueActions.js
  client/app/queue/QueueApp.jsx
  client/app/queue/QueueLoadingScreen.jsx
  client/app/queue/components/AmaTaskTable.jsx
  client/app/queue/components/TaskTable.jsx
  client/app/queue/constants.js
  client/app/queue/reducers.js
  client/app/queue/selectors.js
  client/app/queue/types/models.js
  client/app/queue/types/state.js
  client/constants/USER_ROLE_TYPES.json
  db/seeds.rb
  spec/controllers/organizations/tasks_controller_spec.rb
Labels: In-Progress, Ready-to-Merge

#6478 Do not pass hearing type to vacols
  app/models/judge_schedule_period.rb
Labels: In-Progress, Ready-to-Merge

#6457 Anya/6419 assign case for qr
  app/models/judge_case_review.rb
  app/models/legacy_appeal.rb
  app/models/vacols/decision_quality_review.rb
  app/repositories/queue_repository.rb
  spec/factories/judge_case_review.rb
  spec/models/judge_case_review_spec.rb
Labels: In-Progress, Ready-to-Merge

#6489 Update Ruby Gemfile version
  Gemfile
  Gemfile.lock
Labels: In-Progress, Ready-to-Merge

#6482 Judge can reassign AMA case to another attorney
  app/controllers/tasks_controller.rb
  app/models/tasks/attorney_task.rb
  spec/controllers/tasks_controller_spec.rb
Labels: In-Progress, Ready-to-Merge

#6494 Refresh schedule periods on page load
  client/app/hearingSchedule/containers/BuildScheduleContainer.jsx
Labels: In-Progress, Ready-to-Merge

#6498 Flow | Annotates QueueApp
  client/app/queue/ColocatedTaskListView.jsx
  client/app/queue/QueueApp.jsx
  client/app/queue/QueueLoadingScreen.jsx
Labels: In-Progress, Ready-to-Merge

#6483 Issue with hearing_date not being properly set in UTC and with 00:00:00 time
  app/helpers/vacols_helper.rb
  app/models/serializers/hearings/hearing_day_serializer.rb
  app/models/vacols/case_hearing.rb
  spec/models/hearing_day_spec.rb
  spec/requests/hearing_day_spec.rb
Labels: In-Progress, Ready-to-Merge

#6491 API | Adds AOD field to Task
  app/models/appeal.rb
  app/models/serializers/work_queue/task_serializer.rb
  spec/controllers/tasks_controller_spec.rb
Labels: In-Progress, Ready-to-Merge

#6459 Increment issue count to handle decision date
  client/app/intake/pages/appeal/finish.jsx
  client/app/intake/pages/higherLevelReview/finish.jsx
  client/app/intake/pages/supplementalClaim/finish.jsx
  client/app/intake/reducers/appeal.js
  client/app/intake/reducers/higherLevelReview.js
  client/app/intake/reducers/supplementalClaim.js
  client/app/intake/selectors.js
  client/app/intake/util/index.js
  spec/feature/intake/appeal_spec.rb
  spec/feature/intake/higher_level_review_spec.rb
  spec/feature/intake/supplemental_claim_spec.rb
Labels: In-Progress, Ready-to-Merge

#6496 Queue Colocated | Adds type column
  app/models/appeal.rb
  app/models/legacy_appeal.rb
  app/models/serializers/work_queue/task_serializer.rb
  client/app/queue/CaseListTable.jsx
  client/app/queue/CaseSnapshot.jsx
  client/app/queue/components/AmaTaskTable.jsx
  client/app/queue/components/TaskTable.jsx
  client/app/queue/types/models.js
  client/app/queue/utils.js
Labels: In-Progress, Ready-to-Merge

#6488 Upcase countries for postal code validation
  app/models/veteran.rb
Labels: In-Progress, Ready-to-Merge

#6512 handle when country is nil
  app/models/veteran.rb
Labels: In-Progress, Ready-to-Merge

#6510 Queue Colocated | Add sorting
  client/app/queue/components/AmaTaskTable.jsx
  client/app/queue/types/models.js
Labels: In-Progress, Ready-to-Merge

#6513 Build Schedule Finalized SPs
  client/app/hearingSchedule/components/BuildSchedule.jsx
  client/test/karma/hearingSchedule/components/BuildSchedule-test.js
Labels: In-Progress

#6507 removing days after they are filled from available days
  app/services/hearing_schedule/generate_hearing_days_schedule.rb
Labels: In-Progress, Ready-to-Merge

#6523 Send to VACOLS flag
  client/app/hearingSchedule/actions.js
  client/app/hearingSchedule/constants.js
  client/app/hearingSchedule/containers/BuildScheduleContainer.jsx
  client/app/hearingSchedule/containers/ReviewAssignmentsContainer.jsx
  client/app/hearingSchedule/reducers.js
Labels: In-Progress

#6514 VACOLS Integration fixes
  app/helpers/vacols_helper.rb
  app/models/ro_schedule_period.rb
  app/models/vacols/case_hearing.rb
  spec/requests/hearing_day_spec.rb
Labels: In-Progress, Ready-to-Merge

#6452 Fixes Dispatch admin header UI
  client/app/establishClaimAdmin/StuckTasks.jsx
  client/app/establishClaimAdmin/index.jsx
Labels: In-Progress, Ready-to-Merge

#6530 Allow n/a for judge non-availability
  app/models/hearings/judge_non_availability.rb
  app/services/hearing_schedule/validate_judge_spreadsheet.rb
  db/migrate/20180806210221_remove_non_null_constraint_on_non_availability.rb
  db/schema.rb
  spec/factories/judge_schedule_period.rb
  spec/models/hearings/judge_non_availability_spec.rb
  spec/services/hearing_schedule/validate_judge_spreadsheet_spec.rb
  spec/support/validJudgeSpreadsheet.xlsx
Labels: In-Progress, Ready-to-Merge

#6535 Rspec do not select a case for quality review
  spec/controllers/case_reviews_controller_spec.rb
  spec/models/judge_case_review_spec.rb
Labels: In-Progress

#6527 Queue Colocated | Format veteran names as first name last name
  app/models/appeal.rb
  app/models/serializers/work_queue/task_serializer.rb
  spec/controllers/tasks_controller_spec.rb
Labels: In-Progress, Ready-to-Merge

#6506 Build Schedule | Sort schedule periods
  client/app/hearingSchedule/components/BuildSchedule.jsx
Labels: In-Progress

#6528 Ignore non-showstopping errors to document count and new files endpoints
  app/controllers/appeals_controller.rb
  lib/caseflow/error.rb
Labels: In-Progress, Ready-to-Merge

#6519 Style Veteran's cases list
  client/app/queue/CaseListTable.jsx
  client/app/queue/VeteranCasesView.jsx
Labels: In-Progress

#6536 Disabled button after user clicks
  client/app/hearingSchedule/containers/BuildScheduleUploadContainer.jsx
Labels: In-Progress, Ready-to-Merge

#6537 Fixing extra vacols calls
  app/models/legacy_tasks/legacy_task.rb
Labels: In-Progress, Ready-to-Merge

#6526 adding a nil check and making sure judge still exists
  app/services/hearing_schedule/assign_judges_to_hearing_days.rb
  spec/services/hearing_schedule/assign_judges_to_hearing_days_spec.rb
Labels: In-Progress, Ready-to-Merge

#6538 Moving to receipt date
  app/models/appeal.rb
  spec/factories/appeal.rb
  spec/models/appeal_spec.rb
Labels: In-Progress, Ready-to-Merge

#6531 Fakes::BGSService | Makes veteran names deterministic
  lib/generators/base.rb
  lib/generators/veteran.rb
Labels: In-Progress, Ready-to-Merge

#6521 Update ruby gem for set origin source
  Gemfile
  Gemfile.lock
Labels: In-Progress, Ready-to-Merge

#6516 Show list of all cases for Veteran on details page
  client/.eslintrc.js
  client/app/queue/CaseDetailsView.jsx
  client/app/queue/CaseList/CaseListActions.js
  client/app/queue/CaseList/CaseListReducer.js
  client/app/queue/CaseList/actionTypes.js
  client/app/queue/CaseListTable.jsx
  client/app/queue/CaseTitle.jsx
  client/app/queue/QueueActions.js
  client/app/queue/VeteranCasesView.jsx
  client/app/queue/selectors.js
  client/app/queue/types/models.js
  client/app/queue/types/state.js
  client/app/queue/uiReducer/uiActions.js
  client/app/queue/uiReducer/uiConstants.js
  client/app/queue/uiReducer/uiReducer.js
Labels: In-Progress

#6549 Test cases memorializing Judge algorithm testing for prod rollout
  spec/factories/judge_schedule_period.rb
  spec/factories/vacols/travel_board_schedule.rb
  spec/models/judge_schedule_period_spec.rb
  spec/support/manyNonAvailJudgeSpreadsheet.xlsx
  spec/support/oneAllAvailJudgeSpreadsheet.xlsx
  spec/support/singleNonAvailJudgeSpreadsheet.xlsx
  spec/support/twoAllAvailJudgeSpreadsheet.xlsx
  spec/support/twoInJulyJudgeSpreadsheet.xlsx
Labels: In-Progress, Ready-to-Merge

#6554 Adding check for external_id
  client/app/reader/utils.js
Labels: In-Progress, Ready-to-Merge

#6541 Fixing ama queue test that's failing
  spec/factories/document.rb
  spec/feature/queue/ama_queue_spec.rb
Labels: In-Progress, Ready-to-Merge

#6553 Update brieff table from decass when bva dispatch checkout
  app/mappers/queue_mapper.rb
  app/models/judge_case_review.rb
  app/repositories/queue_repository.rb
  spec/models/judge_case_review_spec.rb
Labels: In-Progress, Ready-to-Merge

#6503 Anya/6493 ama attorney checkout
  app/controllers/case_reviews_controller.rb
  app/models/appeal.rb
  app/models/attorney_case_review.rb
  app/models/concerns/case_review_concern.rb
  app/models/decision_issue.rb
  app/models/judge_case_assignment_to_attorney.rb
  app/models/judge_case_review.rb
  app/models/request_issue.rb
  client/app/queue/utils.js
  client/constants/ISSUE_DISPOSITIONS.json
  db/migrate/20180806124145_create_decision_issues.rb
  db/schema.rb
  spec/controllers/case_reviews_controller_spec.rb
  spec/factories/decision_issue.rb
  spec/models/attorney_case_review_spec.rb
  spec/models/judge_case_review_spec.rb
Labels: In-Progress, Ready-to-Merge

#6539 Queue | Return colocated tasks from AppealsController.tasks
  app/controllers/appeals_controller.rb
  app/models/queues/attorney_queue.rb
  app/models/queues/colocated_queue.rb
  app/models/queues/judge_queue.rb
  client/app/queue/AssignedCasesPage.jsx
  client/app/queue/CaseDetailsLoadingScreen.jsx
  client/app/queue/CaseSnapshot.jsx
  client/app/queue/QueueActions.js
  client/app/queue/QueueLoadingScreen.jsx
  client/app/queue/SubmitDecisionView.jsx
  client/app/queue/UnassignedCasesPage.jsx
  client/app/queue/components/AssignWidget.jsx
  client/app/queue/components/JudgeActionsDropdown.jsx
  client/app/queue/selectors.js
  client/app/queue/types/models.js
  client/app/queue/types/state.js
  client/app/queue/utils.js
  spec/controllers/appeals_controller_spec.rb
Labels: In-Progress

#6560 Test Users page ui
  client/app/test/TestUsers.jsx
Labels: In-Progress

#6505 IDT appeal details endpoint
  app/controllers/idt/api/v1/appeals_controller.rb
  app/mappers/power_of_attorney_mapper.rb
  app/models/certification_stats.rb
  app/models/legacy_appeal.rb
  app/models/queues/legacy_work_queue.rb
  app/models/serializers/idt/v1/appeal_details_serializer.rb
  app/repositories/judge_repository.rb
  app/repositories/queue_repository.rb
  app/services/appeal_repository.rb
  config/routes.rb
  lib/fakes/queue_repository.rb
  spec/controllers/idt/api/appeals_controller_spec.rb
  spec/services/appeals_repository_spec.rb
Labels: In-Progress, Ready-to-Merge

#6566 Queue | Fix some typos on Evaluate Decision screen options
  client/constants/JUDGE_CASE_REVIEW_OPTIONS.json
Labels: In-Progress, Ready-to-Merge

#6559 Highlight current assignee in case search if it is the logged-in user
  client/COPY.json
  client/app/constants/AppConstants.js
  client/app/queue/CaseListTable.jsx
Labels: In-Progress, Ready-to-Merge

#6567 Make Veteran ID in case details title copyable
  client/app/queue/CaseTitle.jsx
Labels: In-Progress, Ready-to-Merge

#6577 updating logic to assign all co hearing days in a date to the same judge
  app/services/hearing_schedule/assign_judges_to_hearing_days.rb
  spec/models/judge_schedule_period_spec.rb
Labels: In-Progress

#6548 Co-located table | New tab
  client/COPY.json
  client/app/queue/ColocatedTaskListView.jsx
  client/app/queue/QueueApp.jsx
  client/app/queue/components/AmaTaskTable.jsx
  client/app/queue/selectors.js
  client/test/karma/queue/ColocatedTaskListView-test.js
Labels: In-Progress, Ready-to-Merge

#6582 Fix NoMethodError count for valid_modifiers
  app/models/ramp_review.rb
  spec/models/ramp_election_spec.rb
  spec/models/ramp_refiling_spec.rb
Labels: In-Progress, Ready-to-Merge

#6579 Queue | Update Evaluate Decision screen layout, copy
  client/COPY.json
  client/app/components/CheckboxGroup.jsx
  client/app/queue/EvaluateDecisionView.jsx
Labels: In-Progress

#6570 Queue | Use previous_task.assigned_at in LegacyTaskSerializer
  app/models/serializers/work_queue/legacy_task_serializer.rb
Labels: In-Progress

#6569 Update parent status when creating or completing a task
  app/models/attorney_case_review.rb
  app/models/task.rb
  spec/controllers/case_reviews_controller_spec.rb
  spec/controllers/tasks_controller_spec.rb
  spec/models/attorney_case_review_spec.rb
Labels: In-Progress, Ready-to-Merge

#6589 Schedule date format in mm/dd/yy
  client/app/hearingSchedule/components/BuildSchedule.jsx
Labels: In-Progress, Ready-to-Merge

#6571 Unify tooltip appearance and add to new docs icon and Veteran ID copy button
  client/COPY.json
  client/app/components/Table.jsx
  client/app/components/Tooltip.jsx
  client/app/hearings/components/WorksheetHeader.jsx
  client/app/queue/CaseTitle.jsx
  client/app/queue/components/NewFile.jsx
Labels: In-Progress, Ready-to-Merge

#6565 Update connect_vbms for change to preprod certificate
  Gemfile
  Gemfile.lock
Labels: In-Progress

#6544 Fixing appeal details
  app/controllers/issues_controller.rb
  app/models/serializers/work_queue/appeal_serializer.rb
  app/models/serializers/work_queue/legacy_appeal_serializer.rb
  client/app/queue/AddColocatedTaskView.jsx
  client/app/queue/AddEditIssueView.jsx
  client/app/queue/AppealDocumentCount.jsx
  client/app/queue/AppellantDetail.jsx
  client/app/queue/AssignedCasesPage.jsx
  client/app/queue/CaseDetailsLink.jsx
  client/app/queue/CaseDetailsLoadingScreen.jsx
  client/app/queue/CaseDetailsView.jsx
  client/app/queue/CaseHearingsDetail.jsx
  client/app/queue/CaseList/CaseListActions.js
  client/app/queue/CaseListTable.jsx
  client/app/queue/CaseListView.jsx
  client/app/queue/CaseSnapshot.jsx
  client/app/queue/CaseTitle.jsx
  client/app/queue/EvaluateDecisionView.jsx
  client/app/queue/QueueActions.js
  client/app/queue/QueueLoadingScreen.jsx
  client/app/queue/SelectDispositionsView.jsx
  client/app/queue/SelectRemandReasonsView.jsx
  client/app/queue/SubmitDecisionView.jsx
  client/app/queue/UnassignedCasesPage.jsx
  client/app/queue/VeteranCasesView.jsx
  client/app/queue/VeteranDetail.jsx
  client/app/queue/components/IssueRemandReasonsOptions.jsx
  client/app/queue/components/JudgeActionsDropdown.jsx
  client/app/queue/components/JudgeStartCheckoutFlowDropdown.jsx
  client/app/queue/components/TaskTable.jsx
  client/app/queue/reducers.js
  client/app/queue/selectors.js
  client/app/queue/types/models.js
  client/app/queue/types/state.js
  client/app/queue/utils.js
  spec/controllers/issues_controller_spec.rb
Labels: In-Progress, Ready-to-Merge

#6603 Update DAS compeltion date
  app/mappers/queue_mapper.rb
  app/models/judge_case_review.rb
  spec/models/judge_case_review_spec.rb
Labels: In-Progress, Ready-to-Merge

#6607 Handle BGS returning end_product record with zero records
  app/models/veteran.rb
Labels: In-Progress, Ready-to-Merge

#6609 Handle zero end products response from BGS
  app/models/veteran.rb
Labels: In-Progress, Ready-to-Merge

#6612 Filter out disposition 9
  app/mappers/issue_mapper.rb
  app/models/appeal_event.rb
  client/app/queue/components/SelectIssueDispositionDropdown.jsx
  client/app/queue/utils.js
  client/constants/VACOLS_DISPOSITIONS_BY_ID.json
  spec/mappers/issue_mapper_spec.rb
Labels: In-Progress, Ready-to-Merge

#6614 handling a case when RO doesn't exist for CO hearing days
  app/controllers/hearings/schedule_periods_controller.rb
  app/models/regional_office.rb
  spec/controllers/hearings/schedule_periods_controller_spec.rb
Labels: In-Progress, Ready-to-Merge

#6624 Ramp Election Sync | Calls application_attr from the job thread
  app/jobs/ramp_election_sync_job.rb
Labels: In-Progress, Ready-to-Merge

#6605 Anya/6581 judge checkout ama
  app/models/attorney_case_review.rb
  app/models/concerns/case_review_concern.rb
  app/models/judge_case_review.rb
  spec/controllers/case_reviews_controller_spec.rb
Labels: In-Progress, Ready-to-Merge

#6610 Combining AMA and legacy tasks
  app/models/serializers/work_queue/task_serializer.rb
  client/app/queue/AssignedCasesPage.jsx
  client/app/queue/AttorneyTaskListView.jsx
  client/app/queue/BeaamAppealListView.jsx
  client/app/queue/CaseDetailsLoadingScreen.jsx
  client/app/queue/CaseSnapshot.jsx
  client/app/queue/ColocatedTaskListView.jsx
  client/app/queue/JudgeAssignTaskListView.jsx
  client/app/queue/JudgeReviewTaskListView.jsx
  client/app/queue/OrganizationQueue.jsx
  client/app/queue/QueueActions.js
  client/app/queue/QueueLoadingScreen.jsx
  client/app/queue/SubmitDecisionView.jsx
  client/app/queue/UnassignedCasesPage.jsx
  client/app/queue/components/AmaTaskTable.jsx
  client/app/queue/components/AssignWidget.jsx
  client/app/queue/components/JudgeActionsDropdown.jsx
  client/app/queue/components/TaskTable.jsx
  client/app/queue/constants.js
  client/app/queue/reducers.js
  client/app/queue/selectors.js
  client/app/queue/types/models.js
  client/app/queue/types/state.js
  client/app/queue/uiReducer/uiActions.js
  client/app/queue/uiReducer/uiConstants.js
  client/app/queue/uiReducer/uiReducer.js
  client/app/queue/utils.js
  client/test/karma/queue/ColocatedTaskListView-test.js
  client/test/karma/queue/QueueLoadingScreen-test.js
  spec/controllers/tasks_controller_spec.rb
  spec/feature/queue/task_queue_spec.rb
Labels: In-Progress, Ready-to-Merge

#6616 Improve appearance of sorting table row carets
  client/app/components/RenderFunctions.jsx
  client/app/components/Table.jsx
Labels: In-Progress, Ready-to-Merge

#6630 Update status to assigned for parent when child is completed
  app/models/task.rb
  spec/controllers/case_reviews_controller_spec.rb
  spec/models/colocated_task_spec.rb
Labels: In-Progress, Ready-to-Merge

#6629 adding additional error messages for algorithm errors
  app/controllers/hearings/schedule_periods_controller.rb
  app/services/hearing_schedule/errors/not_enough_available_days.rb
  app/services/hearing_schedule/errors/standard_error_with_details.rb
  app/services/hearing_schedule/generate_hearing_days_schedule.rb
  app/services/hearing_schedule/ro_allocation.rb
  client/app/hearingSchedule/actions.js
  client/app/hearingSchedule/components/ReviewAssignments.jsx
  client/app/hearingSchedule/containers/ReviewAssignmentsContainer.jsx
  client/app/hearingSchedule/reducers.js
  spec/services/hearing_schedule/generate_hearing_days_schedule_spec.rb
  spec/services/hearing_schedule/ro_allocation_spec.rb
Labels: In-Progress

#6625 Fix the dates displayed to the judge on the evaluate decision page
  app/models/legacy_tasks/attorney_legacy_task.rb
  app/models/legacy_tasks/judge_legacy_task.rb
  app/models/legacy_tasks/legacy_task.rb
  client/app/queue/EvaluateDecisionView.jsx
  spec/models/legacy_tasks/attorney_legacy_task_spec.rb
  spec/models/legacy_tasks/judge_legacy_task_spec.rb
Labels: In-Progress, Ready-to-Merge

#6631 Add appeal_type property to legacy task serializer
  app/models/legacy_tasks/legacy_task.rb
  app/models/serializers/work_queue/legacy_task_serializer.rb
Labels: In-Progress, Ready-to-Merge

#6634 sort algorithm output by dates desc in Hearing Schedule
  app/models/ro_schedule_period.rb
  app/services/hearing_schedule/assign_judges_to_hearing_days.rb
Labels: In-Progress, Ready-to-Merge

#6620 Queue | Send attorney id judge case review
  app/models/judge_case_review.rb
  app/models/legacy_tasks/legacy_task.rb
  app/models/serializers/work_queue/beaam_serializer.rb
  app/models/serializers/work_queue/legacy_task_serializer.rb
  app/models/vacols/case_assignment.rb
  client/app/queue/EvaluateDecisionView.jsx
  client/app/queue/components/JudgeActionsDropdown.jsx
  client/app/queue/types/models.js
  client/app/queue/utils.js
  client/test/karma/queue/QueueLoadingScreen-test.js
  spec/factories/judge_case_review.rb
Labels: In-Progress, Ready-to-Merge

#6627 fix typo
  client/app/intake/pages/search.jsx
Labels: In Progress, In-Progress, Ready-to-Merge

#6637 Use assigned to location date for attorney
  app/models/legacy_tasks/attorney_legacy_task.rb
  spec/models/legacy_tasks/attorney_legacy_task_spec.rb
Labels: In-Progress, Ready-to-Merge

#6638 Fix typo that causes reader to fail to load documents
  client/app/queue/components/TaskTable.jsx
Labels: In-Progress, Ready-to-Merge

#6639 Enable access to VSO organizational queue for VSO users
  client/app/queue/OrganizationQueue.jsx
  client/app/queue/OrganizationQueueLoadingScreen.jsx
  client/app/queue/QueueApp.jsx
Labels: In-Progress

#6619 Add non rated eps for hlr and sc flows
  app/models/ama_review.rb
  app/models/end_product.rb
  app/models/end_product_establishment.rb
  app/models/higher_level_review.rb
  app/models/intake.rb
  app/models/request_issue.rb
  app/models/supplemental_claim.rb
  spec/feature/intake/higher_level_review_spec.rb
  spec/feature/intake/supplemental_claim_spec.rb
  spec/models/end_product_establishment_spec.rb
  spec/models/higher_level_review_intake_spec.rb
  spec/models/higher_level_review_spec.rb
  spec/models/supplemental_claim_intake_spec.rb
  spec/models/supplemental_claim_spec.rb
Labels: In-Progress, Ready-to-Merge

#6636 Fix bug when Veteran country is nil
  app/models/veteran.rb
  spec/feature/intake/intake_spec.rb
  spec/models/intake_spec.rb
Labels: In-Progress

#6644 Expire intakes after 1 day.
  app/controllers/intakes_controller.rb
  app/models/intake.rb
  app/models/ramp_election_intake.rb
  spec/models/higher_level_review_intake_spec.rb
  spec/models/intake_spec.rb
  spec/models/ramp_election_intake_spec.rb
  spec/models/supplemental_claim_intake_spec.rb
Labels: In-Progress, Ready-to-Merge

#6640 adds remaining attributes to IDT API— document information, outstanding review, and QR info
  app/controllers/idt/api/v1/appeals_controller.rb
  app/models/legacy_appeal.rb
  app/models/serializers/idt/v1/appeal_details_serializer.rb
  app/models/serializers/idt/v1/task_serializer.rb
  app/models/vacols/case.rb
  app/models/vacols/mail.rb
  spec/controllers/idt/api/appeals_controller_spec.rb
  spec/factories/vacols/case.rb
  spec/factories/vacols/decision_quality_review.rb
  spec/factories/vacols/mail.rb
  spec/models/legacy_appeal_spec.rb
Labels: In-Progress, Ready-to-Merge

#6642 Add space to error text
  client/app/intake/pages/search.jsx
Labels: In-Progress, Ready-to-Merge

#6643 Rollback ramp election on canceled ep
  app/models/end_product_establishment.rb
  app/models/ramp_election_rollback.rb
  app/models/ramp_review.rb
  app/models/user.rb
  app/services/appeal_repository.rb
  scripts/enable_features_dev.rb
  spec/models/ramp_election_spec.rb
Labels: In-Progress

#6649 SyncIntakeJob | Calls application_attr from the job thread
  app/jobs/sync_intake_job.rb
Labels: In-Progress, Ready-to-Merge

#6654 Update vbms
  Gemfile
  Gemfile.lock
Labels: In-Progress, Ready-to-Merge

#6659 Modify query for CO and Video hearings
  app/models/vacols/case_hearing.rb
Labels: In-Progress, Ready-to-Merge

#6651 Show appropriate error when UI receives server error
  client/app/hearingSchedule/containers/BuildScheduleContainer.jsx
Labels: In-Progress, Ready-to-Merge

#6658 Prohibit access to files in case search for VSO users when denied by BGS
  app/controllers/appeals_controller.rb
  app/models/user.rb
Labels: In-Progress, Ready-to-Merge

#6635 Hearing-Prep update FAQS
  app/assets/images/help/hearing-latest-notes.jpg
  client/app/help/components/HearingsHelp.jsx
  public/hearingprep_training_guide_june2018.pdf
Labels: In-Progress, Ready-to-Merge

#6599 Colocated | Send back to assigning attorney
  app/models/legacy_tasks/legacy_task.rb
  app/models/serializers/work_queue/legacy_task_serializer.rb
  app/models/serializers/work_queue/task_serializer.rb
  app/models/task.rb
  client/COPY.json
  client/app/queue/CaseDetailsLoadingScreen.jsx
  client/app/queue/CaseDetailsView.jsx
  client/app/queue/CaseSnapshot.jsx
  client/app/queue/ColocatedTaskListView.jsx
  client/app/queue/EvaluateDecisionView.jsx
  client/app/queue/JudgeSelectComponent.jsx
  client/app/queue/QueueActions.js
  client/app/queue/QueueApp.jsx
  client/app/queue/QueueLoadingScreen.jsx
  client/app/queue/SelectDispositionsView.jsx
  client/app/queue/SelectRemandReasonsView.jsx
  client/app/queue/components/ColocatedActionsDropdown.jsx
  client/app/queue/components/JudgeActionsDropdown.jsx
  client/app/queue/components/SendToAssigningAttorneyModal.jsx
  client/app/queue/components/TaskTable.jsx
  client/app/queue/constants.js
  client/app/queue/reducers.js
  client/app/queue/selectors.js
  client/app/queue/types/models.js
  client/app/queue/utils.js
  client/constants/CO_LOCATED_ACTIONS.json
  client/test/karma/queue/QueueLoadingScreen-test.js
  spec/controllers/appeals_controller_spec.rb
  spec/controllers/tasks_controller_spec.rb
  spec/factories/task.rb
  spec/feature/queue/checkout_flows_spec.rb
Labels: In-Progress, Ready-to-Merge

#6564 Adding transaction for finalized / vacols upload
  app/models/judge_schedule_period.rb
  app/models/ro_schedule_period.rb
  client/app/hearingSchedule/containers/BuildScheduleContainer.jsx
Labels: In-Progress, Ready-to-Merge

#6664 Add Australia to list of countries requiring zip (temporary)
  app/models/veteran.rb
Labels: In-Progress

#6665 Queue | Limit judge case review comment length
  app/models/attorney_case_review.rb
  app/models/judge_case_review.rb
  client/app/queue/EvaluateDecisionView.jsx
  client/app/queue/constants.js
  client/constants/VACOLS_COLUMN_MAX_LENGTHS.json
  spec/feature/queue/checkout_flows_spec.rb
Labels: In-Progress

#6595 Co-located table | On hold tab
  app/models/serializers/work_queue/task_serializer.rb
  client/COPY.json
  client/app/queue/CaseSnapshot.jsx
  client/app/queue/ColocatedTaskListView.jsx
  client/app/queue/SubmitDecisionView.jsx
  client/app/queue/components/TaskTable.jsx
  client/app/queue/selectors.js
  client/app/queue/types/models.js
  client/app/queue/utils.js
  client/flow-typed/npm/mocha_v3.1.x.js
  client/test/karma/queue/ColocatedTaskListView-test.js
Labels: In-Progress, Ready-to-Merge

#6648 changes 1:1 to 1:many
  app/models/legacy_appeal.rb
  app/models/vacols/case.rb
  app/models/vacols/representative.rb
  app/repositories/queue_repository.rb
  app/services/appeal_repository.rb
  app/services/full_grants_report.rb
  app/services/power_of_attorney_repository.rb
  app/services/remands_report.rb
  lib/generators/appeal.rb
  lib/generators/legacy_appeal.rb
  spec/factories/vacols/case.rb
  spec/factories/vacols/representative.rb
  spec/models/legacy_appeal_spec.rb
  spec/models/vacols/representative_spec.rb
  spec/services/power_of_attorney_repository_spec.rb
Labels: In-Progress, Ready-to-Merge

#6667 fix flaky test
  spec/controllers/case_reviews_controller_spec.rb
Labels: In-Progress, Ready-to-Merge

#6671 Display Veteran date of birth correctly for BEAAM appeals
  app/models/serializers/work_queue/legacy_appeal_serializer.rb
  client/app/queue/VeteranDetail.jsx
  client/app/util/DateUtil.js
Labels: In-Progress, Ready-to-Merge

#6662 adding judge algorithm errors with dates
  app/controllers/hearings/schedule_periods_controller.rb
  app/services/hearing_schedule/assign_judges_to_hearing_days.rb
  app/services/hearing_schedule/errors/cannot_assign_judges.rb
  client/app/hearingSchedule/components/ReviewAssignments.jsx
  spec/models/judge_schedule_period_spec.rb
  spec/services/hearing_schedule/assign_judges_to_hearing_days_spec.rb
Labels: In-Progress, Ready-to-Merge

#6669 Test data set up for ramp_refiling
  lib/fakes/bgs_service.rb
  local/vacols/bgs_setup.csv
Labels: In-Progress

#6628 creates intake out of service flag
  app/controllers/intakes_controller.rb
Labels: In-Progress, Ready-to-Merge

#6555 Add ability to set payee code for the claimant
  Gemfile
  Gemfile.lock
  app/models/ama_review.rb
  app/models/appeal_intake.rb
  app/models/claimant.rb
  app/models/end_product.rb
  app/models/end_product_establishment.rb
  app/models/higher_level_review.rb
  app/models/higher_level_review_intake.rb
  app/models/ramp_election.rb
  app/models/ramp_review.rb
  app/models/supplemental_claim.rb
  app/models/supplemental_claim_intake.rb
  client/app/intake/actions/ama.js
  client/app/intake/components/SelectClaimant.jsx
  client/app/intake/constants.js
  client/app/intake/pages/appeal/review.jsx
  client/app/intake/pages/higherLevelReview/review.jsx
  client/app/intake/pages/supplementalClaim/review.jsx
  client/app/intake/reducers/appeal.js
  client/app/intake/reducers/higherLevelReview.js
  client/app/intake/reducers/supplementalClaim.js
  client/app/intake/util/index.js
  db/migrate/20180717185230_add_claimant_participant_id_to_end_product_establishments.rb
  db/migrate/20180808215503_add_payee_cd_to_claimants.rb
  db/migrate/20180817195432_add_payee_code_and_claimant_to_end_product_establishment.rb
  db/schema.rb
  spec/feature/dispatch/establish_claim_spec.rb
  spec/feature/intake/appeal_spec.rb
  spec/feature/intake/higher_level_review_spec.rb
  spec/feature/intake/ramp_election_spec.rb
  spec/feature/intake/ramp_refiling_spec.rb
  spec/feature/intake/supplemental_claim_spec.rb
  spec/models/appeal_intake_spec.rb
  spec/models/end_product_establishment_spec.rb
  spec/models/end_product_spec.rb
  spec/models/higher_level_review_intake_spec.rb
  spec/models/higher_level_review_spec.rb
  spec/models/ramp_closed_appeal_spec.rb
  spec/models/ramp_election_spec.rb
  spec/models/supplemental_claim_intake_spec.rb
  spec/models/supplemental_claim_spec.rb
Labels: In-Progress

#6676 README updates
  README.md
Labels: In-Progress, Ready-to-Merge

#6675 Tweak copy
  client/app/containers/OutOfService.jsx
Labels: In-Progress, Ready-to-Merge

#6684 Include all scheduled hearings
  app/models/vacols/case_hearing.rb
Labels: In-Progress, Ready-to-Merge

#6672 add missing logos
  client/app/containers/StyleGuide/StyleGuideLogos.jsx
Labels: In-Progress, Ready-to-Merge

#6670 Colocated Queue | Place hold
  app/controllers/tasks_controller.rb
  app/models/serializers/work_queue/legacy_task_serializer.rb
  client/COPY.json
  client/app/queue/AddColocatedTaskView.jsx
  client/app/queue/ColocatedPlaceHoldView.jsx
  client/app/queue/QueueActions.js
  client/app/queue/QueueApp.jsx
  client/app/queue/components/ColocatedActionsDropdown.jsx
  client/app/queue/components/DecisionViewBase.jsx
  client/app/queue/components/JudgeActionsDropdown.jsx
  client/app/queue/components/SelectCheckoutFlowDropdown.jsx
  client/app/queue/components/SendToAssigningAttorneyModal.jsx
  client/app/queue/components/TaskTable.jsx
  client/app/queue/constants.js
  client/app/queue/reducers.js
  client/app/queue/types/models.js
  client/app/queue/uiReducer/uiReducer.js
  client/app/queue/utils.js
  client/constants/CO_LOCATED_ACTIONS.json
  client/test/karma/queue/QueueLoadingScreen-test.js
  db/schema.rb
  spec/feature/queue/checkout_flows_spec.rb
Labels: In-Progress, Ready-to-Merge

#6690 Add another test file number for RAMP selection for Will
  local/vacols/bgs_setup.csv
Labels: In-Progress

#6682 tweak readme
  README.md
Labels: In-Progress, Ready-to-Merge

#6681 Anya/6632 schedule hearing translation
  PULL_REQUEST_TEMPLATE.md
  app/models/legacy_appeal.rb
  app/models/task.rb
  app/models/tasks/colocated_task.rb
  client/constants/CO_LOCATED_ADMIN_ACTIONS.json
  spec/models/colocated_task_spec.rb
Labels: In-Progress, Ready-to-Merge

#6696 Queue | Case Details task information
  client/COPY.json
  client/app/queue/CaseSnapshot.jsx
  client/app/queue/types/models.js
  client/app/queue/utils.js
  spec/feature/queue/case_details_spec.rb
Labels: In-Progress

#6686 Use profile date for ratings issues
  client/app/intake/components/RatedIssues.jsx
  spec/feature/intake/appeal_spec.rb
  spec/feature/intake/higher_level_review_spec.rb
  spec/feature/intake/supplemental_claim_spec.rb
Labels: In-Progress, Ready-to-Merge

#6697 Clear local cache before recreating veteran records
  lib/fakes/initializer.rb
Labels: In-Progress

#6693 Change add issue button styling to secondary
  client/app/intake/components/NonRatedIssues.jsx
Labels: In-Progress, Ready-to-Merge

#6702 Framework for Intake Edit
  app/models/higher_level_review.rb
  app/models/supplemental_claim.rb
  app/views/higher_level_reviews/edit.html.erb
  app/views/supplemental_claims/edit.html.erb
  client/app/index.js
  client/app/intake/constants.js
  client/app/intakeEdit/IntakeEditFrame.jsx
  client/app/intakeEdit/constants.js
  client/app/intakeEdit/index.js
  client/app/intakeEdit/pages/landing.jsx
  client/app/intakeEdit/pages/selectIssues.jsx
  client/app/intakeEdit/reducers/index.js
  config/routes.rb
  spec/feature/intake/appeal_spec.rb
  spec/feature/intake/higher_level_review_spec.rb
  spec/feature/intake/ramp_election_spec.rb
  spec/feature/intake/ramp_refiling_spec.rb
  spec/feature/intake/supplemental_claim_spec.rb
Labels: In-Progress, Ready-to-Merge

#6698 fix no ratings for dev
  lib/generators/veteran.rb
Labels: In-Progress, Ready-to-Merge

#6695 Ensures safe updates to POA
  app/models/power_of_attorney.rb
  app/models/serializers/work_queue/appeal_serializer.rb
  app/models/vacols/representative.rb
  app/services/power_of_attorney_repository.rb
  spec/models/vacols/representative_spec.rb
  spec/services/power_of_attorney_repository_spec.rb
Labels: In-Progress, Ready-to-Merge

#6707 Fix Vacols timeliness during judge checkout
  app/mappers/queue_mapper.rb
  app/repositories/queue_repository.rb
  spec/models/judge_case_review_spec.rb
Labels: In-Progress, Ready-to-Merge

#6708 Differentiate between assign vs review tasks for judge tasks
  app/models/task.rb
  app/models/tasks/judge_task.rb
  db/seeds.rb
  spec/controllers/case_reviews_controller_spec.rb
  spec/factories/task.rb
  spec/models/tasks/colocated_task_spec.rb
  spec/models/tasks/judge_task_spec.rb
Labels: In-Progress, Ready-to-Merge

#6712 Hearing schedule feature tests
  spec/feature/hearing_schedule/build_schedule_spec.rb
  spec/models/hearing_day_spec.rb
Labels: In-Progress

#6677 Create Task methods to enable generic task completion
  app/models/task.rb
  app/models/tasks/judge_task.rb
  spec/models/task_spec.rb
Labels: In-Progress, Ready-to-Merge

#6716 Co-located table | Pending action tab
  client/COPY.json
  client/app/queue/ColocatedTaskListView.jsx
  client/app/queue/selectors.js
  client/test/karma/queue/ColocatedTaskListView-test.js
Labels: In-Progress, Ready-to-Merge

#6717 Correct path to VSO organizational queue function
  app/models/organizations/vso.rb
Labels: In-Progress, Ready-to-Merge

#6718 Jobs | Sets Sentry context on the worker thread
  app/jobs/application_job.rb
  app/jobs/ramp_election_sync_job.rb
  app/jobs/sync_intake_job.rb
  spec/jobs/application_job_spec.rb
Labels: In-Progress, Ready-to-Merge

#6722 Colocated Queue | Add task counts to tabs
  client/COPY.json
  client/app/queue/ColocatedTaskListView.jsx
  client/test/karma/queue/ColocatedTaskListView-test.js
Labels: In-Progress, Ready-to-Merge

#6689 Add hook to create root parent Task from AMA appeals
  app/models/task.rb
  app/models/tasks/root_task.rb
Labels: In-Progress, Ready-to-Merge

#6719 Return ama tasks for attorneys
  app/models/queues/attorney_queue.rb
  spec/controllers/tasks_controller_spec.rb
Labels: In-Progress, Ready-to-Merge

#6713 Enable generic task actions for organizational queues on the backend
  app/controllers/tasks_controller.rb
  app/models/task.rb
  app/models/tasks/generic_task.rb
  spec/factories/task.rb
  spec/models/tasks/generic_task_spec.rb
Labels: In-Progress

#6705 Basic content for edit landing page
  app/assets/stylesheets/_intake.scss
  app/assets/stylesheets/_variables.scss
  app/models/higher_level_review.rb
  app/models/supplemental_claim.rb
  app/views/higher_level_reviews/edit.html.erb
  app/views/supplemental_claims/edit.html.erb
  client/app/intake/constants.js
  client/app/intake/pages/search.jsx
  client/app/intake/pages/selectForm.jsx
  client/app/intake/reducers/appeal.js
  client/app/intake/reducers/higherLevelReview.js
  client/app/intake/reducers/rampElection.js
  client/app/intake/reducers/rampRefiling.js
  client/app/intake/reducers/supplementalClaim.js
  client/app/intakeCommon/constants.js
  client/app/intakeEdit/IntakeEditFrame.jsx
  client/app/intakeEdit/pages/landing.jsx
  client/app/intakeEdit/pages/selectIssues.jsx
  client/app/intakeEdit/reducers/index.js
  spec/feature/intake/higher_level_review_spec.rb
  spec/feature/intake/supplemental_claim_spec.rb
Labels: In-Progress, Ready-to-Merge

#6711 Add edit issues page
  app/models/higher_level_review.rb
  app/models/request_issue.rb
  app/models/supplemental_claim.rb
  app/views/higher_level_reviews/edit.html.erb
  app/views/supplemental_claims/edit.html.erb
  client/app/intake/actions/ama.js
  client/app/intake/constants.js
  client/app/intake/pages/appeal/finish.jsx
  client/app/intake/pages/higherLevelReview/finish.jsx
  client/app/intake/pages/supplementalClaim/finish.jsx
  client/app/intake/reducers/appeal.js
  client/app/intake/reducers/higherLevelReview.js
  client/app/intake/reducers/supplementalClaim.js
  client/app/intake/selectors.js
  client/app/intake/util/index.js
  client/app/intakeCommon/components/IssueCounter.jsx
  client/app/intakeCommon/components/NonRatedIssues.jsx
  client/app/intakeCommon/components/RatedIssues.jsx
  client/app/intakeCommon/constants.js
  client/app/intakeCommon/util/index.js
  client/app/intakeEdit/pages/landing.jsx
  client/app/intakeEdit/pages/selectIssues.jsx
  client/app/intakeEdit/reducers/index.js
  spec/feature/intake/edit_spec.rb
  spec/feature/intake/higher_level_review_spec.rb
  spec/feature/intake/supplemental_claim_spec.rb
Labels: In-Progress, Ready-to-Merge

#6728 Remove postal code requirement for Germany and Australia
  app/models/veteran.rb
Labels: In-Progress

#6726 Update judges attorneys
  lib/constants/attorney_judge_teams.rb
Labels: In-Progress, Ready-to-Merge

#6731 Add disposition to request issues table and to vbms service
  app/services/external_api/vbms_service.rb
  db/migrate/20180824223530_add_disposition_to_request_issues.rb
  db/schema.rb
Labels: In-Progress, Ready-to-Merge

#6733 Ignore rubyzip vulnerability one week
  lib/tasks/security.rake
Labels: In-Progress, Ready-to-Merge

#6743 Fix for CAVC option being displayed on non-Board dispositions
  app/models/legacy_appeal.rb
  spec/models/appeal_series_alerts_spec.rb
  spec/models/legacy_appeal_spec.rb
Labels: In-Progress

#6745 Show all AMA appeals in case search
  app/controllers/appeals_controller.rb
Labels: In-Progress, Ready-to-Merge

#6729 Anya/6699 ama appeals for idt
  app/controllers/idt/api/v1/appeals_controller.rb
  app/controllers/idt/api/v1/base_controller.rb
  app/models/appeal.rb
  app/models/legacy_appeal.rb
  app/models/serializers/idt/v1/appeal_serializer.rb
  scripts/enable_features_dev.rb
  spec/controllers/idt/api/appeals_controller_spec.rb
Labels: In-Progress, Ready-to-Merge

#6732 allows attorneys, judges, and colocated to use idt api
  app/controllers/idt/api/v1/base_controller.rb
Labels: In-Progress, Ready-to-Merge

#6746 Determine is user is a dispatch user
  app/models/user.rb
  app/repositories/user_repository.rb
  spec/factories/vacols/staff.rb
  spec/repositories/user_repository_spec.rb
Labels: In-Progress, Ready-to-Merge

#6694 Filters documents array by doc id, corrects "written_by" attribute
  app/controllers/idt/api/v1/appeals_controller.rb
  app/models/serializers/idt/v1/document_serializer.rb
  app/models/serializers/idt/v1/task_serializer.rb
  app/models/vacols/case_assignment.rb
  spec/controllers/idt/api/appeals_controller_spec.rb
Labels: In-Progress, Ready-to-Merge

#6748 Improve root task for appeal
  app/models/organizations/bva.rb
  app/models/task.rb
  app/models/tasks/root_task.rb
  db/migrate/20180827194153_add_bva_org_row.rb
  db/schema.rb
  db/seeds.rb
Labels: In-Progress, Ready-to-Merge

#6461 Upgrade Ruby to 2.5.1
  .circleci/config.yml
  .ruby-version
  .travis.yml
  Gemfile
  Gemfile.lock
  ci-bin/circle_docker_container/Dockerfile
  ci-bin/circle_docker_container/build_and_push.sh
Labels: In-Progress

#6749 Colocated Queue | Redefines colocated admin teams
  lib/constants/co_located_teams.rb
Labels: In-Progress, Ready-to-Merge
