Repository department-of-veterans-affairs/caseflow, pull requests merged in 2018-04, with the labels that each got.

#5009 Handling exceptions when efolder api calls fail
  app/models/appeal.rb
  app/models/hearing.rb
  lib/caseflow/error.rb
Labels: In-Progress

#5008 Queue | link to hearing worksheet print view
  client/app/queue/AppealDetail.jsx
  spec/feature/queue/queue_spec.rb
Labels: In-Progress

#5025 Fix for appeals missing NOD dates
  app/models/appeal_series.rb
Labels: In-Progress

#5023 Add time since NOD to intake stats page
  app/models/intake_stats.rb
  app/models/ramp_closed_appeal.rb
  app/views/intake_stats/show.html.erb
  lib/fakes/appeal_repository.rb
  spec/feature/intake_stats_spec.rb
Labels: In-Progress

#5027 Hearings refactor stylesheet
  app/assets/stylesheets/_hearings.scss
Labels: In-Progress

#5017 Adding the same name attributes for some fake hearings
  lib/fakes/hearing_repository.rb
Labels: In-Progress

#5026 Queue | Rename issue readjudication field
  client/app/queue/SubmitDecisionView.jsx
  client/app/queue/components/SelectIssueDispositionDropdown.jsx
Labels: In-Progress

#4880 pt3 of GA to Hearing Prep
  client/app/hearings/HearingWorksheet.jsx
  client/app/hearings/actions/Dockets.js
  client/app/hearings/analytics.js
  client/app/hearings/components/DocketHearingRow.jsx
  client/app/hearings/components/HearingWorksheetStream.jsx
  client/app/hearings/components/WorksheetHeaderVeteranSelection.jsx
Labels: In-Progress

#5036 Check receipt_date is not in the future if there is no notice_date
  app/models/ramp_election.rb
  spec/models/ramp_election_spec.rb
Labels: In-Progress

#4940 Moves Danger to CircleCI
  .circleci/config.yml
  .travis.yml
Labels: In-Progress

#5039 Remove completed in favor of established
  app/models/intake_stats.rb
  app/models/ramp_election.rb
  app/models/ramp_election_intake.rb
  app/models/ramp_refiling.rb
  app/models/ramp_refiling_intake.rb
  app/models/ramp_review.rb
  spec/feature/intake_spec.rb
  spec/feature/intake_stats_spec.rb
  spec/models/ramp_election_intake_spec.rb
  spec/models/ramp_election_spec.rb
  spec/models/ramp_refiling_intake_spec.rb
Labels: In-Progress

#5043 Fix local env without aws creds
  config/environments/local.rb
Labels: In-Progress

#5046 Move the localstack web ui to 8082 (from 8080)
  docker-compose.yml
Labels: In-Progress

#5041 Hearing worksheet header styles
  app/assets/stylesheets/_hearings.scss
  client/app/hearings/components/HearingWorksheetIssues.jsx
Labels: In-Progress

#5040 Add cancellation reasons to intake table
  db/migrate/20180402231703_add_cancellation_reason_to_intake.rb
  db/schema.rb
Labels: In-Progress

#5049 Adding a date to hold options
  app/assets/stylesheets/_hearings.scss
  client/app/hearings/components/DocketHearingRow.jsx
Labels: In-Progress

#5037 Rename worksheet issues vha to omo
  app/controllers/hearings/appeals_controller.rb
  client/app/hearings/actions/Issue.js
  client/app/hearings/components/HearingWorksheetPreImpressions.jsx
  client/app/hearings/constants/constants.js
  client/app/hearings/reducers/index.js
  client/test/karma/hearings/reducers/index-test.js
  db/migrate/20180402204041_change_worksheet_issues_vha_column_name.rb
  db/schema.rb
  spec/controllers/hearings/appeals_controller_spec.rb
  spec/models/appeal_spec.rb
Labels: In-Progress

#5019 "Already Certified" tweaks, OMO request changes issue modification fields
  app/mappers/queue_mapper.rb
  app/models/attorney_case_reviews/attorney_case_review.rb
  client/app/certification/components/AlreadyCertified.jsx
  spec/feature/certification/start_certification_spec.rb
  spec/mappers/queue_mapper_spec.rb
  spec/models/attorney_case_reviews/attorney_case_review_spec.rb
Labels: In-Progress

#5032 Queue Attorney check out | Confirmation banner
  client/app/components/Alert.jsx
  client/app/queue/QueueActions.js
  client/app/queue/QueueApp.jsx
  client/app/queue/QueueListView.jsx
  client/app/queue/QueueLoadingScreen.jsx
  client/app/queue/SelectDispositionsView.jsx
  client/app/queue/SubmitDecisionView.jsx
  client/app/queue/components/DecisionViewBase.jsx
  client/app/queue/constants.js
  client/app/queue/reducers.js
  client/app/queue/uiReducer/uiActions.js
  client/app/queue/uiReducer/uiConstants.js
  client/app/queue/uiReducer/uiReducer.js
  client/app/queue/utils.js
  spec/feature/queue/queue_spec.rb
Labels: In-Progress

#5045 Move judges index to the users controller
  app/controllers/application_controller.rb
  app/controllers/queue_controller.rb
  app/controllers/users_controller.rb
  client/app/queue/QueueLoadingScreen.jsx
  config/routes.rb
  spec/controllers/queue_controller_spec.rb
  spec/controllers/users_controller_spec.rb
Labels: In-Progress

#5057 Updating definition of an active RampElection EP to include nil status
  app/models/ramp_election.rb
  spec/models/ramp_election_spec.rb
Labels: In-Progress

#5005 Disconnects worksheet window from print window
  client/app/hearings/HearingWorksheet.jsx
Labels: In-Progress

#5050 Consolidate/Remove non styleguide gray colors
  app/assets/stylesheets/_hearings.scss
  app/assets/stylesheets/_main.scss
  app/assets/stylesheets/_reviewer.scss
  app/assets/stylesheets/_style_guide.scss
  app/assets/stylesheets/react/_select-dropdown.scss
  app/assets/stylesheets/reader/_document_list.scss
  vendor/assets/stylesheets/_rc_collapse.scss
Labels: In-Progress

#5066 No border top css change for hearing days table
  client/app/hearings/Dockets.jsx
Labels: In-Progress

#5069 Adds database setup steps to Circle build
  .circleci/config.yml
Labels: In-Progress

#5072 Adding search for description and preventing unnecessary state changes
  client/app/reader/DocTypeColumn.jsx
  client/app/reader/DocumentSearch.jsx
  client/app/reader/search.js
Labels: In-Progress

#5068 Removing margins from daily docket table
  app/assets/stylesheets/_hearings.scss
Labels: In-Progress

#5048 Return list of appeals for requests to queue/appeals
  app/controllers/appeals_controller.rb
  config/routes.rb
  spec/controllers/appeals_controller_spec.rb
  spec/controllers/queue_controller_spec.rb
Labels: In-Progress

#5059 Hearing-Prep| Don't show RO for CO hearings
  client/app/hearings/Dockets.jsx
Labels: In-Progress

#5054 multiple regional office locations for shared dockets
  app/models/hearing_docket.rb
  client/app/hearings/Dockets.jsx
  spec/models/hearing_docket_spec.rb
Labels: In-Progress

#5079 Updating caseflow frontend toolkit package
  client/package.json
  client/yarn.lock
Labels: In-Progress

#5075 Add client/yarn-error.log to gitignore
  .gitignore
Labels: In-Progress

#5094 Eager load directories in production env
  config/application.rb
Labels: In-Progress

#5095 Fix params in histogram_controller for datadog
  app/controllers/metrics/v1/histogram_controller.rb
Labels: In-Progress

#5058 Get user from intake in SyncIntakeJob
  app/jobs/sync_intake_job.rb
  app/models/ramp_election.rb
  spec/jobs/sync_intake_job_spec.rb
  spec/models/ramp_election_spec.rb
Labels: In-Progress

#5087 Updates RampReview validations
  app/models/ramp_election.rb
  app/models/ramp_review.rb
  client/app/intake/util/index.js
  spec/feature/intake_spec.rb
  spec/feature/intake_stats_spec.rb
  spec/models/ramp_election_intake_spec.rb
  spec/models/ramp_election_spec.rb
  spec/models/ramp_issue_spec.rb
  spec/models/ramp_refiling_intake_spec.rb
  spec/models/ramp_refiling_spec.rb
Labels: In-Progress

#5082 Queue | Pop multiple breadcrumbs on jump backwards
  client/app/queue/components/DecisionViewBase.jsx
  client/app/queue/uiReducer/uiActions.js
  client/app/queue/uiReducer/uiReducer.js
Labels: In-Progress

#5051 Queue | Save issue edits to server
  client/app/queue/AddEditIssueView.jsx
  client/app/queue/QueueListView.jsx
  client/app/queue/SelectDispositionsView.jsx
  client/app/queue/SubmitDecisionView.jsx
  client/app/queue/uiReducer/uiActions.js
  client/app/queue/uiReducer/uiReducer.js
  spec/feature/queue/queue_spec.rb
Labels: In-Progress

#5078 Remove unnecessary DB seeding, add Queue link to admin page, fix dev document count bug
  app/controllers/queue_controller.rb
  app/controllers/test/users_controller.rb
  db/seeds.rb
  lib/fakes/initializer.rb
  spec/feature/switch_user_spec.rb
Labels: In-Progress

#4963 Issue 4791 - Remove visibility check on if condition.
  client/app/reader/PdfFile.jsx
  spec/feature/reader/reader_spec.rb
Labels: In-Progress

#5107 Update Package json for frontend kit
  client/package.json
  client/yarn.lock
Labels: In-Progress

#5103 Update the statuspage url
  client/app/containers/OutOfService.jsx
Labels: In-Progress

#5028 Implement functionality for a judge to assign a case to an attorney
  app/controllers/queue_controller.rb
  app/models/attorney_case_reviews/attorney_case_review.rb
  app/models/judge_case_assignment.rb
  app/models/user.rb
  app/models/vacols/decass.rb
  app/repositories/queue_repository.rb
  app/repositories/user_repository.rb
  config/routes.rb
  lib/fakes/queue_repository.rb
  lib/fakes/user_repository.rb
  spec/controllers/queue_controller_spec.rb
  spec/models/attorney_case_reviews/attorney_case_review_spec.rb
Labels: In-Progress

#5106 Building a docker container to run our builds in
  .circleci/config.yml
  .gitignore
  ci-bin/circle_docker_container/Dockerfile
  ci-bin/circle_docker_container/build_and_push.sh
  ci-bin/setup-circleci-prereqs
Labels: In-Progress

#5118 Formats code
  README.md
Labels: In-Progress

#5112 Fixes buggy tests
  app/models/document.rb
Labels: In-Progress

#5122 Removes unused constant
  app/models/document.rb
Labels: In-Progress

#5111 Add disposition to case details view
  client/app/queue/components/IssueListItem.jsx
  client/app/queue/components/SelectIssueDispositionDropdown.jsx
  client/app/queue/constants.js
  spec/feature/queue/queue_spec.rb
Labels: In-Progress

#5126 Updates SyncIntakeJob to only operate on established reviews
  app/models/ramp_election.rb
  spec/jobs/sync_intake_job_spec.rb
  spec/models/ramp_election_spec.rb
Labels: In-Progress

#5114 Make the EP portion of RampElectionIntake.complete! idempotent
  app/models/end_product.rb
  app/models/ramp_election.rb
  app/models/ramp_election_intake.rb
  app/models/ramp_refiling.rb
  app/models/ramp_review.rb
  db/schema.rb
  spec/models/end_product_spec.rb
  spec/models/ramp_election_intake_spec.rb
  spec/models/ramp_election_spec.rb
Labels: In-Progress

#5131 Reverting docket sorting in Hearing prep
  client/app/hearings/DailyDocket.jsx
Labels: In-Progress

#5132 Oracle datetime fix
  app/models/vacols/case_hearing.rb
Labels: In-Progress

#5124 Queue Attorney check out | Delete an issue
  client/app/queue/AddEditIssueView.jsx
  client/app/queue/QueueActions.js
  client/app/queue/SubmitDecisionView.jsx
  client/app/queue/constants.js
  client/app/queue/reducers.js
  client/app/queue/uiReducer/uiActions.js
  client/app/queue/uiReducer/uiConstants.js
  client/app/queue/uiReducer/uiReducer.js
  spec/feature/queue/queue_spec.rb
Labels: In-Progress

#5128 Makes SyncIntakeJob use system user
  app/jobs/sync_intake_job.rb
  app/models/ramp_election.rb
  spec/jobs/sync_intake_job_spec.rb
  spec/models/ramp_election_spec.rb
Labels: In-Progress

#5138 Pass user data with VBMS establish claim request
  Gemfile
  Gemfile.lock
  app/services/external_api/vbms_service.rb
Labels: In-Progress

#5137 Modifying CircleCI bundler cache
  .circleci/config.yml
Labels: In-Progress

#5139 Remove sleep from sync_all
  app/models/ramp_election.rb
  spec/models/ramp_election_spec.rb
Labels: In-Progress

#5100 Add manager view for canceled and error'd intakes
  app/assets/stylesheets/_intake.scss
  app/controllers/intake_manager_controller.rb
  app/models/intake.rb
  app/models/ramp_review.rb
  app/views/intake_manager/index.html.erb
  client/app/establishClaimAdmin/actions/index.js
  client/app/index.js
  client/app/intakeManager/FlaggedForReview.jsx
  client/app/intakeManager/FlaggedForReviewContainer.jsx
  client/app/intakeManager/actions/index.js
  client/app/intakeManager/constants/index.js
  client/app/intakeManager/index.jsx
  client/app/intakeManager/reducers/index.js
  config/routes.rb
  spec/feature/intake_manager_spec.rb
  spec/models/intake_spec.rb
Labels: In-Progress

#5109 Queue table | Messaging for cases without DECASS records
  client/app/components/RenderFunctions.jsx
  client/app/queue/QueueListView.jsx
  client/app/queue/QueueTable.jsx
  client/app/queue/ReaderLink.jsx
  client/package.json
  client/yarn.lock
  spec/feature/queue/queue_spec.rb
Labels: In-Progress

#5074 Queue | Attorney check out | Remand reasons
  app/models/serializers/work_queue/appeal_serializer.rb
  client/app/components/Checkbox.jsx
  client/app/components/CheckboxGroup.jsx
  client/app/queue/AddEditIssueView.jsx
  client/app/queue/QueueActions.js
  client/app/queue/QueueApp.jsx
  client/app/queue/SelectDispositionsView.jsx
  client/app/queue/SelectRemandReasonsView.jsx
  client/app/queue/SubmitDecisionView.jsx
  client/app/queue/components/DecisionViewBase.jsx
  client/app/queue/components/IssueListItem.jsx
  client/app/queue/components/IssueRemandReasonsOptions.jsx
  client/app/queue/components/SelectIssueDispositionDropdown.jsx
  client/app/queue/constants.js
  client/app/queue/reducers.js
  client/app/queue/utils.js
  spec/feature/queue/queue_spec.rb
Labels: In-Progress

#5133 Hearing Prep | Show only current number of issues on Daily Docket
  app/models/appeal.rb
  app/models/hearing.rb
  client/app/hearings/components/DocketHearingRow.jsx
  client/app/hearings/components/WorksheetHeaderVeteranSelection.jsx
  spec/models/hearing_spec.rb
Labels: In-Progress

#5146 Intake manager review page updates
  app/models/intake.rb
  client/app/intakeManager/reducers/index.js
  spec/feature/intake_manager_spec.rb
  spec/models/intake_spec.rb
Labels: In-Progress

#5140 Do not close appeals with nod_date after election receipt_date
  app/models/appeal.rb
  app/models/ramp_election_intake.rb
  spec/feature/intake_spec.rb
  spec/models/appeal_spec.rb
Labels: In-Progress

#5125 Anya/5055 datadog metrics
  app/models/attorney_case_reviews/attorney_case_review.rb
  app/models/judge_case_assignment.rb
  app/repositories/issue_repository.rb
  app/repositories/queue_repository.rb
  app/services/business_metrics.rb
  app/services/external_api/efolder_service.rb
  spec/repositories/issue_repository_spec.rb
  spec/services/business_metrics_spec.rb
Labels: In-Progress

#5155 Updates caseflow-commons to fix fiscal year label
  Gemfile
  Gemfile.lock
  spec/feature/intake_stats_spec.rb
Labels: In-Progress

#5159 Queue | Make checkbox IDs specific to issue
  client/app/queue/components/IssueRemandReasonsOptions.jsx
Labels: Bug, In-Progress, caseflow-queue, foxtrot

#5145 Add FACOLS to CircleCI build
  .circleci/config.yml
  Gemfile
  config/database.yml
  lib/tasks/local/vacols.rake
  local/vacols/Dockerfile
  local/vacols/build_and_push.sh
  local/vacols/dockerInitWithSchema.sh
  local/vacols/loadSchema.sh
Labels: In-Progress

#5093 Hearing Worksheet for Reader
  client/app/hearings/containers/HearingWorksheetContainer.jsx
  client/app/reader/utils.js
Labels: In-Progress

#5162 Fix IssueList formatting weirdness
  client/app/queue/SelectDispositionsView.jsx
  client/app/queue/components/IssueList.jsx
  client/app/queue/constants.js
Labels: In-Progress

#5164 Search form with form name
  client/app/intake/pages/search.jsx
  spec/feature/intake_spec.rb
Labels: In-Progress

#5175 Add caching around bgs `can_access`
  app/services/external_api/bgs_service.rb
Labels: In-Progress

#5141 AMA Intake form selection searchable dropdown
  app/views/intakes/index.html.erb
  client/app/intake/IntakeFrame.jsx
  client/app/intake/constants.js
  client/app/intake/pages/selectForm.jsx
  spec/feature/intake_spec.rb
Labels: In-Progress

#5108 Lowell/5011 search bar mvp
  app/controllers/appeals_controller.rb
  app/models/serializers/work_queue/appeal_serializer.rb
  app/views/queue/index.html.erb
  client/app/queue/CaseList/CaseListActions.js
  client/app/queue/CaseList/CaseListReducer.js
  client/app/queue/CaseList/actionTypes.js
  client/app/queue/CaseListSearch.jsx
  client/app/queue/CaseListTable.jsx
  client/app/queue/CaseListView.jsx
  client/app/queue/QueueApp.jsx
  client/app/queue/SearchEnabledView.jsx
  client/app/queue/constants.js
  client/app/queue/reducers.js
  lib/generators/random.rb
  spec/controllers/appeals_controller_spec.rb
  spec/feature/queue/queue_spec.rb
Labels: In-Progress

#5182 Adding loading messages for worksheet page
  client/app/hearings/HearingWorksheet.jsx
  client/app/hearings/components/WorksheetHeaderVeteranSelection.jsx
Labels: In-Progress

#5199 Queue | Clear error message on unmount QueueListView
  client/app/queue/QueueListView.jsx
Labels: In-Progress

#5127 [Tech Spec] Shared Constants
  app/mappers/issue_mapper.rb
  app/models/appeal.rb
  app/models/issue.rb
  app/models/vacols/case.rb
  app/services/appeal_repository.rb
  client/app/queue/components/IssueListItem.jsx
  client/app/queue/components/SelectIssueDispositionDropdown.jsx
  client/app/queue/constants.js
  config/initializers/constants.rb
  constants/VACOLS_DISPOSITIONS_BY_ID.json
  spec/models/appeal_event_spec.rb
Labels: In-Progress

#5190 Fix test that leaks state
  client/test/karma/components/AutoSave-test.js
Labels: In-Progress

#5189 Fix form_type for searchable dropdown
  client/app/intake/pages/selectForm.jsx
  spec/feature/intake_spec.rb
Labels: In-Progress

#5209 Run danger lint and security while FACOLS gets ready on Circle
  .circleci/config.yml
Labels: In-Progress

#5211 Intake Supplemental Claim review page
  app/models/intake.rb
  app/models/supplemental_claim.rb
  app/models/supplemental_claim_intake.rb
  client/app/intake/actions/supplementalClaim.js
  client/app/intake/constants.js
  client/app/intake/index.js
  client/app/intake/pages/finish.jsx
  client/app/intake/pages/review.jsx
  client/app/intake/pages/supplementalClaim/finish.jsx
  client/app/intake/pages/supplementalClaim/review.jsx
  client/app/intake/reducers/supplementalClaim.js
  client/app/intake/selectors.js
  client/app/intake/util/index.js
  db/migrate/20180416184214_create_supplemental_claims.rb
  db/schema.rb
  spec/feature/intake_spec.rb
  spec/models/supplemental_claim_spec.rb
Labels: In-Progress

#5210 Makes button more enticing
  client/app/reader/CaseSelectSearch.jsx
  spec/feature/queue/queue_spec.rb
  spec/feature/reader/reader_spec.rb
Labels: In-Progress

#5143 Anya/judges list
  app/controllers/users_controller.rb
  app/models/judge.rb
  app/models/user.rb
  app/repositories/judge_repository.rb
  app/repositories/user_repository.rb
  lib/constants/attorney_judge_teams.rb
  lib/fakes/user_repository.rb
  lib/files/attorneys_judges_chiefs.csv
  spec/controllers/queue_controller_spec.rb
  spec/controllers/users_controller_spec.rb
  spec/models/attorney_case_reviews/attorney_case_review_spec.rb
  spec/models/judge_spec.rb
  spec/rails_helper.rb
Labels: In-Progress

#5191 Queue: Adds view of review tasks for judges
  app/views/queue/index.html.erb
  client/app/queue/AttorneyTaskListView.jsx
  client/app/queue/AttorneyTaskTable.jsx
  client/app/queue/CaseDetailsLink.jsx
  client/app/queue/JudgeReviewTaskListView.jsx
  client/app/queue/JudgeReviewTaskTable.jsx
  client/app/queue/QueueApp.jsx
Labels: In-Progress

#5229 Cancellation working for Supplemental Claim
  app/models/supplemental_claim_intake.rb
  spec/models/supplemental_claim_intake_spec.rb
Labels: In-Progress

#5232 Update ruby-bgs
  Gemfile
  Gemfile.lock
Labels: In-Progress

#5235 Adds participant_id to Veteran
  app/models/veteran.rb
  lib/generators/veteran.rb
  spec/models/veteran_spec.rb
Labels: In-Progress

#5224 "holdays" isn't a column in HEARSCHED
  lib/helpers/sanitizers.rb
Labels: In-Progress

#5234 Refactor: combine cancel methods into Intake model
  app/models/intake.rb
  app/models/ramp_election_intake.rb
  app/models/ramp_refiling_intake.rb
  app/models/supplemental_claim_intake.rb
Labels: In-Progress

#5160 Queue | Add Issue
  app/controllers/issues_controller.rb
  app/models/serializers/work_queue/appeal_serializer.rb
  app/models/serializers/work_queue/issue_serializer.rb
  client/app/queue/AddEditIssueView.jsx
  client/app/queue/QueueApp.jsx
  client/app/queue/SelectDispositionsView.jsx
  client/app/queue/reducers.js
  client/app/queue/uiReducer/uiActions.js
  lib/fakes/issue_repository.rb
  spec/controllers/issues_controller_spec.rb
  spec/feature/queue/queue_spec.rb
Labels: In-Progress

#5236 Add Rating model & query method for timely ratings
  app/models/rating.rb
  app/services/external_api/bgs_service.rb
  lib/fakes/bgs_service.rb
  lib/generators/rating.rb
  spec/models/rating_spec.rb
Labels: In-Progress

#5242 Adds RatingIssues
  app/models/rating.rb
  app/models/rating_issue.rb
  lib/fakes/bgs_service.rb
  spec/models/rating_issue_spec.rb
  spec/models/rating_spec.rb
Labels: In-Progress

#5245 If it is an acting judge with an attorney number, default to attorney…
  app/repositories/user_repository.rb
  spec/repositories/user_repository_spec.rb
Labels: In-Progress

#5238 Queue | Move VACOLS issue descriptions, remand reasons into shared constant
  app/models/issue.rb
  app/models/vacols/remand_reason.rb
  client/app/queue/AddEditIssueView.jsx
  client/app/queue/components/IssueListItem.jsx
  client/app/queue/constants.js
  client/app/queue/utils.js
  constants/ACTIVE_REMAND_REASONS_BY_ID.json
  constants/INACTIVE_REMAND_REASONS_BY_ID.json
  constants/ISSUE_INFO.json
  lib/constants/issue.rb
Labels: In-Progress

#5248 Adds serializers for Ratings and RatingIssues
  app/models/rating.rb
  app/models/rating_issue.rb
  app/models/supplemental_claim_intake.rb
  app/models/veteran.rb
  spec/models/rating_spec.rb
Labels: In-Progress

#5250 Caching Rating and RatingIssues
  app/models/rating.rb
  app/models/rating_issue.rb
  app/models/supplemental_claim_intake.rb
  app/models/veteran.rb
Labels: In-Progress

#5256 /queue/X: Adds document IDs to tasks
  app/models/appeal.rb
  app/models/serializers/work_queue/task_serializer.rb
  app/models/tasks/vacols_assignment.rb
  app/models/vacols/case_assignment.rb
  lib/fakes/queue_repository.rb
  spec/models/tasks/judge_vacols_assignment_spec.rb
Labels: In-Progress

#5251 Improve BGS fake rating endpoints. Sort ratings
  app/models/rating.rb
  lib/fakes/bgs_service.rb
  lib/generators/rating.rb
  spec/feature/intake_spec.rb
  spec/models/rating_spec.rb
Labels: In-Progress

#5262 Judge queue | Adds document ID to judge review table
  client/app/queue/JudgeReviewTaskTable.jsx
Labels: In-Progress

#5220 Fixes a flaky test in circleci
  .circleci/config.yml
Labels: In-Progress

#5261 Add more debugging statements to the efolder service failures
  app/services/external_api/efolder_service.rb
Labels: In-Progress

#5253 Implement attorney judge team for other envs
  app/models/judge.rb
  config/initializers/deploy_env.rb
  lib/constants/attorney_judge_teams.rb
  spec/controllers/users_controller_spec.rb
Labels: In-Progress

#5180 Adding DIC to appeal attributes
  app/models/appeal.rb
  app/models/issue.rb
  client/app/hearings/components/HearingWorksheetDocs.jsx
  spec/models/issue_spec.rb
Labels: In-Progress

#5267 This will fix sensitive errors for eX v2
  app/services/external_api/efolder_service.rb
  spec/services/external_api/efolder_service_spec.rb
Labels: In-Progress

#5270 Fixes veteran-is-appellant logic
  client/app/queue/CaseDetailsLink.jsx
Labels: In-Progress

#5271 Queue | Send full issue payload when creating/updating
  client/app/queue/AddEditIssueView.jsx
Labels: In-Progress

#5279 Update BGS gem
  Gemfile
  Gemfile.lock
Labels: In-Progress

#5278 Catch 400 status codes
  app/controllers/reader/documents_controller.rb
  app/jobs/fetch_documents_for_reader_user_job.rb
  app/services/external_api/efolder_service.rb
  lib/caseflow/error.rb
  spec/jobs/fetch_documents_for_reader_user_spec.rb
  spec/services/external_api/efolder_service_spec.rb
Labels: In-Progress

#5226 Anya/5053 judge assign to another attorney
  app/controllers/queue_controller.rb
  app/mappers/queue_mapper.rb
  app/models/attorney_case_reviews/attorney_case_review.rb
  app/models/judge_case_assignment.rb
  app/repositories/queue_repository.rb
  config/routes.rb
  spec/controllers/queue_controller_spec.rb
  spec/mappers/queue_mapper_spec.rb
  spec/models/attorney_case_reviews/attorney_case_review_spec.rb
  spec/models/judge_case_assignment_spec.rb
Labels: In-Progress

#5284 Some manifests take longer than 3 minutes to fetch - upping the time …
  app/services/external_api/efolder_service.rb
Labels: In-Progress

#5249 Queue | Update loadedQueue issues from server after CUD
  client/app/queue/AddEditIssueView.jsx
  client/app/queue/AttorneyTaskListView.jsx
  client/app/queue/QueueActions.js
  client/app/queue/QueueApp.jsx
  client/app/queue/QueueDetailView.jsx
  client/app/queue/SelectDispositionsView.jsx
  client/app/queue/SelectRemandReasonsView.jsx
  client/app/queue/SubmitDecisionView.jsx
  client/app/queue/components/IssueRemandReasonsOptions.jsx
  client/app/queue/constants.js
  client/app/queue/reducers.js
  spec/feature/queue/queue_spec.rb
Labels: In-Progress

#5273 Judges queue | Adds name of assigner to /queue/X
  app/models/appeal.rb
  app/models/serializers/work_queue/task_serializer.rb
  app/models/tasks/vacols_assignment.rb
  app/models/vacols/case_assignment.rb
  lib/fakes/queue_repository.rb
  spec/models/tasks/judge_vacols_assignment_spec.rb
Labels: In-Progress

#5275 Judges queue | Displays abbreviated name of the assigner
  client/app/queue/JudgeReviewTaskTable.jsx
Labels: In-Progress, Ready-to-Merge

#5291 Queue | Fix sending `after_certification` as boolean
  client/app/queue/components/IssueRemandReasonsOptions.jsx
Labels: In-Progress

#5288 Case search results links to /queue/appeals/:id instead of /queue/tasks/:id
  app/controllers/appeals_controller.rb
  client/app/queue/AppealDetail.jsx
  client/app/queue/AppellantDetail.jsx
  client/app/queue/AttorneyTaskTable.jsx
  client/app/queue/CaseDetail/CaseDetailActions.js
  client/app/queue/CaseDetail/CaseDetailReducer.js
  client/app/queue/CaseDetail/actionTypes.js
  client/app/queue/CaseDetailView.jsx
  client/app/queue/CaseListTable.jsx
  client/app/queue/QueueApp.jsx
  client/app/queue/QueueDetailView.jsx
  client/app/queue/ReaderLink.jsx
  client/app/queue/constants.js
  client/app/queue/reducers.js
  config/routes.rb
  spec/feature/queue/queue_spec.rb
Labels: In-Progress

#5287 Hearing Days | Table & Date header alignment
  app/assets/stylesheets/_hearings.scss
Labels: In-Progress

#5277 Veteran refactor
  app/models/appeal.rb
  app/models/concerns/associated_bgs_record.rb
  app/models/intake.rb
  app/models/ramp_review.rb
  app/models/veteran.rb
  lib/generators/veteran.rb
  spec/models/ramp_election_spec.rb
  spec/models/veteran_spec.rb
Labels: In-Progress

#5312 Add service to the appeals controller for metrics
  app/controllers/appeals_controller.rb
Labels: In-Progress

#5315 Anya/5142 second part
  lib/constants/attorney_judge_teams.rb
  lib/files/attorneys_judges_chiefs.csv
Labels: In-Progress

#5314 Docs Redesign
  app/assets/stylesheets/_hearings.scss
  client/app/hearings/components/HearingWorksheetDocs.jsx
  spec/feature/hearings_spec.rb
Labels: In-Progress

#5316 Remove Queue branding from Caseflow
  client/app/queue/QueueApp.jsx
Labels: In-Progress

#5318 Change copy when judge has no cases
  client/app/queue/JudgeTaskListView.jsx
Labels: In-Progress

#5259 Queue | Edit issue diagnostic code
  app/models/issue.rb
  app/models/serializers/work_queue/issue_serializer.rb
  client/app/queue/AddEditIssueView.jsx
  client/app/queue/QueueActions.js
  client/app/queue/components/IssueListItem.jsx
  client/app/queue/components/IssueRemandReasonsOptions.jsx
  client/app/queue/utils.js
  constants/DIAGNOSTIC_CODE_DESCRIPTIONS.json
  constants/ISSUE_INFO.json
  lib/constants/issue.rb
  spec/feature/queue/queue_spec.rb
Labels: In-Progress

#5324 Queue | Assigns URLs to queues
  app/controllers/queue_controller.rb
  app/views/queue/show.html.erb
  client/app/queue/JudgeTaskListView.jsx
  client/app/queue/QueueApp.jsx
  config/routes.rb
Labels: In-Progress, Ready-to-Merge

#5302 End Product refactor into module
  app/models/concerns/establishes_end_product.rb
  app/models/ramp_election.rb
  app/models/ramp_refiling.rb
  app/models/ramp_refiling_intake.rb
  app/models/ramp_review.rb
  app/models/supplemental_claim.rb
  spec/models/ramp_election_spec.rb
Labels: In-Progress

#5329 Judges queue | Splits JudgeTaskListView
  client/app/queue/JudgeAssignTaskListView.jsx
  client/app/queue/JudgeReviewTaskListView.jsx
  client/app/queue/QueueApp.jsx
Labels: In-Progress, Ready-to-Merge

#5214 fixing css for + issue on the worksheet page
  app/assets/stylesheets/_hearings.scss
Labels: In-Progress

#5325 Supplemental Claim End Product
  app/models/end_product.rb
  app/models/supplemental_claim.rb
  app/models/supplemental_claim_intake.rb
  client/app/intake/actions/supplementalClaim.js
  client/app/intake/pages/supplementalClaim/finish.jsx
  client/app/intake/reducers/supplementalClaim.js
  spec/feature/intake_spec.rb
  spec/models/supplemental_claim_intake_spec.rb
  spec/models/supplemental_claim_spec.rb
Labels: In-Progress

#5344 FACOLS | Sets the default station ID to the board's
  lib/tasks/local/vacols.rake
Labels: In-Progress, Ready-to-Merge

#5348 Supplemental Claim completed page
  client/app/intake/pages/completed.jsx
  client/app/intake/pages/supplementalClaim/completed.jsx
  client/app/intake/reducers/supplementalClaim.js
  spec/feature/intake_spec.rb
Labels: In-Progress

#5349 Update RAMP ineligible copy
  client/app/intake/pages/search.jsx
Labels: In-Progress
