Repository department-of-veterans-affairs/caseflow, pull requests merged in 2018-06, with the labels that each got.

#5745 Adding non-availability data structures
  app/models/hearings/co_non_availability.rb
  app/models/hearings/judge_non_availability.rb
  app/models/hearings/non_availability.rb
  app/models/hearings/ro_non_availability.rb
  db/migrate/20180531181503_create_non_availability.rb
  db/schema.rb
Labels: Ready-to-Merge

#5755 Moves COPY.json to the client directory
  client/COPY.json
  client/app/queue/AppellantDetail.jsx
  client/app/queue/AttorneyTaskListView.jsx
  client/app/queue/AttorneyTaskTable.jsx
  client/app/queue/BeaamAppealListView.jsx
  client/app/queue/BeaamTable.jsx
  client/app/queue/CaseDetailsLink.jsx
  client/app/queue/CaseListTable.jsx
  client/app/queue/CaseListView.jsx
  client/app/queue/CaseSearchErrorMessage.jsx
  client/app/queue/CaseSearchSheet.jsx
  client/app/queue/JudgeAssignTaskTable.jsx
  client/app/queue/JudgeReviewTaskListView.jsx
  client/app/queue/JudgeReviewTaskTable.jsx
  client/app/queue/components/JudgeStartCheckoutFlowDropdown.jsx
  client/app/queue/constants.js
  config/initializers/copy.rb
Labels: Ready-to-Merge

#5737 Queue | Serialize Remand Reasons
  app/models/issue.rb
  app/models/serializers/work_queue/issue_serializer.rb
  app/repositories/issue_repository.rb
  lib/fakes/issue_repository.rb
Labels: Ready-to-Merge

#5746 Adds a script to enable features locally
  README.md
  scripts/enable_features_dev.rb
Labels: Ready-to-Merge

#5754 Bug fix: removed update user for update_hearing operation. Revert to …
  app/models/vacols/case_hearing.rb
Labels: Ready-to-Merge

#5759 Adding debugging steps for FACOLS
  README.md
Labels: Ready-to-Merge

#5715 Adding the basic hearing schedule hearing days generator
  Gemfile
  Gemfile.lock
  app/services/hearing_schedule/generate_hearing_days_schedule.rb
  spec/services/hearing_schedule/generate_hearing_days_schedule_spec.rb
Labels: Ready-to-Merge

#5750 Modifying CircleCI caching keys
  .circleci/config.yml
Labels: In-Progress, Ready-to-Merge

#5758 Redesign case details title
  client/app/queue/CaseTitle.jsx
  client/app/queue/QueueDetailView.jsx
  spec/feature/queue/queue_spec.rb
Labels: Ready-to-Merge

#5730 Making Reader work with AMA appeals
  app/controllers/appeals_controller.rb
  app/controllers/reader/appeal_controller.rb
  app/controllers/reader/documents_controller.rb
  app/jobs/add_series_id_to_documents_job.rb
  app/models/appeal.rb
  app/models/legacy_appeal.rb
  app/models/serializers/work_queue/appeal_serializer.rb
  app/models/vacols/remand_reason.rb
  app/services/external_api/efolder_service.rb
  app/services/external_api/vbms_service.rb
  client/app/queue/BeaamTable.jsx
  client/app/queue/components/IssueListItem.jsx
  client/app/reader/PdfViewer/PdfViewerActions.js
  db/seeds.rb
  lib/fakes/vbms_service.rb
  spec/factories/vacols/case.rb
  spec/models/appeal_spec.rb
  spec/models/hearing_spec.rb
Labels: In-Progress, Ready-to-Merge

#5707 Judges | Review dispositions
  client/app/queue/QueueApp.jsx
  client/app/queue/QueueDetailView.jsx
  client/app/queue/SelectDispositionsView.jsx
  client/app/queue/SelectRemandReasonsView.jsx
  client/app/queue/components/DecisionViewBase.jsx
  client/app/queue/components/JudgeStartCheckoutFlowDropdown.jsx
  client/app/queue/constants.js
  client/app/queue/uiReducer/uiActions.js
  client/app/queue/uiReducer/uiConstants.js
  client/app/queue/uiReducer/uiReducer.js
Labels: In-Progress

#5769 HP Worksheet symlink npm styles for wysiwg lib
  app/assets/stylesheets/application.css
  app/assets/stylesheets/hearings/_hearings_styles_root.css
  app/assets/stylesheets/hearings/_react-draft-wysiwyg.css
  app/assets/stylesheets/hearings/_wysiwyg.scss
  app/assets/stylesheets/react-draft-wysiwyg.css
Labels: Ready-to-Merge

#5761 Allocation data structure
  app/models/hearings/allocation.rb
  db/migrate/20180601173719_create_allocation.rb
  db/schema.rb
Labels: In-Progress, Ready-to-Merge

#5770 Moves constants dir to client dir for Flow
  client/app/queue/AddEditIssueView.jsx
  client/app/queue/components/IssueListItem.jsx
  client/app/queue/components/SelectIssueDispositionDropdown.jsx
  client/app/queue/constants.js
  client/app/queue/utils.js
  client/constants/ACTIVE_REMAND_REASONS_BY_ID.json
  client/constants/DIAGNOSTIC_CODE_DESCRIPTIONS.json
  client/constants/INACTIVE_REMAND_REASONS_BY_ID.json
  client/constants/ISSUE_INFO.json
  client/constants/VACOLS_DISPOSITIONS_BY_ID.json
  config/initializers/constants.rb
Labels: Ready-to-Merge

#5783 Close appeals irregardless of election receipt date
  app/models/legacy_appeal.rb
  app/models/ramp_election_intake.rb
  spec/models/legacy_appeal_spec.rb
Labels: In-Progress

#5734 Add more info to efolder failure logs
  app/controllers/reader/documents_controller.rb
  app/services/external_api/efolder_service.rb
  lib/caseflow/error.rb
  spec/jobs/fetch_documents_for_reader_user_spec.rb
  spec/services/external_api/efolder_service_spec.rb
Labels: Ready-to-Merge

#5787 Add rake tasks to rebuild local dev env in consolidated steps
  lib/tasks/local/build.rake
  lib/tasks/local/destroy.rake
Labels: Ready-to-Merge

#5718 Create judge case review table and logic
  app/mappers/queue_mapper.rb
  app/models/judge_case_review.rb
  app/models/legacy_appeal.rb
  app/models/vacols/decass.rb
  app/repositories/queue_repository.rb
  constants/JUDGE_CASE_REVIEW_OPTIONS.json
  db/migrate/20180529171733_create_judge_case_reviews.rb
  db/schema.rb
  spec/mappers/queue_mapper_spec.rb
  spec/models/judge_case_review_spec.rb
Labels: Ready-to-Merge

#5762 Queue | Use disposition ID
  app/mappers/issue_mapper.rb
  app/models/issue.rb
  app/models/serializers/work_queue/issue_serializer.rb
  app/repositories/issue_repository.rb
  client/app/queue/SelectDispositionsView.jsx
  client/app/queue/components/IssueListItem.jsx
  client/app/queue/components/SelectIssueDispositionDropdown.jsx
  client/app/queue/constants.js
  client/app/queue/utils.js
  lib/fakes/data/appeal_data.rb
  lib/generators/issue.rb
  spec/controllers/tasks_controller_spec.rb
  spec/mappers/issue_mapper_spec.rb
  spec/repositories/issue_repository_spec.rb
Labels: In-Progress

#5796 Increase queue request timeout
  client/app/queue/QueueLoadingScreen.jsx
  client/app/util/ApiUtil.js
Labels: In-Progress, Ready-to-Merge

#5793 Improve build local dev env script
  README.md
  lib/tasks/local/build.rake
Labels: In-Progress, Ready-to-Merge

#5794 Pass BGS timeout through to API
  app/controllers/api/v2/appeals_controller.rb
  spec/feature/api/v2/appeals_spec.rb
Labels: Ready-to-Merge

#5803 Judge Queue | Adds check for timeout errors
  client/app/queue/AssignedCasesPage.jsx
Labels: In-Progress, Ready-to-Merge

#5795 Add Hearing Schedule tab to 'test/users' page
  app/controllers/hearings/schedule_controller.rb
  app/controllers/test/users_controller.rb
  app/models/user.rb
  app/models/vacols/case_hearing.rb
  config/routes.rb
  lib/tasks/local/vacols.rake
  local/vacols/VACOLS::Actcode_dump.csv
Labels: Ready-to-Merge

#5682 Re-factor attorney case reviews to be more flexible
  app/controllers/tasks_controller.rb
  app/models/attorney_case_review.rb
  app/models/attorney_case_reviews/draft_decision.rb
  app/models/attorney_case_reviews/omo_request.rb
  client/app/queue/SubmitDecisionView.jsx
  client/app/queue/constants.js
  db/migrate/20180525153724_rename_type_to_title_in_attorney_case_reviews.rb
  db/schema.rb
  spec/controllers/tasks_controller_spec.rb
  spec/models/attorney_case_review_spec.rb
  spec/models/attorney_case_reviews/draft_decision_spec.rb
  spec/models/attorney_case_reviews/omo_request_spec.rb
Labels: In-Progress

#5804 Tracer for reclosure of RAMP closed appeals job
  app/jobs/sync_intake_job.rb
  app/models/legacy_appeal.rb
  app/models/ramp_closed_appeal.rb
  app/models/vacols/case.rb
  app/services/appeal_repository.rb
  lib/fakes/appeal_repository.rb
  spec/jobs/sync_intake_job_spec.rb
  spec/models/ramp_closed_appeal_spec.rb
Labels: In-Progress, Ready-to-Merge

#5752 Resolves Hearing Prep accessibility issues
  app/assets/stylesheets/_hearings.scss
  client/app/components/Checkbox.jsx
  client/app/components/TabWindow.jsx
  client/app/hearings/components/DocketHearingRow.jsx
Labels: In-Progress, Ready-to-Merge

#5801 Initial support for multiple elections in ramp refilings
  app/models/ramp_refiling.rb
  app/models/ramp_refiling_intake.rb
  spec/models/ramp_refiling_spec.rb
Labels: In-Progress, Ready-to-Merge

#5717 adding a check to see if the docket date is more than 30 days away in HP
  client/app/hearings/Dockets.jsx
  lib/tasks/local/vacols.rake
  spec/feature/hearings_spec.rb
Labels: In-Progress, Ready-to-Merge

#5807 fixing the tests for generate hearing days
  app/services/hearing_schedule/generate_hearing_days_schedule.rb
  spec/factories/non_availability.rb
  spec/factories/ro_schedule_period.rb
  spec/services/hearing_schedule/generate_hearing_days_schedule_spec.rb
Labels: In-Progress, Ready-to-Merge

#5797 Update Vacols location to Caseflow when assigned to a co-located user
  app/models/legacy_appeal.rb
  app/models/tasks/co_located_admin_action.rb
  app/services/appeal_repository.rb
  client/constants/CO_LOCATED_ADMIN_ACTIONS.json
  client/constants/JUDGE_CASE_REVIEW_OPTIONS.json
  spec/models/co_located_admin_action_spec.rb
Labels: In-Progress, Ready-to-Merge

#5625 HP Refactor copy button
  app/assets/stylesheets/_hearings.scss
  client/app/hearings/components/WorksheetHeader.jsx
  client/package.json
  client/yarn.lock
Labels: In-Progress

#5811 Re-factor judge case assignment logic into its own class and move tas…
  app/controllers/tasks_controller.rb
  app/models/attorney_case_review.rb
  app/models/concerns/legacy_task_concern.rb
  app/models/judge_case_assignment_to_attorney.rb
  app/models/judge_case_review.rb
  app/models/legacy_tasks/attorney_legacy_task.rb
  app/models/queues/attorney_queue.rb
  spec/controllers/tasks_controller_spec.rb
  spec/models/judge_case_assignment_to_attorney_spec.rb
  spec/models/legacy_tasks/attorney_legacy_task_spec.rb
Labels: In-Progress, Ready-to-Merge

#5812 Added values for VACOLS actcode table. These values are required for …
  lib/helpers/sanitizers.rb
  lib/tasks/local/vacols.rake
  local/vacols/VACOLS::Actcode_dump.csv
Labels: In-Progress, Ready-to-Merge

#5817 adding travel board schedule prod data with fields sanitized
  lib/tasks/local/vacols.rake
  local/vacols/VACOLS::TravelBoardSchedule_dump.csv
Labels: In-Progress, Ready-to-Merge

#5799 Ability to choose claimant other than the Veteran - Front end
  app/models/intake.rb
  app/models/relationship.rb
  app/models/veteran.rb
  client/app/intake/actions/common.js
  client/app/intake/components/SelectClaimant.jsx
  client/app/intake/constants.js
  client/app/intake/pages/higherLevelReview/review.jsx
  client/app/intake/reducers/higherLevelReview.js
  client/app/intake/util/index.js
  lib/fakes/bgs_service.rb
  spec/feature/intake/higher_level_review_spec.rb
Labels: In-Progress, Ready-to-Merge

#5784 Queue | Update remand reasons
  app/models/issue.rb
  app/models/vacols/remand_reason.rb
  app/repositories/issue_repository.rb
  app/repositories/remand_reason_repository.rb
  lib/fakes/issue_repository.rb
  lib/fakes/remand_reason_repository.rb
  spec/factories/vacols/remand_reason.rb
  spec/repositories/issue_repository_spec.rb
  spec/repositories/remand_reason_repository_spec.rb
Labels: In-Progress, Ready-to-Merge

#5813 Add appeal closure logic
  app/models/legacy_appeal.rb
  app/models/ramp_closed_appeal.rb
  app/services/appeal_repository.rb
  spec/models/ramp_closed_appeal_spec.rb
Labels: In-Progress, Ready-to-Merge

#5839 Fix no relationships
  app/services/external_api/bgs_service.rb
Labels: In-Progress, Ready-to-Merge

#5763 Rewrite tests for FACOLS, cancel_certification and save_certification…
  spec/factories/certification.rb
  spec/factories/user.rb
  spec/feature/certification/cancel_certification_spec.rb
  spec/feature/certification/save_certification_spec.rb
  spec/feature/certification/start_certification_spec.rb
  spec/jobs/start_certification_job_spec.rb
  spec/models/certification_spec.rb
  spec/rails_helper.rb
Labels: In-Progress

#5826 Anya/5611 judge checkout create controller
  app/controllers/tasks_controller.rb
  app/models/judge_case_review.rb
  spec/controllers/tasks_controller_spec.rb
  spec/models/judge_case_review_spec.rb
Labels: In-Progress, Ready-to-Merge

#5816 Refactors Redux state
  client/.eslintrc.js
  client/app/queue/AddEditIssueView.jsx
  client/app/queue/AssignedCasesPage.jsx
  client/app/queue/AttorneyTaskListView.jsx
  client/app/queue/AttorneyTaskTable.jsx
  client/app/queue/BeaamTable.jsx
  client/app/queue/JudgeAssignTaskListView.jsx
  client/app/queue/JudgeReviewTaskListView.jsx
  client/app/queue/JudgeReviewTaskTable.jsx
  client/app/queue/SubmitDecisionView.jsx
  client/app/queue/reducers.js
Labels: In-Progress, Ready-to-Merge

#5843 Don't call relationships unless ama is enabled
  app/models/intake.rb
Labels: In-Progress, Ready-to-Merge

#5853 Intake fix
  app/models/intake.rb
Labels: In-Progress

#5834 Queue help page
  app/views/help/queue.html.erb
  client/app/help/HelpRootView.jsx
  client/app/help/components/QueueHelp.jsx
  client/app/help/index.js
  config/routes.rb
Labels: In-Progress, Ready-to-Merge

#5841 Set open timeout and read timout to longer time
  app/services/external_api/efolder_service.rb
Labels: In-Progress, Ready-to-Merge

#5845 Make CaseTitle self contained
  client/app/queue/CaseTitle.jsx
  client/app/queue/QueueDetailView.jsx
Labels: In-Progress, Ready-to-Merge

#5837 Add case snapshot to case details page
  client/COPY.json
  client/app/constants/AppConstants.js
  client/app/queue/AppealDetail.jsx
  client/app/queue/CaseSnapshot.jsx
  client/app/queue/QueueDetailView.jsx
  spec/feature/queue/queue_spec.rb
  spec/models/certification_spec.rb
Labels: In-Progress, Ready-to-Merge

#5864 Queue | Enable Case details link for paper cases
  client/app/queue/CaseDetailsLink.jsx
Labels: In-Progress, Ready-to-Merge

#5865 Do not make document count requests for paper cases
  client/app/queue/AppealDocumentCount.jsx
Labels: In-Progress, Ready-to-Merge

#5866 Update VACOLS RAMP re-close script
  app/models/ramp_closed_appeal.rb
  app/models/vacols/case.rb
  app/services/appeal_repository.rb
Labels: In-Progress, Ready-to-Merge

#5732 Filtering RO non-available days for each RO
  app/services/hearing_schedule/generate_hearing_days_schedule.rb
  spec/factories/non_availability.rb
  spec/fake_date_helper.rb
  spec/rails_helper.rb
  spec/services/hearing_schedule/generate_hearing_days_schedule_spec.rb
Labels: In-Progress, Ready-to-Merge

#5830 Ignore EfolderAccessForbidden error is document_count method
  app/controllers/appeals_controller.rb
Labels: In-Progress, Ready-to-Merge

#5815 Allow different claimant from veteran (Part 2)
  app/models/appeal.rb
  app/models/appeal_intake.rb
  app/models/claimant.rb
  app/models/higher_level_review.rb
  app/models/higher_level_review_intake.rb
  app/models/supplemental_claim.rb
  app/models/supplemental_claim_intake.rb
  app/models/veteran.rb
  client/app/intake/actions/appeal.js
  client/app/intake/actions/higherLevelReview.js
  client/app/intake/actions/supplementalClaim.js
  client/app/intake/pages/appeal/review.jsx
  client/app/intake/pages/supplementalClaim/review.jsx
  client/app/intake/reducers/appeal.js
  client/app/intake/reducers/supplementalClaim.js
  db/migrate/20180607184059_create_claimants.rb
  db/schema.rb
  spec/controllers/reader/appeal_controller_spec.rb
  spec/feature/intake/appeal_spec.rb
  spec/feature/intake/higher_level_review_spec.rb
  spec/feature/intake/supplemental_claim_spec.rb
  spec/models/appeal_intake_spec.rb
  spec/models/higher_level_review_intake_spec.rb
  spec/models/supplemental_claim_intake_spec.rb
Labels: In-Progress

#5856 Fails build and destroy scripts on command failures
  lib/tasks/local/build.rake
  lib/tasks/local/destroy.rake
Labels: In-Progress, Ready-to-Merge

#5857 Create issues during judge case review
  app/controllers/tasks_controller.rb
  app/models/attorney_case_review.rb
  app/models/concerns/legacy_task_concern.rb
  app/models/judge_case_review.rb
  spec/controllers/tasks_controller_spec.rb
  spec/models/judge_case_review_spec.rb
Labels: In-Progress, Ready-to-Merge

#5870 Remove queue_case_search feature toggle
  app/views/queue/index.html.erb
  app/views/queue/show.html.erb
  client/app/queue/QueueApp.jsx
  client/app/queue/SearchBar.jsx
  scripts/enable_features_dev.rb
  spec/feature/queue/queue_spec.rb
Labels: In-Progress, Ready-to-Merge

#5900 Moving power of attorney to abide by the test_facols feature toggle.
  app/models/power_of_attorney.rb
  spec/feature/certification/save_certification_spec.rb
  spec/models/judge_case_review_spec.rb
Labels: In-Progress, Ready-to-Merge

#5840 Extracts activeAppeal from state correctly
  client/app/queue/QueueLoadingScreen.jsx
  spec/controllers/appeals_controller_spec.rb
Labels: In-Progress, Ready-to-Merge

#5863 Ignore ClientRequestError when hitting document_count endpoint
  app/controllers/appeals_controller.rb
Labels: In-Progress, Ready-to-Merge

#5881 Intake AMA refactoring
  client/app/intake/actions/ama.js
  client/app/intake/actions/appeal.js
  client/app/intake/actions/higherLevelReview.js
  client/app/intake/actions/supplementalClaim.js
  client/app/intake/pages/appeal/finish.jsx
  client/app/intake/pages/higherLevelReview/finish.jsx
  client/app/intake/pages/supplementalClaim/finish.jsx
Labels: In-Progress, Ready-to-Merge

#5789 Adding spreadsheet templates to repo
  public/JudgeAssignmentTemplate.xlsx
  public/ROAssignmentTemplate.xlsx
Labels: In-Progress, Ready-to-Merge

#5869 5776 remove election from refiling code
  app/models/ramp_refiling_intake.rb
  spec/factories/ramp_election.rb
  spec/feature/intake/intake_stats_spec.rb
  spec/feature/intake/ramp_refiling_spec.rb
  spec/models/ramp_refiling_intake_spec.rb
  spec/models/ramp_refiling_spec.rb
Labels: In-Progress, Ready-to-Merge

#5887 Don't let VBMS errors stop SyncIntakeJob
  app/jobs/sync_intake_job.rb
  app/models/ramp_election.rb
Labels: In-Progress, Ready-to-Merge

#5899 Adding factory bot to demo env
  Gemfile
Labels: In-Progress, Ready-to-Merge

#5747 Move appeal_events_spec.rb tests to FACOLS
  app/models/vacols/case.rb
  app/models/vacols/priorloc.rb
  spec/controllers/reader/appeal_controller_spec.rb
  spec/factories/vacols/case.rb
  spec/factories/vacols/case_hearing.rb
  spec/factories/vacols/case_issue.rb
  spec/factories/vacols/priorloc.rb
  spec/feature/certification/cancel_certification_spec.rb
  spec/feature/certification/start_certification_spec.rb
  spec/jobs/start_certification_job_spec.rb
  spec/models/appeal_events_spec.rb
  spec/models/certification_spec.rb
Labels: In-Progress

#5896 Queue | Use CaseDetailsLink in CaseListTable
  client/app/queue/CaseDetailsLink.jsx
  client/app/queue/CaseListTable.jsx
Labels: In-Progress

#5893 Fix judge case review test
  spec/factories/vacols/case.rb
  spec/factories/vacols/case_issue.rb
Labels: In-Progress, Ready-to-Merge

#5527 Refactor HP print pdf
  app/assets/stylesheets/application.css
  app/assets/stylesheets/hearings/_worksheet_print.scss
  client/app/components/PrintPageBreak.jsx
  client/app/hearings/HearingWorksheet.jsx
  client/app/hearings/components/HearingWorksheetDocs.jsx
  client/app/hearings/components/WorksheetHeader.jsx
Labels: In-Progress

#5901 Rspec: Stops filtering backtraces
  spec/spec_helper.rb
Labels: In-Progress, Ready-to-Merge

#5894 Update external dependencies section in readme
  README.md
Labels: In-Progress, Ready-to-Merge

#5892 Refactor AMA Intake - submitReview
  client/app/intake/actions/ama.js
  client/app/intake/actions/appeal.js
  client/app/intake/actions/higherLevelReview.js
  client/app/intake/actions/supplementalClaim.js
  client/app/intake/pages/appeal/review.jsx
  client/app/intake/pages/higherLevelReview/review.jsx
  client/app/intake/pages/supplementalClaim/review.jsx
  client/app/intake/util/index.js
Labels: In-Progress, Ready-to-Merge

#5897 Refactor rating issues
  client/app/intake/components/RatedIssueCounter.jsx
  client/app/intake/components/RatedIssues.jsx
  client/app/intake/pages/appeal/finish.jsx
  client/app/intake/pages/appeal/ratedIssues.jsx
  client/app/intake/pages/higherLevelReview/finish.jsx
  client/app/intake/pages/higherLevelReview/ratedIssues.jsx
  client/app/intake/pages/supplementalClaim/finish.jsx
Labels: In-Progress, Ready-to-Merge

#5902 Refactor AMA Intake non-rated issues
  client/app/intake/components/NonRatedIssue.jsx
  client/app/intake/components/NonRatedIssues.jsx
  client/app/intake/pages/appeal/finish.jsx
  client/app/intake/pages/appeal/nonRatedIssues.jsx
  client/app/intake/pages/higherLevelReview/finish.jsx
  client/app/intake/pages/higherLevelReview/nonRatedIssues.jsx
  client/app/intake/pages/supplementalClaim/finish.jsx
  client/app/intake/pages/supplementalClaim/nonRatedIssues.jsx
Labels: In-Progress

#5898 VACOLS Integration - Query for all master records by a date range
  app/controllers/hearings/hearing_day_controller.rb
  app/controllers/hearings/schedule_controller.rb
  app/controllers/hearings_controller.rb
  app/controllers/test/users_controller.rb
  app/models/hearing.rb
  app/models/hearing_day.rb
  app/models/serializers/hearings/hearing_day_serializer.rb
  app/models/serializers/hearings/travel_board_schedule_serializer.rb
  app/models/vacols/case_hearing.rb
  app/models/vacols/travel_board_schedule.rb
  app/repositories/hearing_day_repository.rb
  app/repositories/hearing_repository.rb
  app/views/hearings/schedule_index.html.erb
  config/routes.rb
  lib/fakes/hearing_repository.rb
  lib/generators/vacols/travel_board_schedule.rb
  spec/models/hearing_day_spec.rb
  spec/models/hearing_spec.rb
  spec/requests/hearing_day_spec.rb
Labels: In-Validation, Ready-to-Merge

#5915 Use username when updating location, not RO
  app/models/vacols/case.rb
Labels: In-Progress

#5911 Capture another error that happens on sync
  app/models/ramp_election.rb
Labels: In-Progress, Ready-to-Merge

#5918 Return assigned to attorney date for judge
  app/models/legacy_tasks/judge_legacy_task.rb
  app/models/legacy_tasks/legacy_task.rb
  app/models/serializers/work_queue/task_serializer.rb
  spec/models/legacy_tasks/judge_legacy_task_spec.rb
Labels: In-Progress, Ready-to-Merge

#5920 Limit the issue notes' length
  app/mappers/issue_mapper.rb
  spec/mappers/issue_mapper_spec.rb
Labels: In-Progress, Ready-to-Merge

#5880 Judge Spreadsheet Validation
  app/services/hearing_schedule/validate_judge_spreadsheet.rb
  spec/models/hearings/judge_schedule_period_spec.rb
  spec/services/hearing_schedule/validate_judge_spreadsheet_spec.rb
  spec/support/judgeDuplicateDates.xlsx
  spec/support/judgeNotInDb.xlsx
  spec/support/judgeWrongDataType.xlsx
  spec/support/validJudgeSpreadsheet.xlsx
Labels: In-Progress, Ready-to-Merge

#5891 Anya/5844 facols tests
  app/mappers/queue_mapper.rb
  app/repositories/queue_repository.rb
  app/repositories/user_repository.rb
  spec/repositories/queue_repository_spec.rb
Labels: In-Progress, Ready-to-Merge

#5907 Queue | Set default userRole
  app/views/queue/index.html.erb
Labels: In-Progress, Ready-to-Merge

#5871 Fetching Travelboard hearing days
  app/mappers/travel_board_schedule_mapper.rb
  app/services/hearing_schedule/generate_hearing_days_schedule.rb
  spec/factories/vacols/travel_board_schedule.rb
  spec/services/hearing_schedule/generate_hearing_days_schedule_spec.rb
Labels: In-Progress, Ready-to-Merge

#5912 Start working on EndProductEstablishment class
  app/models/concerns/establishes_end_product.rb
  app/models/end_product_establishment.rb
  app/models/ramp_refiling.rb
  spec/models/end_product_establishment_spec.rb
  spec/models/higher_level_review_spec.rb
  spec/models/ramp_election_spec.rb
  spec/models/supplemental_claim_spec.rb
Labels: In-Progress

#5924 disable prepped checkbox until docket loads
  client/app/hearings/components/WorksheetHeaderVeteranSelection.jsx
Labels: In-Progress, Ready-to-Merge

#5921 Tweak case snapshot styling
  client/COPY.json
  client/app/queue/CaseSnapshot.jsx
  spec/feature/queue/queue_spec.rb
Labels: In-Progress, Ready-to-Merge

#5941 update Redis version used by CircleCI
  .circleci/config.yml
Labels: In-Progress, Ready-to-Merge

#5938 Queue | Adds unit tests for RemandReasonRepository.create_remand_reasons and RemandReasonRepository.delete_remand_reasons
  app/repositories/remand_reason_repository.rb
  spec/repositories/remand_reason_repository_spec.rb
Labels: In-Progress, Ready-to-Merge

#5610 Judge check out | Evaluate decision
  client/COPY.json
  client/app/components/Alert.jsx
  client/app/components/CheckboxGroup.jsx
  client/app/queue/CaseDetailsView.jsx
  client/app/queue/CaseSnapshot.jsx
  client/app/queue/CaseTitle.jsx
  client/app/queue/EvaluateDecisionView.jsx
  client/app/queue/QueueApp.jsx
  client/app/queue/SelectDispositionsView.jsx
  client/app/queue/components/JudgeStartCheckoutFlowDropdown.jsx
  client/app/queue/constants.js
Labels: In-Progress, Ready-to-Merge

#5910 Revert "Rspec: Stops filtering backtraces"
  spec/spec_helper.rb
Labels: In-Progress, Ready-to-Merge

#5939 Improve display of case snapshot at slimmer widths
  client/app/queue/CaseSnapshot.jsx
Labels: In-Progress, Ready-to-Merge

#5935 Write Facols unit tests for remand repository
  app/models/vacols/remand_reason.rb
  app/repositories/remand_reason_repository.rb
  spec/factories/vacols/case_issue.rb
  spec/repositories/remand_reason_repository_spec.rb
Labels: In-Progress, Ready-to-Merge

#5942 Improve appearance of case title at narrow widths
  client/app/queue/CaseTitle.jsx
Labels: In-Progress, Ready-to-Merge

#5943 Queue | Remove unneeded css check in test
  spec/feature/queue/queue_spec.rb
Labels: In-Progress, Ready-to-Merge

#5909 RO Non-Availability Sheet Validation
  app/models/regional_office.rb
  app/services/hearing_schedule/validate_judge_spreadsheet.rb
  app/services/hearing_schedule/validate_ro_spreadsheet.rb
  spec/factories/ro_schedule_period.rb
  spec/services/hearing_schedule/generate_hearing_days_schedule_spec.rb
  spec/services/hearing_schedule/validate_ro_spreadsheet_spec.rb
  spec/support/coDuplicateDates.xlsx
  spec/support/coOutOfRange.xlsx
  spec/support/coWrongDataType.xlsx
  spec/support/duplicateDates.xlsx
  spec/support/outOfRange.xlsx
  spec/support/roDuplicateDates.xlsx
  spec/support/roNotInSystem.xlsx
  spec/support/roNotListed.xlsx
  spec/support/roOutOfRange.xlsx
  spec/support/roWrongDataType.xlsx
  spec/support/validRoSpreadsheet.xlsx
  spec/support/wrongDataType.xlsx
Labels: In-Progress, Ready-to-Merge

#5947 Trying to speed up reader tests
  app/controllers/reader/application_controller.rb
  spec/feature/reader/reader_spec.rb
  spec/support/database_cleaner.rb
Labels: In-Progress

#5922 Moving Appeal Status tests to FACOLS
  app/models/vacols/case_docket.rb
  spec/factories/vacols/case.rb
  spec/factories/vacols/case_hearing.rb
  spec/factories/vacols/case_issue.rb
  spec/jobs/take_docket_snapshot_job_spec.rb
  spec/models/appeal_history_spec.rb
  spec/models/appeal_series_alerts_spec.rb
  spec/models/appeal_series_issues_spec.rb
  spec/models/docket_snapshot_spec.rb
Labels: In-Progress, Ready-to-Merge

#5944 Return AMA appeals in queue case search
  app/controllers/appeals_controller.rb
Labels: In-Progress, Ready-to-Merge

#5959 Upgrades Sprockets to fix vulnerability
  Gemfile.lock
Labels: In-Progress

#5952 Remove actions column from attorney task table
  client/app/queue/AttorneyTaskTable.jsx
  spec/feature/queue/queue_spec.rb
Labels: In-Progress, Ready-to-Merge

#5956 Queue | Add judge checkout flow dropdown to CaseSnapshot, remove from JudgeReviewTaskTable
  client/app/queue/CaseSnapshot.jsx
  client/app/queue/JudgeReviewTaskTable.jsx
  client/app/queue/components/JudgeStartCheckoutFlowDropdown.jsx
Labels: In-Progress, Ready-to-Merge

#5965 Do not allow blank descriptions for non-rated issues
  client/app/intake/components/NonRatedIssues.jsx
  client/app/intake/util/index.js
Labels: In-Progress

#5916 Judge Queue: Harmonizes /queue and /tasks endpoints
  app/controllers/tasks_controller.rb
  app/models/judge_case_assignment_to_attorney.rb
  app/models/legacy_tasks/legacy_task.rb
  client/app/queue/utils.js
  client/test/karma/queue/QueueLoadingScreen-test.js
  spec/controllers/tasks_controller_spec.rb
  spec/factories/vacols/decass.rb
  spec/models/legacy_tasks/attorney_legacy_task_spec.rb
  spec/models/legacy_tasks/judge_legacy_task_spec.rb
Labels: In-Progress, Ready-to-Merge

#5946 Frontend Code Structure
  app/controllers/test/users_controller.rb
  app/views/hearings/schedule_index.html.erb
  client/app/constants/AppConstants.js
  client/app/hearingSchedule/containers/BuildSchedule.jsx
  client/app/hearingSchedule/index.jsx
  client/app/index.js
  config/routes.rb
  spec/controllers/home_controller_spec.rb
  spec/feature/out_of_service_spec.rb
Labels: In-Progress, Ready-to-Merge

#5964 Fixing the first set of intake tests
  spec/feature/intake/intake_spec.rb
Labels: In-Progress, Ready-to-Merge, sierra

#5957 Anya/5884 determine if user co located admin
  app/controllers/application_controller.rb
  app/controllers/tasks_controller.rb
  app/models/judge_case_assignment_to_attorney.rb
  app/models/queues/work_queue.rb
  app/models/tasks/co_located_admin_action.rb
  app/models/user.rb
  app/repositories/user_repository.rb
  app/views/queue/index.html.erb
  app/views/queue/show.html.erb
  lib/fakes/user_repository.rb
  spec/controllers/tasks_controller_spec.rb
  spec/factories/vacols/staff.rb
  spec/models/co_located_admin_action_spec.rb
  spec/models/judge_case_assignment_to_attorney_spec.rb
  spec/repositories/user_repository_spec.rb
Labels: In-Progress, Ready-to-Merge

#5962 Allocation validation
  app/services/hearing_schedule/validate_ro_spreadsheet.rb
  spec/services/hearing_schedule/validate_ro_spreadsheet_spec.rb
  spec/support/allocationDuplicateRo.xlsx
  spec/support/allocationWrongCoLocation.xlsx
  spec/support/allocationWrongDataType.xlsx
Labels: In-Progress

#5970 Refactor legacy task routes
  app/controllers/application_controller.rb
  app/controllers/case_reviews_controller.rb
  app/controllers/issues_controller.rb
  app/controllers/legacy_tasks_controller.rb
  app/controllers/tasks_controller.rb
  app/models/judge_case_assignment_to_attorney.rb
  client/app/queue/SubmitDecisionView.jsx
  config/routes.rb
  spec/controllers/case_reviews_controller_spec.rb
  spec/controllers/legacy_tasks_controller_spec.rb
  spec/controllers/tasks_controller_spec.rb
Labels: In-Progress, Ready-to-Merge

#5454 Create a way to set up application debug context for each active job
  app/jobs/application_job.rb
  app/jobs/create_establish_claim_tasks_job.rb
  app/jobs/fetch_documents_for_reader_user_job.rb
  app/jobs/prepare_establish_claim_tasks_job.rb
  app/jobs/retrieve_documents_for_reader_job.rb
  app/jobs/sync_intake_job.rb
  spec/controllers/home_controller_spec.rb
Labels: In-Progress, Ready-to-Merge

#5966 Match intake with existing ramp election on complete
  app/models/ramp_election_intake.rb
  client/app/intake/pages/search.jsx
  spec/feature/intake/intake_stats_spec.rb
  spec/feature/intake/ramp_election_spec.rb
  spec/models/intake_stats_spec.rb
  spec/models/ramp_election_intake_spec.rb
Labels: In-Progress, Ready-to-Merge

#5984 Allow more decision codes for work product
  app/models/vacols/decass.rb
Labels: In-Progress, Ready-to-Merge

#5990 Fix test leaking feature toggle state
  spec/feature/queue/queue_spec.rb
Labels: In-Progress

#5992 Update COPY.json
  client/COPY.json
Labels: In-Progress, Ready-to-Merge

#5988 Move Appeal Decision Types to Shared Constants file
  app/models/attorney_case_review.rb
  client/app/queue/QueueApp.jsx
  client/app/queue/SubmitDecisionView.jsx
  client/app/queue/components/JudgeStartCheckoutFlowDropdown.jsx
  client/app/queue/components/SelectCheckoutFlowDropdown.jsx
  client/app/queue/constants.js
  client/app/queue/utils.js
  client/constants/APPEAL_DECISION_TYPES.json
  spec/controllers/case_reviews_controller_spec.rb
  spec/models/attorney_case_review_spec.rb
Labels: In-Progress, Ready-to-Merge

#5720 Judges | Assign cases | Select and assign multiple cases to an attorney
  app/views/queue/index.html.erb
  app/views/queue/show.html.erb
  client/app/components/AssignWidget.jsx
  client/app/components/SearchableDropdown.jsx
  client/app/queue/JudgeAssignTaskListView.jsx
  client/app/queue/JudgeAssignTaskTable.jsx
  client/app/queue/QueueActions.js
  client/app/queue/constants.js
  client/app/queue/reducers.js
  scripts/enable_features_dev.rb
Labels: In-Progress, Ready-to-Merge

#5980 Importing judge non-availability
  app/models/hearings/judge_non_availability.rb
  app/services/hearing_schedule/get_spreadsheet_data.rb
  app/services/hearing_schedule/validate_judge_spreadsheet.rb
  spec/models/hearings/judge_non_availability_spec.rb
Labels: In-Progress, Ready-to-Merge

#5985 Build Schedule welcome page
  client/COPY.json
  client/app/components/RenderFunctions.jsx
  client/app/hearingSchedule/components/BuildSchedule.jsx
  client/app/hearingSchedule/containers/BuildSchedule.jsx
  client/app/hearingSchedule/containers/BuildScheduleContainer.jsx
  client/app/hearingSchedule/index.jsx
  client/app/reader/PdfUI.jsx
  client/test/karma/hearingSchedule/components/BuildSchedule-test.js
Labels: In-Progress, Ready-to-Merge

#5978 Anya/5936 multiple admin actions 2
  app/controllers/application_controller.rb
  app/controllers/tasks_controller.rb
  app/models/tasks/co_located_admin_action.rb
  spec/controllers/tasks_controller_spec.rb
  spec/models/co_located_admin_action_spec.rb
Labels: In-Progress, Ready-to-Merge

#5974 Fixing unowned tests
  spec/controllers/appeals_controller_spec.rb
  spec/controllers/issues_controller_spec.rb
  spec/controllers/users_controller_spec.rb
  spec/factories/legacy_appeal.rb
  spec/factories/vacols/case.rb
  spec/factories/vacols/case_hearing.rb
  spec/factories/vacols/staff.rb
  spec/feature/dropdown_spec.rb
  spec/feature/login_spec.rb
  spec/feature/out_of_service_spec.rb
  spec/feature/send_feedback_spec.rb
  spec/models/power_of_attorney_spec.rb
  spec/models/user_spec.rb
  spec/requests/appeal_controller_spec.rb
  spec/services/appeals_repository_spec.rb
  spec/services/power_of_attorney_repository_spec.rb
Labels: In-Progress

#5967 Select hearing days by regional office.
  app/controllers/hearings/hearing_day_controller.rb
  app/mappers/hearing_day_mapper.rb
  app/mappers/hearing_mapper.rb
  app/models/hearing_day.rb
  app/models/serializers/hearings/hearing_day_serializer.rb
  app/models/vacols/case_hearing.rb
  app/models/vacols/travel_board_schedule.rb
  app/repositories/hearing_day_repository.rb
  spec/models/hearing_day_spec.rb
  spec/requests/hearing_day_spec.rb
Labels: In-Progress, Ready-to-Merge

#5996 Template Validation for Allocation Days
  app/services/hearing_schedule/validate_ro_spreadsheet.rb
  spec/services/hearing_schedule/validate_ro_spreadsheet_spec.rb
  spec/support/allocationTemplateNotFollowed.xlsx
Labels: In-Progress

#5997 Imports CO non-availability spreadsheet data
  app/models/hearings/co_non_availability.rb
  app/services/hearing_schedule/get_spreadsheet_data.rb
  app/services/hearing_schedule/validate_ro_spreadsheet.rb
  spec/models/hearings/co_non_availability_spec.rb
Labels: In-Progress

#6000 welcome page redux integration
  app/views/hearings/schedule_index.html.erb
  client/app/hearingSchedule/HearingScheduleApp.jsx
  client/app/hearingSchedule/actions.js
  client/app/hearingSchedule/components/LoadingScreen.jsx
  client/app/hearingSchedule/constants.js
  client/app/hearingSchedule/index.jsx
  client/app/hearingSchedule/reducers.js
Labels: In-Progress, Ready-to-Merge

#6010 Changing sequence
  spec/factories/vacols/case_issue.rb
Labels: In-Progress

#6006 Add another rescue to sync intake job
  app/models/ramp_election.rb
Labels: In-Progress, Ready-to-Merge

#5972 Excel Integration | Template validation
  app/services/hearing_schedule/validate_ro_spreadsheet.rb
  spec/services/hearing_schedule/validate_ro_spreadsheet_spec.rb
  spec/support/roTemplateNotFollowed.xlsx
Labels: In-Progress

#5999 Anya/5982 assign round robin
  app/models/tasks/co_located_admin_action.rb
  lib/constants/co_located_teams.rb
  spec/models/co_located_admin_action_spec.rb
Labels: In-Progress, Ready-to-Merge

#6013 Move index to legacy tasks controller
  app/controllers/legacy_tasks_controller.rb
  app/controllers/tasks_controller.rb
  config/routes.rb
  spec/controllers/legacy_tasks_controller_spec.rb
  spec/controllers/tasks_controller_spec.rb
Labels: In-Progress, Ready-to-Merge

#6016 Improve code for disableAddNonRatedIssue
  client/app/intake/components/NonRatedIssues.jsx
Labels: In-Progress, Ready-to-Merge

#6002 Stop loading every appeal for a second time.
  .simplecov
  app/controllers/legacy_tasks_controller.rb
  app/models/legacy_tasks/attorney_legacy_task.rb
  app/models/legacy_tasks/judge_legacy_task.rb
  app/models/legacy_tasks/legacy_task.rb
  app/models/queues/work_queue.rb
  spec/models/legacy_tasks/attorney_legacy_task_spec.rb
  spec/models/legacy_tasks/judge_legacy_task_spec.rb
Labels: In-Progress, Ready-to-Merge

#6018 Make appeal view, claims search, and tasks polymorphic
  app/controllers/reader/claims_folder_searches_controller.rb
  app/controllers/reader/documents_controller.rb
  app/controllers/tasks_controller.rb
  app/models/appeal.rb
  app/models/appeal_view.rb
  app/models/claims_folder_search.rb
  app/models/legacy_appeal.rb
  app/models/task.rb
  db/migrate/20180626151744_make_appeal_view_polymorphic.rb
  db/migrate/20180626151805_make_claim_folder_search_polymorphic.rb
  db/migrate/20180626151823_make_tasks_polymorphic.rb
  db/migrate/20180626152943_add_appeal_view_index_with_appeal_type.rb
  db/schema.rb
Labels: In-Progress

#5971 Fetch claimant information from BGS
  app/mappers/address_mapper.rb
  app/models/appeal.rb
  app/models/claimant.rb
  app/models/serializers/work_queue/appeal_serializer.rb
  app/services/external_api/bgs_service.rb
  db/seeds.rb
  lib/fakes/bgs_service.rb
  scripts/enable_features_dev.rb
  spec/factories/appeal.rb
  spec/factories/claimant.rb
  spec/mappers/address_mapper_spec.rb
  spec/models/claimant_spec.rb
Labels: In-Progress

#6017 Judges | Assign cases | Task reassignment
  client/app/components/AssignWidget.jsx
  client/app/queue/AssignedCasesPage.jsx
  client/app/queue/JudgeAssignTaskListView.jsx
  client/app/queue/QueueActions.js
  client/app/queue/UnassignedCasesPage.jsx
  client/app/queue/constants.js
  client/app/queue/reducers.js
Labels: In-Progress, Ready-to-Merge

#6026 Use CircleCI build badge instead of Travis badge
  README.md
Labels: In-Progress, Ready-to-Merge

#6021 Fix role for the legacy tasks index
  app/controllers/legacy_tasks_controller.rb
Labels: In-Progress, Ready-to-Merge

#6028 AppealView read without appeal type, write with appeal type
  app/controllers/reader/documents_controller.rb
Labels: In-Progress, Ready-to-Merge

#6024 Split syncing ramp intakes into a fan out of jobs
  app/jobs/ramp_election_sync_job.rb
  app/jobs/sync_intake_job.rb
  app/models/ramp_election.rb
  spec/factories/ramp_election.rb
  spec/jobs/ramp_election_sync_job_spec.rb
  spec/jobs/sync_intake_job_spec.rb
  spec/models/ramp_election_spec.rb
Labels: In-Progress, Ready-to-Merge

#6029 End product establishment refactoring
  app/controllers/intakes_controller.rb
  app/models/ama_review.rb
  app/models/concerns/establishes_end_product.rb
  app/models/end_product_establishment.rb
  app/models/higher_level_review.rb
  app/models/ramp_election.rb
  app/models/ramp_review.rb
  app/models/supplemental_claim.rb
Labels: In-Progress

#6036 Fix enable_features_dev
  scripts/enable_features_dev.rb
Labels: In-Progress, Ready-to-Merge

#6035 Turn on VBMS V5 with FeatureToggle
  Gemfile
  Gemfile.lock
  app/services/external_api/vbms_service.rb
Labels: In-Progress, Ready-to-Merge

#6039 Facols test for reassign case to judge method
  spec/repositories/queue_repository_spec.rb
Labels: In-Progress, Ready-to-Merge

#5977 Queue | Connect judge checkout to dispatch FE to BE
  app/models/judge_case_review.rb
  app/models/vacols/decass.rb
  client/COPY.json
  client/app/queue/CaseDetailsView.jsx
  client/app/queue/EvaluateDecisionView.jsx
  client/app/queue/QueueApp.jsx
  client/app/queue/SelectDispositionsView.jsx
  client/app/queue/SubmitDecisionView.jsx
  client/app/queue/components/DecisionViewBase.jsx
  client/app/queue/components/JudgeStartCheckoutFlowDropdown.jsx
  client/app/queue/utils.js
  client/constants/JUDGE_CASE_REVIEW_OPTIONS.json
  lib/constants/decass_work_product_types.rb
  spec/factories/vacols/case.rb
  spec/factories/vacols/decass.rb
  spec/factories/vacols/staff.rb
  spec/feature/queue/queue_spec.rb
Labels: In-Progress, Ready-to-Merge

#6037 issue1055
  app/assets/images/help/caseflow-cancelmodal.jpg
  app/assets/images/help/caseflow-cancelmodal.png
  app/assets/images/help/caseflow-login.jpg
  app/assets/images/help/caseflow-login.png
  app/assets/images/help/caseflow-mismatched.jpg
  app/assets/images/help/caseflow-mismatched.png
  app/assets/images/help/caseflow-mismatched_v2.jpg
  app/assets/images/help/caseflow-mismatched_v2.png
  app/assets/images/help/caseflow-requiredfield.jpg
  app/assets/images/help/caseflow-requiredfield.png
  app/assets/images/help/hearing-access.jpg
  app/assets/images/help/hearing-access.png
  app/assets/images/help/intake-access.jpg
  app/assets/images/help/intake-access.png
  app/assets/images/help/intake-feedback.jpg
  app/assets/images/help/intake-feedback.png
  app/assets/images/help/reader-access.jpg
  app/assets/images/help/reader-access.png
  app/assets/images/help/reader-feedback.jpg
  app/assets/images/help/reader-feedback.png
  app/assets/images/help/reader-separate-tab.jpg
  app/assets/images/help/reader-separate-tab.png
  app/assets/images/help/vacols-certify.jpg
  app/assets/images/help/vacols-certify.png
  app/assets/images/help/vacols-cleardate.jpg
  app/assets/images/help/vacols-cleardate.png
  app/assets/images/help/vacols-processes.jpg
  app/assets/images/help/vacols-processes.png
  app/assets/images/help/vacols-search.jpg
  app/assets/images/help/vacols-search.png
  app/assets/images/help/vacols-travelboard.jpg
  app/assets/images/help/vacols-travelboard.png
  app/assets/images/help/vacols-update.jpg
  app/assets/images/help/vacols-update.png
  app/assets/images/help/vbms-addlabel.jpg
  app/assets/images/help/vbms-addlabel.png
  app/assets/images/help/vbms-documentproperties.jpg
  app/assets/images/help/vbms-documentproperties.png
  client/app/help/components/CertificationHelp.jsx
Labels: In-Progress, Ready-to-Merge

#6001 Dropdown Btn comp
  app/assets/stylesheets/_commons.scss
  client/app/components/DropdownButton.jsx
  client/app/hearingSchedule/components/BuildSchedule.jsx
Labels: In-Progress, Ready-to-Merge

#6030 Add request issues and docket number to Queue
  app/models/appeal.rb
  app/models/serializers/work_queue/appeal_serializer.rb
  client/app/queue/components/IssueListItem.jsx
  client/app/queue/components/LegacyIssueListItem.jsx
  db/seeds.rb
  spec/factories/appeal.rb
  spec/factories/request_issue.rb
  spec/feature/queue/ama_queue_spec.rb
  spec/feature/queue/queue_spec.rb
Labels: In-Progress, Ready-to-Merge

#6051 Queue | Replace/update attorney checkout flow tests
  spec/feature/queue/queue_spec.rb
Labels: In-Progress, Ready-to-Merge

#6012 Imports allocation and RO non-availability data
  app/models/hearings/allocation.rb
  app/models/hearings/co_non_availability.rb
  app/models/hearings/judge_non_availability.rb
  app/models/hearings/ro_non_availability.rb
  app/services/hearing_schedule/get_spreadsheet_data.rb
  app/services/hearing_schedule/validate_ro_spreadsheet.rb
  spec/models/hearings/allocation_spec.rb
  spec/models/hearings/ro_non_availability_spec.rb
  spec/services/hearing_schedule/validate_ro_spreadsheet_spec.rb
  spec/support/allocationTemplateNotFollowed.xlsx
Labels: In-Progress, Ready-to-Merge

#6047 api fix for empty issues
  app/models/appeal_series.rb
  app/models/appeal_series_issues.rb
  app/models/issue.rb
  spec/models/appeal_series_spec.rb
Labels: In-Progress

#6052 issue1055 update refs for other help pages
  client/app/help/components/HearingsHelp.jsx
  client/app/help/components/IntakeHelp.jsx
  client/app/help/components/QueueHelp.jsx
  client/app/help/components/ReaderHelp.jsx
Labels: In-Progress, Ready-to-Merge

#6059 Preprod: Adds attorneys to CASEFLOW1's team
  lib/constants/attorney_judge_teams.rb
Labels: In-Progress, Ready-to-Merge
