Repository department-of-veterans-affairs/caseflow, pull requests merged in 2019-01, with the labels that each got.

#8477 Use named and relative dates rather than hardcoded strings
  spec/feature/intake/appeal_spec.rb
  spec/feature/intake/ramp_election_spec.rb
  spec/models/hearing_day_spec.rb
  spec/rails_helper.rb
  spec/support/date_time_helper.rb
Labels: In-Progress

#8487 fix tests for checking date
  spec/feature/queue/case_details_spec.rb
Labels: In-Progress, Ready-to-Merge

#8486 Caseflow CO hearing days - test fixes
  spec/models/hearing_day_spec.rb
Labels: In-Progress, Ready-to-Merge

#8468 non-comp SC and HLR create DecisionReviewTask on complete!
  app/models/claim_review.rb
  app/models/claim_review_intake.rb
  app/models/request_issue.rb
  spec/models/higher_level_review_intake_spec.rb
  spec/models/supplemental_claim_intake_spec.rb
Labels: In-Progress, Ready-to-Merge

#8470 Remove vacols_id and vacols_sequence_id columns from legacy_issue_optins
  app/models/legacy_issue_optin.rb
  db/migrate/20181228182233_drop_vacols_id_from_legacy_issue_optin.rb
  db/schema.rb
  spec/factories/legacy_issue_optin.rb
  spec/models/legacy_issue_optin_spec.rb
Labels: In-Progress, Ready-to-Merge

#8478 Add completed_at and started_at to task serializer
  app/models/serializers/work_queue/decision_review_task_serializer.rb
  spec/models/serializers/work_queue/decision_review_task_serializer_spec.rb
Labels: In-Progress, Ready-to-Merge

#8463 Edit appeal copy updates
  client/app/intake/components/RemoveIssueModal.jsx
  client/app/intake/pages/addIssues.jsx
  client/app/intake/util/issues.js
  client/app/intakeEdit/components/EditButtons.jsx
  spec/feature/intake/appeal_spec.rb
  spec/feature/intake/edit_spec.rb
Labels: In-Progress, Ready-to-Merge

#8464 Simplify LegacyWorkQueue
  app/controllers/idt/api/v1/appeals_controller.rb
  app/controllers/legacy_tasks_controller.rb
  app/controllers/tasks_controller.rb
  app/models/queues/legacy_work_queue.rb
  spec/feature/queue/case_details_spec.rb
  spec/models/queues/legacy_work_queue_spec.rb
Labels: In-Progress, Ready-to-Merge

#8140 8032 create multiple admin actions
  client/COPY.json
  client/app/queue/AddColocatedTaskView.jsx
  spec/feature/queue/case_assignment_spec.rb
  spec/feature/queue/colocated_task_queue_spec.rb
Labels: In-Progress, Ready-to-Merge

#8430 Assign Veterans | Appeal type tag
  client/app/hearingSchedule/components/AssignHearings.jsx
Labels: In-Progress, Ready-to-Merge

#8432 Do not show decision issues from future in contestable issues
  app/models/appeal.rb
  app/models/claim_review.rb
  spec/feature/intake/higher_level_review_spec.rb
  spec/feature/intake/supplemental_claim_spec.rb
  spec/models/appeal_spec.rb
  spec/models/claim_review_spec.rb
  spec/support/intake_helpers.rb
Labels: In-Progress, Ready-to-Merge

#8442 When there are no relationships and claimant is not Veteran
  client/app/intake/components/SelectClaimant.jsx
  client/app/intake/pages/review.jsx
  spec/feature/intake/appeal_spec.rb
  spec/feature/intake/higher_level_review_spec.rb
  spec/feature/intake/intake_spec.rb
  spec/feature/intake/review_page_spec.rb
  spec/feature/intake/supplemental_claim_spec.rb
  spec/support/intake_helpers.rb
Labels: In-Progress, Ready-to-Merge

#8460 adds the JudgeQualityReviewTask
  app/controllers/tasks_controller.rb
  app/models/task.rb
  app/models/tasks/judge_assign_task.rb
  app/models/tasks/judge_decision_review_task.rb
  app/models/tasks/judge_quality_review_task.rb
  app/models/tasks/judge_review_task.rb
  app/models/tasks/judge_task.rb
  client/COPY.json
  client/app/queue/AssignToAttorneyModalView.jsx
  client/app/queue/JudgeDecisionReviewTaskListView.jsx
  client/app/queue/QueueApp.jsx
  client/app/queue/selectors.js
  db/seeds.rb
  spec/controllers/case_reviews_controller_spec.rb
  spec/controllers/idt/api/appeals_controller_spec.rb
  spec/controllers/tasks_controller_spec.rb
  spec/factories/task.rb
  spec/feature/queue/ama_queue_spec.rb
  spec/feature/queue/case_details_spec.rb
  spec/feature/queue/judge_assignment_spec.rb
  spec/feature/queue/judge_checkout_flow_spec.rb
  spec/feature/queue/task_queue_spec.rb
  spec/models/task_spec.rb
  spec/models/tasks/judge_task_spec.rb
  spec/models/user_spec.rb
Labels: In-Progress, Ready-to-Merge

#8493 Rkreyhsig/fix flakey sniffybara non unique id test
  client/app/queue/components/ActionsDropdown.jsx
Labels: In-Progress

#8476 Change where alert appears on case details page
  client/app/queue/CaseDetailsView.jsx
Labels: In-Progress, Ready-to-Merge

#8447 Hearing Schedule Flaky Tests
  spec/controllers/hearings/schedule_periods_controller_spec.rb
  spec/models/judge_schedule_period_spec.rb
  spec/services/hearing_schedule/assign_judges_to_hearing_days_spec.rb
Labels: In-Progress

#7553 Display special issues for legacy cases
  app/models/legacy_appeal.rb
  app/models/legacy_tasks/attorney_legacy_task.rb
  app/models/legacy_tasks/judge_legacy_task.rb
  app/models/special_issue_list.rb
  client/COPY.json
  client/app/queue/SelectSpecialIssuesView.jsx
  spec/feature/queue/ama_queue_spec.rb
  spec/feature/queue/attorney_checkout_flow_spec.rb
  spec/feature/queue/judge_checkout_flow_spec.rb
Labels: In-Progress, Ready-to-Merge

#8405 Edit request issues by id
  app/models/appeal.rb
  app/models/claim_review.rb
  app/models/request_issue.rb
  client/app/intake/util/issues.js
  spec/factories/request_issue.rb
  spec/feature/intake/edit_spec.rb
  spec/models/request_issues_update_spec.rb
Labels: In-Progress, Ready-to-Merge

#8507 return unless receipt date
  app/models/appeal.rb
  app/models/claim_review.rb
Labels: In-Progress

#8500 Hearing prep sentry error
  client/app/hearings/DailyDocket.jsx
Labels: In-Progress

#8416 Add Hearing Day | Saturday & Sunday
  client/app/hearingSchedule/containers/ListScheduleContainer.jsx
Labels: In-Progress

#8503 Case Details| show Judge when hearing is cancelled
  client/app/queue/CaseHearingsDetail.jsx
  spec/feature/queue/case_details_spec.rb
Labels: In-Progress

#8489 Move automatic task assignment logic from task to organization
  app/models/colocated_task_distributor.rb
  app/models/organization.rb
  app/models/organizations/colocated.rb
  app/models/round_robin_task_distributor.rb
  app/models/task.rb
  app/models/tasks/colocated_task.rb
  lib/caseflow/error.rb
  spec/factories/task.rb
  spec/models/colocated_task_distributor_spec.rb
  spec/models/organization_spec.rb
  spec/models/organizations/colocated_spec.rb
  spec/models/round_robin_task_distributor_spec.rb
  spec/models/task_spec.rb
Labels: In-Progress, Ready-to-Merge

#8514 Complete the decision issue feature test
  app/models/concerns/issue_updater.rb
  spec/feature/queue/attorney_checkout_flow_spec.rb
Labels: In-Progress, Ready-to-Merge

#8517 Create non-comp LOB on demand
  app/controllers/claim_review_controller.rb
  app/models/appeal.rb
  app/models/claim_review.rb
  app/models/claim_review_intake.rb
  app/models/decision_review.rb
  app/models/decision_review_intake.rb
  db/migrate/20190104163907_add_hlrscuuid.rb
  db/schema.rb
  spec/controllers/higher_level_reviews_controller_spec.rb
  spec/feature/non_comp/dispositions_spec.rb
  spec/models/claim_review_spec.rb
Labels: In-Progress

#8520 Add diagnostic code columns to request issues and decision issues
  app/models/serializers/work_queue/appeal_serializer.rb
  client/app/queue/components/ContestedIssues.jsx
  db/migrate/20190104170322_add_diagnostic_code_to_request_issues_and_decision_issues.rb
  db/schema.rb
  spec/factories/request_issue.rb
  spec/feature/queue/attorney_checkout_flow_spec.rb
Labels: In-Progress, Ready-to-Merge

#8523 Add request issues columns with updated names
  app/models/higher_level_review.rb
  app/models/request_issue.rb
  db/migrate/20190104182112_add_contested_rating_issue_columns_to_request_issue.rb
  db/migrate/20190104190600_add_contested_rating_issue_reference_id_index.rb
  db/schema.rb
Labels: In-Progress, Ready-to-Merge

#8509 delete decision issue when request issue is deleted
  app/models/decision_issue.rb
  app/models/request_issue.rb
  app/models/request_issues_update.rb
  spec/models/request_issues_update_spec.rb
Labels: In-Progress, Ready-to-Merge

#8527 adding search and filter to noncomp page
  client/app/nonComp/components/NonCompTabs.jsx
  client/app/nonComp/components/TaskTableColumns.jsx
  client/app/styles/_noncomp.scss
Labels: In-Progress, Ready-to-Merge

#8526 Validation: blank regional office for CO hearings
  app/models/hearing_day.rb
  client/app/hearingSchedule/containers/ListScheduleContainer.jsx
  spec/controllers/hearings_controller_spec.rb
  spec/requests/hearing_day_spec.rb
Labels: In-Progress, Ready-to-Merge

#8481 7344 appeal ineligible lane
  app/models/appeal.rb
  app/models/claim_review.rb
  app/models/contestable_issue.rb
  app/models/decision_issue.rb
  app/models/decision_review.rb
  app/models/rating_issue.rb
  app/models/request_issue.rb
  client/app/intake/actions/addIssues.js
  client/app/intake/components/AddedIssue.jsx
  client/app/intake/util/issues.js
  client/constants/INELIGIBLE_REQUEST_ISSUES.json
  lib/fakes/bgs_service.rb
  spec/factories/appeal.rb
  spec/factories/request_issue.rb
  spec/feature/intake/appeal_spec.rb
  spec/feature/intake/edit_spec.rb
  spec/feature/intake/higher_level_review_spec.rb
  spec/feature/intake/nonrating_request_issue_modal_spec.rb
  spec/feature/intake/supplemental_claim_spec.rb
  spec/models/claim_review_spec.rb
  spec/models/contestable_issue_spec.rb
  spec/models/decision_review_spec.rb
  spec/models/rating_issue_spec.rb
  spec/models/rating_spec.rb
  spec/models/request_issue_spec.rb
Labels: In-Progress

#8491 AMA hearings table
  app/controllers/hearings/worksheets_controller.rb
  app/controllers/hearings_controller.rb
  app/models/hearing.rb
  app/models/legacy_hearing.rb
  client/app/hearings/DailyDocket.jsx
  client/app/hearings/actions/Dockets.js
  client/app/hearings/components/WorksheetHeaderVeteranSelection.jsx
  config/routes.rb
  db/migrate/20181224183228_create_ama_hearings.rb
  db/schema.rb
  spec/controllers/hearings/worksheets_controller_spec.rb
  spec/controllers/hearings_controller_spec.rb
  spec/factories/hearing.rb
  spec/feature/hearings_spec.rb
Labels: In-Progress, Ready-to-Merge

#8480 Simplify logic in TaskSnapshot component #8467 (PR)
  client/COPY.json
  client/app/queue/TaskSnapshot.jsx
  spec/feature/queue/case_details_spec.rb
Labels: In-Progress

#8536 Make test less fragile
  spec/models/round_robin_task_distributor_spec.rb
Labels: In-Progress, Ready-to-Merge

#8512 Do not show rating issues from the future
  app/models/decision_review.rb
  db/schema.rb
  spec/feature/intake/higher_level_review_spec.rb
  spec/feature/intake/supplemental_claim_spec.rb
  spec/models/decision_review_spec.rb
Labels: In-Progress, Ready-to-Merge

#8538 Add test for task instructions shape change
  app/models/task.rb
  spec/models/task_spec.rb
Labels: In-Progress, Ready-to-Merge

#8528 Fixing TaskSnapshot console errors
  client/app/queue/TaskSnapshot.jsx
Labels: In-Progress

#8429 [WIP] Comment deep links
  client/app/components/CopyTextButton.jsx
  client/app/reader/AnnotationLayer/AnnotationActions.js
  client/app/reader/AnnotationLayer/AnnotationLayerReducer.js
  client/app/reader/AnnotationLayer/actionTypes.js
  client/app/reader/Comment.jsx
  client/app/reader/PdfViewer.jsx
  lib/fakes/vbms_service.rb
  spec/feature/reader/reader_spec.rb
Labels: In-Progress, Ready-to-Merge

#8529 Read from contested_request_issue columns
  app/models/contestable_issue.rb
  app/models/decision_review.rb
  app/models/end_product_establishment.rb
  app/models/higher_level_review.rb
  app/models/rating_issue.rb
  app/models/request_issue.rb
  lib/fakes/bgs_service.rb
  spec/factories/request_issue.rb
  spec/feature/intake/appeal_spec.rb
  spec/feature/intake/edit_spec.rb
  spec/feature/intake/higher_level_review_spec.rb
  spec/feature/intake/supplemental_claim_spec.rb
  spec/models/appeal_intake_spec.rb
  spec/models/claim_review_spec.rb
  spec/models/decision_issue_spec.rb
  spec/models/end_product_establishment_spec.rb
  spec/models/higher_level_review_intake_spec.rb
  spec/models/higher_level_review_spec.rb
  spec/models/rating_issue_spec.rb
  spec/models/request_issue_spec.rb
  spec/models/request_issues_update_spec.rb
  spec/models/supplemental_claim_intake_spec.rb
  spec/support/intake_helpers.rb
Labels: In-Progress, Ready-to-Merge

#8428 Add veteran ahl job
  app/controllers/api/v1/jobs_controller.rb
  app/jobs/fetch_hearing_locations_for_veterans_job.rb
  app/models/hearings/available_hearing_locations.rb
  app/models/legacy_appeal.rb
  app/models/veteran.rb
  app/services/external_api/facilities_locator_service.rb
  app/services/external_api/va_dot_gov_service.rb
  app/services/external_api/vets360_service.rb
  app/services/prometheus_service.rb
  config/environments/test.rb
  config/initializers/facilities_locator.rb
  config/initializers/va_dot_gov.rb
  config/initializers/vets360.rb
  db/migrate/20181224142346_add_available_hearing_locations_table.rb
  db/schema.rb
  lib/caseflow/error.rb
  lib/fakes/facilities_locator_service.rb
  lib/fakes/va_dot_gov_service.rb
  lib/fakes/vets360_service.rb
  spec/factories/available_hearing_locations.rb
  spec/jobs/fetch_hearing_locations_for_veterans_job_spec.rb
  spec/services/external_api/facilities_locator_service_spec.rb
  spec/services/external_api/vets360_service_spec.rb
Labels: In-Progress, Ready-to-Merge

#8539 Completed tab gets different column than In Progress tab
  app/controllers/decision_reviews_controller.rb
  app/models/task.rb
  client/app/nonComp/components/NonCompTabs.jsx
  client/app/nonComp/util/index.js
  spec/feature/non_comp/reviews_spec.rb
  spec/feature/queue/colocated_checkout_flow_spec.rb
Labels: In-Progress, Ready-to-Merge

#8546 Add Pension board grant EP codes
  app/models/board_grant_effectuation.rb
  app/models/end_product.rb
  spec/models/board_grant_effectuation_spec.rb
Labels: In-Progress, Ready-to-Merge

#8556 Skipping flaky test
  spec/requests/hearing_day_spec.rb
Labels: In-Progress, Ready-to-Merge

#8551 Optimize hearing page
  .circleci/config.yml
  Gemfile
  Gemfile.lock
  app/controllers/appeals_controller.rb
  app/controllers/tasks_controller.rb
  app/services/appeal_repository.rb
  client/app/hearingSchedule/containers/AssignHearingsContainer.jsx
  config/environments/development.rb
  config/environments/test.rb
  config/routes.rb
  spec/controllers/appeals_controller_spec.rb
  spec/controllers/tasks_controller_spec.rb
Labels: In-Progress, Ready-to-Merge

#8558 Use VACOLS task eager loading functionality for organizations
  app/controllers/organizations/tasks_controller.rb
  app/controllers/tasks_controller.rb
  app/services/appeal_repository.rb
Labels: In-Progress, Ready-to-Merge

#8135 Implement edit confirmation page for HLRs and SCs
  app/controllers/appeals_controller.rb
  app/controllers/claim_review_controller.rb
  app/models/request_issues_update.rb
  client/app/intake/components/IneligibleIssuesList.jsx
  client/app/intake/pages/decisionReviewEditCompleted.jsx
  client/app/intake/pages/decisionReviewIntakeCompleted.jsx
  client/app/intakeEdit/IntakeEditFrame.jsx
  client/app/intakeEdit/actions/edit.js
  client/app/intakeEdit/reducers/index.js
  spec/factories/appeal.rb
  spec/factories/intake.rb
  spec/feature/intake/edit_spec.rb
  spec/feature/intake/intake_edit_confirmation_spec.rb
  spec/support/intake_helpers.rb
Labels: In-Progress, Ready-to-Merge

#8540 Anya/8358 do not hard code benefit type
  app/models/serializers/idt/v1/appeal_details_serializer.rb
  app/models/serializers/work_queue/appeal_serializer.rb
  db/migrate/20190107161740_not_null_constraint_benefit_type.rb
  db/schema.rb
  spec/feature/intake/edit_spec.rb
  spec/models/end_product_establishment_spec.rb
Labels: In-Progress, Ready-to-Merge

#8549 Add description columns and begin writing to them
  app/models/higher_level_review.rb
  app/models/request_issue.rb
  db/migrate/20190107210543_add_request_issue_description_columns.rb
  db/schema.rb
  spec/feature/intake/appeal_spec.rb
  spec/feature/intake/higher_level_review_spec.rb
  spec/feature/intake/supplemental_claim_spec.rb
  spec/feature/queue/ama_queue_spec.rb
  spec/feature/queue/case_details_spec.rb
  spec/models/appeal_intake_spec.rb
  spec/models/claim_review_spec.rb
  spec/models/decision_issue_spec.rb
  spec/models/end_product_establishment_spec.rb
  spec/models/higher_level_review_intake_spec.rb
  spec/models/request_issue_spec.rb
  spec/models/request_issues_update_spec.rb
  spec/models/supplemental_claim_intake_spec.rb
  spec/support/intake_helpers.rb
Labels: In-Progress

#8559 Fix test data
  db/seeds.rb
Labels: In-Progress, Ready-to-Merge

#8560 Fix timezone flakey test
  spec/feature/non_comp/reviews_spec.rb
Labels: In-Progress, Ready-to-Merge

#8562 Case Details -> Hearing Worksheet Link
  app/models/serializers/work_queue/legacy_appeal_serializer.rb
  client/app/queue/CaseHearingsDetail.jsx
  client/app/queue/types/models.js
  client/app/queue/utils.js
  client/app/reader/utils.js
  spec/feature/queue/case_details_spec.rb
Labels: In-Progress, Ready-to-Merge

#8566 add missing benefit_type in seeds
  lib/fakes/bgs_service.rb
Labels: In-Progress, Ready-to-Merge

#8222 Create mail task modal routes to team based on task type
  app/controllers/tasks_controller.rb
  app/models/appeal.rb
  app/models/organizations/litigation_support.rb
  app/models/task.rb
  app/models/tasks/generic_task.rb
  app/models/tasks/mail_task.rb
  app/models/tasks/root_task.rb
  client/COPY.json
  client/app/queue/CreateMailTaskDialog.jsx
  client/app/queue/QueueApp.jsx
  client/app/queue/components/ActionsDropdown.jsx
  lib/caseflow/error.rb
  spec/factories/appeal.rb
  spec/feature/queue/task_queue_spec.rb
  spec/models/appeal_spec.rb
  spec/models/tasks/mail_task_spec.rb
Labels: In-Progress, Ready-to-Merge

#8569 Edit / Remove Hearing Day Link Correction
  client/app/components/RenderFunctions.jsx
  client/app/hearingSchedule/components/DailyDocket.jsx
Labels: In-Progress

#8574 add profile_date when generating ratings for confirmation tests
  spec/feature/intake/intake_edit_confirmation_spec.rb
Labels: In-Progress, Ready-to-Merge

#8568 Serializer updates
  client/app/hearingSchedule/components/AssignHearings.jsx
Labels: In-Progress, Ready-to-Merge

#8479 Show "+ Add a new task" button in active tasks title bar #8216 (PR)
  client/COPY.json
  client/app/queue/TaskSnapshot.jsx
  client/app/queue/components/AddNewTaskButton.jsx
  client/app/queue/selectors.js
  spec/feature/queue/task_queue_spec.rb
Labels: In-Progress, Ready-to-Merge

#8588 Browser date math is outside our control, make regex more robust
  spec/feature/non_comp/reviews_spec.rb
Labels: Ready-to-Merge

#8561 Anya/8521 stay disposition
  app/mappers/issue_mapper.rb
  app/models/legacy_appeal.rb
  client/app/queue/components/SelectIssueDispositionDropdown.jsx
  client/app/queue/utils.js
  client/constants/UNDECIDED_VACOLS_DISPOSITIONS_BY_ID.json
  spec/feature/queue/attorney_checkout_flow_spec.rb
Labels: In-Progress, Ready-to-Merge

#8579 Read from new rating issue description columns
  app/models/board_grant_effectuation.rb
  app/models/claim_review.rb
  app/models/contestable_issue.rb
  app/models/decision_issue.rb
  app/models/higher_level_review.rb
  app/models/request_issue.rb
  client/app/intake/util/issues.js
  spec/factories/request_issue.rb
  spec/feature/intake/appeal_spec.rb
  spec/feature/intake/edit_spec.rb
  spec/feature/intake/higher_level_review_spec.rb
  spec/feature/intake/supplemental_claim_spec.rb
  spec/feature/queue/ama_queue_spec.rb
  spec/feature/queue/attorney_checkout_flow_spec.rb
  spec/feature/queue/case_details_spec.rb
  spec/models/appeal_intake_spec.rb
  spec/models/claim_review_spec.rb
  spec/models/contestable_issue_spec.rb
  spec/models/decision_document_spec.rb
  spec/models/decision_issue_spec.rb
  spec/models/end_product_establishment_spec.rb
  spec/models/higher_level_review_intake_spec.rb
  spec/models/higher_level_review_spec.rb
  spec/models/request_issue_spec.rb
  spec/models/request_issues_update_spec.rb
  spec/models/supplemental_claim_intake_spec.rb
  spec/support/intake_helpers.rb
Labels: Ready-to-Merge

#8589 Add explicit defaultSortIdx prop to TaskTable
  client/app/nonComp/components/NonCompTabs.jsx
  client/app/queue/components/TaskTable.jsx
Labels: Ready-to-Merge

#8548 Create BoardGrantEffectuation tasks for noncompensation issues
  app/models/board_grant_effectuation.rb
  app/models/serializers/work_queue/board_grant_effectuation_task_serializer.rb
  app/models/serializers/work_queue/decision_review_task_serializer.rb
  app/models/tasks/board_grant_effectuation_task.rb
  db/schema.rb
  spec/factories/task.rb
  spec/feature/non_comp/reviews_spec.rb
  spec/models/board_grant_effectuation_spec.rb
  spec/models/tasks/board_grant_effectuation_task_spec.rb
Labels: In-Progress, Ready-to-Merge

#8596 Backwards compatible migration
  app/models/hearing_day.rb
Labels: In-Progress, Ready-to-Merge

#8571 save noncomp task decision
  app/controllers/decision_reviews_controller.rb
  app/models/decision_issue.rb
  app/models/decision_review.rb
  app/models/request_issue.rb
  app/models/tasks/decision_review_task.rb
  app/views/decision_reviews/index.html.erb
  app/views/decision_reviews/show.html.erb
  client/app/components/TabWindow.jsx
  client/app/nonComp/actions/task.js
  client/app/nonComp/components/Alerts.jsx
  client/app/nonComp/components/NonCompTabs.jsx
  client/app/nonComp/constants.js
  client/app/nonComp/pages/DispositionPage.jsx
  client/app/nonComp/pages/ReviewPage.jsx
  client/app/nonComp/reducers/index.js
  client/app/nonComp/util/index.js
  config/routes.rb
  spec/controllers/decision_reviews_controller_spec.rb
  spec/feature/non_comp/dispositions_spec.rb
Labels: In-Progress

#8599 Refactor edit spec
  spec/feature/intake/appeal/edit_spec.rb
  spec/feature/intake/appeal_spec.rb
  spec/feature/intake/edit_spec.rb
  spec/feature/intake/higher_level_review/edit_spec.rb
  spec/feature/intake/higher_level_review_spec.rb
  spec/feature/intake/supplemental_claim/edit_spec.rb
  spec/feature/intake/supplemental_claim_spec.rb
  spec/support/intake_helpers.rb
Labels: In-Progress, Ready-to-Merge

#8552 Make special issues per contention instead of per claim for VACOLS opt in
  Gemfile
  Gemfile.lock
  app/models/decision_review.rb
  app/models/end_product_establishment.rb
  app/models/higher_level_review.rb
  app/models/ramp_refiling.rb
  app/models/request_issue.rb
  app/services/external_api/vbms_service.rb
  lib/fakes/vbms_service.rb
  spec/feature/intake/higher_level_review/edit_spec.rb
  spec/feature/intake/higher_level_review_spec.rb
  spec/feature/intake/ramp_refiling_spec.rb
  spec/feature/intake/supplemental_claim/edit_spec.rb
  spec/feature/intake/supplemental_claim_spec.rb
  spec/feature/non_comp/reviews_spec.rb
  spec/models/appeal_spec.rb
  spec/models/claim_review_spec.rb
  spec/models/decision_document_spec.rb
  spec/models/end_product_establishment_spec.rb
  spec/models/higher_level_review_intake_spec.rb
  spec/models/higher_level_review_spec.rb
  spec/models/ramp_refiling_spec.rb
  spec/models/request_issue_spec.rb
  spec/models/request_issues_update_spec.rb
  spec/models/supplemental_claim_intake_spec.rb
  spec/models/supplemental_claim_spec.rb
Labels: In-Progress, Ready-to-Merge

#8578 Distribute 4% of all AMA cases to QR
  app/controllers/case_reviews_controller.rb
  app/models/quality_review_case_selector.rb
  spec/controllers/case_reviews_controller_spec.rb
  spec/feature/queue/attorney_checkout_flow_spec.rb
  spec/feature/queue/judge_checkout_flow_spec.rb
Labels: In-Progress, Ready-to-Merge

#8544 hearing.date / hearing_day.hearing_date -> scheduled_for
  app/controllers/hearings/hearing_day_controller.rb
  app/controllers/hearings_controller.rb
  app/controllers/regional_offices_controller.rb
  app/mappers/hearing_day_mapper.rb
  app/mappers/hearing_mapper.rb
  app/models/appeal_event.rb
  app/models/appeal_series_alerts.rb
  app/models/hearing.rb
  app/models/hearing_day.rb
  app/models/hearing_docket.rb
  app/models/hearings/master_record.rb
  app/models/judge.rb
  app/models/legacy_hearing.rb
  app/models/ro_schedule_period.rb
  app/models/serializers/hearings/hearing_day_serializer.rb
  app/models/serializers/work_queue/legacy_appeal_serializer.rb
  app/models/user.rb
  app/models/vacols/case_hearing.rb
  app/repositories/hearing_day_repository.rb
  app/repositories/hearing_repository.rb
  app/services/hearing_schedule/assign_judges_to_hearing_days.rb
  client/app/components/HearingDayDropdown.jsx
  client/app/hearingSchedule/components/AssignHearings.jsx
  client/app/hearingSchedule/components/DailyDocket.jsx
  client/app/hearingSchedule/components/ListSchedule.jsx
  client/app/hearingSchedule/components/ReviewAssignments.jsx
  client/app/hearingSchedule/containers/DailyDocketContainer.jsx
  client/app/hearingSchedule/containers/ListScheduleContainer.jsx
  client/app/hearings/DailyDocket.jsx
  client/app/hearings/Dockets.jsx
  client/app/hearings/components/WorksheetHeader.jsx
  client/app/hearings/components/WorksheetHeaderVeteranSelection.jsx
  db/migrate/20190107184216_rename_field_in_hearing_day.rb
  db/schema.rb
  lib/generators/legacy_hearing.rb
  spec/controllers/hearings_controller_spec.rb
  spec/factories/hearing_day.rb
  spec/factories/legacy_hearing.rb
  spec/feature/hearing_schedule/build_schedule_spec.rb
  spec/feature/queue/case_details_spec.rb
  spec/models/appeal_event_spec.rb
  spec/models/hearing_day_spec.rb
  spec/models/hearing_docket_spec.rb
  spec/models/judge_schedule_period_spec.rb
  spec/models/judge_spec.rb
  spec/models/legacy_hearing_spec.rb
  spec/models/master_record_spec.rb
  spec/models/schedule_period_spec.rb
  spec/repositories/hearing_repository_spec.rb
  spec/requests/hearing_day_spec.rb
Labels: In-Progress

#8593 Remove ColocatedTask assigned by attorney constraint
  app/models/tasks/colocated_task.rb
  spec/controllers/tasks_controller_spec.rb
  spec/models/tasks/colocated_task_spec.rb
Labels: In-Progress, Ready-to-Merge

#8098 Add Higher Level Reviews and Supplemental Claims to search view
  app/controllers/appeals_controller.rb
  app/models/claim_review.rb
  app/models/end_product_establishment.rb
  client/COPY.json
  client/app/queue/CaseList/CaseListActions.js
  client/app/queue/CaseList/actionTypes.js
  client/app/queue/CaseListTable.jsx
  client/app/queue/CaseListView.jsx
  client/app/queue/OtherReviewsTable.jsx
  client/app/queue/QueueActions.js
  client/app/queue/constants.js
  client/app/queue/reducers.js
  client/app/queue/selectors.js
  client/app/queue/types/models.js
  client/app/queue/types/state.js
  client/app/queue/utils.js
  client/constants/CLAIM_REVIEW_TEXT.json
  client/constants/CLAIM_REVIEW_TYPES.json
  client/constants/EP_STATUSES.json
  db/seeds.rb
  spec/controllers/appeals_controller_spec.rb
  spec/feature/queue/search_spec.rb
  spec/models/claim_review_spec.rb
Labels: In-Progress, Ready-to-Merge

#8613 Fix for sentry #3305
  app/models/appeal_series.rb
Labels: In-Progress, Ready-to-Merge

#8575 Allow editing document ID
  app/controllers/case_reviews_controller.rb
  app/models/serializers/work_queue/appeal_serializer.rb
  app/models/serializers/work_queue/legacy_appeal_serializer.rb
  app/services/form_response.rb
  app/workflows/update_attorney_case_review.rb
  client/COPY.json
  client/app/queue/CaseTitleDetails.jsx
  client/app/queue/utils.js
  config/routes.rb
  spec/feature/queue/case_details/update_document_id_spec.rb
  spec/feature/queue/case_details_spec.rb
  spec/workflows/update_attorney_case_review_spec.rb
Labels: In-Progress

#8624 fix incorrect HLR / SCs table test in search_spec.rb
  spec/feature/queue/search_spec.rb
Labels: In-Progress, Ready-to-Merge

#8637 text change, default column sort
  client/COPY.json
  client/app/nonComp/components/NonCompTabs.jsx
  spec/feature/non_comp/reviews_spec.rb
Labels: In-Progress, Ready-to-Merge

#8333 Creates distribution, evidence window, and informal hearing presentation tasks for direct review and evidence submission appeals
  app/models/tasks/distribution_task.rb
  app/models/tasks/evidence_submission_window_task.rb
  app/models/tasks/root_task.rb
  spec/models/tasks/evidence_submission_window_task_spec.rb
  spec/models/tasks/root_task_spec.rb
Labels: In-Progress, Ready-to-Merge

#8550 Add hearing_regional_office column to Veteran and AHL job
  app/jobs/fetch_hearing_locations_for_veterans_job.rb
  app/services/external_api/va_dot_gov_service.rb
  db/migrate/20190110162001_add_regional_office_to_veteran.rb
  db/schema.rb
  lib/caseflow/error.rb
  lib/fakes/va_dot_gov_service.rb
  spec/jobs/fetch_hearing_locations_for_veterans_job_spec.rb
Labels: In-Progress, Ready-to-Merge

#8564 Update document_count to use Caseflow Documents table
  app/controllers/appeals_controller.rb
  app/models/appeal.rb
  app/models/legacy_appeal.rb
  spec/controllers/appeals_controller_spec.rb
  spec/feature/queue/ama_queue_spec.rb
  spec/models/legacy_appeal_spec.rb
Labels: In-Progress, Ready-to-Merge

#8601 assign ColocatedTasks w/auto child task creation
  app/controllers/tasks_controller.rb
  app/models/colocated_task_distributor.rb
  app/models/organization.rb
  app/models/organizations/colocated.rb
  app/models/round_robin_task_distributor.rb
  app/models/task.rb
  app/models/tasks/colocated_task.rb
  spec/models/colocated_task_distributor_spec.rb
  spec/models/organization_spec.rb
  spec/models/organizations/colocated_spec.rb
  spec/models/task_spec.rb
  spec/models/tasks/colocated_task_spec.rb
Labels: In-Progress, Ready-to-Merge

#8639 hearing_type -> request_type
  app/controllers/hearings/hearing_day_controller.rb
  app/controllers/regional_offices_controller.rb
  app/mappers/hearing_day_mapper.rb
  app/mappers/hearing_mapper.rb
  app/models/hearing.rb
  app/models/hearing_day.rb
  app/models/ro_schedule_period.rb
  app/models/serializers/hearings/hearing_day_serializer.rb
  app/models/vacols/case_hearing.rb
  app/repositories/hearing_day_repository.rb
  app/repositories/hearing_repository.rb
  app/services/appeal_repository.rb
  app/services/hearing_schedule/assign_judges_to_hearing_days.rb
  client/app/hearingSchedule/actions.js
  client/app/hearingSchedule/components/DailyDocket.jsx
  client/app/hearingSchedule/components/HearingDayAddModal.jsx
  client/app/hearingSchedule/components/ListSchedule.jsx
  client/app/hearingSchedule/components/ReviewAssignments.jsx
  client/app/hearingSchedule/constants.js
  client/app/hearingSchedule/containers/DailyDocketContainer.jsx
  client/app/hearingSchedule/containers/ListScheduleContainer.jsx
  client/app/hearingSchedule/reducers.js
  db/migrate/20190111000717_rename_hearing_day_field.rb
  db/schema.rb
  spec/controllers/hearings_controller_spec.rb
  spec/factories/hearing_day.rb
  spec/feature/hearing_schedule/build_schedule_spec.rb
  spec/feature/hearing_schedule/schedule_veteran_spec.rb
  spec/helpers/master_record_helper_spec.rb
  spec/models/hearing_day_spec.rb
  spec/models/judge_schedule_period_spec.rb
  spec/models/schedule_period_spec.rb
  spec/repositories/hearing_day_repository_spec.rb
  spec/requests/hearing_day_spec.rb
  spec/services/hearing_schedule/assign_judges_to_hearing_days_spec.rb
Labels: In-Progress

#8638 add board grant effectuation task page
  app/controllers/decision_reviews_controller.rb
  app/models/decision_issue.rb
  app/models/tasks/board_grant_effectuation_task.rb
  app/models/tasks/decision_review_task.rb
  client/app/nonComp/actions/task.js
  client/app/nonComp/components/Alerts.jsx
  client/app/nonComp/components/BoardGrant.jsx
  client/app/nonComp/components/Disposition.jsx
  client/app/nonComp/components/NonCompTabs.jsx
  client/app/nonComp/index.jsx
  client/app/nonComp/pages/ReviewPage.jsx
  client/app/nonComp/pages/TaskPage.jsx
  client/app/nonComp/reducers/index.js
  client/app/nonComp/util/index.js
  spec/controllers/decision_reviews_controller_spec.rb
  spec/feature/non_comp/board_grants_spec.rb
  spec/feature/non_comp/dispositions_spec.rb
Labels: In-Progress, Ready-to-Merge

#8609 Hearing Worksheet | Case Details Link
  client/app/hearings/components/WorksheetHeaderVeteranSelection.jsx
Labels: In-Progress

#8670 Fix decision issue descriptions
  app/models/request_issue.rb
  spec/models/request_issue_spec.rb
Labels: In-Progress, Ready-to-Merge

#8602 Create Appeal remand supplemental claims
  app/models/appeal.rb
  app/models/claim_review.rb
  app/models/claim_review_intake.rb
  app/models/decision_document.rb
  app/models/decision_issue.rb
  app/models/end_product.rb
  app/models/end_product_establishment.rb
  app/models/higher_level_review.rb
  app/models/request_issue.rb
  app/models/supplemental_claim.rb
  client/app/intake/reducers/higherLevelReview.js
  client/app/intake/reducers/supplementalClaim.js
  db/migrate/20190109234311_add_decision_review_remanded_to_supplemental_claims.rb
  db/schema.rb
  spec/factories/decision_issue.rb
  spec/feature/intake/higher_level_review/edit_spec.rb
  spec/feature/intake/higher_level_review_spec.rb
  spec/feature/intake/supplemental_claim/edit_spec.rb
  spec/feature/intake/supplemental_claim_spec.rb
  spec/models/appeal_spec.rb
  spec/models/claim_review_spec.rb
  spec/models/decision_document_spec.rb
  spec/models/decision_issue_spec.rb
  spec/models/end_product_establishment_spec.rb
  spec/models/higher_level_review_spec.rb
  spec/models/request_issue_spec.rb
  spec/models/supplemental_claim_spec.rb
Labels: In-Progress, Ready-to-Merge

#8669 Do not require address for deceased Veteran
  app/models/veteran.rb
  spec/models/intake_spec.rb
Labels: In-Progress, Ready-to-Merge

#8671 fix type filter styling
  client/app/components/ListItemPickerCheckbox.jsx
  client/app/components/Table.jsx
  client/app/nonComp/components/NonCompTabs.jsx
  client/app/nonComp/components/TaskTableColumns.jsx
Labels: In-Progress, Ready-to-Merge

#8577 Benefit type per Appeal issue
  app/models/appeal.rb
  app/models/board_grant_effectuation.rb
  app/models/claim_review.rb
  app/models/claim_review_intake.rb
  app/models/concerns/has_business_line.rb
  app/models/decision_issue.rb
  app/models/decision_review.rb
  app/models/decision_review_intake.rb
  app/models/rating_issue.rb
  app/models/request_issue.rb
  client/app/intake/actions/addIssues.js
  client/app/intake/components/BenefitType.jsx
  client/app/intake/components/LegacyOptInModal.jsx
  client/app/intake/components/NonratingRequestIssueModal.jsx
  client/app/intake/components/UntimelyExemptionModal.jsx
  client/app/intake/constants.js
  client/app/intake/pages/higherLevelReview/finish.jsx
  client/app/intake/pages/supplementalClaim/finish.jsx
  client/app/intake/reducers/appeal.js
  client/app/intake/reducers/higherLevelReview.js
  client/app/intake/reducers/supplementalClaim.js
  client/app/intake/util/index.js
  client/app/intake/util/issues.js
  client/app/styles/_intake.scss
  spec/factories/appeal.rb
  spec/feature/intake/appeal/edit_spec.rb
  spec/feature/intake/appeal_spec.rb
  spec/feature/intake/nonrating_request_issue_modal_spec.rb
  spec/feature/intake/supplemental_claim_spec.rb
  spec/models/appeal_intake_spec.rb
  spec/models/claim_review_spec.rb
  spec/models/decision_issue_spec.rb
  spec/models/decision_review_spec.rb
  spec/models/request_issue_spec.rb
  spec/support/intake_helpers.rb
Labels: In-Progress, sierra

#8606 Add diagnostic code to decision issue modal
  app/controllers/case_reviews_controller.rb
  app/models/concerns/issue_updater.rb
  app/models/decision_issue.rb
  client/COPY.json
  client/app/queue/SelectDispositionsView.jsx
  client/app/queue/types/models.js
  spec/controllers/case_reviews_controller_spec.rb
  spec/factories/decision_issue.rb
  spec/factories/request_issue.rb
  spec/feature/queue/attorney_checkout_flow_spec.rb
  spec/models/attorney_case_review_spec.rb
Labels: In-Progress, Ready-to-Merge

#8683 Changing = to IN in CaseHearing query
  app/models/vacols/case_hearing.rb
Labels: In-Progress, Ready-to-Merge

#8663 Do no throw issue repository errors to sentry
  app/controllers/issues_controller.rb
  app/mappers/issue_mapper.rb
  app/repositories/issue_repository.rb
  lib/caseflow/error.rb
  spec/controllers/issues_controller_spec.rb
Labels: In-Progress, Ready-to-Merge

#8687 Fixing nil return
  app/models/hearing_day.rb
  spec/models/hearing_day_spec.rb
Labels: In-Progress, Ready-to-Merge

#8699 Make notes a required field when placing ColocatedTask on hold
  client/COPY.json
  client/app/queue/ColocatedPlaceHoldView.jsx
  spec/feature/queue/colocated_task_queue_spec.rb
Labels: In-Progress, Ready-to-Merge

#8702 update list
  lib/constants/ramp_judges.rb
Labels: In-Progress, Ready-to-Merge

#8565 Authorize child task creation with available task actions
  app/models/legacy_tasks/attorney_legacy_task.rb
  app/models/legacy_tasks/judge_legacy_task.rb
  app/models/task.rb
  app/models/tasks/attorney_task.rb
  app/models/tasks/colocated_task.rb
  app/models/tasks/generic_task.rb
  app/models/tasks/judge_quality_review_task.rb
  app/models/tasks/mail_task.rb
  client/COPY.json
  client/app/queue/QueueApp.jsx
  client/constants/TASK_ACTIONS.json
  spec/feature/hearing_schedule/schedule_veteran_spec.rb
  spec/feature/queue/ama_queue_spec.rb
  spec/feature/queue/case_assignment_spec.rb
  spec/feature/queue/colocated_checkout_flow_spec.rb
  spec/feature/queue/colocated_task_queue_spec.rb
  spec/feature/queue/judge_checkout_flow_spec.rb
  spec/feature/queue/task_queue_spec.rb
  spec/models/task_spec.rb
  spec/models/tasks/judge_task_spec.rb
Labels: In-Progress, Ready-to-Merge

#8696 Fix text area in disposition view
  client/app/nonComp/components/Disposition.jsx
Labels: In-Progress, Ready-to-Merge

#8686 Only show case once in the attorney task list view
  app/models/queues/attorney_queue.rb
  spec/feature/queue/case_assignment_spec.rb
  spec/models/queues/attorney_queue_spec.rb
Labels: In-Progress, Ready-to-Merge

#8698 adds ready scope
  app/models/appeal.rb
  app/models/tasks/root_task.rb
  spec/models/appeal_spec.rb
Labels: In-Progress, Ready-to-Merge

#8709 use ep 34 on hlrs
  app/models/higher_level_review.rb
Labels: In-Progress, Ready-to-Merge

#8703 Fix request issues seeds
  db/seeds.rb
  spec/factories/request_issue.rb
Labels: In-Progress, Ready-to-Merge

#8712 Remove trailing pipe from days waiting column if no due date for task
  client/app/queue/components/TaskTable.jsx
Labels: In-Progress, Ready-to-Merge

#8673 AMA Upcoming Hearing Days & Daily Docket
  app/controllers/hearings_controller.rb
  app/mappers/hearing_mapper.rb
  app/models/appeal.rb
  app/models/appeal_series.rb
  app/models/appeal_series_alerts.rb
  app/models/concerns/appeal_concern.rb
  app/models/concerns/hearing_concern.rb
  app/models/hearing.rb
  app/models/hearing_day.rb
  app/models/hearing_docket.rb
  app/models/hearings/master_record.rb
  app/models/judge.rb
  app/models/legacy_hearing.rb
  app/models/serializers/work_queue/appeal_serializer.rb
  app/models/serializers/work_queue/legacy_appeal_serializer.rb
  app/models/vacols/case_hearing.rb
  app/repositories/hearing_repository.rb
  client/app/hearingSchedule/components/AssignHearings.jsx
  client/app/hearingSchedule/components/DailyDocket.jsx
  client/app/hearings/DailyDocket.jsx
  client/app/hearings/Dockets.jsx
  client/app/hearings/HearingWorksheet.jsx
  client/app/hearings/actions/Dockets.js
  client/app/hearings/analytics.js
  client/app/hearings/components/WorksheetHeader.jsx
  client/app/hearings/components/WorksheetHeaderVeteranSelection.jsx
  client/app/hearings/constants/constants.js
  client/app/hearings/reducers/index.js
  client/app/hearings/util/index.js
  client/app/queue/CaseHearingsDetail.jsx
  db/migrate/20190113170514_add_time_to_hearings.rb
  db/schema.rb
  lib/generators/legacy_hearing.rb
  spec/controllers/hearings_controller_spec.rb
  spec/factories/hearing.rb
  spec/feature/queue/case_details_spec.rb
  spec/mappers/hearing_mapper_spec.rb
  spec/models/appeal_series_alerts_spec.rb
  spec/models/hearing_docket_spec.rb
  spec/models/legacy_hearing_spec.rb
  spec/models/master_record_spec.rb
  spec/repositories/hearing_repository_spec.rb
Labels: In-Progress

#8717 Improve VLJ support staff test data
  db/seeds.rb
  spec/factories/task.rb
Labels: In-Progress, Ready-to-Merge

#8707 Hearing Schedule Flaky Tests
  spec/models/judge_schedule_period_spec.rb
  spec/services/hearing_schedule/generate_hearing_days_schedule_spec.rb
Labels: In-Progress, Ready-to-Merge

#8730 Use strong_migrations gem
  Gemfile
  Gemfile.lock
  Rakefile
  config/initializers/strong_migrations.rb
  db/migrate/20190110220936_make_hearing_views_polymorphic.rb
  db/schema.rb
Labels: In-Progress, Ready-to-Merge

#8735 Do not send to sentry case already assigned errors
  app/controllers/legacy_tasks_controller.rb
  app/repositories/queue_repository.rb
  lib/caseflow/error.rb
  spec/controllers/legacy_tasks_controller_spec.rb
  spec/models/judge_case_assignment_to_attorney_spec.rb
  spec/repositories/queue_repository_spec.rb
Labels: In-Progress, Ready-to-Merge

#8719 Enable sending ColocatedTasks for AMA appeals to Translation team
  app/models/task.rb
  app/models/tasks/colocated_task.rb
  client/COPY.json
  client/app/queue/AssignToView.jsx
  client/app/queue/QueueApp.jsx
  client/constants/TASK_ACTIONS.json
  db/seeds.rb
  spec/feature/queue/colocated_task_queue_spec.rb
Labels: In-Progress, Ready-to-Merge

#8737 Moved server error display to Add Hearing modal.
  client/app/hearingSchedule/components/HearingDayAddModal.jsx
  client/app/hearingSchedule/containers/ListScheduleContainer.jsx
Labels: In-Progress

#8745 bump connect_vbms (no logic change, just test updates)
  Gemfile
  Gemfile.lock
Labels: In-Progress, Ready-to-Merge

#8704 Set receipt date of DTA Supplemental Claims to approximate decision date
  app/models/decision_issue.rb
  app/models/higher_level_review.rb
  spec/models/appeal_spec.rb
  spec/models/decision_document_spec.rb
  spec/models/decision_issue_spec.rb
  spec/models/end_product_establishment_spec.rb
  spec/models/higher_level_review_spec.rb
  spec/models/request_issue_spec.rb
  spec/requests/hearing_day_spec.rb
Labels: In-Progress, Ready-to-Merge

#8744 Create hearing task at case details load
  app/controllers/tasks_controller.rb
  app/models/tasks/schedule_hearing_task.rb
  client/app/queue/components/AssignHearingModal.jsx
  spec/controllers/tasks_controller_spec.rb
  spec/models/tasks/schedule_hearing_task_spec.rb
  spec/requests/hearing_day_spec.rb
Labels: In-Progress

#8721 Allow judges to create admin actions
  app/models/legacy_tasks/judge_legacy_task.rb
  app/models/tasks/judge_assign_task.rb
  app/models/tasks/judge_decision_review_task.rb
  app/models/tasks/judge_quality_review_task.rb
  app/models/tasks/judge_task.rb
  spec/feature/queue/attorney_checkout_flow_spec.rb
  spec/feature/queue/judge_checkout_flow_spec.rb
  spec/feature/queue/task_queue_spec.rb
  spec/models/tasks/judge_task_spec.rb
Labels: In-Progress

#8736 Redirect to tasks table after non-comp intake success
  app/controllers/intakes_controller.rb
  app/models/organizations/business_line.rb
  app/models/serializers/work_queue/decision_review_task_serializer.rb
  app/views/decision_reviews/index.html.erb
  client/app/intake/pages/decisionReviewIntakeCompleted.jsx
  client/app/intake/reducers/higherLevelReview.js
  client/app/intake/reducers/supplementalClaim.js
  client/app/nonComp/components/Alerts.jsx
  client/app/nonComp/index.jsx
  client/app/nonComp/pages/TaskPage.jsx
  spec/controllers/intakes_controller_spec.rb
  spec/feature/intake/higher_level_review_spec.rb
  spec/feature/intake/nonrating_request_issue_modal_spec.rb
  spec/feature/intake/supplemental_claim_spec.rb
  spec/feature/non_comp/board_grants_spec.rb
  spec/feature/non_comp/reviews_spec.rb
Labels: In-Progress, Ready-to-Merge

#8758 Broken link on the daily docket
  client/app/hearingSchedule/components/AssignHearings.jsx
  client/app/hearingSchedule/components/DailyDocket.jsx
  client/app/hearings/DailyDocket.jsx
Labels: In-Progress, Ready-to-Merge

#8705 Limit contention text to 255 characters
  app/models/board_grant_effectuation.rb
  app/models/contention.rb
  app/models/decision_issue.rb
  app/models/ramp_issue.rb
  app/models/ramp_refiling.rb
  app/models/request_issue.rb
  spec/models/decision_document_spec.rb
  spec/models/end_product_establishment_spec.rb
  spec/models/ramp_refiling_spec.rb
Labels: In-Progress, Ready-to-Merge

#8769 Fix VACOLS Opt-in special issue
  app/models/request_issue.rb
  spec/models/end_product_establishment_spec.rb
Labels: In-Progress, Ready-to-Merge

#8772 Do not expect the order to be the same in the response
  spec/controllers/tasks_controller_spec.rb
Labels: In-Progress

#8766 VACOLS issues should also ignore the AMA timeliness reqs
  app/models/request_issue.rb
  client/app/intake/components/AddedIssue.jsx
  spec/feature/intake/appeal_spec.rb
  spec/feature/intake/higher_level_review_spec.rb
  spec/feature/intake/supplemental_claim_spec.rb
  spec/models/request_issue_spec.rb
Labels: In-Progress, Ready-to-Merge

#8697 Disabling tasks when they are completed
  app/models/serializers/work_queue/decision_review_task_serializer.rb
  app/models/tasks/board_grant_effectuation_task.rb
  app/models/tasks/decision_review_task.rb
  client/app/components/TextareaField.jsx
  client/app/nonComp/components/BoardGrant.jsx
  client/app/nonComp/components/Disposition.jsx
  client/app/styles/_noncomp.scss
  spec/controllers/decision_reviews_controller_spec.rb
  spec/feature/non_comp/board_grants_spec.rb
  spec/feature/non_comp/dispositions_spec.rb
  spec/models/serializers/work_queue/decision_review_task_serializer_spec.rb
Labels: In-Progress, Ready-to-Merge

#8714 AHL Job Updates
  app/jobs/fetch_hearing_locations_for_veterans_job.rb
  app/services/external_api/va_dot_gov_service.rb
  app/services/prometheus_service.rb
  db/migrate/20190117054954_add_classificationto_available_hearing_locations.rb
  db/schema.rb
  lib/caseflow/error.rb
  spec/jobs/fetch_hearing_locations_for_veterans_job_spec.rb
Labels: In-Progress

#8741 Daily docket feature tests
  app/mappers/hearing_mapper.rb
  client/app/hearingSchedule/components/DailyDocket.jsx
  spec/factories/hearing.rb
  spec/factories/vacols/case_hearing.rb
  spec/feature/hearing_schedule/daily_docket_spec.rb
  spec/feature/hearings_spec.rb
  spec/models/tasks/schedule_hearing_task_spec.rb
Labels: In-Progress, Ready-to-Merge

#8753 tracks distribution task ready time, catches timer task job errors
  app/jobs/task_timer_job.rb
  app/models/tasks/distribution_task.rb
  app/models/tasks/informal_hearing_presentation_task.rb
  app/models/tasks/root_task.rb
  spec/jobs/task_timer_job_spec.rb
  spec/models/tasks/distribution_task_spec.rb
Labels: In-Progress

#8743 do not error out on backfilled ratings
  app/jobs/decision_issue_sync_job.rb
  app/models/decision_review.rb
  app/models/decision_review_intake.rb
  app/models/rating.rb
  spec/feature/intake/appeal_spec.rb
  spec/feature/intake/higher_level_review_spec.rb
  spec/jobs/decision_rating_issue_sync_job_spec.rb
  spec/support/intake_helpers.rb
Labels: In-Progress, Ready-to-Merge

#8770 Copy for completed intake with no EP created
  client/app/intake/pages/decisionReviewEditCompleted.jsx
  client/app/intake/pages/decisionReviewIntakeCompleted.jsx
  spec/feature/intake/confirmation_page_spec.rb
  spec/feature/intake/intake_edit_confirmation_spec.rb
  spec/support/intake_helpers.rb
Labels: In-Progress, Ready-to-Merge

#8779 Add/Edit and Delete Hearing Day Feature Tests
  client/app/hearingSchedule/components/HearingDayAddModal.jsx
  spec/feature/hearing_schedule/add_hearing_day_spec.rb
  spec/feature/hearing_schedule/edit_hearing_day_spec.rb
  spec/feature/hearing_schedule/remove_hearing_day_spec.rb
  spec/feature/hearing_schedule/schedule_veteran_spec.rb
Labels: In-Progress

#8792 Prevent saving video hearings to Caseflow with hearing dates prior to 4/1/2019
  client/app/hearingSchedule/components/HearingDayAddModal.jsx
  client/app/hearingSchedule/containers/ListScheduleContainer.jsx
  spec/feature/hearing_schedule/add_hearing_day_spec.rb
Labels: In-Progress

#8760 Common Components for Hearing Dropdowns that Require Data from AJAX Calls
  client/app/hearingSchedule/components/DataDropdowns/HearingCoordinator.jsx
  client/app/hearingSchedule/components/DataDropdowns/HearingDate.jsx
  client/app/hearingSchedule/components/DataDropdowns/HearingRoom.jsx
  client/app/hearingSchedule/components/DataDropdowns/Judge.jsx
  client/app/hearingSchedule/components/DataDropdowns/RegionalOffice.jsx
  client/app/hearingSchedule/components/DataDropdowns/actions.js
  client/app/hearingSchedule/components/DataDropdowns/constants.js
  client/app/hearingSchedule/components/DataDropdowns/index.js
  client/app/hearingSchedule/components/DataDropdowns/reducers.js
  client/app/hearingSchedule/reducers.js
Labels: In-Progress, Ready-to-Merge

#8767 Claimant copy changes
  client/COPY.json
  client/app/intake/components/SelectClaimant.jsx
  client/app/intake/pages/search.jsx
  spec/feature/intake/higher_level_review_spec.rb
  spec/feature/intake/review_page_spec.rb
Labels: In-Progress, Ready-to-Merge

#8794 Set autocomplete to off for Document ID field
  client/app/components/TextField.jsx
  client/app/queue/SubmitDecisionView.jsx
Labels: In-Progress

#8813 Use user_id to find a judge instead of css id
  app/controllers/users_controller.rb
  client/app/queue/CaseDetailsLoadingScreen.jsx
  client/app/queue/QueueApp.jsx
  client/app/queue/QueueLoadingScreen.jsx
  client/app/queue/types/models.js
  spec/controllers/users_controller_spec.rb
Labels: In-Progress, Ready-to-Merge

#8814 Use legacyAppeal instead of appealSeries as the type in API responses
  app/models/serializers/v2/appeal_serializer.rb
  spec/feature/api/v2/appeals_spec.rb
Labels: Appeal Status, In-Progress, Ready-to-Merge, appeals-status-api

#8816 Stop autocomplete suggestions for searchable dropdowns
  client/app/components/SearchableDropdown.jsx
Labels: In-Progress, Ready-to-Merge

#8718 Special issues copy changes and new component
  client/COPY.json
  client/app/components/CheckboxGroup.jsx
  client/app/constants/SpecialIssueFilters.js
  client/app/constants/SpecialIssues.js
  client/app/queue/SelectSpecialIssuesView.jsx
  client/app/styles/_main.scss
Labels: In-Progress, Ready-to-Merge

#8787 changes to update spacing between lines
  client/app/queue/components/ContestedIssues.jsx
Labels: In-Progress, Ready-to-Merge

#8818 remove decision date column from HLR / SC table
  client/app/queue/OtherReviewsTable.jsx
Labels: In-Progress, Ready-to-Merge

#8750 Create hearing task at intake
  app/controllers/hearings/hearing_day_controller.rb
  app/controllers/regional_offices_controller.rb
  app/controllers/tasks_controller.rb
  app/models/hearing_day.rb
  app/models/tasks/root_task.rb
  app/models/tasks/schedule_hearing_task.rb
  app/models/vacols/case_hearing.rb
  app/repositories/hearing_day_repository.rb
  app/repositories/hearing_repository.rb
  app/services/hearing_schedule/assign_judges_to_hearing_days.rb
  client/app/hearingSchedule/components/AssignHearings.jsx
  client/app/hearingSchedule/components/DailyDocket.jsx
  client/app/queue/components/AssignHearingModal.jsx
  db/seeds.rb
  scripts/enable_features_dev.rb
  spec/factories/appeal.rb
  spec/feature/hearing_schedule/build_schedule_spec.rb
  spec/models/hearing_day_spec.rb
  spec/models/tasks/root_task_spec.rb
  spec/models/tasks/schedule_hearing_task_spec.rb
  spec/repositories/hearing_day_repository_spec.rb
  spec/requests/hearing_day_spec.rb
Labels: In-Progress, Ready-to-Merge

#8801 Replacing HearingCoordinator and Judges Dropdowns
  app/controllers/regional_offices_controller.rb
  app/models/regional_office.rb
  client/app/components/DataDropdowns/HearingCoordinator.jsx
  client/app/components/DataDropdowns/HearingDate.jsx
  client/app/components/DataDropdowns/HearingRoom.jsx
  client/app/components/DataDropdowns/Judge.jsx
  client/app/components/DataDropdowns/RegionalOffice.jsx
  client/app/components/DataDropdowns/constants.js
  client/app/components/DataDropdowns/index.js
  client/app/components/RoSelectorDropdown.jsx
  client/app/components/common/actionTypes.js
  client/app/components/common/actions.js
  client/app/components/common/reducers.js
  client/app/hearingSchedule/actions.js
  client/app/hearingSchedule/components/AssignHearings.jsx
  client/app/hearingSchedule/components/DataDropdowns/actions.js
  client/app/hearingSchedule/components/DataDropdowns/constants.js
  client/app/hearingSchedule/components/DataDropdowns/reducers.js
  client/app/hearingSchedule/components/HearingDayAddModal.jsx
  client/app/hearingSchedule/components/HearingDayEditModal.jsx
  client/app/hearingSchedule/containers/AssignHearingsContainer.jsx
  client/app/hearingSchedule/containers/DailyDocketContainer.jsx
  client/app/hearingSchedule/containers/ListScheduleContainer.jsx
  client/app/hearingSchedule/reducers.js
  client/app/queue/components/AssignHearingModal.jsx
  spec/controllers/regional_offices_controller_spec.rb
Labels: In-Progress, Ready-to-Merge

#8812 issue.eligibleForSocOptIn is undefined for RequestIssues on edit
  client/app/intake/components/AddedIssue.jsx
  spec/feature/intake/higher_level_review/edit_spec.rb
Labels: In-Progress, Ready-to-Merge

#8817 default EP modifier to empty string if it is null
  app/models/end_product_establishment.rb
  spec/models/end_product_establishment_spec.rb
Labels: In-Progress, Ready-to-Merge

#8841 Add statutory opt-in disposition to appeal status (closes #8808)
  app/models/appeal_event.rb
  app/models/appeal_series.rb
  spec/models/appeal_event_spec.rb
  spec/models/appeal_series_spec.rb
Labels: In-Progress

#8826 Restore Removed Hearing Day Confirmation Message
  client/app/hearingSchedule/containers/DailyDocketContainer.jsx
Labels: In-Progress

#8790 Add asyncable jobs admin page
  app/controllers/asyncable_jobs_controller.rb
  app/models/claim_review_intake.rb
  app/models/concerns/asyncable.rb
  app/models/concerns/run_asyncable.rb
  app/models/decision_review_intake.rb
  app/models/intake.rb
  app/services/asyncable_jobs.rb
  app/views/asyncable_jobs/index.html.erb
  client/app/asyncableJobs/index.jsx
  client/app/asyncableJobs/pages/JobsPage.jsx
  client/app/asyncableJobs/reducers/index.js
  client/app/index.js
  config/routes.rb
  spec/controllers/asyncable_jobs_controller_spec.rb
  spec/feature/asyncable_jobs/asyncable_jobs_index_spec.rb
  spec/services/asyncable_jobs_spec.rb
Labels: In-Progress, Ready-to-Merge

#8854 Mark a few more transient bgs sync errors
  app/models/end_product_establishment.rb
Labels: In-Progress, Ready-to-Merge

#8786 do not report err on SUBMIT_REVIEW_FAIL
  client/app/intake/pages/review.jsx
Labels: In-Progress, Ready-to-Merge

#8827 assign `BvaDispatchTask`s with automatic child creation
  app/controllers/case_reviews_controller.rb
  app/models/bva_dispatch_task_distributor.rb
  app/models/organizations/bva_dispatch.rb
  app/models/tasks/bva_dispatch_task.rb
  app/models/tasks/quality_review_task.rb
  spec/controllers/idt/api/appeals_controller_spec.rb
  spec/models/organizations/bva_dispatch_spec.rb
  spec/models/tasks/bva_dispatch_task_spec.rb
Labels: In-Progress, Ready-to-Merge

#8829 add app tagging for debugging
  app/controllers/dispatch/tasks_controller.rb
  app/controllers/dispatch/user_quotas_controller.rb
  app/jobs/application_job.rb
  app/jobs/decision_issue_sync_job.rb
  app/jobs/decision_review_process_job.rb
  app/jobs/fetch_documents_for_reader_user_job.rb
  app/jobs/retrieve_documents_for_reader_job.rb
  app/jobs/sync_reviews_job.rb
  app/jobs/task_timer_job.rb
Labels: In-Progress, Ready-to-Merge

#8856 separate out claimant w fiduciary error to keep sentry clean
  lib/caseflow/error.rb
Labels: In-Progress, Ready-to-Merge

#8864 Ignore nil submitted at when sorting asyncable jobs
  app/models/concerns/asyncable.rb
  app/services/asyncable_jobs.rb
  spec/services/asyncable_jobs_spec.rb
Labels: In-Progress

#8319 change title of HearingBadge
  client/app/queue/components/HearingBadge.jsx
Labels: In-Progress, Ready-to-Merge

#8848 AMA hearing worksheet
  app/controllers/hearings/worksheets_controller.rb
  app/models/hearing.rb
  app/models/hearing_issue_note.rb
  app/models/request_issue.rb
  client/app/components/ContentSection.jsx
  client/app/hearings/HearingWorksheet.jsx
  client/app/hearings/actions/Issue.js
  client/app/hearings/components/HearingWorksheetAmaIssues.jsx
  client/app/hearings/components/HearingWorksheetPreImpressions.jsx
  client/app/hearings/components/WorksheetHeader.jsx
  client/app/hearings/constants/constants.js
  client/app/hearings/reducers/index.js
  client/app/queue/components/ContestedIssues.jsx
  db/migrate/20190118155859_create_hearing_issue_notes.rb
  db/schema.rb
  spec/feature/hearings_spec.rb
Labels: In-Progress, Ready-to-Merge

#8860 Dates on download link CSV
  client/app/hearingSchedule/components/ListSchedule.jsx
Labels: In-Progress, Ready-to-Merge

#8871 Add message for zero pending jobs
  app/models/concerns/asyncable.rb
  client/app/asyncableJobs/pages/JobsPage.jsx
  spec/feature/asyncable_jobs/asyncable_jobs_index_spec.rb
Labels: In-Progress, Ready-to-Merge
