Repository department-of-veterans-affairs/caseflow, pull requests merged in 2019-10, with the labels that each got.

#12252 Async job notes
  app/controllers/asyncable_jobs_controller.rb
  app/models/board_grant_effectuation.rb
  app/models/decision_document.rb
  app/models/decision_review.rb
  app/models/job_note.rb
  app/models/request_issue.rb
  app/models/request_issues_update.rb
  app/views/asyncable_jobs/show.html.erb
  client/app/asyncableJobs/components/JobNotes.jsx
  client/app/asyncableJobs/pages/JobPage.jsx
  client/app/styles/_jobs.scss
  client/package.json
  client/yarn.lock
  config/routes.rb
  db/migrate/20190925205112_create_job_notes.rb
  db/schema.rb
  spec/feature/asyncable_jobs/asyncable_jobs_index_spec.rb
Labels: Ready-to-Merge

#12235 Example SQL for timed hold task
  app/models/application_record.rb
  app/sql/timed-hold-task.sql
  spec/sql/timed_hold_task_sql_spec.rb
Labels: Ready-to-Merge

#12263 Filter out nil hearing locations
  app/controllers/api/v2/hearings_controller.rb
  app/models/hearing_location.rb
  spec/controllers/api/v2/hearings_controller_spec.rb
  spec/factories/hearing.rb
  spec/factories/hearing_location.rb
  spec/factories/legacy_hearing.rb
Labels: Ready-to-Merge

#12258 Return queue config to the front end for user queues
  app/controllers/tasks_controller.rb
  app/models/organization.rb
  app/models/queue_config.rb
  app/models/user.rb
  spec/controllers/tasks_controller_spec.rb
  spec/models/queue_config_spec.rb
Labels: Ready-to-Merge

#12259 Async job notes (#12252)
  app/controllers/asyncable_jobs_controller.rb
  app/models/board_grant_effectuation.rb
  app/models/decision_document.rb
  app/models/decision_review.rb
  app/models/job_note.rb
  app/models/request_issue.rb
  app/models/request_issues_update.rb
  app/views/asyncable_jobs/show.html.erb
  client/app/asyncableJobs/components/JobNotes.jsx
  client/app/asyncableJobs/pages/JobPage.jsx
  client/app/styles/_jobs.scss
  client/package.json
  client/yarn.lock
  config/routes.rb
  db/migrate/20190925205112_create_job_notes.rb
  db/schema.rb
  spec/feature/asyncable_jobs/asyncable_jobs_index_spec.rb
Labels: Ready-to-Merge

#12261 do not save changesets for documents and annotations
  app/models/annotation.rb
  app/models/document.rb
  app/models/documents_tag.rb
  spec/models/document_spec.rb
Labels: Ready-to-Merge

#12222 Add issue templates for epic and story
  .github/ISSUE_TEMPLATE/epic.md
  .github/ISSUE_TEMPLATE/issue-report.md
  .github/ISSUE_TEMPLATE/story.md
  .gitignore
Labels: Ready-to-Merge

#12257 check assets:precompile during CI
  .circleci/config.yml
  .reek.yml
  Makefile.example
  app/services/appeal_task_history.rb
  spec/models/request_issues_update_spec.rb
  spec/services/appeal_task_history_spec.rb
Labels: Ready-to-Merge

#12282 Fix definition for remanded on request issue
  app/models/request_issue.rb
  spec/factories/higher_level_review.rb
  spec/feature/intake/supplemental_claim/edit_spec.rb
  spec/models/claim_review_spec.rb
  spec/workflows/end_product_code_selector_spec.rb
Labels: Ready-to-Merge

#12272 Remove action column from tasks table.
  app/models/task.rb
  db/migrate/20191001224339_remove_action_from_tasks.rb
  db/schema.rb
Labels: Ready-to-Merge

#12273 Update connect vbms
  Gemfile
  Gemfile.lock
Labels: Ready-to-Merge

#12164 Bump Redux & Related
  app/views/dispatch/establish_claims/assigned_existing_ep.html.erb
  app/views/dispatch/establish_claims/canceled.html.erb
  app/views/dispatch/establish_claims/canceled_tasks.html.erb
  app/views/dispatch/establish_claims/complete.html.erb
  app/views/dispatch/establish_claims/show.html.erb
  app/views/dispatch/establish_claims/unprepared_tasks.html.erb
  client/app/asyncableJobs/index.jsx
  client/app/certification/Certification.jsx
  client/app/components/ReduxBase.jsx
  client/app/containers/EstablishClaimPage/EstablishClaim.jsx
  client/app/containers/EstablishClaimPage/EstablishClaimContainer.jsx
  client/app/containers/EstablishClaimPage/EstablishClaimNote.jsx
  client/app/containers/EstablishClaimPage/index.jsx
  client/app/establishClaim/components/CancelModal.jsx
  client/app/establishClaim/constants/index.js
  client/app/establishClaim/reducers/establishClaimForm.js
  client/app/establishClaimAdmin/index.jsx
  client/app/hearings/components/HearingDayAddModal.jsx
  client/app/hearings/index.jsx
  client/app/inbox/index.jsx
  client/app/index.js
  client/app/intake/index.js
  client/app/intakeEdit/index.js
  client/app/intakeManager/index.jsx
  client/app/manageEstablishClaim/index.jsx
  client/app/nonComp/index.jsx
  client/app/queue/SelectRemandReasonsView.jsx
  client/app/queue/components/IssueRemandReasonsOptions.jsx
  client/app/queue/index.jsx
  client/app/reader/index.jsx
  client/app/util/ReduxUtil.js
  client/package.json
  client/test/karma/containers/EstablishClaim-test.js
  client/test/karma/containers/EstablishClaimContainer-test.js
  client/test/karma/establishClaim/WrappingComponent.jsx
  client/test/node/containers/EstablishClaim-test.js
  client/yarn.lock
Labels: Ready-to-Merge

#11847 BGS Address Finder
  app/services/external_api/bgs_address_finder.rb
  app/services/external_api/bgs_service.rb
  spec/services/external_api/bgs_service_spec.rb
Labels: Ready-to-Merge

#12227 Fix formatting of full address
  app/models/address.rb
  spec/models/address_spec.rb
Labels: Ready-to-Merge

#12228 DTA corrections - prevent invalid new issues from being added
  app/models/claim_review.rb
  app/workflows/contestable_issue_generator.rb
  client/app/intake/components/AddIssuesModal.jsx
  client/app/intake/pages/addIssues.jsx
  spec/feature/intake/end_product_correction_spec.rb
  spec/feature/intake/supplemental_claim/edit_spec.rb
  spec/models/decision_review_spec.rb
  spec/workflows/contestable_issue_generator_spec.rb
Labels: Ready-to-Merge

#12300 Filter Nil Dispositions for hearings
  app/controllers/api/v2/hearings_controller.rb
  spec/controllers/api/v2/hearings_controller_spec.rb
Labels: Ready-to-Merge

#12294 Remove feedback
  README.md
  config/environments/test.rb
Labels: Ready-to-Merge

#12306 Fix warning appearing in attorney checkout feature tests
  spec/feature/queue/attorney_checkout_flow_spec.rb
Labels: Ready-to-Merge

#12317 Fix edge case where dispatched case has incomplete tasks
  app/sql/bva-decision-progress.sql
  spec/sql/bva_decision_progress_spec.rb
Labels: Ready-to-Merge

#12298 Monthly metrics report
  app/controllers/api/v1/jobs_controller.rb
  app/jobs/monthly_metrics_report_job.rb
  app/services/claim_review_async_stats_reporter.rb
  spec/jobs/monthly_metrics_report_job_spec.rb
  spec/services/claim_review_async_stats_reporter_spec.rb
Labels: Ready-to-Merge

#12305 Append structure attribute names to appeal label
  app/models/concerns/prints_task_tree.rb
  spec/models/appeal_spec.rb
  spec/models/legacy_appeal_spec.rb
Labels: Ready-to-Merge

#12310 Remove unused env vars
  config/environments/demo.rb
  config/environments/development.rb
  config/environments/ssh_forwarding.rb
  config/environments/test.rb
  config/secrets.yml
Labels: Ready-to-Merge

#10833 Create product-lead-responsibilities.md
  docs/product-lead-responsibilities.md
Labels: Ready-to-Merge

#12278 Lighthouse - add descriptions to OpenAPI spec that should appear on the developer portal
  app/controllers/api/docs/v3/decision_reviews.yaml
Labels: Ready-to-Merge, lighthouse

#12277 BVA & VBA users withdraw appeal functionality
  app/models/user.rb
  app/views/appeals/edit.html.erb
  app/views/higher_level_reviews/edit.html.erb
  app/views/supplemental_claims/edit.html.erb
  client/app/intake/components/IssueList.jsx
  client/app/intake/pages/addIssues.jsx
  client/app/intake/reducers/featureToggles.js
  client/app/intakeEdit/reducers/index.js
  client/test/karma/intake/testData.js
  spec/feature/intake/appeal/edit_spec.rb
  spec/feature/intake/end_product_correction_spec.rb
  spec/feature/intake/higher_level_review/edit_spec.rb
  spec/feature/intake/intake_edit_confirmation_spec.rb
  spec/feature/intake/supplemental_claim/edit_spec.rb
  spec/feature/queue/delete_request_issues_spec.rb
  spec/models/user_spec.rb
  spec/support/intake_helpers.rb
Labels: Ready-to-Merge

#12324 Fix address initialization bug
  app/models/appeal.rb
  app/models/claimant.rb
Labels: Ready-to-Merge

#12326 Make checker jobs slack output more readable
  app/services/asyncable_jobs_reporter.rb
  app/services/open_hearing_tasks_without_active_descendants_checker.rb
  app/services/reviews_with_duplicate_ep_error_checker.rb
  spec/services/open_hearing_tasks_without_active_descendants_checker_spec.rb
Labels: Ready-to-Merge

#12322 Add format documentation in rspec
  .circleci/config.yml
  .rspec
  spec/feature/dispatch/establish_claim_spec.rb
Labels: Ready-to-Merge

#12335 Filter out VACOLS hearings not associated with a Case
  app/models/vacols/case_hearing.rb
  spec/repositories/hearing_repository_spec.rb
Labels: Ready-to-Merge

#12325 Fix edge case with double counting timed hold tasks
  app/sql/bva-decision-progress.sql
  spec/sql/bva_decision_progress_spec.rb
Labels: Ready-to-Merge

#11928 Use column names from columns rather than individual constants
  app/models/queue_tabs/assigned_tasks_tab.rb
  app/models/queue_tabs/completed_tasks_tab.rb
  app/models/queue_tabs/on_hold_tasks_tab.rb
  app/models/queue_tabs/tracking_tasks_tab.rb
  app/models/queue_tabs/unassigned_tasks_tab.rb
  app/models/serializers/work_queue/task_column_serializer.rb
  app/models/task_filter.rb
  app/models/task_sorter.rb
  client/app/queue/components/TaskTable.jsx
  client/app/queue/components/TaskTableColumns.jsx
  client/constants/QUEUE_CONFIG.json
  spec/models/queue_config_spec.rb
  spec/models/queue_filter_parameter_spec.rb
  spec/models/queue_tabs/assigned_tasks_tab_spec.rb
  spec/models/queue_tabs/completed_tasks_tab_spec.rb
  spec/models/queue_tabs/on_hold_tasks_tab_spec.rb
  spec/models/queue_tabs/unassigned_tasks_tab_spec.rb
  spec/models/task_filter_spec.rb
  spec/models/task_pager_spec.rb
  spec/models/task_sorter_spec.rb
Labels: Ready-to-Merge

#12342 Update connect VBMS
  Gemfile
  Gemfile.lock
Labels: Ready-to-Merge

#12354 Add output to enable features script
  scripts/duplicate_decass_deleter.rb
  scripts/enable_features_dev.rb
Labels: Ready-to-Merge

#12360 Route sentry errors to queue
  app/jobs/update_appellant_representation_job.rb
Labels: Ready-to-Merge

#12358 Cached user table
  app/controllers/api/v1/jobs_controller.rb
  app/jobs/caseflow_job.rb
  app/jobs/nightly_syncs_job.rb
  app/jobs/update_cached_appeals_attributes_job.rb
  app/models/cached_user.rb
  db/migrate/20191010164748_created_cached_user_attributes.rb
  db/schema.rb
  spec/jobs/nightly_syncs_job_spec.rb
  spec/models/cached_user_spec.rb
Labels: Ready-to-Merge

#12240 Accessibility Fix for Dropdown Menus
  client/app/components/DropdownButton.jsx
  client/app/hearings/containers/ListScheduleContainer.jsx
Labels: Ready-to-Merge

#12206 Judge assign task view performance
  app/controllers/users_controller.rb
  app/serializers/attorney_serializer.rb
  client/app/queue/AssignedCasesPage.jsx
  client/app/queue/JudgeAssignTaskListView.jsx
  client/app/queue/QueueActions.js
  client/app/queue/constants.js
  client/app/queue/reducers.js
  spec/controllers/users_controller_spec.rb
Labels: Ready-to-Merge

#12309 Remove redirect if editing DTA claim
  client/app/intake/components/AddedIssue.jsx
  client/app/intake/components/IssueList.jsx
  client/app/intake/constants.js
  client/app/intake/pages/addIssues.jsx
  client/app/intake/util/issues.js
  client/app/intakeEdit/IntakeEditFrame.jsx
  spec/feature/intake/end_product_correction_spec.rb
  spec/feature/intake/supplemental_claim/edit_spec.rb
Labels: Ready-to-Merge

#12364 Skip nil sdomainid staff records
  app/models/cached_user.rb
  spec/models/cached_user_spec.rb
Labels: Ready-to-Merge

#12340 Updated README DB env setup to show need for AWS
  README.md
Labels: Ready-to-Merge

#12341 set label to 'Search'
  client/app/components/SearchBar.jsx
Labels: Ready-to-Merge

#12366 instead of sleep, cache geomatch API responses
  app/jobs/fetch_hearing_locations_for_veterans_job.rb
  app/services/external_api/va_dot_gov_service.rb
  db/seeds.rb
  spec/feature/hearings/add_hearing_day_spec.rb
Labels: Ready-to-Merge

#12369 Optimize query for appeals with zero tasks
  app/queries/appeals_with_no_tasks_or_all_tasks_on_hold_query.rb
Labels: Ready-to-Merge

#12353 Appeals API - ignore station ID checks for User.api_user
  app/models/validators/intake_start_validator.rb
  spec/models/validators/intake_start_validator_spec.rb
Labels: lighthouse

#12376 Improve rating decision dates
  .reek.yml
  app/models/rating_decision.rb
  spec/models/rating_decision_spec.rb
Labels: Ready-to-Merge

#12379 Geomatch cache for 2 hours, not 24
  app/services/external_api/va_dot_gov_service.rb
Labels: Ready-to-Merge

#12385 Tableau SQL data sources
  Gemfile
  Gemfile.lock
  app/sql/ama-cases.sql
  app/sql/ama-tasks.sql
  scripts/pretty-sql.rb
  spec/sql/ama_cases_sql_spec.rb
  spec/sql/ama_tasks_sql_spec.rb
  spec/support/shared_examples/ama_sql.rb
  spec/support/sql_helpers.rb
Labels: Ready-to-Merge

#12372 Update address bar to reflect deep link when navigating queue
  client/app/queue/QueueTable.jsx
  spec/feature/queue/task_queue_spec.rb
Labels: Ready-to-Merge

#12393 add nl2br fn to StringUtil
  client/app/util/StringUtil.js
  client/test/karma/util/StringUtil-test.js
Labels: Ready-to-Merge

#12172 Update JudgeAssignTask documentation
  app/models/tasks/judge_assign_task.rb
Labels: Ready-to-Merge

#12391 Fix decision_status__sort_ logic
  app/models/legacy_appeal.rb
  app/models/veteran.rb
  app/sql/ama-cases.sql
  app/sql/ama-tasks.sql
  app/workflows/case_search_results_for_veteran_file_number.rb
  spec/controllers/intakes_controller_spec.rb
  spec/feature/hearings/list_schedule/hearing_prep_spec.rb
  spec/models/task_filter_spec.rb
  spec/sql/ama_cases_sql_spec.rb
  spec/sql/ama_tasks_sql_spec.rb
  spec/sql/bva_decision_progress_spec.rb
  spec/support/shared_examples/ama_sql.rb
Labels: Ready-to-Merge

#12361 Avoid Wrapping Long Labels under Input in CheckboxGroup
  client/app/components/CheckboxGroup.jsx
  client/app/styles/_commons.scss
  spec/feature/queue/judge_checkout_flow_spec.rb
Labels: Ready-to-Merge

#12313 Lit Support | Pulac-Cerullo Reminders
  app/assets/documents/chairman_memorandum_01-10-18.pdf
  app/models/tasks/abstract_motion_to_vacate_task.rb
  app/models/tasks/judge_sign_motion_to_vacate_task.rb
  client/COPY.json
  client/app/components/CopyTextButton.jsx
  client/app/queue/AssignToView.jsx
  client/app/queue/CaseDetailsView.jsx
  client/app/queue/QueueApp.jsx
  client/app/queue/TaskSnapshot.jsx
  client/app/queue/pulacCerullo/CavcLinkInfo.jsx
  client/app/queue/pulacCerullo/PulacCerulloReminderAlert.jsx
  client/app/queue/pulacCerullo/PulacCerulloReminderModal.jsx
  client/app/queue/pulacCerullo/index.js
  client/constants/TASK_ACTIONS.json
  client/test/karma/queue/mtv/sample.js
  spec/factories/task.rb
  spec/feature/queue/motion_to_vacate_spec.rb
  spec/feature/queue/task_queue_spec.rb
Labels: Ready-to-Merge

#12405 Remove ability to reassign an AMA judge task from the 'Assign to attorney' page or modal
  app/controllers/judge_assign_tasks_controller.rb
  client/COPY.json
  client/app/queue/components/AssignWidget.jsx
  spec/controllers/judge_assign_tasks_controller_spec.rb
  spec/feature/queue/judge_assignment_spec.rb
Labels: Ready-to-Merge

#12281 Appeals API intake status show
  .reek.yml
  app/controllers/api/docs/v3/decision_reviews.yaml
  app/controllers/api/v3/decision_review/appeals_controller.rb
  app/controllers/api/v3/decision_review/higher_level_reviews_controller.rb
  app/controllers/api/v3/decision_review/intake_statuses_controller.rb
  app/controllers/api/v3/decision_review/supplemental_claims_controller.rb
  app/models/decision_review.rb
  app/services/api/v3/decision_review/higher_level_review_intake_processor.rb
  app/services/api/v3/decision_review/intake_processor.rb
  app/services/api/v3/decision_review/intake_status.rb
  config/routes.rb
  spec/requests/api/docs/v3/docs_controller_spec.rb
  spec/requests/api/v3/decision_review/higher_level_reviews_controller_spec.rb
  spec/requests/api/v3/decision_review/intake_statuses_controller_spec.rb
  spec/services/api/v3/decision_review/intake_processor_spec.rb
  spec/services/api/v3/decision_review/intake_status_spec.rb
Labels: Ready-to-Merge, lighthouse

#12401 Migration to create Virtual Hearings table
  db/migrate/20191015204516_create_virtual_hearings.rb
  db/schema.rb
Labels: Ready-to-Merge

#12363 Intake add date-picker
  client/app/intake/actions/rampElection.js
  client/app/intake/actions/rampRefiling.js
  client/app/intake/components/AddedIssue.jsx
  client/app/intake/components/NonratingRequestIssueModal.jsx
  client/app/intake/pages/addIssues.jsx
  client/app/intake/pages/appeal/review.jsx
  client/app/intake/pages/higherLevelReview/review.jsx
  client/app/intake/pages/rampElection/review.jsx
  client/app/intake/pages/rampRefiling/review.jsx
  client/app/intake/pages/supplementalClaim/review.jsx
  client/app/intake/reducers/appeal.js
  client/app/intake/reducers/higherLevelReview.js
  client/app/intake/reducers/rampElection.js
  client/app/intake/reducers/rampRefiling.js
  client/app/intake/reducers/supplementalClaim.js
  client/app/intake/util/index.js
  client/app/intake/util/issues.js
  client/app/intakeEdit/components/EditButtons.jsx
  spec/feature/intake/appeal/edit_spec.rb
  spec/feature/intake/higher_level_review_spec.rb
Labels: Ready-to-Merge

#12402 Extend judge reassign action to JudgeLegacyAssignTasks
  app/models/legacy_tasks/judge_legacy_assign_task.rb
  app/repositories/task_action_repository.rb
  client/app/queue/AssignToView.jsx
  client/app/queue/QueueActions.js
  config/routes.rb
  spec/controllers/legacy_tasks_controller_spec.rb
  spec/feature/queue/judge_assignment_spec.rb
Labels: Ready-to-Merge

#12398 add to the make file's clean directive commands to remove node_modules and packag…
  Makefile.example
Labels: Ready-to-Merge

#12415 move att name printout to task_tree_attributes
  app/models/concerns/prints_task_tree.rb
Labels: Ready-to-Merge

#12396 Virtual Hearing Modal
  app/views/hearings/index.html.erb
  client/COPY.json
  client/app/components/Dropdown.jsx
  client/app/components/SearchableDropdown.jsx
  client/app/components/common/reducers.js
  client/app/hearings/HearingsApp.jsx
  client/app/hearings/components/Details.jsx
  client/app/hearings/components/DetailsSections.jsx
  client/app/hearings/components/VirtualHearingModal.jsx
  client/app/hearings/components/details/DetailsInputs.jsx
  client/app/hearings/components/details/DetailsOverview.jsx
  client/app/hearings/components/details/TranscriptionDetailsInputs.jsx
  client/app/hearings/components/details/TranscriptionProblemInputs.jsx
  client/app/hearings/components/details/TranscriptionRequestInputs.jsx
  client/app/hearings/components/details/style.jsx
  client/app/hearings/containers/DetailsContainer.jsx
  spec/feature/hearings/hearing_details_spec.rb
Labels: Ready-to-Merge

#12377 change filtering to UNION results, not INTERSECT
  app/models/queue_column.rb
  app/models/queue_filter_parameter.rb
  app/models/task_filter.rb
  client/constants/QUEUE_CONFIG.json
  spec/models/queue_column_spec.rb
  spec/models/queue_filter_parameter_spec.rb
  spec/models/task_filter_spec.rb
Labels: Ready-to-Merge

#12431 Delete tech-lead-description.md
  docs/tech-lead-description.md
Labels: Ready-to-Merge

#12429 Delete product-lead-responsibilities.md
  docs/product-lead-responsibilities.md
Labels: Ready-to-Merge

#12430 Delete engineering-lead-description.md
  docs/engineering-lead-description.md
Labels: Ready-to-Merge

#12426 Fix remanded definition for request issue
  app/models/request_issue.rb
  spec/models/request_issue_spec.rb
Labels: Ready-to-Merge

#12346 User batch flake spec
  spec/feature/login_spec.rb
Labels: Ready-to-Merge

#12440 930enchancement -show correction type
  client/app/intake/components/AddedIssue.jsx
  client/app/intake/components/CorrectionTypeModal.jsx
  client/app/intake/constants.js
  client/app/intake/pages/addIssues.jsx
  spec/feature/intake/end_product_correction_spec.rb
Labels: Ready-to-Merge

#12435 Org user selector fetches remaining_users async via XHR
  app/controllers/organizations/users_controller.rb
  app/controllers/users_controller.rb
  app/models/organization.rb
  app/services/user_finder.rb
  client/app/components/SearchableDropdown.jsx
  client/app/queue/OrganizationUsers.jsx
  spec/controllers/users_controller_spec.rb
  spec/feature/queue/user_organization_spec.rb
  spec/services/user_finder_spec.rb
Labels: Ready-to-Merge

#12413 create pexip service class
  .reek.yml
  app/services/external_api/pexip_service.rb
  app/services/external_api/pexip_service/create_response.rb
  app/services/external_api/pexip_service/delete_response.rb
  app/services/external_api/pexip_service/response.rb
  lib/caseflow/error.rb
  lib/fakes/pexip_service.rb
  spec/services/external_api/pexip_service_spec.rb
Labels: Ready-to-Merge

#12427 Save end product claim type code updates
  app/models/end_product_code_update.rb
  app/models/end_product_establishment.rb
  db/migrate/20191017235707_create_end_product_code_updates.rb
  db/schema.rb
  spec/models/end_product_establishment_spec.rb
Labels: Ready-to-Merge

#12419 Update reassign function
  app/models/task.rb
  spec/models/tasks/generic_task_spec.rb
Labels: Ready-to-Merge

#12371 Add Back Hearing view
  app/controllers/hearings/hearing_view_controller.rb
  client/app/hearings/components/hearingWorksheet/HearingWorksheet.jsx
  client/app/queue/CaseHearingsDetail.jsx
  config/routes.rb
  spec/feature/hearings/hearing_worksheet/hearing_prep_spec.rb
  spec/feature/queue/case_details_spec.rb
Labels: Ready-to-Merge

#12417 Add Virtual Hearings Model
  app/models/concerns/has_virtual_hearing.rb
  app/models/hearing.rb
  app/models/hearings/virtual_hearing.rb
  app/models/legacy_hearing.rb
  app/repositories/virtual_hearing_repository.rb
  app/serializers/hearings/hearing_serializer.rb
  app/serializers/hearings/legacy_hearing_serializer.rb
  spec/factories/hearing.rb
  spec/factories/legacy_hearing.rb
  spec/factories/virtual_hearing.rb
  spec/models/concerns/has_virtual_hearing_examples.rb
  spec/models/hearing_spec.rb
  spec/models/legacy_hearing_spec.rb
  spec/repositories/virtual_hearing_repository_spec.rb
Labels: Ready-to-Merge

#12444 Update user selection placeholder text
  client/COPY.json
Labels: Ready-to-Merge

#12368 Automatically reassign Motions to Vacate tasks back to motions attorneys when denied or withdrawn/dismissed
  app/workflows/post_decision_motion_updater.rb
  client/COPY.json
  client/app/queue/QueueApp.jsx
  client/app/queue/mtv/MTVJudgeDisposition.jsx
  client/app/queue/mtv/MissingDenialDraftAlert.jsx
  client/app/queue/mtv/ReturnToLitSupportModal.jsx
  client/constants/TASK_ACTIONS.json
  spec/feature/queue/motion_to_vacate_spec.rb
  spec/workflows/post_decision_motion_updater_spec.rb
Labels: Ready-to-Merge

#12449 Create JudgeTeamRole table
  app/models/decision_drafting_attorney.rb
  app/models/judge_team_lead.rb
  app/models/judge_team_role.rb
  app/models/organizations_user.rb
  db/migrate/20191021215017_create_judge_team_roles.rb
  db/schema.rb
  spec/factories/judge_team_role.rb
  spec/factories/organizations_user.rb
  spec/models/judge_team_role_spec.rb
Labels: Ready-to-Merge

#12475 AOD motion column comments
  db/migrate/20191023204446_add_column_comments_for_advance_on_docket_motions.rb
  db/schema.rb
Labels: Ready-to-Merge

#12452 Add Aria labels for Reader table sorting controls
  client/app/reader/DocumentsTable.jsx
Labels: Ready-to-Merge

#12149 Rubaiyat/12022 create attorney task for assigned legacy cases
  app/controllers/judge_assign_tasks_controller.rb
  app/controllers/legacy_tasks_controller.rb
  app/workflows/attorney_task_creator.rb
  app/workflows/das_deprecation/assign_task_to_attorney.rb
  client/app/queue/QueueActions.js
  client/app/queue/selectors.js
  spec/controllers/legacy_tasks_controller_spec.rb
  spec/workflows/das_deprecation/assign_task_to_attorney_spec.rb
Labels: Ready-to-Merge

#12482 Add Alternate Hearing Location IDs
  client/constants/REGIONAL_OFFICE_INFORMATION.json
Labels: Ready-to-Merge

#12484 Create JudgeTeamLead when creating JudgeTeams for judges
  app/models/organizations/judge_team.rb
  app/models/organizations_user.rb
  spec/models/judge_spec.rb
  spec/models/judge_team_spec.rb
  spec/models/organizations_user_spec.rb
  spec/models/user_spec.rb
  spec/workflows/das_deprecation/assign_task_to_attorney_spec.rb
Labels: Ready-to-Merge

#12485 Make classes that inherit from GenericTask inherit from Task
  app/models/tasks/abstract_motion_to_vacate_task.rb
  app/models/tasks/denied_motion_to_vacate_task.rb
  app/models/tasks/dismissed_motion_to_vacate_task.rb
  app/models/tasks/straight_vacate_and_readjudication_task.rb
  app/models/tasks/vacate_and_de_novo_task.rb
  spec/workflows/post_decision_motion_updater_spec.rb
Labels: Ready-to-Merge

#12191 Add scripts to streamline dev env setup
  README.md
  scripts/dev_env_setup_step1.sh
  scripts/dev_env_setup_step2.sh
Labels: Ready-to-Merge

#12489 Add Support for "Help" Text to RadioField
  client/app/components/RadioField.jsx
  client/app/components/RadioField.module.scss
  client/app/containers/StyleGuide/RadioFieldExamples/Example5.jsx
  client/app/containers/StyleGuide/StyleGuideRadioField.jsx
  client/webpack.config.js
Labels: Ready-to-Merge

#12084 Optimize Hearing Days Index a bit
  app/models/hearing_day.rb
  app/serializers/hearings/hearing_day_serializer.rb
  app/services/hearing_day_range.rb
  spec/models/hearing_day_spec.rb
  spec/services/hearing_day_range_spec.rb
Labels: Ready-to-Merge

#12487 Remove references to GenericTask
  app/controllers/tasks_controller.rb
  app/models/tasks/colocated_task.rb
  app/repositories/task_action_repository.rb
  client/app/queue/AssignToView.jsx
  client/test/karma/queue/ColocatedTaskListView-test.js
  client/test/karma/queue/mtv/sample.js
  spec/controllers/idt/api/appeals_controller_spec.rb
  spec/controllers/organizations/tasks_controller_spec.rb
  spec/controllers/tasks_controller_spec.rb
  spec/factories/task.rb
  spec/feature/queue/case_details_spec.rb
  spec/feature/queue/task_queue_spec.rb
  spec/models/task_spec.rb
  spec/models/tasks/generic_task_spec.rb
  spec/models/tasks/mail_task_spec.rb
  spec/models/tasks/privacy_act_task_spec.rb
  spec/models/tasks/quality_review_task_spec.rb
  spec/models/tasks/timed_hold_task_spec.rb
  spec/models/user_spec.rb
Labels: Ready-to-Merge

#12495 Add meat to OrganizationsController.add_user_to_vso code comment
  app/controllers/organizations_controller.rb
Labels: Ready-to-Merge

#12498 Only compile javascript assets for front-end tests
  spec/rails_helper.rb
Labels: Ready-to-Merge

#12454 MTV | Add option for partial grant and select issues
  app/models/post_decision_motion.rb
  app/workflows/post_decision_motion_updater.rb
  client/COPY.json
  client/app/queue/mtv/MTVDispositionSelection.jsx
  client/app/queue/mtv/MTVIssueSelection.jsx
  client/app/queue/mtv/MTVJudgeDisposition.jsx
  client/constants/MOTION_TO_VACATE.json
  spec/feature/queue/motion_to_vacate_spec.rb
  spec/support/queue_helpers.rb
Labels: Ready-to-Merge

#12503 Appeals API - Update description for /intake_statuses
  app/controllers/api/docs/v3/decision_reviews.yaml
Labels: Ready-to-Merge

#12504 Show automatically routed ColocatedTasks in attorney's on hold tab
  app/models/queues/attorney_queue.rb
  spec/models/queues/attorney_queue_spec.rb
Labels: Ready-to-Merge

#12511 add diagnostic code 9917 & 9918
  client/constants/DIAGNOSTIC_CODE_DESCRIPTIONS.json
Labels: Ready-to-Merge, batteam

#12516 refactor Veteran attribute caching
  app/models/veteran.rb
Labels: Ready-to-Merge

#12494 Edit Virtual Hearing Modal
  client/app/hearings/components/VirtualHearingModal.jsx
  client/app/hearings/components/dailyDocket/DailyDocketRow.jsx
  spec/feature/hearings/daily_docket/hearing_prep_spec.rb
Labels: Ready-to-Merge

#12512 Reset RIght Hearing Data After Save
  client/app/hearings/components/Details.jsx
  client/app/hearings/containers/DetailsContainer.jsx
Labels: Ready-to-Merge

#12509 Only save new codes if it has changed since last checked
  app/models/end_product_establishment.rb
  spec/models/end_product_establishment_spec.rb
Labels: Ready-to-Merge

#12527 Preserve line breaks added to task instructions
  client/app/queue/components/TaskRows.jsx
Labels: Ready-to-Merge

#12499 Build individual generic queues from config
  client/app/components/TabWindow.jsx
  client/app/queue/ColocatedTaskListView.jsx
  client/app/queue/components/TaskTable.jsx
  client/app/queue/components/TaskTableColumns.jsx
  client/test/karma/queue/ColocatedTaskListView-test.js
Labels: Ready-to-Merge

#12488 Controllers for Virtual Hearings
  Gemfile
  Gemfile.lock
  app/controllers/hearings_controller.rb
  app/models/hearings/forms/base_hearing_update_form.rb
  app/models/hearings/forms/hearing_update_form.rb
  app/models/hearings/forms/legacy_hearing_update_form.rb
  app/models/hearings/virtual_hearing.rb
  config/application.rb
  spec/controllers/hearings_controller_spec.rb
  spec/factories/legacy_hearing.rb
  spec/feature/hearings/hearing_worksheet/hearing_prep_spec.rb
  spec/models/hearing_spec.rb
  spec/models/hearings/virtual_hearing_spec.rb
  spec/models/legacy_hearing_spec.rb
  spec/repositories/virtual_hearing_repository_spec.rb
Labels: Ready-to-Merge

#12530 Cleanup and comments from Death Dismissal
  Makefile.example
  app/models/legacy_tasks/judge_legacy_decision_review_task.rb
  spec/feature/queue/special_case_movement_task_spec.rb
Labels: Ready-to-Merge

#12533 Screen Reader Announces Checkboxes Fix
  client/app/components/Checkbox.jsx
Labels: Ready-to-Merge

#12529 Created LegacyAppeal `eligible_for_death_dismissal`
  app/models/appeal.rb
  app/models/legacy_appeal.rb
  spec/models/legacy_appeal_spec.rb
Labels: Ready-to-Merge
