Repository department-of-veterans-affairs/caseflow, pull requests merged in 2019-11, with the labels that each got.

#12532 Persist Fake Ratings storage
  .reek.yml
  db/seeds.rb
  lib/fakes/bgs_service.rb
  lib/fakes/end_product_store.rb
  lib/fakes/persistent_store.rb
  lib/fakes/rating_store.rb
  lib/generators/rating.rb
  lib/tasks/local/fakes.rake
  spec/feature/intake/appeal_spec.rb
  spec/feature/non_comp/dispositions_spec.rb
  spec/models/hearings/virtual_hearing_spec.rb
Labels: Ready-to-Merge

#12548 Set long timeout for index migration
  db/migrate/20191031211321_add_request_id_index_to_versions.rb
Labels: Ready-to-Merge

#12526 Fix edit confirmation page bug when ineligible issues added
  client/app/intake/pages/decisionReviewEditCompleted.jsx
  spec/feature/intake/intake_edit_confirmation_spec.rb
Labels: Ready-to-Merge

#12483 Create rake task to reassign all tasks assigned to a user
  .reek.yml
  app/workflows/bulk_task_reassignment.rb
  lib/tasks/tasks.rake
  spec/lib/tasks/tasks_spec.rb
  spec/workflows/bulk_task_reassignment_spec.rb
Labels: Ready-to-Merge

#12513 MTV | Save partial grant to database with selected issues
  app/controllers/post_decision_motions_controller.rb
  app/models/post_decision_motion.rb
  app/workflows/post_decision_motion_updater.rb
  client/app/queue/mtv/MTVJudgeDisposition.jsx
  db/migrate/20191028200741_add_issues_to_post_decision_motions.rb
  db/schema.rb
  spec/feature/queue/motion_to_vacate_spec.rb
Labels: Ready-to-Merge

#12546 Virtual Hearings Controller - Move transaction
  app/models/hearings/forms/base_hearing_update_form.rb
  app/models/hearings/forms/hearing_update_form.rb
Labels: Ready-to-Merge

#12563 fixed syntax error in migration
  db/migrate/20191028200741_add_issues_to_post_decision_motions.rb
  db/schema.rb
Labels: Ready-to-Merge

#12541 If a veteran has a duplicate record, show an error alert when a user searches for a veteran in intake
  app/models/intake.rb
  app/models/validators/intake_start_validator.rb
  app/services/duplicate_veteran_participant_id_finder.rb
  client/app/components/Alert.jsx
  client/app/intake/pages/search.jsx
  client/app/intake/reducers/intake.js
  spec/feature/intake/intake_spec.rb
  spec/services/duplicate_veteran_participant_id_finder_spec.rb
Labels: Ready-to-Merge, foxtrot

#12459 Lighthouse pb implement hlr show endpoint
  app/controllers/api/docs/v3/decision_reviews.yaml
  app/controllers/api/v3/decision_review/higher_level_reviews_controller.rb
  app/models/request_issue.rb
  app/serializers/api/v3/claimant_serializer.rb
  app/serializers/api/v3/decision_issue_serializer.rb
  app/serializers/api/v3/higher_level_review_serializer.rb
  app/serializers/api/v3/request_issue_serializer.rb
  app/serializers/api/v3/veteran_serializer.rb
  spec/requests/api/v3/decision_review/higher_level_reviews_controller_spec.rb
Labels: Ready-to-Merge

#12528 Sandra/12378 decision date undentified issue
  app/controllers/intakes_controller.rb
  app/models/request_issue.rb
  app/views/appeals/edit.html.erb
  app/views/higher_level_reviews/edit.html.erb
  app/views/supplemental_claims/edit.html.erb
  client/app/intake/actions/addIssues.js
  client/app/intake/components/AddIssueManager.jsx
  client/app/intake/components/UnidentifiedIssuesModal.jsx
  client/app/intake/pages/addIssues.jsx
  client/app/intake/reducers/featureToggles.js
  client/app/intake/util/issues.js
  client/test/karma/intake/UnidentifiedIssuesModal-test.js
  client/test/karma/intake/testData.js
  db/migrate/20191101145935_update_decision_date_comment_on_request_issues.rb
  db/schema.rb
  spec/feature/intake/add_issues_spec.rb
Labels: Ready-to-Merge

#12576 Do not reopen RootTasks when child created
  app/models/tasks/root_task.rb
  spec/models/tasks/root_task_spec.rb
Labels: Ready-to-Merge

#12571 Stop created inbox_messages in db/seeds
  db/seeds.rb
Labels: Ready-to-Merge

#12572 Fix regression with AOD params being empty
  app/controllers/hearings_controller.rb
  spec/controllers/hearings_controller_spec.rb
Labels: Ready-to-Merge

#12579 Do not query BGS when matching SSN (allow nil attribute)
  app/services/veteran_finder.rb
  spec/services/veteran_finder_spec.rb
Labels: Ready-to-Merge

#12578 Send message to Sentry when child task created for closed task
  .reek.yml
  app/models/task.rb
  app/models/tasks/root_task.rb
  spec/models/task_spec.rb
  spec/models/tasks/root_task_spec.rb
Labels: Ready-to-Merge

#12549 Remove actions on on-hold tasks for judges
  app/models/tasks/judge_task.rb
  spec/models/tasks/judge_task_spec.rb
Labels: Ready-to-Merge

#12535 Death Dismissal Part 2 Backend Logic
  .reek.yml
  app/models/legacy_appeal.rb
  app/repositories/appeal_repository.rb
  spec/models/legacy_appeal_spec.rb
  spec/repositories/appeal_repository_spec.rb
Labels: Ready-to-Merge

#12559 screenreader now capable of reading checkbox group
  client/app/containers/EstablishClaimPage/EstablishClaimDecision.jsx
  client/app/styles/dispatch/_dispatch.scss
Labels: Ready-to-Merge

#12582 Add upsert to AODMotion
  app/controllers/advance_on_docket_motions_controller.rb
  app/models/advance_on_docket_motion.rb
  app/models/hearings/forms/hearing_update_form.rb
  spec/controllers/advanced_on_docket_motions_controller_spec.rb
Labels: Ready-to-Merge

#12596 Don't send message to Sentry when we create a child task for a RootTask that is already on hold
  app/models/tasks/root_task.rb
  spec/models/tasks/root_task_spec.rb
Labels: Ready-to-Merge

#12493 Create DecisionDraftingAttorney rows when adding users to JudgeTeams
  app/models/organizations/judge_team.rb
  spec/models/judge_team_spec.rb
Labels: Ready-to-Merge

#12606 Fix db seeds inbox creation
  db/seeds.rb
Labels: Ready-to-Merge

#12586 Allow VSOs to place their tasks on hold and end holds early
  app/controllers/tasks/end_hold_controller.rb
  app/controllers/tasks/place_hold_controller.rb
  app/controllers/tasks_controller.rb
  spec/controllers/tasks/end_hold_controller_spec.rb
  spec/controllers/tasks/place_hold_controller_spec.rb
  spec/controllers/tasks_controller_spec.rb
Labels: Ready-to-Merge

#12613 Create AMA Appeals ready for Distribution with known Vet File Numbers
  db/seeds.rb
Labels: Ready-to-Merge

#12497 Add class to ensure JudgeTeamRoles are correct
  app/models/organization.rb
  app/services/judge_team_role_checker.rb
  spec/factories/organization.rb
  spec/services/judge_team_role_checker_spec.rb
Labels: Ready-to-Merge

#12598 Add Virtual type to daily docket
  app/models/hearing.rb
  app/models/hearing_day.rb
  app/models/hearings/virtual_hearing.rb
  app/models/legacy_hearing.rb
  app/serializers/hearings/hearing_day_serializer.rb
  client/app/hearings/components/dailyDocket/DailyDocketPrinted.jsx
Labels: Ready-to-Merge

#12618 Add Hearings to VSO
  db/seeds.rb
Labels: Ready-to-Merge

#12619 add indexing to alias on virtual hearings table
  db/migrate/20191106153923_add_index_to_virtual_hearings.rb
  db/schema.rb
Labels: Ready-to-Merge, tango

#12620 Clean up db after spec (fixes flake in batch_users_for_reader_query_spec)
  spec/controllers/idt/authentications_controller_spec.rb
Labels: Ready-to-Merge

#12542 Create design-story.md
  .github/ISSUE_TEMPLATE/design-task.md
Labels: Ready-to-Merge

#12599 Remove modern recordkeeping, always use promulgation date as decision date
  app/models/rating_decision.rb
  app/workflows/contestable_issue_generator.rb
  spec/feature/intake/add_issues_spec.rb
  spec/models/rating_decision_spec.rb
  spec/support/intake_helpers.rb
Labels: Ready-to-Merge

#12625 Fix hearing disposition change job spec flakey test
  app/jobs/hearing_disposition_change_job.rb
Labels: Ready-to-Merge

#12567 MTV | Add org tasks to MTV task tree to account for potentially inactive users
  app/models/tasks/abstract_motion_to_vacate_task.rb
  app/models/tasks/decided_motion_to_vacate_task.rb
  app/models/tasks/denied_motion_to_vacate_task.rb
  app/models/tasks/dismissed_motion_to_vacate_task.rb
  app/models/tasks/straight_vacate_and_readjudication_task.rb
  app/models/tasks/vacate_and_de_novo_task.rb
  app/workflows/post_decision_motion_updater.rb
  spec/factories/task.rb
  spec/models/decided_motion_to_vacate_task_spec.rb
  spec/workflows/post_decision_motion_updater_spec.rb
Labels: Ready-to-Merge

#12627 add note about docs moved to wiki
  docs/caseflow-apis.md
Labels: Ready-to-Merge

#12628 Add header to design task template
  .github/ISSUE_TEMPLATE/design-task.md
Labels: Ready-to-Merge

#12575 HearingCoordinatorScheduleQueue
  app/controllers/tasks_controller.rb
  app/models/queues/hearing_coordinator_schedule_queue.rb
  app/models/tasks/schedule_hearing_task.rb
  spec/models/queues/hearing_coordinator_schedule_queue_spec.rb
  spec/models/tasks/schedule_hearing_task_spec.rb
Labels: Ready-to-Merge

#12466 Migrate to wiki
  docs/FACOLS.md
Labels: Ready-to-Merge

#12467 Migrate to wiki
  docs/asyncable-models.md
Labels: Ready-to-Merge

#12630 Always fetch user queue
  client/app/queue/QueueLoadingScreen.jsx
  spec/feature/queue/ama_queue_spec.rb
Labels: Ready-to-Merge

#12469 Migrate to wiki
  docs/bat-team.md
Labels: Ready-to-Merge

#12611 Rubaiyat/create virtual hearing conference job
  app/jobs/virtual_hearings/create_conference_job.rb
  app/jobs/virtual_hearings/pexip_client.rb
  app/jobs/virtual_hearings/send_email.rb
  config/initializers/pexip.rb
  lib/fakes/pexip_service.rb
  spec/jobs/virtual_hearings/create_conference_job_spec.rb
Labels: Ready-to-Merge

#12608 Hearing Day Controller Refactor
  app/controllers/hearings/hearing_day_controller.rb
  app/serializers/hearings/hearing_day_serializer.rb
  app/services/hearing_day_range.rb
  app/services/hearing_day_room_assignment.rb
Labels: Ready-to-Merge

#12626 Async job CSV export
  app/controllers/asyncable_jobs_controller.rb
  client/app/asyncableJobs/components/AsyncModelNav.jsx
  client/app/asyncableJobs/pages/JobsPage.jsx
  spec/controllers/asyncable_jobs_controller_spec.rb
  spec/feature/asyncable_jobs/asyncable_jobs_index_spec.rb
Labels: Ready-to-Merge

#12639 Rubaiyat/minor changes to create conference job
  app/jobs/virtual_hearings/create_conference_job.rb
  app/jobs/virtual_hearings/pexip_client.rb
  app/services/external_api/pexip_service.rb
Labels: Ready-to-Merge, tango

#12633 Add engineering task template
  .github/ISSUE_TEMPLATE/engineering-task.md
  .github/ISSUE_TEMPLATE/epic.md
  .github/ISSUE_TEMPLATE/story.md
Labels: Ready-to-Merge

#12652 Upgrade brakeman dependency from 4.6.1 to 4.7.1
  Gemfile.lock
Labels: Ready-to-Merge

#12636 Rake task to assign all existing JudgeTeam Members a JudgeTeamRole
  .reek.yml
  app/workflows/assign_judgeteam_roles.rb
  lib/tasks/tasks.rake
  spec/workflows/bulk_task_reassignment_spec.rb
Labels: Ready-to-Merge

#12614 MTV | Backend Support for "Return to Litigation Support" Workflow
  app/controllers/post_decision_motions_controller.rb
  client/COPY.json
  client/app/queue/QueueApp.jsx
  client/app/queue/mtv/AddressMotionToVacateView.jsx
  client/app/queue/mtv/MTVJudgeDisposition.jsx
  client/app/queue/mtv/ReturnToLitSupportModal.jsx
  client/app/queue/mtv/actionTypes.js
  client/app/queue/mtv/mtvActions.js
  client/app/queue/utils.js
  config/routes.rb
  spec/feature/queue/motion_to_vacate_spec.rb
Labels: Ready-to-Merge

#12550 Clean Virtual Hearing Conferences Job
  .reek.yml
  app/jobs/virtual_hearings/delete_conferences_job.rb
  app/jobs/virtual_hearings/send_email.rb
  app/repositories/virtual_hearing_repository.rb
  lib/fakes/pexip_service.rb
  spec/factories/user.rb
  spec/jobs/virtual_hearings/delete_conferences_job_spec.rb
  spec/repositories/virtual_hearing_repository_spec.rb
Labels: Ready-to-Merge

#12663 Invert logic syntax for readability
  app/models/veteran.rb
Labels: Ready-to-Merge

#12671 Add db:migrate:redo step to CI
  .circleci/config.yml
Labels: Ready-to-Merge

#12664 Search User name in autocomplete, fix zero match bug
  app/controllers/users_controller.rb
  app/services/user_finder.rb
  spec/controllers/users_controller_spec.rb
  spec/services/user_finder_spec.rb
Labels: Ready-to-Merge

#12676 Add back argument refactor ate
  app/workflows/assign_judgeteam_roles.rb
Labels: Ready-to-Merge

#12677 Kat/12421 refactor bugfix 2
  app/workflows/assign_judgeteam_roles.rb
Labels: Ready-to-Merge

#12631 Add virtual to request type for hearing days
  app/controllers/hearings/hearing_day_controller.rb
  app/queries/hearing_days_with_virtual_hearings_query.rb
  app/repositories/virtual_hearing_repository.rb
  app/serializers/hearings/hearing_day_serializer.rb
  app/services/hearing_day_range.rb
  spec/controllers/hearings/hearing_day_controller_spec.rb
  spec/controllers/hearings_controller_spec.rb
Labels: Ready-to-Merge

#12660 Disable pagination when listing async jobs for CSV export
  app/controllers/asyncable_jobs_controller.rb
  spec/controllers/asyncable_jobs_controller_spec.rb
Labels: Ready-to-Merge

#12690 Fix intake receipt_date logic for contestable issues
  app/workflows/contestable_issue_generator.rb
  spec/workflows/contestable_issue_generator_spec.rb
Labels: Ready-to-Merge

#12675 Choose correct claimant and payee code for board grant effectuations
  app/models/board_grant_effectuation.rb
  app/models/relationship.rb
  app/models/veteran.rb
  spec/models/board_grant_effectuation_spec.rb
  spec/models/decision_document_spec.rb
  spec/models/veteran_spec.rb
Labels: Ready-to-Merge

#12667 Quiet job alerts that are not actionable
  .reek.yml
  app/jobs/warm_bgs_caches_job.rb
  app/services/asyncable_jobs_reporter.rb
  app/services/expired_async_jobs_checker.rb
  spec/controllers/asyncable_jobs_controller_spec.rb
  spec/jobs/warm_bgs_caches_job_spec.rb
  spec/services/asyncable_jobs_reporter_spec.rb
Labels: Ready-to-Merge

#12699 Add virtual_hearings_establishment table
  db/migrate/20191113160247_create_virtual_hearing_establishments.rb
  db/schema.rb
Labels: Ready-to-Merge

#12701 Add UI changes section to PR Template
  PULL_REQUEST_TEMPLATE.md
Labels: Ready-to-Merge

#12698 Alphabetize TASK_CLASSES_LOOKUP in TasksController.
  app/controllers/tasks_controller.rb
Labels: Ready-to-Merge

#12673 Appeal status
  app/models/appeal.rb
  app/services/bva_appeal_status.rb
  spec/controllers/idt/api/appeals_controller_spec.rb
  spec/models/appeal_spec.rb
  spec/services/bva_appeal_status_spec.rb
  spec/sql/bva_decision_progress_spec.rb
Labels: Ready-to-Merge

#12687 Show POA address on Case Details Page
  app/controllers/appeals_controller.rb
  app/models/appeal.rb
  app/models/claimant.rb
  app/models/legacy_appeal.rb
  app/models/person.rb
  app/models/power_of_attorney.rb
  app/services/bgs_power_of_attorney.rb
  app/services/external_api/bgs_service.rb
  client/app/queue/PowerOfAttorneyDetail.jsx
  lib/fakes/bgs_service.rb
Labels: Ready-to-Merge

#12696 Rubaiyat/integrate caseflow with virtual hearings
  app/models/hearings/forms/base_hearing_update_form.rb
  app/serializers/hearings/hearing_serializer.rb
  app/serializers/hearings/legacy_hearing_serializer.rb
  app/serializers/hearings/virtual_hearing_serializer.rb
  client/app/hearings/components/Details.jsx
  client/app/hearings/components/DetailsSections.jsx
  client/app/hearings/components/dailyDocket/DailyDocketRow.jsx
  client/app/hearings/components/details/DetailsInputs.jsx
  client/app/hearings/containers/DailyDocketContainer.jsx
  spec/controllers/hearings_controller_spec.rb
  spec/feature/hearings/daily_docket/hearing_prep_spec.rb
  spec/feature/hearings/hearing_details_spec.rb
Labels: Ready-to-Merge

#12190 Redistribute cases logic
  .reek.yml
  app/models/dockets/legacy_docket.rb
  app/services/redistributed_case.rb
  spec/factories/legacy_appeal.rb
  spec/models/distribution_spec.rb
  spec/models/redistributed_case_spec.rb
Labels: Ready-to-Merge

#12679 v3 api - update spec - receive contact info when intaking HLRs
  app/controllers/api/docs/v3/decision_reviews.yaml
Labels: Ready-to-Merge, lighthouse

#12715 Pass task type instead of generic Task when assigning tasks to organizations.
  app/repositories/task_action_repository.rb
Labels: Ready-to-Merge

#12702 Add Asyncable to Virtual Hearings Establishment
  app/jobs/virtual_hearings/create_conference_job.rb
  app/models/hearings/forms/base_hearing_update_form.rb
  app/models/hearings/virtual_hearing.rb
  app/models/hearings/virtual_hearing_establishment.rb
  spec/factories/virtual_hearing.rb
  spec/factories/virtual_hearing_establishment.rb
  spec/jobs/virtual_hearings/create_conference_job_spec.rb
Labels: Ready-to-Merge

#12722 v3 api - update spec - receive informal conference rep and time slots when intaking HLRs
  app/controllers/api/docs/v3/decision_reviews.yaml
Labels: Ready-to-Merge, lighthouse

#12682 Check timeliness eligibility on unidentified issues
  app/models/request_issue.rb
  client/app/intake/components/AddIssueManager.jsx
  client/app/intake/components/AddedIssue.jsx
  client/app/intake/components/NonratingRequestIssueModal.jsx
  client/app/intake/components/UnidentifiedIssuesModal.jsx
  client/app/intake/pages/higherLevelReview/review.jsx
  client/app/intake/util/issues.js
  client/app/styles/_intake.scss
  spec/feature/intake/add_issues_spec.rb
  spec/feature/intake/appeal_spec.rb
  spec/feature/intake/higher_level_review/edit_spec.rb
  spec/models/request_issue_spec.rb
Labels: Ready-to-Merge

#12720 APIv3 - HigherLevelReview#show to match up with specs
  app/controllers/api/docs/v3/decision_reviews.yaml
  app/serializers/api/v3/higher_level_review_serializer.rb
  spec/requests/api/v3/decision_review/higher_level_reviews_controller_spec.rb
Labels: Ready-to-Merge, lighthouse

#12714 request issue report week-over-week by type
  .reek.yml
  app/models/request_issue.rb
  app/services/request_issue_reporter.rb
  spec/factories/request_issue.rb
  spec/models/request_issue_spec.rb
  spec/services/request_issue_reporter_spec.rb
Labels: Ready-to-Merge

#12721 kick off virtual conference job from base_hearing_update_form
  app/models/hearings/forms/base_hearing_update_form.rb
  spec/controllers/hearings_controller_spec.rb
  spec/feature/hearings/hearing_details_spec.rb
Labels: Ready-to-Merge

#12588 Do not save two claimants during intake, use last claimant if there are two
  app/controllers/advance_on_docket_motions_controller.rb
  app/controllers/intakes_controller.rb
  app/models/appeal.rb
  app/models/appeal_intake.rb
  app/models/board_grant_effectuation.rb
  app/models/claim_review_intake.rb
  app/models/claimant.rb
  app/models/decision_issue.rb
  app/models/decision_review.rb
  app/models/serializers/idt/v1/appeal_details_serializer.rb
  app/models/serializers/work_queue/appeal_serializer.rb
  app/models/serializers/work_queue/veteran_record_request_serializer.rb
  app/serializers/api/v3/higher_level_review_serializer.rb
  spec/controllers/advanced_on_docket_motions_controller_spec.rb
  spec/controllers/idt/api/appeals_controller_spec.rb
  spec/factories/claimant.rb
  spec/feature/hearings/daily_docket/build_hearsched_spec.rb
  spec/feature/intake/higher_level_review_spec.rb
  spec/feature/intake/review_page_spec.rb
  spec/feature/intake/supplemental_claim_spec.rb
  spec/feature/non_comp/board_grants_spec.rb
  spec/feature/non_comp/record_requests_spec.rb
  spec/feature/queue/ama_queue_spec.rb
  spec/feature/queue/task_queue_spec.rb
  spec/models/appeal_intake_spec.rb
  spec/models/appeal_spec.rb
  spec/models/claim_review_intake_spec.rb
  spec/models/claimant_spec.rb
  spec/models/decision_issue_spec.rb
  spec/models/higher_level_review_intake_spec.rb
  spec/models/higher_level_review_spec.rb
  spec/models/supplemental_claim_intake_spec.rb
  spec/requests/api/v3/decision_review/higher_level_reviews_controller_spec.rb
  spec/support/intake_helpers.rb
  spec/workflows/ama_appeal_dispatch_spec.rb
Labels: Ready-to-Merge

#12707 Enable sending inbox messages during job note creation
  app/controllers/asyncable_jobs_controller.rb
  app/models/concerns/asyncable.rb
  app/models/decision_review.rb
  app/models/hearings/virtual_hearing_establishment.rb
  app/services/asyncable_job_messaging.rb
  client/app/asyncableJobs/components/JobNotes.jsx
  spec/feature/asyncable_jobs/asyncable_jobs_index_spec.rb
  spec/models/decision_review_spec.rb
  spec/services/asyncable_job_messaging.rb
Labels: Ready-to-Merge

#12735 Upgrade nokogiri to 1.10.5
  Gemfile
  Gemfile.lock
Labels: Ready-to-Merge

#12729 adding job to the jobs API whitelist
  app/controllers/api/v1/jobs_controller.rb
Labels: Ready-to-Merge, tango

#12727 Remove json_hearing_day and json_hearing_days
  app/controllers/hearings/hearing_day_controller.rb
  app/controllers/hearings/schedule_periods_controller.rb
  app/models/hearing_day.rb
  app/serializers/hearings/hearing_day_serializer.rb
  app/services/hearing_schedule/assign_judges_to_hearing_days.rb
  app/services/hearing_schedule/generate_co_hearing_days_schedule.rb
  spec/models/hearing_day_spec.rb
  spec/models/judge_schedule_period_spec.rb
Labels: Ready-to-Merge

#12740 Add message type column to messages db schema
  app/models/message.rb
  db/migrate/20191118163855_add_message_type_to_messages.rb
  db/schema.rb
Labels: Ready-to-Merge

#12718 Appeal updated since query
  app/queries/appeals_updated_since_query.rb
  db/migrate/20191114210706_add_updated_at_indices.rb
  db/schema.rb
  lib/tasks/tasks.rake
  spec/controllers/hearings_controller_spec.rb
  spec/feature/hearings/daily_docket/build_hearsched_spec.rb
  spec/feature/queue/colocated_task_queue_spec.rb
  spec/lib/tasks/tasks_spec.rb
  spec/queries/appeals_updated_since_query_spec.rb
Labels: Ready-to-Merge

#12745 Always clean both databases when including rails_helper
  spec/models/queue_tab_spec.rb
  spec/models/tasks/judge_quality_review_task_spec.rb
  spec/rails_helper.rb
  spec/support/database_cleaner.rb
  spec/support/vacols_database_cleaner.rb
Labels: Ready-to-Merge

#12743 fix status field input from hearing details page
  client/app/hearings/components/details/DetailsInputs.jsx
Labels: Ready-to-Merge, tango

#12751 remove updated_at indices on large tables
  db/migrate/20191114210706_add_updated_at_indices.rb
  db/schema.rb
Labels: Ready-to-Merge

#12752 Drop more indices on large tables
  db/migrate/20191114210706_add_updated_at_indices.rb
  db/schema.rb
Labels: Ready-to-Merge

#12734 Link to Virtual Hearing
  client/app/hearings/components/Details.jsx
  client/app/hearings/components/VirtualHearingLink.jsx
  client/app/hearings/components/dailyDocket/DailyDocketRow.jsx
  client/app/hearings/components/details/DetailsInputs.jsx
Labels: Ready-to-Merge

#12754 Add missing index, skip some Appeal associations for updated_since
  app/queries/appeals_updated_since_query.rb
  db/migrate/20191119192631_add_missing_appeal_indices.rb
  db/schema.rb
Labels: Ready-to-Merge

#12755 make the switch product link accessible as a expanding/collapsing button
  client/package.json
  client/yarn.lock
  spec/feature/help_spec.rb
Labels: Ready-to-Merge

#12758 Use request issues update user for establishment and cancellations
  app/jobs/decision_review_process_job.rb
  spec/jobs/decision_review_process_job_spec.rb
Labels: Ready-to-Merge

#12741 remove judge email validation from virtual hearings
  app/jobs/virtual_hearings/send_email.rb
  app/models/hearings/forms/base_hearing_update_form.rb
  app/models/hearings/virtual_hearing.rb
  spec/feature/hearings/hearing_details_spec.rb
Labels: Ready-to-Merge

#12629 Add AMO metrics report
  .reek.yml
  app/jobs/amo_metrics_report_job.rb
  app/jobs/monthly_metrics_report_job.rb
  app/services/claim_review_async_stats_reporter.rb
  spec/jobs/amo_metrics_report_job_spec.rb
  spec/jobs/monthly_metrics_report_job_spec.rb
  spec/support/shared_examples/metrics_reports.rb
Labels: Ready-to-Merge

#12753 Only send updated params to /hearings on DailyDocket / HearingDetails
  app/models/hearing.rb
  app/models/legacy_hearing.rb
  client/app/components/common/reducers.js
  client/app/hearings/components/Details.jsx
  client/app/hearings/components/DetailsSections.jsx
  client/app/hearings/components/dailyDocket/DailyDocketRow.jsx
  client/app/hearings/components/details/DetailsInputs.jsx
  client/app/hearings/components/details/HearingTypeDropdown.jsx
  client/app/hearings/containers/DailyDocketContainer.jsx
  client/app/hearings/containers/DetailsContainer.jsx
  client/app/hearings/utils.js
  spec/feature/hearings/hearing_details_spec.rb
  spec/feature/hearings/virtual_hearings/hearing_details_spec.rb
Labels: Ready-to-Merge

#12763 Migration timeout
  db/migrate/20191119192631_add_missing_appeal_indices.rb
Labels: Ready-to-Merge

#12766 Send ReviewsWithDuplicateEpErrorChecker alert to foxtrot channel
  app/services/reviews_with_duplicate_ep_error_checker.rb
Labels: Ready-to-Merge

#12764 Danger warn on large table migration
  Dangerfile
Labels: Ready-to-Merge

#12747 Remove actionNameOfTask() helper function
  client/app/queue/ChangeTaskTypeModal.jsx
  client/app/queue/components/TaskRows.jsx
  client/app/queue/components/TaskTableColumns.jsx
  client/app/queue/utils.js
  client/test/karma/queue/ColocatedTaskListView-test.js
  spec/feature/queue/attorney_queue_spec.rb
  spec/feature/queue/task_queue_spec.rb
Labels: Ready-to-Merge

#12726 Ignore non-actionable tasks when reporting last assignee
  app/models/appeal.rb
  app/models/legacy_appeal.rb
  app/models/task.rb
  spec/models/appeal_spec.rb
  spec/models/legacy_appeal_spec.rb
Labels: Ready-to-Merge, echo

#12669 Initial ETL models
  .circleci/config.yml
  .reek.yml
  .rubocop.yml
  Makefile.example
  app/models/etl/appeal.rb
  app/models/etl/organization.rb
  app/models/etl/person.rb
  app/models/etl/record.rb
  app/models/etl/task.rb
  app/models/etl/user.rb
  db/etl/migrate/20191111164808_create_etl_appeals.rb
  db/etl/migrate/20191119204827_create_etl_users.rb
  db/etl/migrate/20191120184256_create_etl_tasks.rb
  db/etl/migrate/20191120213930_create_etl_people.rb
  db/etl/migrate/20191120213941_create_etl_organizations.rb
  db/etl/schema.rb
Labels: Ready-to-Merge

#12775 Remove all references to GenericTask from the codebase.
  app/controllers/tasks_controller.rb
  app/models/tasks/generic_task.rb
Labels: Ready-to-Merge

#12774 Include error message in ACD docket number error
  app/models/vacols/case_docket.rb
  client/COPY.json
Labels: Ready-to-Merge

#12732 Lighthouse pb issues spec changes
  app/controllers/api/docs/v3/decision_reviews.yaml
Labels: Ready-to-Merge, lighthouse

#12730 v3 api - remove RequestIssues abstraction from HLR endpoint
  app/controllers/api/docs/v3/decision_reviews.yaml
Labels: Ready-to-Merge, lighthouse

#12770 Revert "Add logging for deprecated method (#10954)"
  app/models/document.rb
Labels: Ready-to-Merge

#12783 v3 API - fix typo in POST HLR example
  app/controllers/api/docs/v3/decision_reviews.yaml
Labels: Ready-to-Merge, lighthouse

#12737 Do not expire FACOLS pw
  local/vacols/setup_vacols.sql
Labels: Ready-to-Merge

#12780 Link CircleCI badge directly to master branch (not all branches)
  README.md
Labels: Ready-to-Merge

#12744 Remove use_task_pages_api feature toggle now that all users have it enabled
  app/controllers/organizations/tasks_controller.rb
  app/controllers/tasks_controller.rb
  app/models/queue_config.rb
  app/models/queues/generic_queue.rb
  app/models/representative.rb
  app/serializers/work_queue/organization_task_serializer.rb
  spec/controllers/organizations/tasks_controller_spec.rb
  spec/feature/hearings/change_hearing_disposition_spec.rb
  spec/feature/queue/bulk_task_assignment_spec.rb
  spec/feature/queue/task_queue_spec.rb
  spec/models/queue_config_spec.rb
Labels: Ready-to-Merge

#12767 Message user about first job failure after 24 hours
  app/models/claim_review.rb
  app/models/concerns/asyncable.rb
  app/services/asyncable_job_messaging.rb
  app/services/asyncable_jobs_reporter.rb
  spec/feature/inbox/inbox_spec.rb
  spec/services/asyncable_job_messaging.rb
  spec/services/asyncable_job_messaging_spec.rb
Labels: Ready-to-Merge

#12790 Hide Unused Docket Row
  client/app/hearings/components/dailyDocket/DailyDocket.jsx
  client/app/hearings/components/dailyDocket/DailyDocketRow.jsx
  client/app/hearings/components/dailyDocket/DailyDocketRows.jsx
  client/app/hearings/components/dailyDocket/style.js
Labels: Ready-to-Merge

#12798 Only assignee can act on JudgeTasks
  app/models/tasks/judge_task.rb
  spec/models/tasks/judge_task_spec.rb
Labels: Ready-to-Merge

#12787 Validation Error Messages in Virtual Hearing Modal
  client/app/hearings/components/Details.jsx
  client/app/hearings/components/DetailsSections.jsx
  client/app/hearings/components/VirtualHearingModal.jsx
Labels: Ready-to-Merge

#12801 v3 api - fix bad indentation in HLR post example
  app/controllers/api/docs/v3/decision_reviews.yaml
Labels: Ready-to-Merge, lighthouse

#12796 Message user when a job succeeds after 24 hours
  app/models/claim_review.rb
  app/services/asyncable_job_messaging.rb
  spec/feature/inbox/inbox_spec.rb
  spec/services/asyncable_job_messaging_spec.rb
Labels: Ready-to-Merge

#12794 refactor local:destroy and local:build
  lib/tasks/local/build.rake
  lib/tasks/local/destroy.rake
Labels: Ready-to-Merge

#12807 Move has_many job_notes from subclasses into Asyncable
  app/models/board_grant_effectuation.rb
  app/models/concerns/asyncable.rb
  app/models/decision_document.rb
  app/models/decision_review.rb
  app/models/hearings/virtual_hearing_establishment.rb
  app/models/request_issue.rb
  app/models/request_issues_update.rb
  spec/models/concerns/asyncable_spec.rb
Labels: Ready-to-Merge

#12806 UI Bug Fix: Add line-height to usa-alert-text
  client/app/styles/react/_alerts.scss
Labels: Ready-to-Merge

#12788 ETL syncer
  Makefile.example
  app/models/etl/organizations_user.rb
  app/models/etl/record.rb
  app/models/etl/user.rb
  app/models/user.rb
  app/queries/users_updated_since_query.rb
  app/services/etl/appeal_syncer.rb
  app/services/etl/organization_syncer.rb
  app/services/etl/organizations_user_syncer.rb
  app/services/etl/person_syncer.rb
  app/services/etl/syncer.rb
  app/services/etl/user_syncer.rb
  spec/queries/users_updated_since_query_spec.rb
  spec/services/etl/organization_syncer_spec.rb
  spec/services/etl/organizations_user_syncer_spec.rb
  spec/services/etl/person_syncer_spec.rb
  spec/services/etl/syncer_spec.rb
  spec/services/etl/user_syncer_spec.rb
Labels: Ready-to-Merge

#12772 Handle Various Virtual Hearing Confirmation Messages
  app/controllers/hearings_controller.rb
  app/models/hearings/forms/base_hearing_update_form.rb
  app/models/user_alert.rb
  app/services/virtual_hearing_user_alert_builder.rb
  client/COPY.json
  client/app/components/UserAlerts.jsx
  client/app/components/common/actionTypes.js
  client/app/components/common/actions.js
  client/app/components/common/reducers.js
  client/app/hearings/components/Details.jsx
  client/app/hearings/components/dailyDocket/DailyDocket.jsx
  client/app/hearings/components/dailyDocket/DailyDocketRow.jsx
  client/app/hearings/components/dailyDocket/DailyDocketRowInputs.jsx
  client/app/hearings/containers/DailyDocketContainer.jsx
  client/app/hearings/containers/DetailsContainer.jsx
  client/app/hearings/containers/HearingWorksheetContainer.jsx
  client/app/hearings/containers/HearingWorksheetPrintAllContainer.jsx
  spec/controllers/hearings_controller_spec.rb
  spec/feature/hearings/daily_docket/hearing_prep_spec.rb
  spec/feature/hearings/hearing_details_spec.rb
  spec/feature/hearings/virtual_hearings/daily_docket_spec.rb
  spec/feature/hearings/virtual_hearings/hearing_details_spec.rb
Labels: Ready-to-Merge

#12818 Bump React Router to 5.1.x
  client/package.json
  client/yarn.lock
Labels: Ready-to-Merge

#12816 ETL sync appeals tasks
  app/models/etl/appeal.rb
  app/models/etl/record.rb
  app/models/etl/task.rb
  app/models/etl/user.rb
  app/models/veteran.rb
  app/services/etl/task_syncer.rb
  db/etl/migrate/20191126164353_remove_users_vacols_not_null.rb
  db/etl/migrate/20191126203511_add_appeal_timestamps.rb
  db/etl/schema.rb
  spec/feature/queue/colocated_task_queue_spec.rb
  spec/services/etl/appeal_syncer_spec.rb
  spec/services/etl/task_syncer_spec.rb
  spec/services/etl/user_syncer_spec.rb
  spec/support/shared_examples/ama_sql.rb
Labels: Ready-to-Merge

#12820 Fix lodash/underscore import in UserAlerts
  client/app/components/UserAlerts.jsx
Labels: Ready-to-Merge

#12757 ferris & rubaiyat/add veteran and poa email fields
  app/jobs/virtual_hearings/create_conference_job.rb
  app/models/hearings/forms/base_hearing_update_form.rb
  app/serializers/hearings/virtual_hearing_serializer.rb
  client/COPY.json
  client/app/hearings/components/Details.jsx
  client/app/hearings/components/DetailsSections.jsx
  client/app/hearings/components/VirtualHearingLink.jsx
  client/app/hearings/components/VirtualHearingModal.jsx
  client/app/hearings/components/dailyDocket/DailyDocketRow.jsx
  client/app/hearings/components/details/DetailsInputs.jsx
  client/app/hearings/components/details/DetailsOverview.jsx
  client/app/hearings/components/details/HearingTypeDropdown.jsx
  spec/controllers/hearings_controller_spec.rb
  spec/feature/hearings/hearing_details_spec.rb
  spec/feature/hearings/virtual_hearings/daily_docket_spec.rb
  spec/feature/hearings/virtual_hearings/hearing_details_spec.rb
Labels: Ready-to-Merge

#12821 Fix Layout of Certification Footer (Fixes Mult Focused Element Issue)
  client/app/certification/ConfirmCaseDetails.jsx
  client/app/certification/Footer.jsx
Labels: Ready-to-Merge
