Repository department-of-veterans-affairs/caseflow, pull requests merged in 2019-12, with the labels that each got.

#12814 v3 API - fix LegacyAppealsIssue spec
  app/controllers/api/docs/v3/decision_reviews.yaml
Labels: Ready-to-Merge, lighthouse

#12829 ETL sync fixes
  .reek.yml
  app/models/appeal.rb
  app/models/etl/appeal.rb
  app/queries/appeals_updated_since_query.rb
  app/services/etl/appeal_syncer.rb
  app/services/etl/syncer.rb
  app/services/etl/task_syncer.rb
  spec/services/etl/appeal_syncer_spec.rb
  spec/services/etl/task_syncer_spec.rb
Labels: Ready-to-Merge

#12819 Appeal Status Decorator
  app/decorators/appeal_status_api_decorator.rb
  app/decorators/application_decorator.rb
  app/models/api_status_alerts.rb
  app/models/appeal.rb
  app/models/appeal_events.rb
  app/services/api/v2/appeals.rb
  spec/decorators/appeal_status_api_decorator_spec.rb
  spec/models/appeal_spec.rb
  spec/serializers/status_serializer_spec.rb
Labels: Ready-to-Merge

#12823 resend emails when user changes virtual hearin…
  app/models/hearings/forms/base_hearing_update_form.rb
  app/services/virtual_hearing_user_alert_builder.rb
  client/COPY.json
  client/app/hearings/components/dailyDocket/DailyDocketRow.jsx
  client/app/hearings/containers/DailyDocketContainer.jsx
  spec/controllers/hearings_controller_spec.rb
  spec/factories/virtual_hearing.rb
  spec/feature/hearings/virtual_hearings/daily_docket_spec.rb
  spec/feature/hearings/virtual_hearings/hearing_details_spec.rb
Labels: Ready-to-Merge

#12842 Use SimpleDelegator for a delegation pattern
  app/workflows/request_issue_closure.rb
  spec/workflows/request_issue_closure_spec.rb
Labels: Ready-to-Merge

#12844 ETL sync fixes
  Makefile.example
  app/models/etl/appeal.rb
Labels: Ready-to-Merge

#12847 Do not raise FilenumberDoesNotExist during document prefetch
  app/workflows/fetch_documents_for_reader_job.rb
  spec/jobs/fetch_documents_for_reader_user_spec.rb
  spec/workflows/fetch_documents_for_reader_spec.rb
Labels: Ready-to-Merge

#12848 Cleanup feature toggles
  app/services/external_api/vbms_service.rb
Labels: Ready-to-Merge

#12835 Fix bug where Virtual type isn't displayed for legacy virtual hearing
  app/queries/hearing_days_with_virtual_hearings_query.rb
  app/serializers/hearings/hearing_day_serializer.rb
  app/services/hearing_day_range.rb
  spec/controllers/hearings/hearing_day_controller_spec.rb
  spec/factories/legacy_hearing.rb
  spec/feature/hearings/daily_docket/build_hearsched_spec.rb
  spec/models/legacy_hearing_spec.rb
Labels: Ready-to-Merge

#12845 disable hearing dropdowns while async job is running
  client/app/hearings/components/dailyDocket/DailyDocketRow.jsx
  client/app/hearings/components/details/DetailsInputs.jsx
  client/app/hearings/components/details/HearingTypeDropdown.jsx
  spec/feature/hearings/virtual_hearings/daily_docket_spec.rb
  spec/feature/hearings/virtual_hearings/hearing_details_spec.rb
Labels: Ready-to-Merge

#12838 Bug Fix: React refs in EvaluateDecisionView & JudgeCaseQuality
  client/app/queue/caseEvaluation/EvaluateDecisionView.jsx
  client/app/queue/caseEvaluation/JudgeCaseQuality.jsx
Labels: Ready-to-Merge, batteam

#12841 EstablishClaim error logging
  app/jobs/prepare_establish_claim_tasks_job.rb
  app/models/establish_claim.rb
  spec/jobs/prepare_establish_claim_tasks_job_spec.rb
Labels: Ready-to-Merge

#12854 Add inbox messaging for when a job is manually cancelled
  app/models/claim_review.rb
  app/models/job_note.rb
  app/services/asyncable_job_messaging.rb
  spec/services/asyncable_job_messaging_spec.rb
Labels: Ready-to-Merge

#12852 Pass in props to virtual hearing link; make it more similar to the mockup
  app/jobs/virtual_hearings/create_conference_job.rb
  app/serializers/hearings/virtual_hearing_serializer.rb
  client/COPY.json
  client/app/components/RenderFunctions.jsx
  client/app/hearings/components/Details.jsx
  client/app/hearings/components/DetailsSections.jsx
  client/app/hearings/components/VirtualHearingLink.jsx
  client/app/hearings/components/dailyDocket/DailyDocketRow.jsx
  client/app/hearings/components/dailyDocket/DailyDocketRowInputs.jsx
  client/app/hearings/components/details/DetailsInputs.jsx
  spec/jobs/virtual_hearings/create_conference_job_spec.rb
Labels: Ready-to-Merge

#12858 Fix ClaimReview cancellation bug in #12854
  app/models/claim_review.rb
Labels: Ready-to-Merge

#12865 rep email can be empty
  client/app/hearings/components/VirtualHearingModal.jsx
Labels: Ready-to-Merge

#12859 Wrap each ETL batch in its own transaction
  app/services/etl/syncer.rb
Labels: Ready-to-Merge

#12878 disable virtual hearings dropdown and text fields for non hearing admins
  client/app/hearings/components/details/DetailsInputs.jsx
Labels: Ready-to-Merge

#12857 Add single_cov gem for local test coverage
  Gemfile
  Gemfile.lock
  README.md
  spec/spec_helper.rb
Labels: Ready-to-Merge

#12837 Add instructions when bulk reassigning tasks
  app/models/task.rb
  app/workflows/bulk_task_reassignment.rb
  client/COPY.json
  spec/workflows/bulk_task_reassignment_spec.rb
Labels: Ready-to-Merge

#12899 Split caseflowdemo env vars into separate file for easier sourcing
  docker-bin/env.sh
  docker-bin/startup.sh
Labels: Ready-to-Merge

#12861 Convert ui_hash to serializers (issues)
  app/controllers/appeals_controller.rb
  app/controllers/claim_review_controller.rb
  app/models/decision_review.rb
  app/models/decision_review_intake.rb
  app/models/ramp_issue.rb
  app/models/ramp_refiling_intake.rb
  app/models/rating.rb
  app/models/rating_issue.rb
  app/models/request_issue.rb
  app/models/serializers/work_queue/decision_review_task_serializer.rb
  app/models/tasks/board_grant_effectuation_task.rb
  app/serializers/ramp_issue_serializer.rb
  app/serializers/rating_issue_serializer.rb
  app/serializers/rating_serializer.rb
  app/serializers/request_issue_serializer.rb
  spec/models/request_issue_spec.rb
Labels: Ready-to-Merge

#12868 remove task's action field references
  app/controllers/tasks/change_type_controller.rb
  app/controllers/tasks_controller.rb
  app/models/task.rb
  app/models/tasks/colocated_task.rb
  app/models/tasks/mail_task.rb
  app/repositories/task_action_repository.rb
  client/app/queue/AddColocatedTaskView.jsx
  client/app/queue/ChangeTaskTypeModal.jsx
  spec/controllers/tasks/change_type_controller_spec.rb
  spec/controllers/tasks_controller_spec.rb
  spec/feature/queue/task_queue_spec.rb
  spec/models/tasks/colocated_task_spec.rb
Labels: Ready-to-Merge

#11711 Count VACOLS requests in tests and simulate latency locally
  app/services/database_request_counter.rb
  config/initializers/vacols_request_spy.rb
  spec/controllers/tasks_controller_spec.rb
Labels: Ready-to-Merge

#12898 implement sort fix with role & tabIndex
  client/app/queue/QueueTable.jsx
Labels: Ready-to-Merge

#12874 Add job logging of exceptions
  app/workflows/fetch_documents_for_reader_job.rb
Labels: Ready-to-Merge

#12904 flakey test fix
  spec/feature/queue/colocated_task_queue_spec.rb
Labels: Ready-to-Merge

#12892 Bump "bgs" Gem to Latest (Adding "Known Errors" Functionality)
  Gemfile
  Gemfile.lock
Labels: Ready-to-Merge

#12906 Reduce ETL SQL calls by 66%
  app/models/etl/task.rb
Labels: Ready-to-Merge

#12900 Fix bug where fake veterans not autobuilt in caseflowdemo
  lib/fakes/bgs_service.rb
Labels: Ready-to-Merge

#12908 ETL appeals sort column
  app/models/appeal.rb
  app/models/etl/appeal.rb
  app/services/bva_appeal_status.rb
  db/etl/migrate/20191209162326_add_appeal_status_sort.rb
  db/etl/schema.rb
  spec/services/bva_appeal_status_spec.rb
Labels: Ready-to-Merge

#12779 Update JudgeTeam methods to use new JudgeTeamRoles
  .reek.yml
  app/models/organizations/judge_team.rb
  app/models/user.rb
  spec/models/judge_team_spec.rb
  spec/models/organizations/judge_team_spec.rb
Labels: Ready-to-Merge

#12909 Distribution & docket batch size updated with new attorney logic
  app/models/distribution.rb
  app/models/docket_coordinator.rb
  app/models/judge_team_role.rb
Labels: Ready-to-Merge

#12911 fix make migrate
  Makefile.example
Labels: Ready-to-Merge

#12921 hotfix for colocated action count mismatch
  app/repositories/task_action_repository.rb
Labels: Ready-to-Merge

#12923 Add Credentials to Production Configs
  Gemfile
  Gemfile.lock
  config/environments/demo.rb
  config/environments/production.rb
  config/environments/staging.rb
Labels: Ready-to-Merge

#12915 AMA Quality Review percentage update & cap
  app/models/judge_case_review.rb
  app/models/quality_review_case_selector.rb
  app/models/tasks/quality_review_task.rb
  spec/models/quality_review_case_selector_spec.rb
Labels: Ready-to-Merge

#12936 Fix a Higher-Level review test broken because of date
  spec/feature/intake/higher_level_review_spec.rb
Labels: Ready-to-Merge

#12914 Convert ui_hash to serializers (tasks and other)
  app/controllers/asyncable_jobs_controller.rb
  app/models/decision_review.rb
  app/models/intake.rb
  app/models/job_note.rb
  app/models/ramp_issue.rb
  app/models/rating.rb
  app/models/rating_issue.rb
  app/models/relationship.rb
  app/models/request_issue.rb
  app/serializers/intake/job_note_serializer.rb
  app/serializers/intake/ramp_issue_serializer.rb
  app/serializers/intake/rating_issue_serializer.rb
  app/serializers/intake/rating_serializer.rb
  app/serializers/intake/relationship_serializer.rb
  app/serializers/intake/request_issue_serializer.rb
  app/views/asyncable_jobs/show.html.erb
  spec/models/relationship_spec.rb
Labels: Ready-to-Merge

#12922 Clean up feature toggles
  app/views/queue/index.html.erb
  client/app/queue/CaseTitleDetails.jsx
  client/app/queue/JudgeAssignTaskListView.jsx
  client/app/queue/QueueApp.jsx
  client/app/queue/components/ActionsDropdown.jsx
  client/app/queue/components/AssignWidget.jsx
  client/app/queue/uiReducer/uiActions.js
  client/app/queue/uiReducer/uiConstants.js
  client/app/queue/uiReducer/uiReducer.js
Labels: Ready-to-Merge

#12924 Enable caseflowdemo caching for fakes, etc
  docker-bin/startup.sh
Labels: Ready-to-Merge

#12918 Add message for editing a non-established claim review
  app/controllers/claim_review_controller.rb
  app/models/claim_review.rb
  client/app/intake/constants.js
  client/app/intake/pages/addIssues.jsx
  client/app/intakeEdit/IntakeEditFrame.jsx
  spec/feature/intake/higher_level_review/edit_spec.rb
  spec/feature/intake/supplemental_claim/edit_spec.rb
  spec/feature/non_comp/dispositions_spec.rb
Labels: Ready-to-Merge

#12930 Bump papertrail version
  Gemfile
  Gemfile.lock
  config/initializers/paper_trail.rb
  spec/services/appeal_task_history_spec.rb
Labels: Ready-to-Merge

#12946 Security Fix | ws
  client/package.json
  client/yarn.lock
Labels: Ready-to-Merge

#12938 Allow lit support team members to create mail tasks
  app/models/organization.rb
  app/models/organizations/litigation_support.rb
  app/models/organizations/mail_team.rb
  app/models/tasks/root_task.rb
  spec/models/tasks/root_task_spec.rb
Labels: Ready-to-Merge

#12950 search for appeal with both ssn and file_number
  app/services/appeal_finder.rb
  spec/controllers/appeals_controller_spec.rb
  spec/feature/queue/search_spec.rb
Labels: Ready-to-Merge

#12962 Set statement_timeout longer for FK and index migrations
  db/migrate/20191206024319_reference_legacy_issue_in_legacy_issue_optins.rb
Labels: Ready-to-Merge

#12957 New Selenium webdriver syntax
  spec/support/capybara.rb
Labels: Ready-to-Merge

#12953 Hide inbox messages older than 120 days by default
  app/models/message.rb
  app/services/inbox_messages.rb
  client/app/inbox/pages/InboxPage.jsx
  spec/feature/inbox/inbox_spec.rb
  spec/services/inbox_messages_spec.rb
Labels: Ready-to-Merge

#12965 Return a nil end_product_code when request issue closed status is ineligible
  app/models/request_issue.rb
  spec/models/request_issue_spec.rb
Labels: Ready-to-Merge, foxtrot

#12956 Remove old style hold code
  app/controllers/tasks_controller.rb
  app/models/queues/generic_queue.rb
  app/models/task.rb
  app/models/tasks/hearing_admin_action_task.rb
  app/models/tasks/timed_hold_task.rb
  app/sql/ama-tasks.sql
  client/app/queue/ColocatedPlaceHoldView.jsx
  client/app/queue/QueueApp.jsx
  db/seeds.rb
  spec/controllers/asyncable_jobs_controller_spec.rb
  spec/controllers/tasks_controller_spec.rb
  spec/factories/task.rb
  spec/feature/queue/attorney_queue_spec.rb
  spec/feature/queue/colocated_task_queue_spec.rb
  spec/feature/queue/task_queue_spec.rb
  spec/models/queues/generic_queue_spec.rb
  spec/models/serializers/work_queue/task_serializer_spec.rb
  spec/models/task_spec.rb
  spec/models/tasks/assign_hearing_disposition_task_spec.rb
  spec/models/tasks/colocated_task_spec.rb
  spec/models/tasks/distribution_task_spec.rb
  spec/models/tasks/generic_task_spec.rb
  spec/models/tasks/timed_hold_task_spec.rb
  spec/workflows/bulk_task_reassignment_spec.rb
Labels: Ready-to-Merge

#12964 Drop on_hold_duration column
  db/migrate/20191213173125_remove_on_hold_duration_from_tasks.rb
  db/schema.rb
Labels: Ready-to-Merge

#12860 Add POA column to assign hearing table
  app/views/hearings/index.html.erb
  client/app/hearings/HearingsApp.jsx
  client/app/hearings/components/assignHearings/AssignHearings.jsx
  client/app/hearings/components/assignHearings/AssignHearingsTable.jsx
  client/app/hearings/components/assignHearings/AssignHearingsTabs.jsx
  client/app/hearings/containers/AssignHearingsContainer.jsx
  client/app/queue/CaseTitle.jsx
  client/app/queue/PowerOfAttorneyDetail.jsx
  client/app/queue/reducers.js
Labels: Ready-to-Merge

#12910 Task tree endpoint
  app/assets/javascripts/task-tree.js
  app/controllers/appeals_controller.rb
  app/models/concerns/prints_task_tree.rb
  app/views/layouts/_head.html.erb
  app/views/layouts/_head_google_analytics.html.erb
  app/views/layouts/_head_new_relic.html.erb
  app/views/layouts/_head_sentry.html.erb
  app/views/layouts/application.html.erb
  app/views/layouts/plain_application.html.erb
  app/views/queue/task_tree.html.erb
  client/app/styles/app.scss
  client/app/styles/queue/_task_tree.scss
  config/initializers/assets.rb
  config/routes.rb
  spec/controllers/appeals_controller_spec.rb
  spec/feature/queue/task_tree_spec.rb
  spec/models/appeal_spec.rb
  spec/models/legacy_appeal_spec.rb
Labels: Ready-to-Merge

#12925 raise error when creating second open JudgeDecisionReviewTask
  .reek.yml
  app/models/tasks/judge_decision_review_task.rb
  lib/caseflow/error.rb
  spec/models/tasks/judge_task_spec.rb
  spec/workflows/bulk_task_reassignment_spec.rb
Labels: Ready-to-Merge

#12704 Webpack 4
  .circleci/config.yml
  .nvmrc
  client/.babelrc
  client/app/index.js
  client/app/queue/CaseDetailsLink.jsx
  client/app/queue/utils.js
  client/babel.config.js
  client/package.json
  client/test/helpers/AsyncTests.js
  client/test/node/reader/DecisionReviewer-skip.js
  client/test/node/register.js
  client/test/node/setup.js
  client/webpack.config.js
  client/webpack.hot.config.js
  client/yarn.lock
Labels: Ready-to-Merge

#12972 ETL syncer job
  app/controllers/api/v1/jobs_controller.rb
  app/jobs/etl_builder_job.rb
  app/models/etl/organization.rb
  app/services/etl/builder.rb
  app/services/etl/syncer.rb
  db/etl/migrate/20191213194037_add_task_id_index.rb
  db/etl/schema.rb
  spec/feature/hearings/daily_docket/build_hearsched_spec.rb
  spec/feature/queue/ama_queue_spec.rb
  spec/feature/queue/task_queue_spec.rb
  spec/jobs/etl_builder_job_spec.rb
  spec/services/etl/builder_spec.rb
Labels: Ready-to-Merge

#12978 Tweak copy for a few async message types
  app/services/asyncable_job_messaging.rb
Labels: Ready-to-Merge

#12990 update test to ignore array order
  spec/services/judge_team_role_checker_spec.rb
Labels: Flaky test, Ready-to-Merge, tech-improvement

#12984 show appropriate alerts on hearing details and daily docket
  app/models/hearings/forms/base_hearing_update_form.rb
  app/models/hearings/forms/hearing_update_form.rb
  spec/feature/hearings/hearing_details_spec.rb
  spec/feature/hearings/virtual_hearings/daily_docket_spec.rb
Labels: Ready-to-Merge

#12905 Add status field to organizations.
  app/models/organization.rb
  client/constants/ORGANIZATION_STATUSES.json
  db/etl/migrate/20191212221851_org_status_change.rb
  db/etl/migrate/20191212222617_org_status_default.rb
  db/etl/schema.rb
  db/migrate/20191216190943_add_status_to_organizations.rb
  db/migrate/20191216191111_add_default_value_to_organization_status.rb
  db/schema.rb
  spec/models/organization_spec.rb
Labels: Ready-to-Merge

#12948 Convert ui_hash to serializers (decision review files)
  app/models/appeal.rb
  app/models/claim_review.rb
  app/models/decision_issue.rb
  app/models/decision_review.rb
  app/models/higher_level_review.rb
  app/models/supplemental_claim.rb
  app/serializers/intake/appeal_serializer.rb
  app/serializers/intake/claim_review_serializer.rb
  app/serializers/intake/decision_issue_serializer.rb
  app/serializers/intake/decision_review_serializer.rb
  app/serializers/intake/higher_level_review_serializer.rb
  app/serializers/intake/supplemental_claim_serializer.rb
Labels: Ready-to-Merge

#12986 Looking at flakes
  spec/feature/queue/ama_queue_spec.rb
  spec/feature/queue/task_queue_spec.rb
Labels: Ready-to-Merge

#13000 Include vet file numbers in async job labeling for Inbox
  app/models/claim_review.rb
  app/models/concerns/asyncable.rb
  app/services/asyncable_job_messaging.rb
  spec/services/asyncable_job_messaging_spec.rb
Labels: Ready-to-Merge

#12992 Add missing ep codes for 930 corrections on HLR DTA PMC supplemental claims
  app/workflows/end_product_code_selector.rb
  spec/workflows/end_product_code_selector_spec.rb
Labels: Ready-to-Merge

#12998 Fix URL for POA Email
  app/views/virtual_hearing_mailer/_representative_confirmation.html.erb
  app/views/virtual_hearing_mailer/_representative_updated_time_confirmation.html.erb
Labels: Ready-to-Merge

#12983 Disallow the assignment of tasks to inactive users
  .reek.yml
  app/models/round_robin_task_distributor.rb
  app/models/task.rb
  app/models/tasks/abstract_motion_to_vacate_task.rb
  app/models/tasks/judge_sign_motion_to_vacate_task.rb
  lib/caseflow/error.rb
  spec/models/round_robin_task_distributor_spec.rb
  spec/models/task_spec.rb
Labels: Ready-to-Merge

#13004 ETL schema for attorney case reviews, decision issues
  app/models/etl/attorney_case_review.rb
  app/models/etl/decision_issue.rb
  app/models/etl/record.rb
  app/models/etl/task.rb
  app/services/etl/attorney_case_review_syncer.rb
  app/services/etl/decision_issue_syncer.rb
  db/etl/migrate/20191217193046_create_attorney_case_reviews.rb
  db/etl/migrate/20191217202614_create_decision_issues.rb
  db/etl/schema.rb
  db/migrate/20191217215216_add_index_decision_issues_disposition.rb
  db/schema.rb
  spec/services/etl/attorney_case_review_syncer_spec.rb
  spec/services/etl/decision_issue_syncer_spec.rb
Labels: Ready-to-Merge

#13010 Update copy for legacy issue opt-in selection
  client/COPY.json
  client/app/intake/components/LegacyOptInApproved.jsx
  spec/feature/intake/higher_level_review_spec.rb
  spec/support/intake_helpers.rb
Labels: Ready-to-Merge

#13016 Add AttorneyCaseReview, DecisionIssue to ETL::Builder
  app/services/etl/builder.rb
Labels: Ready-to-Merge

#13014 Remove Whitespace in Virtual Hearing Link
  client/app/hearings/components/VirtualHearingLink.jsx
Labels: Ready-to-Merge

#13019 Do not block distribution when one fails
  app/workflows/create_judge_assign_tasks_for_appeals.rb
  app/workflows/hearing_request_case_distributor.rb
  spec/models/dockets/hearing_request_docket_spec.rb
Labels: Ready-to-Merge

#13026 Upgrade rack gem for security fix
  Gemfile.lock
Labels: Ready-to-Merge

#13028 Have LetsEncrypt for demo using NGINX
  docker-compose-demo.yml
  local/nginx/conf.d/default.conf
  local/nginx/config/nginx/site-confs/default
Labels: Ready-to-Merge

#13022 Use AMA_DOCKET type constants over strings
  db/seeds.rb
  spec/factories/cached_appeals.rb
  spec/feature/api/v2/appeals_spec.rb
  spec/feature/intake/appeal/edit_spec.rb
  spec/feature/intake/appeal_spec.rb
  spec/feature/intake/ramp_refiling_spec.rb
  spec/feature/queue/case_details_spec.rb
  spec/models/ramp_election_spec.rb
  spec/models/ramp_refiling_spec.rb
  spec/models/tasks/evidence_submission_window_task_spec.rb
  spec/models/tasks/special_case_movement_spec.rb
  spec/models/tasks/translation_task_spec.rb
  spec/support/intake_helpers.rb
Labels: Ready-to-Merge

#13013 Add virtual hearing type to daily docket
  client/app/hearings/components/dailyDocket/DailyDocketRow.jsx
  client/app/hearings/components/dailyDocket/DailyDocketRowDisplayText.jsx
  client/app/hearings/components/dailyDocket/DailyDocketRows.jsx
Labels: Ready-to-Merge

#13029 Fix flakey test
  spec/feature/queue/ama_queue_spec.rb
  spec/workflows/initial_tasks_factory_spec.rb
Labels: Ready-to-Merge

#13020 ETL::OrganizationsUser sync by unique cols index
  app/models/etl/organizations_user.rb
  spec/models/appeal_spec.rb
  spec/services/etl/appeal_syncer_spec.rb
  spec/support/database_cleaner.rb
Labels: Ready-to-Merge

#13036 increase default proxy buffer sizes
  local/nginx/config/nginx/site-confs/default
Labels: Ready-to-Merge

#13012 Always create a job note for Inbox-worthy fails and successes
  app/services/asyncable_job_messaging.rb
  spec/services/asyncable_job_messaging_spec.rb
Labels: Ready-to-Merge

#13040 Increase number of cases sent to QualityReview
  app/models/quality_review_case_selector.rb
  spec/models/quality_review_case_selector_spec.rb
Labels: Ready-to-Merge

#13038 Remove PUSHGATEWAY_HEALTHCHECK
  app/controllers/health_checks_controller.rb
  config/environments/staging.rb
  config/environments/test.rb
  spec/requests/health_checks_spec.rb
Labels: Ready-to-Merge

#13032 Remove the last bits of generic task from the code
  db/seeds.rb
  spec/controllers/asyncable_jobs_controller_spec.rb
  spec/controllers/organizations/task_pages_controller_spec.rb
  spec/controllers/tasks/end_hold_controller_spec.rb
  spec/controllers/tasks/place_hold_controller_spec.rb
  spec/controllers/tasks_controller_spec.rb
  spec/factories/task.rb
  spec/feature/queue/ama_queue_spec.rb
  spec/feature/queue/task_queue_spec.rb
  spec/models/appeal_spec.rb
  spec/models/legacy_appeal_spec.rb
  spec/models/organization_spec.rb
  spec/models/queue_config_spec.rb
  spec/models/queue_tabs/organization_assigned_tasks_tab_spec.rb
  spec/models/queue_tabs/organization_completed_tasks_tab_spec.rb
  spec/models/queue_tabs/organization_on_hold_tasks_tab_spec.rb
  spec/models/queue_tabs/organization_tracking_tasks_tab_spec.rb
  spec/models/queue_tabs/organization_unassigned_tasks_tab_spec.rb
  spec/models/serializers/work_queue/task_serializer_spec.rb
  spec/models/task_filter_spec.rb
  spec/models/task_pager_spec.rb
  spec/models/task_sorter_spec.rb
  spec/models/task_spec.rb
  spec/models/task_timer_spec.rb
  spec/models/tasks/generic_task_spec.rb
  spec/models/tasks/mail_task_spec.rb
  spec/models/tasks/quality_review_task_spec.rb
  spec/models/tasks/root_task_spec.rb
  spec/models/tasks/timed_hold_task_spec.rb
  spec/repositories/task_action_repository_spec.rb
  spec/services/untracked_legacy_appeals_checker_spec.rb
  spec/sql/timed_hold_task_sql_spec.rb
Labels: Ready-to-Merge

#12981 Display "Virtual" hearing type on worksheet, and case details hearings list
  app/serializers/hearings/appeal_hearing_serializer.rb
  app/serializers/hearings/hearing_day_serializer.rb
  client/COPY.json
  client/app/hearings/components/dailyDocket/DailyDocketPrinted.jsx
  client/app/hearings/components/hearingWorksheet/WorksheetHeader.jsx
  client/app/queue/CaseHearingsDetail.jsx
  client/app/queue/utils.js
Labels: Ready-to-Merge

#12815 API v3 - contestable issues endpoint
  app/controllers/api/v3/base_controller.rb
  app/controllers/api/v3/decision_review/contestable_issues_controller.rb
  app/controllers/api/v3/decision_review/intake_statuses_controller.rb
  app/models/contestable_issue.rb
  app/serializers/api/v3/contestable_issue_serializer.rb
  config/routes.rb
  spec/models/contestable_issue_spec.rb
  spec/requests/api/v3/decision_review/contestable_issues_controller_spec.rb
Labels: Ready-to-Merge, lighthouse

#13025 Add cached user attributes from VACOLS
  app/models/etl/user.rb
  db/etl/migrate/20191218214351_add_more_cached_user_attributes.rb
  db/etl/schema.rb
  db/migrate/20191218211421_add_more_cached_user_attributes.rb
  db/schema.rb
Labels: Ready-to-Merge

#13030 Add async job copy to Intake Completed screen
  client/app/intake/pages/decisionReviewIntakeCompleted.jsx
  spec/feature/intake/appeal_spec.rb
  spec/feature/intake/higher_level_review_spec.rb
  spec/feature/intake/supplemental_claim_spec.rb
Labels: Ready-to-Merge

#13039 Add index to document_views.user_id
  db/migrate/20191219155741_add_user_id_index_document_views.rb
  db/schema.rb
Labels: Ready-to-Merge

#12993 Bump Frontend Deps 2019-12
  client/app/hearings/components/VirtualHearingModal.jsx
  client/app/hearings/components/dailyDocket/DailyDocketRowDisplayText.jsx
  client/app/hearings/components/modalForms/HearingTime.jsx
  client/app/hearings/utils.js
  client/app/util/DateUtil.js
  client/package.json
  client/yarn.lock
Labels: Ready-to-Merge

#13008 Move task tree to its own controller
  app/controllers/appeals_controller.rb
  app/controllers/task_tree_controller.rb
  app/models/appeal.rb
  app/views/queue/task_tree.html.erb
  app/views/task_tree/show.html.erb
  client/app/styles/_task_tree.scss
  client/app/styles/app.scss
  client/app/styles/queue/_task_tree.scss
  config/routes.rb
  spec/controllers/appeals_controller_spec.rb
  spec/controllers/task_tree_controller_spec.rb
  spec/feature/task_tree_spec.rb
Labels: Ready-to-Merge

#13031 Allow PreRoutingColocatedTasks to be reassigned
  app/models/tasks/colocated_task.rb
  spec/controllers/tasks/change_type_controller_spec.rb
  spec/models/tasks/colocated_task_spec.rb
Labels: Ready-to-Merge

#13042 Add more models that refer to Users
  .reek.yml
  app/services/user_reporter.rb
Labels: Ready-to-Merge

#13044 Do not use random strings in sort tests
  spec/models/task_pager_spec.rb
Labels: Ready-to-Merge

#13045 Add virtual hearing calendar invites to email
  .reek.yml
  Gemfile
  Gemfile.lock
  app/helpers/virtual_hearings/calendar_template_helper.rb
  app/jobs/virtual_hearings/send_email.rb
  app/mailers/virtual_hearing_mailer.rb
  app/models/hearings/virtual_hearing.rb
  app/models/mail_recipient.rb
  app/services/virtual_hearings/calendar_service.rb
  app/views/virtual_hearing_mailer/calendar_events/judge_confirmation_event_description.text.erb
  app/views/virtual_hearing_mailer/calendar_events/representative_changed_to_video_event_description.text.erb
  app/views/virtual_hearing_mailer/calendar_events/representative_confirmation_event_description.text.erb
  app/views/virtual_hearing_mailer/calendar_events/veteran_changed_to_video_event_description.text.erb
  app/views/virtual_hearing_mailer/calendar_events/veteran_confirmation_event_description.text.erb
  app/views/virtual_hearing_mailer/cancellation.html.erb
  app/views/virtual_hearing_mailer/confirmation.html.erb
  app/views/virtual_hearing_mailer/updated_time_confirmation.html.erb
  spec/mailers/virtual_hearing_mailer_spec.rb
Labels: Ready-to-Merge
