Repository department-of-veterans-affairs/caseflow, pull requests merged in 2019-05, with the labels that each got.

#10585 Add Link to Hearing Schedule Judge View
  client/app/hearings/Dockets.jsx
  spec/feature/hearing_prep/daily_docket_spec.rb
Labels: In-Progress, Ready-to-Merge

#10637 Use new facols docker image 20190502
  .circleci/config.yml
  config/database.yml
  lib/tasks/local/vacols.rake
Labels: In-Progress

#10559 Add due process remand reason
  client/app/queue/components/IssueRemandReasonsOptions.jsx
  client/constants/AMA_REMAND_REASONS_BY_ID.json
  spec/models/attorney_case_review_spec.rb
Labels: In-Progress, Ready-to-Merge

#10591 Disable MissingSafeMethod and TooManyStatements
  .reek.yml
Labels: In-Progress, Ready-to-Merge

#10622 Fix ActionController::ParameterMissing bugs
  client/app/certification/CancelCertificationModal.jsx
  client/app/hearings/actions/Dockets.js
  spec/feature/certification/cancel_certification_spec.rb
  spec/feature/hearing_prep/hearing_worksheet_spec.rb
Labels: In-Progress, Ready-to-Merge

#10634 Non Comp | Quick copy change |
  client/COPY.json
  client/app/nonComp/components/RecordRequest.jsx
  spec/feature/non_comp/record_requests_spec.rb
Labels: In-Progress, Ready-to-Merge

#10579 Linux/Ubuntu install directions
  LINUX_SETUP_AND_INSTALL.md
  README.md
Labels: In-Progress, Ready-to-Merge

#10603 Move worksheet link on case hearing component to newline
  client/app/queue/CaseHearingsDetail.jsx
Labels: In-Progress, Ready-to-Merge

#10606 Add VBMSError::DocumentNotFound
  app/exceptions/vbms_error.rb
Labels: In-Progress, Ready-to-Merge

#10628 Add document types to VBMSService
  app/services/external_api/vbms_service.rb
Labels: In-Progress, Ready-to-Merge

#10642 Add spacing below flash alert
  client/app/nonComp/components/Alerts.jsx
Labels: In-Progress, Ready-to-Merge

#10602 Ensure response is JSON before parsing
  client/app/components/LoadingDataDisplay.jsx
Labels: In-Progress, Ready-to-Merge

#10624 Only legacy case reviews should be selected for legacy QR
  app/models/judge_case_review.rb
  spec/models/judge_case_review_spec.rb
Labels: In-Progress, Ready-to-Merge

#10604 Organization url & name updates
  app/models/organization.rb
  spec/controllers/organizations/tasks_controller_spec.rb
  spec/feature/queue/ama_queue_spec.rb
  spec/models/appeal_spec.rb
  spec/models/hearing_spec.rb
  spec/models/judge_team_spec.rb
  spec/models/legacy_appeal_spec.rb
  spec/models/organization_spec.rb
  spec/models/organizations/field_vso_spec.rb
  spec/models/representative_spec.rb
  spec/models/task_spec.rb
Labels: In-Progress, Ready-to-Merge

#10635 Removing judges' reschedule permissions
  app/models/tasks/disposition_task.rb
Labels: In-Progress, Ready-to-Merge

#10626 Appeal Status: updating how get the scheduled hearing
  app/models/appeal.rb
Labels: In-Progress, Ready-to-Merge

#10638 Appeal Status: Fixing a typo in serializer
  app/models/serializers/v2/appeal_status_serializer.rb
Labels: In-Progress, Ready-to-Merge

#10636 Search for user by user pg id instead of css id
  app/models/user.rb
  spec/models/user_spec.rb
Labels: In-Progress, Ready-to-Merge

#10611 Appeal Status API bug fix and added logging
  app/models/issue.rb
  spec/models/issue_spec.rb
Labels: In-Progress, Ready-to-Merge

#10646 No show task instructions
  app/models/tasks/disposition_task.rb
  spec/models/tasks/disposition_task_spec.rb
Labels: In-Progress, Ready-to-Merge

#10397 Rename issue_category to nonrating_issue_category
  app/models/decision_issue.rb
  app/models/request_issue.rb
  app/models/supplemental_claim.rb
  client/app/intake/util/issues.js
  db/migrate/20190430225016_remove_issue_category_from_request_issue.rb
  db/schema.rb
  db/seeds.rb
  spec/factories/request_issue.rb
  spec/feature/intake/appeal/edit_spec.rb
  spec/feature/intake/appeal_spec.rb
  spec/feature/intake/higher_level_review/edit_spec.rb
  spec/feature/intake/higher_level_review_spec.rb
  spec/feature/intake/nonrating_request_issue_modal_spec.rb
  spec/feature/intake/supplemental_claim/edit_spec.rb
  spec/feature/intake/supplemental_claim_spec.rb
  spec/models/appeal_intake_spec.rb
  spec/models/claim_review_spec.rb
  spec/models/decision_issue_spec.rb
  spec/models/higher_level_review_spec.rb
  spec/models/request_issue_spec.rb
  spec/models/request_issues_update_spec.rb
  spec/support/intake_helpers.rb
Labels: In-Progress, Ready-to-Merge

#10616 Rename decision issue profile and promulgation date in code
  app/models/board_grant_effectuation.rb
  app/models/contestable_issue.rb
  app/models/decision_issue.rb
  app/models/request_issue.rb
  app/models/supplemental_claim.rb
  db/seeds.rb
  spec/factories/request_issue.rb
  spec/feature/intake/higher_level_review_spec.rb
  spec/models/appeal_spec.rb
  spec/models/board_grant_effectuation_spec.rb
  spec/models/contestable_issue_spec.rb
  spec/models/decision_issue_spec.rb
  spec/models/decision_review_spec.rb
  spec/models/higher_level_review_spec.rb
  spec/models/request_issue_spec.rb
  spec/models/supplemental_claim_spec.rb
Labels: In-Progress, Ready-to-Merge

#10631 Do not show canceled jobs in Async jobs page
  app/models/concerns/asyncable.rb
  spec/services/asyncable_jobs_spec.rb
Labels: In-Progress, Ready-to-Merge

#10648 Sorts appeals so job definitely pulls different appeals each run
  app/jobs/fetch_hearing_locations_for_veterans_job.rb
  spec/jobs/fetch_hearing_locations_for_veterans_job_spec.rb
Labels: In-Progress, Ready-to-Merge

#10605 Enforcing Organization URL uniqueness at the db level
  db/migrate/20190430151227_add_unique_constraint_to_organization_url.rb
  db/migrate/20190430152338_add_comments_to_organization_fields.rb
  db/schema.rb
Labels: In-Progress, Ready-to-Merge

#10580 Exclude TrackVeteranTasks from Appeal.assigned_to_location determination
  app/models/appeal.rb
  app/models/task.rb
  spec/models/appeal_spec.rb
Labels: Ready-to-Merge

#10612 Add PrivacyActTask class for Privacy Team tasks.
  app/controllers/tasks_controller.rb
  app/models/task.rb
  app/models/tasks/privacy_act_task.rb
  spec/factories/task.rb
  spec/models/tasks/privacy_act_task_spec.rb
Labels: Ready-to-Merge

#10653 Do not select child classes of DispositionTasks in HearingDispositionChangeJob
  .reek.yml
  app/jobs/hearing_disposition_change_job.rb
  spec/jobs/hearing_disposition_change_job_spec.rb
Labels: In-Progress, Ready-to-Merge

#10651 Remove renamed decision issue fields
  db/migrate/20190503191516_remove_renamed_decision_issue_columns.rb
  db/schema.rb
Labels: In-Progress, Ready-to-Merge

#10618 Always show AssignHearingsTabs and show error message if no veterans to schedule
  client/COPY.json
  client/app/hearingSchedule/components/AssignHearings.jsx
  client/app/hearingSchedule/components/AssignHearingsTabs.jsx
  client/app/hearingSchedule/containers/AssignHearingsContainer.jsx
Labels: In-Progress, Ready-to-Merge

#10588 Remove Hearing Schedule Time Query Parameter
  client/app/hearingSchedule/components/AssignHearingsTabs.jsx
  client/app/queue/CaseDetailsView.jsx
  client/app/queue/components/AssignHearingModal.jsx
  client/app/queue/uiReducer/uiReducer.js
Labels: In-Progress, Ready-to-Merge

#10138 Add modal for batch assigning tasks
  app/controllers/organizations/users_controller.rb
  client/app/components/Alert.jsx
  client/app/queue/OrganizationQueue.jsx
  client/app/queue/QueueActions.js
  client/app/queue/components/BulkAssignModal.jsx
  client/app/queue/components/TaskTable.jsx
  client/app/queue/constants.js
  client/app/queue/reducers.js
  client/app/styles/_table.scss
  client/constants/ORGANIZATION_NAMES.json
  client/test/karma/queue/BulkAssignModal-test.js
Labels: In-Progress, Ready-to-Merge

#10584 Update gems with bummr
  .codeclimate.yml
  .rubocop.yml
  Gemfile.lock
  app/controllers/appeals_controller.rb
  app/controllers/claim_review_controller.rb
  app/controllers/dispatch/establish_claims_controller.rb
  app/controllers/distributions_controller.rb
  app/controllers/hearings_controller.rb
  app/controllers/intakes_controller.rb
  app/controllers/reader/documents_controller.rb
  app/helpers/retry_helper.rb
  app/jobs/decision_issue_sync_job.rb
  app/jobs/decision_review_process_job.rb
  app/jobs/end_product_sync_job.rb
  app/jobs/fetch_documents_for_reader_user_job.rb
  app/jobs/start_certification_job.rb
  app/jobs/start_distribution_job.rb
  app/jobs/sync_intake_job.rb
  app/jobs/sync_reviews_job.rb
  app/jobs/task_timer_job.rb
  app/jobs/update_appellant_representation_job.rb
  app/models/appeal_intake.rb
  app/models/claim_review_intake.rb
  app/models/concerns/issue_updater.rb
  app/models/decision_document.rb
  app/models/decision_review.rb
  app/models/distribution.rb
  app/models/end_product.rb
  app/models/end_product_establishment.rb
  app/models/establish_claim.rb
  app/models/intake.rb
  app/models/ramp_election_intake.rb
  app/models/ramp_refiling.rb
  app/models/ramp_refiling_intake.rb
  app/models/tasks/bva_dispatch_task.rb
  app/services/appeal_repository.rb
  app/services/external_api/vbms_service.rb
  app/services/report.rb
  app/workflows/upload_document_to_vbms.rb
  config/application.rb
  config/environments/development.rb
  config/environments/ssh_forwarding.rb
  config/environments/staging.rb
  spec/jobs/hearing_disposition_change_job_spec.rb
  spec/support/capybara.rb
  spec/support/clear_cache.rb
Labels: In-Progress, Ready-to-Merge

#9953 Tweak withdrawn copy
  app/models/appeal.rb
  app/models/serializers/work_queue/appeal_serializer.rb
  client/COPY.json
  client/app/queue/components/TaskRows.jsx
  client/app/queue/utils.js
  spec/models/appeal_spec.rb
Labels: In-Progress, Ready-to-Merge

#10668 Handle more error messages from VA.gov address validator API
  app/services/external_api/va_dot_gov_service.rb
  app/services/va_dot_gov_address_validator.rb
  lib/caseflow/error.rb
  spec/jobs/fetch_hearing_locations_for_veterans_job_spec.rb
Labels: In-Progress, Ready-to-Merge

#10656 Disable Code Climate method line count
  .codeclimate.yml
Labels: In-Progress, Ready-to-Merge

#10675 Only make 1 request for doc counts from efolder
  app/controllers/appeals_controller.rb
  app/services/external_api/efolder_service.rb
  lib/fakes/vbms_service.rb
Labels: In-Progress

#10679 Lowell/reduce efolder requests from queue doc count
  spec/controllers/appeals_controller_spec.rb
Labels: In-Progress, Ready-to-Merge

#10623 Add task column to Attorney Queue view.
  app/models/tasks/attorney_task.rb
  client/COPY.json
  client/app/queue/AttorneyTaskListView.jsx
  spec/feature/queue/attorney_queue_spec.rb
  spec/feature/queue/task_queue_spec.rb
  spec/models/tasks/attorney_task_spec.rb
Labels: In-Progress, Ready-to-Merge

#10650 Users can create change hearing disposition tasks
  app/controllers/tasks_controller.rb
  app/models/task.rb
  app/models/tasks/disposition_task.rb
  app/models/tasks/generic_task.rb
  app/models/tasks/hearing_admin_action_task.rb
  app/models/tasks/hearing_task.rb
  app/models/tasks/no_show_hearing_task.rb
  app/models/tasks/root_task.rb
  app/models/tasks/schedule_hearing_task.rb
  app/models/tasks/transcription_task.rb
  client/COPY.json
  client/app/queue/CreateChangeHearingDispositionTaskModal.jsx
  client/app/queue/QueueApp.jsx
  client/constants/TASK_ACTIONS.json
  config/routes.rb
  spec/controllers/tasks_controller_spec.rb
  spec/factories/task.rb
  spec/feature/hearing_schedule/change_hearing_disposition_spec.rb
  spec/feature/hearing_schedule/daily_docket_spec.rb
  spec/feature/queue/hearings_tasks_spec.rb
  spec/feature/queue/transcription_team_spec.rb
  spec/models/tasks/disposition_task_spec.rb
  spec/models/tasks/generic_task_spec.rb
  spec/models/tasks/hearing_admin_action_task_spec.rb
  spec/models/tasks/hearing_task_spec.rb
  spec/models/tasks/no_show_hearing_task_spec.rb
  spec/models/tasks/root_task_spec.rb
  spec/models/tasks/schedule_hearing_task_spec.rb
Labels: In-Progress, Ready-to-Merge

#10673 Do not show removed reviews in case search
  app/models/claim_review.rb
  app/models/decision_review.rb
  app/workflows/appeals_for_file_number.rb
  app/workflows/case_search_results_for_caseflow_veteran_id.rb
  app/workflows/case_search_results_for_veteran_file_number.rb
  spec/feature/queue/search_spec.rb
  spec/models/claim_review_spec.rb
  spec/models/decision_review_spec.rb
Labels: In-Progress, Ready-to-Merge

#10674 Withdrawal date restrictions
  client/app/components/DateSelector.jsx
  client/app/components/TextField.jsx
  client/app/intake/pages/addIssues.jsx
  client/app/intakeEdit/components/EditButtons.jsx
  client/app/styles/_noncomp.scss
  spec/feature/intake/appeal/edit_spec.rb
Labels: In-Progress, Ready-to-Merge

#10694 Roll back appeal document count changes from #10675
  app/controllers/appeals_controller.rb
  spec/controllers/appeals_controller_spec.rb
Labels: In-Progress

#9338 Update README.md
  README.md
Labels: In-Progress, Ready-to-Merge

#10652 Bat Team documentation
  docs/bat-team.md
Labels: In-Progress, Ready-to-Merge, batteam

#10692 fix flakes
  spec/models/tasks/colocated_task_spec.rb
Labels: In-Progress, Ready-to-Merge

#10654 Add VBMS::ShareExceptionFindRatingData
  app/exceptions/vbms_error.rb
Labels: In-Progress, Ready-to-Merge

#9963 Remove disabled but valid Rubocop offenses
  app/controllers/application_controller.rb
  app/controllers/distributions_controller.rb
  app/controllers/reader/documents_controller.rb
  app/controllers/special_issues_controller.rb
  app/mappers/power_of_attorney_mapper.rb
  app/mappers/zip_code_to_lat_lng_mapper.rb
  app/models/appeal.rb
  app/models/appeal_series.rb
  app/models/appeal_series_issues.rb
  app/models/decision_review.rb
  app/models/decision_review_intake.rb
  app/models/dockets/hearing_request_docket.rb
  app/models/dockets/legacy_docket.rb
  app/models/full_name.rb
  app/models/hearing.rb
  app/models/hearing_day.rb
  app/models/issue.rb
  app/models/legacy_appeal.rb
  app/models/request_issue.rb
  app/models/tasks/generic_task.rb
  app/models/vacols/case.rb
  app/models/vacols/case_docket.rb
  app/models/vacols/note.rb
  app/models/veteran.rb
  app/repositories/queue_repository.rb
  app/services/appeal_repository.rb
  app/services/external_api/efolder_service.rb
  app/services/form8_pdf_service.rb
  app/services/metrics_service.rb
  app/services/va_dot_gov_address_validator.rb
  bin/update
  config.ru
  config/initializers/paper_trail.rb
  lib/caseflow/error.rb
  lib/fakes/bgs_service.rb
  lib/fakes/vbms_service.rb
  lib/generators/vacols/case.rb
  lib/tasks/ci.rake
  lib/tasks/lint.rake
  spec/factories/task.rb
  spec/fake_date_helper.rb
  spec/models/appeal_history_spec.rb
  spec/models/contention_spec.rb
  spec/models/end_product_establishment_spec.rb
Labels: In-Progress, Ready-to-Merge

#10633 Rebuilding Facols from Oracle Base Image
  .circleci/config.yml
  .gitignore
  Makefile.example
  app/models/vacols/actcode.rb
  app/models/vacols/case.rb
  app/models/vacols/case_assignment.rb
  app/models/vacols/case_docket.rb
  app/models/vacols/case_hearing.rb
  app/models/vacols/case_issue.rb
  app/models/vacols/cavc_case_decision.rb
  app/models/vacols/correspondent.rb
  app/models/vacols/decass.rb
  app/models/vacols/decision_quality_review.rb
  app/models/vacols/diary.rb
  app/models/vacols/folder.rb
  app/models/vacols/issref.rb
  app/models/vacols/issue_reference.rb
  app/models/vacols/mail.rb
  app/models/vacols/note.rb
  app/models/vacols/priorloc.rb
  app/models/vacols/remand_reason.rb
  app/models/vacols/representative.rb
  app/models/vacols/staff.rb
  app/models/vacols/travel_board_schedule.rb
  app/models/vacols/vftypes.rb
  app/repositories/queue_repository.rb
  config/database.yml
  docker-compose.yml
  lib/tasks/local/build.rake
  lib/tasks/local/vacols.rake
  local/vacols/Dockerfile
  local/vacols/build_and_push.sh
  local/vacols/build_push.sh
  local/vacols/dockerInitWithSchema.sh
  local/vacols/loadSchema.sh
  local/vacols/setup_vacols.sql
  local/vacols/vacols_copy_1_tablespaces.sql
  local/vacols/vacols_copy_2_tables_dev.sql
  local/vacols/vacols_copy_2_tables_test.sql
  local/vacols/vacols_copy_3_indexes_dev.sql
  local/vacols/vacols_copy_3_indexes_test.sql
  local/vacols/vacols_copy_4_triggers.sql
  local/vacols/vacols_copy_4_triggers_dev.sql
  local/vacols/vacols_copy_4_triggers_test.sql
  local/vacols/vacols_copy_5_functions_dev.sql
  local/vacols/vacols_copy_5_functions_test.sql
  local/vacols/vacols_copy_6_procedure_dev.sql
  local/vacols/vacols_copy_6_procedure_test.sql
  local/vacols/vacols_copy_7_sequences.sql
  local/vacols/vacols_copy_7_sequences_dev.sql
  local/vacols/vacols_copy_7_sequences_test.sql
Labels: In-Progress, Ready-to-Merge

#10284 Add common component for AMA issues
  client/app/components/AmaIssueList.jsx
  client/app/queue/SelectDispositionsView.jsx
  client/app/queue/components/CaseDetailsIssueList.jsx
  client/app/queue/components/ContestedIssues.jsx
  client/app/queue/components/DecisionIssues.jsx
  spec/controllers/tasks_controller_spec.rb
  spec/feature/queue/attorney_checkout_flow_spec.rb
  spec/feature/queue/case_details_spec.rb
  spec/feature/queue/delete_request_issues_spec.rb
Labels: In-Progress, Ready-to-Merge

#10702 Return 'temporarily unavailable' text for all doc counts
  app/controllers/appeals_controller.rb
  spec/controllers/appeals_controller_spec.rb
  spec/feature/queue/ama_queue_spec.rb
  spec/feature/queue/case_details_spec.rb
Labels: In-Progress, Ready-to-Merge

#10705 Revert "Rebuilding Facols from Oracle Base Image (#10633)"
  .circleci/config.yml
  .gitignore
  Makefile.example
  app/models/vacols/actcode.rb
  app/models/vacols/case.rb
  app/models/vacols/case_assignment.rb
  app/models/vacols/case_docket.rb
  app/models/vacols/case_hearing.rb
  app/models/vacols/case_issue.rb
  app/models/vacols/cavc_case_decision.rb
  app/models/vacols/correspondent.rb
  app/models/vacols/decass.rb
  app/models/vacols/decision_quality_review.rb
  app/models/vacols/diary.rb
  app/models/vacols/folder.rb
  app/models/vacols/issref.rb
  app/models/vacols/issue_reference.rb
  app/models/vacols/mail.rb
  app/models/vacols/note.rb
  app/models/vacols/priorloc.rb
  app/models/vacols/remand_reason.rb
  app/models/vacols/representative.rb
  app/models/vacols/staff.rb
  app/models/vacols/travel_board_schedule.rb
  app/models/vacols/vftypes.rb
  app/repositories/queue_repository.rb
  config/database.yml
  docker-compose.yml
  lib/tasks/local/build.rake
  lib/tasks/local/vacols.rake
  local/vacols/Dockerfile
  local/vacols/build_and_push.sh
  local/vacols/build_push.sh
  local/vacols/dockerInitWithSchema.sh
  local/vacols/loadSchema.sh
  local/vacols/setup_vacols.sql
  local/vacols/vacols_copy_1_tablespaces.sql
  local/vacols/vacols_copy_2_tables.sql
  local/vacols/vacols_copy_2_tables_test.sql
  local/vacols/vacols_copy_3_indexes.sql
  local/vacols/vacols_copy_3_indexes_test.sql
  local/vacols/vacols_copy_4_triggers.sql
  local/vacols/vacols_copy_4_triggers_dev.sql
  local/vacols/vacols_copy_4_triggers_test.sql
  local/vacols/vacols_copy_5_functions.sql
  local/vacols/vacols_copy_5_functions_test.sql
  local/vacols/vacols_copy_6_procedure_test.sql
  local/vacols/vacols_copy_6_procedures.sql
  local/vacols/vacols_copy_7_sequences.sql
  local/vacols/vacols_copy_7_sequences_dev.sql
  local/vacols/vacols_copy_7_sequences_test.sql
Labels: In-Progress

#10706 Revert "Revert "Rebuilding Facols from Oracle Base Image (#10633)""
  .circleci/config.yml
  .gitignore
  Makefile.example
  app/models/vacols/actcode.rb
  app/models/vacols/case.rb
  app/models/vacols/case_assignment.rb
  app/models/vacols/case_docket.rb
  app/models/vacols/case_hearing.rb
  app/models/vacols/case_issue.rb
  app/models/vacols/cavc_case_decision.rb
  app/models/vacols/correspondent.rb
  app/models/vacols/decass.rb
  app/models/vacols/decision_quality_review.rb
  app/models/vacols/diary.rb
  app/models/vacols/folder.rb
  app/models/vacols/issref.rb
  app/models/vacols/issue_reference.rb
  app/models/vacols/mail.rb
  app/models/vacols/note.rb
  app/models/vacols/priorloc.rb
  app/models/vacols/remand_reason.rb
  app/models/vacols/representative.rb
  app/models/vacols/staff.rb
  app/models/vacols/travel_board_schedule.rb
  app/models/vacols/vftypes.rb
  app/repositories/queue_repository.rb
  config/application.rb
  config/database.yml
  config/environments/development.rb
  config/environments/test.rb
  docker-compose.yml
  lib/tasks/local/build.rake
  lib/tasks/local/vacols.rake
  local/vacols/Dockerfile
  local/vacols/build_and_push.sh
  local/vacols/build_push.sh
  local/vacols/dockerInitWithSchema.sh
  local/vacols/loadSchema.sh
  local/vacols/setup_vacols.sql
  local/vacols/vacols_copy_1_tablespaces.sql
  local/vacols/vacols_copy_2_tables_dev.sql
  local/vacols/vacols_copy_2_tables_test.sql
  local/vacols/vacols_copy_3_indexes_dev.sql
  local/vacols/vacols_copy_3_indexes_test.sql
  local/vacols/vacols_copy_4_triggers.sql
  local/vacols/vacols_copy_4_triggers_dev.sql
  local/vacols/vacols_copy_4_triggers_test.sql
  local/vacols/vacols_copy_5_functions_dev.sql
  local/vacols/vacols_copy_5_functions_test.sql
  local/vacols/vacols_copy_6_procedure_dev.sql
  local/vacols/vacols_copy_6_procedure_test.sql
  local/vacols/vacols_copy_7_sequences.sql
  local/vacols/vacols_copy_7_sequences_dev.sql
  local/vacols/vacols_copy_7_sequences_test.sql
Labels: In-Progress

#10683 Refresh Veteran address before establishing claim
  app/models/end_product_establishment.rb
  app/models/establish_claim.rb
  app/models/veteran.rb
  spec/models/end_product_establishment_spec.rb
  spec/models/veteran_spec.rb
Labels: In-Progress, Ready-to-Merge

#10710 Reduce number of Efolder retries from 300 to 10
  app/services/external_api/efolder_service.rb
Labels: In-Progress

#10595 Add a rake task and tests for changing task assigned_to in bulk
  lib/tasks/tasks.rake
  spec/lib/tasks/tasks_spec.rb
Labels: In-Progress, Ready-to-Merge

#10711 Make doccount temporarily the empty string
  app/controllers/appeals_controller.rb
  spec/controllers/appeals_controller_spec.rb
Labels: In-Progress, Ready-to-Merge

#10687 End holds set with timed hold tasks
  app/controllers/tasks/end_hold_controller.rb
  app/models/legacy_tasks/legacy_task.rb
  app/models/serializers/work_queue/task_serializer.rb
  app/models/task.rb
  app/models/tasks/disposition_task.rb
  app/models/tasks/hearing_admin_action_task.rb
  app/models/tasks/no_show_hearing_task.rb
  app/models/tasks/schedule_hearing_task.rb
  app/models/tasks/timed_hold_task.rb
  app/models/tasks/transcription_task.rb
  app/repositories/task_action_repository.rb
  client/COPY.json
  client/app/queue/QueueApp.jsx
  client/app/queue/components/EndHoldModal.jsx
  client/constants/TASK_ACTIONS.json
  config/routes.rb
  spec/controllers/tasks/end_hold_controller_spec.rb
  spec/feature/queue/task_queue_spec.rb
  spec/models/serializers/work_queue/task_serializer_spec.rb
  spec/models/task_spec.rb
  spec/models/tasks/timed_hold_task_spec.rb
  spec/repositories/task_action_repository_spec.rb
Labels: In-Progress, Ready-to-Merge

#10682 Allow edit on hearings details for legacy hearing
  app/controllers/hearings_controller.rb
  app/mappers/hearing_mapper.rb
  app/models/hearing_day.rb
  app/models/legacy_hearing.rb
  app/repositories/hearing_repository.rb
  client/app/hearingSchedule/components/Details.jsx
  client/app/hearingSchedule/components/DetailsSections.jsx
  spec/feature/hearing_schedule/hearing_details_spec.rb
  spec/models/hearing_day_spec.rb
Labels: In-Progress, Ready-to-Merge

#10718 Execute build script from anywhere
  lib/tasks/local/build.rake
  local/vacols/build_push.sh
Labels: In-Progress, Ready-to-Merge

#10684 Update multiple phone number error copy
  client/COPY.json
  client/app/components/LoadingDataDisplay.jsx
  client/app/intake/pages/search.jsx
Labels: In-Progress, Ready-to-Merge

#10686 New column for edited contention text
  app/models/request_issue.rb
  client/app/intake/pages/addIssues.jsx
  client/app/intake/util/issues.js
  client/app/styles/_intake.scss
  client/app/styles/_noncomp.scss
  db/migrate/20190509155449_add_edited_description_to_request_issues.rb
  db/schema.rb
  spec/feature/intake/appeal/edit_spec.rb
  spec/feature/intake/higher_level_review/edit_spec.rb
  spec/models/request_issue_spec.rb
Labels: In-Progress, Ready-to-Merge

#10720 Reader null safe bugs
  client/app/reader/AnnotationLayer/AnnotationActions.js
  client/app/reader/PdfViewer.jsx
  client/app/reader/utils.js
Labels: In-Progress, Ready-to-Merge

#10727 Add VBMSError::MissingVeteranIdentifier
  app/exceptions/vbms_error.rb
Labels: In-Progress, Ready-to-Merge

#10726 fix wikipedia link
  docs/bat-team.md
Labels: In-Progress, Ready-to-Merge

#10722 Initial pass of updates on README
  LINUX_SETUP_AND_INSTALL.md
  README.md
  docs/FACOLS.md
Labels: In-Progress, Ready-to-Merge

#10701 Add feedback page, remove env var for feedback and fix spec test
  app/controllers/application_controller.rb
  app/views/application/feedback.html.erb
  app/views/errors/404.html.erb
  client/app/containers/Feedback.jsx
  client/app/index.js
  client/package.json
  client/yarn.lock
  config/environments/demo.rb
  config/environments/development.rb
  config/environments/ssh_forwarding.rb
  config/routes.rb
  spec/feature/send_feedback_spec.rb
Labels: In-Progress, Ready-to-Merge

#10738 Fix regression with var name
  local/vacols/build_push.sh
Labels: In-Progress, Ready-to-Merge

#10725 Add VBMSError::Unknown
  app/exceptions/vbms_error.rb
  spec/models/tasks/colocated_task_spec.rb
Labels: In-Progress, Ready-to-Merge

#10728 Enable all tasks to be placed on timed hold
  app/controllers/tasks/place_hold_controller.rb
  app/models/task.rb
  app/models/tasks/attorney_task.rb
  app/models/tasks/generic_task.rb
  app/models/tasks/informal_hearing_presentation_task.rb
  app/models/tasks/judge_task.rb
  app/models/tasks/privacy_act_task.rb
  app/models/tasks/quality_review_task.rb
  app/models/tasks/schedule_hearing_task.rb
  app/models/tasks/timed_hold_task.rb
  app/models/tasks/transcription_task.rb
  client/app/queue/QueueApp.jsx
  client/app/queue/components/StartHoldModal.jsx
  client/app/queue/constants.js
  client/constants/TASK_ACTIONS.json
  spec/controllers/tasks_controller_spec.rb
  spec/feature/queue/attorney_queue_spec.rb
  spec/feature/queue/task_queue_spec.rb
  spec/models/tasks/generic_task_spec.rb
  spec/models/tasks/informal_hearing_presentation_task_spec.rb
  spec/models/tasks/judge_quality_review_task_spec.rb
  spec/models/tasks/judge_task_spec.rb
  spec/models/tasks/privacy_act_task_spec.rb
Labels: In-Progress, Ready-to-Merge

#10742 mark vbms upstream connect error as transient
  app/exceptions/vbms_error.rb
Labels: In-Progress, Ready-to-Merge

#10745 Rename Quality Review test user
  db/seeds.rb
Labels: In-Progress, Ready-to-Merge

#10719 Use QueueOrganizationDropdown in judge queues
  app/models/user.rb
  client/COPY.json
  client/app/queue/JudgeAssignTaskListView.jsx
  client/app/queue/JudgeDecisionReviewTaskListView.jsx
  client/app/queue/components/QueueJudgeAssignOrReviewDropdown.jsx
  client/app/queue/components/QueueOrganizationDropdown.jsx
  spec/feature/queue/judge_assignment_spec.rb
  spec/models/user_spec.rb
Labels: In-Progress, Ready-to-Merge

#10755 Do not re-parse VBMS errors in BGS wrapper
  app/exceptions/bgs_sync_error.rb
Labels: In-Progress

#10753 Redirect BusinessLine organizations to /decision_reviews
  app/controllers/organizations/tasks_controller.rb
  spec/controllers/organizations/tasks_controller_spec.rb
Labels: In-Progress, Ready-to-Merge

#10743 Save edited contention text
  client/app/components/TextareaField.jsx
  client/app/intake/actions/addIssues.js
  client/app/intake/components/AddedIssue.jsx
  client/app/intake/components/EditContentionTitle.jsx
  client/app/intake/constants.js
  client/app/intake/pages/addIssues.jsx
  client/app/intake/reducers/common.js
  client/app/intake/util/issues.js
  spec/feature/intake/higher_level_review/edit_spec.rb
Labels: In-Progress, Ready-to-Merge

#10757 Hide RootTask from case timeline
  app/models/tasks/root_task.rb
  client/app/queue/components/TaskRows.jsx
  spec/feature/queue/case_details_spec.rb
Labels: In-Progress, Ready-to-Merge

#10734 Make sure detail exists before calling destroy!
  app/models/intake.rb
Labels: In-Progress, Ready-to-Merge

#10746 Add VBMS::UnknownUser error class
  app/exceptions/vbms_error.rb
  spec/exceptions/vbms_error_spec.rb
Labels: In-Progress, Ready-to-Merge

#10721 Remove class method for ama_activation_date, check user in feature to…
  app/models/decision_review.rb
  app/models/request_issue.rb
  lib/fakes/bgs_service.rb
  spec/feature/intake/appeal/edit_spec.rb
  spec/feature/intake/appeal_spec.rb
  spec/feature/intake/higher_level_review/edit_spec.rb
  spec/feature/intake/higher_level_review_spec.rb
  spec/feature/intake/supplemental_claim/edit_spec.rb
  spec/feature/intake/supplemental_claim_spec.rb
  spec/models/appeal_spec.rb
  spec/models/claim_review_spec.rb
  spec/models/higher_level_review_spec.rb
  spec/models/request_issue_spec.rb
  spec/models/supplemental_claim_spec.rb
  spec/support/date_time_helper.rb
Labels: In-Progress, Ready-to-Merge

#10768 Add rubocop-performance gem
  .rubocop.yml
  Gemfile
  Gemfile.lock
Labels: In-Progress, Ready-to-Merge

#10763 Use Capybara's built-in scroll_to
  spec/feature/intake/ramp_refiling_spec.rb
  spec/feature/non_comp/dispositions_spec.rb
  spec/feature/queue/case_details_spec.rb
  spec/feature/queue/colocated_task_queue_spec.rb
  spec/feature/queue/judge_assignment_spec.rb
  spec/feature/reader/reader_spec.rb
  spec/rails_helper.rb
Labels: In-Progress, Ready-to-Merge

#10774 Show reassigned ColocatedTasks in AttorneyQueue
  app/models/queues/attorney_queue.rb
  client/app/queue/selectors.js
  spec/controllers/tasks_controller_spec.rb
  spec/factories/task.rb
  spec/feature/queue/attorney_queue_spec.rb
  spec/feature/queue/quality_review_flow_spec.rb
  spec/models/queues/attorney_queue_spec.rb
Labels: In-Progress, Ready-to-Merge

#10771 modify column name for upcoming hearings; populate column with hearin…
  client/app/hearingSchedule/components/AssignHearingsTabs.jsx
Labels: In-Progress, Ready-to-Merge

#10758 Adding hearing prep redirect
  app/controllers/application_controller.rb
  app/controllers/hearings/dockets_controller.rb
  app/models/user.rb
  app/views/hearing_schedule/index.html.erb
  client/app/hearingSchedule/HearingScheduleApp.jsx
  client/app/hearingSchedule/components/ListSchedule.jsx
  client/app/hearingSchedule/containers/ListScheduleContainer.jsx
  spec/feature/hearing_prep/daily_docket_spec.rb
  spec/feature/hearing_prep/upcoming_hearings_spec.rb
Labels: In-Progress

#10779 Add meta_request gem for better debugging
  Gemfile
  Gemfile.lock
  README.md
Labels: In-Progress, Ready-to-Merge

#10781 fix syntax in hearing.assigned_to_vso?
  app/models/hearing.rb
  app/models/legacy_hearing.rb
Labels: In-Progress, Ready-to-Merge

#10782 Updated node-sass
  client/yarn.lock
Labels: In-Progress, Ready-to-Merge

#10660 Hearing Time Refactor
  app/models/hearing.rb
  app/models/legacy_hearing.rb
  app/services/hearing_time_service.rb
  spec/factories/hearing.rb
  spec/factories/legacy_hearing.rb
  spec/models/judge_spec.rb
  spec/services/hearing_time_service_spec.rb
Labels: In-Progress, Ready-to-Merge

#10773 Handle MultiAddressError in AHL Job
  app/jobs/fetch_hearing_locations_for_veterans_job.rb
  app/services/va_dot_gov_address_validator.rb
  app/services/va_dot_gov_address_validator_exceptions.rb
  spec/jobs/fetch_hearing_locations_for_veterans_job_spec.rb
Labels: In-Progress, Ready-to-Merge

#10785 Fetch only data from Facilities API endpoint
  app/services/external_api/va_dot_gov_service.rb
  lib/fakes/va_dot_gov_service.rb
  spec/services/external_api/va_dot_gov_service_spec.rb
Labels: In-Progress, Ready-to-Merge

#10770 Move Label formatting to backend
  README.md
  app/controllers/idt/api/v1/appeals_controller.rb
  app/models/docket.rb
  app/models/legacy_tasks/judge_legacy_task.rb
  app/models/task.rb
  client/COPY.json
  client/app/queue/AssignToAttorneyModalView.jsx
  client/app/queue/components/TaskTable.jsx
  client/app/queue/selectors.js
  client/test/karma/queue/QueueLoadingScreen-test.js
  spec/feature/hearing_schedule/change_hearing_disposition_spec.rb
  spec/models/legacy_tasks/judge_legacy_task_spec.rb
Labels: In-Progress, Ready-to-Merge

#10798 Fix imprecise on hold calculation
  app/models/tasks/timed_hold_task.rb
  spec/controllers/tasks/place_hold_controller_spec.rb
  spec/models/tasks/timed_hold_task_spec.rb
Labels: In-Progress, Ready-to-Merge

#10806 remove module prefix to fix issue with module reloading
  lib/fakes/va_dot_gov_service.rb
Labels: In-Progress

#10789 Update document series ids with 1 SQL statement
  Gemfile
  app/services/add_series_id_to_documents_service.rb
  app/services/document_fetcher.rb
  app/services/document_series_id_assigner.rb
  spec/services/document_series_id_assigner_spec.rb
Labels: In-Progress, Ready-to-Merge

#10765 Add VBMSError::BadSOAPMessage
  app/exceptions/vbms_error.rb
Labels: In-Progress, Ready-to-Merge

#10793 Quiet warnings and deprecation notices
  spec/models/document_spec.rb
  spec/services/external_api/va_dot_gov_service_spec.rb
Labels: In-Progress, Ready-to-Merge

#10712 Front End Hearing Time Refactor
  app/controllers/hearings_controller.rb
  app/models/hearing.rb
  app/models/legacy_hearing.rb
  app/models/tasks/disposition_task.rb
  app/models/tasks/schedule_hearing_task.rb
  app/repositories/hearing_repository.rb
  client/app/components/common/actionTypes.js
  client/app/components/common/actions.js
  client/app/components/common/reducers.js
  client/app/hearingSchedule/components/DailyDocket.jsx
  client/app/hearingSchedule/components/DailyDocketRow.jsx
  client/app/hearingSchedule/components/DailyDocketRowDisplayText.jsx
  client/app/hearingSchedule/components/DailyDocketRowInputs.jsx
  client/app/hearingSchedule/components/modalForms/AssignHearingForm.jsx
  client/app/hearingSchedule/components/modalForms/HearingTime.jsx
  client/app/hearingSchedule/containers/DailyDocketContainer.jsx
  client/app/hearings/constants/constants.js
  client/app/queue/components/AssignHearingModal.jsx
  client/app/queue/components/PostponeHearingModal.jsx
  spec/feature/hearing_schedule/daily_docket_spec.rb
  spec/feature/hearing_schedule/postpone_hearing_spec.rb
  spec/feature/hearing_schedule/schedule_veteran_spec.rb
  spec/models/tasks/disposition_task_spec.rb
  spec/models/tasks/schedule_hearing_task_spec.rb
  spec/repositories/hearing_repository_spec.rb
Labels: In-Progress

#10796 Speed up hearing day controller index
  app/controllers/hearings/hearing_day_controller.rb
Labels: In-Progress, Ready-to-Merge, tango

#10693 Change task type (FE only)
  app/models/tasks/colocated_task.rb
  app/models/tasks/mail_task.rb
  app/repositories/task_action_repository.rb
  client/COPY.json
  client/app/queue/ChangeTaskTypeModal.jsx
  client/app/queue/QueueApp.jsx
  client/app/queue/components/TaskTable.jsx
  client/app/queue/utils.js
  client/constants/CO_LOCATED_ACTIONS.json
  client/constants/TASK_ACTIONS.json
  spec/feature/queue/colocated_task_queue_spec.rb
  spec/feature/queue/mail_task_spec.rb
Labels: In-Progress, Ready-to-Merge

#10811 Unable to cest EP| decision date 2/15/19
  client/constants/INELIGIBLE_REQUEST_ISSUES.json
Labels: In-Progress, Ready-to-Merge

#10707 Removing VACOLS hearing days
  app/controllers/hearings/dockets_controller.rb
  app/controllers/hearings/hearing_day_controller.rb
  app/controllers/regional_offices_controller.rb
  app/mappers/hearing_day_mapper.rb
  app/models/hearing_day.rb
  app/models/vacols/case_hearing.rb
  app/models/vacols/travel_board_schedule.rb
  app/repositories/hearing_day_repository.rb
  app/repositories/hearing_repository.rb
  app/repositories/travel_board_schedule_repository.rb
  app/services/hearing_schedule/assign_judges_to_hearing_days.rb
  app/services/hearing_schedule/generate_hearing_days_schedule.rb
  client/app/hearingSchedule/components/DailyDocket.jsx
  client/app/hearingSchedule/components/DailyDocketModals.jsx
  client/app/hearingSchedule/components/ListSchedule.jsx
  spec/controllers/hearings/dockets_controller_spec.rb
  spec/factories/vacols/case_hearing.rb
  spec/models/appeal_series_alerts_spec.rb
  spec/models/hearing_day_spec.rb
  spec/repositories/hearing_day_repository_spec.rb
  spec/requests/hearing_day_spec.rb
Labels: In-Progress, Ready-to-Merge

#10808 apply stub_const to quiet warnings
  spec/controllers/hearings_controller_spec.rb
  spec/feature/hearing_schedule/list_schedule_spec.rb
  spec/jobs/fetch_hearing_locations_for_veterans_job_spec.rb
  spec/models/hearing_spec.rb
  spec/models/representative_spec.rb
  spec/models/user_spec.rb
  spec/models/veteran_spec.rb
Labels: In-Progress, Ready-to-Merge

#10809 disabling flake. failed 19/20 times with ensure_stable
  spec/feature/reader/reader_spec.rb
Labels: In-Progress, Ready-to-Merge

#10801 Tech lead responsibilities doc
  docs/tech-lead-description.md
Labels: In-Progress, Ready-to-Merge

#10803 Display "Assigned To" on case details page when assignee is an organization.
  app/models/serializers/work_queue/legacy_task_serializer.rb
  app/models/serializers/work_queue/task_serializer.rb
  client/app/queue/components/TaskRows.jsx
  client/app/queue/utils.js
Labels: In-Progress, Ready-to-Merge

#10783 Only allow RAMP intakes if feature toggle enabled
  README.md
  app/controllers/intakes_controller.rb
  app/models/request_issue.rb
  client/app/intake/pages/selectForm.jsx
  spec/feature/intake/appeal_spec.rb
  spec/feature/intake/higher_level_review_spec.rb
  spec/feature/intake/intake_spec.rb
  spec/feature/intake/ramp_election_spec.rb
  spec/feature/intake/ramp_refiling_spec.rb
  spec/feature/intake/review_page_spec.rb
  spec/feature/intake/supplemental_claim_spec.rb
  spec/feature/intake/time_zone_spec.rb
  spec/models/ramp_refiling_spec.rb
  spec/support/intake_helpers.rb
Labels: In-Progress, Ready-to-Merge

#10819 Removing user query from vacols attributes
  app/repositories/hearing_repository.rb
Labels: In-Progress, Ready-to-Merge

#10784 Add MissingContentionDisposition exception
  app/models/request_issue.rb
Labels: In-Progress, Ready-to-Merge

#10735 Inject docket number column into TaskTable instance in OrganizationQueue.
  client/app/queue/OrganizationQueue.jsx
  client/app/queue/components/TaskTable.jsx
Labels: Ready-to-Merge

#10786 Removing unused hearing prep pages
  README.md
  app/controllers/application_controller.rb
  app/controllers/hearings/dockets_controller.rb
  app/controllers/hearings/hearing_day_controller.rb
  app/controllers/hearings_controller.rb
  app/controllers/test/users_controller.rb
  app/helpers/master_record_helper.rb
  app/models/hearing_docket.rb
  app/models/hearings/master_record.rb
  app/models/judge.rb
  app/models/user.rb
  app/models/vacols/case_hearing.rb
  app/repositories/hearing_repository.rb
  app/views/hearing_schedule/index.html.erb
  client/app/containers/StyleGuide/StyleGuideFooter.jsx
  client/app/containers/StyleGuide/StyleGuideNavigationBar.jsx
  client/app/hearingSchedule/HearingScheduleApp.jsx
  client/app/hearingSchedule/components/ListSchedule.jsx
  client/app/hearingSchedule/containers/ListScheduleContainer.jsx
  client/app/hearings/DailyDocket.jsx
  client/app/hearings/Dockets.jsx
  client/app/hearings/actions/Dockets.js
  client/app/hearings/components/WorksheetHeaderVeteranSelection.jsx
  client/app/hearings/constants/constants.js
  client/app/hearings/containers/DailyDocketContainer.jsx
  client/app/hearings/containers/DocketsContainer.jsx
  client/app/hearings/index.jsx
  client/app/hearings/reducers/index.js
  client/app/hearings/reducers/issue.js
  client/test/karma/components/AutoSave-test.js
  client/test/karma/hearings/actions/Dockets-test.js
  client/test/karma/hearings/reducers/index-test.js
  client/test/karma/hearings/util/IssuesUtil-test.js
  config/routes.rb
  spec/controllers/hearings/dockets_controller_spec.rb
  spec/feature/hearing_prep/daily_docket_spec.rb
  spec/feature/hearing_prep/hearing_worksheet_spec.rb
  spec/feature/hearing_prep/upcoming_hearings_spec.rb
  spec/feature/hearing_schedule/change_hearing_disposition_spec.rb
  spec/feature/hearing_schedule/list_schedule_spec.rb
  spec/feature/out_of_service_spec.rb
  spec/helpers/master_record_helper_spec.rb
  spec/models/hearing_docket_spec.rb
  spec/models/judge_spec.rb
  spec/models/master_record_spec.rb
  spec/repositories/hearing_repository_spec.rb
Labels: In-Progress, Ready-to-Merge

#10790 EFolderService.document_count uses efolder /api/v2/veterans endpoint
  app/controllers/appeals_controller.rb
  app/services/external_api/efolder_service.rb
  lib/fakes/vbms_service.rb
  spec/controllers/appeals_controller_spec.rb
  spec/feature/queue/ama_queue_spec.rb
  spec/feature/queue/case_details_spec.rb
Labels: In-Progress, Ready-to-Merge

#10837 Cache document count endpoint
  app/services/cache_manager.rb
  app/services/external_api/efolder_service.rb
  spec/services/external_api/efolder_service_spec.rb
Labels: Ready-to-Merge

#10685 Update legacy opt in copy on edit
  client/COPY.json
  client/app/intake/components/AddedIssue.jsx
  client/app/intake/pages/addIssues.jsx
  client/app/intake/pages/decisionReviewIntakeCompleted.jsx
  client/constants/INTAKE_STRINGS.json
  spec/feature/intake/appeal_spec.rb
  spec/feature/intake/higher_level_review/edit_spec.rb
  spec/feature/intake/higher_level_review_spec.rb
  spec/feature/intake/supplemental_claim_spec.rb
Labels: In-Progress

#10842 Do not create record request tasks for unidentified issues
  app/models/request_issue.rb
  spec/factories/request_issue.rb
  spec/models/appeal_spec.rb
  spec/models/request_issue_spec.rb
Labels: Ready-to-Merge

#10797 change hearing disposition from schedule hearing task
  app/controllers/tasks_controller.rb
  app/jobs/hearing_disposition_change_job.rb
  app/models/tasks/disposition_task.rb
  app/models/tasks/generic_task.rb
  app/models/tasks/hearing_admin_action_task.rb
  app/models/tasks/hearing_task.rb
  app/models/tasks/no_show_hearing_task.rb
  app/models/tasks/schedule_hearing_task.rb
  app/models/tasks/transcription_task.rb
  client/COPY.json
  client/constants/TASK_ACTIONS.json
  spec/controllers/tasks_controller_spec.rb
  spec/feature/hearing_schedule/change_hearing_disposition_spec.rb
  spec/jobs/hearing_disposition_change_job_spec.rb
  spec/models/tasks/disposition_task_spec.rb
  spec/models/tasks/generic_task_spec.rb
  spec/models/tasks/hearing_task_spec.rb
  spec/models/tasks/schedule_hearing_task_spec.rb
Labels: In-Progress, Ready-to-Merge, tango

#10845 Removing unnecessary transaction to speed up pageload
  app/models/legacy_hearing.rb
Labels: Ready-to-Merge

#10821 Decision date validation nonrating request issues
  client/app/intake/components/NonratingRequestIssueModal.jsx
  client/app/styles/_intake.scss
  spec/feature/intake/higher_level_review_spec.rb
  spec/feature/intake/intake_edit_confirmation_spec.rb
  spec/feature/intake/veteran_name_caching_spec.rb
Labels: Ready-to-Merge

#10818 Create bulk assign endpoint
  .reek.yml
  app/controllers/bulk_task_assignments_controller.rb
  app/models/organization.rb
  app/models/organizations/hearings_management.rb
  app/models/tasks/disposition_task.rb
  app/workflows/bulk_task_assignment.rb
  config/routes.rb
  db/seeds.rb
  spec/controllers/bulk_task_assignments_controller_spec.rb
  spec/factories/task.rb
  spec/feature/queue/ama_queue_spec.rb
  spec/workflows/bulk_task_assignment_spec.rb
Labels: In-Progress, Ready-to-Merge

#10831 Stop cascading task closure at org boundary
  .reek.yml
  app/models/task.rb
  app/models/tasks/disposition_task.rb
  app/models/tasks/distribution_task.rb
  app/models/tasks/hearing_task.rb
  app/models/tasks/root_task.rb
  app/models/tasks/schedule_hearing_task.rb
  spec/models/task_spec.rb
  spec/models/tasks/hearing_admin_action_task_spec.rb
  spec/models/tasks/no_show_hearing_task_spec.rb
  spec/models/tasks/quality_review_task_spec.rb
  spec/models/tasks/timed_hold_task_spec.rb
Labels: Ready-to-Merge

#10836 Moving hearing worksheet to hearings application
  app/controllers/hearing_schedule_controller.rb
  app/controllers/hearings/hearing_day_controller.rb
  app/views/hearing_schedule/index.html.erb
  app/views/hearings/index.html.erb
  client/app/hearingSchedule/HearingScheduleApp.jsx
  client/app/hearingSchedule/HearingsApp.jsx
  client/app/hearingSchedule/index.jsx
  client/app/hearingSchedule/reducers.js
  client/app/hearings/HearingWorksheet.jsx
  client/app/hearings/components/HearingWorksheetIssues.jsx
  client/app/hearings/components/HearingWorksheetStream.jsx
  client/app/hearings/components/WorksheetHeader.jsx
  client/app/hearings/components/WorksheetHeaderVeteranSelection.jsx
  client/app/hearings/containers/HearingWorksheetContainer.jsx
  client/app/hearings/index.jsx
  client/app/hearings/reducers/index.js
  client/app/index.js
  spec/models/hearing_day_spec.rb
Labels: Ready-to-Merge

#10847 Fix Disposition Update
  client/app/hearingSchedule/components/DailyDocket.jsx
  client/app/hearingSchedule/components/DailyDocketModals.jsx
  client/app/hearingSchedule/components/DailyDocketRowInputs.jsx
Labels: Ready-to-Merge

#10730 Add "Cancel and Assign RO" action to Address Verify task
  .reek.yml
  app/jobs/fetch_hearing_locations_for_veterans_job.rb
  app/models/tasks/hearing_admin_action_task.rb
  app/models/tasks/hearing_admin_action_verify_address_task.rb
  app/services/va_dot_gov_address_validator.rb
  client/COPY.json
  client/app/queue/QueueApp.jsx
  client/app/queue/components/CancelTaskAssignRegionalOfficeModal.jsx
  client/constants/TASK_ACTIONS.json
  spec/factories/task.rb
  spec/feature/queue/hearings_tasks_spec.rb
  spec/jobs/fetch_hearing_locations_for_veterans_job_spec.rb
  spec/models/tasks/hearing_admin_action_task_spec.rb
Labels: In-Progress, Ready-to-Merge

#10832 Save edited contention text to server
  app/models/request_issue.rb
  app/models/request_issues_update.rb
  client/app/intake/util/issues.js
  db/migrate/20190520201631_add_edited_request_issue_ids_to_request_issues_updates.rb
  db/schema.rb
  spec/feature/intake/higher_level_review/edit_spec.rb
Labels: Ready-to-Merge

#10850 Removing uniq on hashed objects
  app/repositories/hearing_repository.rb
Labels: Ready-to-Merge

#10750 Pulac
  app/controllers/tasks_controller.rb
  app/models/organizations/pulac_curello.rb
  app/models/tasks/mail_task.rb
  app/models/tasks/pulac_curello_task.rb
  app/repositories/task_action_repository.rb
  client/COPY.json
  client/app/queue/AssignToView.jsx
  client/app/queue/QueueApp.jsx
  client/constants/TASK_ACTIONS.json
  db/seeds.rb
  spec/feature/queue/task_queue_spec.rb
Labels: In-Progress

#10849 Do not throw error if efolder request does not finish within 10 seconds
  app/services/external_api/efolder_service.rb
  spec/services/external_api/efolder_service_spec.rb
Labels: Ready-to-Merge

#10857 add 2-minute timeout to hearing_day.json request on Hearings Schedule page
  client/app/hearingSchedule/containers/ListScheduleContainer.jsx
Labels: Ready-to-Merge, tango

#10853 Only update VACOLS location for ColocatedTasks when location is CASEFLOW
  app/models/tasks/colocated_task.rb
  spec/models/tasks/colocated_task_spec.rb
Labels: Ready-to-Merge

#10848 AttorneyQualityReviewTask
  app/controllers/tasks_controller.rb
  app/models/queues/attorney_queue.rb
  app/models/tasks/attorney_quality_review_task.rb
  app/models/tasks/judge_quality_review_task.rb
  app/repositories/task_action_repository.rb
  client/COPY.json
  client/app/queue/QueueApp.jsx
  client/constants/TASK_ACTIONS.json
  spec/feature/queue/quality_review_flow_spec.rb
  spec/models/tasks/attorney_quality_review_task_spec.rb
  spec/models/tasks/judge_quality_review_task_spec.rb
  spec/models/tasks/judge_task_spec.rb
Labels: Ready-to-Merge

#10859 Docket Row Key Fix
  client/app/hearingSchedule/components/DailyDocketRows.jsx
Labels: Ready-to-Merge

#10704 Automatic case distribution for Hearing Docket
  app/models/dockets/hearing_request_docket.rb
  app/queries/hearing_request_distribution_query.rb
  app/workflows/create_judge_assign_tasks_for_appeals.rb
  app/workflows/hearing_request_case_distributor.rb
  app/workflows/judge_assign_task_creator.rb
  spec/factories/appeal.rb
  spec/models/dockets/hearing_request_docket_spec.rb
Labels: In-Progress, Ready-to-Merge

#10676 PA was routed incorrectly
  app/services/appeal_repository.rb
  client/app/constants/SpecialIssues.js
  client/test/karma/constants/SpecialIssuesFilters-test.js
Labels: In-Progress, Ready-to-Merge

#10860 Give AttorneyRewriteTask a label
  app/models/tasks/attorney_rewrite_task.rb
  client/COPY.json
Labels: Ready-to-Merge

#10862 Pulac
  app/controllers/tasks_controller.rb
  app/models/organizations/pulac_cerullo.rb
  app/models/organizations/pulac_curello.rb
  app/models/tasks/pulac_cerullo_task.rb
  app/repositories/task_action_repository.rb
  client/app/queue/AssignToView.jsx
  client/app/queue/QueueApp.jsx
  db/seeds.rb
  spec/feature/queue/task_queue_spec.rb
Labels: Ready-to-Merge

#10869 Use regular scope chaining vs merging
  app/models/docket.rb
  app/models/dockets/direct_review_docket.rb
Labels: Ready-to-Merge

#10870 stop checking for duplicate action values
  app/models/task.rb
  lib/caseflow/error.rb
  spec/models/task_spec.rb
Labels: Ready-to-Merge

#10791 Add button to print Daily Docket
  app/assets/stylesheets/print/hearings_schedule.scss
  app/assets/stylesheets/print/hearings_worksheet.scss
  app/controllers/hearings/hearing_day_controller.rb
  app/controllers/hearings/worksheets_controller.rb
  app/views/hearings/index.html.erb
  client/app/components/ProgressBar.jsx
  client/app/components/TabWindow.jsx
  client/app/constants/AppConstants.js
  client/app/hearingSchedule/HearingsApp.jsx
  client/app/hearingSchedule/components/DailyDocket.jsx
  client/app/hearingSchedule/components/DailyDocketEditLinks.jsx
  client/app/hearingSchedule/components/DailyDocketModals.jsx
  client/app/hearingSchedule/components/DailyDocketPrinted.jsx
  client/app/hearingSchedule/components/DailyDocketRowDisplayText.jsx
  client/app/hearingSchedule/components/ListSchedule.jsx
  client/app/hearingSchedule/containers/DailyDocketContainer.jsx
  client/app/hearingSchedule/containers/ListScheduleContainer.jsx
  client/app/hearingSchedule/utils.js
  client/app/hearings/HearingWorksheet.jsx
  client/app/hearings/containers/HearingWorksheetContainer.jsx
  client/app/styles/hearings/_hearings_styles_root.scss
  client/app/util/PrintUtil.js
  client/constants/AOD_CODE_TO_LABEL_MAP.json
  client/constants/HEARING_DISPOSITION_TYPE_TO_LABEL_MAP.json
  config/initializers/assets.rb
  config/routes.rb
Labels: In-Progress, Ready-to-Merge

#10814 AMA AOD functionality
  app/controllers/concerns/hearings_concerns.rb
  app/controllers/hearings_controller.rb
  app/models/hearing.rb
  client/app/hearingSchedule/HearingsApp.jsx
  client/app/hearingSchedule/components/DailyDocketRow.jsx
  client/app/hearingSchedule/components/DailyDocketRowInputs.jsx
  client/app/hearingSchedule/containers/DailyDocketContainer.jsx
  spec/feature/hearing_schedule/daily_docket_spec.rb
  spec/models/hearing_spec.rb
Labels: In-Progress, Ready-to-Merge

#10871 Removing HP Part 3 - Moving worksheet to 'hearings' folder
  client/app/constants/AppConstants.js
  client/app/hearingSchedule/HearingsApp.jsx
  client/app/hearingSchedule/containers/HearingWorksheetContainer.jsx
  client/app/hearings/HearingWorksheet.jsx
  client/app/hearings/actions/Dockets.js
  client/app/hearings/actions/Issue.js
  client/app/hearings/analytics.js
  client/app/hearings/components/HearingWorksheetStream.jsx
  client/app/hearings/components/WorksheetHeaderVeteranSelection.jsx
  client/app/hearings/constants/constants.js
  client/app/hearings/containers/HearingWorksheetContainer.jsx
  client/app/hearings/reducers/index.js
  spec/feature/hearings/add_hearing_day_spec.rb
  spec/feature/hearings/build_schedule_spec.rb
  spec/feature/hearings/change_hearing_disposition_spec.rb
  spec/feature/hearings/daily_docket_spec.rb
  spec/feature/hearings/edit_hearing_day_spec.rb
  spec/feature/hearings/hearing_details_spec.rb
  spec/feature/hearings/hearing_worksheet_spec.rb
  spec/feature/hearings/list_schedule_spec.rb
  spec/feature/hearings/postpone_hearing_spec.rb
  spec/feature/hearings/remove_hearing_day_spec.rb
  spec/feature/hearings/schedule_veteran_spec.rb
Labels: Ready-to-Merge

#10879 Move LOB redirect from tasks.json endpoint to main .html endpoint
  app/controllers/decision_reviews_controller.rb
  app/controllers/organizations/tasks_controller.rb
  app/controllers/organizations_controller.rb
  spec/controllers/organizations/tasks_controller_spec.rb
  spec/feature/queue/user_organization_spec.rb
Labels: Ready-to-Merge

#10865 Add user station_id to default Sentry alert
  app/controllers/application_controller.rb
Labels: Ready-to-Merge

#10868 Update gems with bummr
  Gemfile
  Gemfile.lock
  config/brakeman.ignore
Labels: Ready-to-Merge

#10772 Break out root task creation to reduce file size
  app/models/appeal.rb
  app/models/tasks/distribution_task.rb
  app/models/tasks/evidence_submission_window_task.rb
  app/models/tasks/hearing_task.rb
  app/models/tasks/root_task.rb
  app/workflows/ihp_tasks_factory.rb
  app/workflows/initial_tasks_factory.rb
  db/seeds.rb
  spec/models/appeal_spec.rb
  spec/models/hearing_spec.rb
  spec/models/tasks/evidence_submission_window_task_spec.rb
  spec/models/tasks/informal_hearing_presentation_task_spec.rb
  spec/models/tasks/root_task_spec.rb
  spec/models/tasks/schedule_hearing_task_spec.rb
  spec/workflows/initial_tasks_factory_spec.rb
Labels: In-Progress, Ready-to-Merge

#10670 Allow Dispatch to Return Cases to the Judge
  app/controllers/tasks_controller.rb
  app/models/queues/attorney_queue.rb
  app/models/tasks/attorney_dispatch_return_task.rb
  app/models/tasks/bva_dispatch_task.rb
  app/models/tasks/generic_task.rb
  app/models/tasks/judge_dispatch_return_task.rb
  app/models/tasks/judge_task.rb
  app/models/tasks/quality_review_task.rb
  app/repositories/task_action_repository.rb
  app/workflows/complete_case_review.rb
  client/COPY.json
  client/app/queue/QueueApp.jsx
  client/app/queue/selectors.js
  client/constants/TASK_ACTIONS.json
  db/seeds.rb
  spec/factories/task.rb
  spec/feature/queue/quality_review_flow_spec.rb
  spec/feature/queue/task_queue_spec.rb
  spec/models/tasks/attorney_dispatch_return_task_spec.rb
  spec/models/tasks/judge_dispatch_return_task_spec.rb
Labels: In-Progress, Ready-to-Merge

#10899 Default to RO58 for Philippines addresses
  app/services/va_dot_gov_address_validator.rb
  app/services/va_dot_gov_address_validator_exceptions.rb
  spec/jobs/fetch_hearing_locations_for_veterans_job_spec.rb
Labels: Ready-to-Merge

#10874 Withdrawn status for AMA appeals
  client/app/queue/CaseListTable.jsx
  spec/feature/queue/search_spec.rb
Labels: Ready-to-Merge

#10904 Ignore sentry alerts for a month, tag GH tix with sentry-alert
  docs/bat-team.md
Labels: Ready-to-Merge, batteam

#10910 Adding judge permissions to print daily docket page
  app/controllers/hearing_schedule_controller.rb
  app/controllers/hearings/hearing_day_controller.rb
Labels: Ready-to-Merge

#10898 Renaming hearings reducers
  client/app/hearings/actions/actions.js
  client/app/hearings/components/HearingDayEditModal.jsx
  client/app/hearings/components/dailyDocket/DailyDocket.jsx
  client/app/hearings/components/dailyDocket/DailyDocketEditLinks.jsx
  client/app/hearings/components/dailyDocket/DailyDocketModals.jsx
  client/app/hearings/components/dailyDocket/DailyDocketPrinted.jsx
  client/app/hearings/components/dailyDocket/DailyDocketRow.jsx
  client/app/hearings/components/dailyDocket/DailyDocketRowDisplayText.jsx
  client/app/hearings/components/dailyDocket/DailyDocketRowInputs.jsx
  client/app/hearings/components/dailyDocket/DailyDocketRows.jsx
  client/app/hearings/components/hearingWorksheet/HearingWorksheet.jsx
  client/app/hearings/components/hearingWorksheet/HearingWorksheetIssueDelete.jsx
  client/app/hearings/components/hearingWorksheet/HearingWorksheetIssues.jsx
  client/app/hearings/components/hearingWorksheet/HearingWorksheetStream.jsx
  client/app/hearings/components/hearingWorksheet/WorksheetHeader.jsx
  client/app/hearings/components/hearingWorksheet/WorksheetHeaderVeteranSelection.jsx
  client/app/hearings/constants.js
  client/app/hearings/containers/DailyDocketContainer.jsx
  client/app/hearings/index.jsx
  client/app/hearings/reducers/dailyDocketReducer.js
  client/app/hearings/reducers/hearingScheduleReducer.js
  client/app/hearings/reducers/hearingWorksheetReducer.js
  client/app/hearings/reducers/index.js
  client/app/util/DateUtil.js
Labels: Ready-to-Merge
