Repository department-of-veterans-affairs/caseflow, pull requests merged in 2019-09, with the labels that each got.

#11958 Fix test around inbox read message button content
  spec/support/date_time_helper.rb
Labels: Ready-to-Merge

#11537 add test to verify no cancel tasks for active issues
  spec/models/request_issues_update_spec.rb
Labels: Ready-to-Merge

#11953 fix edge case where JS regex failed to match over multiple lines
  client/app/asyncableJobs/pages/JobsPage.jsx
  spec/feature/asyncable_jobs/asyncable_jobs_index_spec.rb
Labels: Ready-to-Merge

#11961 Remove voided decision issue code
  app/models/decision_issue.rb
  app/workflows/contestable_issue_generator.rb
  spec/models/decision_issue_spec.rb
  spec/models/decision_review_spec.rb
Labels: Ready-to-Merge

#11880 Add Assignee Label to CachedAppealAttributes for Legacy Appeals
  .reek.yml
  app/jobs/update_cached_appeals_attributes_job.rb
  spec/factories/cached_appeals.rb
Labels: Ready-to-Merge

#11965 Sorting by assignee label
  client/app/queue/components/TaskTable.jsx
  client/constants/QUEUE_CONFIG.json
  spec/models/task_sorter_spec.rb
Labels: Ready-to-Merge

#11598 Lighthouse - Higher Level Review /happier/ path
  .reek.yml
  app/controllers/api/docs/v3/decision_reviews.yaml
  app/controllers/api/v3/decision_review/higher_level_reviews_controller.rb
  app/controllers/api/v3/decision_review/intake_statuses_controller.rb
  app/exceptions/api/v3/decision_review/review_error.rb
  app/exceptions/api/v3/decision_review/start_error.rb
  app/services/api/v3/decision_review/higher_level_review_intake_processor.rb
  app/services/api/v3/decision_review/intake_error.rb
  app/services/api/v3/decision_review/intake_errors.rb
  app/services/api/v3/decision_review/intake_params.rb
  app/services/api/v3/decision_review/intake_processor.rb
  app/services/api/v3/decision_review/intake_status.rb
  app/services/api/v3/decision_review/request_issue_params.rb
  config/routes.rb
  spec/controllers/api/docs/v3/decision_reviews_spec.rb
  spec/exceptions/api/v3/decision_review/review_error_spec.rb
  spec/exceptions/api/v3/decision_review/start_error_spec.rb
  spec/requests/api/v3/decision_review/higher_level_reviews_controller_spec.rb
  spec/requests/api/v3/higher_level_reviews_controller_spec.rb
  spec/services/api/v3/decision_review/higher_level_review_intake_processor_spec.rb
  spec/services/api/v3/decision_review/intake_error_spec.rb
  spec/services/api/v3/decision_review/intake_errors_spec.rb
  spec/services/api/v3/decision_review/intake_params_spec.rb
  spec/services/api/v3/decision_review/intake_processor_spec.rb
  spec/services/api/v3/decision_review/intake_status_spec.rb
  spec/services/api/v3/decision_review/request_issue_params_spec.rb
Labels: lighthouse

#11957 OpenHearingTasksWithoutActiveDescendantsChecker also finds childless HearingTasks
  app/services/open_hearing_tasks_without_active_descendants_checker.rb
  spec/services/open_hearing_tasks_without_active_descendants_checker_spec.rb
Labels: Ready-to-Merge

#11967 Show only most recently closed tasks on non-comp queues
  app/controllers/decision_reviews_controller.rb
  spec/factories/task.rb
  spec/feature/non_comp/reviews_spec.rb
  spec/repositories/appeal_repository_spec.rb
Labels: Ready-to-Merge

#11899 Error message for co hearing rooms
  app/controllers/hearings/hearing_day_controller.rb
  client/COPY.json
  client/app/hearings/components/HearingDayAddModal.jsx
  spec/feature/hearings/add_hearing_day_spec.rb
  spec/requests/hearing_day_spec.rb
Labels: Ready-to-Merge

#11976 Skip appeals that do not have a veteran associated
  app/jobs/warm_bgs_caches_job.rb
Labels: Ready-to-Merge

#11960 Add positive feedback to Attorney Evaluation Screen for AMA appeals
  app/controllers/case_reviews_controller.rb
  client/COPY.json
  client/app/queue/EvaluateDecisionView.jsx
  client/app/queue/QueueApp.jsx
  client/app/queue/caseEvaluation/EvaluateDecisionView.jsx
  client/app/queue/caseEvaluation/JudgeCaseQuality.jsx
  client/app/queue/caseEvaluation/index.js
  client/app/queue/utils.js
  client/constants/JUDGE_CASE_REVIEW_OPTIONS.json
  db/migrate/20190829183634_add_positive_feedback_to_judge_case_review.rb
  db/schema.rb
  spec/feature/queue/judge_checkout_flow_spec.rb
Labels: Ready-to-Merge

#11972 Add legacy appeal tests for change hearing disposition flow
  spec/factories/vacols/case_hearing.rb
  spec/feature/hearings/change_hearing_disposition_spec.rb
Labels: Ready-to-Merge

#11983 EP 930s | Update current validation to ensure request issue corrections to not be treated as duplicates
  app/models/request_issue.rb
  spec/models/request_issue_spec.rb
Labels: Ready-to-Merge

#11979 Prefer veteran.file_number over vbms_id
  app/models/legacy_appeal.rb
  app/models/veteran.rb
  client/COPY.json
  client/app/intake/pages/search.jsx
  lib/fakes/bgs_service.rb
  spec/controllers/appeals_controller_spec.rb
  spec/controllers/tasks_controller_spec.rb
  spec/feature/intake/intake_spec.rb
  spec/models/legacy_appeal_spec.rb
  spec/models/legacy_hearing_spec.rb
Labels: Ready-to-Merge

#12000 Self-documented Makefile
  .codeclimate.yml
  Makefile.example
Labels: Ready-to-Merge

#11980 PropTypes for DailyDocketRowInputs
  client/app/hearings/components/dailyDocket/DailyDocketRowInputs.jsx
Labels: Ready-to-Merge

#12006 Sometimes legacy appeals don't have decass records
  app/models/legacy_appeal.rb
  spec/models/legacy_appeal_spec.rb
Labels: Ready-to-Merge

#12010 Move job notifications to the job channel
  app/services/data_integrity_checker.rb
  app/services/open_hearing_tasks_without_active_descendants_checker.rb
  app/services/slack_service.rb
Labels: Ready-to-Merge

#11937 Return All Decision Issues, Regardless of Receipt Date
  app/workflows/contestable_issue_generator.rb
  spec/feature/intake/end_product_correction_spec.rb
  spec/models/appeal_spec.rb
  spec/models/decision_review_spec.rb
Labels: Ready-to-Merge

#12013 Fix flakey BVA Dispatch test
  spec/models/organizations/bva_dispatch_spec.rb
Labels: Ready-to-Merge

#11860 Add missing PropTypes for ftseng-parse-json-once branch
  client/app/asyncableJobs/pages/JobsPage.jsx
  client/app/certification/Certification.jsx
  client/app/components/DataDropdowns/RegionalOffice.jsx
  client/app/components/LoadingDataDisplay.jsx
  client/app/components/PerformanceDegradationBanner.jsx
  client/app/hearings/actions/hearingWorksheetActions.js
  client/app/hearings/components/AssignHearings.jsx
  client/app/hearings/components/HearingDayAddModal.jsx
  client/app/hearings/components/hearingWorksheet/WorksheetHeaderVeteranSelection.jsx
  client/app/hearings/containers/AssignHearingsContainer.jsx
  client/app/hearings/containers/BuildScheduleContainer.jsx
  client/app/hearings/containers/DailyDocketContainer.jsx
  client/app/hearings/containers/ListScheduleContainer.jsx
  client/app/hearings/containers/ReviewAssignmentsContainer.jsx
  client/app/intake/actions/decisionReview.js
  client/app/intake/actions/intake.js
  client/app/intake/actions/rampElection.js
  client/app/intake/actions/rampRefiling.js
  client/app/intakeEdit/actions/edit.js
  client/app/intakeManager/UserStats.jsx
  client/app/nonComp/actions/task.js
  client/app/queue/AddColocatedTaskView.jsx
  client/app/queue/AddEditIssueView.jsx
  client/app/queue/AppealDocumentCount.jsx
  client/app/queue/AssignToView.jsx
  client/app/queue/CaseListView.jsx
  client/app/queue/ChangeHearingDispositionModal.jsx
  client/app/queue/ChangeTaskTypeModal.jsx
  client/app/queue/ColocatedPlaceHoldView.jsx
  client/app/queue/CreateChangeHearingDispositionTaskModal.jsx
  client/app/queue/CreateMailTaskDialog.jsx
  client/app/queue/OrganizationQueueLoadingScreen.jsx
  client/app/queue/OrganizationUsers.jsx
  client/app/queue/PostponeHearingTaskModal.jsx
  client/app/queue/QueueActions.js
  client/app/queue/QueueLoadingScreen.jsx
  client/app/queue/QueueTable.jsx
  client/app/queue/SpecialIssueLoadingScreen.jsx
  client/app/queue/VeteranCasesView.jsx
  client/app/queue/components/CancelTaskModal.jsx
  client/app/queue/components/CompleteTaskModal.jsx
  client/app/queue/components/EndHoldModal.jsx
  client/app/queue/components/HearingBadge.jsx
  client/app/queue/components/PostponeHearingModal.jsx
  client/app/queue/components/StartHoldModal.jsx
  client/app/queue/uiReducer/uiActions.js
  client/app/reader/AnnotationLayer/AnnotationActions.js
  client/app/reader/CaseSelect/CaseSelectActions.js
  client/app/reader/PdfViewer/PdfViewerActions.js
  client/app/reader/ReaderLoadingScreen.jsx
  client/app/reader/utils.js
Labels: Ready-to-Merge

#12004 refactor Fakes::BGSService
  .reek.yml
  lib/fakes/bgs_service.rb
  lib/fakes/bgs_service_grants.rb
  lib/fakes/bgs_service_record_maker.rb
Labels: Ready-to-Merge

#12008 Add instrumentation to the updated cached appeals job
  app/jobs/update_cached_appeals_attributes_job.rb
Labels: Ready-to-Merge

#12018 Rename private Veteran class method
  .reek.yml
  app/models/veteran.rb
Labels: Ready-to-Merge

#11993 Update legacy appeal VACOLS location code
  app/models/legacy_appeal.rb
  app/repositories/appeal_repository.rb
  spec/models/legacy_appeal_spec.rb
  spec/models/vacols/case_spec.rb
Labels: Ready-to-Merge

#12023 may_modify uses both find_flashes and station conflict check
  app/services/external_api/bgs_service.rb
  spec/services/external_api/bgs_service_spec.rb
Labels: Ready-to-Merge

#12015 Clean up judge_case_review_checkout feature toggle
  app/views/queue/index.html.erb
  spec/feature/queue/judge_checkout_flow_spec.rb
Labels: Ready-to-Merge

#12025 warm hearing caches 2 weeks out, catch all errors
  app/jobs/warm_bgs_caches_job.rb
  app/services/external_api/bgs_service.rb
  spec/models/person_spec.rb
Labels: Ready-to-Merge

#11949 Add Key to Case Loading Screen
  client/app/queue/CaseDetailsLoadingScreen.jsx
Labels: Ready-to-Merge

#12030 When filtering on RO join on legacy appeals as well
  app/workflows/bulk_task_assignment.rb
  spec/factories/legacy_appeal.rb
  spec/workflows/bulk_task_assignment_spec.rb
Labels: Ready-to-Merge

#12028 Skip nonpriority legacy appeal distribution when case previously distributed
  app/models/dockets/legacy_docket.rb
  spec/models/distribution_spec.rb
Labels: Ready-to-Merge

#12024 Persistent local Veteran store
  app/models/veteran.rb
  lib/fakes/bgs_service.rb
  lib/fakes/end_product_store.rb
  lib/fakes/persistent_store.rb
  lib/fakes/veteran_store.rb
  lib/generators/veteran.rb
  spec/factories/veteran.rb
  spec/feature/intake/veteran_name_caching_spec.rb
  spec/jobs/fetch_hearing_locations_for_veterans_job_spec.rb
  spec/models/end_product_establishment_spec.rb
  spec/models/legacy_appeal_spec.rb
  spec/models/ramp_election_spec.rb
  spec/models/veteran_spec.rb
  spec/services/veteran_finder_spec.rb
Labels: Ready-to-Merge

#12029 Assign Hearings Page Refactor
  client/app/hearings/components/assignHearings/AssignHearings.jsx
  client/app/hearings/components/assignHearings/AssignHearingsDocketLine.jsx
  client/app/hearings/components/assignHearings/AssignHearingsFields.jsx
  client/app/hearings/components/assignHearings/AssignHearingsTable.jsx
  client/app/hearings/components/assignHearings/AssignHearingsTabs.jsx
  client/app/hearings/containers/AssignHearingsContainer.jsx
  client/test/karma/hearings/components/AssignHearings-test.js
Labels: Ready-to-Merge

#12038 Exclude TimedHoldTasks from bulk assignment
  app/controllers/organizations/task_summary_controller.rb
Labels: Ready-to-Merge

#12027 Change ACD window to 90 days
  app/models/dockets/direct_review_docket.rb
  spec/models/docket_coordinator_spec.rb
  spec/models/dockets/direct_review_docket_spec.rb
Labels: Ready-to-Merge

#12033 Send file number mismatches to DataDog instead of Sentry
  app/models/legacy_appeal.rb
  spec/models/legacy_appeal_spec.rb
Labels: Ready-to-Merge

#11970 Edit issues after intake
  app/controllers/asyncable_jobs_controller.rb
  app/controllers/claim_review_controller.rb
  app/controllers/intakes_controller.rb
  app/models/appeal.rb
  app/models/claim_review.rb
  app/models/claim_review_intake.rb
  app/models/decision_review.rb
  app/models/veteran.rb
  client/COPY.json
  client/app/asyncableJobs/components/JobRestartButton.jsx
  client/app/errors/Error500.jsx
  client/app/intake/components/UnidentifiedIssueAlert.jsx
  client/app/intake/pages/addIssues.jsx
  client/app/intake/pages/decisionReviewEditCompleted.jsx
  client/app/intake/pages/decisionReviewIntakeCompleted.jsx
  client/app/intake/reducers/appeal.js
  client/app/intake/reducers/higherLevelReview.js
  client/app/intake/reducers/intake.js
  client/app/intake/reducers/supplementalClaim.js
  client/app/styles/_intake.scss
  spec/controllers/asyncable_jobs_controller_spec.rb
  spec/controllers/higher_level_reviews_controller_spec.rb
  spec/factories/higher_level_review.rb
  spec/factories/supplemental_claim.rb
  spec/feature/intake/add_issues_spec.rb
  spec/feature/intake/appeal_spec.rb
  spec/feature/intake/confirmation_page_spec.rb
  spec/feature/intake/end_product_correction_spec.rb
  spec/feature/intake/higher_level_review/edit_spec.rb
  spec/feature/intake/higher_level_review_spec.rb
  spec/feature/intake/intake_edit_confirmation_spec.rb
  spec/feature/intake/supplemental_claim/edit_spec.rb
  spec/feature/intake/supplemental_claim_spec.rb
  spec/feature/queue/delete_request_issues_spec.rb
  spec/feature/queue/search_spec.rb
  spec/requests/api/v3/decision_review/higher_level_reviews_controller_spec.rb
  spec/support/date_time_helper.rb
  spec/support/intake_helpers.rb
Labels: AMO, BVA Intake, Ready-to-Merge, caseflow-intake, enhancement, foxtrot, priority-medium

#12045 Collect runtimes from additional piece of cache appeal job
  app/jobs/update_cached_appeals_attributes_job.rb
Labels: Ready-to-Merge

#12046 Replace arrays with hashes in appeal cache job
  app/jobs/update_cached_appeals_attributes_job.rb
Labels: Ready-to-Merge

#12051 skip existing distributed cases for both priority and nonpriority legacy
  app/models/dockets/legacy_docket.rb
  spec/models/distribution_spec.rb
Labels: Ready-to-Merge

#11974 Implement logic when judge finishes reviewing motion to vacate task
  app/controllers/post_decision_motions_controller.rb
  app/models/tasks/straight_vacate_and_readjudication_task.rb
  app/models/tasks/vacate_and_de_novo_task.rb
  app/workflows/post_decision_motion_updater.rb
  spec/controllers/post_decision_motions_controller_spec.rb
  spec/workflows/post_decision_motion_updater_spec.rb
Labels: Ready-to-Merge

#12041 Add test demonstrating zero legacy cases results in full AMA dockets
  spec/models/distribution_spec.rb
Labels: Ready-to-Merge

#12047 Add instrumentation to the job to confirm the bug is still happening
  app/jobs/update_cached_appeals_attributes_job.rb
  spec/jobs/update_cached_appeals_attributes_job_spec.rb
Labels: Ready-to-Merge

#12057 Prevent creation of duplicate TrackVeteranTasks on intake
  app/workflows/initial_tasks_factory.rb
  spec/workflows/initial_tasks_factory_spec.rb
Labels: Ready-to-Merge

#12058 Do not attempt to move annotation if we don't have coords
  client/app/reader/PdfViewer.jsx
Labels: Ready-to-Merge

#12042 Begin unifying GenericTask and Task models.
  app/models/task.rb
  app/models/tasks/assign_hearing_disposition_task.rb
  app/models/tasks/attorney_task.rb
  app/models/tasks/bva_dispatch_task.rb
  app/models/tasks/colocated_task.rb
  app/models/tasks/decision_review_task.rb
  app/models/tasks/distribution_task.rb
  app/models/tasks/evidence_submission_window_task.rb
  app/models/tasks/foia_task.rb
  app/models/tasks/generic_task.rb
  app/models/tasks/hearing_admin_action_task.rb
  app/models/tasks/hearing_task.rb
  app/models/tasks/informal_hearing_presentation_task.rb
  app/models/tasks/judge_task.rb
  app/models/tasks/mail_task.rb
  app/models/tasks/no_show_hearing_task.rb
  app/models/tasks/privacy_act_task.rb
  app/models/tasks/pulac_cerullo_task.rb
  app/models/tasks/quality_review_task.rb
  app/models/tasks/root_task.rb
  app/models/tasks/schedule_hearing_task.rb
  app/models/tasks/special_case_movement_task.rb
  app/models/tasks/timed_hold_task.rb
  app/models/tasks/track_veteran_task.rb
  app/models/tasks/transcription_task.rb
  app/models/tasks/translation_task.rb
  spec/jobs/task_timer_job_spec.rb
  spec/models/concerns/timeable_task_spec.rb
  spec/models/task_spec.rb
Labels: Ready-to-Merge

#12049 When editing claim issues for non veteran claimants, show claimant name
  client/app/intake/util/issues.js
  spec/feature/intake/higher_level_review/edit_spec.rb
  spec/feature/intake/higher_level_review_spec.rb
  spec/feature/intake/supplemental_claim_spec.rb
Labels: Ready-to-Merge

#12087 Unused script
  bin/setup
Labels: Ready-to-Merge

#12061 Add ability to look up BGS participant IDs before logging into Caseflow
  app/controllers/user_info_controller.rb
  app/services/external_api/bgs_service.rb
  client/app/queue/LookupParticipantIdModal.jsx
  config/routes.rb
  lib/caseflow/error.rb
  lib/fakes/bgs_service.rb
  lib/generators/random.rb
  spec/controllers/user_info_controller_spec.rb
Labels: Ready-to-Merge

#11850 Upgrade diff npm lib
  client/yarn.lock
Labels: Ready-to-Merge

#12091 11657/task table cols 400
  client/app/queue/OrganizationQueue.jsx
  client/app/queue/components/TaskTable.jsx
  client/app/queue/components/TaskTableColumns.jsx
  client/app/queue/utils.js
Labels: Ready-to-Merge

#12079 Try harder to get claimant name for decision review task
  app/models/serializers/work_queue/decision_review_task_serializer.rb
  spec/models/serializers/work_queue/decision_review_task_serializer_spec.rb
Labels: Ready-to-Merge

#12085 subsecond rounding bug
  app/models/application_record.rb
  spec/sql/basic_spec.rb
Labels: Ready-to-Merge

#12089 Enable pagination filtering by assignee
  app/models/queue_column.rb
  app/models/task_filter.rb
  client/app/queue/OrganizationQueue.jsx
  client/app/queue/components/TaskTableColumns.jsx
  client/constants/QUEUE_CONFIG.json
  spec/models/queue_column_spec.rb
  spec/models/task_filter_spec.rb
Labels: Ready-to-Merge

#12106 Fix task filter flakey test
  spec/models/task_filter_spec.rb
Labels: Ready-to-Merge

#12104 Allow edit of DTA claims for 930s
  client/app/intake/pages/addIssues.jsx
  spec/feature/intake/end_product_correction_spec.rb
Labels: Ready-to-Merge

#12105 Alert on /intake if unread inbox messages
  app/controllers/intakes_controller.rb
  client/app/components/InboxLink.jsx
  client/app/components/IntakeLink.jsx
  client/app/inbox/index.jsx
  client/app/intake/IntakeFrame.jsx
  client/app/intake/pages/selectForm.jsx
  client/app/intake/reducers/intake.js
  spec/feature/intake/intake_spec.rb
Labels: Ready-to-Merge

#12050 Appeals API - update spec for HLR show route
  app/controllers/api/docs/v3/decision_reviews.yaml
  spec/controllers/api/docs/v3/decision_reviews_spec.rb
Labels: Ready-to-Merge, lighthouse

#12090 Optimize most recently held hearing controller action
  app/controllers/appeals_controller.rb
  app/queries/hearings_for_appeal.rb
  app/serializers/hearings/appeal_hearing_serializer.rb
  app/serializers/helpers/appeal_hearing_helper.rb
  config/routes.rb
Labels: Ready-to-Merge

#12118 Serialize assigned at for days waiting column
  app/models/serializers/work_queue/task_column_serializer.rb
Labels: Ready-to-Merge

#11920 Appeals API - error for non compensation LOBs
  app/controllers/api/docs/v3/decision_reviews.yaml
  app/services/api/v3/decision_review/intake_error.rb
  app/services/api/v3/decision_review/intake_params.rb
  spec/services/api/v3/decision_review/intake_params_spec.rb
Labels: Ready-to-Merge, lighthouse

#12112 Filter inactive appeals from decision review tasks queue
  app/controllers/decision_reviews_controller.rb
  spec/feature/non_comp/reviews_spec.rb
Labels: Ready-to-Merge

#12133 Remove time estimates from doc post tech-lead discussion
  docs/tech-lead-description.md
Labels: Ready-to-Merge

#12131 Implement naive caching for queue pagination API
  client/app/queue/QueueTable.jsx
Labels: Ready-to-Merge

#12114 Don't create DecisionReviewTask if there are only ineligible issues
  app/models/appeal.rb
  app/models/claim_review.rb
  app/models/claim_review_intake.rb
  app/models/decision_review.rb
  app/models/request_issues_update.rb
  spec/factories/request_issue.rb
  spec/models/appeal_spec.rb
  spec/models/claim_review_spec.rb
  spec/models/request_issues_update_spec.rb
Labels: Ready-to-Merge

#12152 Assume compensation benefit type for issues contesting rating decisions
  app/models/request_issue.rb
  spec/models/request_issue_spec.rb
Labels: Ready-to-Merge

#12130 Remove one VACOLS call in cache appeals job
  app/jobs/update_cached_appeals_attributes_job.rb
Labels: Ready-to-Merge

#12144 add closest regional office key column
  db/migrate/20190917210301_add_closest_regional_office_key_to_cached_appeal_attributes.rb
  db/schema.rb
Labels: Ready-to-Merge

#12154 Do not get dispositions for ineligible noncomp issues
  app/models/serializers/work_queue/decision_review_task_serializer.rb
  client/app/nonComp/components/Disposition.jsx
  spec/feature/non_comp/dispositions_spec.rb
  spec/models/serializers/work_queue/decision_review_task_serializer_spec.rb
Labels: Ready-to-Merge

#12155 Prevent MailRoutingErrors from triggering Sentry alerts
  app/controllers/tasks_controller.rb
  spec/controllers/tasks_controller_spec.rb
Labels: Ready-to-Merge

#12128 Add closest_regional_office_key to cached attributes
  app/jobs/update_cached_appeals_attributes_job.rb
Labels: Ready-to-Merge

#12127 Intake | Alphabetize Intake drop down menu items
  client/app/intake/constants.js
  client/constants/INTAKE_FORM_NAMES.json
  client/constants/ISSUE_CATEGORIES.json
Labels: Ready-to-Merge

#12039 updated user model method; added test in user_spec
  app/models/user.rb
  spec/controllers/users_controller_spec.rb
  spec/feature/hearings/edit_hearing_day_spec.rb
  spec/models/user_spec.rb
Labels: Ready-to-Merge

#12132 Add DecisionReviewTasksForInactiveAppealsChecker
  app/jobs/data_integrity_checks_job.rb
  app/services/decision_review_tasks_for_inactive_appeals_checker.rb
  spec/services/decision_review_tasks_for_inactive_appeals_checker_spec.rb
Labels: Ready-to-Merge

#12161 check for open tasks with closed_at value
  app/jobs/data_integrity_checks_job.rb
  app/services/open_tasks_with_closed_at_checker.rb
  spec/services/open_tasks_with_closed_at_checker_spec.rb
Labels: Ready-to-Merge

#12017 11908/create judge assign task for legacy cases
  app/models/docket.rb
  app/models/dockets/legacy_docket.rb
  app/models/vacols/case_docket.rb
  app/workflows/create_judge_assign_tasks_for_appeals.rb
  app/workflows/das_deprecation/case_distribution.rb
  app/workflows/hearing_request_case_distributor.rb
  app/workflows/judge_assign_task_creator.rb
  spec/models/vacols/case_docket_spec.rb
  spec/workflows/das_deprecation/case_distribution_spec.rb
Labels: Ready-to-Merge

#12142 New User for Testing
  db/seeds.rb
Labels: Ready-to-Merge

#12076 bva decision progress sql
  app/sql/bva-decision-progress.sql
  spec/sql/bva_decision_progress_spec.rb
Labels: Ready-to-Merge

#12184 Allow Intake Admin with VSO role combination to see /jobs
  app/controllers/asyncable_jobs_controller.rb
Labels: Ready-to-Merge

#12178 Use claim date for submit date when creating contentions
  Gemfile
  Gemfile.lock
  app/models/end_product_establishment.rb
  app/models/ramp_refiling.rb
  app/services/external_api/vbms_service.rb
  lib/fakes/vbms_service.rb
  lib/generators/contention.rb
  spec/feature/intake/higher_level_review/edit_spec.rb
  spec/feature/intake/higher_level_review_spec.rb
  spec/feature/intake/ramp_refiling_spec.rb
  spec/feature/intake/supplemental_claim/edit_spec.rb
  spec/feature/intake/supplemental_claim_spec.rb
  spec/models/claim_review_spec.rb
  spec/models/decision_document_spec.rb
  spec/models/end_product_establishment_spec.rb
  spec/models/higher_level_review_intake_spec.rb
  spec/models/ramp_refiling_spec.rb
  spec/models/request_issues_update_spec.rb
  spec/models/supplemental_claim_intake_spec.rb
Labels: Ready-to-Merge

#12116 Remove Prometheus service since we will be using Datadog
  Gemfile
  Gemfile.lock
  app/controllers/concerns/collect_data_dog_metrics.rb
  app/controllers/health_checks_controller.rb
  app/jobs/middleware/job_prometheus_metric_middleware.rb
  app/middleware/metrics_auth.rb
  app/services/metrics_service.rb
  app/services/prometheus_service.rb
  config.ru
  config/initializers/shoryuken.rb
  config/secrets.yml
  spec/jobs/job_prometheus_metric_middleware_spec.rb
  spec/services/metrics_service_spec.rb
  spec/services/prometheus_service_spec.rb
Labels: Ready-to-Merge

#12169 Refactor request issue end_product_code, add codes for 930s
  app/models/claim_review.rb
  app/models/end_product_establishment.rb
  app/models/request_issue.rb
  app/workflows/end_product_code_selector.rb
  client/constants/END_PRODUCT_CODES.json
  spec/feature/intake/higher_level_review/edit_spec.rb
  spec/models/claim_review_spec.rb
  spec/models/request_issue_spec.rb
  spec/workflows/end_product_code_selector_spec.rb
Labels: Ready-to-Merge

#12180 Remove unneeded validations for correction issues coming from decision issues on the same claim
  app/models/contestable_issue.rb
  app/models/request_issue.rb
  spec/factories/higher_level_review.rb
  spec/factories/supplemental_claim.rb
  spec/feature/intake/end_product_correction_spec.rb
  spec/models/decision_review_spec.rb
Labels: Ready-to-Merge

#12185 Add missing timestamp columns
  PULL_REQUEST_TEMPLATE.md
  app/controllers/distributions_controller.rb
  app/models/distribution.rb
  app/models/document.rb
  app/models/staff_field_for_organization.rb
  app/models/tasks/task_business_payload.rb
  app/serializers/distribution_serializer.rb
  db/migrate/20190920213522_add_timestamps_to_missing_tables.rb
  db/schema.rb
  lib/generators/document.rb
Labels: Ready-to-Merge

#12189 Fix hiding add issues button on dta corrections
  client/app/intake/pages/addIssues.jsx
  spec/feature/intake/end_product_correction_spec.rb
Labels: Ready-to-Merge

#12199 Skip flakes
  app/repositories/judge_repository.rb
  spec/repositories/judge_repository_spec.rb
Labels: Ready-to-Merge

#12196 Add Hearings Page: Screen Reader Modal Navigation Fix
  client/app/components/Modal.jsx
Labels: Ready-to-Merge

#12117 Refactor queue selection and legacy task eager loading
  app/controllers/judge_assign_tasks_controller.rb
  app/controllers/organizations/tasks_controller.rb
  app/controllers/tasks/change_type_controller.rb
  app/controllers/tasks_controller.rb
  app/models/queues/attorney_queue.rb
  app/serializers/ama_and_legacy_task_serializer.rb
  app/workflows/queue_for_role.rb
  spec/workflows/queue_for_role_spec.rb
Labels: Ready-to-Merge

#12207 Swap appeal finds for wheres
  app/jobs/update_cached_appeals_attributes_job.rb
Labels: Ready-to-Merge, batteam

#12219 Allow admin users to see /jobs page
  app/controllers/asyncable_jobs_controller.rb
  spec/controllers/asyncable_jobs_controller_spec.rb
Labels: Ready-to-Merge

#12083 Rubaiyat/11592 feature testing by roles 3
  spec/feature/hearings/build_schedule/build_hearsched_spec.rb
  spec/feature/hearings/hearing_worksheet/hearing_prep_spec.rb
  spec/feature/hearings/hearing_worksheet_spec.rb
  spec/feature/hearings/schedule_veteran/build_hearsched_spec.rb
Labels: Ready-to-Merge

#12221 check for actionable reviews with DuplicateEP errors
  app/jobs/data_integrity_checks_job.rb
  app/services/reviews_with_duplicate_ep_error_checker.rb
  spec/jobs/data_integrity_checks_job_spec.rb
  spec/services/reviews_with_duplicate_ep_error_checker_spec.rb
Labels: Ready-to-Merge

#12203 Set correct contention type when creating contention
  Gemfile
  Gemfile.lock
  app/models/board_grant_effectuation.rb
  app/models/end_product_establishment.rb
  app/models/request_issue.rb
  client/constants/CONTENTION_TYPES.json
  lib/fakes/vbms_service.rb
  spec/feature/intake/higher_level_review/edit_spec.rb
  spec/feature/intake/higher_level_review_spec.rb
  spec/feature/intake/supplemental_claim/edit_spec.rb
  spec/feature/intake/supplemental_claim_spec.rb
  spec/models/claim_review_spec.rb
  spec/models/decision_document_spec.rb
  spec/models/end_product_establishment_spec.rb
  spec/models/higher_level_review_intake_spec.rb
  spec/models/request_issues_update_spec.rb
  spec/models/supplemental_claim_intake_spec.rb
Labels: Ready-to-Merge

#12223 Allow vso admins to see other vso user's tasks and reassign them
  app/models/task.rb
  app/models/tasks/informal_hearing_presentation_task.rb
  app/workflows/tasks_for_appeal.rb
  spec/models/tasks/informal_hearing_presentation_task_spec.rb
Labels: Ready-to-Merge

#12224 Add Appeal.stuck? method, small refactors
  app/models/appeal.rb
  app/queries/appeals_with_no_tasks_or_all_tasks_on_hold_query.rb
  spec/models/appeal_spec.rb
  spec/queries/appeals_with_no_tasks_or_all_tasks_on_hold_query_spec.rb
Labels: Ready-to-Merge

#12198 add aria attributes to table header to reduce verbosity
  client/app/queue/QueueTable.jsx
Labels: Ready-to-Merge

#12205 Batch calls to users table
  app/models/user.rb
  app/repositories/attorney_repository.rb
  app/repositories/judge_repository.rb
  app/repositories/user_repository.rb
  spec/models/user_spec.rb
  spec/repositories/attorney_repository_spec.rb
  spec/repositories/judge_repository_spec.rb
Labels: Ready-to-Merge

#12226 Cache of hearing facility addresses
  app/models/hearing_location.rb
  app/serializers/api/v2/hearing_serializer.rb
  client/constants/REGIONAL_OFFICE_FACILITY_ADDRESS.json
  spec/models/hearing_location_spec.rb
Labels: Ready-to-Merge

#12192 Enable paper_trail for Tasks
  app/models/appeal.rb
  app/models/concerns/has_task_history.rb
  app/models/legacy_appeal.rb
  app/models/task.rb
  app/models/task_event.rb
  app/services/appeal_task_history.rb
  config/initializers/paper_trail.rb
  db/migrate/20190924110338_add_paper_trail_changeset.rb
  db/schema.rb
  spec/feature/queue/ama_queue_spec.rb
  spec/services/appeal_task_history_spec.rb
Labels: Ready-to-Merge

#12234 Set current_user for data integrity checks
  app/jobs/data_integrity_checks_job.rb
Labels: Ready-to-Merge

#12213 Fix DOM element bugs with paginated queues
  app/controllers/organizations/task_pages_controller.rb
  app/models/task_pager.rb
  client/app/queue/QueueTable.jsx
  spec/controllers/organizations/task_pages_controller_spec.rb
  spec/feature/queue/task_queue_spec.rb
  spec/models/task_pager_spec.rb
Labels: Ready-to-Merge

#12232 consider modifiers on recently closed claims taken
  app/models/end_product.rb
  app/services/reviews_with_duplicate_ep_error_checker.rb
  app/workflows/end_product_modifier_finder.rb
  spec/models/end_product_establishment_spec.rb
Labels: Ready-to-Merge

#12193 Monthly metrics job
  .reek.yml
  app/jobs/monthly_metrics_report_job.rb
  app/services/claim_review_async_stats_reporter.rb
  spec/services/claim_review_async_stats_reporter_spec.rb
Labels: Ready-to-Merge

#12249 Fix security warning
  Gemfile.lock
  spec/feature/hearings/edit_hearing_day_spec.rb
  spec/feature/hearings/remove_hearing_day_spec.rb
Labels: Ready-to-Merge

#12248 Reorganize class, lints
  .reek.yml
  app/models/task.rb
Labels: Ready-to-Merge

#12250 Increase timeout for fetching RO offices
  client/app/hearings/containers/AssignHearingsContainer.jsx
Labels: Ready-to-Merge

#12253 Override name/address/zip for vba_372
  .reek.yml
  app/models/hearing_location.rb
  client/constants/REGIONAL_OFFICE_FACILITY_ADDRESS.json
  client/constants/REGIONAL_OFFICE_INFORMATION.json
  spec/models/hearing_location_spec.rb
Labels: Ready-to-Merge
