Repository department-of-veterans-affairs/caseflow, pull requests merged in 2019-06, with the labels that each got.

#10976 Remove errant brace character
  client/app/queue/OrganizationQueue.jsx
  client/app/queue/OrganizationQueueLoadingScreen.jsx
Labels: Ready-to-Merge

#10981 Temporary fix for db/seeds
  db/seeds.rb
Labels: Ready-to-Merge

#10905 Update task taxonomy
  app/controllers/decision_reviews_controller.rb
  app/controllers/idt/api/v1/appeals_controller.rb
  app/jobs/hearing_disposition_change_job.rb
  app/jobs/update_appellant_representation_job.rb
  app/models/api_status_alerts.rb
  app/models/appeal.rb
  app/models/colocated_task_distributor.rb
  app/models/hearing.rb
  app/models/legacy_hearing.rb
  app/models/queues/attorney_queue.rb
  app/models/request_issue.rb
  app/models/task.rb
  app/models/task_timer.rb
  app/models/tasks/attorney_task.rb
  app/models/tasks/colocated_task.rb
  app/models/tasks/disposition_task.rb
  app/models/tasks/generic_task.rb
  app/models/tasks/hearing_admin_action_task.rb
  app/models/tasks/hearing_task.rb
  app/models/tasks/mail_task.rb
  app/models/tasks/root_task.rb
  app/models/tasks/schedule_hearing_task.rb
  app/models/tasks/timed_hold_task.rb
  app/models/tasks/track_veteran_task.rb
  app/services/va_dot_gov_address_validator.rb
  app/workflows/bulk_task_assignment.rb
  spec/feature/queue/hearings_tasks_spec.rb
  spec/feature/queue/task_queue_spec.rb
  spec/jobs/hearing_disposition_change_job_spec.rb
  spec/models/task_spec.rb
  spec/models/tasks/generic_task_spec.rb
  spec/models/tasks/hearing_task_spec.rb
  spec/models/tasks/no_show_hearing_task_spec.rb
  spec/models/tasks/schedule_hearing_task_spec.rb
  spec/models/tasks/timed_hold_task_spec.rb
  spec/models/tasks/track_veteran_task_spec.rb
  spec/models/tasks/transcription_task_spec.rb
Labels: Ready-to-Merge

#10962 Store POA at time of dispatch in Appeals table
  app/workflows/ama_appeal_dispatch.rb
  db/migrate/20190531152758_add_poa_participant_id_to_appeal.rb
  db/schema.rb
  spec/workflows/ama_appeal_dispatch_spec.rb
Labels: Ready-to-Merge

#10858 refactor upcoming_days_for_vso_user
  app/models/hearing_day.rb
  spec/models/hearing_day_spec.rb
Labels: Ready-to-Merge, tango

#10895 Remove ACD feature toggles
  app/models/concerns/legacy_case_distribution.rb
  app/models/distribution.rb
  app/workflows/initial_tasks_factory.rb
  db/seeds.rb
  scripts/enable_features_dev.rb
  spec/feature/hearings/postpone_hearing_spec.rb
  spec/feature/hearings/schedule_veteran_spec.rb
  spec/feature/queue/judge_assignment_spec.rb
  spec/models/appeal_intake_spec.rb
  spec/models/appeal_spec.rb
  spec/models/distribution_spec.rb
  spec/models/docket_coordinator_spec.rb
  spec/models/docket_spec.rb
  spec/models/dockets/direct_review_docket_spec.rb
  spec/models/dockets/hearing_request_docket_spec.rb
  spec/models/tasks/evidence_submission_window_task_spec.rb
  spec/models/tasks/informal_hearing_presentation_task_spec.rb
  spec/models/tasks/schedule_hearing_task_spec.rb
  spec/workflows/initial_tasks_factory_spec.rb
Labels: Ready-to-Merge

#10979 Add efolder_documents_fetched_at to users table
  app/jobs/fetch_documents_for_reader_user_job.rb
  app/jobs/retrieve_documents_for_reader_job.rb
  app/queries/batch_users_for_reader_query.rb
  db/migrate/20190603150958_add_efolder_documents_fetched_at_to_users.rb
  db/schema.rb
  spec/jobs/fetch_documents_for_reader_user_spec.rb
  spec/jobs/retrieve_documents_for_reader_job_spec.rb
  spec/models/user_spec.rb
  spec/queries/batch_users_for_reader_query_spec.rb
Labels: Ready-to-Merge

#10988 Organization clean_url means voc_rehab -> voc-rehab
  app/models/concerns/has_business_line.rb
Labels: Ready-to-Merge

#10987 Get Person Id from Participant Id for Hearings AOD
  app/models/hearing.rb
  spec/feature/hearings/daily_docket_spec.rb
Labels: Ready-to-Merge

#10983 Use established modal pattern for bulk task assignment
  app/controllers/bulk_task_assignments_controller.rb
  app/workflows/bulk_task_assignment.rb
  client/app/queue/OrganizationQueue.jsx
  client/app/queue/QueueApp.jsx
  client/app/queue/components/BulkAssignButton.jsx
  client/app/queue/components/BulkAssignModal.jsx
  config/routes.rb
  spec/controllers/bulk_task_assignments_controller_spec.rb
  spec/feature/queue/hearings_tasks_spec.rb
  spec/workflows/bulk_task_assignment_spec.rb
Labels: Ready-to-Merge

#10949 Add not null db constraint to tasks.assigned_to_id
  db/migrate/20190530185719_add_not_null_task_assigned_to.rb
  db/schema.rb
  spec/models/task_spec.rb
Labels: Ready-to-Merge

#11000 Build schedule fixes
  app/controllers/hearings/schedule_periods_controller.rb
  client/app/hearings/containers/BuildScheduleUploadContainer.jsx
  spec/controllers/hearings/schedule_periods_controller_spec.rb
  spec/feature/hearings/build_schedule_spec.rb
Labels: Ready-to-Merge

#10392 Add Docket Cutoff Lines to Assign Hearings Page
  app/models/serializers/work_queue/appeal_serializer.rb
  app/models/serializers/work_queue/legacy_appeal_serializer.rb
  app/models/serializers/work_queue/legacy_task_serializer.rb
  app/models/serializers/work_queue/task_serializer.rb
  client/app/hearings/components/AssignHearingsDocketLine.jsx
  client/app/hearings/components/AssignHearingsTabs.jsx
Labels: In-Progress, Ready-to-Merge

#10999 Update auto case distribution specs
  spec/feature/queue/judge_assignment_spec.rb
  spec/models/distribution_spec.rb
Labels: Ready-to-Merge

#10966 Consolidating backend hp/hs code
  app/controllers/concerns/hearings_concerns.rb
  app/controllers/hearing_schedule_controller.rb
  app/controllers/hearings/appeals_controller.rb
  app/controllers/hearings/hearing_day_controller.rb
  app/controllers/hearings/schedule_periods_controller.rb
  app/controllers/hearings/worksheets_controller.rb
  app/controllers/hearings_application_controller.rb
  app/controllers/hearings_controller.rb
  app/mappers/travel_board_schedule_mapper.rb
  app/models/hearing.rb
  app/models/legacy_appeal.rb
  app/models/legacy_hearing.rb
  app/models/vacols/case_hearing.rb
  app/models/vacols/travel_board_schedule.rb
  app/repositories/hearing_repository.rb
  app/services/hearing_schedule/generate_hearing_days_schedule.rb
  config/routes.rb
  lib/generators/legacy_hearing.rb
  spec/controllers/hearings_application_controller_spec.rb
  spec/models/hearing_day_spec.rb
  spec/models/vacols/case_hearing_spec.rb
  spec/repositories/hearing_repository_spec.rb
Labels: Ready-to-Merge

#11012 prepare establish claim error
  app/models/establish_claim.rb
Labels: Ready-to-Merge

#11013 Add VBMSError:: FileNumberNotFoundForClaimId exception class
  app/exceptions/vbms_error.rb
Labels: Ready-to-Merge

#11014 fix request store application check
  app/models/legacy_appeal.rb
Labels: Ready-to-Merge

#11015 Categorize VBMS error
  app/exceptions/vbms_error.rb
Labels: Ready-to-Merge

#11005 Remove automatic_case_distribution feature flag references
  app/controllers/distributions_controller.rb
  app/views/queue/index.html.erb
  client/app/queue/components/AssignWidget.jsx
  scripts/enable_features_dev.rb
  spec/controllers/distributions_controller_spec.rb
  spec/feature/queue/judge_assignment_spec.rb
Labels: Ready-to-Merge

#10977 Move ACD scopes from Appeal to Docket
  app/models/appeal.rb
  app/models/docket.rb
  app/models/docket_coordinator.rb
  app/models/dockets/direct_review_docket.rb
  spec/feature/queue/judge_assignment_spec.rb
  spec/models/appeal_spec.rb
  spec/models/distribution_spec.rb
  spec/models/docket_coordinator_spec.rb
  spec/models/docket_spec.rb
  spec/models/dockets/hearing_request_docket_spec.rb
Labels: Ready-to-Merge

#11018 Speed up Quality Review feature test
  spec/feature/queue/quality_review_flow_spec.rb
Labels: Ready-to-Merge

#10992 Add warning message for invalid withdrawal date
  client/app/intake/pages/addIssues.jsx
  spec/feature/intake/appeal/edit_spec.rb
Labels: Ready-to-Merge

#11008 Move task subclasses into their own files
  app/models/tasks/address_change_mail_task.rb
  app/models/tasks/aod_motion_mail_task.rb
  app/models/tasks/appeal_withdrawal_mail_task.rb
  app/models/tasks/clear_and_unmistakeable_error_mail_task.rb
  app/models/tasks/congressional_interest_mail_task.rb
  app/models/tasks/controlled_correspondence_mail_task.rb
  app/models/tasks/death_certificate_mail_task.rb
  app/models/tasks/evidence_or_argument_mail_task.rb
  app/models/tasks/extension_request_mail_task.rb
  app/models/tasks/foia_request_mail_task.rb
  app/models/tasks/hearing_admin_action_contested_claimant_task.rb
  app/models/tasks/hearing_admin_action_foia_privacy_request_task.rb
  app/models/tasks/hearing_admin_action_incarcerated_veteran_task.rb
  app/models/tasks/hearing_admin_action_missing_forms_task.rb
  app/models/tasks/hearing_admin_action_other_task.rb
  app/models/tasks/hearing_admin_action_task.rb
  app/models/tasks/hearing_admin_action_verify_poa_task.rb
  app/models/tasks/hearing_related_mail_task.rb
  app/models/tasks/mail_task.rb
  app/models/tasks/other_motion_mail_task.rb
  app/models/tasks/power_of_attorney_related_mail_task.rb
  app/models/tasks/privacy_act_request_mail_task.rb
  app/models/tasks/privacy_complaint_mail_task.rb
  app/models/tasks/reconsideration_motion_mail_task.rb
  app/models/tasks/returned_undeliverable_correspondence_mail_task.rb
  app/models/tasks/status_inquiry_mail_task.rb
  app/models/tasks/vacate_motion_mail_task.rb
  db/seeds.rb
  spec/controllers/tasks_controller_spec.rb
  spec/feature/queue/mail_task_spec.rb
  spec/models/task_spec.rb
  spec/models/tasks/mail_task_spec.rb
Labels: Ready-to-Merge

#11024 Ktipton/10645 node tar
  client/yarn.lock
Labels: Ready-to-Merge, batteam

#10932 Fix timed hold task cancellation behaviour
  app/models/task.rb
  app/models/tasks/colocated_task.rb
  app/models/tasks/hearing_admin_action_task.rb
  spec/feature/queue/quality_review_flow_spec.rb
  spec/models/task_spec.rb
Labels: Ready-to-Merge

#11017 Return promise function to org queue loading component
  client/app/queue/OrganizationQueueLoadingScreen.jsx
  client/app/queue/utils.js
  spec/models/task_spec.rb
Labels: Ready-to-Merge

#11027 Add update assign RO to legacy appeal
  app/models/appeal.rb
  app/models/tasks/hearing_admin_action_foreign_veteran_case_task.rb
  app/models/tasks/hearing_admin_action_verify_address_task.rb
  app/services/va_dot_gov_address_validator.rb
  spec/models/tasks/hearing_admin_action_verify_address_task_spec.rb
Labels: Ready-to-Merge

#11034 Remove unused function argument
  app/models/tasks/address_change_mail_task.rb
  app/models/tasks/aod_motion_mail_task.rb
  app/models/tasks/appeal_withdrawal_mail_task.rb
  app/models/tasks/clear_and_unmistakeable_error_mail_task.rb
  app/models/tasks/congressional_interest_mail_task.rb
  app/models/tasks/controlled_correspondence_mail_task.rb
  app/models/tasks/death_certificate_mail_task.rb
  app/models/tasks/evidence_or_argument_mail_task.rb
  app/models/tasks/extension_request_mail_task.rb
  app/models/tasks/foia_request_mail_task.rb
  app/models/tasks/hearing_related_mail_task.rb
  app/models/tasks/mail_task.rb
  app/models/tasks/other_motion_mail_task.rb
  app/models/tasks/power_of_attorney_related_mail_task.rb
  app/models/tasks/privacy_act_request_mail_task.rb
  app/models/tasks/privacy_complaint_mail_task.rb
  app/models/tasks/reconsideration_motion_mail_task.rb
  app/models/tasks/returned_undeliverable_correspondence_mail_task.rb
  app/models/tasks/status_inquiry_mail_task.rb
  app/models/tasks/vacate_motion_mail_task.rb
Labels: Ready-to-Merge

#11033 Add decision issues back to case details
  client/app/queue/components/CaseDetailsIssueList.jsx
  spec/feature/queue/attorney_checkout_flow_spec.rb
Labels: Ready-to-Merge

#10926 Change Task Type - Back End
  app/controllers/tasks/change_type_controller.rb
  app/models/task.rb
  app/models/tasks/colocated_task.rb
  app/models/tasks/mail_task.rb
  client/app/queue/ChangeTaskTypeModal.jsx
  config/routes.rb
  spec/controllers/tasks/change_type_controller_spec.rb
  spec/feature/queue/colocated_checkout_flow_spec.rb
  spec/feature/queue/colocated_task_queue_spec.rb
  spec/feature/queue/mail_task_spec.rb
  spec/models/task_spec.rb
  spec/models/tasks/mail_task_spec.rb
Labels: Ready-to-Merge

#11038 Use Right Prop Name for onChange on Hearing Day Nav
  client/app/hearings/components/AssignHearings.jsx
Labels: Ready-to-Merge

#11039 Compare Appeal's Closest Regional Office to Determine if Dropdown Should Be Dynamic
  client/app/hearings/components/dailyDocket/DailyDocketRowInputs.jsx
  client/app/hearings/components/modalForms/AssignHearingForm.jsx
  client/app/queue/components/PostponeHearingModal.jsx
Labels: Ready-to-Merge

#11046 add yarn install to the make install target
  Makefile.example
Labels: Ready-to-Merge

#11059 Refactor Timeout Calculation
  client/app/hearings/containers/ListScheduleContainer.jsx
  client/app/queue/AppealDocumentCount.jsx
  client/app/queue/OrganizationQueueLoadingScreen.jsx
  client/app/queue/QueueActions.js
  client/app/queue/QueueLoadingScreen.jsx
  client/app/queue/SpecialIssueLoadingScreen.jsx
  client/app/util/DateUtil.js
Labels: Ready-to-Merge

#11067 Remove VLJ and attorney names from case title for removed appeals
  app/models/serializers/work_queue/appeal_serializer.rb
  client/app/queue/CaseTitleDetails.jsx
  client/app/queue/utils.js
  spec/feature/queue/case_details_spec.rb
Labels: Ready-to-Merge

#11064 Withdrawn mail task routing
  app/models/tasks/appeal_withdrawal_mail_task.rb
  db/seeds.rb
  spec/models/tasks/mail_task_spec.rb
Labels: Ready-to-Merge

#11065 only re-use modifiers for CLR EPs
  app/models/end_product.rb
  app/models/end_product_establishment.rb
  spec/models/end_product_establishment_spec.rb
Labels: Ready-to-Merge

#11071 Add training video for non-comp
  client/app/help/components/IntakeHelp.jsx
Labels: Ready-to-Merge

#11074 Edit contention text confirmation message
  client/app/intake/pages/decisionReviewEditCompleted.jsx
  spec/feature/intake/higher_level_review/edit_spec.rb
Labels: Ready-to-Merge

#11076 Only show AOD tasks for hearings management, temporary
  app/controllers/organizations/tasks_controller.rb
  spec/feature/queue/case_details_spec.rb
  spec/feature/queue/quality_review_flow_spec.rb
  spec/feature/queue/task_queue_spec.rb
Labels: Ready-to-Merge

#11085 Segregate ui tests from non ui tests without using tags
  spec/feature/hearings/hearing_admin_action_foreign_veteran_case_task_spec.rb
  spec/feature/hearings/hearing_admin_action_verify_address_task_spec.rb
  spec/models/tasks/hearing_admin_action_foreign_veteran_case_task_spec.rb
  spec/models/tasks/hearing_admin_action_verify_address_task_spec.rb
Labels: Ready-to-Merge

#11088 TaskTimer should clean up its errors when processed successfully
  app/jobs/task_timer_job.rb
Labels: Ready-to-Merge

#11090 Rename Hearing Management to Hearings Management as it is in plural i…
  app/models/organizations/hearings_management.rb
  client/app/queue/ColocatedTaskListView.jsx
  client/app/queue/OrganizationQueue.jsx
  spec/factories/organization.rb
  spec/feature/queue/hearings_tasks_spec.rb
Labels: Ready-to-Merge

#11068 AsyncableJobsReporter as_csv
  .reek.yml
  app/services/asyncable_jobs_reporter.rb
  spec/services/asyncable_jobs_reporter_spec.rb
Labels: Ready-to-Merge

#11089 Prevent intake using reserved file number
  app/models/intake.rb
  client/app/intake/pages/search.jsx
  spec/controllers/intakes_controller_spec.rb
  spec/feature/intake/intake_spec.rb
Labels: Ready-to-Merge

#11099 Remove ReaderUser class
  app/models/users/reader_user.rb
  app/services/user_reporter.rb
  lib/generators/reader_user.rb
  spec/models/reader_user_spec.rb
Labels: Ready-to-Merge

#11066 Legacy hearings load appellant address and poa info from BGS instead of VACOLS
  app/models/appeal.rb
  app/models/concerns/associated_vacols_model.rb
  app/models/hearing.rb
  app/models/legacy_appeal.rb
  app/models/legacy_hearing.rb
  app/models/serializers/work_queue/legacy_appeal_serializer.rb
  app/repositories/hearing_repository.rb
  app/services/appeal_repository.rb
  client/app/hearings/components/dailyDocket/DailyDocketRowDisplayText.jsx
  config/initializers/constants.rb
  lib/fakes/bgs_service.rb
  lib/fakes/constants/BGS_SERVICE.json
  spec/feature/hearings/daily_docket_spec.rb
  spec/feature/hearings/schedule_veteran_spec.rb
  spec/models/concerns/associated_vacols_model_spec.rb
  spec/models/legacy_hearing_spec.rb
  spec/models/serializers/work_queue/legacy_appeal_serializer_spec.rb
  spec/repositories/hearing_repository_spec.rb
  spec/services/appeal_repository_spec.rb
Labels: Ready-to-Merge

#11095 Capture error if RI doesn't have an associated rating
  app/models/request_issue.rb
  spec/models/request_issue_spec.rb
Labels: Ready-to-Merge

#11101 Drop reader users table
  db/migrate/20190617164845_drop_reader_user_table.rb
  db/schema.rb
Labels: Ready-to-Merge

#11100 Adding unique constraint for hearings vacols_ids
  db/migrate/20190617152134_add_unique_constraint_hearings_vacols_ids.rb
  db/schema.rb
Labels: Ready-to-Merge

#11098 Canceled hearings - require Evidence Submission Window Tasks
  app/models/tasks/disposition_task.rb
  spec/models/tasks/disposition_task_spec.rb
Labels: Ready-to-Merge

#11072 Veteran Search by SSN or File Number
  app/controllers/appeals_controller.rb
  app/models/claim_review.rb
  app/models/legacy_appeal.rb
  app/models/veteran.rb
  app/services/appeal_finder.rb
  app/services/veteran_finder.rb
  app/validators/validate_vso_employee_can_access_file_number.rb
  app/workflows/appeals_for_file_number.rb
  app/workflows/case_search_results_base.rb
  app/workflows/case_search_results_for_caseflow_veteran_id.rb
  app/workflows/case_search_results_for_veteran_file_number.rb
  client/COPY.json
  spec/controllers/appeals_controller_spec.rb
  spec/factories/veteran.rb
Labels: Ready-to-Merge

#11030 Update contention text in VBMS in request issues update
  app/models/contention.rb
  app/models/end_product_establishment.rb
  app/models/request_issue.rb
  app/models/request_issue_contention.rb
  app/models/request_issues_update.rb
  db/migrate/20190605211054_add_contention_updated_at_to_request_issue.rb
  db/schema.rb
  spec/models/end_product_establishment_spec.rb
  spec/models/request_issue_contention_spec.rb
  spec/models/request_issue_spec.rb
  spec/models/request_issues_update_spec.rb
Labels: Ready-to-Merge

#11110 Soft restriction on creating duplicate colocated tasks
  app/controllers/application_controller.rb
  app/controllers/hearings/hearing_day_controller.rb
  app/models/tasks/colocated_task.rb
  app/workflows/complete_case_review.rb
  app/workflows/update_attorney_case_review.rb
  app/workflows/update_legacy_attorney_case_review.rb
  client/COPY.json
  spec/feature/queue/case_assignment_spec.rb
  spec/models/tasks/colocated_task_spec.rb
Labels: Ready-to-Merge

#11096 Add incident flash error
  app/models/intake.rb
  app/models/veteran.rb
  client/COPY.json
  client/app/intake/pages/search.jsx
  spec/feature/intake/intake_spec.rb
Labels: Ready-to-Merge

#10936 update docker-demo
  docker-compose-demo.yml
Labels: Ready-to-Merge

#11117 Caseflow Demo Dockerized needed some love
  docker-bin/startup.sh
  docker-compose-demo.yml
Labels: Ready-to-Merge

#11123 FACOLS is taking longer to start
  docker-bin/startup.sh
Labels: Ready-to-Merge

#11115 Anya/7378 decision dates in future
  .codeclimate.yml
  client/app/intake/components/NonratingRequestIssueModal.jsx
  client/app/intake/util/issues.js
  spec/feature/intake/higher_level_review_spec.rb
Labels: Ready-to-Merge

#11127 Add missing indexes on tasks
  db/migrate/20190618173816_add_tasks_indexes.rb
  db/schema.rb
Labels: Ready-to-Merge

#11126 revert legacy appeals & hearings pull address and POA from BGS
  app/models/legacy_appeal.rb
  app/models/legacy_hearing.rb
  app/models/serializers/work_queue/legacy_appeal_serializer.rb
  app/repositories/hearing_repository.rb
  app/services/appeal_repository.rb
  spec/feature/hearings/daily_docket_spec.rb
  spec/feature/hearings/schedule_veteran_spec.rb
  spec/models/serializers/work_queue/legacy_appeal_serializer_spec.rb
Labels: Ready-to-Merge

#11131 disable flakey test
  spec/models/docket_spec.rb
Labels: Ready-to-Merge

#11105 Include tasks as element in QueueConfig
  app/controllers/organizations/tasks_controller.rb
  app/models/organization.rb
  app/models/queue_config.rb
  app/models/queues/generic_queue.rb
  app/models/representative.rb
  spec/models/queue_config_spec.rb
  spec/models/queues/generic_queue_spec.rb
Labels: Ready-to-Merge

#11134 Add test to confirm ColocatedTasks charge to correct VACOLS user
  spec/models/tasks/colocated_task_spec.rb
Labels: Ready-to-Merge

#11133 Finish establishment processing if EP is inactive
  app/models/claim_review.rb
  app/models/end_product_establishment.rb
  app/models/higher_level_review.rb
  spec/feature/queue/search_spec.rb
  spec/models/claim_review_spec.rb
Labels: Ready-to-Merge

#10889 Allow TaskActions to change label and URL in repository functions
  app/helpers/task_action_helper.rb
  app/models/task.rb
  app/models/tasks/attorney_task.rb
  app/models/tasks/change_hearing_disposition_task.rb
  app/models/tasks/colocated_task.rb
  app/models/tasks/generic_task.rb
  app/models/tasks/hearing_admin_action_foreign_veteran_case_task.rb
  app/models/tasks/hearing_admin_action_task.rb
  app/models/tasks/informal_hearing_presentation_task.rb
  app/models/tasks/judge_task.rb
  app/models/tasks/privacy_act_task.rb
  app/models/tasks/quality_review_task.rb
  app/models/tasks/schedule_hearing_task.rb
  app/models/tasks/transcription_task.rb
  app/repositories/task_action_repository.rb
  client/constants/TASK_ACTIONS.json
  spec/feature/queue/task_queue_spec.rb
  spec/models/tasks/generic_task_spec.rb
  spec/models/tasks/hearing_admin_action_foreign_veteran_case_task_spec.rb
  spec/models/tasks/informal_hearing_presentation_task_spec.rb
  spec/models/tasks/judge_dispatch_return_task_spec.rb
  spec/models/tasks/judge_quality_review_task_spec.rb
  spec/models/tasks/privacy_act_task_spec.rb
Labels: Ready-to-Merge

#10940 add classes to task factories
  spec/controllers/decision_reviews_controller_spec.rb
  spec/factories/task.rb
  spec/feature/queue/attorney_queue_spec.rb
  spec/feature/queue/task_queue_spec.rb
  spec/models/queues/attorney_queue_spec.rb
  spec/models/serializers/work_queue/decision_review_task_serializer_spec.rb
  spec/models/serializers/work_queue/veteran_record_request_serializer_spec.rb
  spec/models/task_spec.rb
  spec/models/tasks/board_grant_effectuation_task_spec.rb
  spec/models/tasks/colocated_task_spec.rb
  spec/models/tasks/decision_review_task_spec.rb
  spec/models/tasks/judge_task_spec.rb
Labels: Ready-to-Merge

#11130 SSN and File Number Search - Frontend
  app/controllers/appeals_controller.rb
  app/validators/validate_vso_employee_can_access_file_number.rb
  app/workflows/case_search_results_base.rb
  app/workflows/case_search_results_for_caseflow_veteran_id.rb
  app/workflows/case_search_results_for_veteran_file_number.rb
  client/app/queue/CaseList/CaseListActions.js
  client/app/queue/CaseListSearch.jsx
  client/app/queue/CaseListView.jsx
  client/app/queue/QueueApp.jsx
  config/routes.rb
  spec/controllers/appeals_controller_spec.rb
Labels: Ready-to-Merge

#11142 Use CacheManager rather than blindly nuking Redis on re-seed
  db/seeds.rb
Labels: Ready-to-Merge

#11145 Make shared examples name for Verify Address Task unique
  spec/feature/hearings/hearing_admin_action_verify_address_task_spec.rb
Labels: Ready-to-Merge

#11150 turn on BGS POA for appeals docket
  app/controllers/appeals_controller.rb
Labels: Ready-to-Merge

#11146 Fix bugs around bulk assignment UI and write more feature tests
  app/workflows/bulk_task_assignment.rb
  client/app/queue/components/BulkAssignModal.jsx
  db/seeds.rb
  spec/factories/task.rb
  spec/feature/queue/bulk_task_assignment_spec.rb
  spec/feature/queue/hearings_tasks_spec.rb
  spec/workflows/bulk_task_assignment_spec.rb
Labels: Ready-to-Merge

#11144 Fix Same Day Postponement Bug
  app/repositories/hearing_repository.rb
  spec/feature/hearings/postpone_hearing_spec.rb
Labels: Ready-to-Merge

#11141 Fix Hearing Location on Hearing Details
  .reek.yml
  app/models/hearing.rb
  app/models/legacy_hearing.rb
  app/serializers/hearings/hearing_serializer.rb
  app/serializers/hearings/hearing_serializer_base.rb
  app/serializers/hearings/legacy_hearing_serializer.rb
  client/app/hearings/components/AssignHearingsTabs.jsx
  config/application.rb
  spec/models/hearing_day_spec.rb
Labels: Ready-to-Merge

#11080 Fix decision date
  client/app/queue/components/TaskRows.jsx
Labels: Ready-to-Merge

#11140 Close JudgeAssignTasks upon creating AttorneyTasks rather than changing them to JudgeDecisionReviewTasks
  app/controllers/judge_assign_tasks_controller.rb
  app/models/tasks/judge_assign_task.rb
  db/seeds.rb
  spec/controllers/case_reviews_controller_spec.rb
  spec/controllers/idt/api/appeals_controller_spec.rb
  spec/controllers/judge_assign_tasks_controller_spec.rb
  spec/factories/task.rb
  spec/feature/queue/attorney_checkout_flow_spec.rb
  spec/feature/queue/attorney_queue_spec.rb
  spec/feature/queue/case_details_spec.rb
  spec/feature/queue/quality_review_flow_spec.rb
  spec/models/tasks/attorney_task_spec.rb
  spec/models/tasks/judge_quality_review_task_spec.rb
  spec/models/tasks/judge_task_spec.rb
Labels: Ready-to-Merge

#11160 Fix loading button when required fields are missing
  client/app/queue/components/BulkAssignModal.jsx
  spec/feature/queue/bulk_task_assignment_spec.rb
Labels: Ready-to-Merge

#11153 Add logging for ColocatedTask VACOLS location bug
  app/models/tasks/colocated_task.rb
Labels: Ready-to-Merge

#11019 Refactor nonpriority_receipts_per_year
  app/models/docket.rb
  app/models/dockets/direct_review_docket.rb
  spec/models/dockets/direct_review_docket_spec.rb
Labels: Ready-to-Merge, auto-case-distribution

#11155 hardcode limit on tasks returned by /organizations/tasks endpoint
  app/controllers/organizations/tasks_controller.rb
  app/models/appeal.rb
  app/models/queues/generic_queue.rb
Labels: Ready-to-Merge

#11143 Re-enable BGS lookup for POA
  app/controllers/api/v1/jobs_controller.rb
  app/jobs/warm_bgs_participant_caches_job.rb
  app/models/legacy_appeal.rb
  app/models/legacy_hearing.rb
  app/models/serializers/work_queue/legacy_appeal_serializer.rb
  app/repositories/hearing_repository.rb
  app/services/appeal_repository.rb
  app/services/bgs_address_service.rb
  app/services/bgs_power_of_attorney.rb
  app/services/cache_manager.rb
  spec/feature/hearings/daily_docket_spec.rb
  spec/feature/hearings/schedule_veteran_spec.rb
  spec/jobs/warm_bgs_participant_caches_job_spec.rb
  spec/models/serializers/work_queue/legacy_appeal_serializer_spec.rb
Labels: Ready-to-Merge

#11156 VeteranFinder.find_or_create
  app/models/veteran.rb
  app/services/appeal_finder.rb
  app/services/veteran_finder.rb
  app/workflows/case_search_results_for_veteran_file_number.rb
  spec/controllers/appeals_controller_spec.rb
  spec/services/veteran_finder_spec.rb
Labels: Ready-to-Merge

#11149 Load queue configuration from backend/Redux store.
  client/app/queue/OrganizationQueue.jsx
  client/app/queue/OrganizationQueueLoadingScreen.jsx
Labels: Ready-to-Merge

#11164 Add some profiling statements, bump limit down
  app/controllers/organizations/tasks_controller.rb
  spec/feature/queue/ama_queue_spec.rb
  spec/feature/queue/bulk_task_assignment_spec.rb
Labels: Ready-to-Merge

#11172 Remove ColocatedTask logging to Sentry
  app/models/tasks/colocated_task.rb
Labels: Ready-to-Merge

#11136 Make legacy appeals with ssoc dates before ama ineligible for opt in
  app/models/legacy_appeal.rb
  spec/feature/intake/appeal/edit_spec.rb
  spec/feature/intake/appeal_spec.rb
  spec/feature/intake/higher_level_review/edit_spec.rb
  spec/feature/intake/higher_level_review_spec.rb
  spec/feature/intake/supplemental_claim/edit_spec.rb
  spec/models/legacy_appeal_spec.rb
  spec/support/date_time_helper.rb
Labels: Ready-to-Merge

#11138 Allow withdrawn appeals to be distributed
  app/models/appeal.rb
  app/models/claim_review.rb
  app/models/decision_review.rb
  app/models/request_issues_update.rb
  app/policies/withdrawn_decision_review_policy.rb
  app/services/appeal_active_task_cancellation.rb
  app/services/claim_review_active_task_cancellation.rb
  app/workflows/request_issue_withdrawal.rb
  spec/feature/intake/higher_level_review/edit_spec.rb
  spec/workflows/appeal_withdrawal_spec.rb
Labels: Ready-to-Merge

#11168 randomize SSN in specs
  app/models/veteran.rb
  app/services/veteran_finder.rb
  lib/fakes/bgs_service.rb
  lib/generators/veteran.rb
  spec/controllers/idt/api/veterans_controller_spec.rb
  spec/controllers/intakes_controller_spec.rb
  spec/factories/veteran.rb
  spec/feature/queue/search_spec.rb
  spec/models/veteran_spec.rb
Labels: Ready-to-Merge

#11182 lower queue task limit to 200
  app/controllers/organizations/tasks_controller.rb
Labels: Ready-to-Merge

#11148 Call Fakes::EndProductStore.new.clear! on re-seed
  db/seeds.rb
Labels: Ready-to-Merge

#11157 Remove instructions field from Transcription Modal
  app/repositories/task_action_repository.rb
  client/COPY.json
  client/app/queue/components/CompleteTaskModal.jsx
  spec/feature/queue/task_queue_spec.rb
  spec/feature/queue/transcription_team_spec.rb
Labels: Ready-to-Merge

#11163 Automatically add BGS VSO team members to the VSO team in Caseflow
  app/controllers/organizations_controller.rb
  spec/controllers/organizations_controller_spec.rb
Labels: Ready-to-Merge

#11165 Set application for IDT controllers to trigger BGS AOD lookup
  app/controllers/idt/api/v1/base_controller.rb
Labels: Ready-to-Merge

#11037 Add code quality docs
  docs/code-quality.md
Labels: Ready-to-Merge

#11171 Print task trees
  Gemfile
  Gemfile.lock
  app/models/appeal.rb
  app/models/concerns/prints_task_tree.rb
  app/models/legacy_appeal.rb
  app/models/task.rb
  spec/models/appeal_spec.rb
  spec/models/legacy_appeal_spec.rb
  spec/models/task_spec.rb
Labels: Ready-to-Merge

#11062 cancel icon
  client/COPY.json
  client/app/components/RenderFunctions.jsx
  client/app/queue/components/TaskRows.jsx
Labels: Ready-to-Merge

#11173 Fix tests in search spec
  spec/feature/queue/search_spec.rb
Labels: Ready-to-Merge

#11177 Only update VACOLS location for organization ColocatedTasks
  app/models/tasks/colocated_task.rb
  spec/feature/queue/task_queue_spec.rb
  spec/models/tasks/colocated_task_spec.rb
Labels: Ready-to-Merge

#11170 Specify that issue modal is nonrating
  client/app/intake/components/NonratingRequestIssueModal.jsx
  spec/feature/intake/appeal_spec.rb
  spec/feature/intake/higher_level_review/edit_spec.rb
  spec/feature/intake/higher_level_review_spec.rb
  spec/feature/intake/supplemental_claim/edit_spec.rb
  spec/support/intake_helpers.rb
Labels: Ready-to-Merge

#11185 Fix flakey bulk assignment test
  client/app/queue/components/BulkAssignModal.jsx
  spec/feature/queue/bulk_task_assignment_spec.rb
Labels: Ready-to-Merge

#11147 Reflect withdrawn appeals in Case Timeline
  app/models/decision_review.rb
  app/models/serializers/work_queue/appeal_serializer.rb
  client/COPY.json
  client/app/components/RenderFunctions.jsx
  client/app/queue/components/TaskRows.jsx
  client/app/queue/utils.js
  spec/feature/queue/case_details_spec.rb
Labels: Ready-to-Merge

#11137 Validate claimant address when address is present but fields are empty
  app/models/claimant.rb
  app/models/validators/claimant_validator.rb
  spec/feature/intake/review_page_spec.rb
  spec/models/higher_level_review_intake_spec.rb
  spec/models/supplemental_claim_intake_spec.rb
Labels: Ready-to-Merge

#11199 Shrink task window to 1 week, bump up limit to 400
  app/controllers/organizations/tasks_controller.rb
  app/models/queues/generic_queue.rb
  app/models/task.rb
  spec/controllers/organizations/tasks_controller_spec.rb
  spec/feature/hearings/daily_docket_spec.rb
  spec/feature/queue/case_details_spec.rb
Labels: Ready-to-Merge

#11203 Fix N+1 query in Organizations::TasksController
  app/models/queue_config.rb
  app/models/queues/generic_queue.rb
  app/models/task_pager.rb
Labels: Ready-to-Merge

#11184 Renaming DispositionTasks
  app/jobs/hearing_disposition_change_job.rb
  app/jobs/update_appellant_representation_job.rb
  app/models/hearing.rb
  app/models/legacy_hearing.rb
  app/models/tasks/assign_hearing_disposition_task.rb
  app/models/tasks/change_hearing_disposition_task.rb
  app/models/tasks/disposition_task.rb
  app/models/tasks/evidence_submission_window_task.rb
  app/models/tasks/hearing_task.rb
  app/models/tasks/schedule_hearing_task.rb
  app/models/tasks/transcription_task.rb
  db/seeds.rb
  lib/tasks/tasks.rake
  scripts/back_fill_hearing_task_associations.rb
  scripts/back_fill_hearing_tasks.rb
  spec/controllers/tasks_controller_spec.rb
  spec/factories/hearing.rb
  spec/factories/legacy_hearing.rb
  spec/factories/task.rb
  spec/feature/hearings/change_hearing_disposition_spec.rb
  spec/feature/hearings/daily_docket_spec.rb
  spec/feature/hearings/postpone_hearing_spec.rb
  spec/feature/queue/hearings_tasks_spec.rb
  spec/feature/queue/task_queue_spec.rb
  spec/feature/queue/transcription_team_spec.rb
  spec/jobs/hearing_disposition_change_job_spec.rb
  spec/jobs/update_appellant_representation_job_spec.rb
  spec/lib/tasks/tasks_spec.rb
  spec/models/appeal_spec.rb
  spec/models/legacy_hearing_spec.rb
  spec/models/task_spec.rb
  spec/models/tasks/assign_hearing_disposition_task_spec.rb
  spec/models/tasks/evidence_submission_window_task_spec.rb
  spec/models/tasks/generic_task_spec.rb
  spec/models/tasks/hearing_task_spec.rb
  spec/models/tasks/no_show_hearing_task_spec.rb
  spec/models/tasks/schedule_hearing_task_spec.rb
  spec/models/tasks/transcription_task_spec.rb
Labels: Ready-to-Merge

#11207 Ensure completed judge assign tasks do not appear in case timeline
  app/models/tasks/judge_assign_task.rb
  spec/feature/queue/case_details_spec.rb
Labels: Ready-to-Merge

#11209 Legacy opt in, do not connect to VACOLS if there aren't opt ins
  app/services/legacy_optin_manager.rb
Labels: Ready-to-Merge

#11211 Force vertical scrollbar on async job error strings
  client/app/styles/_jobs.scss
Labels: Ready-to-Merge

#11180 Update Appeal#withdrawn? to match latest requirements
  app/models/appeal.rb
  app/models/decision_review.rb
  app/policies/withdrawn_decision_review_policy.rb
  app/services/appeal_active_task_cancellation.rb
  spec/feature/queue/search_spec.rb
  spec/models/appeal_spec.rb
  spec/models/decision_review_spec.rb
  spec/policies/withdrawn_decision_review_policy_spec.rb
  spec/support/fake_decision_review.rb
Labels: Ready-to-Merge

#11215 Close EP400 request issues
  app/models/end_product_establishment.rb
  spec/models/end_product_establishment_spec.rb
Labels: Ready-to-Merge

#11212 Update support contact to point at YourIT
  app/controllers/test/users_controller.rb
  client/app/certification/components/ErrorMessage.jsx
  client/app/errors/Error500.jsx
  client/app/hearings/components/ReviewAssignments.jsx
  client/app/help/components/DispatchHelp.jsx
  client/app/help/components/HearingsHelp.jsx
  client/app/help/components/QueueHelp.jsx
  client/app/help/components/ReaderHelp.jsx
  client/app/intake/components/ErrorAlert.jsx
  client/app/intake/pages/search.jsx
  client/app/intakeEdit/IntakeEditFrame.jsx
  client/app/nonComp/components/Alerts.jsx
  config/routes.rb
Labels: Ready-to-Merge

#11217 Avoid serializing tasks 2x unless feature use_task_pages_api
  app/models/queue_config.rb
  spec/models/queue_config_spec.rb
Labels: Ready-to-Merge

#11218 Fix table filtering
  client/app/components/TableFilter.jsx
  client/app/queue/OrganizationQueue.jsx
  client/app/queue/QueueTable.jsx
  client/app/queue/components/TaskTable.jsx
  client/app/queue/constants.js
Labels: Ready-to-Merge

#11219 Add correction EP codes
  .codeclimate.yml
  .reek.yml
  app/models/board_grant_effectuation.rb
  app/models/end_product.rb
  spec/models/board_grant_effectuation_spec.rb
Labels: Ready-to-Merge

#11224 Add failing test to show where flake is
  spec/feature/queue/bulk_task_assignment_spec.rb
  spec/rails_helper.rb
Labels: Ready-to-Merge

#11227 Increase page size limit for org tasks
  app/controllers/organizations/tasks_controller.rb
Labels: Ready-to-Merge

#11228 Hide reader link from VSO org queues
  app/models/queue_config.rb
Labels: Ready-to-Merge

#11179 Fix Makefile for FACOLS db seeds
  Makefile.example
Labels: Ready-to-Merge

#11208 Yank jquery-rails gem
  Gemfile
  Gemfile.lock
Labels: Ready-to-Merge

#11210 Allow Case Review members to edit request issues
  app/models/serializers/work_queue/appeal_serializer.rb
  app/models/user.rb
  app/policies/appeal_request_issues_policy.rb
  spec/models/user_spec.rb
  spec/policies/appeal_request_issues_policy_spec.rb
Labels: Ready-to-Merge

#11234 Only add the decision task to the task list once, not on every render
  client/app/queue/components/TaskRows.jsx
Labels: Ready-to-Merge

#11232 Allow VLJ support staff to reassign tasks assigned to themselves
  app/models/tasks/colocated_task.rb
Labels: Ready-to-Merge

#11213 Enable org queues to use task pagination API
  app/controllers/organizations/tasks_controller.rb
  app/models/organization.rb
  app/models/organizations/colocated.rb
  app/models/organizations/hearings_management.rb
  app/models/organizations/vso.rb
  app/models/queue_config.rb
  app/models/task_pager.rb
  client/app/components/TablePagination.jsx
  client/app/queue/OrganizationQueue.jsx
  client/app/queue/QueueTable.jsx
  client/app/queue/utils.js
  client/constants/QUEUE_CONFIG.json
  client/test/karma/components/TablePagination-test.js
  spec/models/organization_spec.rb
  spec/models/queue_config_spec.rb
Labels: Ready-to-Merge

#11229 Refactor logic around BGS EP modifier
  app/models/decision_document.rb
  app/models/end_product_establishment.rb
  app/models/ramp_review.rb
  app/workflows/end_product_modifier_finder.rb
  spec/models/end_product_establishment_spec.rb
Labels: Ready-to-Merge

#11237 Sort Records to sync ASC
  app/models/record_synced_by_job.rb
  spec/models/record_synced_by_job_spec.rb
Labels: Ready-to-Merge

#11222 Removing old model
  app/models/tasks/disposition_task.rb
Labels: Ready-to-Merge

#11242 Check feature toggle on per-user basis for use_task_pages_api
  app/models/queue_config.rb
Labels: Ready-to-Merge

#11239 Re-enable table filter names for org queues
  client/app/components/FilterSummary.jsx
  client/app/queue/QueueTable.jsx
  client/app/queue/components/TaskTable.jsx
  client/app/queue/constants.js
Labels: Ready-to-Merge

#11241 Use participant_id to indicate BGS record found
  app/models/veteran.rb
  spec/models/legacy_appeal_spec.rb
Labels: Ready-to-Merge

#10971 download functionality
  lib/tasks/local/build.rake
  local/vacols/build_push.sh
Labels: Ready-to-Merge

#11246 clean up attorney case review records when related task deleted
  app/models/task.rb
  spec/feature/hearings/hearing_admin_action_verify_address_task_spec.rb
Labels: Ready-to-Merge

#11200 Improve Print View of Hearing Worksheet
  app/assets/stylesheets/print/hearings_worksheet.scss
  client/app/hearings/components/hearingWorksheet/HearingWorksheet.jsx
  client/app/hearings/components/hearingWorksheet/HearingWorksheetDocs.jsx
  client/app/hearings/components/hearingWorksheet/HearingWorksheetIssues.jsx
  client/app/hearings/components/hearingWorksheet/HearingWorksheetPreImpressions.jsx
  client/app/hearings/components/hearingWorksheet/HearingWorksheetPrinted.jsx
  client/app/hearings/components/hearingWorksheet/HearingWorksheetStream.jsx
  client/app/hearings/components/hearingWorksheet/WorksheetFooter.jsx
  client/app/hearings/components/hearingWorksheet/WorksheetHeader.jsx
  client/app/hearings/components/hearingWorksheet/WorksheetHeaderVeteranSelection.jsx
  client/app/hearings/containers/HearingWorksheetContainer.jsx
  client/app/hearings/utils.js
  client/app/reader/DecisionReviewer.jsx
  client/app/styles/hearings/_hearings.scss
  client/app/util/FormatUtil.js
  lib/fakes/bgs_service.rb
  spec/feature/hearings/hearing_worksheet_spec.rb
Labels: Ready-to-Merge

#11159 validation, test for unique constraint on HearingTaskAssociation
  app/models/hearing.rb
  app/models/hearing_task_association.rb
  app/models/legacy_hearing.rb
  client/COPY.json
  spec/models/hearing_task_association_spec.rb
  spec/models/tasks/schedule_hearing_task_spec.rb
Labels: Ready-to-Merge

#11216 Lighthouse api docs controller
  app/controllers/api/docs/v3/decision_reviews.yaml
  app/controllers/api/docs/v3/docs_controller.rb
  config/brakeman.ignore
  config/routes.rb
  spec/requests/api/docs/v3/docs_controller_spec.rb
Labels: Ready-to-Merge, lighthouse
