Repository department-of-veterans-affairs/caseflow, pull requests merged in 2019-08, with the labels that each got.

#11563 Custom VACOLS attribute type for ASCII column
  README.md
  app/mappers/queue_mapper.rb
  app/models/vacols/case_hearing.rb
  app/models/vacols/case_issue.rb
  app/models/vacols/decass.rb
  app/models/vacols/record.rb
  app/models/vacols/representative.rb
  config/boot.rb
  config/initializers/activerecord_types.rb
  lib/helpers/ascii_converter.rb
  spec/helpers/ascii_converter_spec.rb
  spec/mappers/queue_mapper_spec.rb
  spec/models/vacols/representative_spec.rb
Labels: Ready-to-Merge

#11619 Allow VSO users to see the Feedback page
  app/controllers/application_controller.rb
  spec/feature/send_feedback_spec.rb
Labels: Ready-to-Merge

#11624 Masquerade as user does not require station id
  app/controllers/test/users_controller.rb
  client/app/test/TestUsers.jsx
  spec/feature/log_in_as_user_spec.rb
Labels: Ready-to-Merge

#11625 Add sorting feature to Days On Hold column in `/organizations/<organization` queue view.
  app/models/task_pager.rb
  client/app/queue/components/TaskTable.jsx
  spec/models/task_pager_spec.rb
Labels: Ready-to-Merge

#11611 Testing for TaskTimerJob success by emitting gauge to DataDog.
  app/jobs/task_timer_job.rb
  spec/jobs/task_timer_job_spec.rb
Labels: Ready-to-Merge

#11620 move feature spec to controller spec
  spec/controllers/application_controller_spec.rb
  spec/feature/send_feedback_spec.rb
Labels: Ready-to-Merge

#11633 When canceling Claim Review establishment, also close request issues
  app/models/claim_review.rb
  spec/models/claim_review_spec.rb
Labels: Ready-to-Merge

#11638 add rake task that activates stalled hearing tasks
  lib/tasks/fixes.rake
  spec/lib/tasks/fixes_spec.rb
Labels: Ready-to-Merge, tango

#11594 Fix Caseflow timeline for canceled withdrawal of appeals tasks
  app/models/task.rb
  app/models/tasks/hearing_task.rb
  spec/factories/task.rb
  spec/feature/queue/case_details_spec.rb
  spec/models/tasks/colocated_task_spec.rb
Labels: Ready-to-Merge

#11651 Allow JudgeAssignTasks to keep changing types for another month
  app/models/tasks/judge_assign_task.rb
  spec/models/tasks/judge_task_spec.rb
Labels: Ready-to-Merge

#11630 Available actions migrated to subclasses
  app/models/tasks/colocated_task.rb
  app/models/tasks/schedule_hearing_colocated_task.rb
  app/models/tasks/translation_colocated_task.rb
  spec/models/tasks/colocated_task_spec.rb
Labels: Ready-to-Merge

#11467 Skip VLJ support for schedule_hearing, missing_hearing_transcripts, translation, and foia colocated tasks
  app/controllers/tasks_controller.rb
  app/models/task.rb
  app/models/tasks/colocated_task.rb
  app/models/tasks/foia_colocated_task.rb
  app/models/tasks/foia_task.rb
  app/models/tasks/generic_task.rb
  app/models/tasks/missing_hearing_transcripts_colocated_task.rb
  app/models/tasks/schedule_hearing_colocated_task.rb
  app/models/tasks/timed_hold_task.rb
  app/models/tasks/track_veteran_task.rb
  app/models/tasks/transcription_task.rb
  app/models/tasks/translation_colocated_task.rb
  client/app/queue/components/CompleteTaskModal.jsx
  client/constants/CO_LOCATED_ADMIN_ACTIONS.json
  client/constants/TASK_ACTIONS.json
  db/seeds.rb
  spec/controllers/tasks_controller_spec.rb
  spec/factories/task.rb
  spec/feature/queue/case_assignment_spec.rb
  spec/feature/queue/case_details_spec.rb
  spec/feature/queue/colocated_task_queue_spec.rb
  spec/feature/queue/privacy_team_spec.rb
  spec/feature/queue/task_queue_spec.rb
  spec/models/legacy_appeal_spec.rb
  spec/models/task_spec.rb
  spec/models/tasks/colocated_task_spec.rb
  spec/models/tasks/foia_task_spec.rb
  spec/models/tasks/judge_task_spec.rb
Labels: Ready-to-Merge

#11569 Throw error if task status is not assigned on create
  app/models/task.rb
Labels: Ready-to-Merge

#11616 Refactor Status API controller
  app/controllers/api/v2/appeals_controller.rb
  app/services/api/v2/appeals.rb
  spec/feature/api/v2/appeals_spec.rb
  spec/services/api/v2/appeals_spec.rb
  spec/support/api_helpers.rb
Labels: Ready-to-Merge

#11629 Refactor Assign Hearings to use QueueTable instead of Table
  client/app/components/FilterSummary.jsx
  client/app/components/TableFilter.jsx
  client/app/hearings/components/AssignHearingsTabs.jsx
  client/app/hearings/components/ListSchedule.jsx
  client/app/queue/QueueTable.jsx
Labels: Ready-to-Merge

#11649 Enable prop-types lint for React
  client/.eslintrc.js
  client/app/components/StyleGuideComponentTitle.jsx
  client/app/containers/EstablishClaimPage/EstablishClaimDecision.jsx
  client/app/queue/components/DispatchSuccessDetail.jsx
  client/app/reader/utils.js
  client/package.json
  client/yarn.lock
Labels: Ready-to-Merge

#11636 Abstract v3 api controller
  app/controllers/api/docs/v3/docs_controller.rb
  app/controllers/api/external_proxy_controller.rb
  app/controllers/api/v3/decision_review/higher_level_reviews_controller.rb
  config/brakeman.ignore
Labels: lighthouse

#11644 Sort tasks by docket number in Organization Queue view.
  app/models/task_pager.rb
  client/app/queue/components/TaskTable.jsx
  spec/factories/cached_appeals.rb
  spec/models/task_pager_spec.rb
Labels: Ready-to-Merge

#11655 Error handling for hearings missing from VACOLS
  app/controllers/hearings/worksheets_controller.rb
  app/controllers/hearings_application_controller.rb
  app/controllers/hearings_controller.rb
  client/app/hearings/actions/hearingWorksheetActions.js
  client/app/hearings/containers/DetailsContainer.jsx
  client/app/hearings/containers/HearingWorksheetContainer.jsx
  client/app/hearings/containers/HearingWorksheetPrintAllContainer.jsx
  config/routes.rb
  spec/controllers/hearings/worksheets_controller_spec.rb
Labels: Ready-to-Merge

#11659 FactoryBot ColocatedTask assignee fix
  app/models/tasks/colocated_task.rb
  db/seeds.rb
  spec/controllers/tasks/change_type_controller_spec.rb
  spec/controllers/tasks_controller_spec.rb
  spec/feature/queue/attorney_queue_spec.rb
  spec/feature/queue/colocated_task_queue_spec.rb
  spec/models/queues/attorney_queue_spec.rb
  spec/models/tasks/colocated_task_spec.rb
Labels: Ready-to-Merge

#11662 Enable passing of ids to fixes:activate_stalled_hearing_tasks rake task
  lib/tasks/fixes.rake
  spec/lib/tasks/fixes_spec.rb
Labels: Ready-to-Merge, tango

#11637 Use constants for AMA docket types in code
  app/models/dockets/direct_review_docket.rb
  app/models/dockets/evidence_submission_docket.rb
  app/models/dockets/hearing_request_docket.rb
  app/models/ramp_refiling.rb
  db/seeds.rb
  spec/feature/hearings/postpone_hearing_spec.rb
  spec/feature/hearings/schedule_veteran_spec.rb
  spec/feature/queue/case_details_spec.rb
  spec/models/appeal_intake_spec.rb
  spec/models/appeal_spec.rb
  spec/models/distribution_spec.rb
  spec/models/docket_coordinator_spec.rb
  spec/models/docket_spec.rb
  spec/models/dockets/direct_review_docket_spec.rb
  spec/models/dockets/hearing_request_docket_spec.rb
  spec/models/ramp_refiling_intake_spec.rb
  spec/workflows/appeal_withdrawal_spec.rb
  spec/workflows/initial_tasks_factory_spec.rb
Labels: Ready-to-Merge

#11646 Run UpdateCachedAppealsAttributesJob during data seeding.
  db/seeds.rb
Labels: Ready-to-Merge

#11418 Simplify and unify error handling
  .reek.yml
  Gemfile
  Gemfile.lock
  app/controllers/api/application_controller.rb
  app/controllers/application_controller.rb
  app/exceptions/bgs_sync_error.rb
  app/exceptions/standard_error.rb
  app/exceptions/vbms_error.rb
  app/jobs/application_job.rb
  app/jobs/decision_issue_sync_job.rb
  app/jobs/decision_review_process_job.rb
  app/jobs/end_product_sync_job.rb
  app/jobs/fetch_hearing_locations_for_veterans_job.rb
  app/jobs/hearing_disposition_change_job.rb
  app/jobs/sync_intake_job.rb
  app/jobs/sync_reviews_job.rb
  app/jobs/task_timer_job.rb
  app/jobs/update_appellant_representation_job.rb
  app/models/end_product_establishment.rb
  app/models/establish_claim.rb
  app/models/legacy_appeal.rb
  app/models/legacy_hearing.rb
  app/models/rating.rb
  app/services/external_api/vbms_documents_for_appeal.rb
  app/services/external_api/vbms_request.rb
  app/services/external_api/vbms_service.rb
  spec/controllers/api/application_controller_spec.rb
  spec/exceptions/vbms_error_spec.rb
  spec/feature/queue/case_details_spec.rb
  spec/jobs/decision_issue_sync_job_spec.rb
  spec/jobs/decision_review_process_job_spec.rb
  spec/models/end_product_establishment_spec.rb
  spec/models/ramp_election_spec.rb
  spec/services/vbms_documents_for_appeal_spec.rb
Labels: Ready-to-Merge

#11667 Sort by regional office
  app/jobs/update_cached_appeals_attributes_job.rb
  app/models/end_product.rb
  app/models/regional_office_email.rb
  app/models/task_pager.rb
  client/COPY.json
  client/app/queue/components/TaskTable.jsx
  client/app/queue/utils.js
  config/brakeman.ignore
  db/migrate/20190806133551_add_closest_regional_office_city_to_cached_appeal_attributes.rb
  db/schema.rb
  spec/models/task_pager_spec.rb
Labels: Ready-to-Merge

#11654 Translation Task blocks appeal distribution
  app/models/appeal.rb
  app/models/tasks/translation_task.rb
  db/seeds.rb
  spec/models/appeal_spec.rb
  spec/models/tasks/translation_task_spec.rb
Labels: Ready-to-Merge

#11648 Allow backend to accept Queue filters
  app/models/queue_filter_parameter.rb
  app/models/queue_where_clause_arguments_factory.rb
  app/models/task_pager.rb
  lib/caseflow/error.rb
  spec/models/queue_filter_parameter_spec.rb
  spec/models/queue_where_clause_arguments_factory_spec.rb
  spec/models/task_pager_spec.rb
Labels: Ready-to-Merge

#11675 Simplify TaskTimerJob specs
  app/jobs/task_timer_job.rb
  spec/jobs/task_timer_job_spec.rb
Labels: Ready-to-Merge

#11465 Add AOD Modal to Daily Docket
  app/controllers/hearings_controller.rb
  app/models/hearing.rb
  app/serializers/hearings/hearing_serializer.rb
  client/app/hearings/components/dailyDocket/DailyDocketModals.jsx
  client/app/hearings/components/dailyDocket/DailyDocketRow.jsx
  client/app/hearings/components/dailyDocket/DailyDocketRowInputs.jsx
  spec/feature/hearings/daily_docket_spec.rb
Labels: Ready-to-Merge

#11679 Use appeal method directly in serializer
  app/models/serializers/work_queue/appeal_serializer.rb
Labels: Ready-to-Merge

#11664 Allow judges to return cases to any attorney
  app/repositories/task_action_repository.rb
  spec/feature/queue/ama_queue_spec.rb
  spec/repositories/task_action_repository_spec.rb
Labels: Ready-to-Merge

#11686 Only sending modified fields to backend from hearing worksheet
  app/controllers/hearings_controller.rb
  client/app/hearings/actions/hearingWorksheetActions.js
  spec/feature/hearings/hearing_worksheet_spec.rb
Labels: Ready-to-Merge

#11665 Add instructions for Hearing Tasks
  app/models/serializers/work_queue/task_serializer.rb
  app/models/task.rb
  app/models/tasks/assign_hearing_disposition_task.rb
  app/models/tasks/change_hearing_disposition_task.rb
  app/models/tasks/hearing_task.rb
  app/models/tasks/schedule_hearing_task.rb
  client/COPY.json
  spec/feature/hearings/change_hearing_disposition_spec.rb
  spec/feature/hearings/hearing_admin_action_foreign_veteran_case_task_spec.rb
  spec/models/tasks/assign_hearing_disposition_task_spec.rb
  spec/models/tasks/hearing_task_spec.rb
Labels: Ready-to-Merge

#11503 If any of the request issues have ratings, do not allow to edit them
  app/models/request_issue.rb
  client/COPY.json
  client/app/intake/actions/addIssues.js
  client/app/intake/components/IssueList.jsx
  client/app/intake/util/issues.js
  spec/feature/intake/higher_level_review/edit_spec.rb
  spec/feature/intake/veteran_name_caching_spec.rb
  spec/models/request_issue_spec.rb
Labels: Ready-to-Merge

#11661 Add user-friendly validation to `outcode` endpoint
  .reek.yml
  app/controllers/idt/api/v1/appeals_controller.rb
  app/validators/decision_document_validator.rb
  app/workflows/ama_appeal_dispatch.rb
  app/workflows/legacy_appeal_dispatch.rb
  spec/controllers/idt/api/appeals_controller_spec.rb
  spec/factories/legacy_appeal.rb
  spec/models/tasks/bva_dispatch_task_spec.rb
  spec/workflows/legacy_appeal_dispatch_spec.rb
Labels: Ready-to-Merge

#11688 Update connect-vbms to allow adding special issues to manually create…
  Gemfile
  Gemfile.lock
Labels: Ready-to-Merge

#11653 Filter out voided decision issues
  app/models/appeal.rb
  app/models/claim_review.rb
  app/models/decision_issue.rb
  app/models/decision_review.rb
  app/models/request_issue.rb
  app/workflows/contestable_issue_generator.rb
  spec/models/decision_issue_spec.rb
  spec/models/decision_review_spec.rb
  spec/models/request_issue_spec.rb
Labels: Ready-to-Merge

#11628 do not slack msg in uat
  app/jobs/caseflow_job.rb
  app/jobs/update_appellant_representation_job.rb
Labels: Ready-to-Merge

#11676 Sort by veteran name
  app/jobs/update_cached_appeals_attributes_job.rb
  app/models/task_pager.rb
  client/app/queue/components/TaskTable.jsx
  config/brakeman.ignore
  db/migrate/20190806180125_add_veteran_name_to_cached_appeal_attributes.rb
  db/schema.rb
  spec/models/task_pager_spec.rb
Labels: Ready-to-Merge

#11694 Use guard clause in controller
  app/controllers/idt/api/v1/appeals_controller.rb
Labels: Ready-to-Merge

#11479 Refactor Error Handling for VaDotGovService
  .reek.yml
  app/jobs/fetch_hearing_locations_for_veterans_job.rb
  app/models/address.rb
  app/models/appeal.rb
  app/models/legacy_appeal.rb
  app/models/regional_office.rb
  app/models/veteran.rb
  app/services/external_api/va_dot_gov_service.rb
  app/services/external_api/va_dot_gov_service/address_validation_response.rb
  app/services/external_api/va_dot_gov_service/facilities_response.rb
  app/services/external_api/va_dot_gov_service/response.rb
  app/services/external_api/va_dot_gov_service/response_message.rb
  app/services/va_dot_gov_address_validator.rb
  app/services/va_dot_gov_address_validator/error_handler.rb
  app/services/va_dot_gov_address_validator/validations.rb
  app/services/va_dot_gov_address_validator_exceptions.rb
  lib/caseflow/error.rb
  spec/factories/appeal.rb
  spec/jobs/fetch_hearing_locations_for_veterans_job_spec.rb
  spec/models/appeal_spec.rb
  spec/services/external_api/va_dot_gov_service_spec.rb
  spec/services/va_dot_gov_address_validator_spec.rb
Labels: Ready-to-Merge

#11702 Sort by issue count
  app/jobs/update_cached_appeals_attributes_job.rb
  app/models/task_pager.rb
  client/app/queue/components/TaskTable.jsx
  config/brakeman.ignore
  db/migrate/20190807192535_add_issue_count_to_cached_appeal_attributes.rb
  db/schema.rb
  spec/models/task_pager_spec.rb
Labels: Ready-to-Merge

#11680 Allow judges to correct issues for hearings they were assigned to
  app/policies/appeal_request_issues_policy.rb
  spec/feature/queue/case_details/edit_issues_spec.rb
  spec/models/task_pager_spec.rb
Labels: Ready-to-Merge

#11703 Stop sending Slack job alerts from UAT
  app/jobs/caseflow_job.rb
  app/jobs/update_appellant_representation_job.rb
  app/services/slack_service.rb
  spec/services/slack_service_spec.rb
Labels: Ready-to-Merge

#11709 Include "Assign team cases" dropdown for all vacols judges
  app/models/user.rb
  app/views/queue/index.html.erb
  spec/models/user_spec.rb
Labels: Ready-to-Merge

#11718 update instructions for installing bundler
  README.md
Labels: Ready-to-Merge

#11706 Get Facility Ids to Geomatch from Outside state
  app/models/regional_office.rb
  app/services/va_dot_gov_address_validator.rb
  app/services/va_dot_gov_address_validator/validations.rb
  client/constants/REGIONAL_OFFICE_INFORMATION.json
  spec/models/regional_office_spec.rb
  spec/models/tasks/hearing_admin_action_verify_address_task_spec.rb
  spec/services/va_dot_gov_address_validator_spec.rb
Labels: Ready-to-Merge

#11729 Add VaDotGovNullAddressError
  app/models/appeal.rb
  app/models/legacy_appeal.rb
  app/services/va_dot_gov_address_validator/error_handler.rb
  app/services/va_dot_gov_address_validator/validations.rb
Labels: Ready-to-Merge

#11704 Add Hearing Day Relationship to Legacy Hearing
  db/migrate/20190807203232_add_hearing_day_id_to_legacy_hearings.rb
  db/schema.rb
Labels: Ready-to-Merge

#11744 Update connect_vbms gem
  Gemfile
  Gemfile.lock
Labels: Ready-to-Merge

#11751 Update Nokogiri to protect against CVE-2019-5477
  Gemfile
  Gemfile.lock
Labels: Ready-to-Merge

#11587 Do not include canceled claims in taken EP modifiers
  app/workflows/end_product_modifier_finder.rb
  spec/models/end_product_establishment_spec.rb
Labels: Ready-to-Merge

#11714 Remove use_bgs feature flag and refactor rep code into its own class
  app/models/legacy_appeal.rb
  app/models/legacy_appeal_representative.rb
  app/models/legacy_hearing.rb
  app/models/power_of_attorney.rb
  spec/controllers/idt/api/appeals_controller_spec.rb
  spec/feature/hearings/daily_docket_spec.rb
  spec/feature/queue/case_details_spec.rb
  spec/models/legacy_appeal_spec.rb
  spec/rails_helper.rb
Labels: Ready-to-Merge

#11728 Hide view docs button in Case Details for RO and call center users
  app/models/user.rb
  app/views/hearings/index.html.erb
  app/views/queue/index.html.erb
  client/app/hearings/HearingsApp.jsx
  client/app/hearings/components/ListSchedule.jsx
  client/app/hearings/components/dailyDocket/DailyDocket.jsx
  client/app/hearings/components/dailyDocket/DailyDocketEditLinks.jsx
  client/app/hearings/components/dailyDocket/DailyDocketPrinted.jsx
  client/app/hearings/components/dailyDocket/DailyDocketRow.jsx
  client/app/hearings/components/dailyDocket/DailyDocketRowDisplayText.jsx
  client/app/hearings/components/dailyDocket/DailyDocketRows.jsx
  client/app/hearings/containers/DetailsContainer.jsx
  client/app/hearings/containers/ListScheduleContainer.jsx
  client/app/queue/CaseDetailsView.jsx
  client/app/queue/CaseTitleDetails.jsx
  client/app/queue/QueueApp.jsx
  spec/feature/queue/ama_queue_spec.rb
  spec/feature/queue/case_details_spec.rb
Labels: Ready-to-Merge

#11748 Remove create_board_grant_effectuations feature toggle
  app/models/decision_document.rb
  spec/models/decision_document_spec.rb
Labels: Ready-to-Merge

#11759 Add DB cleanup to tests that need them
  spec/factories/task.rb
  spec/lib/tasks/fixes_spec.rb
  spec/models/queue_where_clause_arguments_factory_spec.rb
  spec/models/tasks/foia_task_spec.rb
  spec/services/va_dot_gov_address_validator_spec.rb
Labels: Ready-to-Merge

#11746 Remove decision_reviews feature toggle
  spec/controllers/decision_reviews_controller_spec.rb
  spec/feature/intake/higher_level_review/edit_spec.rb
  spec/feature/intake/higher_level_review_spec.rb
  spec/feature/intake/supplemental_claim/edit_spec.rb
  spec/feature/intake/supplemental_claim_spec.rb
  spec/feature/non_comp/board_grants_spec.rb
  spec/feature/non_comp/dispositions_spec.rb
  spec/feature/non_comp/record_requests_spec.rb
  spec/feature/non_comp/reviews_spec.rb
Labels: Ready-to-Merge

#11755 Add webmock gem
  Gemfile
  Gemfile.lock
  app/jobs/dependencies_check_job.rb
  spec/jobs/dependencies_check_job_spec.rb
  spec/support/fake_http_library.rb
  spec/support/fake_response.rb
Labels: Ready-to-Merge

#11762 Add Danger rule to check for specs that need the DB
  Dangerfile
Labels: Ready-to-Merge

#11682 feature toggle around api v3
  app/controllers/api/docs/v3/docs_controller.rb
  app/controllers/api/external_proxy_controller.rb
  app/controllers/api/v3/base_controller.rb
  app/controllers/api/v3/decision_review/higher_level_reviews_controller.rb
  config/brakeman.ignore
  spec/controllers/api/v3/base_controller_spec.rb
  spec/requests/api/v3/higher_level_reviews_controller_spec.rb
Labels: lighthouse

#11768 Rollback & migrate to correct schema.rb
  db/schema.rb
Labels: Ready-to-Merge

#11753 Update connect_vbms gem
  Gemfile
  Gemfile.lock
Labels: Ready-to-Merge

#11553 Case distribution
  app/controllers/distributions_controller.rb
  app/jobs/start_distribution_job.rb
  app/models/distribution.rb
  spec/factories/distribution.rb
  spec/models/distribution_spec.rb
Labels: Ready-to-Merge

#11741 Cache Hearing Day id from VACOLS
  app/models/legacy_hearing.rb
  app/repositories/hearing_repository.rb
  spec/factories/legacy_hearing.rb
  spec/models/legacy_hearing_spec.rb
Labels: Ready-to-Merge

#11773 Fix issue where filter options were shown as blank for Type and Docket
  client/app/components/TableFilter.jsx
Labels: Ready-to-Merge

#11771 Remove case_search_home_page feature toggle
  app/controllers/application_controller.rb
  app/controllers/home_controller.rb
  db/seeds.rb
  spec/controllers/home_controller_spec.rb
  spec/feature/queue/search_spec.rb
Labels: Ready-to-Merge

#11747 Update gems with bummr
  Gemfile.lock
  db/seeds.rb
  lib/helpers/sanitizers.rb
  spec/fake_date_helper.rb
Labels: Ready-to-Merge

#11781 When canceling an AssignHearingDispositionTask, only try to create an EvidenceSubmissionWindowTask if it doesn't already exist
  app/models/tasks/assign_hearing_disposition_task.rb
  spec/factories/task.rb
  spec/feature/queue/bulk_task_assignment_spec.rb
  spec/models/tasks/assign_hearing_disposition_task_spec.rb
Labels: Ready-to-Merge

#11792 Add missing DB cleanup tags
  spec/services/va_dot_gov_address_validator_spec.rb
Labels: Ready-to-Merge

#11766 Add new PostDecisionMotion model and associated DB table
  app/models/post_decision_motion.rb
  db/migrate/20190815125313_create_post_decision_motions.rb
  db/schema.rb
  spec/factories/post_decision_motions.rb
  spec/models/post_decision_motion_spec.rb
Labels: Ready-to-Merge

#11794 Add modal to look up BGS participant ID
  app/controllers/application_controller.rb
  app/controllers/team_management_controller.rb
  app/controllers/users_controller.rb
  client/COPY.json
  client/app/queue/LookupParticipantIdModal.jsx
  client/app/queue/QueueApp.jsx
  client/app/queue/TeamManagement.jsx
  client/app/queue/components/QueueFlowModal.jsx
  client/app/queue/uiReducer/uiActions.js
  config/routes.rb
Labels: Ready-to-Merge

#11788 Ensure case search returns legacy appeals for vso employees
  app/models/veteran.rb
  spec/models/veteran_spec.rb
Labels: Ready-to-Merge

#11786 Fix bug for no upcoming hearing days for RO17 and RO18
  client/app/hearings/components/AssignHearings.jsx
  spec/feature/hearings/schedule_veteran_spec.rb
Labels: Ready-to-Merge

#11795 Refactor AttorneyTask to inherit from GenericTask
  app/models/tasks/attorney_task.rb
  app/models/tasks/generic_task.rb
  spec/controllers/tasks_controller_spec.rb
Labels: Ready-to-Merge

#11745 Bump React
  client/package.json
  client/test/helpers/index.js
  client/test/karma/components/LoadingDataDisplay-test.js
  client/test/karma/components/Modal-test.js
  client/test/karma/hearings/components/ReviewAssignments-test.js
  client/yarn.lock
Labels: Ready-to-Merge

#11690 Enable back-end sorting of tasks by appeal type
  app/jobs/update_cached_appeals_attributes_job.rb
  app/models/task_pager.rb
  app/models/vacols/case.rb
  client/app/queue/components/TaskTable.jsx
  config/brakeman.ignore
  db/migrate/20190807144959_add_column_to_cached_appeal_attributes.rb
  db/schema.rb
  spec/factories/cached_appeals.rb
  spec/jobs/update_cached_appeals_attributes_job_spec.rb
  spec/models/task_pager_spec.rb
Labels: Ready-to-Merge

#11784 Refactoring: Fix prop types, move some messaging to COPY
  client/COPY.json
  client/app/hearings/components/ListSchedule.jsx
  client/app/hearings/components/dailyDocket/DailyDocket.jsx
  client/app/hearings/components/dailyDocket/DailyDocketEditLinks.jsx
  client/app/hearings/components/dailyDocket/DailyDocketModals.jsx
  client/app/hearings/components/dailyDocket/DailyDocketRow.jsx
  client/app/hearings/components/dailyDocket/DailyDocketRowDisplayText.jsx
  client/app/hearings/components/dailyDocket/DailyDocketRows.jsx
  client/app/hearings/containers/DailyDocketContainer.jsx
Labels: Ready-to-Merge

#11806 Add started_at and errored_at columns to Distribution
  app/controllers/distributions_controller.rb
  app/jobs/start_distribution_job.rb
  app/models/distributed_case.rb
  app/models/distribution.rb
  app/models/dockets/legacy_docket.rb
  app/models/vacols/case.rb
  app/queries/vacols_location_batch_updater.rb
  app/repositories/appeal_repository.rb
  app/repositories/power_of_attorney_repository.rb
  client/app/components/Pagination.jsx
  db/migrate/20190816145951_add_started_at_distribution.rb
  db/schema.rb
  spec/models/distribution_spec.rb
  spec/repositories/appeal_repository_spec.rb
  spec/repositories/power_of_attorney_repository_spec.rb
Labels: Ready-to-Merge

#11808 Show Paper Case Notification
  app/models/legacy_appeal.rb
  app/models/serializers/work_queue/legacy_appeal_serializer.rb
  app/serializers/hearings/hearing_serializer.rb
  app/serializers/hearings/legacy_hearing_serializer.rb
  client/app/hearings/components/dailyDocket/DailyDocketRowDisplayText.jsx
  spec/feature/hearings/daily_docket_spec.rb
Labels: Ready-to-Merge

#11819 Stop creating JudgeTasks with action argument
  app/models/docket.rb
  app/workflows/judge_assign_task_creator.rb
Labels: Ready-to-Merge

#11783 Removed intake-reserved-file-number-flag
  app/models/validators/intake_start_validator.rb
  spec/controllers/intakes_controller_spec.rb
  spec/feature/intake/intake_spec.rb
Labels: Ready-to-Merge

#11825 Change copy on link from Reader back to queue
  client/app/reader/BackToQueueLink.jsx
  spec/feature/queue/case_details_spec.rb
Labels: Ready-to-Merge

#11823 Update label for ColocatedTasks created by judges
  app/models/tasks/colocated_task.rb
  client/constants/TASK_ACTIONS.json
  spec/feature/queue/task_queue_spec.rb
Labels: Ready-to-Merge

#11824 change "started" status outside of transaction
  app/models/distribution.rb
Labels: Ready-to-Merge

#11827 Update RequestIssue attributes in Decision Review openapi spec
  app/controllers/api/docs/v3/decision_reviews.yaml
Labels: Ready-to-Merge

#11828 Avoid redirect woes
  client/app/queue/LookupParticipantIdModal.jsx
Labels: Ready-to-Merge

#11750 Move logic for sorting tasks out of TaskPager
  app/models/cached_appeal.rb
  app/models/queue_column.rb
  app/models/queue_config.rb
  app/models/task_pager.rb
  app/models/task_sorter.rb
  client/COPY.json
  client/constants/QUEUE_CONFIG.json
  spec/models/queue_column_spec.rb
  spec/models/task_pager_spec.rb
  spec/models/task_sorter_spec.rb
Labels: Ready-to-Merge

#11818 Don't check action field when checking for task similarity
  app/models/task.rb
Labels: Ready-to-Merge

#11821 Update copy on team management page
  client/COPY.json
  client/app/queue/OrganizationUsers.jsx
  spec/feature/queue/user_organization_spec.rb
Labels: Ready-to-Merge

#11816 Rename QueueWhereClauseArgumentsFactory -> TaskFilter
  app/models/task_filter.rb
  app/models/task_pager.rb
  spec/models/queue_where_clause_arguments_factory_spec.rb
  spec/models/task_filter_spec.rb
Labels: Ready-to-Merge

#11810 Add active status for users
  app/models/user.rb
  client/constants/USER_STATUSES.json
  db/migrate/20190816194620_add_status_to_users.rb
  db/migrate/20190816210203_add_default_value_to_status.rb
  db/schema.rb
  spec/models/user_spec.rb
Labels: Ready-to-Merge

#11817 Remove JudgeLegacyTask reliance on action field
  app/controllers/idt/api/v1/appeals_controller.rb
  app/models/legacy_tasks/judge_legacy_assign_task.rb
  app/models/legacy_tasks/judge_legacy_decision_review_task.rb
  app/models/legacy_tasks/judge_legacy_task.rb
  spec/controllers/tasks_controller_spec.rb
  spec/models/legacy_tasks/judge_legacy_task_spec.rb
  spec/models/queues/legacy_work_queue_spec.rb
Labels: Ready-to-Merge

#11732 Rename advanced_on_docket to advanced_on_docket?
  app/models/advance_on_docket_motion.rb
  app/models/appeal.rb
  app/models/claimant.rb
  app/models/hearing.rb
  app/models/legacy_appeal.rb
  app/models/person.rb
  app/models/serializers/idt/v1/appeal_details_serializer.rb
  app/models/serializers/v2/appeal_status_serializer.rb
  app/models/serializers/work_queue/appeal_serializer.rb
  app/models/serializers/work_queue/decision_review_serializer.rb
  app/models/serializers/work_queue/task_column_serializer.rb
  app/models/serializers/work_queue/task_serializer.rb
  spec/controllers/idt/api/appeals_controller_spec.rb
  spec/models/appeal_spec.rb
  spec/models/claimant_spec.rb
Labels: Ready-to-Merge

#11785 Handle Alternate Location Request Failures Gracefully
  app/controllers/hearings_controller.rb
  app/services/external_api/va_dot_gov_service/response.rb
  app/services/va_dot_gov_address_validator.rb
  app/services/va_dot_gov_address_validator/error_handler.rb
  app/services/va_dot_gov_address_validator/validations.rb
  client/app/components/DataDropdowns/AppealHearingLocations.jsx
  spec/controllers/hearings_controller_spec.rb
  spec/feature/hearings/schedule_veteran_spec.rb
  spec/services/va_dot_gov_address_validator_spec.rb
Labels: Ready-to-Merge

#11841 Use hearing_location.name for regional_office in hearings API
  app/serializers/api/v2/hearing_serializer.rb
  docs/caseflow-apis.md
Labels: Ready-to-Merge

#11790 Add Headway Release History Link
  app/controllers/application_controller.rb
Labels: Ready-to-Merge

#11813 Add RatingDecision for not-service-connected decisions
  app/models/rating.rb
  app/models/rating_decision.rb
  lib/generators/rating.rb
  spec/models/rating_decision_spec.rb
  spec/models/rating_issue_spec.rb
  spec/models/rating_spec.rb
Labels: Ready-to-Merge

#11822 Datadog Service through Caseflow Job
  app/jobs/caseflow_job.rb
  app/jobs/data_integrity_checks_job.rb
  app/jobs/sync_intake_job.rb
  app/jobs/task_timer_job.rb
  app/jobs/update_appellant_representation_job.rb
  app/jobs/update_cached_appeals_attributes_job.rb
  app/jobs/warm_bgs_caches_job.rb
  app/services/data_dog_service.rb
  spec/jobs/update_appellant_representation_job_spec.rb
Labels: Ready-to-Merge

#11854 disability_evaluations may be plural array
  app/models/rating_decision.rb
Labels: Ready-to-Merge

#11843 Fix front end case type sort order
  client/app/queue/components/TaskTable.jsx
Labels: Ready-to-Merge

#11845 Create blocking MailTasks as children of DistributionTasks.
  app/models/tasks/mail_task.rb
  spec/feature/queue/task_queue_spec.rb
  spec/models/tasks/mail_task_spec.rb
Labels: Ready-to-Merge

#11820 Ignore action column of tasks table
  app/models/task.rb
  spec/factories/task.rb
  spec/feature/queue/case_details_spec.rb
  spec/models/task_pager_spec.rb
Labels: Ready-to-Merge

#11853 Simplify Hearing Location Job Query
  app/jobs/fetch_hearing_locations_for_veterans_job.rb
  spec/factories/legacy_appeal.rb
  spec/jobs/fetch_hearing_locations_for_veterans_job_spec.rb
Labels: Ready-to-Merge

#11855 Create pre routed subclass for old style colocated tasks in production
  app/models/tasks/colocated_task.rb
  app/models/tasks/foia_colocated_task.rb
  app/models/tasks/missing_hearing_transcripts_colocated_task.rb
  app/models/tasks/pre_routing_colocated_task.rb
  app/models/tasks/pre_routing_foia_colocated_task.rb
  app/models/tasks/pre_routing_missing_hearing_transcripts_colocated_task.rb
  app/models/tasks/pre_routing_translation_colocated_task.rb
  app/models/tasks/translation_colocated_task.rb
Labels: Ready-to-Merge

#11832 Refactor ColocatedTask to inherit from GenericTask instead of Task.
  app/models/tasks/colocated_task.rb
Labels: Ready-to-Merge

#11800 Allow adding dispositions to post-decision motions
  app/controllers/post_decision_motions_controller.rb
  app/models/post_decision_motion.rb
  app/models/tasks/judge_address_motion_to_vacate_task.rb
  client/COPY.json
  config/routes.rb
  db/migrate/20190821162943_add_vacate_type_to_post_decision_motion.rb
  db/schema.rb
  spec/controllers/post_decision_motions_controller_spec.rb
  spec/factories/task.rb
  spec/models/tasks/judge_address_motion_to_vacate_task_spec.rb
Labels: Ready-to-Merge

#11749 BGSService.may_modify depends on conflict checker
  app/models/validators/intake_start_validator.rb
  app/services/external_api/bgs_service.rb
  app/services/external_api/bgs_veteran_station_user_conflict.rb
  lib/fakes/bgs_service.rb
  spec/services/external_api/bgs_service_spec.rb
Labels: Ready-to-Merge

#11863 Backfill people names
  app/jobs/warm_bgs_caches_job.rb
  app/models/intake.rb
Labels: Ready-to-Merge

#11846 Contestable rating decisions
  .reek.yml
  app/models/concerns/latest_rating_disability_evaluation.rb
  app/models/contestable_issue.rb
  app/models/rating.rb
  app/models/rating_decision.rb
  app/models/request_issue.rb
  db/migrate/20190820083623_add_request_issue_rating_sequence_number.rb
  db/schema.rb
  spec/models/contestable_issue_spec.rb
  spec/models/decision_review_spec.rb
  spec/models/rating_decision_spec.rb
  spec/models/rating_spec.rb
Labels: Ready-to-Merge

#11862 Run missed distribution jobs
  app/jobs/missed_job_sweeper_job.rb
  spec/jobs/missed_job_sweeper_job_spec.rb
Labels: Ready-to-Merge

#11869 Move docket name filters to constants file
  client/app/queue/components/TaskTable.jsx
  client/app/queue/constants.js
  client/constants/DOCKET_NAME_FILTERS.json
Labels: Ready-to-Merge

#11873 Add rating decision original_denial_date
  app/models/rating_decision.rb
Labels: Ready-to-Merge

#11874 Raise error with invalid job priority
  app/jobs/application_job.rb
  app/jobs/calculate_dispatch_stats_job.rb
  app/jobs/calculate_intake_stats_job.rb
  app/jobs/create_establish_claim_tasks_job.rb
  app/jobs/data_integrity_checks_job.rb
  app/jobs/decision_issue_sync_job.rb
  app/jobs/decision_review_process_job.rb
  app/jobs/dependencies_check_job.rb
  app/jobs/dependencies_report_service_log_job.rb
  app/jobs/docket_range_job.rb
  app/jobs/end_product_sync_job.rb
  app/jobs/fetch_documents_for_reader_user_job.rb
  app/jobs/fetch_hearing_locations_for_veterans_job.rb
  app/jobs/hearing_disposition_change_job.rb
  app/jobs/heartbeat_tasks_job.rb
  app/jobs/missed_job_sweeper_job.rb
  app/jobs/monitor_business_critical_jobs_job.rb
  app/jobs/out_of_service_reminder_job.rb
  app/jobs/prepare_establish_claim_tasks_job.rb
  app/jobs/process_decision_document_job.rb
  app/jobs/reassign_old_tasks_job.rb
  app/jobs/retrieve_documents_for_reader_job.rb
  app/jobs/start_certification_job.rb
  app/jobs/start_distribution_job.rb
  app/jobs/sync_intake_job.rb
  app/jobs/sync_reviews_job.rb
  app/jobs/take_docket_snapshot_job.rb
  app/jobs/task_timer_job.rb
  app/jobs/update_appellant_representation_job.rb
  app/jobs/update_cached_appeals_attributes_job.rb
  app/jobs/upload_document_to_vbms_job.rb
  app/jobs/warm_bgs_caches_job.rb
  spec/jobs/application_job_spec.rb
Labels: Ready-to-Merge, bat-team

#11870 Fix BGS participant ID lookup
  app/controllers/users_controller.rb
Labels: Ready-to-Merge

#11872 Cache friendly labels for appeal case type
  app/jobs/update_cached_appeals_attributes_job.rb
  app/models/vacols/case.rb
  spec/factories/cached_appeals.rb
  spec/models/task_pager_spec.rb
  spec/models/task_sorter_spec.rb
Labels: Ready-to-Merge

#11857 Add Assignee Label to CachedAppealAttributes for AMA Appeals
  app/jobs/update_cached_appeals_attributes_job.rb
  db/migrate/20190821180128_add_assignee_label_to_cached_appeals_attribute_table.rb
  db/schema.rb
Labels: Ready-to-Merge

#11877 Remove reference to task action field in factory
  spec/factories/appeal.rb
Labels: Ready-to-Merge

#11875 Contestable rating decisions
  app/models/contestable_issue.rb
  app/models/rating.rb
  app/models/rating_decision.rb
  spec/models/contestable_issue_spec.rb
  spec/models/rating_decision_spec.rb
Labels: Ready-to-Merge

#11876 rspec: use explicit xhr wait time for alert to appear
  spec/feature/hearings/daily_docket_spec.rb
Labels: Ready-to-Merge

#11884 Fix pager sort to ignore case and consistent ruby-vs-sql
  .reek.yml
  app/models/task_sorter.rb
  spec/models/task_pager_spec.rb
Labels: Ready-to-Merge

#11885 Update the PR template with Documentation & File Top-Line Comments
  PULL_REQUEST_TEMPLATE.md
Labels: Ready-to-Merge

#11939 Handle null error body in AppealHearingLocations dropdown
  client/app/components/DataDropdowns/AppealHearingLocations.jsx
Labels: Ready-to-Merge

#11936 Claim review async stats
  .reek.yml
  app/models/concerns/asyncable.rb
  app/services/claim_review_async_stats_reporter.rb
  spec/services/claim_review_async_stats_reporter_spec.rb
Labels: Ready-to-Merge

#11844 move issues_hash and status_hash into serializers
  app/models/appeal.rb
  app/models/appeal_series.rb
  app/models/claim_review.rb
  app/models/decision_review.rb
  app/models/higher_level_review.rb
  app/models/serializers/v2/appeal_status_serializer.rb
  app/models/serializers/v2/hlr_status_serializer.rb
  app/models/serializers/v2/legacy_appeal_status_serializer.rb
  app/models/serializers/v2/sc_status_serializer.rb
  app/models/supplemental_claim.rb
  app/serializers/issue_serializer.rb
  app/serializers/issues_field_serializer.rb
  app/serializers/status_field_serializer.rb
  app/serializers/status_serializer.rb
  spec/models/appeal_series_spec.rb
  spec/models/appeal_spec.rb
  spec/models/higher_level_review_spec.rb
  spec/models/supplemental_claim_spec.rb
  spec/serializers/issue_serializer_spec.rb
  spec/serializers/status_serializer_spec.rb
Labels: Ready-to-Merge

#11913 Inbox and intake messages
  app/controllers/asyncable_jobs_controller.rb
  app/controllers/concerns/pagination_concern.rb
  app/controllers/inbox_controller.rb
  app/models/message.rb
  app/models/user.rb
  app/services/inbox_messages.rb
  app/views/inbox/index.html.erb
  client/app/asyncableJobs/pages/JobsPage.jsx
  client/app/components/EasyPagination.jsx
  client/app/inbox/index.jsx
  client/app/inbox/pages/InboxPage.jsx
  client/app/inbox/reducers/index.js
  client/app/index.js
  client/app/intake/pages/selectForm.jsx
  client/app/styles/_inbox.scss
  client/app/styles/app.scss
  config/routes.rb
  db/migrate/20190827142452_create_messages.rb
  db/schema.rb
  spec/controllers/asyncable_jobs_controller_spec.rb
  spec/factories/messages.rb
  spec/feature/asyncable_jobs/asyncable_jobs_index_spec.rb
  spec/feature/inbox/inbox_spec.rb
  spec/models/message_spec.rb
  spec/services/inbox_messages_spec.rb
  spec/support/date_time_helper.rb
Labels: Ready-to-Merge

#11865 Geomatch All Facilities
  app/models/regional_office.rb
  app/services/external_api/va_dot_gov_service.rb
  app/services/va_dot_gov_address_validator.rb
  app/services/va_dot_gov_address_validator/closest_regional_office_finder.rb
  app/services/va_dot_gov_address_validator/validations.rb
  client/constants/REGIONAL_OFFICE_INFORMATION.json
  spec/models/regional_office_spec.rb
  spec/services/va_dot_gov_address_validator/closest_regional_office_finder_spec.rb
  spec/services/va_dot_gov_address_validator_spec.rb
  spec/support/hearing_helpers.rb
Labels: Ready-to-Merge

#11798 Caselist Response Body Fix
  client/app/queue/CaseList/CaseListActions.js
Labels: Ready-to-Merge

#11934 Deprecate intake stats manager
  app/controllers/intake_stats_controller.rb
  app/views/intake_manager/index.html.erb
  client/app/intakeManager/FlaggedForReview.jsx
  client/app/intakeManager/FlaggedForReviewContainer.jsx
  client/app/intakeManager/UserStats.jsx
  spec/feature/intake/intake_manager_spec.rb
  spec/feature/intake/intake_stats_spec.rb
Labels: Ready-to-Merge

#11945 Find active child TimedHoldTask without New Query
  app/models/task.rb
  spec/feature/queue/case_details_spec.rb
  spec/models/task_spec.rb
  spec/models/tasks/assign_hearing_disposition_task_spec.rb
  spec/models/tasks/timed_hold_task_spec.rb
  spec/models/tasks/transcription_task_spec.rb
Labels: Ready-to-Merge

#11944 Async jobs page style
  client/app/asyncableJobs/components/AsyncModelNav.jsx
  client/app/asyncableJobs/components/JobRestartButton.jsx
  client/app/asyncableJobs/pages/JobPage.jsx
  client/app/asyncableJobs/pages/JobsPage.jsx
  client/app/asyncableJobs/reducers/index.js
  client/app/styles/_jobs.scss
  spec/feature/asyncable_jobs/asyncable_jobs_index_spec.rb
Labels: Ready-to-Merge

#11829 Removed ama_decision_issues feature toggle
  spec/controllers/case_reviews_controller_spec.rb
  spec/feature/queue/case_details_spec.rb
  spec/feature/queue/delete_request_issues_spec.rb
  spec/feature/withdrawn_request_issues_spec.rb
Labels: Ready-to-Merge

#11935 Disable GA if we are in development env
  app/views/layouts/application.html.erb
Labels: Ready-to-Merge

#11954 flakey spec for sorting
  spec/models/task_sorter_spec.rb
Labels: Ready-to-Merge
