Repository department-of-veterans-affairs/caseflow, pull requests merged in 2020-09, with the labels that each got.

#15033 [PART 1] Prep work for blocked scm front end
  app/controllers/tasks_controller.rb
  app/models/task.rb
  app/models/tasks/distribution_task.rb
  app/models/tasks/mail_task.rb
  app/models/tasks/special_case_movement/blocked_special_case_movement_task.rb
  app/repositories/task_action_repository.rb
  client/COPY.json
  client/app/queue/BlockedAdvanceToJudgeView.jsx
  client/app/queue/QueueApp.jsx
  client/constants/TASK_ACTIONS.json
  spec/controllers/tasks_controller_spec.rb
  spec/feature/queue/special_case_movement_task_spec.rb
  spec/models/task_spec.rb
  spec/models/tasks/distribution_task_spec.rb
  spec/models/tasks/special_case_movement/blocked_special_case_movement_task_spec.rb
Labels: Ready-to-Merge

#15118 Separated out logic for scheduling veteran hearings
  client/app/hearings/components/ScheduleVeteran.jsx
  client/app/hearings/components/ScheduleVeteran.stories.js
  client/app/hearings/components/ScheduleVeteranForm.jsx
  client/app/hearings/components/ScheduleVeteranForm.stories.js
  client/app/hearings/components/VirtualHearings/AppellantSection.jsx
  client/app/hearings/constants.js
  client/test/app/hearings/components/ScheduleVeteran.test.js
  client/test/app/hearings/components/ScheduleVeteranForm.test.js
  client/test/app/hearings/components/__snapshots__/ScheduleVeteran.test.js.snap
  client/test/app/hearings/components/__snapshots__/ScheduleVeteranForm.test.js.snap
  client/test/data/appeals.js
  client/test/data/hearings.js
  client/test/data/stores/queueStore.js
Labels: Ready-to-Merge

#15081 Reverts Caseflow Dispatch Validating
  app/models/legacy_appeal.rb
  app/views/dispatch/establish_claims/show.html.erb
  client/app/constants/SpecialIssueEnabler.js
  client/app/constants/SpecialIssues.js
  client/app/containers/EstablishClaimPage/EstablishClaim.jsx
  client/app/containers/EstablishClaimPage/EstablishClaimDecision.jsx
  client/app/containers/EstablishClaimPage/EstablishClaimEmail.jsx
  client/app/containers/EstablishClaimPage/EstablishClaimForm.jsx
  client/app/containers/EstablishClaimPage/EstablishClaimNote.jsx
  client/app/establishClaim/constants/index.js
  client/app/establishClaim/reducers/index.js
  client/app/establishClaim/reducers/specialIssues.js
  client/app/establishClaim/selectors/index.js
  client/app/establishClaim/util/index.js
  spec/feature/dispatch/establish_claim_spec.rb
Labels: Ready-to-Merge

#15144 add diagnostic code for 7632
  client/constants/DIAGNOSTIC_CODE_DESCRIPTIONS.json
Labels: Ready-to-Merge, Source: Bat Team

#15133 PRs alert when we touch a Service integration
  Dangerfile
Labels: Ready-to-Merge

#15146 Drops the unused contentions from the Legacy Appeal
  db/migrate/20200902141700_revert_add_new_contensions_to_legacy_appeal.rb
  db/schema.rb
  docs/schema/caseflow.csv
Labels: Ready-to-Merge

#15125 Prioritize AOD and CAVC cases during Bulk Assignment
  app/models/appeal.rb
  app/models/legacy_appeal.rb
  app/models/task.rb
  app/workflows/bulk_task_assignment.rb
  spec/workflows/bulk_task_assignment_spec.rb
Labels: Priority: Medium, Product: caseflow-queue, Ready-to-Merge, Stakeholder: BVA, Team: Echo 🐬, Type: Bug

#15151 Properly check feature toggle for backlog bust
  app/models/concerns/ama_case_distribution.rb
  spec/models/distribution_spec.rb
Labels: Ready-to-Merge

#15147 Removes ignore columns from LegacyAppeal Model
  app/models/legacy_appeal.rb
Labels: Ready-to-Merge

#14932 Allow DVCs to toggle accepts_priority_pushed_cases from the front end
  app/controllers/team_management_controller.rb
  app/models/organization.rb
  client/COPY.json
  client/app/queue/TeamManagement.jsx
  spec/controllers/team_management_controller_spec.rb
  spec/feature/queue/team_management_spec.rb
Labels: blocked

#14928 Allow DVCs to view the team management page
  app/controllers/application_controller.rb
  app/controllers/team_management_controller.rb
  app/models/organization.rb
  app/models/user.rb
  client/COPY.json
  client/app/queue/TeamManagement.jsx
  db/seeds/users.rb
  spec/controllers/team_management_controller_spec.rb
  spec/feature/queue/team_management_spec.rb
  spec/seeds/users_spec.rb
Labels: blocked

#14926 Team management page updates
  app/controllers/application_controller.rb
  app/controllers/team_management_controller.rb
  app/models/organization.rb
  app/models/organizations/dvc_team.rb
  app/models/organizations/judge_team.rb
  app/models/user.rb
  client/COPY.json
  client/app/queue/TeamManagement.jsx
  db/seeds/users.rb
  spec/controllers/team_management_controller_spec.rb
  spec/feature/queue/team_management_spec.rb
  spec/seeds/users_spec.rb
Labels: blocked

#15174 Fix missing method error for capture_exception
  app/models/legacy_hearing.rb
Labels: Ready-to-Merge

#15152 Updates to EditContentionTitle
  client/app/intake/components/EditContentionTitle.jsx
  client/app/intake/components/EditContentionTitle.stories.js
  client/test/app/intake/components/EditContentionTitle.test.js
  client/test/app/intake/components/__snapshots__/EditContentionTitle.test.js.snap
Labels: Ready-to-Merge, Team: Foxtrot 🦊

#15093 Bug | Fix code for cancelling an EP in BGS
  app/models/end_product_establishment.rb
  app/services/external_api/bgs_service.rb
  lib/fakes/bgs_service.rb
  spec/factories/end_product_establishment.rb
  spec/models/end_product_establishment_spec.rb
  spec/models/request_issues_update_spec.rb
Labels: Ready-to-Merge

#15178 Add comment to special_issue_lists table
  db/migrate/20200904140217_change_special_issue_lists_comment.rb
  db/schema.rb
  docs/schema/caseflow.csv
Labels: Ready-to-Merge, Team: Echo 🐬, Type: Documentation

#15153 Update Appeal type label on claim details page
  client/COPY.json
Labels: Product: caseflow-hearings, Ready-to-Merge, Stakeholder: BVA, Team: Tango 💃

#15172 Missing Ratings | Add current rating profile endpoint to Caseflow
  app/models/current_rating.rb
  app/models/rating.rb
  app/services/external_api/bgs_service.rb
  lib/fakes/bgs_service.rb
  spec/models/current_rating_spec.rb
Labels: Ready-to-Merge

#15015 add migration inheritance requirement
  PULL_REQUEST_TEMPLATE.md
Labels: Ready-to-Merge

#15045 Tech spec for recording hearing request type
  docs/tech-specs/2020-08-19-convert-travel-board-hearing-to-video-or-virtual-hearing-request.md
Labels: Ready-to-Merge, Team: Tango 💃

#15145 Display hearing type on case details
  app/models/appeal.rb
  app/models/legacy_appeal.rb
  app/models/serializers/work_queue/appeal_serializer.rb
  app/models/serializers/work_queue/legacy_appeal_serializer.rb
  client/COPY.json
  client/app/queue/CaseTitleDetails.jsx
  client/app/queue/CaseTitleDetails.stories.js
  client/app/queue/utils.js
  spec/feature/queue/case_details_spec.rb
  spec/models/appeal_spec.rb
Labels: Ready-to-Merge, Team: Tango 💃

#15184 Write hearing type to VACOLS when converting legacy hearings
  app/mappers/hearing_mapper.rb
  app/models/hearing.rb
  app/models/hearings/forms/base_hearing_update_form.rb
  app/models/hearings/forms/legacy_hearing_update_form.rb
  app/models/hearings/virtual_hearing.rb
  app/models/legacy_hearing.rb
  db/migrate/20200908050443_add_original_vacols_request_type_to_legacy_hearing.rb
  db/schema.rb
  docs/schema/caseflow.csv
  spec/mappers/hearing_mapper_spec.rb
  spec/models/legacy_hearing_spec.rb
Labels: Ready-to-Merge, Team: Tango 💃

#15182 Fix contested typo in Issue Category Dropdown
  app/controllers/api/docs/v3/decision_reviews.yaml
  client/constants/ISSUE_CATEGORIES.json
  spec/feature/intake/add_issues_spec.rb
Labels: Priority: High, Product: caseflow-intake, Stakeholder: BVA, Team: Foxtrot 🦊

#15082 Ensure vacols location isn't set incorrectly when user requests disposition change
  app/models/tasks/hearing_task.rb
  app/models/tasks/schedule_hearing_task.rb
  spec/models/tasks/schedule_hearing_task_spec.rb
Labels: Ready-to-Merge, Team: Tango 💃

#15192 Add Sentry ID from Raven to data integrity job Slack message
  app/jobs/data_integrity_checks_job.rb
  spec/jobs/data_integrity_checks_job_spec.rb
Labels: Ready-to-Merge, Source: Sentry Alert, Type: Tech-Improvement

#15199 Upgrade Rails to 5.2.4.4 to address CVE-2020-15169
  Gemfile
  Gemfile.lock
Labels: Eng: Dependencies, Ready-to-Merge

#15191 Create "Clerk of the Board" Org
  app/models/organizations/clerk_of_the_board.rb
Labels: Ready-to-Merge, Team: Foxtrot 🦊

#15188 Ensure props change when navigating to a new page from the nav bar
  client/app/components/NavigationBar.jsx
Labels: Ready-to-Merge

#15168 Add integrations UAT testing to PR template
  PULL_REQUEST_TEMPLATE.md
Labels: Ready-to-Merge

#15189 Add changed hearing request type column to legacy hearings
  app/jobs/start_certification_job.rb
  app/models/hearing_day.rb
  app/models/legacy_appeal.rb
  app/services/va_dot_gov_address_validator/validations.rb
  db/migrate/20200908191436_add_changed_hearing_request_type_to_legacy_appeal.rb
  db/schema.rb
  docs/schema/caseflow.csv
  spec/models/legacy_appeal_spec.rb
Labels: Ready-to-Merge, Team: Tango 💃

#15204 remove unused associated_hearing_is_video method
  app/models/hearings/virtual_hearing.rb
Labels: Ready-to-Merge, Team: Tango 💃

#15198 Fix issue where POA is fetched multiple times on Case Details
  client/app/queue/reducers.js
Labels: Ready-to-Merge, Team: Tango 💃

#15083 Use BGS representative in all Hearings Jobs
  app/models/legacy_appeal_representative.rb
  spec/jobs/virtual_hearings/create_conference_job_spec.rb
Labels: Ready-to-Merge, Team: Tango 💃

#15235 Fix display of non-vet claimants on non-comp DR tasks
  app/models/serializers/work_queue/decision_review_task_serializer.rb
  spec/models/serializers/work_queue/decision_review_task_serializer_spec.rb
Labels: Ready-to-Merge

#15170 Add associations to end product establishment for effectuations
  app/models/end_product_establishment.rb
Labels: Ready-to-Merge, Team: Foxtrot 🦊

#15237 Remove eligible_due_to_date for aod motions
  app/models/advance_on_docket_motion.rb
  spec/models/advance_on_docket_motion_spec.rb
Labels: Ready-to-Merge

#15241 Clarify task_timer table comments
  app/models/concerns/timeable_task.rb
  app/models/task_timer.rb
  app/models/tasks/timed_hold_task.rb
  db/migrate/20200915143743_edit_task_timers_comments.rb
  db/schema.rb
  docs/schema/caseflow.csv
Labels: Priority: Low, Product: caseflow-queue, Ready-to-Merge, Team: Echo 🐬, Type: Documentation

#15228 Edit EP Claim Labels | Add map of end product code characteristics
  client/constants/EP_CLAIM_TYPES.json
Labels: Ready-to-Merge, Team: Foxtrot 🦊

#15244 Use request_type instead of readabale_request_type to determine RO
  client/app/hearings/components/dailyDocket/DailyDocket.jsx
Labels: Product: caseflow-hearings, Ready-to-Merge, Stakeholder: BVA, Team: Tango 💃, Type: Bug

#15213 Create ChangeHearingRequestTypeTask
  .rubocop.yml
  app/controllers/appeals_controller.rb
  app/jobs/fetch_hearing_locations_for_veterans_job.rb
  app/models/tasks/change_hearing_request_type_task.rb
  app/models/user.rb
  app/repositories/appeal_repository.rb
  app/repositories/task_action_repository.rb
  app/services/hearing_task_tree_initializer.rb
  app/workflows/tasks_for_appeal.rb
  client/COPY.json
  client/constants/TASK_ACTIONS.json
  spec/controllers/hearings/schedule_hearing_tasks_controller_spec.rb
  spec/feature/hearings/convert_travel_board_hearing/edit_hearsched_spec.rb
  spec/models/queue_tabs/assign_hearing_tab_spec.rb
  spec/repositories/appeal_repository_spec.rb
  spec/services/hearing_task_tree_initializer_spec.rb
Labels: Ready-to-Merge, Team: Tango 💃

#15240 Select room based on all existing hearing days instead of limiting by request type
  app/services/hearing_day_room_assignment.rb
  spec/services/hearing_day_room_assignment_spec.rb
Labels: Ready-to-Merge, Team: Tango 💃

#15209 Give hearing team admins the ability to reassign tasks assigned to their team members
  app/models/concerns/task_extension_for_hearings.rb
  app/models/tasks/change_hearing_disposition_task.rb
  app/models/tasks/hearing_related_mail_task.rb
  app/models/tasks/schedule_hearing_colocated_task.rb
  app/repositories/task_action_repository.rb
  client/constants/TASK_ACTIONS.json
  spec/models/task_spec.rb
Labels: Ready-to-Merge

#15243 Fix BGEs' failure to sync for non-rating decisions
  app/models/board_grant_effectuation.rb
  spec/models/board_grant_effectuation_spec.rb
Labels: Ready-to-Merge

#15252 Store cancelled by id on tasks
  app/models/task.rb
  app/models/tasks/assign_hearing_disposition_task.rb
  app/workflows/tasks_for_appeal.rb
  db/migrate/20200916150837_add_cancelled_by_id_to_tasks.rb
  db/schema.rb
  docs/schema/caseflow.csv
  spec/models/task_spec.rb
  spec/models/tasks/assign_hearing_disposition_task_spec.rb
  spec/models/tasks/schedule_hearing_task_spec.rb
Labels: Ready-to-Merge

#15262 Updates ruby gem to include Edit EP Claim Labels
  Gemfile
  Gemfile.lock
Labels: Ready-to-Merge

#15231 Added paper trail versioning when changed_request_type updated
  app/models/legacy_appeal.rb
  spec/models/legacy_appeal_spec.rb
Labels: Ready-to-Merge

#15256 Add EndProductChangeValidator for calculating edit eligibility
  app/workflows/end_product_change_validator.rb
  spec/workflows/end_product_change_validator_spec.rb
Labels: Ready-to-Merge

#15234 Added DocketSwitchMailTask
  app/models/tasks/docket_switch_mail_task.rb
  app/models/tasks/mail_task.rb
  app/repositories/task_action_repository.rb
  client/COPY.json
  client/constants/TASK_ACTIONS.json
  db/seeds/users.rb
  spec/factories/task.rb
  spec/models/organizations/clerk_of_the_board_spec.rb
  spec/models/tasks/docket_switch_mail_task_spec.rb
  spec/models/tasks/mail_task_spec.rb
  spec/seeds/users_spec.rb
Labels: Ready-to-Merge, Team: Foxtrot 🦊

#15242 Handle convert travel board
  app/models/tasks/change_hearing_request_type_task.rb
  spec/controllers/tasks_controller_spec.rb
  spec/factories/task.rb
Labels: Ready-to-Merge

#15260 Add DecisionDateChecker job
  app/jobs/data_integrity_checks_job.rb
  app/services/decision_date_checker.rb
  spec/jobs/data_integrity_checks_job_spec.rb
  spec/services/decision_date_checker_spec.rb
Labels: Product: caseflow-intake, Team: Foxtrot 🦊, Type: Bug, Type: Tech-Improvement

#14879 Accessible Styling of `SearchableDropdown` with `readOnly`
  client/app/styles/react/_select-dropdown.scss
Labels: Ready-to-Merge, Team: Foxtrot 🦊

#15248 Automate fix for RedistributedCase::CannotRedistribute Sentry alert
  app/models/task.rb
  app/services/redistributed_case.rb
  spec/models/distribution_spec.rb
  spec/services/redistributed_case_spec.rb
Labels: Ready-to-Merge

#15277 Set Docker image to 0.11.4
  docker-compose.yml
Labels: Ready-to-Merge

#15169 Re-add pay grade validation
  app/models/veteran.rb
  app/services/external_api/bgs_service.rb
  spec/feature/intake/intake_spec.rb
Labels: Ready-to-Merge, Team: Foxtrot 🦊

#15233 Always display hearing time in edt/ro timezone for Video/formally-video hearings
  client/app/hearings/components/HearingTime.jsx
Labels: Ready-to-Merge, Team: Tango 💃

#15230 Reset virtual hearing states on cancel
  client/app/hearings/components/Details.jsx
  client/app/hearings/contexts/HearingsFormContext.jsx
Labels: Ready-to-Merge, Team: Tango 💃

#15279 Updated CreateMailTaskDialog to Support Customized Success Alert Content
  client/COPY.json
  client/app/queue/CreateMailTaskDialog.jsx
  spec/feature/queue/docket_change_spec.rb
Labels: Ready-to-Merge

#15297 Remove unnecessary router definition
  client/app/reader/index.jsx
Labels: Ready-to-Merge

#15301 re-add one-second sleep between calls to the va.gov service
  app/services/external_api/va_dot_gov_service.rb
Labels: Ready-to-Merge, Team: Tango 💃

#15299 Create a new Link component in Caseflow (based on the component from the Frontend Toolkit)
  client/app/components/Link.jsx
  client/app/reader/PdfUI.jsx
Labels: Ready-to-Merge

#15291 Geomatch Travel Board Hearings
  app/jobs/fetch_hearing_locations_for_veterans_job.rb
  app/models/appeal.rb
  client/COPY.json
  client/app/hearings/components/HearingTypeConversionForm.jsx
  client/app/hearings/components/HearingTypeConversionForm.stories.js
  client/test/app/hearings/components/HearingTypeConversionForm.test.js
  client/test/app/hearings/components/__snapshots__/HearingTypeConversionForm.test.js.snap
  spec/jobs/fetch_hearing_locations_for_veterans_job_spec.rb
  spec/models/appeal_spec.rb
Labels: Ready-to-Merge, Team: Tango 💃

#15294 Add hearing_request_type and formally_travel to cached_appeal_attributes
  app/jobs/update_cached_appeals_attributes_job.rb
  app/models/legacy_appeal.rb
  db/migrate/20200923004430_add_hearing_request_type_and_formally_travel_to_cached_appeals_attributes.rb
  db/schema.rb
  docs/schema/caseflow.csv
  spec/jobs/update_cached_appeals_attributes_job_spec.rb
Labels: Ready-to-Merge, Team: Tango 💃

#15307 Revert total_batch_size to JudgeTeam query
  app/models/distribution.rb
Labels: Ready-to-Merge

#15273 Attorney Fees | Bug Fix | Allow adding attorney claimant when veteran has no relationships
  client/COPY.json
  client/app/intake/components/SelectClaimant.jsx
  client/app/intake/pages/review.jsx
  spec/feature/intake/higher_level_review_spec.rb
  spec/feature/intake/review_page_spec.rb
Labels: Ready-to-Merge

#15312 Display hearing request type column on assign hearings table
  app/controllers/hearings/schedule_hearing_tasks_controller.rb
  app/models/queue_tabs/assign_hearing_tab.rb
  app/models/serializers/work_queue/task_column_serializer.rb
  client/app/hearings/components/assignHearings/AssignHearingsDocketLine.jsx
  client/app/hearings/components/assignHearings/AssignHearingsFields.jsx
  client/app/hearings/components/assignHearings/AssignHearingsTable.jsx
  client/app/queue/utils.js
  client/constants/QUEUE_CONFIG.json
  spec/feature/hearings/assign_hearings_table_spec.rb
  spec/feature/hearings/schedule_veteran/build_hearsched_spec.rb
Labels: Ready-to-Merge, Team: Tango 💃

#15315 Include user id when sending data to Google Analytics
  app/views/layouts/_head_google_analytics.html.erb
Labels: Eng: Data Work Group, Priority: Low, Ready-to-Merge, Type: Metrics or Reporting

#15340 Edit EP Claim Labels | Add "type" to request issue
  db/migrate/20200928194138_add_request_issue_type_to_request_issues.rb
  db/migrate/20200928194631_backfill_request_issue_type.rb
  db/schema.rb
  docs/schema/caseflow.csv
Labels: Ready-to-Merge

#15313 Ensure days waiting of oldest appeal in slack report includes non genpop cases
  .reek.yml
  app/models/concerns/automatic_case_distribution.rb
  app/models/docket.rb
  app/models/dockets/hearing_request_docket.rb
  app/models/dockets/legacy_docket.rb
  app/models/vacols/case_docket.rb
  app/repositories/appeal_repository.rb
  spec/jobs/push_priority_appeals_to_judges_job_spec.rb
  spec/models/distribution_spec.rb
  spec/models/docket_spec.rb
  spec/models/dockets/hearing_request_docket_spec.rb
  spec/models/vacols/case_docket_spec.rb
Labels: Feature: auto-case-distribution, Priority: Medium, Ready-to-Merge, Stakeholder: BVA, Team: Echo 🐬, Type: Bug, User: Judge

#15344 Revert "Edit EP Claim Labels | Add "type" to request issue (#15340)"
  db/migrate/20200928194138_add_request_issue_type_to_request_issues.rb
  db/migrate/20200928194631_backfill_request_issue_type.rb
  db/schema.rb
  docs/schema/caseflow.csv
Labels: Ready-to-Merge

#15319 Fix issue where Schedule Veteran page was displaying at bottom of page
  app/models/tasks/schedule_hearing_task.rb
  app/repositories/task_action_repository.rb
  client/app/queue/QueueApp.jsx
  client/app/queue/components/ActionsDropdown.jsx
  client/app/queue/components/PostponeHearingModal.jsx
  client/constants/TASK_ACTIONS.json
Labels: Ready-to-Merge, Team: Tango 💃

#15304 Create CavcTask model
  app/models/tasks/cavc_task.rb
  app/models/validators/parent_task_validator.rb
  app/serializers/hearings/hearing_day_serializer.rb
  client/COPY.json
  spec/factories/task.rb
  spec/models/tasks/cavc_task_spec.rb
Labels: Priority: Medium, Product: caseflow-queue, Ready-to-Merge

#15316 Retry getting a rating profile on BGS::ShareError
  app/models/promulgated_rating.rb
  lib/fakes/bgs_service.rb
  spec/models/promulgated_rating_spec.rb
  spec/models/rating_at_issue_spec.rb
Labels: Ready-to-Merge, Team: Foxtrot 🦊

#15317 Show disabilities with rating ID unless duplicate
  app/models/rating_decision.rb
  app/workflows/contestable_issue_generator.rb
  spec/models/rating_decision_spec.rb
  spec/workflows/contestable_issue_generator_spec.rb
Labels: Ready-to-Merge, Team: Foxtrot 🦊

#15328 Only consider genpop appeals when attempting to evenly distribute cases to judges
  app/jobs/push_priority_appeals_to_judges_job.rb
  app/models/concerns/proportion_hash.rb
  app/models/docket.rb
  app/models/docket_coordinator.rb
  app/models/dockets/hearing_request_docket.rb
  app/models/dockets/legacy_docket.rb
  app/models/vacols/case_docket.rb
  app/repositories/appeal_repository.rb
  spec/jobs/push_priority_appeals_to_judges_job_spec.rb
  spec/models/docket_coordinator_spec.rb
Labels: Feature: auto-case-distribution, Priority: Medium, Product: caseflow-queue, Ready-to-Merge, Stakeholder: BVA, Team: Echo 🐬, Type: Bug, User: Judge

#15346 Edit EP Claim Labels | Adds back "type" to request issue
  db/migrate/20200929164648_add_type_to_request_issues.rb
  db/migrate/20200929170305_backfill_request_issue_type.rb
  db/schema.rb
  docs/schema/caseflow.csv
Labels: Ready-to-Merge

#15345 Do not load attorneys if props don't tell us to
  client/app/queue/QueueLoadingScreen.jsx
Labels: Eng: Performance, Feature: generic-queue, Priority: Low, Product: caseflow-queue, Ready-to-Merge, Stakeholder: BVA, Type: Tech-Improvement, User: Judge
