Repository department-of-veterans-affairs/caseflow, pull requests merged in 2020-11, with the labels that each got.

#15546 Fix flakey test
  spec/feature/intake/confirmation_page_spec.rb
Labels: Team: Foxtrot 🦊

#15547 Ensure Consistent Fake Data in AddClaimantModal Tests
  client/test/app/intake/components/AddClaimantModal.test.js
Labels: Ready-to-Merge, Team: Foxtrot 🦊

#15468 Update changes method for request issues update
  app/models/request_issues_update.rb
  spec/models/request_issues_update_spec.rb
  yarn.lock
Labels: Priority: Medium, Product: caseflow-intake, Team: Foxtrot 🦊, Type: Bug

#15543 Update reschedule/cancel email language in virtual hearing email
  app/views/virtual_hearing_mailer/sections/_rescheduling_or_canceling_your_hearing.erb
  lib/tasks/emails.rake
  spec/factories/hearing.rb
  spec/factories/virtual_hearing.rb
Labels: Ready-to-Merge, Team: Tango 💃

#14278 Change logic for routing withdraw requests
  app/models/legacy_appeal.rb
  app/models/legacy_appeal_representative.rb
  app/models/tasks/hearing_task.rb
  app/models/tasks/schedule_hearing_task.rb
  spec/feature/queue/hearings_tasks_spec.rb
  spec/models/legacy_appeal_representative_spec.rb
  spec/models/tasks/hearing_task_spec.rb
  spec/models/tasks/schedule_hearing_task_spec.rb
Labels: Ready-to-Merge, Team: Tango 💃

#15551 Do not pull every atty individually when calculating batch size
  app/models/concerns/automatic_case_distribution.rb
  app/models/distribution.rb
  app/models/docket_coordinator.rb
  app/models/judge_team_role.rb
Labels: Feature: auto-case-distribution, Priority: Medium, Product: caseflow-queue, Ready-to-Merge, Stakeholder: BVA, Team: Echo 🐬, Type: Tech-Improvement

#15533 Add CAVC Remand Section to Case Details
  app/models/appeal.rb
  app/models/serializers/work_queue/appeal_serializer.rb
  client/COPY.json
  client/app/queue/CaseDetailsView.jsx
  client/app/queue/CavcDetail.jsx
  client/app/queue/CavcDetail.stories.mdx
  client/app/queue/utils.js
  client/constants/CAVC_REMAND_SUBTYPE_NAMES.json
Labels: Ready-to-Merge

#15544 Add Markdown support to task instructions on Case Details page
  client/app/queue/components/TaskRows.jsx
  client/app/queue/docketSwitch/recommendDocketSwitch/RecommendDocketSwitchContainer.jsx
  client/package.json
  client/test/app/queue/docketChange/RecommendDocketSwitchContainer.test.js
  client/test/app/queue/docketChange/__snapshots__/RecommendDocketSwitchContainer.test.js.snap
  client/yarn.lock
  spec/feature/queue/case_details_spec.rb
  spec/feature/queue/docket_change_spec.rb
Labels: Ready-to-Merge, Team: Foxtrot 🦊

#15553 Redistribute hearing request cases
  app/models/distributed_case.rb
  app/models/vacols/case_docket.rb
  app/services/redistributed_case.rb
  app/workflows/hearing_request_case_distributor.rb
  spec/models/distributed_case_spec.rb
  spec/models/dockets/hearing_request_docket_spec.rb
Labels: Feature: auto-case-distribution, Priority: Medium, Product: caseflow-queue, Ready-to-Merge, Stakeholder: BVA, Team: Echo 🐬, Type: Bug, User: Judge

#15524 Replace InvalidParentTask with ParentTaskValidator
  app/models/tasks/assign_hearing_disposition_task.rb
  app/models/tasks/special_case_movement_task.rb
  app/models/tasks/timed_hold_task.rb
  app/models/tasks/transcription_task.rb
  app/models/validators/parent_task_validator.rb
  spec/models/tasks/assign_hearing_disposition_task_spec.rb
  spec/models/tasks/cavc_task_spec.rb
  spec/models/tasks/special_case_movement_shared_examples.rb
  spec/models/tasks/timed_hold_task_spec.rb
  spec/models/tasks/transcription_task_spec.rb
  spec/models/validators/parent_task_validator_spec.rb
Labels: Ready-to-Merge

#15539 refactor feature test dropdown helper
  client/COPY.json
  client/app/components/DataDropdowns/HearingCoordinator.jsx
  client/app/components/DataDropdowns/HearingRoom.jsx
  client/app/components/DataDropdowns/Judge.jsx
  spec/feature/hearings/hearing_details_spec.rb
  spec/support/feature_helper.rb
Labels: Ready-to-Merge, Type: Tech-Improvement

#15564 Cancel all hearing tasks without callbacks when canceling a ChangeHearingRequestTypeTask
  app/models/tasks/change_hearing_request_type_task.rb
  app/services/hearing_task_tree_initializer.rb
  app/workflows/tasks_for_appeal.rb
  spec/controllers/tasks_controller_spec.rb
  spec/factories/task.rb
  spec/feature/hearings/convert_travel_board_hearing/edit_hearsched_spec.rb
  spec/models/tasks/change_hearing_request_type_task_spec.rb
  spec/services/hearing_task_tree_initializer_spec.rb
  spec/workflows/tasks_for_appeal_spec.rb
Labels: Ready-to-Merge, Team: Tango 💃

#15550 Handle data edits for changing rating issues to nonrating
  app/models/end_product_update.rb
  spec/models/end_product_update_spec.rb
Labels: Ready-to-Merge

#15558 Minor tweaks to onboarding script
  README.md
  scripts/dev_env_setup_step1.sh
Labels: Ready-to-Merge, Type: Documentation

#15516 Disable SVSR from Intaking a new AMA form
  app/controllers/intakes_controller.rb
  app/models/user.rb
  app/services/external_api/bgs_service.rb
  lib/fakes/bgs_service.rb
  spec/feature/intake/intake_spec.rb
  spec/models/user_spec.rb
Labels: Ready-to-Merge

#15557 Create templates for virtual hearing reminder emails
  app/mailers/virtual_hearing_mailer.rb
  app/views/virtual_hearing_mailer/_appellant_reminder.html.erb
  app/views/virtual_hearing_mailer/_representative_reminder.html.erb
  app/views/virtual_hearing_mailer/reminder.html.erb
  app/views/virtual_hearing_mailer/sections/_test_your_connection.html.erb
  lib/tasks/emails.rake
  spec/factories/virtual_hearing.rb
  spec/mailers/virtual_hearing_mailer_spec.rb
Labels: Ready-to-Merge, Team: Tango 💃

#15542 Pass the latest not cancelled IHP task on an appeal to the front end
  app/models/appeal.rb
  app/models/legacy_appeal.rb
  app/models/queue_tab.rb
  app/models/serializers/work_queue/legacy_task_serializer.rb
  app/models/serializers/work_queue/task_column_serializer.rb
  spec/models/appeal_shared_examples.rb
  spec/models/appeal_spec.rb
  spec/models/legacy_appeal_spec.rb
Labels: Ready-to-Merge

#15579 Color Slack messages from jobs based on title then body contents
  app/jobs/set_appeal_age_aod_job.rb
  app/jobs/stats_collector_job.rb
  app/jobs/update_appellant_representation_job.rb
  app/jobs/update_cached_appeals_attributes_job.rb
  app/services/slack_service.rb
  spec/jobs/set_appeal_age_aod_job_spec.rb
  spec/jobs/update_cached_appeals_attributes_job_spec.rb
  spec/services/slack_service_spec.rb
Labels: Ready-to-Merge, Source: Bat Team

#15587 Add ability to tag docker images with a branch name
  docker-bin/tagnpush.sh
Labels: Ready-to-Merge

#15577 Cache hearings related fields selectively
  .reek.yml
  app/jobs/hearings/geomatch_and_cache_appeal_job.rb
  app/jobs/update_cached_appeals_attributes_job.rb
  app/services/cached_appeal_service.rb
  spec/jobs/hearings/geomatch_and_cache_appeal_job_spec.rb
  spec/jobs/update_cached_appeals_attributes_job_spec.rb
  spec/services/cached_appeal_service_spec.rb
Labels: Ready-to-Merge

#15548 Add SendCavcRemandProcessedLetterTask
  app/controllers/tasks_controller.rb
  app/models/tasks/cavc_task.rb
  app/models/tasks/send_cavc_remand_processed_letter_task.rb
  app/repositories/task_action_repository.rb
  app/workflows/initial_tasks_factory.rb
  client/COPY.json
  spec/factories/task.rb
  spec/feature/queue/cavc_task_queue_spec.rb
  spec/models/tasks/cavc_task_spec.rb
  spec/models/tasks/send_cavc_remand_processed_letter_task_spec.rb
  spec/models/tasks/task_shared_examples.rb
  spec/workflows/initial_tasks_factory_spec.rb
Labels: Priority: Medium, Product: caseflow-queue, Ready-to-Merge, Stakeholder: BVA, Team: Echo 🐬, Type: New Development

#15438 Added tech spec for refactoring Reader application
  docs/tech-specs/2020-10-16-reader-refactor.md
Labels: Ready-to-Merge

#15582 Update rating issue descriptions when converting from nonrating
  app/models/end_product_update.rb
  spec/models/end_product_update_spec.rb
Labels: Ready-to-Merge

#15586 Intake | Docket Change | Recommendation success banner
  client/COPY.json
  client/app/queue/docketSwitch/recommendDocketSwitch/RecommendDocketSwitchContainer.jsx
  spec/feature/queue/docket_change_spec.rb
Labels: Ready-to-Merge

#15600 Revert "Cache hearings related fields selectively"
  .reek.yml
  app/jobs/hearings/geomatch_and_cache_appeal_job.rb
  app/jobs/update_cached_appeals_attributes_job.rb
  app/services/cached_appeal_service.rb
  spec/jobs/hearings/geomatch_and_cache_appeal_job_spec.rb
  spec/jobs/update_cached_appeals_attributes_job_spec.rb
  spec/services/cached_appeal_service_spec.rb
Labels: Ready-to-Merge

#15592 Limit the creation of ChangeHearingRequestTypeTasks
  app/models/legacy_appeal.rb
  app/models/user.rb
  app/workflows/tasks_for_appeal.rb
  spec/feature/hearings/convert_travel_board_hearing/edit_hearsched_spec.rb
  spec/workflows/tasks_for_appeal_spec.rb
Labels: Ready-to-Merge, Team: Tango 💃

#15534 Show end product label on edit
  app/controllers/intakes_controller.rb
  app/models/decision_review.rb
  app/models/end_product_establishment.rb
  app/serializers/intake/decision_review_intake_serializer.rb
  app/views/higher_level_reviews/edit.html.erb
  app/views/supplemental_claims/edit.html.erb
  client/app/intake/pages/addIssues.jsx
  client/app/intake/pages/decisionReviewEditCompleted.jsx
  client/app/intake/pages/decisionReviewIntakeCompleted.jsx
  client/app/intake/reducers/featureToggles.js
  client/app/intake/reducers/intake.js
  client/app/intake/util/issues.js
  client/app/styles/_intake.scss
  client/constants/EP_CLAIM_TYPES.json
  client/test/app/intake/util/__snapshots__/issues.test.js.snap
  spec/feature/intake/edit_ep_claim_labels_spec.rb
  spec/feature/intake/higher_level_review/edit_spec.rb
  spec/feature/intake/supplemental_claim/edit_spec.rb
Labels: Ready-to-Merge, Team: Foxtrot 🦊

#15595 Stuck Appeals Job now finds appeals where on_hold tasks do not have an active descendant
  app/queries/appeals_with_no_tasks_or_all_tasks_on_hold_query.rb
  spec/queries/appeals_with_no_tasks_or_all_tasks_on_hold_query_spec.rb
  spec/services/stuck_appeals_checker_spec.rb
Labels: Ready-to-Merge

#15254 Add Knapsack Pro to CircleCI
  .circleci/config.yml
  Gemfile
  Gemfile.lock
  README.md
  spec/rails_helper.rb
Labels: Ready-to-Merge, Type: Tech-Improvement

#15604 Fix video room and dockets per date constants
  app/services/hearing_schedule/generate_hearing_days_schedule.rb
Labels: Ready-to-Merge

#15593 Only allocate CO dockets once per week
  .reek.yml
  app/services/hearing_schedule/generate_hearing_days_schedule.rb
  spec/controllers/hearings/schedule_periods_controller_spec.rb
  spec/feature/hearings/build_schedule/build_hearsched_spec.rb
  spec/models/hearing_day_spec.rb
  spec/services/hearing_schedule/generate_hearing_days_schedule_spec.rb
Labels: Ready-to-Merge, Team: Tango 💃

#15555 Confirm correct case ordering for cavc ama appeals
  app/models/appeal.rb
  app/models/serializers/v2/appeal_status_serializer.rb
  app/models/task.rb
  app/models/task_sorter.rb
  client/constants/AMA_STREAM_TYPES.json
  config/brakeman.ignore
  db/seeds/mtv.rb
  spec/factories/appeal.rb
  spec/factories/docket_change.rb
  spec/factories/post_decision_motions.rb
  spec/feature/api/v2/appeals_spec.rb
  spec/feature/queue/motion_to_vacate_spec.rb
  spec/models/appeal_spec.rb
  spec/models/task_pager_spec.rb
  spec/models/task_sorter_spec.rb
  spec/models/tasks/bva_dispatch_task_spec.rb
  spec/models/tasks/colocated_task_spec.rb
  spec/models/tasks/judge_task_spec.rb
  spec/models/tasks/task_shared_examples.rb
  spec/workflows/bulk_task_assignment_spec.rb
  spec/workflows/initial_tasks_factory_spec.rb
  spec/workflows/post_decision_motion_updater_spec.rb
Labels: Ready-to-Merge

#15581 Add job to send virtual hearing reminder emails
  app/controllers/api/v1/jobs_controller.rb
  app/jobs/virtual_hearings/send_email.rb
  app/jobs/virtual_hearings/send_reminder_emails_job.rb
  app/models/hearings/sent_hearing_email_event.rb
  app/models/hearings/virtual_hearing.rb
  app/repositories/virtual_hearing_repository.rb
  app/services/virtual_hearings/reminder_service.rb
  db/migrate/20201104175215_add_reminder_email_flags_to_virtual_hearings.rb
  db/schema.rb
  docs/schema/caseflow.csv
  spec/factories/virtual_hearing.rb
  spec/jobs/virtual_hearings/send_reminder_emails_job_spec.rb
  spec/repositories/virtual_hearing_repository_spec.rb
  spec/services/virtual_hearings/reminder_service_spec.rb
Labels: Ready-to-Merge, Team: Tango 💃

#15591 Check if the user is the judge or attorney on a case review to determine what actions they see in LegacyTasks
  app/models/legacy_appeal.rb
  app/models/queues/legacy_work_queue.rb
  spec/models/legacy_appeal_spec.rb
Labels: Feature: caseflow-decisions, Priority: Medium, Product: caseflow-queue, Ready-to-Merge, Team: Echo 🐬, Type: Enhancement, User: AVLJ

#15506 Removes 'Built with <3 by Digital Service at VA' from the Caseflow footer
  app/views/layouts/application.html.erb
Labels: Ready-to-Merge

#15602 Backend and routing for edit NOD date save functionality
  app/controllers/appeals_controller.rb
  app/models/appeal.rb
  app/schemas/appeals_schemas.rb
  config/routes.rb
  spec/models/appeal_spec.rb
Labels: Feature: Edit NOD, Ready-to-Merge, Team: X-ray 💀

#15624 Fill out application and queue priority on email reminder job
  app/jobs/virtual_hearings/send_reminder_emails_job.rb
  spec/controllers/api/v1/jobs_controller_spec.rb
Labels: Ready-to-Merge

#15623 Write comments for Build Hearing Schedule functionality
  app/controllers/hearings/schedule_periods_controller.rb
  app/models/hearings/allocation.rb
  app/models/hearings/co_non_availability.rb
  app/models/hearings/ro_non_availability.rb
  app/models/judge_schedule_period.rb
  app/models/ro_schedule_period.rb
  app/models/schedule_period.rb
  app/services/hearing_schedule/assign_judges_to_hearing_days.rb
  app/services/hearing_schedule/generate_hearing_days_schedule.rb
  app/services/hearing_schedule/ro_allocation.rb
Labels: Ready-to-Merge

#15609 Docket Switch Denial View
  client/COPY.json
  client/app/queue/docketSwitch/denial/DocketSwitchDenialContainer.jsx
  client/app/queue/docketSwitch/denial/DocketSwitchDenialForm.jsx
  client/app/queue/docketSwitch/denial/DocketSwitchDenialForm.stories.js
  client/app/queue/docketSwitch/denial/docketSwitchDenialSlice.js
  client/app/queue/docketSwitch/docketSwitchRoutes.js
  client/test/app/queue/docketSwitch/DocketSwitchDenialForm.test.js
  client/test/app/queue/docketSwitch/__snapshots__/DocketSwitchDenialForm.test.js.snap
  spec/factories/task.rb
  spec/feature/queue/docket_switch_spec.rb
Labels: Ready-to-Merge, Team: Foxtrot 🦊

#15598 Handle edge cases for EvidenceSubmissionWindowTasks
  app/models/concerns/asyncable.rb
  spec/models/concerns/timeable_task_spec.rb
Labels: Ready-to-Merge

#15626 Set current user in reminder emails job
  app/jobs/virtual_hearings/create_conference_job.rb
  app/jobs/virtual_hearings/delete_conferences_job.rb
  app/jobs/virtual_hearings/ensure_current_user_is_set.rb
  app/jobs/virtual_hearings/send_reminder_emails_job.rb
Labels: Ready-to-Merge

#15617 Allow appeals to be searched by their stream docket number
  app/services/appeal_finder.rb
  app/workflows/case_search_results_for_docket_number.rb
  spec/services/appeal_finder_spec.rb
Labels: Ready-to-Merge

#15625 CASEFLOW-108 #resolve Create CavcRemandProcessedLetterResponseWindowTask
  app/controllers/tasks_controller.rb
  app/models/tasks/cavc_remand_processed_letter_response_window_task.rb
  app/models/tasks/send_cavc_remand_processed_letter_task.rb
  app/repositories/task_action_repository.rb
  client/COPY.json
  spec/feature/queue/cavc_task_queue_spec.rb
  spec/models/tasks/cavc_remand_processed_letter_response_window_task_spec.rb
  spec/models/tasks/send_cavc_remand_processed_letter_task_spec.rb
Labels: Priority: Medium, Product: caseflow-queue, Ready-to-Merge, Stakeholder: BVA, Team: Echo 🐬, Type: Enhancement

#15634 Resolve double reminder bug
  app/services/virtual_hearings/reminder_service.rb
  spec/jobs/virtual_hearings/send_reminder_emails_job_spec.rb
Labels: Ready-to-Merge

#15633 Add fields to IDT appeals detail serializer
  app/models/serializers/idt/v1/appeal_details_serializer.rb
  spec/models/serializers/idt/appeal_details_serializer_spec.rb
Labels: Ready-to-Merge, Team: Foxtrot 🦊

#15622 Restrict All Docket Switch Attorney Task Actions to COTB Users
  app/models/tasks/docket_switch/docket_switch_abstract_attorney_task.rb
  app/models/tasks/docket_switch/docket_switch_denied_task.rb
  app/models/tasks/docket_switch/docket_switch_granted_task.rb
  app/models/tasks/docket_switch/docket_switch_mail_task.rb
  spec/models/tasks/docket_switch_denied_task_spec.rb
  spec/models/tasks/docket_switch_granted_task_spec.rb
  spec/models/tasks/docket_switch_mail_task_spec.rb
Labels: Ready-to-Merge, Team: Foxtrot 🦊

#15637 Task sorter fix for sort by task label
  app/models/task_sorter.rb
  spec/feature/intake/add_issues_spec.rb
  spec/models/task_sorter_spec.rb
Labels: Ready-to-Merge, Team: Foxtrot 🦊

#15631 CASEFLOW-106 #done Allow CAVC Litigation Support Users to Correct Issues
  app/policies/appeal_request_issues_policy.rb
  client/app/intake/pages/addIssues.jsx
  spec/feature/queue/cavc_task_queue_spec.rb
Labels: Priority: Medium, Product: caseflow-queue, Ready-to-Merge, Stakeholder: BVA, Team: Echo 🐬, Type: Enhancement, User: Litigation Support

#15614 Update withdraw hearing copy; add withdraw hearing action for AssignHearingDispositionTask
  app/models/concerns/task_extension_for_hearings.rb
  app/models/legacy_appeal.rb
  app/models/legacy_appeal_representative.rb
  app/models/tasks/assign_hearing_disposition_task.rb
  app/models/tasks/schedule_hearing_task.rb
  app/repositories/task_action_repository.rb
  client/COPY.json
  client/app/queue/components/CancelTaskModal.jsx
  spec/feature/hearings/schedule_veteran/build_hearsched_spec.rb
  spec/models/legacy_appeal_representative_spec.rb
  spec/models/tasks/assign_hearing_disposition_task_spec.rb
Labels: Ready-to-Merge

#15629 Edit Claim Label Confirmation modal
  client/COPY.json
  client/app/intake/pages/addIssues.jsx
  client/app/intakeEdit/components/ConfirmClaimLabelModal.jsx
  client/app/intakeEdit/components/ConfirmClaimLabelModal.stories.js
  client/app/intakeEdit/components/EditClaimLabelModal.jsx
  client/test/app/intake/components/ConfirmClaimLabelModal.test.js
  client/test/app/intake/components/EditClaimLabelModal.test.js
  client/test/app/intake/components/__snapshots__/ConfirmClaimLabelModal.test.js.snap
  client/test/app/intake/components/__snapshots__/EditClaimLabelModal.test.js.snap
  spec/feature/intake/edit_ep_claim_labels_spec.rb
Labels: Ready-to-Merge, Team: Foxtrot 🦊

#15642 Add class-level comment to ScheduleHearingColocatedTask
  app/models/tasks/schedule_hearing_colocated_task.rb
Labels: Ready-to-Merge

#15641 Include docket number and stream type in `treee` rendering
  app/models/concerns/task_tree_render_module.rb
Labels: Priority: Low, Ready-to-Merge, Team: Echo 🐬, Type: Enhancement
