Repository department-of-veterans-affairs/caseflow, pull requests merged in 2020-04, with the labels that each got.

#13824 Enable pagination for all organizations
  app/controllers/organizations/tasks_controller.rb
  app/models/organization.rb
  app/models/organizations/colocated.rb
  app/models/organizations/hearings_management.rb
  app/models/organizations/vso.rb
  app/models/queue_config.rb
  client/app/queue/OrganizationQueue.jsx
  client/app/queue/OrganizationQueueLoadingScreen.jsx
  client/test/karma/queue/ColocatedTaskListView-test.js
  spec/controllers/organizations/tasks_controller_spec.rb
  spec/feature/queue/task_queue_spec.rb
  spec/models/organization_spec.rb
  spec/models/queue_config_spec.rb
Labels: Ready-to-Merge

#13812 Added COVID-19 Field to UntimelyExemptionModal
  app/controllers/intakes_controller.rb
  app/models/request_issue.rb
  app/services/api/v3/decision_review/contestable_issue_params.rb
  app/views/appeals/edit.html.erb
  app/views/higher_level_reviews/edit.html.erb
  app/workflows/request_issue_correction.rb
  client/app/intake/actions/decisionReview.js
  client/app/intake/components/AddIssueManager.jsx
  client/app/intake/components/UntimelyExemptionModal.jsx
  client/app/intake/index.js
  client/app/intake/reducers/featureToggles.js
  client/app/intake/util/issues.js
  client/test/karma/intake/UntimelyExemptionModal-test.js
  spec/feature/intake/add_issues_spec.rb
Labels: Ready-to-Merge, Team: Foxtrot 🦊

#13848 Do not leak PII into slack from stacktrace
  app/jobs/update_cached_appeals_attributes_job.rb
  spec/jobs/update_cached_appeals_attributes_job_spec.rb
Labels: Ready-to-Merge

#13853 Part 2 - Upgrade rubocop version - Make codeclimate fixes
  .rubocop.yml
  Rakefile
  app/controllers/appeals_controller.rb
  app/controllers/document_controller.rb
  app/controllers/idt/api/v1/base_controller.rb
  app/jobs/virtual_hearings/send_email.rb
  app/models/docket.rb
  app/models/docket_coordinator.rb
  app/models/hearing_day.rb
  app/models/hearings/available_hearing_locations.rb
  app/models/intake.rb
  app/models/legacy_appeal.rb
  app/models/legacy_hearing.rb
  app/models/task_sorter.rb
  app/models/user.rb
  app/models/vacols/mail.rb
  app/repositories/appeal_repository.rb
  app/repositories/queue_repository.rb
  app/services/api/v3/decision_review/contestable_issue_finder.rb
  app/services/appeal_finder.rb
  app/services/claim_review_async_stats_reporter.rb
  app/services/hearing_schedule/generate_hearing_days_schedule.rb
  app/services/judge_team_role_checker.rb
  app/services/metrics/certification_usage.rb
  app/services/slack_service.rb
  lib/fakes/initializer.rb
  lib/helpers/sanitizers.rb
  spec/controllers/hearings_controller_spec.rb
  spec/controllers/organizations/task_pages_controller_spec.rb
  spec/factories/vacols/case.rb
  spec/models/distribution_spec.rb
  spec/models/tasks/informal_hearing_presentation_task_spec.rb
  spec/models/tasks/quality_review_task_spec.rb
  spec/rails_helper.rb
  spec/services/asyncable_jobs_spec.rb
  spec/workflows/initial_tasks_factory_spec.rb
Labels: Eng: Backend Work Group, Type: Tech-Improvement

#13844 Don't alert for MailTask creation for closed appeals
  app/models/tasks/root_task.rb
  spec/models/tasks/root_task_spec.rb
Labels: Priority: Medium, Product: caseflow-queue, Ready-to-Merge, Source: Sentry Alert, Team: Echo 🐬, Type: Investigation

#13847 Clarify 'Cancel task' action on AttorneyTasks
  app/models/tasks/attorney_task.rb
  client/constants/TASK_ACTIONS.json
  spec/models/tasks/attorney_task_spec.rb
Labels: Priority: Medium, Product: caseflow-queue, Ready-to-Merge, Team: Echo 🐬, Type: Tech-Improvement

#13859 Fix tiny Datadog bug in send_email
  app/jobs/virtual_hearings/send_email.rb
Labels: Product: caseflow-hearings, Ready-to-Merge, Source: Bat Team, Team: Tango 💃, Type: Bug

#13860 Response timeout is not individually actionable
  client/app/queue/components/HearingBadge.jsx
Labels: Ready-to-Merge

#13689 Add sentry alert issue template
  .github/ISSUE_TEMPLATE/sentry-alert.md
Labels: Ready-to-Merge

#13866 efolder document_count as background job
  app/controllers/appeals_controller.rb
  app/controllers/application_controller.rb
  app/jobs/fetch_efolder_document_count_job.rb
  app/services/external_api/efolder_service.rb
  client/app/queue/AppealDocumentCount.jsx
  spec/jobs/fetch_efolder_document_count_job_spec.rb
  spec/services/external_api/efolder_service_spec.rb
Labels: Ready-to-Merge

#13842 Move concern, add check for already-cancelled hearing task
  app/models/concerns/task_extension_for_hearings.rb
  app/models/tasks/schedule_hearing_task.rb
Labels: Ready-to-Merge, Team: Tango 💃

#13875 Workaround for `Cannot read property 'range' of null` ESLint Bug
  client/.eslintrc.js
Labels: Eng: Frontend Work Group, Ready-to-Merge, Team: Foxtrot 🦊, Type: Bug

#13702 Refresh details and daily docket page data
  app/controllers/hearings_controller.rb
  app/models/hearings/forms/base_hearing_update_form.rb
  app/models/hearings/virtual_hearing.rb
  app/serializers/hearings/virtual_hearing_serializer.rb
  app/services/virtual_hearing_user_alert_builder.rb
  client/COPY.json
  client/app/components/ExponentialPolling.jsx
  client/app/components/common/actionTypes.js
  client/app/components/common/actions.js
  client/app/components/common/reducers.js
  client/app/hearings/components/Details.jsx
  client/app/hearings/components/dailyDocket/DailyDocketRow.jsx
  client/app/hearings/containers/DailyDocketContainer.jsx
  client/app/hearings/utils.js
  client/package.json
  client/yarn.lock
  config/routes.rb
  docs/tech-specs/2020-04-01-transitioning-alerts.md
  spec/feature/hearings/hearing_details_spec.rb
  spec/feature/hearings/virtual_hearings/daily_docket_spec.rb
  spec/feature/hearings/virtual_hearings/hearing_details_spec.rb
Labels: Ready-to-Merge, Team: Tango 💃

#13803 Log video to virtual hearing conversions to datadog
  app/jobs/virtual_hearings/conference_job.rb
  app/jobs/virtual_hearings/create_conference_job.rb
  app/jobs/virtual_hearings/delete_conferences_job.rb
  app/models/hearings/forms/base_hearing_update_form.rb
  client/app/hearings/components/Details.jsx
  spec/feature/hearings/virtual_hearings/hearing_details_spec.rb
  spec/jobs/virtual_hearings/create_conference_job_spec.rb
  spec/models/hearings/forms/hearing_update_form_spec.rb
Labels: Product: caseflow-hearings, Ready-to-Merge, Team: Tango 💃

#13880 Intake | Bug | Do not require veteran city for intake
  app/models/veteran.rb
Labels: Ready-to-Merge

#13881 Intake | Bug | Return true for blank city in claimant validator
  app/models/validators/claimant_validator.rb
  spec/models/validators/claimant_validator_spec.rb
Labels: Ready-to-Merge

#13813 Add HearingsUserContext for Hearing Details
  client/app/hearings/HearingsApp.jsx
  client/app/hearings/HearingsUserContext.jsx
  client/app/hearings/components/Details.jsx
  client/app/hearings/components/DetailsSections.jsx
  client/app/hearings/components/details/DetailsInputs.jsx
  client/app/hearings/containers/DetailsContainer.jsx
Labels: Eng: Frontend Work Group, Ready-to-Merge, Team: Tango 💃, Type: Tech-Improvement

#13886 Add DailyCountsStatsCollector
  app/jobs/stats_collector_job.rb
  app/services/collectors/daily_counts_stats_collector.rb
  spec/services/collectors/daily_counts_stats_collector_spec.rb
Labels: Priority: Low, Ready-to-Merge, Team: Echo 🐬, Type: Metrics or Reporting

#13873 New Speial Issues on Legacy Appeals
  app/controllers/special_issues_controller.rb
  app/views/dispatch/establish_claims/show.html.erb
  app/views/queue/index.html.erb
  client/app/constants/SpecialIssueEnabler.js
  client/app/constants/SpecialIssueFilters.js
  client/app/constants/SpecialIssues.js
  client/app/containers/EstablishClaimPage/EstablishClaim.jsx
  client/app/containers/EstablishClaimPage/EstablishClaimDecision.jsx
  client/app/containers/EstablishClaimPage/EstablishClaimEmail.jsx
  client/app/containers/EstablishClaimPage/EstablishClaimForm.jsx
  client/app/containers/EstablishClaimPage/EstablishClaimNote.jsx
  client/app/establishClaim/reducers/specialIssues.js
  client/app/establishClaim/selectors/index.js
  client/app/establishClaim/util/index.js
  client/app/queue/SelectSpecialIssuesView.jsx
  client/test/karma/constants/SpecialIssuesFilters-test.js
  db/migrate/20200324135048_add_new_issues_to_special_issue_list.rb
  db/schema.rb
  docs/schema/caseflow.csv
Labels: Ready-to-Merge

#13887 Update Various JS Deps 2020-03
  client/package.json
  client/yarn.lock
Labels: Ready-to-Merge, Team: Foxtrot 🦊

#13894 fix flakey hearing task pager spec
  spec/models/hearings/schedule_hearing_task_pager_spec.rb
Labels: Ready-to-Merge, Team: Tango 💃

#13885 Use default backoff multiplier
  client/app/hearings/utils.js
Labels: Product: caseflow-hearings, Ready-to-Merge, Team: Tango 💃

#13896 Fix flaky task filter spec
  app/models/task_filter.rb
  spec/models/task_filter_spec.rb
Labels: Ready-to-Merge

#13603 Intake | Only allow appeal intakes for MailTeam users
  app/controllers/intakes_controller.rb
  app/models/user.rb
  client/COPY.json
  client/app/intake/IntakeFrame.jsx
  client/app/intake/pages/selectForm.jsx
  client/app/intake/reducers/featureToggles.js
  spec/feature/intake/intake_spec.rb
  spec/models/user_spec.rb
Labels: Product: caseflow-intake, Ready-to-Merge, Stakeholder: BVA, Team: Foxtrot 🦊, User: BVA Intake

#13897 Cached appeals indices
  app/models/task.rb
  db/migrate/20200405223053_add_cached_appeal_indices.rb
  db/schema.rb
Labels: Ready-to-Merge

#13879 Display Original Issue Text in AddedIssue Along with Edited Text
  client/app/intake/components/AddedIssue.jsx
  spec/feature/intake/add_issues_spec.rb
Labels: Ready-to-Merge, Team: Foxtrot 🦊

#13867 Automatically close old DecisionReviewTasks
  app/jobs/nightly_syncs_job.rb
  app/services/decision_review_tasks_for_inactive_appeals_checker.rb
  spec/jobs/nightly_syncs_job_spec.rb
Labels: Ready-to-Merge

#13898 Cache veteran's, claimant's, POA's zip code, state, and country
  app/models/address.rb
  app/models/veteran.rb
  app/services/bgs_address_service.rb
  spec/models/claimant_spec.rb
  spec/models/veteran_spec.rb
Labels: Product: caseflow-hearings, Ready-to-Merge, Team: Tango 💃

#13899 Clean up selectors
  client/app/queue/OrganizationQueue.jsx
  client/app/queue/selectors.js
Labels: Ready-to-Merge

#13089 Missing Ratings | Implement Decisions at issue BGS Service
  app/models/concerns/latest_rating_disability_evaluation.rb
  app/models/decision_review.rb
  app/models/decision_review_intake.rb
  app/models/end_product_establishment.rb
  app/models/promulgated_rating.rb
  app/models/rating.rb
  app/models/rating_at_issue.rb
  app/models/request_issue.rb
  app/models/veteran.rb
  app/services/external_api/bgs_service.rb
  lib/fakes/bgs_service.rb
  lib/fakes/bgs_service_record_maker.rb
  lib/generators/promulgated_rating.rb
  lib/generators/rating.rb
  lib/generators/rating_at_issue.rb
  spec/controllers/higher_level_reviews_controller_spec.rb
  spec/feature/intake/add_issues_spec.rb
  spec/feature/intake/end_product_correction_spec.rb
  spec/feature/intake/higher_level_review_spec.rb
  spec/feature/intake/intake_edit_confirmation_spec.rb
  spec/models/appeal_intake_spec.rb
  spec/models/board_grant_effectuation_spec.rb
  spec/models/claim_review_spec.rb
  spec/models/decision_review_spec.rb
  spec/models/end_product_establishment_spec.rb
  spec/models/promulgated_rating_spec.rb
  spec/models/rating_at_issue_spec.rb
  spec/models/rating_decision_spec.rb
  spec/models/rating_issue_spec.rb
  spec/models/rating_spec.rb
  spec/models/request_issue_spec.rb
  spec/requests/api/v3/decision_review/contestable_issues_controller_spec.rb
  spec/support/intake_helpers.rb
  spec/workflows/contestable_issue_generator_spec.rb
Labels: Product: caseflow-intake, Ready-to-Merge, Team: Foxtrot 🦊

#13903 Fixed Routing for Organizations Views
  client/app/queue/QueueApp.jsx
  client/app/queue/components/BulkAssignModal.jsx
  client/app/queue/components/QueueFlowModal.jsx
Labels: Ready-to-Merge, Team: Foxtrot 🦊, Type: Bug

#13906 Intake | Update copy on appeal permissions alert
  client/COPY.json
  client/app/components/InboxLink.jsx
  client/app/components/IntakeLink.jsx
  client/app/intake/pages/selectForm.jsx
  spec/feature/intake/intake_spec.rb
  spec/models/user_spec.rb
Labels: Ready-to-Merge, Stakeholder: BVA, Team: Foxtrot 🦊, Type: Enhancement

#13905 Create a non-admin hearing coordinator user
  db/seeds.rb
Labels: Ready-to-Merge

#13923 Refresh link data on Details
  app/controllers/hearings_controller.rb
  client/app/hearings/components/Details.jsx
  client/app/hearings/components/dailyDocket/DailyDocketRow.jsx
Labels: Product: caseflow-hearings, Ready-to-Merge, Team: Tango 💃, Type: Bug

#13919 Handle undefined alerts from server
  client/app/components/common/actions.js
  client/app/hearings/components/Details.jsx
  client/app/hearings/components/VirtualHearingModal.jsx
  client/app/hearings/components/dailyDocket/DailyDocketRow.jsx
Labels: Product: caseflow-hearings, Ready-to-Merge, Team: Tango 💃, Type: Bug

#13943 upgrade caseflow-commons gem to 0.4.6
  Gemfile
  Gemfile.lock
Labels: Ready-to-Merge

#13895 Update stats collectors to use tagged metrics
  app/jobs/stats_collector_job.rb
  app/services/collectors/daily_counts_stats_collector.rb
  app/services/collectors/request_issues_stats_collector.rb
  app/services/collectors/stats_collector.rb
  spec/jobs/stats_collector_job_spec.rb
  spec/services/collectors/daily_counts_stats_collector_spec.rb
  spec/services/collectors/request_issues_stats_collector_spec.rb
Labels: Priority: Low, Ready-to-Merge, Team: Echo 🐬, Type: Metrics or Reporting

#13933 Capture DataIntegrityChecksJob errors to slack/sentry
  app/jobs/caseflow_job.rb
  app/jobs/data_integrity_checks_job.rb
  spec/jobs/data_integrity_checks_job_spec.rb
Labels: Ready-to-Merge

#13953 Fix missing Loading spinner on Veteran Case Search page
  client/app/queue/CaseList/CaseListReducer.js
Labels: Ready-to-Merge

#13907 Tech spec for storing information about virtual hearings emails
  docs/tech-specs/2020-04-06-virtual-hearings-sent-email-records.md
Labels: Ready-to-Merge, Team: Tango 💃

#13970 Add test to ensure newly added Reader labels return correctly
  spec/models/document_spec.rb
Labels: Ready-to-Merge

#13941 Allow motions attorney to recommend partial grant
  client/app/queue/mtv/MTVDispositionSelection.jsx
  client/app/queue/mtv/MTVJudgeDisposition.jsx
  client/app/queue/mtv/MotionsAttorneyDisposition.jsx
  client/constants/MOTION_TO_VACATE.json
  spec/feature/queue/motion_to_vacate_spec.rb
Labels: Product: caseflow-queue, Ready-to-Merge, Stakeholder: BVA, Team: Foxtrot 🦊, Type: Enhancement

#13916 Case Review & BVA Intake Model Cleanup
  app/models/organizations/bva_intake.rb
  app/models/organizations/case_review.rb
  db/seeds.rb
Labels: Ready-to-Merge

#13974 Remove Lighthouse References From API v3 Documentation
  app/controllers/api/docs/v3/decision_reviews.yaml
Labels: Ready-to-Merge

#13940 Make cancelled appeal obvious in case search
  app/models/serializers/work_queue/appeal_serializer.rb
  client/app/constants/AppConstants.js
  client/app/queue/CaseListTable.jsx
  client/app/queue/utils.js
  spec/feature/queue/search_spec.rb
Labels: Ready-to-Merge

#13969 Intake | Update copy on appeal permissions alert
  client/COPY.json
  client/app/intake/pages/selectForm.jsx
  spec/feature/intake/intake_spec.rb
Labels: Ready-to-Merge, Stakeholder: BVA, Team: Foxtrot 🦊, Type: Enhancement

#13990 Add virtual hearing ID to send_email logging
  app/jobs/virtual_hearings/send_email.rb
Labels: Product: caseflow-hearings, Ready-to-Merge, Team: Tango 💃

#13902 Reorganize layout of Hearing Details page
  client/app/components/TextField.jsx
  client/app/hearings/components/Details.jsx
  client/app/hearings/components/DetailsSections.jsx
  client/app/hearings/components/details/DetailsInputs.jsx
  client/app/hearings/components/details/HearingTypeDropdown.jsx
  client/app/hearings/components/details/TranscriptionDetailsInputs.jsx
  client/app/hearings/components/details/TranscriptionProblemInputs.jsx
  client/app/hearings/components/details/TranscriptionRequestInputs.jsx
  client/app/hearings/components/details/style.jsx
  client/package.json
Labels: Product: caseflow-hearings, Ready-to-Merge, Team: Tango 💃, Type: UI Change

#13997 Intake | When we get a DuplicateEP error for an established EP, update EPE attributes
  app/models/end_product_establishment.rb
  spec/models/end_product_establishment_spec.rb
Labels: Product: caseflow-intake, Ready-to-Merge, Type: Bug

#14006 Add prefix to facilities request cache key
  app/services/external_api/va_dot_gov_service.rb
  client/yarn.lock
Labels: Ready-to-Merge, Team: Tango 💃

#13985 MTV | Judge Can Return to Lit Support for Any Disposition/Reason
  client/COPY.json
  client/app/queue/mtv/MTVJudgeDisposition.jsx
  client/app/queue/mtv/MissingDraftAlert.jsx
  client/app/queue/mtv/ReturnToLitSupportAlert.jsx
  client/app/queue/mtv/ReturnToLitSupportAlert.stories.js
  client/app/queue/mtv/mtvConstants.js
  spec/feature/queue/motion_to_vacate_spec.rb
Labels: Ready-to-Merge, Team: Foxtrot 🦊

#14001 Remove code related to data research for veteran addresses
  app/models/veteran.rb
  app/services/bgs_address_service.rb
  spec/models/claimant_spec.rb
  spec/models/veteran_spec.rb
Labels: Product: caseflow-hearings, Ready-to-Merge, Team: Tango 💃

#14024 Fix DailyDocket test failure related to current date
  spec/feature/hearings/daily_docket/build_hearsched_spec.rb
Labels: Eng: Testing and Development, Product: caseflow-hearings, Ready-to-Merge

#13971 allow Manage Claim Establishment users to access the jobs endpoint
  app/controllers/asyncable_jobs_controller.rb
  spec/controllers/asyncable_jobs_controller_spec.rb
Labels: Product: IDT, Ready-to-Merge

#12870 Save Disposition better
  client/app/hearings/components/dailyDocket/DailyDocket.jsx
  client/app/hearings/components/dailyDocket/DailyDocketModals.jsx
  client/app/hearings/components/dailyDocket/DailyDocketRow.jsx
  client/app/hearings/components/dailyDocket/DailyDocketRowInputs.jsx
  client/app/hearings/components/dailyDocket/style.js
  client/app/hearings/utils.js
  spec/feature/hearings/daily_docket/build_hearsched_spec.rb
Labels: Ready-to-Merge, Team: Tango 💃

#13984 Show badge for overtime cases
  app/models/appeal.rb
  app/models/legacy_appeal.rb
  app/models/serializers/work_queue/appeal_serializer.rb
  app/models/serializers/work_queue/legacy_appeal_serializer.rb
  app/models/serializers/work_queue/legacy_task_serializer.rb
  app/models/serializers/work_queue/task_serializer.rb
  app/models/user.rb
  app/views/queue/index.html.erb
  client/app/queue/CaseListTable.jsx
  client/app/queue/CaseTitle.jsx
  client/app/queue/QueueApp.jsx
  client/app/queue/components/Badge.jsx
  client/app/queue/components/BadgeArea.jsx
  client/app/queue/components/HearingBadge.jsx
  client/app/queue/components/OvertimeBadge.jsx
  client/app/queue/uiReducer/uiActions.js
  client/app/queue/uiReducer/uiConstants.js
  client/app/queue/uiReducer/uiReducer.js
  client/app/queue/utils.js
  client/test/karma/components/OvertimeBadge-test.js
  spec/controllers/tasks_controller_spec.rb
  spec/feature/queue/overtime_spec.rb
Labels: Ready-to-Merge

#14012 Do not show judge or attorney for a cancelled appeal
  client/COPY.json
  client/app/queue/CaseTitleDetails.jsx
  spec/feature/queue/ama_queue_spec.rb
  spec/feature/queue/case_details_spec.rb
Labels: Ready-to-Merge

#14005 Add schema for sent email events
  db/migrate/20200414195209_create_sent_hearing_email_events.rb
  db/schema.rb
  docs/schema/caseflow.csv
Labels: Product: caseflow-hearings, Ready-to-Merge, Team: Tango 💃

#14028 change phoenix RO timezone to America/Phoenix
  client/constants/REGIONAL_OFFICE_FACILITY_ADDRESS.json
  client/constants/REGIONAL_OFFICE_INFORMATION.json
Labels: Ready-to-Merge, Team: Tango 💃

#14007 Add Special Issues Page for AMA appeals
  app/models/tasks/judge_decision_review_task.rb
  app/repositories/task_action_repository.rb
  client/COPY.json
  client/app/constants/SpecialIssueFilters.js
  client/app/constants/SpecialIssues.js
  client/app/queue/SelectDispositionsView.jsx
  client/app/queue/SelectSpecialIssuesView.jsx
  client/app/queue/components/QueueFlowPage.jsx
  client/constants/TASK_ACTIONS.json
  spec/feature/queue/attorney_checkout_flow_spec.rb
  spec/feature/queue/judge_checkout_flow_spec.rb
Labels: Priority: Medium, Product: caseflow-queue, Ready-to-Merge, Stakeholder: BVA, Team: Echo 🐬, Type: Enhancement

#14031 add America/Phoenix to hearing day slots
  app/models/hearing_day.rb
Labels: Ready-to-Merge, Team: Tango 💃

#14032 Update copy on special issues page
  client/COPY.json
  spec/feature/queue/attorney_checkout_flow_spec.rb
  spec/feature/queue/judge_checkout_flow_spec.rb
Labels: Ready-to-Merge

#14003 Remove status field from DB and instead calculate from conference job status
  app/controllers/hearings_controller.rb
  app/jobs/virtual_hearings/create_conference_job.rb
  app/models/concerns/has_virtual_hearing.rb
  app/models/hearings/forms/base_hearing_update_form.rb
  app/models/hearings/virtual_hearing.rb
  app/queries/video_hearing_day_request_type_query.rb
  app/repositories/virtual_hearing_repository.rb
  app/serializers/hearings/virtual_hearing_serializer.rb
  client/app/hearings/components/Details.jsx
  client/app/hearings/components/details/HearingTypeDropdown.jsx
  db/migrate/20200413160545_remove_status_from_virtual_hearings.rb
  db/migrate/20200416161705_add_is_cancelled_to_virtual_hearing.rb
  db/schema.rb
  docs/schema/caseflow.csv
  spec/controllers/api/v2/hearings_controller_spec.rb
  spec/controllers/hearings_controller_spec.rb
  spec/factories/virtual_hearing.rb
  spec/feature/hearings/virtual_hearings/daily_docket_spec.rb
  spec/feature/hearings/virtual_hearings/hearing_details_spec.rb
  spec/jobs/virtual_hearings/create_conference_job_spec.rb
  spec/jobs/virtual_hearings/delete_conferences_job_spec.rb
  spec/queries/video_hearing_day_request_type_query_spec.rb
  spec/repositories/virtual_hearing_repository_spec.rb
Labels: Ready-to-Merge

#14010 Pluralize
  app/jobs/decision_issue_sync_job.rb
  app/jobs/dependencies_report_service_log_job.rb
  app/models/establish_claim.rb
  app/models/tasks/board_grant_effectuation_task.rb
  app/services/open_tasks_with_closed_at_checker.rb
  client/COPY.json
  client/app/components/FilterSummary.jsx
  client/app/containers/EstablishClaimPage/EstablishClaimAssociateEP.jsx
  client/app/containers/EstablishClaimPage/EstablishClaimDecision.jsx
  client/app/containers/StyleGuide/StyleGuideSearchableDropdown.jsx
  client/app/hearings/components/assignHearings/AssignHearingsTable.jsx
  client/app/hearings/components/assignHearings/UpcomingHearingsTable.jsx
  client/app/hearings/components/dailyDocket/DailyDocketRows.jsx
  client/app/help/components/CertificationHelp.jsx
  client/app/help/components/HearingsHelp.jsx
  client/app/help/components/ReaderHelp.jsx
  client/app/intake/components/ErrorAlert.jsx
  client/app/intake/pages/rampElection/finish.jsx
  client/app/queue/AddEditIssueView.jsx
  client/app/queue/OrganizationQueue.jsx
  client/app/reader/SideBarIssueTags.jsx
  client/constants/JUDGE_CASE_REVIEW_OPTIONS.json
  lib/tasks/users.rake
  spec/feature/intake/appeal/edit_spec.rb
  spec/feature/intake/intake_spec.rb
  spec/feature/intake/review_page_spec.rb
  spec/feature/queue/attorney_queue_spec.rb
  spec/feature/reader/reader_spec.rb
  spec/jobs/dependencies_report_service_log_job_spec.rb
  spec/models/concerns/asyncable_spec.rb
  spec/models/establish_claim_spec.rb
  spec/services/open_tasks_with_closed_at_checker_spec.rb
Labels: Ready-to-Merge

#13937 Updates to Hyperlinks during MTV Attorney Review
  client/COPY.json
  client/app/queue/mtv/MotionsAttorneyDisposition.jsx
  client/app/queue/mtv/forms/AddHyperlinkModal.jsx
  client/app/queue/mtv/forms/AddHyperlinkModal.stories.js
  client/app/queue/mtv/forms/DecisionHyperlinks.jsx
  client/app/queue/mtv/forms/DecisionHyperlinks.stories.js
  spec/feature/queue/motion_to_vacate_spec.rb
  spec/support/queue_helpers.rb
Labels: Ready-to-Merge, Team: Foxtrot 🦊

#13959 Allow timeliness exemptions for legacy opt-in
  app/views/supplemental_claims/edit.html.erb
  client/COPY.json
  client/app/intake/components/AddIssueManager.jsx
  client/app/intake/components/UntimelyExemptionModal.jsx
  client/app/intake/reducers/higherLevelReview.js
  client/app/intake/reducers/supplementalClaim.js
  spec/feature/intake/add_issues_spec.rb
  spec/feature/intake/supplemental_claim/edit_spec.rb
Labels: Ready-to-Merge, Team: Foxtrot 🦊, User: VBA Intake

#14042 Fix issue where task hearing is nil
  app/models/concerns/task_extension_for_hearings.rb
Labels: Product: caseflow-hearings, Ready-to-Merge, Team: Tango 💃, Type: Bug

#13850 Part 1 - Upgrade rubocop version
  .codeclimate.yml
  .rubocop.yml
  Gemfile
  Gemfile.lock
  Rakefile
  app/controllers/appeals_controller.rb
  app/controllers/document_controller.rb
  app/controllers/idt/api/v1/base_controller.rb
  app/jobs/virtual_hearings/send_email.rb
  app/models/docket.rb
  app/models/docket_coordinator.rb
  app/models/hearing_day.rb
  app/models/hearings/available_hearing_locations.rb
  app/models/intake.rb
  app/models/legacy_appeal.rb
  app/models/legacy_hearing.rb
  app/models/task_sorter.rb
  app/models/user.rb
  app/models/vacols/mail.rb
  app/repositories/appeal_repository.rb
  app/repositories/queue_repository.rb
  app/services/api/v3/decision_review/contestable_issue_finder.rb
  app/services/api/v3/decision_review/contestable_issue_params.rb
  app/services/appeal_finder.rb
  app/services/claim_review_async_stats_reporter.rb
  app/services/collectors/stats_collector.rb
  app/services/hearing_schedule/generate_hearing_days_schedule.rb
  app/services/judge_team_role_checker.rb
  app/services/metrics/certification_usage.rb
  app/services/slack_service.rb
  lib/fakes/initializer.rb
  lib/helpers/sanitizers.rb
  spec/controllers/hearings_controller_spec.rb
  spec/controllers/organizations/task_pages_controller_spec.rb
  spec/factories/vacols/case.rb
  spec/models/distribution_spec.rb
  spec/models/docket_coordinator_spec.rb
  spec/models/tasks/informal_hearing_presentation_task_spec.rb
  spec/models/tasks/quality_review_task_spec.rb
  spec/rails_helper.rb
  spec/services/asyncable_jobs_spec.rb
  spec/workflows/initial_tasks_factory_spec.rb
Labels: Eng: Backend Work Group, Ready-to-Merge, Type: Tech-Improvement

#14011 Upgrade rspec to 3.9.0 and rspec-rails to 4.0.0
  Gemfile.lock
Labels: Eng: Backend Work Group, Ready-to-Merge, Type: Tech-Improvement

#14035 Shalliburton/13778 status toggle
  client/app/hearings/components/Details.jsx
  client/app/hearings/components/VirtualHearingModal.jsx
  client/app/hearings/components/details/HearingTypeDropdown.jsx
  client/app/hearings/utils.js
Labels: Ready-to-Merge

#14047 Validate special issues dispatch page
  client/app/containers/EstablishClaimPage/EstablishClaimDecision.jsx
  client/app/establishClaim/constants/index.js
  client/app/establishClaim/reducers/index.js
  spec/feature/dispatch/establish_claim_spec.rb
Labels: Ready-to-Merge

#14051 Motion to Vacate | Add Pulac-Cerullo task action to Judge Task
  app/models/tasks/judge_decision_review_task.rb
  spec/models/tasks/judge_task_spec.rb
Labels: Ready-to-Merge

#13932 Intake | COVID-19 update | Add alternate legacy opt-in eligibility rules
  app/models/decision_review.rb
  app/models/issue.rb
  app/models/legacy_appeal.rb
  app/models/request_issue.rb
  client/COPY.json
  client/app/intake/actions/addIssues.js
  client/app/intake/components/AddIssueManager.jsx
  client/app/intake/components/AddedIssue.jsx
  client/app/intake/components/IssueList.jsx
  client/app/intake/components/LegacyOptInModal.jsx
  client/app/intake/util/issues.js
  client/constants/DATES.json
  spec/feature/intake/add_issues_spec.rb
  spec/feature/intake/higher_level_review/edit_spec.rb
  spec/feature/intake/higher_level_review_spec.rb
  spec/models/issue_spec.rb
  spec/models/legacy_appeal_spec.rb
  spec/models/request_issue_spec.rb
  spec/support/intake_helpers.rb
Labels: Ready-to-Merge, Stakeholder: VBA, Team: Foxtrot 🦊, Type: Enhancement

#14060 Remove SEND_TO_TEAM and COLOCATED_ACTION_SEND_TO_TEAM
  client/COPY.json
  client/constants/TASK_ACTIONS.json
Labels: Ready-to-Merge

#14065 Clarify wording on cancel appeal modal
  client/COPY.json
  client/app/components/Modal.jsx
  client/app/containers/StyleGuide/StyleGuideModal.jsx
  client/app/intakeEdit/components/EditButtons.jsx
  client/app/intakeEdit/components/SaveAlertConfirmModal.jsx
  spec/feature/intake/higher_level_review/edit_spec.rb
Labels: Ready-to-Merge

#14063 Enable list axe rule
  client/app/components/AmaIssueList.jsx
  client/app/queue/OrganizationUsers.jsx
  spec/support/VA-axe-run-configuration.json
Labels: Ready-to-Merge

#14027 Create email event receipts when sending hearings notifications
  .reek.yml
  app/jobs/virtual_hearings/create_conference_job.rb
  app/jobs/virtual_hearings/send_email.rb
  app/models/concerns/has_virtual_hearing.rb
  app/models/hearings/sent_hearing_email_event.rb
  app/models/hearings/virtual_hearing.rb
  db/migrate/20200421220601_update_comment_on_sent_hearing_email_event.rb
  db/migrate/20200421231908_add_updated_by_id_to_virtual_hearings.rb
  db/schema.rb
  docs/schema/caseflow.csv
  spec/factories/sent_hearing_email_event.rb
  spec/factories/virtual_hearing.rb
  spec/feature/hearings/virtual_hearings/daily_docket_spec.rb
  spec/feature/hearings/virtual_hearings/hearing_details_spec.rb
  spec/jobs/virtual_hearings/create_conference_job_spec.rb
  spec/jobs/virtual_hearings/delete_conferences_job_spec.rb
  spec/jobs/virtual_hearings/send_email_spec.rb
  spec/models/hearings/sent_hearing_email_event_spec.rb
Labels: Product: caseflow-hearings, Ready-to-Merge, Team: Tango 💃

#14076 Add Datadog to the Demo env to test the traces
  Dockerfile
  config/initializers/datadog.rb
  docker-bin/build.sh
  docker-bin/env.sh
  docker-bin/startup.sh
Labels: Ready-to-Merge

#14075 Added proper escaping to search string in CommentsTable regex
  client/app/reader/CommentsTable.jsx
  spec/feature/reader/reader_spec.rb
Labels: Ready-to-Merge, Source: Sentry Alert, Team: Foxtrot 🦊

#14064 Redirect mixed case CSS_IDs in URL
  app/controllers/concerns/css_id_concern.rb
  app/controllers/legacy_tasks_controller.rb
  app/controllers/users_controller.rb
  spec/controllers/legacy_tasks_controller_spec.rb
  spec/controllers/users_controller_spec.rb
Labels: Feature: generic-queue, Priority: Medium, Product: caseflow-queue, Ready-to-Merge, Stakeholder: BVA, Team: Echo 🐬, Type: Bug, User: Judge

#14086 fix sent hearing email event bug
  app/jobs/virtual_hearings/send_email.rb
  app/models/hearings/virtual_hearing.rb
Labels: Product: caseflow-hearings, Ready-to-Merge, Stakeholder: BVA, Team: Tango 💃

#14046 Added frontend validation for virtual hearing emails
  client/app/hearings/components/Details.jsx
  client/app/hearings/components/details/DetailsInputs.jsx
  client/app/hearings/components/details/style.jsx
Labels: Ready-to-Merge

#14088 Better Handling of Unexpected / Malformed Errors in LookupParticipantIdModal
  client/app/queue/LookupParticipantIdModal.jsx
Labels: Ready-to-Merge, Source: Sentry Alert, Team: Foxtrot 🦊, Type: Bug

#14080 TypeError: Cannot read property 'description' of undefined in IntakeEdit
  app/serializers/intake/request_issue_serializer.rb
  spec/feature/intake/higher_level_review/edit_spec.rb
  spec/feature/intake/higher_level_review_spec.rb
Labels: Product: caseflow-intake, Ready-to-Merge, Team: Foxtrot 🦊, Type: Bug

#13922 BgsPowerOfAttorney model
  .reek.yml
  app/controllers/idt/api/v1/base_controller.rb
  app/controllers/idt/api/v1/veterans_controller.rb
  app/jobs/warm_bgs_caches_job.rb
  app/mappers/power_of_attorney_mapper.rb
  app/models/appeal.rb
  app/models/bgs_power_of_attorney.rb
  app/models/claimant.rb
  app/models/power_of_attorney.rb
  app/services/bgs_power_of_attorney.rb
  app/services/external_api/bgs_service.rb
  config/initializers/datadog.rb
  db/migrate/20200407163044_create_bgs_power_of_attorneys.rb
  db/schema.rb
  docs/schema/caseflow.csv
  lib/fakes/bgs_service.rb
  lib/fakes/bgs_service_poa.rb
  spec/controllers/idt/api/appeals_controller_spec.rb
  spec/controllers/idt/api/veterans_controller_spec.rb
  spec/controllers/organizations/tasks_controller_spec.rb
  spec/controllers/organizations_controller_spec.rb
  spec/factories/bgs_power_of_attorney.rb
  spec/feature/hearings/list_schedule/vso_spec.rb
  spec/feature/hearings/schedule_veteran/build_hearsched_spec.rb
  spec/feature/queue/ama_queue_spec.rb
  spec/jobs/warm_bgs_caches_job_spec.rb
  spec/mappers/power_of_attorney_mapper_spec.rb
  spec/models/appeal_spec.rb
  spec/models/bgs_power_of_attorney_spec.rb
  spec/models/hearing_spec.rb
  spec/models/representative_spec.rb
  spec/models/tasks/assign_hearing_disposition_task_spec.rb
  spec/models/tasks/evidence_submission_window_task_spec.rb
  spec/models/tasks/schedule_hearing_task_spec.rb
  spec/models/user_spec.rb
  spec/services/hearing_day_range_spec.rb
  spec/workflows/ama_appeal_dispatch_spec.rb
  spec/workflows/initial_tasks_factory_spec.rb
Labels: Ready-to-Merge

#14094 More aggressive caching of BGS POA
  app/jobs/warm_bgs_caches_job.rb
  app/models/bgs_power_of_attorney.rb
  app/models/power_of_attorney.rb
  spec/jobs/warm_bgs_caches_job_spec.rb
Labels: Ready-to-Merge

#14093 Optimize as subselect query
  app/models/claimant.rb
  app/models/concerns/has_appeal_updated_since.rb
  app/models/concerns/has_decision_review_updated_since.rb
  app/models/concerns/has_simple_appeal_updated_since.rb
  app/models/decision_document.rb
  app/models/decision_issue.rb
  app/models/hearing.rb
  app/models/hearings/available_hearing_locations.rb
  app/models/intake.rb
  app/models/post_decision_motion.rb
  app/models/request_issue.rb
  app/models/special_issue_list.rb
  app/models/supplemental_claim.rb
  app/models/task.rb
  app/models/vbms_uploaded_document.rb
  app/queries/appeals_updated_since_query.rb
Labels: Ready-to-Merge

#14095 Fix Encoding::CompatibilityError
  app/models/concerns/asyncable.rb
Labels: Ready-to-Merge

#14096 Remove not_null on bgs_power_of_attorney.file_number
  app/models/appeal.rb
  app/models/bgs_power_of_attorney.rb
  app/models/claimant.rb
  db/migrate/20200427152555_remove_not_null_bgs_poa_file_number.rb
  db/schema.rb
  docs/schema/caseflow.csv
  lib/fakes/bgs_service.rb
  spec/models/appeal_spec.rb
  spec/models/claimant_spec.rb
Labels: Ready-to-Merge

#14098 Use safe navigator for potentially nil POA
  app/models/claimant.rb
Labels: Ready-to-Merge

#14090 Shalliburton/13753 email notifications
  app/models/concerns/has_virtual_hearing.rb
  app/models/hearing.rb
  app/models/hearings/sent_hearing_email_event.rb
  app/models/legacy_hearing.rb
  app/serializers/hearings/hearing_serializer.rb
  app/serializers/hearings/legacy_hearing_serializer.rb
  app/serializers/hearings/sent_email_event_serializer.rb
  client/COPY.json
  client/app/hearings/components/Details.jsx
  client/app/hearings/components/details/DetailsInputs.jsx
  client/app/hearings/components/details/EmailNotificationHistory.jsx
  spec/feature/hearings/virtual_hearings/hearing_details_spec.rb
Labels: Ready-to-Merge

#14008 MTV | Updated File Structure
  client/app/queue/mtv/checkout/AddDecisionIssueModal.module.scss
  client/app/queue/mtv/checkout/AddDecisionIssuesView.jsx
  client/app/queue/mtv/checkout/AddEditDecisionIssueModal.jsx
  client/app/queue/mtv/checkout/AddEditDecisionIssueModal.module.scss
  client/app/queue/mtv/checkout/MotionToVacateCheckoutProgressBar.jsx
  client/app/queue/mtv/checkout/MotionToVacateContext.js
  client/app/queue/mtv/checkout/MotionToVacateFlowContainer.jsx
  client/app/queue/mtv/checkout/RemoveDecisionIssueModal.jsx
  client/app/queue/mtv/checkout/ReviewVacatedDecisionIssuesView.jsx
  client/app/queue/mtv/checkout/SubmitVacatedDecisionsView.jsx
  client/app/queue/mtv/checkout/mtvCheckoutSteps.js
  client/app/queue/mtv/checkout/returnToJudge/ReturnToJudgeAlert.jsx
  client/app/queue/mtv/checkout/returnToJudge/ReturnToJudgeModal.jsx
  client/app/queue/mtv/checkout/returnToJudge/ReturnToJudgeModalContainer.jsx
  client/app/queue/mtv/motionToVacateRoutes.js
Labels: Ready-to-Merge

#14092 Fix create change hearing disposition workflow
  app/models/concerns/task_extension_for_hearings.rb
  app/models/tasks/schedule_hearing_task.rb
  client/app/queue/CreateChangeHearingDispositionTaskModal.jsx
  client/app/queue/components/QueueFlowModal.jsx
  spec/feature/hearings/postpone_hearing_spec.rb
Labels: Product: caseflow-hearings, Ready-to-Merge, Team: Tango 💃

#14108 Safe navigation for use of Veteran.last_name
  app/jobs/update_cached_appeals_attributes_job.rb
Labels: Ready-to-Merge

#14109 Fix flaky test
  spec/models/concerns/associated_vacols_model_spec.rb
Labels: Ready-to-Merge

#14128 AMA date tech debt bill came due
  spec/decorators/appeal_status_api_decorator_spec.rb
  spec/feature/intake/appeal/edit_spec.rb
  spec/feature/intake/higher_level_review/edit_spec.rb
  spec/feature/intake/supplemental_claim/edit_spec.rb
  spec/models/claim_review_spec.rb
  spec/models/higher_level_review_spec.rb
  spec/models/legacy_appeal_spec.rb
  spec/models/request_issue_spec.rb
  spec/models/supplemental_claim_spec.rb
  spec/serializers/issue_serializer_spec.rb
  spec/serializers/status_serializer_spec.rb
  spec/support/date_time_helper.rb
Labels: Ready-to-Merge

#14099 Fix pexip alias
  app/controllers/hearings_controller.rb
  app/jobs/virtual_hearings/create_conference_job.rb
  app/models/hearings/virtual_hearing.rb
  app/serializers/hearings/virtual_hearing_serializer.rb
  app/services/external_api/pexip_service.rb
  client/app/hearings/components/Details.jsx
  client/app/hearings/components/VirtualHearingLink.jsx
  client/app/hearings/components/dailyDocket/DailyDocketRow.jsx
  db/migrate/20200427151605_add_alias_with_host_to_virtual_hearings.rb
  db/schema.rb
  docs/schema/caseflow.csv
  docs/schema/etl.csv
  spec/feature/hearings/virtual_hearings/hearing_details_spec.rb
  spec/jobs/virtual_hearings/create_conference_job_spec.rb
  spec/services/external_api/pexip_service_spec.rb
Labels: Ready-to-Merge, Team: Tango 💃

#14102 Grant AOD fix for cases with previous AOD motions
  app/controllers/advance_on_docket_motions_controller.rb
  app/models/advance_on_docket_motion.rb
  app/models/hearing.rb
  app/models/hearings/forms/hearing_update_form.rb
  client/COPY.json
  client/app/queue/AdvancedOnDocketMotionView.jsx
  client/app/queue/QueueActions.js
  client/app/queue/reducers.js
  client/constants/AOD_REASONS.json
  spec/controllers/advanced_on_docket_motions_controller_spec.rb
  spec/controllers/hearings_controller_spec.rb
  spec/feature/hearings/daily_docket/hearing_prep_spec.rb
  spec/feature/intake/appeal_spec.rb
  spec/feature/queue/ama_queue_spec.rb
  spec/models/advance_on_docket_motion_spec.rb
  spec/models/hearing_spec.rb
Labels: Priority: High, Ready-to-Merge, Type: Bug

#14112 Updated Copy in PulacCerulloReminderAlert
  client/app/queue/pulacCerullo/PulacCerulloReminderAlert.jsx
  client/app/queue/pulacCerullo/PulacCerulloReminderAlert.stories.js
  spec/feature/queue/motion_to_vacate_spec.rb
Labels: Ready-to-Merge, Team: Foxtrot 🦊

#14113 Do not return on hold judge tasks to the front end
  app/controllers/tasks_controller.rb
  app/models/queues/generic_queue.rb
  app/models/queues/judge_queue.rb
  app/models/task.rb
  app/workflows/queue_for_role.rb
  spec/controllers/tasks_controller_spec.rb
  spec/workflows/queue_for_role_spec.rb
Labels: Ready-to-Merge

#14119 Fix hearing flake
  spec/feature/hearings/virtual_hearings/hearing_details_spec.rb
Labels: Ready-to-Merge

#14123 Intake | Disable claim establishments
  app/jobs/decision_review_process_job.rb
  spec/feature/intake/higher_level_review_spec.rb
  spec/jobs/decision_review_process_job_spec.rb
  spec/models/higher_level_review_intake_spec.rb
Labels: Product: caseflow-intake, Ready-to-Merge, Team: Foxtrot 🦊

#14105 Optimize BGS POA calls
  .reek.yml
  app/models/bgs_power_of_attorney.rb
  app/services/cache_manager.rb
  spec/models/bgs_power_of_attorney_spec.rb
  spec/models/claimant_spec.rb
Labels: Ready-to-Merge

#14111 Check for non nill attyid when pulling all judges
  app/models/cached_user.rb
  app/models/vacols/staff.rb
  app/repositories/attorney_repository.rb
  app/repositories/judge_repository.rb
  app/repositories/user_repository.rb
  spec/factories/task.rb
  spec/factories/vacols/case_hearing.rb
  spec/models/cached_user_spec.rb
  spec/repositories/attorney_repository_spec.rb
  spec/repositories/judge_repository_spec.rb
Labels: Ready-to-Merge, Type: Bug

#14126 Fix virtual hearing type not displaying for days with held virtual hearings
  app/queries/video_hearing_day_request_type_query.rb
  spec/factories/hearing.rb
  spec/queries/video_hearing_day_request_type_query_spec.rb
Labels: Ready-to-Merge, Team: Tango 💃

#14120 Optimize stuck appeals query
  app/queries/appeals_with_no_tasks_or_all_tasks_on_hold_query.rb
  spec/queries/appeals_with_no_tasks_or_all_tasks_on_hold_query_spec.rb
Labels: Ready-to-Merge

#14131 LegacyAppeal POA reads from file_number or claimant PID
  .reek.yml
  app/models/bgs_power_of_attorney.rb
  app/models/legacy_appeal.rb
  app/models/power_of_attorney.rb
  spec/models/legacy_appeal_spec.rb
  spec/models/power_of_attorney_spec.rb
Labels: Ready-to-Merge

#14073 Make /queue/<css_id>/assign default url for judge assign page
  app/controllers/legacy_tasks_controller.rb
  app/models/user.rb
  client/app/queue/JudgeAssignTaskListView.jsx
  spec/controllers/legacy_tasks_controller_spec.rb
  spec/feature/queue/judge_assignment_spec.rb
  spec/models/user_spec.rb
Labels: Ready-to-Merge

#14115 Update BVA Board Appeal Restriction | Change Allowed Team/Org from Mail Team to BVA Intake Team
  app/models/user.rb
  app/models/validators/intake_start_validator.rb
  spec/feature/intake/intake_spec.rb
  spec/models/user_spec.rb
  spec/models/validators/intake_start_validator_spec.rb
Labels: Product: caseflow-intake, Ready-to-Merge, Team: Foxtrot 🦊, User: BVA Intake

#14114 Missing ratings | Show all disability rating decisions
  app/workflows/contestable_issue_generator.rb
Labels: Product: caseflow-intake, Ready-to-Merge, Team: Foxtrot 🦊, User: VBA Intake

#14139 Hearings table in ODS/ETL
  .reek.yml
  app/models/etl/hearing.rb
  app/models/hearing.rb
  app/services/etl/builder.rb
  app/services/etl/hearing_syncer.rb
  db/etl/migrate/20200429164923_create_hearings.rb
  db/etl/schema.rb
  docs/schema/caseflow.csv
  docs/schema/etl.csv
  spec/services/etl/hearing_syncer_spec.rb
Labels: Ready-to-Merge

#14121 Encapsulated hearing details diff logic to fix toggle
  client/app/hearings/components/Details.jsx
  client/app/hearings/utils.js
Labels: Ready-to-Merge, Team: Tango 💃

#14149 LegacyHearing in ODS
  .reek.yml
  app/models/concerns/has_virtual_hearing.rb
  app/models/etl/hearing.rb
  app/models/etl/legacy_hearing.rb
  app/models/hearing.rb
  app/services/etl/builder.rb
  app/services/etl/legacy_hearing_syncer.rb
  db/etl/migrate/20200430152234_add_hearing_type.rb
  db/etl/schema.rb
  docs/schema/etl.csv
  spec/services/etl/legacy_hearing_syncer_spec.rb
Labels: Ready-to-Merge

#14154 Correct the echo output
  docker-bin/startup.sh
Labels: Ready-to-Merge
