Repository department-of-veterans-affairs/caseflow, pull requests merged in 2020-02, with the labels that each got.

#13287 Handle save for verified unidentified issues
  app/models/request_issue.rb
  app/serializers/intake/request_issue_serializer.rb
  app/workflows/request_issue_correction.rb
  client/app/intake/actions/addIssues.js
  client/app/intake/components/UnidentifiedIssuesModal.jsx
  client/app/intake/util/issues.js
  db/migrate/20200128033405_add_verified_unidentified_issue_to_request_issues.rb
  db/schema.rb
  spec/feature/intake/higher_level_review_spec.rb
  spec/models/request_issue_spec.rb
Labels: Ready-to-Merge

#13331 Fix bug in intake search when BGS return nil
  app/services/duplicate_veteran_participant_id_finder.rb
Labels: Ready-to-Merge

#13337 Fix error caused by undefined appeals object in SelectRemandReasonsView
  client/app/queue/SelectRemandReasonsView.jsx
  spec/feature/queue/case_details_spec.rb
Labels: Ready-to-Merge

#13347 Support Webpack Resolving JSON Files w/o Extension
  client/.eslintrc.js
  client/webpack.config.js
Labels: Ready-to-Merge

#13344 Update #scheduled_for_past? to work with older hearings
  app/models/legacy_hearing.rb
  spec/models/legacy_hearing_spec.rb
Labels: Ready-to-Merge

#13350 only set timezone to Rails.configuration.time_zone when in uat
  app/jobs/application_job.rb
Labels: Ready-to-Merge, tango

#13320 Wrapped routes in QueueApp in Switch component
  client/app/queue/QueueApp.jsx
Labels: Ready-to-Merge, foxtrot

#13352 Add member_of_organization method to User model
  app/models/user.rb
  spec/models/user_spec.rb
Labels: Ready-to-Merge

#13353 Update default error message in LoadingDataDisplay
  client/app/certification/DocumentsCheck.jsx
  client/app/components/LoadingDataDisplay.jsx
  client/app/containers/EstablishClaimPage/EstablishClaimAssociateEP.jsx
  client/app/hearings/components/ListSchedule.jsx
  client/app/queue/CaseDetailsLoadingScreen.jsx
  client/app/queue/CaseListView.jsx
  client/app/queue/OrganizationQueueLoadingScreen.jsx
  client/app/queue/QueueLoadingScreen.jsx
  client/app/queue/SpecialIssueLoadingScreen.jsx
  client/app/queue/VeteranCasesView.jsx
  client/app/queue/components/BulkAssignModal.jsx
  client/app/util/WindowUtil.js
Labels: Ready-to-Merge

#13364 Update ExternalApi::VBMSService#fetch_document_series_for to fallback to BGS claim ID
  app/services/external_api/vbms_document_series_for_appeal.rb
  app/services/external_api/vbms_documents_for_appeal.rb
  app/services/external_api/vbms_request_with_file_number.rb
  app/services/external_api/vbms_service.rb
Labels: Ready-to-Merge

#13334 Set Up Container Component for MTV Checkout Workflows
  client/app/queue/QueueApp.jsx
  client/app/queue/mtv/AddressMotionToVacateView.jsx
  client/app/queue/mtv/MotionToVacateContext.js
  client/app/queue/mtv/MotionToVacateFlowContainer.jsx
  client/app/queue/mtv/motionToVacateRoutes.js
Labels: Ready-to-Merge

#13368 Detect claims that get changed to a 400 and close the request issues
  app/models/end_product_establishment.rb
  spec/models/request_issue_spec.rb
  spec/services/etl/appeal_syncer_spec.rb
Labels: Ready-to-Merge, foxtrot

#13325 Create a Vacate appeal stream for a Motion to Vacate
  app/models/appeal.rb
  app/models/decision_issue.rb
  app/models/decision_review.rb
  app/models/tasks/judge_sign_motion_to_vacate_task.rb
  app/models/tasks/judge_task.rb
  app/models/tasks/straight_vacate_task.rb
  app/models/tasks/vacate_and_de_novo_task.rb
  app/models/tasks/vacate_and_readjudication_task.rb
  app/workflows/initial_tasks_factory.rb
  app/workflows/post_decision_motion_updater.rb
  client/app/queue/mtv/MTVJudgeDisposition.jsx
  client/constants/MOTION_TO_VACATE.json
  db/seeds.rb
  spec/controllers/post_decision_motions_controller_spec.rb
  spec/factories/task.rb
  spec/feature/intake/higher_level_review/edit_spec.rb
  spec/feature/intake/supplemental_claim/edit_spec.rb
  spec/feature/queue/motion_to_vacate_spec.rb
  spec/models/appeal_spec.rb
  spec/models/higher_level_review_spec.rb
  spec/models/intake_spec.rb
  spec/workflows/post_decision_motion_updater_spec.rb
Labels: Ready-to-Merge, foxtrot

#13096 Update readme
  README.md
Labels: Ready-to-Merge

#13346 Serialize appeal stream information for vacate-type appeals
  app/models/appeal.rb
  app/models/serializers/work_queue/appeal_serializer.rb
  spec/factories/appeal.rb
  spec/models/appeal_spec.rb
Labels: Ready-to-Merge, foxtrot

#13369 modify UpdateCachedAppealsAttributesJob job
  app/jobs/update_cached_appeals_attributes_job.rb
Labels: Ready-to-Merge

#13375 handle null receipt_date in serializer
  app/serializers/intake/decision_review_serializer.rb
Labels: Ready-to-Merge

#13173 Create Vacated Decision Issues from Request Issues
  app/controllers/post_decision_motions_controller.rb
  app/models/decision_issue.rb
  app/models/post_decision_motion.rb
  app/models/request_issue.rb
  app/workflows/post_decision_motion_updater.rb
  spec/controllers/post_decision_motions_controller_spec.rb
  spec/factories/post_decision_motions.rb
  spec/feature/queue/motion_to_vacate_spec.rb
  spec/models/post_decision_motion_spec.rb
  spec/workflows/post_decision_motion_updater_spec.rb
Labels: Ready-to-Merge, foxtrot

#13139 Yoom/tree render class
  .reek.yml
  Gemfile
  Gemfile.lock
  app/models/concerns/prints_task_tree.rb
  app/models/concerns/task_tree_render_module.rb
  spec/models/concerns/task_tree_render_module_spec.rb
Labels: Ready-to-Merge

#13361 When establishing a board grant or remand claim, set the status to "RFD"
  Gemfile
  Gemfile.lock
  app/models/end_product.rb
  app/models/end_product_establishment.rb
  spec/feature/dispatch/establish_claim_spec.rb
  spec/feature/intake/ramp_election_spec.rb
  spec/feature/intake/ramp_refiling_spec.rb
  spec/feature/intake/supplemental_claim_spec.rb
  spec/models/claim_review_spec.rb
  spec/models/decision_document_spec.rb
  spec/models/end_product_establishment_spec.rb
  spec/models/end_product_spec.rb
  spec/models/ramp_election_spec.rb
  spec/models/supplemental_claim_intake_spec.rb
Labels: Ready-to-Merge, foxtrot

#13367 Metric: Certifications via Caseflow
  app/models/vacols/case.rb
  app/services/metrics/certification_usage.rb
  spec/services/metrics/certification_usage_spec.rb
Labels: Ready-to-Merge

#13097 Upgrade Rails to 5.2.4.1
  Gemfile
  Gemfile.lock
  app/repositories/virtual_hearing_repository.rb
  bin/setup
  config/storage.yml
  db/etl/schema.rb
  db/schema.rb
  spec/controllers/case_reviews_controller_spec.rb
  spec/factories/claimant.rb
  spec/factories/supplemental_claim.rb
  spec/models/claim_review_spec.rb
  spec/models/serializers/work_queue/decision_review_task_serializer_spec.rb
Labels: Ready-to-Merge

#13380 include child task id in error message
  app/models/tasks/root_task.rb
Labels: Ready-to-Merge

#13381 Fix AssignWidget to prevent TypeError when in a modal
  client/app/queue/components/AssignWidget.jsx
  client/app/queue/components/QueueFlowModal.jsx
Labels: Ready-to-Merge

#13345 MTV | Attorney Review Decision Issues View
  app/repositories/task_action_repository.rb
  app/workflows/post_decision_motion_updater.rb
  client/COPY.json
  client/app/queue/mtv/MotionToVacateFlowContainer.jsx
  client/app/queue/mtv/RemoveDecisionIssueModal.jsx
  client/app/queue/mtv/ReviewVacatedDecisionIssuesView.jsx
  client/app/queue/mtv/mtvCheckoutSteps.js
  client/constants/TASK_ACTIONS.json
  spec/feature/queue/motion_to_vacate_spec.rb
Labels: Ready-to-Merge, foxtrot

#13388 Fallback to time in VACOLS
  app/models/legacy_hearing.rb
Labels: Ready-to-Merge

#13379 show searchable dropdown error in an error banner instead of as a validation error
  client/app/components/DataDropdowns/AppealHearingLocations.jsx
  spec/feature/hearings/schedule_veteran/build_hearsched_spec.rb
Labels: Ready-to-Merge

#13390 Update label for Virtual Hearing Link
  client/COPY.json
  client/app/hearings/components/VirtualHearingLink.jsx
  client/app/hearings/components/details/DetailsInputs.jsx
  client/app/hearings/utils.js
Labels: Ready-to-Merge

#13398 Update error message for duplicate veteran records
  client/app/intake/pages/search.jsx
  spec/feature/intake/intake_spec.rb
Labels: AMO, Ready-to-Merge, caseflow-intake, foxtrot

#13378 Use version 0.1.1 of the console-tree-renderer gem
  Gemfile
  Gemfile.lock
Labels: Ready-to-Merge

#13386 Associate PostDecisionMotion with appeal rather than task
  app/models/appeal.rb
  app/models/post_decision_motion.rb
  app/workflows/post_decision_motion_updater.rb
  db/migrate/20200206161309_link_motions_to_appeals.rb
  db/schema.rb
  spec/factories/appeal.rb
  spec/factories/post_decision_motions.rb
  spec/models/appeal_spec.rb
  spec/models/post_decision_motion_spec.rb
  spec/workflows/post_decision_motion_updater_spec.rb
Labels: Ready-to-Merge, foxtrot

#13397 ensure nil case_record won't break when getting rep name
  .reek.yml
  app/models/concerns/appeal_available_hearing_locations.rb
  app/models/hearings/available_hearing_locations.rb
  app/repositories/power_of_attorney_repository.rb
Labels: Ready-to-Merge

#13406 Fix same-station bypass FeatureToggle bug
  app/models/validators/intake_start_validator.rb
Labels: BVA Intake, Ready-to-Merge, foxtrot, priority-high

#13403 Update ruby-bgs to get access to common_security
  Gemfile
  Gemfile.lock
Labels: Ready-to-Merge

#13407 Fix null object error in Establish Claim
  client/app/containers/EstablishClaimPage/EstablishClaim.jsx
Labels: Ready-to-Merge

#13409 Implement same-station bypass for MailTeam users at Station 101
  app/models/validators/intake_start_validator.rb
  spec/models/validators/intake_start_validator_spec.rb
Labels: BVA Intake, Ready-to-Merge, foxtrot, priority-high

#13395 Upstream Error | Do not fetch contentions for canceled EP to prevent FileNumberNotFoundForClaimID error
  app/models/end_product_establishment.rb
  spec/models/end_product_establishment_spec.rb
Labels: Ready-to-Merge, foxtrot

#13408 increase postgres db to 9.6 in caseflow
  .circleci/config.yml
  docker-compose-demo.yml
  docker-compose.yml
Labels: Ready-to-Merge

#13419 Fix typo in Virtual Hearings Modal
  client/COPY.json
Labels: Ready-to-Merge

#13424 add make down target
  Makefile.example
Labels: Ready-to-Merge

#13437 Cascade PrivacyActTask closure to FoiaColocatedTask
  app/models/tasks/foia_colocated_task.rb
Labels: Ready-to-Merge

#13401 ETL Build tables
  .circleci/config.yml
  .reek.yml
  app/jobs/etl_builder_job.rb
  app/models/etl/build.rb
  app/models/etl/build_table.rb
  app/services/etl/builder.rb
  app/services/etl/syncer.rb
  db/etl/migrate/20200212205344_add_etl_build_tables.rb
  db/etl/schema.rb
  spec/factories/appeal.rb
  spec/services/etl/appeal_syncer_spec.rb
  spec/services/etl/attorney_case_review_syncer_spec.rb
  spec/services/etl/builder_spec.rb
  spec/services/etl/decision_issue_syncer_spec.rb
  spec/services/etl/organization_syncer_spec.rb
  spec/services/etl/organizations_user_syncer_spec.rb
  spec/services/etl/person_syncer_spec.rb
  spec/services/etl/syncer_spec.rb
  spec/services/etl/task_syncer_spec.rb
  spec/services/etl/user_syncer_spec.rb
Labels: Ready-to-Merge, delta

#13442 Add data integrity check for open task with closed parent
  app/services/open_tasks_with_closed_at_checker.rb
  spec/services/open_tasks_with_closed_at_checker_spec.rb
Labels: Ready-to-Merge

#13349 Handle difference of opinion dispositions
  app/models/decision_issue.rb
  app/models/end_product.rb
  app/models/request_issue.rb
  app/workflows/end_product_code_selector.rb
  client/constants/END_PRODUCT_CODES.json
  spec/models/request_issue_spec.rb
  spec/workflows/end_product_code_selector_spec.rb
Labels: Ready-to-Merge, foxtrot

#13443 Updates to the Caseflow Mac setup directions & scripts
  README.md
  scripts/dev_env_setup_step1.sh
  scripts/dev_env_setup_step2.sh
Labels: Ready-to-Merge

#13446 Handle VBMS requirement for newline-free contention text
  app/models/contention.rb
  spec/models/contention_spec.rb
Labels: AMO, Bug, Ready-to-Merge, VBMS, foxtrot

#13449 Keep completed AttorneyTasks with reassigned JudgeDecisionReviewTasks
  app/models/task.rb
  app/models/tasks/attorney_task.rb
  spec/models/task_spec.rb
Labels: Ready-to-Merge

#13456 Demo - Startup.sh needs a bit of love
  docker-bin/startup.sh
Labels: Ready-to-Merge

#13382 Regional Office adjustments for Hearings
  client/constants/REGIONAL_OFFICE_INFORMATION.json
  public/ROAssignmentTemplate.xlsx
  spec/controllers/hearings/schedule_periods_controller_spec.rb
  spec/controllers/regional_offices_controller_spec.rb
  spec/feature/hearings/build_schedule/build_hearsched_spec.rb
  spec/models/hearing_day_spec.rb
  spec/models/hearings/allocation_spec.rb
  spec/models/hearings/ro_non_availability_spec.rb
  spec/support/allocationDuplicateRo.xlsx
  spec/support/allocationTemplateNotFollowed.xlsx
  spec/support/allocationWrongDataType.xlsx
  spec/support/blankRoSpreadsheet.xlsx
  spec/support/coDuplicateDates.xlsx
  spec/support/coOutOfRange.xlsx
  spec/support/coWrongDataType.xlsx
  spec/support/roDuplicateDates.xlsx
  spec/support/roNotInSystem.xlsx
  spec/support/roNotListed.xlsx
  spec/support/roOutOfRange.xlsx
  spec/support/roTemplateNotFollowed.xlsx
  spec/support/roWrongDataType.xlsx
  spec/support/validRoSpreadsheet.xlsx
Labels: Ready-to-Merge

#13452 Add Caseflow::Error::MissingBusinessLine and test
  app/models/appeal.rb
  lib/caseflow/error.rb
  spec/models/appeal_spec.rb
Labels: Ready-to-Merge

#13457 OMO request is no longer supported
  .reek.yml
  app/models/legacy_tasks/judge_legacy_decision_review_task.rb
  spec/feature/queue/judge_checkout_flow_spec.rb
Labels: Ready-to-Merge

#13450 Tree renderer: don't cache root-level tasks
  app/models/concerns/task_tree_render_module.rb
  spec/models/concerns/task_tree_render_module_spec.rb
Labels: Ready-to-Merge

#13204 Realistic name seeds
  db/seeds.rb
Labels: Ready-to-Merge

#13447 Send job stats to DataDog
  app/jobs/warm_bgs_caches_job.rb
Labels: Ready-to-Merge

#13458 Uncaught js XHR error
  client/app/queue/QueueTable.jsx
  client/app/queue/components/HearingBadge.jsx
  client/app/reader/ReaderLoadingScreen.jsx
Labels: Ready-to-Merge

#13472 Report a fiscal year at a time
  app/services/metrics/date_range.rb
  app/services/metrics/hearings_show_rate.rb
  spec/services/metrics/date_range_spec.rb
Labels: Ready-to-Merge, delta

#13487 ETL timeout for slow query
  app/queries/appeals_updated_since_query.rb
  app/services/etl/syncer.rb
Labels: Ready-to-Merge, delta

#13402 MTV | Attorney Checkout | Add Decisions View
  app/models/decision_issue.rb
  client/COPY.json
  client/app/components/Modal.jsx
  client/app/queue/components/DecisionIssues.jsx
  client/app/queue/components/SelectIssueDispositionDropdown.jsx
  client/app/queue/mtv/AddDecisionIssuesView.jsx
  client/app/queue/mtv/AddEditDecisionIssueModal.jsx
  client/app/queue/mtv/AddEditDecisionIssueModal.module.scss
  client/app/queue/mtv/MotionToVacateFlowContainer.jsx
  client/app/queue/mtv/ReviewVacatedDecisionIssuesView.jsx
  client/app/queue/mtv/mtvCheckoutSteps.js
  client/app/queue/utils.js
  spec/feature/queue/motion_to_vacate_spec.rb
Labels: Ready-to-Merge, foxtrot

#13502 Accessibility | Show "Claim details" as button instead of tab
  client/package.json
  client/yarn.lock
Labels: Ready-to-Merge, accessibility, foxtrot

#13501 Find VACOLS cases that no longer exist
  app/services/legacy_appeals_with_no_vacols_case.rb
  spec/services/legacy_appeals_with_no_vacols_case_spec.rb
Labels: Ready-to-Merge

#13440 Implement "Submit" Step of MTV Attorney Checkout
  client/app/queue/SubmitDecisionView.jsx
  client/app/queue/mtv/AddDecisionIssueModal.module.scss
  client/app/queue/mtv/MotionToVacateFlowContainer.jsx
  client/app/queue/mtv/SubmitVacatedDecisionsView.jsx
  spec/feature/queue/motion_to_vacate_spec.rb
Labels: Ready-to-Merge, foxtrot

#13506 Skip some XHR errors as not worth reporting
  client/app/queue/components/HearingBadge.jsx
  client/app/reader/DocumentListHeader.jsx
Labels: Ready-to-Merge

#13453 MTV | Added Progress Bar to Attorney Checkout Flow
  client/app/queue/mtv/MotionToVacateCheckoutProgressBar.jsx
  client/app/queue/mtv/MotionToVacateFlowContainer.jsx
  client/app/queue/mtv/mtvCheckoutSteps.js
  spec/feature/queue/motion_to_vacate_spec.rb
Labels: Ready-to-Merge, foxtrot

#13509 Success Alert upon Completion of JudgeAddressMotionToVacate
  app/controllers/post_decision_motions_controller.rb
  client/COPY.json
  client/app/queue/mtv/AddressMotionToVacateView.jsx
  client/app/queue/mtv/mtvActions.js
  client/app/queue/mtv/mtvMessages.js
  spec/controllers/post_decision_motions_controller_spec.rb
  spec/feature/queue/motion_to_vacate_spec.rb
Labels: Ready-to-Merge, foxtrot

#13513 Add Pulac Cerullo reminder for "vacate" streams
  app/models/tasks/attorney_task.rb
  client/app/queue/CaseDetailsView.jsx
  client/app/queue/pulacCerullo/index.js
  spec/feature/queue/motion_to_vacate_spec.rb
Labels: Ready-to-Merge, foxtrot

#13510 LegacyAppeal.location_history
  app/models/legacy_appeal.rb
  app/models/vacols/priorloc.rb
  app/queries/vacols_location_batch_updater.rb
  app/services/redistributed_case.rb
  spec/models/legacy_appeal_spec.rb
Labels: Ready-to-Merge

#13508 Fix Makefile.example for Linux
  Makefile.example
  README.md
Labels: Ready-to-Merge

#13515 Add updating documentation to GH templates
  .github/ISSUE_TEMPLATE/engineering-task.md
  .github/ISSUE_TEMPLATE/story.md
Labels: Ready-to-Merge

#13517 Make Command: Run Frontend and Backend Independently
  Makefile.example
Labels: Ready-to-Merge

#13411 Fix undefined appellant address
  app/mappers/address_mapper.rb
  app/models/legacy_appeal.rb
  client/app/queue/components/AssignHearingModal.jsx
  spec/controllers/hearings_controller_spec.rb
  spec/factories/legacy_appeal.rb
  spec/feature/hearings/daily_docket/build_hearsched_spec.rb
  spec/models/legacy_appeal_spec.rb
  spec/models/serializers/work_queue/legacy_appeal_serializer_spec.rb
  spec/models/tasks/hearing_admin_action_verify_address_task_spec.rb
Labels: Ready-to-Merge

#13516 Optimize UpdateCachedAppealsAttributesJob
  app/jobs/update_cached_appeals_attributes_job.rb
  app/jobs/warm_bgs_caches_job.rb
  app/repositories/appeal_repository.rb
  app/services/bgs_power_of_attorney.rb
  spec/controllers/tasks_controller_spec.rb
Labels: Ready-to-Merge

#13519 Bat Team | Allow nil for delegation to veteran in Legacy Appeal
  app/models/legacy_appeal.rb
Labels: Ready-to-Merge

#13471 Motion to Vacate | Create "De Novo" appeal stream
  app/models/decision_issue.rb
  app/models/post_decision_motion.rb
  app/models/tasks/bva_dispatch_task.rb
  spec/factories/post_decision_motions.rb
  spec/models/appeal_spec.rb
  spec/models/post_decision_motion_spec.rb
  spec/models/tasks/bva_dispatch_task_spec.rb
Labels: Ready-to-Merge

#13530 Use the presence of a decision doc id to determine if a case has already gone to an attorney
  app/models/queues/legacy_work_queue.rb
  app/models/user.rb
  spec/models/queues/legacy_work_queue_spec.rb
Labels: Ready-to-Merge

#13534 fix flakey filtered tasks spec
  spec/models/task_filter_spec.rb
Labels: Flaky test, Ready-to-Merge

#13528 Reader JS exceptions should be quieter
  client/app/reader/DocumentListHeader.jsx
Labels: Ready-to-Merge

#13546 Fix ArgumentError in LegacyAppeal#address
  app/mappers/address_mapper.rb
  app/models/legacy_appeal.rb
  app/services/bgs_address_service.rb
  app/services/external_api/bgs_address_finder.rb
  spec/factories/legacy_appeal.rb
  spec/mappers/address_mapper_spec.rb
  spec/models/legacy_appeal_spec.rb
Labels: Ready-to-Merge

#13531 Integrate rspec retry
  Gemfile
  Gemfile.lock
  spec/spec_helper.rb
Labels: Ready-to-Merge

#13550 Fix ETL timing bug
  .reek.yml
  app/queries/appeals_updated_since_query.rb
  app/services/etl/builder.rb
  app/services/etl/syncer.rb
  spec/jobs/etl_builder_job_spec.rb
  spec/services/etl/appeal_syncer_spec.rb
  spec/services/etl/attorney_case_review_syncer_spec.rb
  spec/services/etl/builder_spec.rb
  spec/services/etl/decision_issue_syncer_spec.rb
  spec/services/etl/organization_syncer_spec.rb
  spec/services/etl/organizations_user_syncer_spec.rb
  spec/services/etl/person_syncer_spec.rb
  spec/services/etl/syncer_spec.rb
  spec/services/etl/task_syncer_spec.rb
  spec/services/etl/user_syncer_spec.rb
Labels: Ready-to-Merge, delta

#13529 Set closed_at inside update_all when we close tasks
  app/models/tasks/assign_hearing_disposition_task.rb
  app/models/tasks/schedule_hearing_task.rb
  spec/models/tasks/assign_hearing_disposition_task_spec.rb
  spec/models/tasks/schedule_hearing_task_spec.rb
Labels: Ready-to-Merge

#13554 Explicitly prefer BGS POA on cached appeals attributes
  app/jobs/update_cached_appeals_attributes_job.rb
  app/models/power_of_attorney.rb
Labels: Ready-to-Merge

#13549 Fallback to appellant address in VACOLS for LegacyAppeal
  .reek.yml
  app/mappers/address_mapper.rb
  app/models/legacy_appeal.rb
Labels: Ready-to-Merge

#13551 Motion to Vacate | Create "De Novo" Task
  app/models/tasks/bva_dispatch_task.rb
  app/workflows/ama_appeal_dispatch.rb
  app/workflows/de_novo_stream_creator.rb
  spec/models/tasks/bva_dispatch_task_spec.rb
Labels: Ready-to-Merge

#13555 Catch XHR errors for /histogram
  client/app/util/Metrics.js
Labels: Ready-to-Merge
