Repository department-of-veterans-affairs/caseflow, pull requests merged in 2020-10, with the labels that each got.

#15274 Increase Parallelism in CircleCI and use Shared Workspace
  .circleci/config.yml
  Gemfile
  Gemfile.lock
  config/environments/test.rb
Labels: Ready-to-Merge, Type: Tech-Improvement

#15359 in AppealAvailableHearingLocations.suggested_hearing_location, use reject to skip nil distances
  app/models/concerns/appeal_available_hearing_locations.rb
Labels: Ready-to-Merge, Team: Tango 💃

#15302 Added `DocketChange` Model & Updated Schema
  app/models/docket_change.rb
  db/migrate/20200921191403_create_docket_changes.rb
  db/schema.rb
  docs/schema/caseflow.csv
  spec/factories/docket_change.rb
  spec/models/docket_change_spec.rb
Labels: Ready-to-Merge, Team: Foxtrot 🦊

#15358 Edit EP Claim Labels | Add "type" to request issue
  app/models/nonrating_request_issue.rb
  app/models/rating_request_issue.rb
Labels: Ready-to-Merge

#15364 Use Regional Office Label instead of key in success alert
  client/COPY.json
  client/app/hearings/components/HearingTypeConversion.jsx
  client/test/app/hearings/components/__snapshots__/HearingTypeConversionForm.test.js.snap
Labels: Ready-to-Merge, Team: Tango 💃

#15373 Show missing email alert if email is null
  client/app/hearings/components/VirtualHearings/AppellantSection.jsx
  client/test/app/hearings/components/VirtualHearings/AppellantSection.test.js
  client/test/app/hearings/components/VirtualHearings/__snapshots__/AppellantSection.test.js.snap
Labels: Ready-to-Merge, Team: Tango 💃

#15347 Update code comments for Task classes
  app/models/tasks/assign_hearing_disposition_task.rb
  app/models/tasks/attorney_dispatch_return_task.rb
  app/models/tasks/attorney_quality_review_task.rb
  app/models/tasks/distribution_task.rb
  app/models/tasks/evidence_submission_window_task.rb
  app/models/tasks/hearing_task.rb
  app/models/tasks/informal_hearing_presentation_task.rb
  app/models/tasks/judge_assign_task.rb
  app/models/tasks/judge_decision_review_task.rb
  app/models/tasks/mail_task.rb
  app/models/tasks/root_task.rb
  app/models/tasks/schedule_hearing_task.rb
  app/models/tasks/special_case_movement_task.rb
  app/models/tasks/track_veteran_task.rb
  app/models/tasks/translation_task.rb
Labels: Product: caseflow-queue, Ready-to-Merge, Team: Echo 🐬

#15275 Pass Sentry event ID to frontend for displaying Intake errors
  app/controllers/intakes_controller.rb
  client/app/intake/actions/intake.js
  client/app/intake/pages/addIssues.jsx
  client/app/intake/pages/appeal/review.jsx
  client/app/intake/pages/higherLevelReview/review.jsx
  client/app/intake/pages/supplementalClaim/review.jsx
  client/app/intake/reducers/appeal.js
  client/app/intake/reducers/higherLevelReview.js
  client/app/intake/reducers/rampElection.js
  client/app/intake/reducers/rampRefiling.js
  client/app/intake/reducers/supplementalClaim.js
  client/app/intake/util/index.js
  spec/controllers/intakes_controller_spec.rb
  spec/feature/intake/intake_spec.rb
Labels: Ready-to-Merge

#15341 Stub Routes for Docket Change Functionality
  app/models/tasks/docket_switch_mail_task.rb
  client/app/components/PageRoute.jsx
  client/app/queue/QueueApp.jsx
  client/app/queue/docketChange/docketChangeRoutes.js
  client/constants/TASK_ACTIONS.json
  client/package.json
  client/yarn.lock
  spec/models/tasks/docket_switch_mail_task_spec.rb
Labels: Ready-to-Merge, Team: Foxtrot 🦊

#15351 CAVC Remand model & Controller
  app/controllers/cavc_remands_controller.rb
  app/models/cavc_remand.rb
  client/constants/CAVC_DECISION_TYPES.json
  client/constants/CAVC_JUDGE_FULL_NAMES.json
  client/constants/CAVC_REMAND_SUBTYPES.json
  config/routes.rb
  db/migrate/20200923192959_create_cavc_remand.rb
  db/migrate/20200923200721_add_index_to_cavc_remand.rb
  db/schema.rb
  docs/schema/caseflow.csv
  lib/caseflow/error.rb
  spec/controllers/cavc_remands_controller_spec.rb
  spec/models/cavc_remand_spec.rb
Labels: Ready-to-Merge

#15380 Catch nil veteran when sending email
  app/jobs/virtual_hearings/send_email.rb
Labels: Ready-to-Merge, Team: Tango 💃

#15377 Adding filtering for hearing type column on schedule veterans page
  app/models/queue_tabs/assign_hearing_tab.rb
  app/models/task_filter.rb
  client/app/hearings/components/assignHearings/AssignHearingsTable.jsx
  client/constants/QUEUE_CONFIG.json
  spec/feature/hearings/assign_hearings_table_spec.rb
Labels: Ready-to-Merge, Team: Tango 💃

#15391 recover from RecordNotUnique race condition when creating new legacy appeal
  app/models/legacy_appeal.rb
Labels: Eng: Backend Work Group, Ready-to-Merge, Team: Tango 💃

#15381 Assigned by on JudgeDecisionReviewTask shows attorney from AttorneyTask
  app/models/attorney_case_review.rb
  spec/models/attorney_case_review_spec.rb
Labels: Ready-to-Merge

#15320 Rename column formally_travel to former_travel
  app/controllers/hearings/schedule_hearing_tasks_controller.rb
  app/jobs/update_cached_appeals_attributes_job.rb
  app/models/queue_tabs/assign_hearing_tab.rb
  app/models/serializers/work_queue/task_column_serializer.rb
  app/models/task_filter.rb
  client/app/hearings/components/HearingTime.jsx
  db/migrate/20200925163243_rename_formally_travel_to_former_travel.rb
  db/schema.rb
  docs/schema/caseflow.csv
  spec/feature/hearings/assign_hearings_table_spec.rb
  spec/jobs/update_cached_appeals_attributes_job_spec.rb
Labels: Ready-to-Merge, Team: Tango 💃

#15368 Created DocketSwitchRulingTask
  app/models/tasks/docket_switch_mail_task.rb
  app/models/tasks/docket_switch_ruling_task.rb
  client/COPY.json
  client/app/queue/docketChange/docketChangeRoutes.js
  client/constants/TASK_ACTIONS.json
  spec/models/tasks/docket_switch_mail_task_spec.rb
Labels: Ready-to-Merge, Team: Foxtrot 🦊

#15403 Remove diagnostic code validation
  app/models/decision_issue.rb
  spec/models/decision_issue_spec.rb
Labels: Ready-to-Merge

#15383 Edit EP Claim Labels | Add End Product Update model
  app/models/end_product_establishment.rb
  app/models/end_product_update.rb
  db/migrate/20201005190456_create_end_product_update.rb
  db/schema.rb
  docs/schema/caseflow.csv
Labels: Ready-to-Merge

#15401 Disable unlisted claimant UI and update copy
  client/COPY.json
  client/app/intake/components/AddClaimantModal.jsx
  client/test/app/intake/components/AddClaimantModal.test.js
  client/test/app/intake/components/__snapshots__/AddClaimantModal.test.js.snap
  spec/feature/intake/review_page_spec.rb
Labels: Ready-to-Merge

#15414 Change VACOLS location when creating a ChangeHearingRequestTypeTask
  app/services/hearing_task_tree_initializer.rb
  spec/services/hearing_task_tree_initializer_spec.rb
Labels: Ready-to-Merge, Team: Tango 💃

#15396 Fix AOD status caching of appeals
  app/jobs/update_cached_appeals_attributes_job.rb
  spec/jobs/update_cached_appeals_attributes_job_spec.rb
Labels: Feature: generic-queue, Priority: Medium, Product: caseflow-queue, Stakeholder: BVA, Team: Echo 🐬, Type: Bug

#15418 Do not add CO as a location to geomatch from if veteran lives in VA or MD
  app/services/va_dot_gov_address_validator.rb
  app/services/va_dot_gov_address_validator/validations.rb
  spec/services/va_dot_gov_address_validator_spec.rb
Labels: Ready-to-Merge, Team: Tango 💃

#15407 v3 API - Refactor Contestable Issues Controller
  app/controllers/api/v3/decision_reviews/base_contestable_issues_controller.rb
  app/controllers/api/v3/decision_reviews/higher_level_reviews/contestable_issues_controller.rb
Labels: Integration: Lighthouse, Ready-to-Merge

#15395 Display completed ChangeHearingRequestTypeTask info on timeline
  app/jobs/fetch_hearing_locations_for_veterans_job.rb
  app/jobs/start_certification_job.rb
  app/jobs/update_cached_appeals_attributes_job.rb
  app/models/appeal.rb
  app/models/appeal_series.rb
  app/models/legacy_appeal.rb
  app/models/serializers/work_queue/appeal_serializer.rb
  app/models/serializers/work_queue/legacy_appeal_serializer.rb
  app/models/serializers/work_queue/task_column_serializer.rb
  app/models/serializers/work_queue/task_serializer.rb
  app/models/tasks/change_hearing_request_type_task.rb
  app/services/va_dot_gov_address_validator/validations.rb
  app/workflows/tasks_for_appeal.rb
  client/COPY.json
  client/app/queue/CaseTimeline.jsx
  client/app/queue/CaseTimeline.stories.js
  client/app/queue/components/TaskRows.jsx
  client/app/queue/utils.js
  client/test/data/hearings.js
  client/test/data/tasks.js
  client/test/karma/queue/ColocatedTaskListView-test.js
  spec/feature/hearings/convert_travel_board_hearing/edit_hearsched_spec.rb
  spec/feature/queue/case_details_spec.rb
  spec/jobs/update_cached_appeals_attributes_job_spec.rb
  spec/models/appeal_spec.rb
  spec/models/legacy_appeal_spec.rb
Labels: Ready-to-Merge, Team: Tango 💃

#15371 Implement "Send Docket Switch to Judge" Form
  client/COPY.json
  client/app/components/RadioField.jsx
  client/app/queue/QueueApp.jsx
  client/app/queue/docketSwitch/constants.js
  client/app/queue/docketSwitch/docketSwitchRoutes.js
  client/app/queue/docketSwitch/recommendDocketSwitch/RecommendDocketSwitchContainer.jsx
  client/app/queue/docketSwitch/recommendDocketSwitch/RecommendDocketSwitchForm.jsx
  client/app/queue/docketSwitch/recommendDocketSwitch/RecommendDocketSwitchForm.stories.js
  client/constants/TASK_ACTIONS.json
  client/package.json
  client/test/app/queue/docketChange/RecommendDocketSwitchForm.test.js
  client/test/app/queue/docketChange/__snapshots__/RecommendDocketSwitchForm.test.js.snap
  client/yarn.lock
  spec/feature/queue/docket_change_spec.rb
Labels: Ready-to-Merge

#15374 Added logic to prevent adding tasks to a dispatched appeal
  app/workflows/tasks_for_appeal.rb
  spec/feature/hearings/convert_travel_board_hearing/edit_hearsched_spec.rb
Labels: Ready-to-Merge, Team: Tango 💃

#15431 Fix Sentry ID display bug for SC establishment failure
  client/app/intake/reducers/supplementalClaim.js
Labels: Product: caseflow-intake, Ready-to-Merge, Source: Bat Team, Source: Sentry Alert, Type: Bug

#15423 Edit EP Claim Labels | Show EP data on search page
  app/models/end_product_establishment.rb
  client/app/queue/OtherReviewsTable.jsx
  spec/feature/queue/search_spec.rb
  spec/models/end_product_establishment_spec.rb
Labels: Ready-to-Merge, Team: Foxtrot 🦊

#15421 v3 API - Add Appeals Contestable Issues Controller
  app/controllers/api/v3/decision_reviews/appeals/contestable_issues_controller.rb
  config/routes.rb
  spec/requests/api/v3/decision_reviews/appeals/contestable_issues_controller_spec.rb
  spec/requests/api/v3/decision_reviews/higher_level_reviews/contestable_issues_controller_spec.rb
  spec/support/shared_context/requests/api/v3/decision_reviews/shared_context_contestable_issues.rb
  spec/support/shared_examples/requests/api/v3/decision_reviews/shared_examples_contestable_issues.rb
Labels: Integration: Lighthouse

#15433 Add `json_schemer` Gem
  Gemfile
  Gemfile.lock
Labels: Integration: Lighthouse, Ready-to-Merge

#15436 Update VACOLS location when ChangeHearingRequestTypeTask is completed
  app/models/tasks/change_hearing_request_type_task.rb
  app/services/hearing_task_tree_initializer.rb
  spec/controllers/tasks_controller_spec.rb
  spec/services/hearing_task_tree_initializer_spec.rb
Labels: Ready-to-Merge, Team: Tango 💃

#15443 Add CAVC lit support team
  app/models/organizations/cavc_litigation_support.rb
  spec/models/organizations/cavc_litigation_support_spec.rb
Labels: Eng: Beginner Friendly, Priority: Medium, Product: caseflow-queue, Ready-to-Merge, Stakeholder: BVA, Team: Echo 🐬, Type: New Development

#15453 Do not fail age_of_oldest_priority_appeal when there are no ready priority appeals
  app/models/docket.rb
  spec/models/docket_spec.rb
Labels: Feature: auto-case-distribution, Priority: High, Product: caseflow-queue, Ready-to-Merge, Stakeholder: BVA, Team: Echo 🐬, Type: Bug, User: Judge

#15445 Changes to the judge team management page should not rely on a feature toggle
  app/controllers/organizations/users_controller.rb
Labels: Feature: generic-queue, Priority: Low, Product: caseflow-queue, Ready-to-Merge, Stakeholder: BVA, Team: Echo 🐬, Type: Bug, User: Judge

#15444 Shalliburton/15439 webpack aliasing
  client/.eslintrc.js
  client/package.json
  client/webpack.config.js
  client/yarn.lock
Labels: Ready-to-Merge

#15455 Removes not null constraint on CavcRemand updated_by
  app/models/cavc_remand.rb
  db/migrate/20201020135542_cavc_remand_updated_by_nullable.rb
  db/schema.rb
  docs/schema/caseflow.csv
Labels: Ready-to-Merge

#15454 format start and end dates before sending to bgs
  app/services/external_api/bgs_service.rb
  spec/services/external_api/bgs_service_spec.rb
Labels: Product: caseflow-intake, Ready-to-Merge, Source: Bat Team, Type: Bug

#15467 don't use an existing hearing task as the parent of a new change hearing request type task
  app/services/hearing_task_tree_initializer.rb
  spec/services/hearing_task_tree_initializer_spec.rb
Labels: Ready-to-Merge, Team: Tango 💃

#15476 Handle unknown EPE codes
  app/models/end_product_establishment.rb
  spec/models/end_product_establishment_spec.rb
Labels: Ready-to-Merge, Source: Sentry Alert, Type: Bug

#15477 Removes duplicate ep_claim_types
  client/constants/EP_CLAIM_TYPES.json
Labels: Ready-to-Merge

#15483 Add Support for Webpack Aliases to Storybook Config
  client/.storybook/main.js
Labels: Ready-to-Merge, Team: Foxtrot 🦊, Type: Tech-Improvement

#14867 Added support for Redux Toolkit
  client/app/components/ReduxBase.jsx
  client/package.json
  client/yarn.lock
Labels: Eng: Frontend Work Group, Ready-to-Merge

#15485 when retrying fetching the rating profile, return an empty object if a BGS ShareError or a Rating NilRatingProfileListError is raised
  app/models/promulgated_rating.rb
  spec/models/promulgated_rating_spec.rb
Labels: Ready-to-Merge, Source: Bat Team, Team: Foxtrot 🦊, Type: Bug

#15461 Docket Switch | Create Docket switch decision tasks
  app/controllers/tasks_controller.rb
  app/models/tasks/docket_switch/docket_switch_denied_task.rb
  app/models/tasks/docket_switch/docket_switch_granted_task.rb
  app/models/tasks/docket_switch/docket_switch_mail_task.rb
  app/models/tasks/docket_switch/docket_switch_ruling_task.rb
  app/repositories/task_action_repository.rb
  client/COPY.json
  client/constants/TASK_ACTIONS.json
  spec/models/tasks/docket_switch_denied_task_spec.rb
  spec/models/tasks/docket_switch_granted_task_spec.rb
Labels: Ready-to-Merge

#15452 Lookup contestable issues by file number
  app/controllers/api/docs/v3/decision_reviews.yaml
  app/controllers/api/v3/decision_reviews/base_contestable_issues_controller.rb
  spec/support/shared_context/requests/api/v3/decision_reviews/shared_context_contestable_issues.rb
  spec/support/shared_examples/requests/api/v3/decision_reviews/shared_examples_contestable_issues.rb
Labels: Integration: Lighthouse, Ready-to-Merge

#15488 Implement new api/v3 feature toggle checks
  app/controllers/api/v3/base_controller.rb
  app/controllers/api/v3/decision_reviews/appeals/contestable_issues_controller.rb
  app/controllers/api/v3/decision_reviews/appeals_controller.rb
  app/controllers/api/v3/decision_reviews/higher_level_reviews/contestable_issues_controller.rb
  app/controllers/api/v3/decision_reviews/higher_level_reviews_controller.rb
  app/controllers/concerns/api_v3_feature_toggle_concern.rb
  spec/controllers/api/v3/base_controller_spec.rb
  spec/requests/api/v3/decision_reviews/appeals/contestable_issues_controller_spec.rb
  spec/requests/api/v3/decision_reviews/higher_level_reviews/contestable_issues_controller_spec.rb
  spec/requests/api/v3/decision_reviews/higher_level_reviews_controller_spec.rb
Labels: Integration: Lighthouse

#15478 Fewer queries when caching hearing request types
  app/jobs/update_cached_appeals_attributes_job.rb
  app/models/legacy_appeal.rb
Labels: Eng: Performance, Ready-to-Merge

#15480 Add Support for Remand Reasons to MTV Checkout
  client/app/queue/components/remandReasons/IssueRemandReasonCheckbox.jsx
  client/app/queue/components/remandReasons/IssueRemandReasonCheckbox.stories.js
  client/app/queue/components/remandReasons/IssueRemandReasonsForm.jsx
  client/app/queue/components/remandReasons/IssueRemandReasonsForm.stories.js
  client/app/queue/components/remandReasons/constants.js
  client/app/queue/mtv/checkout/AddDecisionIssuesView.jsx
  client/app/queue/mtv/checkout/AddRemandReasonsView.jsx
  client/app/queue/mtv/checkout/MotionToVacateFlowContainer.jsx
  client/test/app/queue/components/remandReasons/IssueRemandReasonCheckbox.test.js
  client/test/app/queue/components/remandReasons/IssueRemandReasonsForm.test.js
  client/test/app/queue/components/remandReasons/__snapshots__/IssueRemandReasonCheckbox.test.js.snap
  client/test/app/queue/components/remandReasons/__snapshots__/IssueRemandReasonsForm.test.js.snap
  spec/feature/queue/motion_to_vacate_spec.rb
Labels: Ready-to-Merge, Team: Foxtrot 🦊

#15469 Create Court Remand (CAVC) Appeal Stream on CavcRemandForm Completion
  app/models/appeal.rb
  app/models/cavc_remand.rb
  app/models/tasks/cavc_task.rb
  app/workflows/initial_tasks_factory.rb
  db/seeds/tasks.rb
  db/seeds/users.rb
  spec/controllers/idt/api/appeals_controller_spec.rb
  spec/factories/appeal.rb
  spec/factories/cavc_remand.rb
  spec/models/appeal_spec.rb
  spec/models/cavc_remand_spec.rb
  spec/seeds/users_spec.rb
  spec/workflows/initial_tasks_factory_spec.rb
Labels: Ready-to-Merge

#15482 Allow UpdateCachedAppealsAttributesJob to complete and send warnings
  app/jobs/update_cached_appeals_attributes_job.rb
  spec/jobs/update_cached_appeals_attributes_job_spec.rb
Labels: Integration: BGS, Priority: Medium, Product: caseflow-queue, Ready-to-Merge, Source: Sentry Alert, Team: Echo 🐬

#15493 Only send AttorneyTasks back to judge assign
  app/models/tasks/attorney_task.rb
  spec/factories/task.rb
  spec/models/tasks/attorney_quality_review_task_spec.rb
  spec/models/tasks/attorney_task_spec.rb
Labels: Ready-to-Merge

#15489 Fix Non-Comp Review Button Styling
  client/app/nonComp/pages/ReviewPage.jsx
Labels: Eng: Beginner Friendly, Priority: Low, Team: Foxtrot 🦊, Type: Bug

#15490 Handle updating correction type in EndProductUpdate
  app/models/end_product_update.rb
  spec/factories/end_product_update.rb
  spec/models/end_product_update_spec.rb
Labels: Ready-to-Merge

#15502 Cancel virtual hearing when hearing is postponed or cancelled
  app/models/tasks/assign_hearing_disposition_task.rb
  spec/models/tasks/assign_hearing_disposition_task_spec.rb
Labels: Ready-to-Merge, Team: Tango 💃

#15512 Revert "Cancel virtual hearing when hearing is postponed or cancelled"
  app/models/tasks/assign_hearing_disposition_task.rb
  spec/models/tasks/assign_hearing_disposition_task_spec.rb
Labels: Ready-to-Merge

#15513 Add Acceptance Criteria to PR template to document database schema and data
  PULL_REQUEST_TEMPLATE.md
Labels: Eng: Data Work Group, Priority: Low, Ready-to-Merge, Type: Documentation

#15487 Create job to cache travel board appeals immediately
  .reek.yml
  app/jobs/fetch_hearing_locations_for_veterans_job.rb
  app/jobs/hearings/geomatch_and_cache_appeal_job.rb
  app/jobs/update_cached_appeals_attributes_job.rb
  app/models/concerns/run_asyncable.rb
  app/models/hearings/forms/base_hearing_update_form.rb
  app/models/tasks/change_hearing_request_type_task.rb
  app/services/cached_appeal_service.rb
  app/services/geomatch_service.rb
  spec/controllers/tasks_controller_spec.rb
  spec/jobs/fetch_hearing_locations_for_veterans_job_spec.rb
  spec/jobs/hearings/geomatch_and_cache_appeal_job_spec.rb
  spec/services/cached_appeal_service_spec.rb
  spec/services/geomatch_service_spec.rb
  spec/support/geomatch_helper.rb
Labels: Ready-to-Merge, Team: Tango 💃

#15504 Handle race conditions when concurrently fetching POA by PID
  app/models/bgs_power_of_attorney.rb
  spec/models/bgs_power_of_attorney_spec.rb
Labels: Ready-to-Merge, Source: Bat Team, Source: Sentry Alert, Type: Bug

#15518 Delete conference when hearing is postponed or cancelled
  app/jobs/virtual_hearings/delete_conferences_job.rb
  app/models/concerns/has_virtual_hearing.rb
  app/models/concerns/hearing_concern.rb
  app/models/hearing.rb
  app/models/hearings/virtual_hearing.rb
  app/models/legacy_hearing.rb
  app/models/tasks/assign_hearing_disposition_task.rb
  app/models/vacols/case_hearing.rb
  app/repositories/virtual_hearing_repository.rb
  spec/jobs/virtual_hearings/delete_conferences_job_spec.rb
  spec/models/hearings/virtual_hearing_spec.rb
  spec/models/tasks/assign_hearing_disposition_task_spec.rb
  spec/repositories/virtual_hearing_repository_spec.rb
Labels: Ready-to-Merge, Team: Tango 💃

#15070 Enabled All Karma Tests
  client/test/karma/queue/ColocatedTaskListView-test.js
Labels: Ready-to-Merge, Type: Bug, Type: Tech-Improvement

#15432 Completed Submit Handler for Recommend Docket Switch View
  app/controllers/tasks_controller.rb
  app/repositories/task_action_repository.rb
  client/app/queue/docketSwitch/recommendDocketSwitch/RecommendDocketSwitchContainer.jsx
  client/app/queue/docketSwitch/recommendDocketSwitch/recommendDocketSwitchSlice.js
  client/app/util/ReduxUtil.js
  client/constants/TASK_ACTIONS.json
  client/test/app/queue/docketChange/RecommendDocketSwitchContainer.test.js
  client/test/app/queue/docketChange/__snapshots__/RecommendDocketSwitchContainer.test.js.snap
  spec/factories/task.rb
  spec/feature/queue/docket_change_spec.rb
  spec/models/tasks/docket_switch_ruling_task_spec.rb
Labels: Ready-to-Merge, Team: Foxtrot 🦊

#15532 Feature test click_dropdown performance
  spec/support/feature_helper.rb
Labels: Eng: Performance, Type: Tech-Improvement

#15492 Api v3 hlr json schema
  app/controllers/api/docs/v3/decision_reviews.yaml
  app/controllers/api/v3/decision_reviews/higher_level_reviews_controller.rb
  app/services/api/v3/decision_reviews/contestable_issue_params.rb
  app/services/api/v3/decision_reviews/errors/schemer_to_json_api_missing_attribute.rb
  app/services/api/v3/decision_reviews/hash_path_validator.rb
  app/services/api/v3/decision_reviews/higher_level_review_intake_params.rb
  app/services/api/v3/decision_reviews/intake_error.rb
  app/services/api/v3/decision_reviews/schemas/form_200996_request_higher_level_review_schema.json
  spec/requests/api/v3/decision_reviews/higher_level_reviews_controller_spec.rb
  spec/services/api/v3/decision_reviews/contestable_issue_params_spec.rb
  spec/services/api/v3/decision_reviews/hash_path_validator_spec.rb
  spec/services/api/v3/decision_reviews/higher_level_review_intake_params_spec.rb
  spec/services/api/v3/decision_reviews/higher_level_review_intake_processor_spec.rb
  spec/services/api/v3/decision_reviews/intake_processor_spec.rb
Labels: Integration: Lighthouse, Ready-to-Merge
