Repository department-of-veterans-affairs/caseflow, pull requests merged in 2020-12, with the labels that each got.

#15638 Edit NOD date save integration
  app/models/appeal.rb
  client/COPY.json
  client/app/queue/QueueActions.js
  client/app/queue/components/EditNodDateModal.jsx
  client/app/queue/components/TaskRows.jsx
  client/test/app/queue/components/__snapshots__/EditNodDateModal.test.js.snap
  spec/models/appeal_spec.rb
Labels: Feature: Edit NOD, Ready-to-Merge, Team: X-ray 💀

#15652 Upgraded to Storybook 6.1.9
  client/babel.config.js
  client/package.json
  client/yarn.lock
Labels: Ready-to-Merge

#15655 Add storybook entry for search bar
  client/app/components/SearchBar.jsx
  client/app/components/SearchBar.stories.js
  client/app/components/SearchBar.stories.mdx
  client/app/reader/DocumentListHeader.jsx
Labels: Ready-to-Merge

#15659 Mkerns/caseflow 197 future nod date error
  client/COPY.json
  client/app/queue/components/EditNodDateModal.jsx
  client/test/app/queue/components/EditNodDateModal.test.js
  client/test/app/queue/components/__snapshots__/EditNodDateModal.test.js.snap
Labels: Ready-to-Merge, Team: X-ray 💀

#15663 Add storybook entries for remaining form fields
  client/app/components/EditableField.jsx
  client/app/components/EditableField.stories.js
  client/app/components/EditableField.stories.mdx
  client/app/components/InlineForm.jsx
  client/app/components/InlineForm.stories.js
  client/app/components/InlineForm.stories.mdx
  client/app/components/SaveableTextArea.jsx
  client/app/components/SaveableTextArea.stories.js
Labels: Ready-to-Merge

#15657 Creates the Table storybook
  client/app/components/Table.stories.js
Labels: Ready-to-Merge

#15669 Refactor, remove unused, and add storybook entries for StatusMessage
  client/app/components/StatusMessage.jsx
  client/app/components/StatusMessage.stories.js
  client/app/components/StatusMessage.stories.mdx
  client/app/containers/StyleGuide/StyleGuideSuccessMessages.jsx
  client/app/styles/_style_guide.scss
Labels: Ready-to-Merge

#15670 Added support for `inputProps` to `SearchBar`
  client/app/components/SearchBar.jsx
Labels: Ready-to-Merge

#15674 Added `internalTextInputProps` to SearchBar
  client/app/components/SearchBar.jsx
Labels: Ready-to-Merge

#15673 Add Actions story
  client/app/components/Actions.stories.js
  client/app/components/Actions.stories.mdx
Labels: Ready-to-Merge, Type: Enhancement

#15679 stop storing value in the EditableField component
  client/app/components/EditableField.jsx
Labels: Product: caseflow-reader, Ready-to-Merge, Source: Bat Team

#15632 Auto close NoShowHearingTask after 15 days and route correctly
  app/models/tasks/assign_hearing_disposition_task.rb
  app/models/tasks/hearing_task.rb
  app/models/tasks/no_show_hearing_task.rb
  spec/factories/hearing.rb
  spec/factories/legacy_hearing.rb
  spec/feature/hearings/change_hearing_disposition_spec.rb
  spec/models/tasks/assign_hearing_disposition_task_spec.rb
  spec/models/tasks/no_show_hearing_task_spec.rb
Labels: Ready-to-Merge

#15678 Fix reminder email issues
  app/jobs/virtual_hearings/send_reminder_emails_job.rb
  app/services/virtual_hearings/reminder_service.rb
  spec/jobs/virtual_hearings/send_reminder_emails_job_spec.rb
  spec/services/virtual_hearings/reminder_service_spec.rb
Labels: Ready-to-Merge

#15680 Adjustments to Stories for EditableField
  client/app/components/EditableField.jsx
  client/app/components/EditableField.stories.js
  client/app/components/EditableField.stories.mdx
Labels: Ready-to-Merge, Type: Tech-Improvement

#15668 Move poa caching out of UpdateCachedAppealsAttributesJob
  app/jobs/update_cached_appeals_attributes_job.rb
  app/jobs/warm_bgs_caches_job.rb
  app/models/hearings/schedule_hearing_task_pager.rb
  app/models/task.rb
  app/services/cached_appeal_service.rb
  spec/controllers/hearings/schedule_hearing_tasks_columns_controller_spec.rb
  spec/factories/bgs_power_of_attorney.rb
  spec/feature/hearings/assign_hearings_table_spec.rb
  spec/jobs/update_cached_appeals_attributes_job_spec.rb
  spec/jobs/warm_bgs_caches_job_spec.rb
  spec/models/queue_tabs/assign_hearing_tab_spec.rb
Labels: Ready-to-Merge

#15682 Add storybook entries for Veteran Details and Veteran State
  client/app/hearings/components/assignHearings/AssignHearingsTable.jsx
  client/app/queue/VeteranDetail.jsx
  client/app/queue/VeteranDetail.stories.js
Labels: Ready-to-Merge

#15687 Storybook component for Loaders
  client/app/components/Button.stories.js
  client/app/components/Buttons.stories.mdx
  client/app/components/LoadingContainer.stories.js
  client/app/components/LoadingContainer.stories.mdx
  client/app/components/SmallLoader.stories.js
  client/app/components/SmallLoader.stories.mdx
Labels: Ready-to-Merge

#15688 Refactor and storybook AppellantDetail
  client/app/queue/AppellantDetail.jsx
  client/app/queue/AppellantDetail.stories.js
Labels: Ready-to-Merge

#15672 pbradin/CASEFLOW-214 Permissions for Edit Nod Date link
  app/models/user.rb
  app/views/queue/index.html.erb
  client/app/queue/CaseDetailsView.jsx
  client/app/queue/CaseTimeline.jsx
  client/app/queue/QueueApp.jsx
  client/app/queue/uiReducer/uiActions.js
  client/app/queue/uiReducer/uiConstants.js
  client/app/queue/uiReducer/uiReducer.js
  spec/feature/queue/case_details_spec.rb
Labels: Feature: Edit NOD, Ready-to-Merge, Team: X-ray 💀

#15685 Updated the format of errors in the BuildScheduleUploadContainer
  app/controllers/hearings/schedule_periods_controller.rb
  client/app/hearings/components/BuildScheduleUpload.jsx
  client/app/hearings/containers/BuildScheduleUploadContainer.jsx
  client/test/karma/hearings/components/BuildScheduleUpload-test.js
  spec/controllers/hearings/schedule_periods_controller_spec.rb
Labels: Ready-to-Merge

#15698 Remove PaperTrail versioning from Document model
  app/models/document.rb
  spec/models/document_spec.rb
Labels: Ready-to-Merge

#15699 Remove 3 day window constraint when assigning judges to hearing days
  app/services/hearing_schedule/assign_judges_to_hearing_days.rb
Labels: Ready-to-Merge

#15701 Use find_by_css_id for faster lookup using the index
  Dangerfile
  app/controllers/idt/api/v1/base_controller.rb
  app/models/legacy_hearing.rb
  app/models/user.rb
  app/repositories/queue_repository.rb
  app/services/user_reporter.rb
  db/seeds/hearings.rb
  db/seeds/mtv.rb
  db/seeds/tasks.rb
  spec/controllers/idt/api/appeals_controller_spec.rb
  spec/models/tasks/colocated_task_spec.rb
Labels: Eng: Performance, Ready-to-Merge, Source: Bat Team

#15691 Docket Switch Grant Flow Skeleton
  client/app/queue/components/DecisionViewFooter.jsx
  client/app/queue/docketSwitch/docketSwitchRoutes.js
  client/app/queue/docketSwitch/docketSwitchSlice.js
  client/app/queue/docketSwitch/grant/CheckoutButtons.jsx
  client/app/queue/docketSwitch/grant/CheckoutButtons.stories.js
  client/app/queue/docketSwitch/grant/DocketSwitchGrantContainer.jsx
  client/app/queue/docketSwitch/grant/DocketSwitchReviewRequestContainer.jsx
  client/app/queue/docketSwitch/grant/DocketSwitchReviewRequestForm.jsx
  client/app/queue/docketSwitch/grant/DocketSwitchReviewRequestForm.stories.js
  client/app/queue/reducers.js
  spec/factories/task.rb
  spec/feature/queue/docket_switch_spec.rb
Labels: Ready-to-Merge, Team: Foxtrot 🦊

#15605 Limit number of allowed AOD motions
  app/models/advance_on_docket_motion.rb
  spec/models/advance_on_docket_motion_spec.rb
Labels: Team: Echo 🐬

#15703 Add FNOD badge to Queue Case List table
  app/models/appeal.rb
  app/models/serializers/work_queue/appeal_serializer.rb
  app/models/serializers/work_queue/task_serializer.rb
  app/views/queue/index.html.erb
  client/app/queue/CaseListTable.jsx
  client/app/queue/components/BadgeArea.jsx
  client/app/queue/components/FnodBadge.jsx
  client/app/queue/components/FnodBadge.stories.js
  client/app/queue/components/FnodBadge.test.js
  client/app/queue/components/__snapshots__/FnodBadge.test.js.snap
  client/app/queue/utils.js
Labels: Feature: FNOD, Ready-to-Merge, Team: X-ray 💀

#15693 Add cavc to priority appeal distribution logic
  app/models/docket.rb
  db/seeds/priority_distributions.rb
  spec/feature/queue/scm_judge_assignment_spec.rb
  spec/jobs/push_priority_appeals_to_judges_job_spec.rb
  spec/models/docket_spec.rb
Labels: Ready-to-Merge

#15683 Additional bgs error handling in WarmBgsCacheJob
  app/jobs/warm_bgs_caches_job.rb
  spec/jobs/warm_bgs_caches_job_spec.rb
Labels: Ready-to-Merge

#15692 Adds CavcCorrespondenceMailTask
  app/models/tasks/cavc_correspondence_mail_task.rb
  app/models/tasks/mail_task.rb
  client/COPY.json
  lib/caseflow/error.rb
  spec/factories/appeal.rb
  spec/models/tasks/cavc_correspondence_mail_task_spec.rb
  spec/models/tasks/mail_task_spec.rb
Labels: Ready-to-Merge

#15720 Update engineering issue template with impact
  .github/ISSUE_TEMPLATE/engineering-task.md
Labels: Ready-to-Merge

#15717 CASEFLOW-126 #done Copy AOD state to CAVC Remand Appeal
  app/models/advance_on_docket_motion.rb
  app/models/appeal.rb
  app/models/cavc_remand.rb
  spec/factories/appeal.rb
  spec/jobs/set_appeal_age_aod_job_spec.rb
  spec/models/cavc_remand_spec.rb
Labels: Ready-to-Merge, Team: Echo 🐬

#15696 Add JudgeTeam admin method
  app/models/organizations/dvc_team.rb
  app/models/organizations/judge_team.rb
  app/models/organizations_user.rb
  client/COPY.json
  spec/factories/cavc_remand.rb
  spec/models/organizations/dvc_team_spec.rb
  spec/models/organizations/judge_team_spec.rb
  spec/models/organizations_user_spec.rb
  spec/models/user_spec.rb
Labels: Ready-to-Merge

#15714 Create virtual hearing url service
  .gitignore
  app/services/virtual_hearings/link_service.rb
  client/COPY.json
  spec/services/virtual_hearings/link_service_spec.rb
Labels: Product: caseflow-hearings, Stakeholder: BVA, Team: Tango 💃

#15713 create a virtual hearing conference id sequence
  .gitignore
  app/services/virtual_hearings/link_service.rb
  app/services/virtual_hearings/sequence_conference_id.rb
  client/COPY.json
  db/migrate/20201221063738_add_virtual_hearing_conference_id_sequence.rb
  db/schema.rb
  docs/schema/caseflow.csv
  spec/services/virtual_hearings/link_service_spec.rb
  spec/services/virtual_hearings/sequence_conference_id_spec.rb
Labels: Product: caseflow-hearings, Stakeholder: BVA, Team: Tango 💃

#15725 Add pre-AMA date error validation to Edit NOD Date Modal
  client/COPY.json
  client/app/queue/components/EditNodDateModal.jsx
  client/test/app/queue/components/EditNodDateModal.test.js
Labels: Feature: Edit NOD, Team: X-ray 💀

#15730 Parse BGS death date format and coerce to ISO 8601
  app/models/veteran.rb
  client/app/queue/VeteranDetail.jsx
  spec/models/veteran_spec.rb
Labels: Ready-to-Merge

#15705 New edit NOD metadata table
  app/models/appeal.rb
  app/models/nod_date_update.rb
  app/queries/appeals_updated_since_query.rb
  db/migrate/20201215215458_create_nod_date_update.rb
  db/schema.rb
  docs/schema/caseflow.csv
Labels: Feature: Edit NOD, Ready-to-Merge, Team: X-ray 💀

#15731 CASEFLOW-486 Add judges and attorneys to those that can edit DOD date
  app/models/user.rb
  spec/feature/queue/case_details_spec.rb
Labels: Feature: Edit NOD, Ready-to-Merge, Team: X-ray 💀

#15708 Restructured IntakeFrame
  client/app/intake/IntakeFrame.jsx
  client/app/intake/components/IntakeLayout.jsx
  client/app/intake/components/IntakeProgressBar.jsx
  client/app/intake/index.js
Labels: Ready-to-Merge, Team: Foxtrot 🦊

#15718 Intake | Allow deceased veteran appellant on appeals #15681
  app/controllers/intakes_controller.rb
  client/COPY.json
  client/app/components/Alert.jsx
  client/app/intake/components/SelectClaimant.jsx
  client/app/intake/pages/appeal/review.jsx
  client/app/intake/pages/decisionReviewIntakeCompleted.jsx
  client/app/intake/pages/higherLevelReview/review.jsx
  client/app/intake/pages/supplementalClaim/review.jsx
  client/app/intake/reducers/featureToggles.js
  client/test/app/hearings/components/VirtualHearings/__snapshots__/AppellantSection.test.js.snap
  client/test/app/hearings/components/__snapshots__/HearingTypeConversion.test.js.snap
  client/test/app/hearings/components/__snapshots__/HearingTypeConversionForm.test.js.snap
  client/test/app/intake/components/SelectClaimant.test.js
  client/test/app/intake/components/__snapshots__/SelectClaimant.test.js.snap
  db/seeds/intake.rb
  spec/feature/intake/appeal_spec.rb
  spec/feature/intake/higher_level_review_spec.rb
  spec/feature/intake/review_page_spec.rb
  spec/feature/intake/supplemental_claim_spec.rb
  spec/support/intake_helpers.rb
Labels: Team: Foxtrot 🦊

#15734 Check feature toggle on user who updated virtual hearing
  app/jobs/virtual_hearings/create_conference_job.rb
Labels: Team: Tango 💃

#15729 Intake | Docket Change | Inputting docket switch information (Grant)
  client/COPY.json
  client/app/queue/components/DecisionViewFooter.jsx
  client/app/queue/docketSwitch/grant/CheckoutButtons.jsx
  client/app/queue/docketSwitch/grant/DocketSwitchReviewRequestContainer.jsx
  client/app/queue/docketSwitch/grant/DocketSwitchReviewRequestForm.jsx
  client/app/queue/docketSwitch/grant/DocketSwitchReviewRequestForm.stories.js
  client/test/app/queue/components/EditNodDateModal.test.js
  client/test/app/queue/docketSwitch/DocketSwitchReviewRequestForm.test.js
  client/test/app/queue/docketSwitch/__snapshots__/DocketSwitchReviewRequestForm.test.js.snap
  spec/feature/queue/docket_switch_spec.rb
Labels: Ready-to-Merge, Team: Foxtrot 🦊

#15724 Non-Veteran Claimants | Adding "Claimant not listed" Option
  app/controllers/intakes_controller.rb
  client/COPY.json
  client/app/components/Alert.jsx
  client/app/intake/components/SelectClaimant.jsx
  client/app/intake/components/SelectClaimant.stories.js
  client/app/intake/pages/appeal/review.jsx
  client/app/intake/pages/decisionReviewIntakeCompleted.jsx
  client/app/intake/pages/higherLevelReview/review.jsx
  client/app/intake/pages/supplementalClaim/review.jsx
  client/app/intake/reducers/featureToggles.js
  client/test/app/hearings/components/VirtualHearings/__snapshots__/AppellantSection.test.js.snap
  client/test/app/hearings/components/__snapshots__/HearingTypeConversion.test.js.snap
  client/test/app/hearings/components/__snapshots__/HearingTypeConversionForm.test.js.snap
  client/test/app/intake/components/SelectClaimant.test.js
  client/test/app/intake/components/__snapshots__/SelectClaimant.test.js.snap
  db/seeds/intake.rb
  spec/feature/intake/appeal_spec.rb
  spec/feature/intake/higher_level_review_spec.rb
  spec/feature/intake/review_page_spec.rb
  spec/feature/intake/supplemental_claim_spec.rb
  spec/support/intake_helpers.rb
Labels: Ready-to-Merge, Team: Foxtrot 🦊
