Repository department-of-veterans-affairs/caseflow, pull requests merged in 2020-07, with the labels that each got.

#14633 Handle BGS::AccountLocked error
  Gemfile
  Gemfile.lock
  app/controllers/idt/api/v1/appeals_controller.rb
  spec/controllers/idt/api/appeals_controller_spec.rb
Labels: Priority: Medium, Product: IDT, Ready-to-Merge, Source: Bat Team, Source: Sentry Alert

#14622 Make docket range job idempotent
  app/jobs/docket_range_job.rb
  app/models/docket_coordinator.rb
  spec/jobs/docket_range_job_spec.rb
  spec/models/docket_coordinator_spec.rb
Labels: Ready-to-Merge, Team: Tango 💃

#14636 Intake | G Code | Store original legacy appeal data in case of rollback
  db/migrate/20200702015739_add_original_legacy_appeal_to_legacy_issue_optins.rb
  db/schema.rb
  docs/schema/caseflow.csv
Labels: Ready-to-Merge

#14644 Tomas/14620 fix virtual hearing mailer spec
  spec/mailers/virtual_hearing_mailer_spec.rb
Labels: Team: Tango 💃

#14577 Update logic for unpacking the VACOLS hearing_date field
  app/mappers/hearing_mapper.rb
  app/models/hearing_day.rb
  app/models/legacy_hearing.rb
  app/models/regional_office.rb
  app/repositories/hearing_repository.rb
  spec/factories/legacy_hearing.rb
  spec/mailers/virtual_hearing_mailer_spec.rb
  spec/mappers/hearing_mapper_spec.rb
  spec/models/legacy_hearing_spec.rb
Labels: Priority: High, Product: caseflow-hearings, Ready-to-Merge, Stakeholder: BVA, Team: Tango 💃

#14646 Rescue RecordNotUnique for BgsPowerOfAttorney
  app/models/claimant.rb
  app/models/power_of_attorney.rb
  spec/models/claimant_spec.rb
  spec/models/power_of_attorney_spec.rb
Labels: Ready-to-Merge, Team: Tango 💃

#14649 Update postgres legacy appeals in batches
  app/jobs/update_cached_appeals_attributes_job.rb
Labels: Ready-to-Merge, Team: Tango 💃

#14407 [Part 1] Add Special Issues to Legacy Appeals
  app/models/legacy_appeal.rb
  client/app/constants/SpecialIssues.js
  client/app/containers/EstablishClaimPage/EstablishClaimDecision.jsx
  client/app/establishClaim/constants/index.js
  client/app/establishClaim/reducers/specialIssues.js
  db/migrate/20200629193042_add_new_contensions_to_legacy_appeal.rb
  db/schema.rb
  docs/schema/caseflow.csv
  spec/feature/dispatch/establish_claim_spec.rb
Labels: Ready-to-Merge

#14650 Refactor POA concurrency rescue; add concurrent test
  app/jobs/update_cached_appeals_attributes_job.rb
  app/models/bgs_power_of_attorney.rb
  app/models/claimant.rb
  app/models/power_of_attorney.rb
  spec/jobs/update_cached_appeals_attributes_job_spec.rb
  spec/models/bgs_power_of_attorney_spec.rb
  spec/models/claimant_spec.rb
  spec/models/power_of_attorney_spec.rb
Labels: Ready-to-Merge, Type: Tech-Improvement

#14647 Add cancel field to cancel task modal
  app/models/tasks/attorney_task.rb
  app/workflows/bulk_task_reassignment.rb
  client/app/queue/components/CancelTaskModal.jsx
  spec/feature/hearings/schedule_veteran/build_hearsched_spec.rb
  spec/feature/queue/case_details_spec.rb
  spec/feature/queue/scm_judge_assignment_spec.rb
  spec/feature/queue/task_queue_spec.rb
  spec/feature/queue/transcription_team_spec.rb
  spec/models/tasks/attorney_task_spec.rb
Labels: Ready-to-Merge

#14589 Contested Claims | Attorney Fees | Add claimant subclasses
  app/models/appeal.rb
  app/models/appeal_intake.rb
  app/models/attorney_claimant.rb
  app/models/claim_review_intake.rb
  app/models/claimant.rb
  app/models/decision_issue.rb
  app/models/decision_review.rb
  app/models/dependent_claimant.rb
  app/models/veteran_claimant.rb
  db/seeds/intake.rb
  spec/factories/appeal.rb
  spec/factories/claimant.rb
  spec/factories/higher_level_review.rb
  spec/factories/supplemental_claim.rb
  spec/feature/intake/appeal_spec.rb
  spec/feature/intake/higher_level_review/edit_spec.rb
  spec/feature/intake/higher_level_review_spec.rb
  spec/feature/intake/supplemental_claim/edit_spec.rb
  spec/feature/intake/supplemental_claim_spec.rb
  spec/models/appeal_intake_spec.rb
  spec/models/appeal_spec.rb
  spec/models/claim_review_intake_spec.rb
  spec/models/claimant_spec.rb
  spec/models/end_product_establishment_spec.rb
  spec/models/higher_level_review_intake_spec.rb
  spec/models/higher_level_review_spec.rb
  spec/models/intake_spec.rb
  spec/models/supplemental_claim_intake_spec.rb
  spec/models/validators/claimant_validator_spec.rb
  spec/support/intake_helpers.rb
Labels: Ready-to-Merge, Team: Foxtrot 🦊

#14651 Avoid triggering extra VACOLS call for hearing when mapping data
  app/models/legacy_hearing.rb
  app/repositories/hearing_repository.rb
Labels: Ready-to-Merge, Team: Tango 💃

#14579 Bump `react-select` and Update `SearchableDropdown`
  client/app/components/SearchableDropdown.jsx
  client/app/components/SearchableDropdown.stories.js
  client/app/containers/StyleGuide/StyleGuideSearchableDropdown.jsx
  client/app/hearings/components/VirtualHearings/Timezone.jsx
  client/app/hearings/components/details/style.jsx
  client/app/intake/components/AddClaimantModal.jsx
  client/app/queue/OrganizationUsers.jsx
  client/app/queue/UserManagement.jsx
  client/app/reader/SideBarIssueTags.jsx
  client/app/styles/react/_select-dropdown.scss
  client/package.json
  client/test/app/components/SearchableDropdown.test.js
  client/test/app/components/__snapshots__/SearchableDropdown.test.js.snap
  client/test/app/hearings/components/VirtualHearings/HearingTime.test.js
  client/test/app/hearings/components/VirtualHearings/Timezone.test.js
  client/test/app/hearings/components/VirtualHearings/__snapshots__/Timezone.test.js.snap
  client/test/app/hearings/components/details/__snapshots__/DetailsForm.test.js.snap
  client/test/app/hearings/components/modalForms/HearingTime.test.js
  client/test/app/hearings/components/modalForms/__snapshots__/HearingTime.test.js.snap
  client/test/app/intake/components/__snapshots__/AddClaimantModal.test.js.snap
  client/yarn.lock
  spec/controllers/tag_controller_spec.rb
  spec/feature/hearings/add_hearing_day_spec.rb
  spec/feature/hearings/change_hearing_disposition_spec.rb
  spec/feature/hearings/daily_docket/build_hearsched_spec.rb
  spec/feature/hearings/daily_docket/ro_viewhearsched_spec.rb
  spec/feature/hearings/edit_hearing_day_spec.rb
  spec/feature/hearings/hearing_admin_action_verify_address_task_spec.rb
  spec/feature/hearings/hearing_details_spec.rb
  spec/feature/hearings/hearing_worksheet/hearing_prep_spec.rb
  spec/feature/hearings/schedule_veteran/build_hearsched_spec.rb
  spec/feature/hearings/virtual_hearings/daily_docket_spec.rb
  spec/feature/hearings/virtual_hearings/hearing_details_spec.rb
  spec/feature/intake/add_issues_spec.rb
  spec/feature/intake/review_page_spec.rb
  spec/feature/login_spec.rb
  spec/feature/non_comp/dispositions_spec.rb
  spec/feature/queue/ama_queue_spec.rb
  spec/feature/queue/attorney_checkout_flow_spec.rb
  spec/feature/queue/bva_dispatch_return_flow_spec.rb
  spec/feature/queue/case_assignment_spec.rb
  spec/feature/queue/case_details_spec.rb
  spec/feature/queue/colocated_task_queue_spec.rb
  spec/feature/queue/judge_assignment_spec.rb
  spec/feature/queue/mail_task_spec.rb
  spec/feature/queue/motion_to_vacate_spec.rb
  spec/feature/queue/privacy_team_spec.rb
  spec/feature/queue/quality_review_flow_spec.rb
  spec/feature/queue/scm_judge_assignment_spec.rb
  spec/feature/queue/task_queue_spec.rb
  spec/feature/queue/user_organization_spec.rb
  spec/feature/queue/users_management_spec.rb
  spec/feature/reader/reader_spec.rb
  spec/feature/switch_user_spec.rb
  spec/feature/withdrawn_request_issues_spec.rb
  spec/support/feature_helper.rb
  spec/support/intake_helpers.rb
Labels: Ready-to-Merge, Team: Foxtrot 🦊

#14618 v3 API - nest /contestable_issues under /higher_level_reviews
  app/controllers/api/v3/base_controller.rb
  app/controllers/api/v3/decision_reviews/contestable_issues_controller.rb
  app/controllers/api/v3/decision_reviews/higher_level_reviews/contestable_issues_controller.rb
  app/controllers/api/v3/decision_reviews/intake_statuses_controller.rb
  app/models/rating_issue.rb
  app/serializers/intake/rating_issue_serializer.rb
  config/routes.rb
  lib/generators/promulgated_rating.rb
  spec/requests/api/v3/decision_reviews/higher_level_reviews/contestable_issues_controller_spec.rb
Labels: Integration: Lighthouse, Ready-to-Merge

#14624 Call out sort direction on table sort icons
  client/app/queue/QueueTable.jsx
  client/app/reader/DocumentsTable.jsx
Labels: Ready-to-Merge

#14635 Disable Geomatching Across State Lines
  app/models/regional_office.rb
  app/services/va_dot_gov_address_validator.rb
  app/services/va_dot_gov_address_validator/closest_regional_office_finder.rb
  app/services/va_dot_gov_address_validator/validations.rb
  spec/models/regional_office_spec.rb
  spec/models/tasks/hearing_admin_action_verify_address_task_spec.rb
  spec/services/va_dot_gov_address_validator/closest_regional_office_finder_spec.rb
  spec/services/va_dot_gov_address_validator_spec.rb
Labels: Ready-to-Merge, Team: Tango 💃

#14501 Allow all orgs to bulk assign tasks
  app/models/organization.rb
  app/models/organizations/hearings_management.rb
  app/models/organizations/mail_team.rb
  app/models/organizations/privacy_team.rb
  app/models/organizations/transcription_team.rb
  app/models/organizations/vso.rb
  app/models/queue_tabs/organization_unassigned_tasks_tab.rb
  app/models/user.rb
  app/workflows/bulk_task_assignment.rb
  spec/feature/queue/bulk_task_assignment_spec.rb
  spec/models/queue_tab_spec.rb
  spec/models/queue_tabs/organization_unassigned_tasks_tab_spec.rb
  spec/workflows/bulk_task_assignment_spec.rb
Labels: Ready-to-Merge

#14628 Make controller schemas stricter by discarding unknown fields
  .reek.yml
  app/controllers/concerns/validation_concern.rb
  app/schemas/controller_schema.rb
  spec/schemas/controller_schema_spec.rb
Labels: Ready-to-Merge, Type: Tech-Improvement

#14631 Contested Claims | Attorney Fees | Backfill veteran and dependent claimant types
  db/migrate/20200707012721_backfill_veteran_and_dependent_claimant_types.rb
  db/schema.rb
Labels: Ready-to-Merge, Team: Foxtrot 🦊

#14665 Enable Reader's accordion side bar to expand
  client/app/reader/SideBarIssueTags.jsx
Labels: Priority: High, Product: caseflow-reader, Ready-to-Merge, Source: Bat Team, Stakeholder: BVA

#14663 Remove extra "to"
  client/COPY.json
Labels: Ready-to-Merge

#14675 Fix BGS POA test flake caused by sharing Redis state
  spec/models/bgs_power_of_attorney_spec.rb
  spec/models/power_of_attorney_spec.rb
Labels: Eng: Flaky Test, Ready-to-Merge

#14666 Fix issue when geomatching returns the San Antonio facility id for closest RO
  app/services/va_dot_gov_address_validator.rb
  app/services/va_dot_gov_address_validator/validations.rb
  spec/services/va_dot_gov_address_validator_spec.rb
Labels: Ready-to-Merge, Team: Tango 💃

#14679 Allow users to remove the last issue tag on a document
  client/app/components/SearchableDropdown.jsx
Labels: Priority: Medium, Product: caseflow-reader, Ready-to-Merge, Source: Bat Team, Stakeholder: BVA, Type: Bug

#14664 Release CM users acting on behalf of judges
  app/controllers/tasks_controller.rb
  app/models/user.rb
  spec/controllers/distributions_controller_spec.rb
  spec/controllers/judge_assign_tasks_controller_spec.rb
  spec/controllers/legacy_tasks_controller_spec.rb
  spec/controllers/tasks_controller_spec.rb
  spec/feature/queue/judge_assignment_spec.rb
  spec/feature/queue/scm_judge_assignment_spec.rb
  spec/models/legacy_tasks/judge_legacy_task_spec.rb
  spec/models/tasks/judge_task_spec.rb
Labels: Ready-to-Merge

#14615 Distribute down to 30 legacy non priority cases tied to a judge before proceeding with auto case distribution
  app/models/concerns/ama_case_distribution.rb
  app/models/dockets/legacy_docket.rb
  app/models/vacols/case_docket.rb
  app/repositories/appeal_repository.rb
  spec/models/distribution_spec.rb
  spec/models/vacols/case_docket_spec.rb
  spec/workflows/das_deprecation/case_distribution_spec.rb
Labels: Ready-to-Merge

#14681 Show cancelled appeals in search and list all cases
  app/services/appeal_finder.rb
  db/schema.rb
  spec/factories/appeal.rb
  spec/feature/queue/search_spec.rb
  spec/services/appeal_finder_spec.rb
Labels: Ready-to-Merge

#14652 Intake | G Code | Store original legacy appeal data in case of rollback
  app/models/request_issue.rb
  db/migrate/20200710232644_rename_folder_date_timeof_decision.rb
  db/schema.rb
  docs/schema/caseflow.csv
  spec/models/request_issue_spec.rb
Labels: Ready-to-Merge

#14678 Fix how updated_by gets assigned
  app/models/concerns/updated_by_user_concern.rb
  app/models/hearing.rb
  app/models/hearing_day.rb
  app/models/hearings/virtual_hearing.rb
  app/models/legacy_hearing.rb
  spec/controllers/hearings_controller_spec.rb
Labels: Ready-to-Merge, Team: Tango 💃

#14683 show correct am/pm on the central office time in the change virtual hearing time modal
  client/app/hearings/components/VirtualHearingModal.jsx
  spec/feature/hearings/virtual_hearings/daily_docket_spec.rb
Labels: Product: caseflow-hearings, Ready-to-Merge, Stakeholder: BVA, Team: Tango 💃

#14660 Refactor components around Assign Hearings Page
  client/app/components/DataDropdowns/HearingDate.jsx
  client/app/components/DataDropdowns/HearingRoom.jsx
  client/app/components/DataDropdowns/index.js
  client/app/hearings/components/HearingDayEditModal.jsx
  client/app/hearings/components/assignHearings/AssignHearings.jsx
  client/app/hearings/containers/AssignHearingsContainer.jsx
Labels: Ready-to-Merge, Team: Tango 💃

#14687 Add make migrate to make docs pr instructions
  PULL_REQUEST_TEMPLATE.md
Labels: Ready-to-Merge

#14694 Add reminder to check migrate:rollback
  PULL_REQUEST_TEMPLATE.md
Labels: Ready-to-Merge, Type: Documentation

#14672 Remove errant reload when bulk assigning tasks
  app/controllers/bulk_task_assignments_controller.rb
  client/app/queue/components/BulkAssignModal.jsx
  spec/controllers/bulk_task_assignments_controller_spec.rb
  spec/feature/queue/bulk_task_assignment_spec.rb
Labels: Ready-to-Merge

#14686 Add priority flag to distributions
  app/controllers/distributions_controller.rb
  app/models/distribution.rb
  db/migrate/20200713173228_add_priority_to_distributions.rb
  db/migrate/20200713174152_backfill_distribution_priority.rb
  db/schema.rb
  docs/schema/caseflow.csv
  spec/models/distribution_spec.rb
Labels: Ready-to-Merge

#14696 Reinstate db:migration:redo check in CI
  .circleci/config.yml
Labels: Ready-to-Merge, Type: Tech-Improvement

#14699 Send back to judge assign without cancel params
  app/models/tasks/attorney_task.rb
  spec/models/tasks/attorney_task_spec.rb
Labels: Ready-to-Merge

#14695 Add request throttling to VA.gov service
  app/jobs/fetch_hearing_locations_for_veterans_job.rb
  app/services/external_api/va_dot_gov_service.rb
Labels: Ready-to-Merge, Team: Tango 💃

#14682 Sort rating_issue_serializer
  app/serializers/intake/rating_issue_serializer.rb
Labels: Ready-to-Merge

#14702 Properly clear overtime success message
  client/app/queue/CaseDetailsLoadingScreen.jsx
  client/app/queue/SetOvertimeStatusModal.jsx
  client/app/queue/components/StartHoldModal.jsx
Labels: Ready-to-Merge

#14690 Reassigning LegacyAppeal drafting to another attorney clears overtime status
  app/controllers/legacy_tasks_controller.rb
  spec/controllers/legacy_tasks_controller_spec.rb
Labels: Ready-to-Merge

#14701 Add comments to hearings* tables and document models
  app/jobs/virtual_hearings/delete_conferences_job.rb
  app/models/hearing.rb
  app/models/hearing_day.rb
  app/models/hearing_location.rb
  app/models/hearings/available_hearing_locations.rb
  app/models/hearings/sent_hearing_email_event.rb
  app/models/hearings/virtual_hearing.rb
  app/models/legacy_hearing.rb
  app/models/tasks/assign_hearing_disposition_task.rb
  app/models/tasks/schedule_hearing_task.rb
  app/models/tasks/transcription_task.rb
  db/migrate/20200715144822_add_comments_to_hearings_table.rb
  db/schema.rb
  docs/schema/caseflow.csv
Labels: Ready-to-Merge

#14707 Add exponential retries to error handling
  app/jobs/virtual_hearings/create_conference_job.rb
  app/jobs/virtual_hearings/delete_conferences_job.rb
  spec/jobs/virtual_hearings/create_conference_job_spec.rb
Labels: Ready-to-Merge, Team: Tango 💃

#14688 Allow JudgeTeams to be marked for new ACD priority job cases
  app/models/organizations/judge_team.rb
  db/etl/migrate/20200715110034_add_accepts_priority_pushed_cases_to_etl_organization.rb
  db/etl/migrate/20200715110603_add_accepts_priority_pushed_cases_index_on_organization.rb
  db/etl/schema.rb
  db/migrate/20200715105504_add_accepts_priority_pushed_cases_to_organization.rb
  db/migrate/20200715105643_backfill_judge_team_accepts_priority_pushed_cases.rb
  db/migrate/20200715105703_add_accepts_priority_pushed_cases_index_on_organization.rb
  db/schema.rb
  docs/schema/caseflow.csv
  docs/schema/etl.csv
  spec/models/organizations/judge_team_spec.rb
Labels: Ready-to-Merge

#14713 Intake | Missing Ratings | Add service to fetch current rating profile |updated ruby_bgs gem
  Gemfile
  Gemfile.lock
Labels: Ready-to-Merge

#14727 increase the query limit on the FetchHearingLocationForVeteransJob
  app/jobs/fetch_hearing_locations_for_veterans_job.rb
  app/services/external_api/va_dot_gov_service.rb
Labels: Ready-to-Merge, Team: Tango 💃

#14700 Add stub implementations of all claimant subclasses
  app/models/attorney_claimant.rb
  app/models/bgs_related_claimant.rb
  app/models/claimant.rb
  app/models/dependent_claimant.rb
  app/models/other_claimant.rb
  app/models/veteran_claimant.rb
  spec/factories/claimant.rb
  spec/models/claimant_spec.rb
  spec/models/decision_issue_spec.rb
Labels: Ready-to-Merge, Team: Foxtrot 🦊

#14662 Check for veteran record where ssn is stored as file number
  app/models/veteran.rb
  spec/feature/intake/appeal/edit_spec.rb
  spec/models/veteran_spec.rb
Labels: Ready-to-Merge, Team: Foxtrot 🦊, Type: Bug

#14728 Updated FACOLS with new field size
  app/mappers/hearing_mapper.rb
  lib/tasks/local/destroy.rake
  local/vacols/vacols_copy_2_tables_dev.sql
  local/vacols/vacols_copy_2_tables_test.sql
Labels: Ready-to-Merge

#14729 Intake | Missing Ratings | Handle unpromulgated ratings from RatingAtIssue
  app/models/rating.rb
  app/models/veteran.rb
  lib/fakes/bgs_service.rb
  spec/models/rating_at_issue_spec.rb
Labels: Ready-to-Merge

#14744 Do not enable das feature flag by default
  scripts/enable_features_dev.rb
Labels: Eng: Backend Work Group

#14740 Added tests for the TextareaField component and added character limit…
  client/app/hearings/components/dailyDocket/DailyDocketRowInputs.jsx
  client/app/hearings/components/details/DetailsForm.jsx
  client/test/app/components/TextareaField.test.js
  client/test/app/components/__snapshots__/TextareaField.test.js.snap
Labels: Ready-to-Merge, Team: Tango 💃

#14746 Use appeal.undecided_issues.count for legacy appeals
  app/models/serializers/work_queue/task_column_serializer.rb
  app/models/serializers/work_queue/task_serializer.rb
  spec/controllers/tasks_controller_spec.rb
Labels: Ready-to-Merge

#14743 Started refactoring modal to only send emails based on updated fields
  app/models/hearings/forms/base_hearing_update_form.rb
  client/app/hearings/components/Details.jsx
  client/app/hearings/components/VirtualHearingModal.jsx
  client/app/hearings/components/VirtualHearings/Timezone.jsx
  client/app/hearings/components/details/ReadOnly.jsx
  client/app/hearings/components/details/VirtualHearingForm.jsx
  client/app/hearings/components/details/style.jsx
  client/app/hearings/utils.js
  client/jest.config.js
  client/test/app/hearings/components/VirtualHearingModal.test.js
  client/test/app/hearings/components/__snapshots__/VirtualHearingModal.test.js.snap
  client/test/data/hearings.js
  spec/factories/virtual_hearing.rb
  spec/feature/hearings/virtual_hearings/daily_docket_spec.rb
  spec/feature/hearings/virtual_hearings/hearing_details_spec.rb
Labels: Ready-to-Merge

#14731 Intake | G-code | Add code for opting in G code appeals
  app/models/issue.rb
  app/models/legacy_appeal.rb
  app/models/legacy_issue_optin.rb
  app/repositories/appeal_repository.rb
  app/services/legacy_optin_manager.rb
  spec/factories/vacols/case.rb
  spec/repositories/appeal_repository_spec.rb
  spec/services/legacy_optin_manager_spec.rb
Labels: Ready-to-Merge, Stakeholder: BVA, Team: Foxtrot 🦊

#14751 Danger alerts for ETL changes
  Dangerfile
Labels: Ready-to-Merge

#14766 temporarily re-add one second of sleep to va.gov api calls
  app/services/external_api/va_dot_gov_service.rb
Labels: Ready-to-Merge, Team: Tango 💃

#14775 Add reminders to capture requirements and concerns
  .github/ISSUE_TEMPLATE/echo-tech-spec.md
Labels: Team: Echo 🐬

#14758 Do not update contention if no contention exists
  app/models/request_issue_contention.rb
  spec/models/request_issue_contention_spec.rb
  spec/models/request_issues_update_spec.rb
Labels: Ready-to-Merge, Source: Upstream-error, Team: Foxtrot 🦊, Type: Bug

#14648 Update Intake Review Endpoint to Support Different Claimant Types
  app/models/appeal_intake.rb
  app/models/attorney_claimant.rb
  app/models/bgs_related_claimant.rb
  app/models/claim_review_intake.rb
  app/models/claimant.rb
  app/models/decision_review.rb
  app/models/decision_review_intake.rb
  app/models/higher_level_review_intake.rb
  app/models/intake.rb
  app/models/other_claimant.rb
  app/models/supplemental_claim_intake.rb
  app/models/validators/other_claimant_validator.rb
  app/schemas/controller_schema.rb
  app/schemas/intakes_schemas.rb
  app/serializers/intake/decision_review_serializer.rb
  app/services/api/v3/decision_reviews/higher_level_review_intake_params.rb
  client/app/components/TextareaField.jsx
  client/app/intake/actions/decisionReview.js
  client/app/intake/components/AddClaimantModal.jsx
  client/app/intake/components/SelectClaimant.jsx
  client/app/intake/constants.js
  client/app/intake/reducers/appeal.js
  client/app/intake/reducers/common.js
  client/app/intake/reducers/higherLevelReview.js
  client/app/intake/reducers/supplementalClaim.js
  client/app/intake/util/index.js
  client/app/intake/util/issues.js
  client/test/app/intake/components/AddClaimantModal.test.js
  client/test/app/intake/components/__snapshots__/AddClaimantModal.test.js.snap
  spec/factories/appeal.rb
  spec/feature/intake/higher_level_review_spec.rb
  spec/feature/intake/review_page_spec.rb
  spec/feature/intake/supplemental_claim_spec.rb
  spec/models/appeal_intake_spec.rb
  spec/models/attorney_claimant_spec.rb
  spec/models/claim_review_intake_spec.rb
  spec/services/api/v3/decision_reviews/higher_level_review_intake_params_spec.rb
  spec/support/intake_helpers.rb
Labels: Ready-to-Merge, Team: Foxtrot 🦊

#14776 Refactored to display virtual hearing fields different for Video hear…
  client/app/hearings/components/VirtualHearings/Emails.jsx
  client/app/hearings/components/VirtualHearings/Fields.jsx
  client/app/hearings/components/VirtualHearings/Timezone.jsx
  client/app/hearings/components/details/VirtualHearingForm.jsx
  client/test/app/hearings/components/VirtualHearings/Emails.test.js
  client/test/app/hearings/components/VirtualHearings/Fields.test.js
  client/test/app/hearings/components/VirtualHearings/Timezone.test.js
  client/test/app/hearings/components/VirtualHearings/__snapshots__/Emails.test.js.snap
  client/test/app/hearings/components/VirtualHearings/__snapshots__/Fields.test.js.snap
  client/test/app/hearings/components/VirtualHearings/__snapshots__/Timezone.test.js.snap
  client/test/app/hearings/components/__snapshots__/VirtualHearingModal.test.js.snap
Labels: Ready-to-Merge

#14764 [Part 2] Populate age_aod column
  app/controllers/api/v1/jobs_controller.rb
  app/jobs/set_appeal_age_aod_job.rb
  app/models/appeal.rb
  app/models/attorney_claimant.rb
  app/models/claimant.rb
  app/models/person.rb
  spec/jobs/set_appeal_age_aod_job_spec.rb
  spec/models/appeal_spec.rb
  spec/models/claimant_spec.rb
Labels: Stakeholder: BVA, Team: Echo 🐬, Type: Metrics or Reporting

#14782 Change cavc column to us_court_of_appeals_for_veterans_claims
  app/controllers/special_issues_controller.rb
  db/migrate/20200728172002_rename_special_issues_cavc_column.rb
  db/schema.rb
  docs/schema/caseflow.csv
Labels: Ready-to-Merge

#14763 Add and populate aod_based_on_age column
  app/controllers/api/v1/jobs_controller.rb
  app/jobs/set_appeal_age_aod_job.rb
  app/models/appeal.rb
  app/models/attorney_claimant.rb
  app/models/claimant.rb
  app/models/person.rb
  db/migrate/20200724030847_add_age_aod_column_to_appeals.rb
  db/migrate/20200724031142_add_age_aod_index_to_appeals.rb
  db/schema.rb
  docs/schema/caseflow.csv
  spec/jobs/set_appeal_age_aod_job_spec.rb
  spec/models/appeal_spec.rb
  spec/models/claimant_spec.rb
Labels: Ready-to-Merge, Stakeholder: BVA, Team: Echo 🐬, Type: Metrics or Reporting

#14784 Allow users to access special issues page
  app/models/tasks/judge_decision_review_task.rb
  app/repositories/task_action_repository.rb
  spec/feature/dispatch/establish_claim_spec.rb
  spec/feature/queue/attorney_checkout_flow_spec.rb
  spec/feature/queue/judge_checkout_flow_spec.rb
Labels: Ready-to-Merge

#14788 Updated regex in StringUtil.parseLinks
  client/app/util/StringUtil.js
  client/test/app/util/StringUtil.test.js
Labels: Ready-to-Merge, Team: Foxtrot 🦊, Type: Bug

#14799 Fix bug preventing selection of deceased vet's dependent claimant
  client/app/intake/components/SelectClaimant.jsx
  spec/feature/intake/review_page_spec.rb
Labels: Ready-to-Merge, Source: Bat Team, Team: Foxtrot 🦊, Type: Bug

#14813 Legacy cases with blocking mail records or diaries are not ready to be distributed
  app/models/vacols/case_docket.rb
  spec/factories/vacols/mail.rb
  spec/models/vacols/case_docket_spec.rb
Labels: Feature: auto-case-distribution, Priority: Medium, Ready-to-Merge, Stakeholder: BVA, Team: Echo 🐬, Type: Bug

#14777 Added Story for `AddressMotionToVacateView`
  client/app/queue/mtv/AddressMotionToVacateView.stories.js
  client/app/queue/mtv/MTVIssueSelection.jsx
Labels: Eng: Frontend Work Group, Ready-to-Merge, Team: Foxtrot 🦊

#14800 Show error message that's triggered when opening modal
  client/app/queue/CaseDetailsView.jsx
  client/app/queue/components/AssignHearingModal.jsx
  client/app/queue/components/QueueFlowModal.jsx
  spec/feature/hearings/schedule_veteran/build_hearsched_spec.rb
Labels: Ready-to-Merge, Team: Tango 💃

#14742 Show room on hearing date dropdown
  app/controllers/regional_offices_controller.rb
  client/app/components/DataDropdowns/HearingDate.jsx
  client/app/hearings/components/modalForms/AssignHearingForm.jsx
  spec/feature/hearings/schedule_veteran/build_hearsched_spec.rb
Labels: Ready-to-Merge

#14837 Resolve issues with converting central office hearings between virtual type
  app/models/hearing.rb
  app/models/legacy_hearing.rb
  app/serializers/hearings/hearing_serializer.rb
  app/serializers/hearings/legacy_hearing_serializer.rb
  client/app/hearings/components/Details.jsx
  client/app/hearings/components/HearingConversion.jsx
  client/app/hearings/components/details/Address.jsx
  client/test/app/hearings/components/HearingConversion.test.js
  client/test/app/hearings/components/__snapshots__/HearingConversion.test.js.snap
  client/test/data/hearings.js
Labels: Ready-to-Merge

#14844 Set SQS queue on SetAppealAgeAodJob
  app/jobs/set_appeal_age_aod_job.rb
Labels: Product: caseflow-queue, Ready-to-Merge, Stakeholder: BVA, Team: Echo 🐬, Type: Metrics or Reporting
