Repository department-of-veterans-affairs/caseflow, pull requests merged in 2020-03, with the labels that each got.

#13562 Upgrade puma to 3.12.4
  Gemfile
  Gemfile.lock
Labels: Ready-to-Merge

#13537 Check for existing claim before re-attempting establishment
  app/models/concerns/asyncable.rb
  app/models/end_product_establishment.rb
  spec/models/end_product_establishment_spec.rb
Labels: AMO, Bug, Ready-to-Merge, VBMS, caseflow-intake, foxtrot, upstream-error

#13543 Add test_link to virtual hearing email
  app/mailers/virtual_hearing_mailer.rb
  app/views/virtual_hearing_mailer/sections/_test_your_connection.html.erb
Labels: Ready-to-Merge

#13559 Add yarn commands and update help in makefile
  Makefile.example
Labels: Ready-to-Merge

#13565 Small optimization similar to #9232
  app/services/etl/syncer.rb
Labels: Ready-to-Merge

#13558 Intake | Fix bug when correcting an issue on a DTA supplemental claim.
  app/workflows/request_issue_correction_cleaner.rb
  spec/workflows/request_issue_correction_cleaner_spec.rb
Labels: AMO Reported, Bug, Ready-to-Merge, caseflow-intake

#13568 Rails 6 deprecation
  spec/feature/api/v2/appeals_spec.rb
Labels: Ready-to-Merge

#13566 Fix test flakes
  spec/feature/certification/cancel_certification_spec.rb
  spec/lib/tasks/fixes_spec.rb
  spec/lib/tasks/tasks_spec.rb
  spec/models/user_spec.rb
  spec/repositories/attorney_repository_spec.rb
  spec/repositories/judge_repository_spec.rb
  spec/support/shared_examples/rake.rb
Labels: Ready-to-Merge

#13567 Fix test flakes
  spec/feature/intake/higher_level_review_spec.rb
  spec/requests/api/v3/decision_review/higher_level_reviews_controller_spec.rb
Labels: Ready-to-Merge

#13572 Motion to Vacate | Make draft decision URL optional
  client/app/components/TextField.jsx
  client/app/queue/mtv/MTVDispositionSelection.jsx
  client/app/queue/mtv/MTVJudgeDisposition.jsx
  client/app/queue/mtv/MotionsAttorneyDisposition.jsx
  spec/feature/queue/motion_to_vacate_spec.rb
Labels: Ready-to-Merge

#13577 Motions to Vacate | Set up demo data in seeds
  db/seeds.rb
Labels: foxtrot

#13573 Added Success Alert after MTV Return to Lit Support
  app/controllers/post_decision_motions_controller.rb
  client/COPY.json
  client/app/queue/mtv/motionToVacateRoutes.js
  client/app/queue/mtv/mtvActions.js
  client/app/queue/mtv/mtvMessages.js
  spec/feature/queue/motion_to_vacate_spec.rb
Labels: Ready-to-Merge, foxtrot

#13560 Allow SCM user to view judge assign queue
  app/controllers/tasks_controller.rb
  client/app/queue/JudgeAssignTaskListView.jsx
  client/app/queue/QueueApp.jsx
  client/app/queue/QueueLoadingScreen.jsx
  client/app/queue/selectors.js
  client/app/queue/uiReducer/uiActions.js
  client/app/queue/uiReducer/uiConstants.js
  client/app/queue/uiReducer/uiReducer.js
  spec/feature/queue/scm_judge_assignment_spec.rb
Labels: Ready-to-Merge, caseflow-queue, echo

#13574 Add LegacyAppealsWithNoVacolsCase to nightly check
  app/jobs/data_integrity_checks_job.rb
  app/services/legacy_appeals_with_no_vacols_case.rb
  spec/services/legacy_appeals_with_no_vacols_case_spec.rb
Labels: Ready-to-Merge

#13141 Implement Pagination for Assign Hearings
  .reek.yml
  app/controllers/hearings/schedule_hearing_tasks_columns_controller.rb
  app/controllers/hearings/schedule_hearing_tasks_controller.rb
  app/controllers/tasks_controller.rb
  app/models/hearings/schedule_hearing_task_pager.rb
  app/models/queue_filter_parameter.rb
  app/models/queue_tabs/assign_hearing_tab.rb
  app/models/queues/hearing_coordinator_schedule_queue.rb
  app/models/serializers/work_queue/appeal_serializer.rb
  app/models/serializers/work_queue/legacy_appeal_serializer.rb
  app/models/serializers/work_queue/task_serializer.rb
  app/models/task_filter.rb
  app/serializers/helpers/appeal_hearing_helper.rb
  app/views/hearings/index.html.erb
  client/COPY.json
  client/app/components/FilterOption.jsx
  client/app/hearings/HearingsApp.jsx
  client/app/hearings/components/assignHearings/AssignHearings.jsx
  client/app/hearings/components/assignHearings/AssignHearingsDocketLine.jsx
  client/app/hearings/components/assignHearings/AssignHearingsFields.jsx
  client/app/hearings/components/assignHearings/AssignHearingsTable.jsx
  client/app/hearings/components/assignHearings/AssignHearingsTabs.jsx
  client/app/hearings/components/assignHearings/LinkToAppeal.jsx
  client/app/hearings/components/assignHearings/Messages.jsx
  client/app/hearings/components/assignHearings/UpcomingHearingsTable.jsx
  client/app/hearings/containers/AssignHearingsContainer.jsx
  client/app/queue/QueueTable.jsx
  client/app/queue/components/AssignHearingModal.jsx
  client/app/queue/components/CancelTaskModal.jsx
  client/app/queue/utils.js
  client/constants/QUEUE_CONFIG.json
  config/routes.rb
  spec/controllers/hearings/schedule_hearing_tasks_columns_controller_spec.rb
  spec/controllers/hearings/schedule_hearing_tasks_controller_spec.rb
  spec/controllers/tasks_controller_spec.rb
  spec/feature/hearings/change_hearing_disposition_spec.rb
  spec/feature/hearings/hearing_admin_action_foreign_veteran_case_task_spec.rb
  spec/feature/hearings/schedule_veteran/build_hearsched_spec.rb
  spec/models/hearings/schedule_hearing_task_pager_spec.rb
  spec/models/queue_filter_parameter_spec.rb
  spec/models/queue_tabs/assign_hearing_tab_spec.rb
  spec/models/queues/hearing_coordinator_schedule_queue_spec.rb
  spec/models/task_filter_spec.rb
Labels: Ready-to-Merge, tango

#13557 Add validations for Hearing Day
  app/models/hearing_day.rb
  spec/feature/hearings/edit_hearing_day_spec.rb
  spec/models/hearing_day_spec.rb
  spec/requests/hearing_day_spec.rb
Labels: Ready-to-Merge, caseflow-hearings, tango

#13588 Bat Team | Safe-navigate end products in legacy appeals with nil vet
  app/models/legacy_appeal.rb
Labels: Bug, Ready-to-Merge, batteam

#13569 Fix/skip Reader spec flakes
  app/controllers/annotation_controller.rb
  spec/feature/queue/ama_queue_spec.rb
  spec/feature/reader/reader_spec.rb
Labels: Flaky test, Ready-to-Merge

#13590 Set statement_timeout on source class connection
  app/services/etl/syncer.rb
Labels: Ready-to-Merge

#13587 Revert "Implement Pagination for Assign Hearings"
  .reek.yml
  app/controllers/hearings/schedule_hearing_tasks_columns_controller.rb
  app/controllers/hearings/schedule_hearing_tasks_controller.rb
  app/controllers/tasks_controller.rb
  app/models/hearings/schedule_hearing_task_pager.rb
  app/models/queue_filter_parameter.rb
  app/models/queue_tabs/assign_hearing_tab.rb
  app/models/queues/hearing_coordinator_schedule_queue.rb
  app/models/serializers/work_queue/appeal_serializer.rb
  app/models/serializers/work_queue/legacy_appeal_serializer.rb
  app/models/serializers/work_queue/task_serializer.rb
  app/models/task_filter.rb
  app/serializers/helpers/appeal_hearing_helper.rb
  app/views/hearings/index.html.erb
  client/COPY.json
  client/app/components/FilterOption.jsx
  client/app/hearings/HearingsApp.jsx
  client/app/hearings/components/assignHearings/AssignHearings.jsx
  client/app/hearings/components/assignHearings/AssignHearingsDocketLine.jsx
  client/app/hearings/components/assignHearings/AssignHearingsFields.jsx
  client/app/hearings/components/assignHearings/AssignHearingsTable.jsx
  client/app/hearings/components/assignHearings/AssignHearingsTabs.jsx
  client/app/hearings/components/assignHearings/LinkToAppeal.jsx
  client/app/hearings/components/assignHearings/Messages.jsx
  client/app/hearings/components/assignHearings/UpcomingHearingsTable.jsx
  client/app/hearings/containers/AssignHearingsContainer.jsx
  client/app/queue/QueueTable.jsx
  client/app/queue/components/AssignHearingModal.jsx
  client/app/queue/components/CancelTaskModal.jsx
  client/app/queue/utils.js
  client/constants/QUEUE_CONFIG.json
  config/routes.rb
  spec/controllers/hearings/schedule_hearing_tasks_columns_controller_spec.rb
  spec/controllers/hearings/schedule_hearing_tasks_controller_spec.rb
  spec/controllers/tasks_controller_spec.rb
  spec/feature/hearings/change_hearing_disposition_spec.rb
  spec/feature/hearings/hearing_admin_action_foreign_veteran_case_task_spec.rb
  spec/feature/hearings/schedule_veteran/build_hearsched_spec.rb
  spec/models/hearings/schedule_hearing_task_pager_spec.rb
  spec/models/queue_filter_parameter_spec.rb
  spec/models/queue_tabs/assign_hearing_tab_spec.rb
  spec/models/queues/hearing_coordinator_schedule_queue_spec.rb
  spec/models/task_filter_spec.rb
Labels: Ready-to-Merge

#13593 Add FK to schema docs
  db/migrate/20200303223649_fix_schema_todo_comment.rb
  db/schema.rb
  docs/schema/caseflow.csv
  docs/schema/etl.csv
  lib/tasks/doc.rake
Labels: Ready-to-Merge

#13595 Add etl.users.user_id index
  db/etl/migrate/20200303223155_add_etl_users_index.rb
  db/etl/schema.rb
Labels: Ready-to-Merge

#13561 Show correct virtual hearing link for judge
  client/app/hearings/utils.js
  spec/feature/hearings/virtual_hearings/daily_docket_spec.rb
Labels: Ready-to-Merge

#13608 Do not show completed hold for tasks that are on hold without an on hold duration
  client/app/queue/utils.js
  client/test/karma/queue/ColocatedTaskListView-test.js
Labels: Product: caseflow-queue, Ready-to-Merge, Team: Echo 🐬, Type: Bug, User: Attorney

#13618 Populate Theme ID for Pexip
  app/services/external_api/pexip_service.rb
  spec/services/external_api/pexip_service_spec.rb
Labels: Ready-to-Merge

#13621 RAMP | Allow new refiling intake if previous refiling EP was cancelled
  app/models/end_product_establishment.rb
  app/models/ramp_closed_appeal.rb
  app/models/ramp_election.rb
  app/models/ramp_election_rollback.rb
  app/models/ramp_refiling_intake.rb
  app/models/request_issue.rb
  spec/models/end_product_establishment_spec.rb
  spec/models/ramp_refiling_intake_spec.rb
Labels: Feature: RAMP, Product: caseflow-intake, Ready-to-Merge, Team: Foxtrot 🦊, Type: Bug

#13563 Oracle SYSDATE is UTC in CircleCI
  Makefile.example
  spec/models/legacy_appeal_spec.rb
Labels: Ready-to-Merge

#13629 Update schema doc for new users.user_id index
  docs/schema/etl.csv
Labels: Team: Delta 🔺

#13635 Fix space in footer text
  client/package.json
  client/yarn.lock
Labels: Eng: Frontend Work Group, Ready-to-Merge, Type: Bug

#13624 Set up hearings time check
  app/controllers/test/hearings_controller.rb
  app/helpers/test/hearings_profile_helper.rb
  app/jobs/test/hearings_profile_job.rb
  app/mailers/test/hearings_profile_mailer.rb
  config/routes.rb
  spec/controllers/test/hearings_controller_spec.rb
  spec/helpers/test/hearings_profile_helper_spec.rb
  spec/jobs/test/hearings_profile_job_spec.rb
  spec/mailers/test/hearings_profile_mailer_spec.rb
Labels: Ready-to-Merge, Team: Tango 💃

#13634 Upgrade connect_vbms: pagination fixes, small security warning
  Gemfile
  Gemfile.lock
Labels: Ready-to-Merge

#13628 LegacyAppeal.cached_vacols_case association
  app/models/legacy_appeal.rb
Labels: Ready-to-Merge

#13638 update from address for hearings time check emails
  app/mailers/test/hearings_profile_mailer.rb
Labels: Ready-to-Merge, Team: Tango 💃

#13631 More accurate hearings seed data; add VSO user that can access hearings
  db/seeds.rb
  lib/fakes/bgs_service.rb
  spec/factories/available_hearing_locations.rb
Labels: Ready-to-Merge, Team: Tango 💃

#13644 Reduce default hearing day range size for index_with_hearings
  app/controllers/hearings/hearing_day_controller.rb
  spec/feature/hearings/schedule_veteran/build_hearsched_spec.rb
  spec/requests/hearing_day_spec.rb
Labels: Ready-to-Merge, Team: Tango 💃

#13633 Motion to Vacate | Hide option to create VacateMotionMailTask until an appeal is outcoded
  app/controllers/post_decision_motions_controller.rb
  app/repositories/task_action_repository.rb
  spec/feature/queue/motion_to_vacate_spec.rb
  spec/feature/queue/task_queue_spec.rb
Labels: Priority: Medium, Product: caseflow-queue, Ready-to-Merge, Team: Foxtrot 🦊, Type: Bug

#13655 Change GovDelivery from email address
  app/mailers/virtual_hearing_mailer.rb
Labels: Feature: hearings-schedule, Ready-to-Merge, Team: Tango 💃

#12195 Hearing Task Association should only return a hearing if the vacols record exists
  app/models/concerns/has_hearing_task.rb
  app/models/hearing.rb
  app/models/legacy_hearing.rb
  app/models/task.rb
  app/models/task_extension_for_hearings.rb
  app/models/tasks/schedule_hearing_task.rb
Labels: Ready-to-Merge, Team: Tango 💃

#13632 Remove judge as a recipient for emails
  .reek.yml
  app/controllers/hearings_controller.rb
  app/jobs/virtual_hearings/send_email.rb
  app/mailers/virtual_hearing_mailer.rb
  app/models/hearings/forms/base_hearing_update_form.rb
  app/models/hearings/virtual_hearing.rb
  app/repositories/virtual_hearing_repository.rb
  app/services/virtual_hearing_user_alert_builder.rb
  app/services/virtual_hearings/calendar_service.rb
  app/views/virtual_hearing_mailer/_judge_confirmation.html.erb
  app/views/virtual_hearing_mailer/_judge_updated_time_confirmation.html.erb
  app/views/virtual_hearing_mailer/calendar_events/judge_confirmation_event_description.text.erb
  app/views/virtual_hearing_mailer/confirmation.html.erb
  app/views/virtual_hearing_mailer/updated_time_confirmation.html.erb
  client/COPY.json
  db/migrate/20200305220025_remove_judge_email_and_judge_email_sent_from_virtual_hearings.rb
  db/schema.rb
  docs/schema/caseflow.csv
  spec/controllers/hearings_controller_spec.rb
  spec/factories/virtual_hearing.rb
  spec/feature/hearings/virtual_hearings/hearing_details_spec.rb
  spec/jobs/virtual_hearings/create_conference_job_spec.rb
  spec/jobs/virtual_hearings/delete_conferences_job_spec.rb
  spec/mailers/virtual_hearing_mailer_spec.rb
Labels: Product: caseflow-hearings, Ready-to-Merge, Team: Tango 💃

#13643 Motion to Vacate | Frontend clean-up
  client/COPY.json
  client/app/components/CheckboxGroup.jsx
  client/app/components/TextareaField.jsx
  client/app/queue/InstructionalText.jsx
  client/app/queue/mtv/MTVIssueSelection.jsx
  client/app/queue/mtv/MTVJudgeDisposition.jsx
  client/app/queue/mtv/MotionsAttorneyDisposition.jsx
  client/app/queue/mtv/SubmitVacatedDecisionsView.jsx
  spec/feature/queue/motion_to_vacate_spec.rb
Labels: Ready-to-Merge

#13650 Intake | Use intake user to set station of jurisdiction
  app/models/decision_review.rb
  spec/feature/intake/higher_level_review_spec.rb
  spec/feature/intake/supplemental_claim_spec.rb
  spec/models/claim_review_spec.rb
  spec/models/higher_level_review_intake_spec.rb
  spec/models/supplemental_claim_intake_spec.rb
Labels: Priority: Medium, Product: caseflow-intake, Ready-to-Merge, Team: Foxtrot 🦊, Type: Bug

#13651 Intake | Use last_synced_at when an EP's last action date is missing
  app/models/end_product_establishment.rb
  app/models/request_issue.rb
  spec/models/end_product_establishment_spec.rb
Labels: Priority: Medium, Product: caseflow-intake, Ready-to-Merge, Team: Foxtrot 🦊, Type: Bug

#13666 Better error handling in establish claim CancelModal
  client/app/establishClaim/components/CancelModal.jsx
Labels: Ready-to-Merge, Team: Foxtrot 🦊

#13674 Added RAMP Code: 683HAERRAMP
  app/models/end_product.rb
  client/constants/END_PRODUCT_CODES.json
Labels: Feature: RAMP, Ready-to-Merge, Source: Bat Team, Team: Foxtrot 🦊

#13675 Adding updated ruby-bgs gem to gemfile
  Gemfile
  Gemfile.lock
  app/services/external_api/bgs_service.rb
Labels: Ready-to-Merge

#13672 Motion to Vacate | Update copy for jurisdictional conflict
  client/COPY.json
  client/constants/TASK_ACTIONS.json
  client/test/karma/queue/mtv/sample.js
Labels: Priority: Medium, Ready-to-Merge, Stakeholder: BVA, Team: Foxtrot 🦊, Type: Bug

#13620 Fix dislocated parent tasks in FactoryBot - Part 5
  spec/controllers/tasks_controller_spec.rb
  spec/factories/task.rb
  spec/feature/queue/ama_queue_spec.rb
  spec/feature/queue/attorney_checkout_flow_spec.rb
  spec/feature/queue/case_details_spec.rb
  spec/feature/queue/judge_checkout_flow_spec.rb
  spec/feature/queue/task_queue_spec.rb
  spec/feature/withdrawn_request_issues_spec.rb
  spec/jobs/fetch_documents_for_reader_user_spec.rb
  spec/models/queue_tabs/organization_assigned_tasks_tab_spec.rb
  spec/models/queue_tabs/organization_on_hold_tasks_tab_spec.rb
  spec/models/queues/attorney_queue_spec.rb
  spec/models/task_pager_spec.rb
  spec/models/task_sorter_spec.rb
  spec/models/task_spec.rb
  spec/models/tasks/colocated_task_spec.rb
  spec/workflows/bulk_task_reassignment_spec.rb
  spec/workflows/fetch_documents_for_reader_spec.rb
Labels: Eng: Backend Work Group, Priority: Low, Team: Echo 🐬, Type: Tech-Improvement

#13607 Fix dislocated parent tasks in FactoryBot - Part 4
  spec/controllers/judge_assign_tasks_controller_spec.rb
  spec/controllers/tasks_controller_spec.rb
  spec/factories/task.rb
  spec/feature/queue/ama_queue_spec.rb
  spec/feature/queue/attorney_checkout_flow_spec.rb
  spec/feature/queue/case_details_spec.rb
  spec/feature/queue/judge_checkout_flow_spec.rb
  spec/feature/queue/task_queue_spec.rb
  spec/feature/withdrawn_request_issues_spec.rb
  spec/jobs/fetch_documents_for_reader_user_spec.rb
  spec/jobs/hearing_disposition_change_job_spec.rb
  spec/models/queue_tabs/organization_assigned_tasks_tab_spec.rb
  spec/models/queue_tabs/organization_on_hold_tasks_tab_spec.rb
  spec/models/queues/attorney_queue_spec.rb
  spec/models/task_pager_spec.rb
  spec/models/task_sorter_spec.rb
  spec/models/task_spec.rb
  spec/models/tasks/colocated_task_spec.rb
  spec/workflows/bulk_task_reassignment_spec.rb
  spec/workflows/fetch_documents_for_reader_spec.rb
Labels: Eng: Backend Work Group, Priority: Low, Team: Echo 🐬, Type: Tech-Improvement

#13606 Fix dislocated parent tasks in FactoryBot - Part 3
  spec/controllers/judge_assign_tasks_controller_spec.rb
  spec/controllers/tasks_controller_spec.rb
  spec/factories/task.rb
  spec/feature/queue/ama_queue_spec.rb
  spec/feature/queue/attorney_checkout_flow_spec.rb
  spec/feature/queue/case_details_spec.rb
  spec/feature/queue/judge_checkout_flow_spec.rb
  spec/feature/queue/task_queue_spec.rb
  spec/feature/withdrawn_request_issues_spec.rb
  spec/jobs/fetch_documents_for_reader_user_spec.rb
  spec/jobs/hearing_disposition_change_job_spec.rb
  spec/models/queue_tabs/organization_assigned_tasks_tab_spec.rb
  spec/models/queue_tabs/organization_on_hold_tasks_tab_spec.rb
  spec/models/queues/attorney_queue_spec.rb
  spec/models/task_pager_spec.rb
  spec/models/task_sorter_spec.rb
  spec/models/task_spec.rb
  spec/models/tasks/colocated_task_spec.rb
  spec/workflows/bulk_task_reassignment_spec.rb
  spec/workflows/fetch_documents_for_reader_spec.rb
Labels: Eng: Backend Work Group, Priority: Low, Team: Echo 🐬, Type: Tech-Improvement

#13605 Fix dislocated parent tasks in FactoryBot - Part 2
  spec/controllers/judge_assign_tasks_controller_spec.rb
  spec/controllers/tasks_controller_spec.rb
  spec/factories/task.rb
  spec/feature/queue/ama_queue_spec.rb
  spec/feature/queue/attorney_checkout_flow_spec.rb
  spec/feature/queue/case_details_spec.rb
  spec/feature/queue/judge_checkout_flow_spec.rb
  spec/feature/queue/task_queue_spec.rb
  spec/feature/withdrawn_request_issues_spec.rb
  spec/jobs/fetch_documents_for_reader_user_spec.rb
  spec/jobs/hearing_disposition_change_job_spec.rb
  spec/models/queue_tabs/organization_assigned_tasks_tab_spec.rb
  spec/models/queue_tabs/organization_on_hold_tasks_tab_spec.rb
  spec/models/queues/attorney_queue_spec.rb
  spec/models/task_pager_spec.rb
  spec/models/task_sorter_spec.rb
  spec/models/task_spec.rb
  spec/models/tasks/colocated_task_spec.rb
  spec/workflows/bulk_task_reassignment_spec.rb
  spec/workflows/fetch_documents_for_reader_spec.rb
Labels: Eng: Backend Work Group, Priority: Low, Team: Echo 🐬, Type: Tech-Improvement

#13677 [Hearings Pagination] Move calculation of docket line index to the back end - Part 4
  app/controllers/hearings/schedule_hearing_tasks_controller.rb
  app/models/hearings/schedule_hearing_task_pager.rb
  client/app/hearings/components/assignHearings/AssignHearingsDocketLine.jsx
  client/app/hearings/components/assignHearings/AssignHearingsTable.jsx
  spec/controllers/hearings/schedule_hearing_tasks_controller_spec.rb
  spec/factories/appeal.rb
  spec/feature/hearings/schedule_veteran/build_hearsched_spec.rb
  spec/models/hearings/schedule_hearing_task_pager_spec.rb
Labels: Team: Tango 💃

#13649 [Hearings Pagination] Update QueueTable to use pipe character as value delimiter - Part 3
  app/controllers/hearings/schedule_hearing_tasks_controller.rb
  app/models/hearings/schedule_hearing_task_pager.rb
  app/models/queue_filter_parameter.rb
  app/models/task_filter.rb
  client/app/hearings/components/assignHearings/AssignHearingsDocketLine.jsx
  client/app/hearings/components/assignHearings/AssignHearingsTable.jsx
  client/app/queue/QueueTable.jsx
  spec/controllers/hearings/schedule_hearing_tasks_controller_spec.rb
  spec/factories/appeal.rb
  spec/feature/hearings/schedule_veteran/build_hearsched_spec.rb
  spec/models/hearings/schedule_hearing_task_pager_spec.rb
  spec/models/queue_filter_parameter_spec.rb
  spec/models/task_filter_spec.rb
  spec/models/task_pager_spec.rb
Labels: Product: caseflow-hearings, Team: Tango 💃

#13648 [Hearings Pagination] Small refactors to initial PR - Part 2
  app/controllers/hearings/schedule_hearing_tasks_columns_controller.rb
  app/controllers/hearings/schedule_hearing_tasks_controller.rb
  app/models/hearings/schedule_hearing_task_pager.rb
  app/models/queue_filter_parameter.rb
  app/models/task_filter.rb
  client/app/hearings/components/assignHearings/AssignHearingsDocketLine.jsx
  client/app/hearings/components/assignHearings/AssignHearingsTable.jsx
  client/app/queue/QueueTable.jsx
  spec/controllers/hearings/schedule_hearing_tasks_controller_spec.rb
  spec/factories/appeal.rb
  spec/feature/hearings/schedule_veteran/build_hearsched_spec.rb
  spec/models/hearings/schedule_hearing_task_pager_spec.rb
  spec/models/queue_filter_parameter_spec.rb
  spec/models/task_filter_spec.rb
  spec/models/task_pager_spec.rb
Labels: Product: caseflow-hearings, Team: Tango 💃

#13602 [Hearings Pagination] Implement pagination for assign hearings (continued) - Part 1
  .reek.yml
  app/controllers/hearings/schedule_hearing_tasks_columns_controller.rb
  app/controllers/hearings/schedule_hearing_tasks_controller.rb
  app/controllers/tasks_controller.rb
  app/models/hearings/schedule_hearing_task_pager.rb
  app/models/queue_filter_parameter.rb
  app/models/queue_tabs/assign_hearing_tab.rb
  app/models/queues/hearing_coordinator_schedule_queue.rb
  app/models/serializers/work_queue/appeal_serializer.rb
  app/models/serializers/work_queue/legacy_appeal_serializer.rb
  app/models/serializers/work_queue/task_serializer.rb
  app/models/task_filter.rb
  app/serializers/helpers/appeal_hearing_helper.rb
  app/views/hearings/index.html.erb
  client/COPY.json
  client/app/components/FilterOption.jsx
  client/app/hearings/HearingsApp.jsx
  client/app/hearings/components/assignHearings/AssignHearings.jsx
  client/app/hearings/components/assignHearings/AssignHearingsDocketLine.jsx
  client/app/hearings/components/assignHearings/AssignHearingsFields.jsx
  client/app/hearings/components/assignHearings/AssignHearingsTable.jsx
  client/app/hearings/components/assignHearings/AssignHearingsTabs.jsx
  client/app/hearings/components/assignHearings/LinkToAppeal.jsx
  client/app/hearings/components/assignHearings/Messages.jsx
  client/app/hearings/components/assignHearings/UpcomingHearingsTable.jsx
  client/app/hearings/containers/AssignHearingsContainer.jsx
  client/app/queue/QueueTable.jsx
  client/app/queue/components/AssignHearingModal.jsx
  client/app/queue/components/CancelTaskModal.jsx
  client/app/queue/utils.js
  client/constants/QUEUE_CONFIG.json
  config/routes.rb
  spec/controllers/hearings/schedule_hearing_tasks_columns_controller_spec.rb
  spec/controllers/hearings/schedule_hearing_tasks_controller_spec.rb
  spec/controllers/tasks_controller_spec.rb
  spec/factories/appeal.rb
  spec/feature/hearings/change_hearing_disposition_spec.rb
  spec/feature/hearings/hearing_admin_action_foreign_veteran_case_task_spec.rb
  spec/feature/hearings/schedule_veteran/build_hearsched_spec.rb
  spec/models/hearings/schedule_hearing_task_pager_spec.rb
  spec/models/queue_filter_parameter_spec.rb
  spec/models/queue_tabs/assign_hearing_tab_spec.rb
  spec/models/queues/hearing_coordinator_schedule_queue_spec.rb
  spec/models/task_filter_spec.rb
  spec/models/task_pager_spec.rb
Labels: Ready-to-Merge

#13604 Fix dislocated parent tasks in FactoryBot - Part 1
  spec/controllers/judge_assign_tasks_controller_spec.rb
  spec/controllers/tasks_controller_spec.rb
  spec/factories/task.rb
  spec/feature/queue/ama_queue_spec.rb
  spec/feature/queue/attorney_checkout_flow_spec.rb
  spec/feature/queue/case_details_spec.rb
  spec/feature/queue/judge_checkout_flow_spec.rb
  spec/feature/queue/task_queue_spec.rb
  spec/feature/withdrawn_request_issues_spec.rb
  spec/jobs/fetch_documents_for_reader_user_spec.rb
  spec/jobs/hearing_disposition_change_job_spec.rb
  spec/models/queue_tabs/organization_assigned_tasks_tab_spec.rb
  spec/models/queue_tabs/organization_on_hold_tasks_tab_spec.rb
  spec/models/queues/attorney_queue_spec.rb
  spec/models/task_pager_spec.rb
  spec/models/task_sorter_spec.rb
  spec/models/task_spec.rb
  spec/models/tasks/colocated_task_spec.rb
  spec/workflows/bulk_task_reassignment_spec.rb
  spec/workflows/fetch_documents_for_reader_spec.rb
Labels: Eng: Backend Work Group, Priority: Low, Ready-to-Merge, Team: Echo 🐬, Type: Tech-Improvement

#13670 Avoid VACOLS calls on already scheduled veterans page - Part 2
  app/controllers/hearings/hearing_day_controller.rb
  spec/feature/hearings/schedule_veteran/build_hearsched_spec.rb
  spec/requests/hearing_day_spec.rb
Labels: Product: caseflow-hearings, Team: Tango 💃

#13668 Avoid VACOLS calls on already scheduled veterans page - Part 1
  app/controllers/hearings/hearing_day_controller.rb
  app/jobs/warm_bgs_caches_job.rb
  app/models/concerns/hearing_time_concern.rb
  app/models/hearing.rb
  app/models/legacy_hearing.rb
  app/serializers/hearings/hearing_for_hearing_day_serializer.rb
  app/serializers/hearings/hearing_serializer.rb
  app/services/hearing_day_range.rb
  client/app/components/DocketTypeBadge.jsx
  client/app/hearings/components/HearingTime.jsx
  client/app/hearings/components/assignHearings/AssignHearingsFields.jsx
  client/app/hearings/components/assignHearings/UpcomingHearingsTable.jsx
  client/app/hearings/components/dailyDocket/DailyDocketPrinted.jsx
  client/app/hearings/components/dailyDocket/DailyDocketRowDisplayText.jsx
  client/app/hearings/components/dailyDocket/DailyDocketRowInputs.jsx
  client/app/hearings/components/modalForms/HearingTime.jsx
  client/app/util/DateUtil.js
  spec/feature/hearings/schedule_veteran/build_hearsched_spec.rb
  spec/requests/hearing_day_spec.rb
  spec/services/hearing_day_range_spec.rb
Labels: Product: caseflow-hearings, Ready-to-Merge, Team: Tango 💃

#13690 Suggest stacked PRs for large pull requests
  Dangerfile
Labels: Ready-to-Merge

#13659 Revert "Remove judge as a recipient for emails"
  .reek.yml
  app/controllers/hearings_controller.rb
  app/jobs/virtual_hearings/send_email.rb
  app/mailers/virtual_hearing_mailer.rb
  app/models/hearings/forms/base_hearing_update_form.rb
  app/models/hearings/virtual_hearing.rb
  app/repositories/virtual_hearing_repository.rb
  app/services/virtual_hearing_user_alert_builder.rb
  app/services/virtual_hearings/calendar_service.rb
  app/views/virtual_hearing_mailer/_judge_confirmation.html.erb
  app/views/virtual_hearing_mailer/_judge_updated_time_confirmation.html.erb
  app/views/virtual_hearing_mailer/calendar_events/judge_confirmation_event_description.text.erb
  app/views/virtual_hearing_mailer/confirmation.html.erb
  app/views/virtual_hearing_mailer/updated_time_confirmation.html.erb
  client/COPY.json
  db/migrate/20200305220025_remove_judge_email_and_judge_email_sent_from_virtual_hearings.rb
  db/schema.rb
  docs/schema/caseflow.csv
  spec/controllers/hearings_controller_spec.rb
  spec/factories/virtual_hearing.rb
  spec/feature/hearings/virtual_hearings/hearing_details_spec.rb
  spec/jobs/virtual_hearings/create_conference_job_spec.rb
  spec/jobs/virtual_hearings/delete_conferences_job_spec.rb
  spec/mailers/virtual_hearing_mailer_spec.rb
Labels: Ready-to-Merge

#13713 Update Schedule Hearing Task Pagination Permissions
  app/controllers/hearings/schedule_hearing_tasks_columns_controller.rb
  app/controllers/hearings/schedule_hearing_tasks_controller.rb
Labels: Ready-to-Merge, Team: Tango 💃

#13673 Motion to Vacate | Set established_at when creating appeal streams
  app/models/appeal.rb
  spec/feature/queue/motion_to_vacate_spec.rb
  spec/models/appeal_spec.rb
Labels: Priority: Medium, Ready-to-Merge, Stakeholder: BVA, Team: Foxtrot 🦊, Type: Bug

#13636 Add missing rake task to Makefile
  .github/ISSUE_TEMPLATE/flaky-test-task.md
  Makefile.example
  spec/feature/intake/higher_level_review/edit_spec.rb
Labels: Ready-to-Merge, Team: Delta 🔺

#13640 Restructured LookupParticipantIdModal to Remove Redux Alerts
  client/COPY.json
  client/app/queue/LookupParticipantIdModal.jsx
  client/app/queue/LookupParticipantIdModal.module.scss
  client/app/queue/components/QueueFlowModal.jsx
Labels: Ready-to-Merge, Team: Foxtrot 🦊

#13706 Prevent multiple vacaturs from multiple submit clicks
  client/app/queue/mtv/AddressMotionToVacateView.jsx
Labels: Priority: Medium, Product: caseflow-queue, Ready-to-Merge, Stakeholder: BVA, Team: Foxtrot 🦊, Type: Bug

#13717 Fix constraint on non-duplicate org assignments in db seeds
  db/seeds.rb
Labels: Ready-to-Merge

#13639 Add Success Alert after ReviewMotionToVacateView
  client/COPY.json
  client/app/queue/mtv/ReviewMotionToVacateView.jsx
  client/app/queue/mtv/mtvActions.js
  client/app/queue/mtv/mtvMessages.js
  spec/feature/queue/motion_to_vacate_spec.rb
Labels: Ready-to-Merge, Team: Foxtrot 🦊

#13718 CSS ID must be unique in seeds
  db/seeds.rb
Labels: Ready-to-Merge

#13599 Fix flake
  spec/controllers/hearings/schedule_hearing_tasks_controller_spec.rb
Labels: Ready-to-Merge

#13723 Fix missing `end` for code block in seed data
  db/seeds.rb
Labels: Ready-to-Merge

#13187 Fix Hearing Time display on Virtual Hearing Emails
  app/controllers/application_controller.rb
  app/helpers/test/hearings_profile_helper.rb
  app/helpers/vacols_helper.rb
  app/mappers/hearing_mapper.rb
  app/models/hearing.rb
  app/models/legacy_hearing.rb
  app/models/vacols/record.rb
  app/services/hearing_time_service.rb
  app/views/virtual_hearing_mailer/sections/_date_time.html.erb
  spec/controllers/hearings_controller_spec.rb
  spec/controllers/home_controller_spec.rb
  spec/helpers/test/hearings_profile_helper_spec.rb
  spec/mailers/test/hearings_profile_mailer_spec.rb
  spec/mailers/virtual_hearing_mailer_spec.rb
  spec/mappers/hearing_mapper_spec.rb
  spec/services/hearing_time_service_spec.rb
Labels: Ready-to-Merge

#13728 Delete dangling Legacy Appeal records nightly
  .reek.yml
  app/jobs/nightly_syncs_job.rb
  app/services/data_integrity_checker.rb
  app/services/legacy_appeals_with_no_vacols_case.rb
  spec/jobs/nightly_syncs_job_spec.rb
  spec/services/legacy_appeals_with_no_vacols_case_spec.rb
Labels: Ready-to-Merge, Team: Echo 🐬

#13682 Implement MTV return-to-judge backend endpoint
  app/controllers/post_decision_motions_controller.rb
  app/models/appeal.rb
  app/workflows/post_decision_motion_deleter.rb
  config/routes.rb
  spec/controllers/post_decision_motions_controller_spec.rb
  spec/factories/appeal.rb
  spec/models/appeal_spec.rb
  spec/workflows/post_decision_motion_deleter_spec.rb
Labels: Ready-to-Merge, Stakeholder: BVA, Stakeholder: OIT, Team: Foxtrot 🦊

#13724 Change Pexip URL and theme
  app/models/hearings/virtual_hearing.rb
  app/services/external_api/pexip_service.rb
  client/app/hearings/components/VirtualHearingLink.jsx
  spec/services/external_api/pexip_service_spec.rb
Labels: Ready-to-Merge

#13739 Add judge_email and judge_email_sent columns to virtual hearings
  db/migrate/20200318204112_add_judge_email_and_judge_email_sent_to_virtual_hearings.rb
  db/schema.rb
Labels: Ready-to-Merge

#13740 Move Hearing and Intake tech specs from appeals-team
  docs/tech-specs/2018-05-18-hearing-schedule-schema.png
  docs/tech-specs/2018-05-18-hearing-schedule.md
  docs/tech-specs/2018-06-21-hearing-schedule-data-model.png
  docs/tech-specs/2018-06-21-vacols-caseflow-transition.md
  docs/tech-specs/2018-08-16-slotting-veterans.md
  docs/tech-specs/2018-11-14-schedule-hearing-task.md
  docs/tech-specs/2018-11-16-co-parent-records-transition.md
  docs/tech-specs/2018-11-28-legacy-issue-establishment.md
  docs/tech-specs/2018-11-30-alternate-hearing-locations.md
  docs/tech-specs/2018-12-06-legacy-issue-optin-and-rollback.md
  docs/tech-specs/2019-01-28-hearing-task-flow.md
  docs/tech-specs/2019-01-28-hearing-task-flow.png
  docs/tech-specs/2019-04-11-hearing-prep-merge.md
  docs/tech-specs/2019-08-01-establish-930-corrections.md
  docs/tech-specs/2019-08-01-establish-930-corrections.png
Labels: Ready-to-Merge, Type: Documentation

#13742 judges always see the central office hearing time in virtual hearing emails
  app/views/virtual_hearing_mailer/sections/_date_time.html.erb
  spec/mailers/virtual_hearing_mailer_spec.rb
Labels: Product: caseflow-hearings, Ready-to-Merge, Team: Tango 💃

#13743 fix flaky test template
  .github/ISSUE_TEMPLATE/design-task.md
  .github/ISSUE_TEMPLATE/echo-tech-spec.md
  .github/ISSUE_TEMPLATE/epic.md
  .github/ISSUE_TEMPLATE/flaky-test.md
  .security.yml
  Gemfile.lock
Labels: Ready-to-Merge

#13601 Motion to Vacate | Implement ReturnToJudge Flow (Frontend)
  app/controllers/post_decision_motions_controller.rb
  app/models/serializers/work_queue/task_serializer.rb
  app/workflows/post_decision_motion_deleter.rb
  client/COPY.json
  client/app/queue/mtv/MotionToVacateFlowContainer.jsx
  client/app/queue/mtv/ReviewVacatedDecisionIssuesView.jsx
  client/app/queue/mtv/motionToVacateRoutes.js
  client/app/queue/mtv/mtvMessages.js
  client/app/queue/mtv/returnToJudge/ReturnToJudgeAlert.jsx
  client/app/queue/mtv/returnToJudge/ReturnToJudgeModal.jsx
  client/app/queue/mtv/returnToJudge/ReturnToJudgeModalContainer.jsx
  client/constants/TASK_ACTIONS.json
  spec/feature/queue/motion_to_vacate_spec.rb
Labels: Ready-to-Merge, Team: Foxtrot 🦊

#13766 Add Sign In menu option on /help page
  app/controllers/application_controller.rb
  app/controllers/sessions_controller.rb
  spec/feature/certification/start_certification_spec.rb
  spec/feature/login_spec.rb
  spec/models/hearings/schedule_hearing_task_pager_spec.rb
Labels: Ready-to-Merge

#13741 Batteam | Add diagnostic code description
  client/constants/DIAGNOSTIC_CODE_DESCRIPTIONS.json
Labels: Product: caseflow-queue, Ready-to-Merge, Source: Bat Team

#13764 add conditional to migration
  db/migrate/20200318204112_add_judge_email_and_judge_email_sent_to_virtual_hearings.rb
Labels: Ready-to-Merge, Team: Tango 💃

#13758 Change session length to 12 hours
  config/initializers/session_store.rb
Labels: Ready-to-Merge

#13705 Add veteran state of residence to assign hearings table - Part 1
  app/controllers/hearings/schedule_hearing_tasks_controller.rb
  app/models/queue_tabs/assign_hearing_tab.rb
  app/models/serializers/work_queue/task_column_serializer.rb
  app/models/serializers/work_queue/task_serializer.rb
  client/app/components/DocketTypeBadge.jsx
  client/app/components/Pagination.jsx
  client/app/hearings/components/assignHearings/AssignHearingsFields.jsx
  client/app/hearings/components/assignHearings/AssignHearingsTable.jsx
  client/app/hearings/components/assignHearings/AssignHearingsTabs.jsx
  client/app/queue/CaseDetailsView.jsx
  client/app/queue/PowerOfAttorneyDetail.jsx
  client/app/queue/VeteranDetail.jsx
  client/app/queue/utils.js
Labels: Product: caseflow-hearings, Ready-to-Merge, Team: Tango 💃

#13767 Fix few virtual hearing related issues
  .reek.yml
  app/jobs/virtual_hearings/create_conference_job.rb
  app/jobs/virtual_hearings/delete_conferences_job.rb
  app/jobs/virtual_hearings/send_email.rb
  app/models/hearings/forms/base_hearing_update_form.rb
  app/services/external_api/pexip_service.rb
  app/services/external_api/pexip_service/response.rb
  spec/jobs/virtual_hearings/create_conference_job_spec.rb
  spec/jobs/virtual_hearings/delete_conferences_job_spec.rb
Labels: Ready-to-Merge

#13765 Updates re Hyperlink Field in MTV Deny/Dismiss Flow
  client/COPY.json
  client/app/queue/mtv/MTVJudgeDisposition.jsx
  client/app/queue/mtv/MotionsAttorneyDisposition.jsx
  client/app/queue/mtv/mtvConstants.js
  client/app/util/StringUtil.js
  spec/feature/queue/motion_to_vacate_spec.rb
  spec/support/queue_helpers.rb
Labels: Ready-to-Merge, Team: Foxtrot 🦊

#13772 Make hearing times in virtual hearings emails consistent
  .reek.yml
  app/helpers/virtual_hearings/calendar_template_helper.rb
  app/mailers/virtual_hearing_mailer.rb
  app/models/hearings/forms/base_hearing_update_form.rb
  app/services/virtual_hearings/calendar_service.rb
  app/views/virtual_hearing_mailer/_representative_location_changed.html.erb
  app/views/virtual_hearing_mailer/_veteran_location_changed.html.erb
  app/views/virtual_hearing_mailer/calendar_events/judge_confirmation_event_description.text.erb
  app/views/virtual_hearing_mailer/calendar_events/representative_changed_to_video_event_description.text.erb
  app/views/virtual_hearing_mailer/calendar_events/representative_confirmation_event_description.text.erb
  app/views/virtual_hearing_mailer/calendar_events/veteran_changed_to_video_event_description.text.erb
  app/views/virtual_hearing_mailer/calendar_events/veteran_confirmation_event_description.text.erb
  app/views/virtual_hearing_mailer/sections/_date_time.html.erb
  spec/jobs/virtual_hearings/send_email_spec.rb
  spec/mailers/virtual_hearing_mailer_spec.rb
Labels: Product: caseflow-hearings, Ready-to-Merge, Stakeholder: BVA, Team: Tango 💃

#13774 Remove redundant `appeal` parameter from FactoryBot.create call - Part 2
  db/seeds.rb
  spec/controllers/idt/api/appeals_controller_spec.rb
  spec/controllers/tasks/end_hold_controller_spec.rb
  spec/feature/queue/ama_queue_spec.rb
  spec/feature/queue/case_details_spec.rb
  spec/feature/queue/hearings_tasks_spec.rb
  spec/feature/queue/judge_assignment_spec.rb
  spec/feature/queue/motion_to_vacate_spec.rb
  spec/feature/queue/quality_review_flow_spec.rb
  spec/jobs/hearing_disposition_change_job_spec.rb
  spec/lib/tasks/fixes_spec.rb
  spec/models/appeal_spec.rb
  spec/models/legacy_appeal_spec.rb
  spec/models/task_spec.rb
  spec/models/tasks/assign_hearing_disposition_task_spec.rb
  spec/models/tasks/attorney_task_spec.rb
  spec/models/tasks/root_task_spec.rb
  spec/models/tasks/track_veteran_task_spec.rb
  spec/queries/appeals_with_no_tasks_or_all_tasks_on_hold_query_spec.rb
  spec/services/open_hearing_tasks_without_active_descendants_checker_spec.rb
  spec/services/open_tasks_with_closed_at_checker_spec.rb
  spec/services/stuck_appeals_checker_spec.rb
  spec/support/shared_examples/ama_sql.rb
Labels: Priority: Low, Team: Echo 🐬, Type: Tech-Improvement

#13773 Remove redundant `appeal` parameter from FactoryBot.create call
  db/seeds.rb
  spec/controllers/idt/api/appeals_controller_spec.rb
  spec/controllers/tasks/end_hold_controller_spec.rb
  spec/controllers/tasks_controller_spec.rb
  spec/controllers/test/hearings_controller_spec.rb
  spec/decorators/appeal_status_api_decorator_spec.rb
  spec/feature/hearings/change_hearing_disposition_spec.rb
  spec/feature/hearings/hearing_admin_action_foreign_veteran_case_task_spec.rb
  spec/feature/hearings/hearing_admin_action_verify_address_task_spec.rb
  spec/feature/hearings/postpone_hearing_spec.rb
  spec/feature/queue/ama_queue_spec.rb
  spec/feature/queue/case_details_spec.rb
  spec/feature/queue/hearings_tasks_spec.rb
  spec/feature/queue/judge_assignment_spec.rb
  spec/feature/queue/motion_to_vacate_spec.rb
  spec/feature/queue/quality_review_flow_spec.rb
  spec/feature/queue/task_queue_spec.rb
  spec/feature/queue/transcription_team_spec.rb
  spec/helpers/test/hearings_profile_helper_spec.rb
  spec/jobs/hearing_disposition_change_job_spec.rb
  spec/lib/tasks/fixes_spec.rb
  spec/models/appeal_spec.rb
  spec/models/concerns/task_tree_render_module_spec.rb
  spec/models/legacy_appeal_spec.rb
  spec/models/task_spec.rb
  spec/models/tasks/assign_hearing_disposition_task_spec.rb
  spec/models/tasks/attorney_task_spec.rb
  spec/models/tasks/bva_dispatch_task_spec.rb
  spec/models/tasks/change_hearing_disposition_task_spec.rb
  spec/models/tasks/evidence_submission_window_task_spec.rb
  spec/models/tasks/hearing_admin_action_foreign_veteran_case_task_spec.rb
  spec/models/tasks/hearing_admin_action_verify_address_task_spec.rb
  spec/models/tasks/hearing_task_spec.rb
  spec/models/tasks/mail_task_spec.rb
  spec/models/tasks/no_show_hearing_task_spec.rb
  spec/models/tasks/root_task_spec.rb
  spec/models/tasks/schedule_hearing_task_spec.rb
  spec/models/tasks/timed_hold_task_spec.rb
  spec/models/tasks/track_veteran_task_spec.rb
  spec/models/tasks/transcription_task_spec.rb
  spec/queries/appeals_with_no_tasks_or_all_tasks_on_hold_query_spec.rb
  spec/repositories/task_action_repository_spec.rb
  spec/serializers/status_serializer_spec.rb
  spec/services/open_hearing_tasks_without_active_descendants_checker_spec.rb
  spec/services/open_tasks_with_closed_at_checker_spec.rb
  spec/services/stuck_appeals_checker_spec.rb
  spec/support/shared_examples/ama_sql.rb
Labels: Priority: Low, Team: Echo 🐬, Type: Tech-Improvement

#13734 Improve make build target
  Makefile.example
Labels: Ready-to-Merge

#13757 Apply no_cache headers to all responses
  app/controllers/application_controller.rb
  spec/controllers/application_controller_spec.rb
Labels: Ready-to-Merge

#13760 Facols column update
  local/vacols/build_push.sh
  local/vacols/vacols_copy_2_tables_dev.sql
  local/vacols/vacols_copy_2_tables_test.sql
  local/vacols/vacols_copy_4_triggers_dev.sql
  local/vacols/vacols_copy_4_triggers_test.sql
Labels: Ready-to-Merge

#13776 Add metrics to delete conferences job
  app/jobs/virtual_hearings/delete_conferences_job.rb
  app/services/data_dog_service.rb
  client/constants/DATADOG_METRICS.json
  spec/jobs/virtual_hearings/delete_conferences_job_spec.rb
Labels: Ready-to-Merge, Team: Tango 💃

#13788 Handle null veteran address in VeteranDetail
  client/app/queue/VeteranDetail.jsx
Labels: Ready-to-Merge, Team: Tango 💃

#13771 Intake | Add decision dates to request issues in seeds for demo
  db/seeds.rb
Labels: Ready-to-Merge, Team: Foxtrot 🦊

#13792 Add request_issues indices for slow query
  db/migrate/20200325200232_add_missing_request_issue_indices.rb
  db/migrate/20200325211113_add_distribution_indices.rb
  db/schema.rb
  docs/schema/caseflow.csv
  spec/feature/intake/supplemental_claim/edit_spec.rb
Labels: Ready-to-Merge

#13799 Add indices to decision_issues
  db/migrate/20200326141733_add_decision_issue_indexes.rb
  db/schema.rb
  docs/schema/caseflow.csv
  spec/models/attorney_case_review_spec.rb
Labels: Ready-to-Merge, Team: Delta 🔺

#13787 Add validation to Special Issues page during checkout
  app/views/queue/index.html.erb
  client/COPY.json
  client/app/queue/SelectSpecialIssuesView.jsx
  spec/feature/queue/attorney_checkout_flow_spec.rb
Labels: Priority: Medium, Product: caseflow-queue, Ready-to-Merge, Stakeholder: BVA, Team: Echo 🐬, Type: Enhancement

#13789 Add logging of GovDelivery response to mailer
  app/controllers/appeals_controller.rb
  app/jobs/test/hearings_profile_job.rb
  app/jobs/virtual_hearings/delete_conferences_job.rb
  app/jobs/virtual_hearings/send_email.rb
  client/constants/DATADOG_METRICS.json
  config/environments/production.rb
  spec/jobs/test/hearings_profile_job_spec.rb
  spec/jobs/virtual_hearings/send_email_spec.rb
  spec/mailers/test/hearings_profile_mailer_spec.rb
  spec/mailers/virtual_hearing_mailer_spec.rb
Labels: Ready-to-Merge, Team: Tango 💃

#13797 Updates to ESLint & Related
  client/.eslintrc.js
  client/package.json
  client/yarn.lock
Labels: Ready-to-Merge, Team: Foxtrot 🦊

#13808 Use test mailer in development
  config/environments/development.rb
Labels: Product: caseflow-hearings, Ready-to-Merge, Team: Tango 💃

#13801 Handle NoMethodError in redistributed_case.rb
  app/services/redistributed_case.rb
  spec/models/redistributed_case_spec.rb
Labels: Priority: Low, Ready-to-Merge, Source: Sentry Alert, Team: Echo 🐬

#13810 Add COVID-19 timeliness exempt column
  db/migrate/20200327174629_add_covid_exempt_column.rb
  db/schema.rb
  docs/schema/caseflow.csv
Labels: Priority: High, Product: caseflow-intake, Ready-to-Merge, Source: AMO Reported, Team: Foxtrot 🦊, User: VBA Intake

#13802 Refactor common state in intake reducers
  app/models/intake.rb
  app/models/veteran.rb
  client/app/intake/reducers/appeal.js
  client/app/intake/reducers/common.js
  client/app/intake/reducers/higherLevelReview.js
  client/app/intake/reducers/intake.js
  client/app/intake/reducers/supplementalClaim.js
Labels: Ready-to-Merge, Team: Foxtrot 🦊, Type: Tech-Improvement

#13779 Add validation to claimant address
  app/models/decision_review_intake.rb
  app/models/validators/claimant_validator.rb
  client/app/intake/constants.js
  client/app/intake/util/index.js
  spec/feature/intake/review_page_spec.rb
  spec/models/validators/claimant_validator_spec.rb
Labels: Integration: VBMS, Priority: Medium, Product: caseflow-intake, Ready-to-Merge, Source: Upstream-error, Stakeholder: AMO, Team: Foxtrot 🦊

#13816 IDT only returns active Appeals
  app/controllers/idt/api/v1/appeals_controller.rb
  spec/controllers/idt/api/appeals_controller_spec.rb
Labels: Product: IDT, Ready-to-Merge, Team: Tango 💃

#13825 AuthenticatedControllerAction sets Raven current_user for APIs
  .security.yml
  Gemfile
  Gemfile.lock
  app/controllers/application_controller.rb
  app/controllers/concerns/authenticated_controller_action.rb
  app/controllers/idt/api/v1/base_controller.rb
  spec/controllers/idt/api/appeals_controller_spec.rb
Labels: Ready-to-Merge

#13820 Send data integrity check timings to DataDog
  app/jobs/data_integrity_checks_job.rb
  spec/jobs/data_integrity_checks_job_spec.rb
Labels: Ready-to-Merge

#13786 Allow SCM team members to move AMA cases
  .reek.yml
  app/models/tasks/attorney_task.rb
  app/models/tasks/judge_decision_review_task.rb
  app/models/tasks/judge_task.rb
  app/repositories/task_action_repository.rb
  app/workflows/attorney_task_creator.rb
  client/app/queue/AssignToAttorneyModalView.jsx
  client/app/queue/CaseDetailsLoadingScreen.jsx
  client/app/queue/QueueApp.jsx
  client/app/queue/components/AssignWidget.jsx
  spec/controllers/judge_assign_tasks_controller_spec.rb
  spec/controllers/post_decision_motions_controller_spec.rb
  spec/controllers/tasks_controller_spec.rb
  spec/factories/appeal.rb
  spec/feature/queue/colocated_task_queue_spec.rb
  spec/feature/queue/scm_judge_assignment_spec.rb
  spec/models/tasks/attorney_task_spec.rb
  spec/models/tasks/judge_task_spec.rb
Labels: Ready-to-Merge

#13822 Reduce BGS can_access cache to 2 hours
  app/services/external_api/bgs_service.rb
Labels: Ready-to-Merge

#13826 Include POST data in Sentry log
  config/initializers/sentry.rb
Labels: Ready-to-Merge

#13827 Add more request context to Raven errors
  app/controllers/api/application_controller.rb
  app/controllers/api/v2/appeals_controller.rb
  spec/feature/api/v2/appeals_spec.rb
Labels: Ready-to-Merge

#13828 Fix make reset
  Makefile.example
Labels: Ready-to-Merge

#13818 Allow CSS_ID in case assignment URL
  app/controllers/legacy_tasks_controller.rb
  client/app/queue/JudgeAssignTaskListView.jsx
  client/app/queue/QueueLoadingScreen.jsx
  client/app/queue/selectors.js
  client/app/queue/uiReducer/uiActions.js
  client/app/queue/uiReducer/uiConstants.js
  client/app/queue/uiReducer/uiReducer.js
  lib/caseflow/error.rb
  spec/controllers/legacy_tasks_controller_spec.rb
  spec/feature/queue/scm_judge_assignment_spec.rb
Labels: Priority: Medium, Product: caseflow-queue, Ready-to-Merge, Stakeholder: BVA, Team: Echo 🐬

#13829 LegacyAppeal has no /edit endpoint
  app/controllers/appeals_controller.rb
  spec/controllers/appeals_controller_spec.rb
Labels: Ready-to-Merge

#13770 Report RequestIssue stats to DataDog
  app/controllers/api/v1/jobs_controller.rb
  app/jobs/stats_collector_job.rb
  app/services/collectors/request_issues_stats_collector.rb
  spec/jobs/stats_collector_job_spec.rb
  spec/services/collectors/request_issues_stats_collector_spec.rb
Labels: Priority: Low, Ready-to-Merge, Team: Echo 🐬, Type: Metrics or Reporting

#13837 Fix Appeal API ArgumentError
  app/models/decision_review.rb
Labels: Ready-to-Merge, Team: Foxtrot 🦊

#13843 Migrate virtual hearings tech spec
  docs/tech-specs/2019-10-10-integrating-caseflow-with-pexip.md
Labels: Ready-to-Merge, Team: Tango 💃

#12428 Migrate task timer Looker view to data integrity checker
  .reek.yml
  app/jobs/data_integrity_checks_job.rb
  app/models/task_timer.rb
  app/queries/pending_incomplete_and_uncancelled_task_timers_query.rb
  app/services/pending_incomplete_and_uncancelled_task_timers_checker.rb
  app/sql/task-timer-looker.sql
  spec/factories/task_timer.rb
  spec/queries/pending_incomplete_and_uncancelled_task_timers_query_spec.rb
  spec/services/pending_incomplete_and_uncancelled_task_timers_checker_spec.rb
Labels: Ready-to-Merge, Team: Delta 🔺
