Repository department-of-veterans-affairs/caseflow, pull requests merged in 2020-06, with the labels that each got.

#13053 Search results for VSO users
  app/workflows/case_search_results_base.rb
  spec/feature/queue/search_spec.rb
Labels: Ready-to-Merge, User: VSO

#14360 Intake | Legacy opt-in | Form 10182 SOC/SSOC Timeliness Update
  app/models/legacy_appeal.rb
  spec/models/legacy_appeal_spec.rb
  spec/models/request_issue_spec.rb
  spec/support/intake_helpers.rb
Labels: Ready-to-Merge

#14429 Intake | Bug | Show non-rating issue description on legacy modal
  client/app/intake/components/AddIssueManager.jsx
  spec/feature/intake/add_issues_spec.rb
Labels: Product: caseflow-intake, Team: Foxtrot 🦊, Type: Bug

#14443 Don't throw error when validating nil doc id
  app/validators/legacy_attorney_case_review_document_id_validator.rb
  spec/models/queues/legacy_work_queue_spec.rb
Labels: Feature: case-details, Priority: Medium, Product: caseflow-queue, Ready-to-Merge, Stakeholder: BVA, Team: Echo 🐬, Type: Bug, User: AVLJ

#14437 Show errors in queue flow modal
  client/app/queue/CaseDetailsView.jsx
  client/app/queue/components/AssignToAttorneyWidget.jsx
  client/app/queue/components/QueueFlowModal.jsx
Labels: Ready-to-Merge

#14436 Clear assignees on cancel and submit
  client/app/queue/components/AssignToAttorneyWidget.jsx
  client/app/queue/uiReducer/uiActions.js
  client/app/queue/uiReducer/uiConstants.js
  client/app/queue/uiReducer/uiReducer.js
Labels: Ready-to-Merge

#14440 Show assignee name in success banner
  client/COPY.json
  client/app/queue/components/AssignToAttorneyWidget.jsx
  client/app/queue/reducers.js
  spec/feature/queue/ama_queue_spec.rb
  spec/feature/queue/judge_assignment_spec.rb
  spec/feature/queue/scm_judge_assignment_spec.rb
Labels: Ready-to-Merge

#14423 Query to find cancelled Root Tasks with completed Dispatch tasks
  app/queries/appeals_with_cancelled_root_task_completed_dispatch_query.rb
  spec/queries/appeals_with_cancelled_root_task_completed_dispatch_query_spec.rb
Labels: Ready-to-Merge

#14442 Show ScheduleHearingColocatedTask on case timeline
  app/models/tasks/schedule_hearing_colocated_task.rb
  db/seeds/tasks.rb
Labels: Ready-to-Merge

#14368 Add schema for IntakesController#review
  .reek.yml
  Gemfile
  Gemfile.lock
  app/controllers/concerns/validation_concern.rb
  app/controllers/intakes_controller.rb
  app/controllers/route_docs_controller.rb
  app/schemas/controller_schema.rb
  app/schemas/intakes_schemas.rb
  app/views/route_docs/index.html.erb
  client/app/intake/components/LegacyOptInApproved.jsx
  client/app/intake/pages/appeal/review.jsx
  client/app/intake/pages/higherLevelReview/review.jsx
  client/app/intake/pages/supplementalClaim/review.jsx
  config/routes.rb
  docs/tech-specs/2020-02-19-controller-schemas.md
Labels: Eng: Backend Work Group, Ready-to-Merge, Type: Tech-Improvement, Type: Tech-Spec

#14459 Acting judges: restore on-hold and completed tabs
  app/models/user.rb
Labels: Priority: High, Product: caseflow-queue, Ready-to-Merge, Type: Bug

#14374 Remove whitespace from emails
  app/models/hearings/forms/base_hearing_update_form.rb
  spec/controllers/hearings_controller_spec.rb
Labels: Ready-to-Merge

#14457 Fix hearing location bug
  app/models/hearing.rb
  app/models/hearing_location.rb
  app/models/hearings/forms/hearing_update_form.rb
  client/app/hearings/components/dailyDocket/DailyDocketRow.jsx
  spec/controllers/hearings_controller_spec.rb
  spec/models/hearing_location_spec.rb
Labels: Product: caseflow-hearings, Ready-to-Merge, Team: Tango 💃, Type: Bug

#14466 Rename constant for clarity
  app/models/rating.rb
Labels: Ready-to-Merge

#14463 No ETL sweeper alert unless more than 20 records affected
  app/jobs/etl_builder_job.rb
  spec/jobs/etl_builder_job_spec.rb
Labels: Ready-to-Merge, Team: Delta 🔺

#14458 [Part 3] Update layout of Hearing Details - Jest Tests
  client/jest.config.js
  client/package.json
  client/test/app/hearings/components/details/DetailsForm.test.js
  client/test/app/hearings/components/details/HearingLinks.test.js
  client/test/app/hearings/components/details/__snapshots__/DetailsForm.test.js.snap
  client/test/app/hearings/components/details/__snapshots__/HearingLinks.test.js.snap
  client/test/data/stores/hearingsStore.js
  client/test/data/user.js
  client/test/data/virtualHearings.js
  client/yarn.lock
Labels: Team: Tango 💃

#14449 [Part 2] Hearing Details Stories
  client/app/components/Accordion.stories.mdx
  client/app/components/ContentSection.stories.mdx
  client/app/components/TitleDetailsSubheader.stories.mdx
  client/app/hearings/components/details/DetailsHeader.stories.mdx
  client/app/hearings/components/details/EmailNotificationHistory.stories.mdx
  client/app/hearings/components/details/HearingLinks.stories.mdx
Labels: Team: Tango 💃

#14435 [Part 1] Update layout of Hearing Details
  client/COPY.json
  client/app/components/Accordion.jsx
  client/app/components/Accordion.stories.mdx
  client/app/components/ContentSection.jsx
  client/app/components/ContentSection.stories.mdx
  client/app/components/TextField.jsx
  client/app/components/TextField.stories.mdx
  client/app/components/TitleDetailsSubheader.jsx
  client/app/components/TitleDetailsSubheader.stories.mdx
  client/app/components/TitleDetailsSubheaderSection.jsx
  client/app/components/UserAlerts.jsx
  client/app/containers/StyleGuide/StyleGuideAccordions.jsx
  client/app/hearings/components/Details.jsx
  client/app/hearings/components/VirtualHearingLink.jsx
  client/app/hearings/components/details/DetailsForm.jsx
  client/app/hearings/components/details/DetailsHeader.jsx
  client/app/hearings/components/details/DetailsHeader.stories.mdx
  client/app/hearings/components/details/EmailNotificationHistory.jsx
  client/app/hearings/components/details/EmailNotificationHistory.stories.mdx
  client/app/hearings/components/details/HearingLinks.jsx
  client/app/hearings/components/details/HearingLinks.stories.mdx
  client/app/hearings/components/details/TranscriptionFormSection.jsx
  client/app/hearings/components/details/VirtualHearingForm.jsx
  client/app/hearings/components/details/style.jsx
  client/app/hearings/components/hearingWorksheet/HearingWorksheet.jsx
  client/app/hearings/components/hearingWorksheet/HearingWorksheetDocs.jsx
  client/app/queue/CaseTitleDetails.jsx
  client/app/reader/ClaimsFolderDetails.jsx
  client/app/reader/PdfSidebar.jsx
  client/app/styles/_commons.scss
  client/app/styles/_main.scss
  client/jest.config.js
  client/package.json
  client/test/app/hearings/components/details/DetailsForm.test.js
  client/test/app/hearings/components/details/HearingLinks.test.js
  client/test/app/hearings/components/details/__snapshots__/DetailsForm.test.js.snap
  client/test/app/hearings/components/details/__snapshots__/HearingLinks.test.js.snap
  client/test/data/stores/hearingsStore.js
  client/test/data/user.js
  client/test/data/virtualHearings.js
  client/yarn.lock
  spec/feature/hearings/virtual_hearings/hearing_details_spec.rb
Labels: Ready-to-Merge, Team: Tango 💃

#14379 v3 API - add `subject_text` and `percent_number` to DecisionIssue
  app/models/board_grant_effectuation.rb
  app/models/request_issue.rb
  db/etl/migrate/20200526054515_add_subject_text_and_percent_number_to_decision_issue.rb
  db/etl/schema.rb
  db/migrate/20200526054515_add_subject_text_and_percent_number_to_decision_issue.rb
  db/schema.rb
Labels: Ready-to-Merge

#14480 Remove build:storybook from build:production
  client/package.json
Labels: Ready-to-Merge, Team: Foxtrot 🦊

#14478 Fix issue with notes not being captured on add hearing day modal
  client/app/hearings/components/HearingDayAddModal.jsx
  client/app/hearings/reducers/hearingScheduleReducer.js
Labels: Ready-to-Merge, Team: Tango 💃

#14481 Add `build:demo` Script
  Dockerfile
  client/package.json
Labels: Ready-to-Merge, Team: Foxtrot 🦊

#14470 Intake | Bug | Add EP codes to validation
  app/models/end_product.rb
Labels: Team: Foxtrot 🦊, Type: Bug

#14482 Use Rails.current_env for DD reporting
  app/services/data_dog_service.rb
  config/initializers/deploy_env.rb
Labels: Ready-to-Merge

#14484 Revert "Revert "Updates to `AddClaimantModal` (#14202)""
  client/app/components/SearchableDropdown.jsx
  client/app/intake/components/AddClaimantModal.jsx
  client/app/intake/components/AddClaimantModal.stories.js
  client/app/intake/components/SelectClaimant.jsx
  client/babel.config.js
  client/package.json
  client/test/app/hearings/components/details/__snapshots__/DetailsForm.test.js.snap
  client/test/app/intake/components/AddClaimantModal.test.js
  client/test/app/intake/components/__snapshots__/AddClaimantModal.test.js.snap
  client/yarn.lock
  spec/feature/intake/intake_spec.rb
  spec/feature/intake/review_page_spec.rb
Labels: Ready-to-Merge, Team: Foxtrot 🦊

#14454 Fixed Debounce in `AddClaimantModal`
  client/app/intake/components/AddClaimantModal.jsx
  client/test/app/intake/components/AddClaimantModal.test.js
Labels: Ready-to-Merge, Team: Foxtrot 🦊

#14485 More graceful handling of possible undefined in `DailyDocketRow`
  client/app/hearings/components/dailyDocket/DailyDocketRow.jsx
Labels: Ready-to-Merge, Source: Sentry Alert, Team: Foxtrot 🦊

#13946 Add TimezoneService for address to timezone lookups
  Gemfile
  Gemfile.lock
  app/models/address.rb
  app/services/timezone_service.rb
  spec/services/timezone_service_spec.rb
Labels: Product: caseflow-hearings, Ready-to-Merge, Team: Tango 💃

#14494 add a make command to run storybook
  Makefile.example
Labels: Ready-to-Merge

#14448 [PART 1] Remove attorney task cancellation hook
  app/controllers/legacy_tasks_controller.rb
  app/models/task.rb
  app/models/tasks/attorney_task.rb
  app/models/tasks/judge_task.rb
  app/workflows/bulk_task_reassignment.rb
  client/app/queue/AssignToView.jsx
  client/app/queue/QueueActions.js
  client/app/queue/components/AssignToAttorneyWidget.jsx
  spec/controllers/legacy_tasks_controller_spec.rb
  spec/factories/user.rb
  spec/models/task_spec.rb
  spec/models/tasks/attorney_task_spec.rb
Labels: Ready-to-Merge

#14497 Default to empty string for instructions
  client/app/queue/components/AssignToAttorneyWidget.jsx
Labels: Ready-to-Merge

#14499 Fix error when receiving an empty hearing location payload for legacy hearings
  app/models/legacy_hearing.rb
Labels: Ready-to-Merge, Team: Tango 💃

#14496 Intake | Use iso8601 datetime for fetching ratings
  app/services/external_api/bgs_service.rb
Labels: Integration: BGS, Ready-to-Merge, Team: Foxtrot 🦊

#14469 Rake test to migrate virtual hearings data
  app/models/hearings/virtual_hearing.rb
  db/migrate/20200604191432_add_appellant_email_and_appellant_email_sent_to_virtual_hearings.rb
  db/schema.rb
  docs/schema/caseflow.csv
  lib/tasks/data_migrations.rake
  spec/feature/hearings/virtual_hearings/daily_docket_spec.rb
  spec/lib/tasks/data_migrations_spec.rb
Labels: Ready-to-Merge, Team: Tango 💃

#14418 Add time options to allow for 45 minute hearings
  client/app/hearings/components/dailyDocket/DailyDocketRow.jsx
  client/app/hearings/components/dailyDocket/DailyDocketRowInputs.jsx
  client/app/hearings/components/modalForms/AssignHearingForm.jsx
  client/app/hearings/components/modalForms/HearingTime.jsx
  client/app/hearings/components/modalForms/HearingTime.stories.mdx
  client/app/hearings/constants.js
  client/constants/HEARING_TIME_OPTIONS.json
  client/constants/HEARING_TIME_RADIO_OPTIONS.json
  client/test/app/hearings/components/modalForms/HearingTime.test.js
  client/test/app/hearings/components/modalForms/__snapshots__/HearingTime.test.js.snap
  spec/feature/hearings/schedule_veteran/build_hearsched_spec.rb
  spec/feature/hearings/virtual_hearings/daily_docket_spec.rb
Labels: Ready-to-Merge, Team: Tango 💃

#14510 Restrict bulk assign to admins of org
  app/controllers/organizations/tasks_controller.rb
  app/workflows/bulk_task_assignment.rb
  client/app/queue/OrganizationQueueLoadingScreen.jsx
  client/app/queue/QueueTableBuilder.jsx
  client/app/queue/uiReducer/uiActions.js
  client/app/queue/uiReducer/uiReducer.js
  spec/controllers/bulk_task_assignments_controller_spec.rb
  spec/controllers/organizations/tasks_controller_spec.rb
  spec/feature/queue/bulk_task_assignment_spec.rb
  spec/workflows/bulk_task_assignment_spec.rb
Labels: Ready-to-Merge

#14467 BVA | Intake | Legacy opt-in | Extend eligibility period that expires during a federal holiday
  app/models/legacy_appeal.rb
  spec/models/legacy_appeal_spec.rb
  spec/support/date_time_helper.rb
Labels: Ready-to-Merge

#14511 Add BGS method and job for syncing attorneys
  app/jobs/nightly_syncs_job.rb
  app/jobs/warm_bgs_caches_job.rb
  app/models/bgs_attorney.rb
  app/services/bgs_address_service.rb
  app/services/external_api/bgs_service.rb
  lib/fakes/bgs_service.rb
  spec/models/bgs_attorney_spec.rb
  spec/services/bgs_address_service_spec.rb
Labels: Ready-to-Merge

#14512 Added Caching of Associated Rating for EPE
  app/models/end_product_establishment.rb
  spec/models/end_product_establishment_spec.rb
Labels: Ready-to-Merge, Team: Foxtrot 🦊

#14487 Contested Claims | Attorney Fees | Migration to add type and notes to claimant table for unlisted claimants
  db/migrate/20200608165840_add_claimant_type_and_notes.rb
  db/migrate/20200610001554_backfill_claimant_type.rb
  db/schema.rb
  docs/schema/caseflow.csv
  docs/schema/etl.csv
Labels: Ready-to-Merge, Team: Foxtrot 🦊

#14520 Remove veteran_email and veteran_email_sent columns
  app/models/hearings/virtual_hearing.rb
  app/repositories/virtual_hearing_repository.rb
  db/migrate/20200611205900_remove_veteran_email_and_veteran_email_sent_from_virtual_hearings.rb
  db/schema.rb
  docs/schema/caseflow.csv
  lib/tasks/data_migrations.rake
  spec/controllers/hearings_controller_spec.rb
  spec/feature/hearings/virtual_hearings/daily_docket_spec.rb
  spec/feature/hearings/virtual_hearings/hearing_details_spec.rb
  spec/lib/tasks/data_migrations_spec.rb
Labels: Ready-to-Merge, Team: Tango 💃

#14517 Prefer BGS lookup by file number when updating existing POA
  app/models/bgs_power_of_attorney.rb
  spec/factories/bgs_power_of_attorney.rb
  spec/models/bgs_power_of_attorney_spec.rb
Labels: Ready-to-Merge

#14516 Enable screenreader to read success alerts
  client/app/components/Alert.jsx
  client/test/karma/components/Alert-test.js
Labels: Ready-to-Merge

#14384 Add BGS POA endpoint with use_poa_claimants feature
  .reek.yml
  app/mappers/power_of_attorney_mapper.rb
  app/services/external_api/bgs_service.rb
  spec/services/external_api/bgs_service_spec.rb
Labels: Ready-to-Merge

#14530 Add comment for legacy_hearings.vacols_id
  db/migrate/20200615153543_add_legacy_hearing_vacols_id_comment.rb
  db/schema.rb
  docs/schema/caseflow.csv
Labels: Ready-to-Merge

#14528 Cache finalized decision issues before receipt date on instance
  app/models/appeal.rb
  app/models/claim_review.rb
Labels: Priority: Medium, Product: caseflow-intake, Ready-to-Merge, Source: Bat Team, Team: Foxtrot 🦊

#14537 Update rack to 2.2.3
  Gemfile
  Gemfile.lock
Labels: Ready-to-Merge

#14535 Revert "Add time options to allow for 45 minute hearings"
  client/app/hearings/components/dailyDocket/DailyDocketRow.jsx
  client/app/hearings/components/dailyDocket/DailyDocketRowInputs.jsx
  client/app/hearings/components/modalForms/AssignHearingForm.jsx
  client/app/hearings/components/modalForms/HearingTime.jsx
  client/app/hearings/components/modalForms/HearingTime.stories.mdx
  client/app/hearings/constants.js
  client/constants/HEARING_TIME_OPTIONS.json
  client/constants/HEARING_TIME_RADIO_OPTIONS.json
  client/test/app/hearings/components/modalForms/HearingTime.test.js
  client/test/app/hearings/components/modalForms/__snapshots__/HearingTime.test.js.snap
  spec/feature/hearings/schedule_veteran/build_hearsched_spec.rb
  spec/feature/hearings/virtual_hearings/daily_docket_spec.rb
Labels: Ready-to-Merge, Team: Tango 💃

#14540 Revert "Revert "Add time options to allow for 45 minute hearings""
  client/app/hearings/components/dailyDocket/DailyDocketRow.jsx
  client/app/hearings/components/dailyDocket/DailyDocketRowInputs.jsx
  client/app/hearings/components/modalForms/AssignHearingForm.jsx
  client/app/hearings/components/modalForms/HearingTime.jsx
  client/app/hearings/components/modalForms/HearingTime.stories.mdx
  client/app/hearings/constants.js
  client/constants/HEARING_TIME_OPTIONS.json
  client/constants/HEARING_TIME_RADIO_OPTIONS.json
  client/test/app/hearings/components/modalForms/HearingTime.test.js
  client/test/app/hearings/components/modalForms/__snapshots__/HearingTime.test.js.snap
  spec/feature/hearings/schedule_veteran/build_hearsched_spec.rb
  spec/feature/hearings/virtual_hearings/daily_docket_spec.rb
Labels: Ready-to-Merge

#14539 Shalliburton/fix saving hearing time
  client/app/hearings/components/dailyDocket/DailyDocketRows.jsx
Labels: Ready-to-Merge

#14536 Add Sentry event id to UpdateCachedAppealsAttributesJob alert
  app/jobs/update_cached_appeals_attributes_job.rb
  spec/jobs/update_cached_appeals_attributes_job_spec.rb
Labels: Ready-to-Merge, Source: Bat Team, Source: Sentry Alert, Type: Tech-Improvement

#14534 Relabel SCMTask in Queue table
  app/models/tasks/special_case_movement_task.rb
  client/COPY.json
  spec/feature/queue/special_case_movement_task_spec.rb
  spec/models/tasks/distribution_task_spec.rb
  spec/models/tasks/judge_task_spec.rb
  spec/models/tasks/special_case_movement_spec.rb
Labels: Feature: queue-table-view, Priority: Medium, Product: caseflow-queue, Ready-to-Merge, Stakeholder: BVA, Team: Echo 🐬

#14523 Enable bulk assign for test orgs
  app/models/organizations/mail_team.rb
  app/models/organizations/privacy_team.rb
  app/models/organizations/transcription_team.rb
  app/models/organizations/vso.rb
  spec/workflows/bulk_task_assignment_spec.rb
Labels: Ready-to-Merge

#14544 Remove volatile updated_at version from EPE cache key
  app/models/end_product_establishment.rb
  spec/models/end_product_establishment_spec.rb
Labels: Eng: Performance, Product: caseflow-intake, Ready-to-Merge, Source: Bat Team, Team: Foxtrot 🦊

#14532 Remove extra tab stops in Reader Document View
  client/app/reader/PdfFile.jsx
  client/app/styles/react/_search_bar.scss
  spec/feature/reader/reader_spec.rb
Labels: Product: caseflow-reader, Ready-to-Merge, Team: Echo 🐬, Type: Accessibility

#14533 Intake | Add Error Classes | Update Gemfile and Gemfile.lock
  Gemfile
  Gemfile.lock
Labels: Ready-to-Merge, Source: Upstream-error, Team: Foxtrot 🦊

#14547 Contested Claims | Attorney Fees | Migration to add notes to claimant table for unlisted claimants
  db/migrate/20200617160206_add_notes_to_claimants.rb
  db/schema.rb
  docs/schema/caseflow.csv
Labels: Ready-to-Merge

#14527 Fix nil veteran for emails
  .reek.yml
  app/helpers/virtual_hearings/appellant_name_helper.rb
  app/helpers/virtual_hearings/veteran_name_helper.rb
  app/mailers/virtual_hearing_mailer.rb
  app/models/concerns/appeal_concern.rb
  app/repositories/virtual_hearing_repository.rb
  app/services/stuck_virtual_hearings_checker.rb
  app/services/virtual_hearing_user_alert_builder.rb
  app/services/virtual_hearings/calendar_service.rb
  app/views/virtual_hearing_mailer/_judge_confirmation.html.erb
  app/views/virtual_hearing_mailer/_judge_updated_time_confirmation.html.erb
  app/views/virtual_hearing_mailer/_representative_confirmation.html.erb
  app/views/virtual_hearing_mailer/_representative_location_changed.html.erb
  app/views/virtual_hearing_mailer/_representative_updated_time_confirmation.html.erb
  app/views/virtual_hearing_mailer/calendar_events/judge_confirmation_event_description.text.erb
  app/views/virtual_hearing_mailer/calendar_events/representative_changed_to_video_event_description.text.erb
  app/views/virtual_hearing_mailer/calendar_events/representative_confirmation_event_description.text.erb
  spec/repositories/virtual_hearing_repository_spec.rb
  spec/services/stuck_virtual_hearings_checker_spec.rb
Labels: Product: caseflow-hearings, Ready-to-Merge, Team: Tango 💃, Type: Bug

#14552 Fix Raven error when logging stats collector exceptions
  app/jobs/stats_collector_job.rb
  spec/jobs/stats_collector_job_spec.rb
Labels: Ready-to-Merge, Source: Bat Team, Source: Sentry Alert, Type: Bug

#14566 [PART 1] Fix 'param is missing or the value is empty: tasks'
  app/controllers/bulk_task_assignments_controller.rb
  app/models/tasks/transcription_task.rb
  client/app/queue/OrganizationQueue.jsx
  client/app/queue/QueueActions.js
  client/app/queue/QueueApp.jsx
  client/app/queue/components/BulkAssignModal.jsx
  client/app/queue/components/TaskTable.jsx
  client/app/queue/constants.js
  client/app/queue/reducers.js
  client/app/queue/uiReducer/uiActions.js
  spec/controllers/bulk_task_assignments_controller_spec.rb
  spec/models/tasks/transcription_task_spec.rb
Labels: Feature: generic-queue, Priority: High, Product: caseflow-queue, Team: Echo 🐬, Type: Bug, User: VSO

#14569 Fix undefined method update_vacols_location for nil:NilClass on dangling legacy appeals
  app/jobs/nightly_syncs_job.rb
  spec/jobs/nightly_syncs_job_spec.rb
Labels: Priority: Medium, Stakeholder: BVA, Team: Tango 💃, Type: Bug

#14570 Workaround VA SSL CA cert bug
  .reek.yml
  app/services/slack_service.rb
  spec/services/slack_service_spec.rb
Labels: Ready-to-Merge

#14571 Update issue sync error copy
  app/models/concerns/issue_updater.rb
  lib/caseflow/error.rb
Labels: Feature: caseflow-decisions, Ready-to-Merge, Type: content ✍🏽

#14567 Add flaky test debug
  spec/factories/document.rb
  spec/jobs/prepare_establish_claim_tasks_job_spec.rb
Labels: Ready-to-Merge

#14545 Add schema for intakes#create
  app/controllers/intakes_controller.rb
  app/schemas/controller_schema.rb
  app/schemas/intakes_schemas.rb
Labels: Ready-to-Merge, Type: Tech-Improvement

#14572 Fix TypeError vetNameFromAppeal(app/queue/AssignToView) on veteran info 500
  client/app/queue/AssignToView.jsx
Labels: Product: caseflow-queue, Ready-to-Merge, Source: Sentry Alert

#14583 Add benefit type validation on when adding decision issues
  client/app/queue/SelectDispositionsView.jsx
Labels: Feature: caseflow-decisions, Priority: Medium, Product: caseflow-queue, Ready-to-Merge, Source: Sentry Alert, Type: Bug, User: Attorney, User: Judge

#14578 Remove case from judge and attorney queue when scheduling hearing
  app/models/tasks/colocated_task.rb
  app/models/tasks/schedule_hearing_colocated_task.rb
  spec/feature/queue/task_queue_spec.rb
  spec/models/tasks/schedule_hearing_colocated_task_spec.rb
Labels: Ready-to-Merge

#14581 Set Sentry application for PostDecisionMotions endpoints
  app/controllers/post_decision_motions_controller.rb
Labels: Ready-to-Merge, Source: Bat Team, Source: Sentry Alert, Type: Tech-Improvement

#14565 Contested Claims | Attorney Fees | Add ‘Claimant not listed’ selection when attorney is not available
  app/models/appeal_intake.rb
  client/COPY.json
  client/app/intake/actions/decisionReview.js
  client/app/intake/components/AddClaimantModal.jsx
  client/app/intake/components/SelectClaimant.jsx
  client/app/intake/reducers/appeal.js
  client/app/intake/util/index.js
  client/test/app/intake/components/__snapshots__/AddClaimantModal.test.js.snap
  spec/feature/intake/review_page_spec.rb
  spec/models/appeal_intake_spec.rb
Labels: Ready-to-Merge

#14593 Include AppealConcern for AMA Appeal
  app/helpers/virtual_hearings/appellant_name_helper.rb
  app/models/appeal.rb
  app/models/concerns/appeal_concern.rb
  app/models/legacy_hearing.rb
  spec/models/appeal_spec.rb
  spec/models/concerns/appeal_concern_spec.rb
Labels: Ready-to-Merge

#14590 v3 API - Remove Veteran Address Fields
  app/controllers/api/docs/v3/decision_reviews.yaml
  app/services/api/v3/decision_review/higher_level_review_intake_params.rb
  spec/services/api/v3/decision_review/higher_level_review_intake_params_spec.rb
Labels: Integration: Lighthouse, Ready-to-Merge

#14588 Motion to Vacate | Bug | Fetch request issues through association
  app/models/post_decision_motion.rb
Labels: Ready-to-Merge, Team: Foxtrot 🦊, Type: Bug

#14550 Add documentation for VA.gov Service
  app/services/external_api/va_dot_gov_service.rb
Labels: Ready-to-Merge, Team: Tango 💃

#14607 Add ruby-prof gem for performance profiling
  Gemfile
  Gemfile.lock
  config/application.rb
Labels: Ready-to-Merge, Type: Tech-Improvement

#14529 Accessibility | Building New, Accessible Tab Components
  client/.eslintrc.js
  client/.storybook/main.js
  client/.storybook/webpack.config.js
  client/app/components/TabWindow.jsx
  client/app/components/tabs/Tab.jsx
  client/app/components/tabs/TabContainer.jsx
  client/app/components/tabs/TabContent.jsx
  client/app/components/tabs/TabContext.js
  client/app/components/tabs/TabItem.jsx
  client/app/components/tabs/TabList.jsx
  client/app/components/tabs/TabPanel.jsx
  client/app/components/tabs/Tabs.jsx
  client/app/components/tabs/Tabs.module.scss
  client/app/components/tabs/Tabs.stories.js
  client/app/styles/react/_tabs.scss
  client/package.json
  client/test/app/components/TabWindow.test.js
  client/test/app/components/__snapshots__/TabWindow.test.js.snap
  client/test/app/components/tabs/Tabs.test.js
  client/test/app/components/tabs/__snapshots__/Tabs.test.js.snap
  client/test/app/jestSetup.js
  client/test/karma/components/TabWindow-test.js
  client/test/karma/queue/ColocatedTaskListView-test.js
  client/webpack.config.js
  client/yarn.lock
Labels: Ready-to-Merge, Team: Foxtrot 🦊, Type: Accessibility

#14606 Resuce RecordNotUniqueError in UpdateCachedAppealsAttributesJob
  app/jobs/update_cached_appeals_attributes_job.rb
  spec/jobs/update_cached_appeals_attributes_job_spec.rb
Labels: Ready-to-Merge

#14586 Revert "Sentry alert for reader document count mismatch"
  app/controllers/reader/documents_controller.rb
  app/services/document_fetcher.rb
  spec/controllers/reader/documents_controller_spec.rb
Labels: Priority: Medium, Product: caseflow-reader, Ready-to-Merge, Source: Sentry Alert, Team: Echo 🐬

#14548 Change from email address and add alias
  app/mailers/test/hearings_profile_mailer.rb
  app/mailers/virtual_hearing_mailer.rb
Labels: Ready-to-Merge, Team: Tango 💃

#14610 Fix Styling Issue with Tab Panels
  client/app/components/tabs/Tabs.module.scss
Labels: Ready-to-Merge, Team: Foxtrot 🦊, Type: Bug

#14556 Add new timezone and hearing time dropdown components
  .circleci/config.yml
  client/app/constants/AppConstants.js
  client/app/hearings/components/VirtualHearings/HearingTime.jsx
  client/app/hearings/components/VirtualHearings/HearingTime.stories.mdx
  client/app/hearings/components/VirtualHearings/Timezone.jsx
  client/app/hearings/components/VirtualHearings/Timezone.stories.mdx
  client/app/hearings/components/details/style.jsx
  client/app/hearings/utils.js
  client/constants/TIMEZONES.json
  client/jest.config.js
  client/test/app/hearings/components/VirtualHearings/HearingTime.test.js
  client/test/app/hearings/components/VirtualHearings/Timezone.test.js
  client/test/app/hearings/components/VirtualHearings/__snapshots__/Timezone.test.js.snap
Labels: Ready-to-Merge

#14594 Improve Performance of Daily Docket Page
  app/models/hearing.rb
  app/models/legacy_hearing.rb
  app/serializers/hearings/hearing_serializer.rb
  app/serializers/hearings/legacy_hearing_serializer.rb
  client/app/hearings/actions/dailyDocketActions.js
  client/app/hearings/components/dailyDocket/DailyDocketRowDisplayText.jsx
  client/app/hearings/containers/DailyDocketContainer.jsx
  client/app/hearings/reducers/dailyDocketReducer.js
  client/app/queue/AppellantDetail.jsx
  client/app/queue/Detail.jsx
  client/app/queue/PowerOfAttorneyDetail.jsx
  client/app/queue/PowerOfAttorneyDetail.stories.mdx
  client/app/queue/VeteranDetail.jsx
  client/app/queue/selectors.js
  spec/jobs/warm_bgs_caches_job_spec.rb
Labels: Ready-to-Merge, Team: Tango 💃

#14553 Update representative email copy to use "Client" instead of "Veteran"
  .reek.yml
  app/mailers/virtual_hearing_mailer.rb
  app/services/virtual_hearings/calendar_service.rb
  app/views/virtual_hearing_mailer/_representative_confirmation.html.erb
  app/views/virtual_hearing_mailer/_representative_location_changed.html.erb
  app/views/virtual_hearing_mailer/_representative_updated_time_confirmation.html.erb
  app/views/virtual_hearing_mailer/calendar_events/appellant_changed_to_video_event_description.text.erb
  app/views/virtual_hearing_mailer/calendar_events/representative_changed_to_video_event_description.text.erb
  app/views/virtual_hearing_mailer/calendar_events/representative_confirmation_event_description.text.erb
Labels: Ready-to-Merge, Team: Tango 💃

#14521 Store appellant and representative timezones
  app/controllers/hearings_controller.rb
  app/helpers/virtual_hearings/calendar_template_helper.rb
  app/models/hearings/forms/base_hearing_update_form.rb
  app/services/hearing_time_service.rb
  app/views/virtual_hearing_mailer/sections/_date_time.html.erb
  db/migrate/20200630154526_add_appellant_tz_and_representative_tz_to_virtual_hearings.rb
  db/schema.rb
  docs/schema/caseflow.csv
  docs/schema/etl.csv
  spec/controllers/hearings_controller_spec.rb
  spec/factories/virtual_hearing.rb
  spec/mailers/virtual_hearing_mailer_spec.rb
  spec/services/hearing_time_service_spec.rb
Labels: Ready-to-Merge, Team: Tango 💃
