Repository department-of-veterans-affairs/caseflow, pull requests merged in 2021-11, with the labels that each got.

#16882 Caseflow 1800 - Create Tasks banner modifications
  app/models/serializers/work_queue/appellant_substitution_serializer.rb
  client/COPY.json
  client/app/queue/CaseDetailsView.jsx
  client/app/queue/VeteranDetail.jsx
  client/app/queue/substituteAppellant/caseDetails/AppealHasSubstitutionAlert.jsx
  client/app/queue/substituteAppellant/caseDetails/AppealHasSubstitutionAlert.stories.js
  client/app/queue/utils.js
  client/test/app/queue/substituteAppellant/AppealHasSubstitutionAlert.test.js
  client/test/app/queue/substituteAppellant/__snapshots__/AppealHasSubstitutionAlert.test.js.snap
  client/test/app/queue/substituteAppellant/tasks/__snapshots__/ScheduleHearingTaskAlert.test.js.snap
Labels: Ready-to-Merge

#16906 Unflake ScheduleVeteran Tests by Setting Date
  client/test/app/hearings/components/ScheduleVeteran.test.js
Labels: Ready-to-Merge

#16908 Avoid DB Seed Flake (on stafkey)
  db/seeds.rb
  db/seeds/hearings.rb
Labels: Ready-to-Merge

#16910 Fix AvailableHearingLocations#veteran
  app/models/hearings/available_hearing_locations.rb
  spec/models/available_hearing_locations_spec.rb
Labels: Ready-to-Merge

#16895 Allow Selection of Open Tasks during Pending-Appeal Substitution
  client/COPY.json
  client/app/queue/substituteAppellant/review/SubstituteAppellantReview.stories.js
  client/app/queue/substituteAppellant/review/SubstituteAppellantReviewContainer.jsx
  client/app/queue/substituteAppellant/substituteAppellant.slice.js
  client/app/queue/substituteAppellant/tasks/KeyDetails.jsx
  client/app/queue/substituteAppellant/tasks/SubstituteAppellantTasksForm.jsx
  client/app/queue/substituteAppellant/tasks/SubstituteAppellantTasksForm.stories.js
  client/app/queue/substituteAppellant/tasks/SubstituteAppellantTasksView.jsx
  client/app/queue/substituteAppellant/tasks/TaskSelectionTable.jsx
  client/app/queue/substituteAppellant/tasks/TasksToCancel.jsx
  client/app/queue/substituteAppellant/tasks/TasksToCopy.jsx
  client/app/queue/substituteAppellant/tasks/utils.js
  client/test/app/queue/substituteAppellant/SubstituteAppellantReview.test.js
  client/test/app/queue/substituteAppellant/SubstituteAppellantTasksForm.test.js
  client/test/app/queue/substituteAppellant/__snapshots__/KeyDetails.test.js.snap
  client/test/app/queue/substituteAppellant/__snapshots__/SubstituteAppellantTasksForm.test.js.snap
  client/test/app/queue/substituteAppellant/tasks/__snapshots__/utils.test.js.snap
  client/test/app/queue/substituteAppellant/tasks/utils.test.js
  client/test/data/queue/substituteAppellant/tasks.js
  spec/feature/queue/substitute_appellant/shared_setup.rb
Labels: Ready-to-Merge

#16912 Add EvidenceSubmissionWindowTask test: checks parent status when closing child task
  spec/models/tasks/evidence_submission_window_task_spec.rb
Labels: Ready-to-Merge

#16842 Add wizard for fixing SSN/filenumber mismatch issue
  lib/helpers/fix_file_number_wizard.rb
Labels: Ready-to-Merge

#16866 OpenTasksWithClosedAtChecker: ignore MailTasks and TrackVeteranTasks with a closed RootTask
  app/services/open_tasks_with_closed_at_checker.rb
  spec/services/open_tasks_with_closed_at_checker_spec.rb
Labels: Ready-to-Merge

#16875 Schedule Travel Board Hearing
  app/models/hearing.rb
Labels: Ready-to-Merge

#16931 Fix Geomatch Distance Flake
  app/models/regional_office.rb
  spec/jobs/hearings/geomatch_and_cache_appeal_job_spec.rb
Labels: Ready-to-Merge

#16923 Send reminders for Travel Board Hearings
  app/mailers/hearing_mailer.rb
  app/repositories/hearing_repository.rb
  lib/tasks/emails.rake
  spec/services/hearings/reminder_service_spec.rb
Labels: Ready-to-Merge

#16915 Program Office & VISN users can mark a task as "In Progress"
  app/models/tasks/pre_docket/assess_documentation_task.rb
  app/repositories/task_action_repository.rb
  client/COPY.json
  client/app/queue/QueueApp.jsx
  client/app/queue/components/InProgressTaskModal.jsx
  client/constants/TASK_ACTIONS.json
  spec/feature/queue/pre_docket_spec.rb
  spec/models/tasks/assess_documentation_task_spec.rb
Labels: Ready-to-Merge, Team Victor

#16936 VISN can cancel their assigned task and send the appeal back to the assigning Program Office
  app/models/tasks/pre_docket/assess_documentation_task.rb
  app/repositories/task_action_repository.rb
  client/COPY.json
  client/app/queue/QueueApp.jsx
  client/constants/TASK_ACTIONS.json
  spec/models/tasks/assess_documentation_task_spec.rb
Labels: Ready-to-Merge, Team Victor

#16925 libbey/caseflow 2546 add 30 day hearing reminder
  app/services/hearings/reminder_service.rb
  app/views/hearing_mailer/_appellant_reminder.html.erb
  spec/mailers/hearing_mailer_spec.rb
  spec/services/hearings/reminder_service_spec.rb
Labels: Team: Tango 💃, Ready-to-Merge

#16924 Improve legacy docket model
  .reek.yml
  README.md
  app/models/appeal.rb
  app/models/distribution.rb
  app/models/docket_coordinator.rb
  app/models/dockets/direct_review_docket.rb
  app/models/dockets/legacy_docket.rb
  app/models/vacols/case_docket.rb
  client/constants/DISTRIBUTION.json
  spec/jobs/push_priority_appeals_to_judges_job_spec.rb
  spec/models/appeal_spec.rb
  spec/models/distribution_spec.rb
  spec/models/distribution_spec_deprecated.rb
  spec/models/docket_coordinator_spec.rb
  spec/models/dockets/direct_review_docket_spec.rb
  spec/models/dockets/legacy_docket_spec.rb
  spec/services/redistributed_case_spec.rb
Labels: Ready-to-Merge

#16896 ProductionConsoleMethods: add finder methods
  app/models/user.rb
  config/application.rb
  lib/helpers/finder_console_methods.rb
  lib/helpers/production_console_methods.rb
  spec/factories/vacols/case.rb
  spec/lib/helpers/finder_console_methods_spec.rb
Labels: Ready-to-Merge

#16926 Enabled notifications for all types of hearings
  app/models/hearings/sent_hearing_email_event.rb
  spec/models/hearings/sent_hearing_email_event_spec.rb
Labels: Team: Tango 💃, Ready-to-Merge

#16929 Mkerns/caseflow 2241 customized on hold modal
  client/COPY.json
  client/app/queue/components/CompleteTaskModal.jsx
  client/app/queue/components/StartHoldModal.jsx
  client/app/queue/components/StartHoldModal.stories.js
  client/app/queue/constants.js
  client/yarn.lock
Labels: Ready-to-Merge

#16948 Allow nil values for vacols_representatives
  app/models/legacy_appeal.rb
  app/models/legacy_appeal_representative.rb
Labels: Ready-to-Merge

#16945 Add context around the bad hearing link
  app/mailers/hearing_mailer.rb
Labels: Ready-to-Merge

#16952 remove extraneous comments
  app/models/docket_coordinator.rb
  app/models/dockets/legacy_docket.rb
Labels: Ready-to-Merge

#16921 ForeignKeyPolymorphicAssociationJob: add available_hearing_locations
  app/jobs/foreign_key_polymorphic_association_job.rb
  app/models/hearings/available_hearing_locations.rb
  config/initializers/immigrant.rb
Labels: Ready-to-Merge

#16946 Increase speed of TaskSummaryController
  app/controllers/organizations/task_summary_controller.rb
Labels: Ready-to-Merge

#16953 Move victor seeds before MTV
  db/seeds.rb
Labels: Ready-to-Merge

#16922 Add WorksheetIssue FK
  config/initializers/immigrant.rb
  db/migrate/20211105125029_add_worksheet_issue_fk.rb
  db/migrate/20211105125151_validate_worksheet_issue_fk.rb
  db/schema.rb
Labels: Ready-to-Merge

#16502 Replicate Appeal 53008 search results
  spec/fixes/assigned_to_search_results_spec.rb
  spec/records/appeal-53008.json
Labels: Ready-to-Merge

#16956 Send IDT authentication errors to Sentry
  app/controllers/idt/authentications_controller.rb
Labels: Ready-to-Merge

#16957 Attempt A Fix for Email Problem
  app/jobs/hearings/send_email.rb
Labels: Ready-to-Merge

#16808 Add Quarterly and Annual metric report jobs
  app/controllers/api/v1/jobs_controller.rb
  app/jobs/annual_metrics_report_job.rb
  app/jobs/monthly_metrics_report_job.rb
  app/jobs/quarterly_metrics_report_job.rb
  app/jobs/recurring_metrics_report_job.rb
  app/services/metrics/non_denial_decisions.rb
  app/services/metrics/reader_adoption_rate.rb
  spec/jobs/annual_metrics_report_job_spec.rb
  spec/jobs/monthly_metrics_report_job_spec.rb
  spec/jobs/quarterly_metrics_report_job_spec.rb
  spec/services/metrics/non_denial_decisions_spec.rb
  spec/services/metrics/reader_adoption_rate_spec.rb
  spec/support/shared_examples/metrics_reports.rb
Labels: Ready-to-Merge

#16961 HearingRenderer: show associated cancelled HearingTasks
  app/models/concerns/has_hearing_task.rb
  lib/helpers/hearing_renderer.rb
  spec/lib/helpers/hearing_renderer_spec.rb
Labels: Ready-to-Merge

#16963 Add Rails logging for IDT token operations
  app/models/idt/token.rb
Labels: Ready-to-Merge

#16918 Update intake form benefit types for updated VA Form 20-0995 and 20-0996
  app/controllers/intakes_controller.rb
  app/models/higher_level_review.rb
  client/app/intake/components/BenefitType.jsx
  client/app/intake/constants.js
  client/app/intake/pages/formGenerator.jsx
  client/app/intake/pages/higherLevelReview/review.jsx
  client/app/intake/pages/review.jsx
  client/app/intake/reducers/featureToggles.js
  spec/feature/intake/higher_level_review_spec.rb
  spec/feature/intake/intake_spec.rb
  spec/models/higher_level_review_spec.rb
Labels: Team: Foxtrot 🦊, User: BVA Intake

#16960 Refactored HearingTimeService#local_time
  app/services/hearing_time_service.rb
  spec/services/hearing_time_service_spec.rb
  spec/support/timezone.rb
Labels: Team: Tango 💃, Ready-to-Merge

#16964 Resend virtual hearings service
  app/services/virtual_hearings/resend_virtual_hearing_emails_service.rb
  spec/services/virtual_hearings/resend_virtual_hearing_emails_service_spec.rb
Labels: Ready-to-Merge

#16955 Add claim_establishments foreign key to dispatch_tasks
  config/initializers/immigrant.rb
  db/migrate/20211118214020_add_foreign_key_for_claim_establishment_task.rb
  db/migrate/20211118214040_validate_foreign_key_for_claim_establishment_task.rb
  db/schema.rb
Labels: Ready-to-Merge

#16917 ACD | Add 30-Day Affinity for Hearing Cases
  app/queries/hearing_request_distribution_query.rb
  spec/factories/appeal.rb
  spec/models/dockets/hearing_request_docket_spec.rb
Labels: Ready-to-Merge

#16972 Add custom email subject
  app/jobs/hearings/send_email.rb
  app/mailers/hearing_mailer.rb
  app/services/virtual_hearings/resend_virtual_hearing_emails_service.rb
  spec/jobs/virtual_hearings/create_conference_job_spec.rb
  spec/mailers/hearing_mailer_spec.rb
  spec/services/virtual_hearings/resend_virtual_hearing_emails_service_spec.rb
Labels: Ready-to-Merge

#16942 Hide VLJ name in Hearings from VSO users
  app/views/hearings/index.html.erb
  client/app/hearings/HearingsApp.jsx
  client/app/hearings/components/ListSchedule.jsx
  client/app/hearings/components/dailyDocket/DailyDocket.jsx
  client/app/hearings/components/dailyDocket/DailyDocketPrinted.jsx
  client/app/hearings/utils.js
  spec/feature/hearings/list_schedule/vso_spec.rb
Labels: Team: Tango 💃, Ready-to-Merge

#16940 libbey/caseflow 2224 contested claims badge in docket
  app/serializers/hearings/hearing_serializer.rb
  app/serializers/hearings/legacy_hearing_serializer.rb
  client/COPY.json
  client/app/components/badges/ContestedBadge/ContestedClaimBadge.jsx
  client/app/hearings/components/dailyDocket/DailyDocketRowDisplayText.jsx
  client/app/styles/hearings/_hearings.scss
  spec/feature/hearings/daily_docket/build_hearsched_spec.rb
Labels: Team: Tango 💃, Ready-to-Merge

#16976 Don't use veteran's SSN for VACOLS appellant if appellant is not veteran
  app/models/legacy_appeal.rb
  spec/models/legacy_appeal_spec.rb
Labels: Ready-to-Merge

#16968 Display "unassigned" for appeal that has open root task and no other open tasks
  app/models/appeal.rb
  app/models/tasks/root_task.rb
  client/COPY.json
  spec/fixes/assigned_to_search_results_spec.rb
  spec/models/appeal_spec.rb
  spec/models/legacy_appeal_spec.rb
  spec/models/tasks/root_task_spec.rb
Labels: Ready-to-Merge

#16982 Fix no method error on legacy appeal
  app/models/legacy_appeal.rb
Labels: Ready-to-Merge

#16975 ForeignKeyPolymorphicAssociationJob: clarify Slack message
  app/jobs/foreign_key_polymorphic_association_job.rb
  spec/jobs/foreign_key_polymorphic_association_job_spec.rb
Labels: Ready-to-Merge

#16984 Update modal text
  client/COPY.json
Labels: Ready-to-Merge, Team Victor

#16928 CF 2497: Updates for VSO access to Case Details page when bgs is returning errors
  app/controllers/appeals_controller.rb
  app/models/concerns/appeal_concern.rb
  app/models/veteran.rb
  spec/controllers/appeals_controller_spec.rb
  spec/feature/queue/case_details_spec.rb
  spec/models/concerns/appeal_concern_spec.rb
Labels: Ready-to-Merge

#16989 Add error handling for resend service
  .rubocop.yml
  app/services/virtual_hearings/resend_virtual_hearing_emails_service.rb
  spec/factories/sent_hearing_email_event.rb
  spec/services/virtual_hearings/resend_virtual_hearing_emails_service_spec.rb
Labels: Ready-to-Merge

#16990 Exclude predocket appeals from update representative job
  app/jobs/update_appellant_representation_job.rb
  app/models/appeal.rb
  spec/factories/appeal.rb
  spec/jobs/update_appellant_representation_job_spec.rb
Labels: Ready-to-Merge

#16723 Refactor CaseReview for easier debugging
  app/models/appeal.rb
  app/models/concerns/appeal_concern.rb
  app/models/legacy_appeal.rb
  app/models/serializers/work_queue/legacy_appeal_serializer.rb
  app/models/task.rb
Labels: Ready-to-Merge

#16991 Fix blank hearings schedule CSV download
  client/app/hearings/components/ListSchedule.jsx
Labels: Team: Tango 💃, Ready-to-Merge

#16935 Fix docket switch active attorney task bug
  app/models/task.rb
  app/workflows/docket_switch/task_handler.rb
  spec/models/docket_switch_spec.rb
Labels: Ready-to-Merge

#16969 Controller update, new serializer, new route
  app/controllers/organizations_controller.rb
  app/models/serializers/work_queue/organization_serializer.rb
  config/routes.rb
  spec/controllers/organizations_controller_spec.rb
Labels: Ready-to-Merge, Team Victor

#16971 Batch assign page for CAMO org
  app/models/organizations/vha_camo.rb
  app/models/user.rb
  app/views/queue/index.html.erb
  client/COPY.json
  client/app/queue/QueueActions.js
  client/app/queue/QueueApp.jsx
  client/app/queue/QueueLoadingScreen.jsx
  client/app/queue/TeamAssignTaskListView.jsx
  client/app/queue/UnassignedCasesPage.jsx
  client/app/queue/components/AssignToAttorneyWidget.jsx
  client/app/queue/components/AssignToVhaProgramOfficeWidget.jsx
  client/app/queue/constants.js
  client/app/queue/reducers.js
  client/app/queue/selectors.js
  client/app/queue/uiReducer/uiActions.js
  client/app/queue/uiReducer/uiConstants.js
  client/app/queue/uiReducer/uiReducer.js
  client/constants/USER_ROLE_TYPES.json
  spec/feature/queue/camo_assignment_spec.rb
Labels: Ready-to-Merge, Team Victor

#16977 Only show docketing action if FT is enabled for user
  app/models/tasks/pre_docket/pre_docket_task.rb
  spec/feature/queue/pre_docket_spec.rb
  spec/models/tasks/pre_docket_task_spec.rb
Labels: Ready-to-Merge, Team Victor

#16981 Only add assign to VISN action if FT is enabled
  app/models/tasks/pre_docket/assess_documentation_task.rb
  spec/feature/queue/pre_docket_spec.rb
  spec/models/tasks/assess_documentation_task_spec.rb
Labels: Ready-to-Merge, Team Victor

#16999 Removes `already initialized constant` warning during `make check-fks`
  lib/tasks/ci.rake
  lib/tasks/support/validate_sql_queries.rb
Labels: Ready-to-Merge

#16951 Mkerns/caseflow 1946 create vha program office org queue
  app/models/organizations/vha_program_office.rb
  app/models/queue_tab.rb
  app/models/queue_tabs/vha_program_office_assigned_tasks_tab.rb
  app/models/queue_tabs/vha_program_office_completed_tasks_tab.rb
  app/models/queue_tabs/vha_program_office_in_progress_tasks_tab.rb
  app/models/queue_tabs/vha_program_office_on_hold_tasks_tab.rb
  app/models/queue_tabs/vha_program_office_ready_for_review_tasks_tab.rb
  app/models/serializers/work_queue/task_column_serializer.rb
  app/models/task.rb
  app/models/task_pager.rb
  client/COPY.json
  client/app/queue/QueueTableBuilder.jsx
  client/app/queue/components/TaskTableColumns.jsx
  client/constants/QUEUE_CONFIG.json
  spec/feature/queue/pre_docket_spec.rb
Labels: Ready-to-Merge

#16997 Add CAMO description
  app/models/organizations/vha_camo.rb
Labels: Ready-to-Merge

#16998 Add advance_on_docket_motions foreign key to persons
  config/initializers/immigrant.rb
  db/migrate/20211130140602_add_foreign_key_on_advance_on_docket_motions_to_people.rb
  db/migrate/20211130140954_validate_foreign_key_on_advance_on_docket_motions_to_persons.rb
  db/schema.rb
  spec/models/advance_on_docket_motion_spec.rb
Labels: Ready-to-Merge

#17004 Fixed special cancelled po_task case
  app/models/organizations/vha_camo.rb
  app/models/queue_tab.rb
  app/models/queue_tabs/vha_camo_assigned_tasks_tab.rb
  app/models/queue_tabs/vha_camo_completed_tasks_tab.rb
  app/models/queue_tabs/vha_program_office_assigned_tasks_tab.rb
  app/models/queue_tabs/vha_program_office_completed_tasks_tab.rb
  app/models/queue_tabs/vha_program_office_in_progress_tasks_tab.rb
  app/models/queue_tabs/vha_program_office_on_hold_tasks_tab.rb
  app/models/queue_tabs/vha_program_office_ready_for_review_tasks_tab.rb
  app/models/task.rb
  app/models/task_pager.rb
  client/COPY.json
  client/constants/QUEUE_CONFIG.json
  spec/feature/queue/pre_docket_spec.rb
Labels: Ready-to-Merge
