Repository department-of-veterans-affairs/caseflow, pull requests merged in 2021-01, with the labels that each got.

#15709 Docket Switch | Submit Denial + Denial Success Banner
  Gemfile
  Gemfile.lock
  app/controllers/docket_switches_controller.rb
  app/models/docket_switch.rb
  client/COPY.json
  client/app/queue/docketSwitch/denial/DocketSwitchDenialContainer.jsx
  client/app/queue/docketSwitch/denial/docketSwitchDenialSlice.js
  config/routes.rb
  spec/controllers/docket_switches_controller_spec.rb
  spec/feature/queue/docket_switch_spec.rb
  spec/models/tasks/docket_switch_denied_task_spec.rb
  spec/models/tasks/docket_switch_ruling_task_spec.rb
Labels: Ready-to-Merge, Team: Foxtrot 🦊

#15739 Paula/caseflow 451 limit edit nod ama
  client/app/queue/CaseTimeline.jsx
  spec/feature/queue/case_details_spec.rb
Labels: Ready-to-Merge, Team: X-ray 💀

#15744 Add docket_range_job mapping to JobsController
  app/controllers/api/v1/jobs_controller.rb
Labels: Ready-to-Merge

#15735 Initial Work on "Add Claimant" Page/Frontend Flow
  client/COPY.json
  client/app/intake/IntakeFrame.jsx
  client/app/intake/components/CancelButton.jsx
  client/app/intake/components/IntakeProgressBar.jsx
  client/app/intake/components/addClaimant/AddClaimantButtons.jsx
  client/app/intake/components/addClaimant/AddClaimantForm.jsx
  client/app/intake/components/addClaimant/AddClaimantForm.stories.js
  client/app/intake/components/addClaimant/AddClaimantPage.jsx
  client/app/intake/components/addClaimant/AddClaimantPage.stories.js
  client/app/intake/components/addClaimant/utils.js
  client/app/intake/constants.js
  client/app/intake/pages/review.jsx
  client/test/app/intake/components/SelectClaimant.test.js
  client/test/app/intake/components/addClaimants/AddClaimantForm.test.js
  client/test/app/intake/components/addClaimants/AddClaimantPage.test.js
  client/test/app/intake/components/addClaimants/__snapshots__/AddClaimantForm.test.js.snap
  client/test/app/intake/components/addClaimants/__snapshots__/AddClaimantPage.test.js.snap
  client/test/app/intake/testUtils.js
  spec/feature/intake/review_page_spec.rb
Labels: Ready-to-Merge, Team: Foxtrot 🦊

#15749 use the new syntax for brew cask installs in README & setup scripts
  README.md
  scripts/dev_env_setup_step1.sh
Labels: Ready-to-Merge

#15748 Prevent tasks from being assigned to COB
  app/models/organizations/clerk_of_the_board.rb
  spec/models/organizations/clerk_of_the_board_spec.rb
Labels: Ready-to-Merge, Team: Foxtrot 🦊

#15754 Assign more rooms to some ros
  app/models/regional_office.rb
  app/services/hearing_schedule/generate_hearing_days_schedule.rb
  spec/models/regional_office_spec.rb
Labels: Ready-to-Merge, Team: Tango 💃

#15746 Create FNOD Banner component
  client/COPY.json
  client/app/queue/CaseDetailsView.jsx
  client/app/queue/components/FnodBanner.jsx
  client/app/queue/components/FnodBanner.stories.js
  client/app/queue/components/FnodBanner.test.js
  client/app/queue/components/__snapshots__/FnodBanner.test.js.snap
Labels: Feature: FNOD, Team: X-ray 💀

#15740 CASEFLOW-641 #done Use admin status to determine role on JudgeTeam
  .reek.yml
  app/controllers/organizations/users_controller.rb
  app/models/decision_drafting_attorney.rb
  app/models/judge_team_lead.rb
  app/models/judge_team_role.rb
  app/models/organization.rb
  app/models/organizations/judge_team.rb
  app/models/organizations_user.rb
  app/models/serializers/work_queue/administered_user_serializer.rb
  app/services/judge_team_role_checker.rb
  app/workflows/assign_judgeteam_roles.rb
  client/COPY.json
  client/app/queue/OrganizationUsers.jsx
  lib/tasks/tasks.rake
  spec/controllers/organizations/users_controller_spec.rb
  spec/factories/judge_team_role.rb
  spec/factories/organization.rb
  spec/models/judge_team_role_spec.rb
  spec/models/organizations/judge_team_spec.rb
  spec/models/organizations_user_spec.rb
  spec/models/user_spec.rb
  spec/services/judge_team_role_checker_spec.rb
Labels: Priority: Medium, Product: caseflow-queue, Ready-to-Merge, Team: Echo 🐬, Type: Tech-Improvement

#15753 Docket Switch | Move granted request issues to new appeal stream
  app/models/appeal.rb
  app/models/docket_switch.rb
  app/models/request_issue.rb
  app/services/bva_appeal_status.rb
  spec/models/docket_switch_spec.rb
  spec/models/request_issue_spec.rb
Labels: Ready-to-Merge, Team: Foxtrot 🦊

#15755 Add tests to prep for major DocumentFetcher refactor
  Gemfile
  Gemfile.lock
  app/models/document.rb
  lib/generators/document.rb
  spec/models/document_spec.rb
  spec/services/document_fetcher_spec.rb
Labels: Eng: Performance, Product: caseflow-reader, Ready-to-Merge, Team: Echo 🐬, Type: Tech-Improvement

#15747 Paula/caseflow 230 add info success message
  client/COPY.json
  client/app/queue/components/EditNodDateModal.jsx
  spec/feature/queue/case_details_spec.rb
Labels: Feature: Edit NOD, Ready-to-Merge, Team: X-ray 💀

#15751 Add MDR to CAVC Remand Entry Form
  client/COPY.json
  client/app/queue/AddCavcRemandView.jsx
  client/app/queue/AddCavcRemandView.stories.js
Labels: Ready-to-Merge

#15760 Add link to CAVC Remand wiki page
  app/models/cavc_remand.rb
  app/models/tasks/cavc_correspondence_mail_task.rb
  app/models/tasks/cavc_remand_processed_letter_response_window_task.rb
  app/models/tasks/cavc_task.rb
  app/models/tasks/send_cavc_remand_processed_letter_task.rb
Labels: Ready-to-Merge

#15761 Adds "make jest" command to run jest tests locally
  Makefile.example
Labels: Ready-to-Merge, Team: Echo 🐬, javascript

#15752 Completing a task no longer says the case is complete; CAVC remands show instructions in case detail
  client/COPY.json
  client/app/queue/CavcDetail.jsx
  client/app/queue/CavcDetail.stories.mdx
Labels: Ready-to-Merge, Team: Echo 🐬

#15769 FNOD badge fix for queue
  app/models/appeal.rb
  app/models/serializers/work_queue/task_column_serializer.rb
  client/app/queue/CaseDetailsView.jsx
  client/app/queue/CaseListTable.jsx
  client/app/queue/components/BadgeArea.jsx
  client/app/queue/components/FnodBadge.jsx
  client/app/queue/components/__snapshots__/FnodBadge.test.js.snap
  client/app/queue/utils.js
Labels: Feature: FNOD, Ready-to-Merge, Team: X-ray 💀

#15770 Add FNOD Banner feature toggle
  app/models/serializers/work_queue/appeal_serializer.rb
  app/views/queue/index.html.erb
  client/app/queue/CaseDetailsView.jsx
  client/app/queue/components/FnodBanner.jsx
  client/app/queue/components/FnodBanner.stories.js
  client/app/queue/components/FnodBanner.test.js
  client/app/queue/components/__snapshots__/FnodBanner.test.js.snap
  client/app/queue/utils.js
Labels: Feature: FNOD, Team: X-ray 💀

#15773 Use sample, not shuffle in a test
  spec/models/task_sorter_spec.rb
Labels: Eng: Flaky Test, Ready-to-Merge, Type: Bug

#15767 CASEFLOW-668 #done POA task completion activates Send-Letter task
  app/models/tasks/send_cavc_remand_processed_letter_task.rb
  spec/factories/task.rb
  spec/models/tasks/send_cavc_remand_processed_letter_task_spec.rb
Labels: Ready-to-Merge, Team: Echo 🐬

#15768 Add certification metric to OIT Monthly Metrics Report Job
  app/jobs/monthly_metrics_report_job.rb
  spec/jobs/monthly_metrics_report_job_spec.rb
  spec/services/metrics/certification_usage_spec.rb
  spec/support/shared_examples/metrics_reports.rb
Labels: Eng: Data, Ready-to-Merge

#15778 Remove Slack notifications to appeals-delta channel
  app/jobs/etl_builder_job.rb
Labels: Ready-to-Merge, Team: Delta 🔺

#15775 CavcRemand add column source_appeal
  app/controllers/cavc_remands_controller.rb
  app/models/appeal.rb
  app/models/cavc_remand.rb
  client/app/queue/AddCavcRemandView.jsx
  db/migrate/20210112144819_rename_cavc_remand_appeal_id_column.rb
  db/migrate/20210112211054_add_source_index_to_cavc_remand.rb
  db/schema.rb
  docs/schema/caseflow.csv
  spec/controllers/cavc_remands_controller_spec.rb
  spec/factories/cavc_remand.rb
  spec/models/cavc_remand_spec.rb
Labels: Ready-to-Merge

#15777 Removes appeal_id from cavc_remand
  app/controllers/cavc_remands_controller.rb
  app/models/cavc_remand.rb
  client/app/queue/AddCavcRemandView.jsx
  db/migrate/20210112213248_remove_cavc_remand_appeal_id.rb
  db/schema.rb
  docs/schema/caseflow.csv
  spec/controllers/cavc_remands_controller_spec.rb
  spec/factories/cavc_remand.rb
  spec/models/cavc_remand_spec.rb
Labels: Ready-to-Merge

#15776 Rerun stuck jobs before reporting; show additional details on Slack
  app/services/stuck_virtual_hearings_checker.rb
  spec/services/stuck_virtual_hearings_checker_spec.rb
Labels: Ready-to-Merge

#15780 Update hearings seed script to create "former travel, virtual" data
  Gemfile.lock
  db/seeds/hearings.rb
Labels: Ready-to-Merge

#15781 Added bulk build hearing days for NVHQ
  app/models/regional_office.rb
  app/models/ro_schedule_period.rb
  app/services/hearing_schedule/generate_hearing_days_schedule.rb
  app/services/hearing_schedule/get_spreadsheet_data.rb
  app/services/hearing_schedule/validate_ro_spreadsheet.rb
  client/app/hearings/components/ReviewAssignments.jsx
  public/ROAssignmentTemplate.xlsx
  spec/controllers/hearings/schedule_periods_controller_spec.rb
  spec/feature/hearings/build_schedule/build_hearsched_spec.rb
  spec/models/hearing_day_spec.rb
  spec/models/hearings/allocation_spec.rb
  spec/support/blankRoSpreadsheet.xlsx
  spec/support/validRoNoRoomsSpreadsheet.xlsx
  spec/support/validRoSpreadsheet.xlsx
Labels: Ready-to-Merge

#15707 Do bulk upsert in DocumentFetcher
  app/models/document.rb
  app/services/document_fetcher.rb
  app/services/document_series_id_assigner.rb
  spec/services/document_fetcher_spec.rb
Labels: Eng: Performance, Product: caseflow-reader, Source: Bat Team, Team: Echo 🐬

#15784 Move feature toggle out of the model and into the front end
  app/models/appeal.rb
  client/app/queue/CaseDetailsView.jsx
  client/app/queue/CaseListTable.jsx
  client/app/queue/CaseTitle.jsx
  client/app/queue/QueueTableBuilder.jsx
  client/app/queue/components/BadgeArea.jsx
  client/app/queue/components/FnodBadge.jsx
  client/app/queue/components/TaskTableColumns.jsx
Labels: Feature: FNOD, Ready-to-Merge, Team: X-ray 💀

#15759 Docket Switch Task Handling
  app/models/appeal.rb
  app/models/docket_switch.rb
  app/models/task.rb
  app/models/tasks/colocated_task.rb
  app/workflows/docket_switch_task_handler.rb
  spec/factories/docket_switch.rb
  spec/factories/task.rb
  spec/models/task_spec.rb
  spec/workflows/docket_switch_task_handler_spec.rb
Labels: Ready-to-Merge, Team: Foxtrot 🦊

#15787 Bulk upsert in DocumentFetcher with duplicate detection
  app/models/document.rb
  app/services/document_fetcher.rb
  app/services/document_series_id_assigner.rb
  spec/services/document_fetcher_spec.rb
Labels: Eng: Performance, Product: caseflow-reader, Team: Echo 🐬

#15797 class << self all of OrganizationsUser
  app/models/organizations_user.rb
Labels: Ready-to-Merge, Team: Echo 🐬

#15789 Ease creation of cavc_remand for testing
  db/seeds/tasks.rb
  spec/factories/appeal.rb
  spec/factories/cavc_remand.rb
Labels: Ready-to-Merge, Team: Echo 🐬, Type: Tech-Improvement

#15796 Don't warn about exact duplicates in DocumentFetcher
  app/services/document_fetcher.rb
  spec/services/document_fetcher_spec.rb
Labels: Eng: Performance, Ready-to-Merge, Source: Sentry Alert, Team: Echo 🐬

#15795 Add Remand Appeal Association to CavcRemand model
  app/controllers/cavc_remands_controller.rb
  app/models/appeal.rb
  app/models/cavc_remand.rb
  db/migrate/20210113152529_add_cavc_remand_cavc_appeal_id.rb
  db/migrate/20210113152544_add_index_cavc_remand_cavc_appeal_id.rb
  db/schema.rb
  docs/schema/caseflow.csv
  spec/models/appeal_spec.rb
  spec/models/cavc_remand_spec.rb
Labels: Ready-to-Merge, Team: Echo 🐬

#15802 indicate environment on db commands
  Makefile.example
Labels: Ready-to-Merge

#15788 Enable CAVC MDR appeal stream creation
  app/controllers/cavc_remands_controller.rb
  app/models/cavc_remand.rb
  spec/controllers/cavc_remands_controller_spec.rb
  spec/feature/queue/cavc_task_queue_spec.rb
Labels: Ready-to-Merge, Team: Echo 🐬

#15799 Moves feature toggle to the frontend and makes fnod badge a connected component
  app/models/appeal.rb
  client/app/queue/components/FnodBadge.jsx
  client/app/queue/components/FnodBadge.test.js
  client/app/queue/components/__snapshots__/FnodBadge.test.js.snap
Labels: Feature: FNOD, Ready-to-Merge, Team: X-ray 💀

#15807 revert environment settings from makefile database commands
  Makefile.example
Labels: Ready-to-Merge

#15806 Fix flakey docket switch task handler spec
  spec/workflows/docket_switch_task_handler_spec.rb
Labels: Eng: Flaky Test, Ready-to-Merge, Team: Foxtrot 🦊

#15658 Add helper to generate AWS filter log command and URL
  app/services/aws_job_log_helper.rb
Labels: Ready-to-Merge

#15800 Change Direct Review Distribution Goal
  app/models/dockets/direct_review_docket.rb
  spec/models/docket_coordinator_spec.rb
  spec/models/dockets/direct_review_docket_spec.rb
Labels: Ready-to-Merge

#15757 Intake | Docket Switch | Ability to manually close tasks
  app/models/serializers/work_queue/task_serializer.rb
  client/COPY.json
  client/app/queue/docketSwitch/docketSwitchSlice.js
  client/app/queue/docketSwitch/grant/DocketSwitchAddTaskContainer.jsx
  client/app/queue/docketSwitch/grant/DocketSwitchAddTaskForm.jsx
  client/app/queue/docketSwitch/grant/DocketSwitchAddTaskForm.stories.js
  client/app/queue/docketSwitch/grant/DocketSwitchAddTaskModal.jsx
  client/app/queue/docketSwitch/grant/DocketSwitchGrantContainer.jsx
  client/app/queue/docketSwitch/grant/DocketSwitchReviewRequestContainer.jsx
  client/app/queue/utils.js
  client/test/app/queue/docketSwitch/DocketSwitchAddTaskForm.test.js
  client/test/app/queue/docketSwitch/__snapshots__/DocketSwitchAddTaskForm.test.js.snap
  spec/feature/queue/docket_switch_spec.rb
Labels: Ready-to-Merge

#15814 Always return cached date of death for VSOs
  app/models/veteran.rb
Labels: Ready-to-Merge

#15810 Fix flake in DocumentFetcher
  spec/services/document_fetcher_spec.rb
Labels: Eng: Flaky Test, Ready-to-Merge, Team: Echo 🐬

#15815 Update FNOD banner source text
  client/COPY.json
  client/app/queue/components/__snapshots__/FnodBanner.test.js.snap
Labels: Feature: FNOD, Ready-to-Merge, Team: X-ray 💀

#15811 Create dependent records and appeals for CAVC appeals FactoryBot
  db/seeds/priority_distributions.rb
  spec/factories/appeal.rb
  spec/factories/cavc_remand.rb
  spec/jobs/push_priority_appeals_to_judges_job_spec.rb
  spec/models/docket_spec.rb
  spec/models/tasks/cavc_correspondence_mail_task_spec.rb
  spec/workflows/bulk_task_assignment_spec.rb
Labels: Ready-to-Merge, Team: Echo 🐬, Type: Tech-Improvement

#15813 Various improvements to logging inside of jobs
  .reek.yml
  .rubocop.yml
  app/jobs/application_job.rb
  app/jobs/middleware/job_sentry_scope_middleware.rb
  app/services/external_api/bgs_service.rb
  config/environments/production.rb
  config/initializers/shoryuken.rb
  spec/jobs/application_job_spec.rb
Labels: Ready-to-Merge

#15774 CASEFLOW-93 #done Automatically place CAVC Remands without mandate on hold
  app/models/appeal.rb
  app/models/cavc_remand.rb
  app/models/decision_review.rb
  app/models/tasks/mdr_task.rb
  app/workflows/initial_tasks_factory.rb
  client/COPY.json
  spec/factories/cavc_remand.rb
  spec/feature/queue/cavc_task_queue_spec.rb
  spec/models/tasks/mdr_task_spec.rb
  spec/workflows/initial_tasks_factory_spec.rb
Labels: Ready-to-Merge, Team: Echo 🐬

#15779 CASEFLOW-675 | Allow CAVC Lit Support team access to teammates' actions
  app/models/concerns/cavc_admin_action_concern.rb
  app/models/task.rb
  app/models/tasks/cavc_correspondence_mail_task.rb
  app/models/tasks/cavc_remand_processed_letter_response_window_task.rb
  app/models/tasks/send_cavc_remand_processed_letter_task.rb
  spec/models/concerns/cavc_admin_action_concern_spec.rb
  spec/models/tasks/cavc_correspondence_mail_task_spec.rb
  spec/models/tasks/send_cavc_remand_processed_letter_task_spec.rb
Labels: Ready-to-Merge, Team: Echo 🐬

#15805 Added convert to virtual for video hearings
  app/models/appeal.rb
  app/models/concerns/hearing_request_type_concern.rb
  app/models/legacy_appeal.rb
  app/models/tasks/schedule_hearing_task.rb
  app/models/user.rb
  app/queries/appeals_updated_since_query.rb
  db/migrate/20210115212305_add_changed_hearing_request_type_to_appeal.rb
  db/schema.rb
  docs/schema/caseflow.csv
  spec/feature/hearings/convert_hearing_request_type/edit_hearsched_spec.rb
  spec/feature/hearings/convert_travel_board_hearing/edit_hearsched_spec.rb
  spec/models/tasks/change_hearing_request_type_task_spec.rb
  spec/workflows/tasks_for_appeal_spec.rb
Labels: Ready-to-Merge

#15808 Add virtual request type as option on Add Hearing Day modal
  app/services/hearing_day_room_assignment.rb
  app/views/hearings/index.html.erb
  client/app/components/DataDropdowns/RegionalOffice.jsx
  client/app/components/DateSelector.jsx
  client/app/hearings/HearingsApp.jsx
  client/app/hearings/components/HearingDayAddModal.jsx
  client/app/hearings/components/HearingDayEditModal.jsx
  client/app/hearings/containers/DailyDocketContainer.jsx
  client/app/hearings/containers/ListScheduleContainer.jsx
  spec/feature/hearings/add_hearing_day_spec.rb
  spec/feature/hearings/edit_hearing_day_spec.rb
Labels: Ready-to-Merge

#15824 Allow VSO users to page through their user queue
  app/controllers/users/task_pages_controller.rb
Labels: Product: caseflow-queue, Ready-to-Merge, Source: Bat Team, User: VSO

#15819 Pass date and docket number in controller and update UI after submit
  app/controllers/appeals_controller.rb
  client/app/queue/components/EditNodDateModal.jsx
Labels: Feature: Edit NOD, Ready-to-Merge, Team: X-ray 💀

#15786 Paula/Caseflow-200-add-edit-reasons
  app/controllers/appeals_controller.rb
  app/controllers/nod_date_updates_controller.rb
  app/schemas/nod_date_updates_schemas.rb
  client/app/queue/components/EditNodDateModal.jsx
  client/test/app/queue/components/EditNodDateModal.test.js
  client/test/app/queue/components/__snapshots__/EditNodDateModal.test.js.snap
  config/routes.rb
  spec/feature/queue/case_details_spec.rb
Labels: Feature: Edit NOD, Ready-to-Merge, Team: X-ray 💀

#15783 Add issue timeliness check for NOD Date Change
  app/models/nod_date_update.rb
  app/models/request_issue.rb
  spec/factories/nod_date_update.rb
  spec/models/nod_date_update_spec.rb
Labels: Feature: Edit NOD, Team: X-ray 💀

#15827 CASEFLOW-376 (Part 1) Allow optional dates for straight_reversal and death_dismissal
  app/controllers/cavc_remands_controller.rb
  app/models/cavc_remand.rb
  app/workflows/initial_tasks_factory.rb
  client/app/queue/AddCavcRemandView.jsx
  spec/controllers/cavc_remands_controller_spec.rb
Labels: Ready-to-Merge, Team: Echo 🐬

#15803 Update virtual hearings email templates with internal use section + other changes
  .reek.yml
  app/helpers/virtual_hearings/appellant_location_helper.rb
  app/helpers/virtual_hearings/link_helper.rb
  app/mailers/virtual_hearing_mailer.rb
  app/views/layouts/virtual_hearing_mailer.html.erb
  app/views/virtual_hearing_mailer/_representative_confirmation.html.erb
  app/views/virtual_hearing_mailer/_representative_location_changed.html.erb
  app/views/virtual_hearing_mailer/_representative_updated_time_confirmation.html.erb
  app/views/virtual_hearing_mailer/sections/_internal_use.html.erb
  app/views/virtual_hearing_mailer/sections/_test_your_connection.html.erb
  lib/tasks/emails.rake
  spec/mailers/virtual_hearing_mailer_spec.rb
Labels: Ready-to-Merge

#15817 Omit the Virtual Hearing RO from list of cities we test sorting
  spec/models/task_pager_spec.rb
Labels: Ready-to-Merge

#15832 Adds more seed users to CAVC Lit Support
  db/seeds/users.rb
  spec/seeds/users_spec.rb
Labels: Ready-to-Merge

#15833 Fix sortHearing for HearingDay display of hearings with multiple timezones
  client/app/hearings/utils.js
  client/test/app/hearings/components/HearingDaySort.test.js
Labels: Ready-to-Merge

#15835 fix a flakey test in the task tree initializer spec
  spec/services/hearing_task_tree_initializer_spec.rb
Labels: Ready-to-Merge, Team: Tango 💃

#15825 Docket Switch | Ability to Add Admin Action Tasks
  client/COPY.json
  client/app/intake/addClaimant/utils.js
  client/app/queue/docketSwitch/denial/DocketSwitchDenialForm.jsx
  client/app/queue/docketSwitch/docketSwitchSlice.js
  client/app/queue/docketSwitch/grant/DocketSwitchAddAdminTaskForm.jsx
  client/app/queue/docketSwitch/grant/DocketSwitchAddAdminTaskForm.stories.js
  client/app/queue/docketSwitch/grant/DocketSwitchAddTaskContainer.jsx
  client/app/queue/docketSwitch/grant/DocketSwitchAddTaskForm.jsx
  client/app/queue/docketSwitch/grant/DocketSwitchEditTasksContainer.jsx
  client/app/queue/docketSwitch/grant/DocketSwitchEditTasksForm.jsx
  client/app/queue/docketSwitch/grant/DocketSwitchEditTasksForm.stories.js
  client/app/queue/docketSwitch/grant/DocketSwitchGrantContainer.jsx
  client/app/queue/docketSwitch/grant/DocketSwitchRemoveTaskModal.jsx
  client/app/queue/docketSwitch/grant/DocketSwitchReviewRequestForm.jsx
  client/app/queue/docketSwitch/judgeRuling/DocketSwitchRulingContainer.jsx
  client/app/queue/docketSwitch/judgeRuling/DocketSwitchRulingForm.jsx
  client/app/queue/docketSwitch/recommendDocketSwitch/RecommendDocketSwitchContainer.jsx
  client/app/queue/docketSwitch/recommendDocketSwitch/RecommendDocketSwitchForm.jsx
  client/constants/DOCKET_SWITCH_DISPOSITIONS.json
  client/constants/DOCKET_SWITCH_TASKS_BY_DOCKET_TYPE.json
  client/package.json
  client/test/app/queue/docketSwitch/DocketSwitchAddAdminTaskForm.test.js
  client/test/app/queue/docketSwitch/DocketSwitchAddTaskForm.test.js
  client/test/app/queue/docketSwitch/DocketSwitchEditTasksForm.test.js
  client/test/app/queue/docketSwitch/__snapshots__/DocketSwitchAddAdminTaskForm.test.js.snap
  client/test/app/queue/docketSwitch/__snapshots__/DocketSwitchEditTasksForm.test.js.snap
  client/yarn.lock
  spec/feature/queue/docket_switch_spec.rb
Labels: Ready-to-Merge

#15840 Fix Fiduciary error
  app/models/decision_issue.rb
Labels: Ready-to-Merge

#15842 Ability to add listed attorney claimant
  app/controllers/intakes_controller.rb
  app/models/bgs_attorney.rb
  client/app/intake/addClaimant/AddClaimantPage.jsx
  client/app/intake/addClaimant/AddClaimantPage.stories.js
  client/app/intake/addClaimant/utils.js
  spec/controllers/intakes_controller_spec.rb
  spec/feature/intake/non_veteran_claimants_spec.rb
  spec/feature/intake/review_page_spec.rb
Labels: Ready-to-Merge, Team: Foxtrot 🦊

#15830 Mkerns/caseflow 199 add warning message
  client/COPY.json
  client/app/queue/components/EditNodDateModal.jsx
  client/test/app/queue/components/EditNodDateModal.test.js
  client/test/app/queue/components/__snapshots__/EditNodDateModal.test.js.snap
Labels: Feature: Edit NOD, Ready-to-Merge, Team: X-ray 💀

#15837 adds scheduled_in_error legacy hearing disposition
  app/mappers/hearing_mapper.rb
  app/models/vacols/case_hearing.rb
  app/services/hearing_day_range.rb
  spec/factories/vacols/case_hearing.rb
  spec/mappers/hearing_mapper_spec.rb
Labels: Team: Tango 💃

#15836 Use constants for VACOLS case hearing dispositions
  app/mappers/hearing_mapper.rb
  app/models/vacols/case_hearing.rb
  app/repositories/appeal_repository.rb
  app/services/hearing_day_range.rb
  client/constants/HEARING_DISPOSITION_TYPES.json
  spec/factories/vacols/case_hearing.rb
  spec/mappers/hearing_mapper_spec.rb
  spec/models/hearing_day_spec.rb
  spec/models/tasks/hearing_task_spec.rb
  spec/models/tasks/schedule_hearing_task_spec.rb
  spec/repositories/hearing_repository_spec.rb
  spec/repositories/virtual_hearing_repository_spec.rb
  spec/services/hearing_task_tree_initializer_spec.rb
  spec/workflows/tasks_for_appeal_spec.rb
Labels: Ready-to-Merge, Team: Tango 💃
