Repository department-of-veterans-affairs/caseflow, pull requests merged in 2021-07, with the labels that each got.

#16440 Unrecognized Appellant Versioning
  app/models/claimant.rb
  app/models/unrecognized_appellant.rb
  app/models/user.rb
  db/migrate/20210630142005_add_current_version_id_to_unrecognized_appellants.rb
  db/schema.rb
  docs/schema/caseflow.csv
  spec/models/unrecognized_appellant_spec.rb
Labels: Ready-to-Merge

#16446 Remove the verify unidentified issue feature
  app/controllers/intakes_controller.rb
  app/views/appeals/edit.html.erb
  app/views/higher_level_reviews/edit.html.erb
  app/views/supplemental_claims/edit.html.erb
  client/app/intake/components/AddIssueManager.jsx
  client/app/intake/components/UnidentifiedIssuesModal.jsx
  client/app/intake/reducers/featureToggles.js
  client/test/karma/intake/UnidentifiedIssuesModal-test.js
  spec/feature/intake/higher_level_review_spec.rb
Labels: Ready-to-Merge

#16441 Unrecognized Appellant API Shell
  app/controllers/unrecognized_appellants_controller.rb
  app/models/unrecognized_appellant.rb
  config/routes.rb
  spec/controllers/unrecognized_appellant_controller_spec.rb
  spec/requests/unrecognized_appellants_request_spec.rb
Labels: Ready-to-Merge

#16448 Explain page: enable loading legacy appeals
  app/views/explain/show.html.erb
  spec/feature/explain_spec.rb
Labels: Eng: Data Work Group, Ready-to-Merge

#16450 Nweinmeister/1564 ua versioning
  app/controllers/unrecognized_appellants_controller.rb
  app/models/unrecognized_appellant.rb
  spec/controllers/unrecognized_appellant_controller_spec.rb
  spec/factories/unrecognized_appellant.rb
  spec/models/unrecognized_appellant_spec.rb
Labels: Ready-to-Merge

#16449 Update scripts to work with awscli v2
  ci-bin/circle_docker_container/build_and_push.sh
  docker-bin/tagnpush.sh
  local/vacols/build_push.sh
Labels: Ready-to-Merge

#16421 Fixed focus indicator on schedule hearings table
  client/app/hearings/components/assignHearings/AssignHearingsDocketLine.jsx
  client/app/hearings/components/assignHearings/AssignHearingsTable.jsx
  client/app/styles/hearings/_hearings.scss
Labels: Ready-to-Merge

#16453 Fix RequestIssue order-of-creation ITF EP code bug
  app/models/claim_review.rb
  spec/models/claim_review_spec.rb
Labels: Ready-to-Merge

#16455 TasksAssignedToInactiveUsersChecker: Reformat Slack alert message
  app/services/tasks_assigned_to_inactive_users_checker.rb
Labels: Ready-to-Merge, Team: Echo 🐬

#16451 Hide `HearingTask` during Substitution
  client/app/queue/substituteAppellant/tasks/utils.js
  client/test/app/queue/substituteAppellant/tasks/utils.test.js
Labels: Ready-to-Merge, Team: Echo 🐬

#16454 Resolve INC18593851 by changing conditional order in shouldSupportSubstituteAppellant
  client/app/queue/substituteAppellant/caseDetails/utils.js
Labels: Ready-to-Merge

#16424 Shalliburton/caseflow 1404 time slot tooltip
  client/app/hearings/components/scheduleHearing/TimeSlotDetail.jsx
  client/app/styles/hearings/_hearings.scss
  client/test/app/hearings/components/assignHearings/__snapshots__/AssignHearingsList.test.js.snap
  client/test/app/hearings/components/assignHearings/__snapshots__/TimeSlotCard.test.js.snap
  client/test/app/hearings/components/scheduleHearing/__snapshots__/TimeSlotButton.test.js.snap
  client/test/app/hearings/components/scheduleHearing/__snapshots__/TimeSlotDetail.test.js.snap
Labels: Ready-to-Merge

#16439 Show informational banner in "About the Appellant" section
  client/COPY.json
  client/app/queue/AppellantDetail.jsx
  spec/feature/queue/case_details_spec.rb
Labels: Ready-to-Merge

#16456 StuckAppealsChecker: notify Team Echo in Slack
  app/services/stuck_appeals_checker.rb
Labels: Ready-to-Merge, Team: Echo 🐬

#16457 Include cancelled cases in Quality Review team's monthly limit for AMA appeals
  app/models/judge_case_review.rb
  app/models/quality_review_case_selector.rb
  spec/models/judge_case_review_spec.rb
  spec/models/quality_review_case_selector_spec.rb
Labels: Ready-to-Merge

#16458 Use .pop, not .sample, for populating "random" names
  spec/models/task_sorter_spec.rb
Labels: Ready-to-Merge, Team: Echo 🐬

#16459 Fix Storybook for FnodBadge
  client/app/queue/components/FnodBadge.stories.js
Labels: Ready-to-Merge

#16461 AppealsWithNoTasksOrAllTasksOnHoldQuery: ignore appeals without a decision document
  app/queries/appeals_with_no_tasks_or_all_tasks_on_hold_query.rb
  spec/models/appeal_spec.rb
  spec/queries/appeals_with_no_tasks_or_all_tasks_on_hold_query_spec.rb
  spec/services/stuck_appeals_checker_spec.rb
Labels: Ready-to-Merge

#16452 Make versioning fields required and backfill previous data
  app/models/other_claimant.rb
  app/models/unrecognized_appellant.rb
  db/migrate/20210701201156_change_unrecognized_appellant_current_version.rb
  db/schema.rb
  spec/factories/unrecognized_appellant.rb
  spec/models/appeal_intake_spec.rb
  spec/models/other_claimant_spec.rb
Labels: Ready-to-Merge

#16402 Remove restrictAppealIntakes feature toggle
  app/controllers/intakes_controller.rb
  client/app/intake/pages/selectForm.jsx
  client/app/intake/reducers/featureToggles.js
  spec/feature/intake/appeal_spec.rb
  spec/feature/intake/intake_spec.rb
  spec/feature/intake/non_veteran_claimants_spec.rb
  spec/feature/intake/time_zone_spec.rb
  spec/support/intake_helpers.rb
Labels: Team: Foxtrot 🦊, Type: Tech-Improvement

#16413 Add orgs for VHA Program and Regional Offices
  app/models/organizations/vha_program_office.rb
  app/models/organizations/vha_regional_office.rb
Labels: Ready-to-Merge

#16460 Add data integrity checker for appeals with more than one open hearing task
  app/jobs/data_integrity_checks_job.rb
  app/services/appeals_with_more_than_one_open_hearing_task_checker.rb
  spec/jobs/data_integrity_checks_job_spec.rb
  spec/services/appeals_with_more_than_one_open_hearing_task_checker_spec.rb
Labels: Ready-to-Merge, Team: Tango 💃

#16444 Display Hearings Scheduled column in the landing page
  app/controllers/hearings/hearing_day_controller.rb
  app/models/concerns/hearing_concern.rb
  app/models/hearing_day.rb
  app/models/vacols/case_hearing.rb
  app/queries/hearing_day_filled_slots_query.rb
  app/serializers/hearings/hearing_day_serializer.rb
  app/views/hearings/index.html.erb
  client/app/hearings/HearingsApp.jsx
  client/app/hearings/components/ListSchedule.jsx
  client/app/hearings/constants.js
  client/app/hearings/containers/AssignHearingsContainer.jsx
  client/app/hearings/containers/ListScheduleContainer.jsx
  spec/controllers/hearings/hearing_day_controller_spec.rb
  spec/factories/hearing.rb
  spec/feature/hearings/list_schedule/build_hearsched_spec.rb
  spec/queries/hearing_day_filled_slots_query_spec.rb
Labels: Ready-to-Merge

#16433 Limit VSO users' ability to view decision issues
  app/models/serializers/work_queue/appeal_serializer.rb
  app/policies/appeal_decision_issues_policy.rb
  spec/factories/appeal.rb
  spec/factories/user.rb
  spec/feature/queue/ama_queue_spec.rb
  spec/models/serializers/work_queue/appeal_serializer_spec.rb
  spec/policies/appeal_decision_issues_policy_spec.rb
Labels: Ready-to-Merge

#16466 seed data for feature to restrict poa visibility
  app/models/serializers/work_queue/appeal_serializer.rb
  app/policies/appeal_decision_issues_policy.rb
  db/seeds.rb
  db/seeds/decision_issues.rb
  db/seeds/tasks.rb
  spec/factories/user.rb
  spec/models/serializers/work_queue/appeal_serializer_spec.rb
  spec/policies/appeal_decision_issues_policy_spec.rb
  spec/seeds/decision_issues_spec.rb
Labels: Ready-to-Merge

#16426 hide ihp tasks on substitute if poa cannot write ihp tasks
  app/controllers/claimants_controller.rb
  app/models/organizations/field_vso.rb
  app/models/serializers/work_queue/power_of_attorney_serializer.rb
  app/models/tasks/informal_hearing_presentation_task.rb
  client/app/queue/substituteAppellant/tasks/SubstituteAppellantTasksView.jsx
  client/app/queue/substituteAppellant/tasks/utils.js
  client/test/app/queue/substituteAppellant/tasks/utils.test.js
  spec/controllers/claimants_controller_spec.rb
  spec/factories/appeal.rb
  spec/feature/queue/case_details_spec.rb
  spec/models/organizations/field_vso_spec.rb
  spec/models/serializers/work_queue/power_of_attorney_serializer_spec.rb
  spec/models/validators/intake_start_validator_spec.rb
Labels: Ready-to-Merge

#16465 Add new spec to show how to Backfill early AMA appeal
  spec/fixes/backfill_early_ama_appeal_spec.rb
  spec/fixes/fixing_dispatched_appeal_spec.rb
  spec/records/early-appeal-39.json
Labels: Eng: Data Work Group, Ready-to-Merge

#16477 route send email error to #appeals-hearings
  app/jobs/virtual_hearings/create_conference_job.rb
Labels: Ready-to-Merge, Team: Tango 💃

#16474 Remove restrictions on converting travel board to virtual
  app/models/legacy_appeal.rb
  app/workflows/tasks_for_appeal.rb
  spec/workflows/tasks_for_appeal_spec.rb
Labels: Ready-to-Merge, Team: Tango 💃

#16472 Add bones for the edit appellant information
  client/app/intakeEdit/components/EditAppellantInformation.jsx
  client/app/queue/QueueApp.jsx
  client/app/queue/editAppellantInformation/EditAppellantInformation.jsx
  client/app/queue/editAppellantInformation/editAppellantInformationSlice.js
  client/app/queue/editAppellantInformation/utils.js
  client/app/queue/reducers.js
Labels: Ready-to-Merge

#16479 Add feature toggle to enable dispatch of unrecognized appellant cases
  app/models/tasks/bva_dispatch_task.rb
  spec/models/tasks/bva_dispatch_task_spec.rb
Labels: Ready-to-Merge

#16480 Create pre-docket task classes
  app/models/tasks/assess_documentation_task.rb
  app/models/tasks/insufficient_information_task.rb
  app/models/tasks/pre_docket_task.rb
Labels: Ready-to-Merge, Team Victor

#16476 Send AmbiguousTimezoneError to Datadog instead of Sentry
  app/models/concerns/appeal_concern.rb
  app/services/timezone_service.rb
  spec/models/concerns/appeal_concern_spec.rb
Labels: Ready-to-Merge

#16483 Update references to Datadog monitors in code comment
  app/jobs/update_cached_appeals_attributes_job.rb
Labels: Ready-to-Merge

#16464 CASEFLOW-1749: Support adding substitute appellants for post-dispatch cases
  client/app/queue/CaseDetailsView.jsx
  db/seeds/substitutions.rb
  spec/factories/appeal.rb
  spec/factories/appellant_substitution.rb
  spec/feature/queue/case_details_spec.rb
  spec/feature/queue/substitute_appellant/substitute_appellant_spec.rb
Labels: Ready-to-Merge, Team: Echo 🐬

#16493 Allow access to the attorneys endpoint
  app/controllers/intakes_controller.rb
  spec/controllers/intakes_controller_spec.rb
Labels: Ready-to-Merge

#16494 Allow more variations on US country name and zip codes
  app/services/timezone_service.rb
  spec/services/timezone_service_spec.rb
Labels: Ready-to-Merge

#16338 Explain page: add timeline visualization
  .reek.yml
  app/assets/javascripts/explain-appeal.js
  app/assets/stylesheets/explain_appeal.css
  app/controllers/concerns/explain/hearing_record_event_mapper.rb
  app/controllers/concerns/explain/record_event_mapper.rb
  app/controllers/concerns/explain_appeal_events_concern.rb
  app/controllers/concerns/explain_timeline_concern.rb
  app/controllers/explain_controller.rb
  app/views/explain/show.html.erb
  client/package.json
  client/yarn.lock
  spec/feature/explain_spec.rb
Labels: Eng: Data Work Group, Ready-to-Merge

#16489 Reader: increase timeout to load documents
  app/services/document_fetcher.rb
Labels: Ready-to-Merge, Source: Bat Team

#16499 CaseflowJob subclasses: report runtime to DataDog
  app/jobs/caseflow_job.rb
  app/jobs/data_integrity_checks_job.rb
  app/jobs/etl_builder_job.rb
  app/jobs/fetch_efolder_document_count_job.rb
  app/jobs/nightly_syncs_job.rb
  app/jobs/task_timer_job.rb
  app/jobs/update_appellant_representation_job.rb
  app/jobs/update_cached_appeals_attributes_job.rb
  app/jobs/warm_bgs_caches_job.rb
  spec/jobs/caseflow_job_spec.rb
  spec/jobs/fetch_efolder_document_count_job_spec.rb
Labels: Ready-to-Merge

#16485 Prepopulate the edit appellant form with existing data
  app/models/concerns/has_unrecognized_party_detail.rb
  app/models/other_claimant.rb
  app/models/serializers/work_queue/appeal_serializer.rb
  client/app/intake/addClaimant/ClaimantForm.jsx
  client/app/queue/QueueApp.jsx
  client/app/queue/editAppellantInformation/EditAppellantInformation.jsx
  client/app/queue/editAppellantInformation/utils.js
  client/app/queue/utils.js
  client/test/app/queue/editAppellantInformation/EditAppellantInformation.test.js
  client/test/app/queue/editAppellantInformation/__snapshots__/EditAppellantInformation.test.js.snap
  client/test/app/queue/editAppellantInformation/utils.test.js
  spec/feature/intake/non_veteran_claimants_spec.rb
Labels: Ready-to-Merge

#16498 Added Alert re VSO Visibility Changes
  app/views/queue/index.html.erb
  client/COPY.json
  client/app/queue/CaseDetailsView.jsx
  client/app/queue/caseDetails/VsoVisibilityAlert.jsx
  client/app/queue/caseDetails/VsoVisibilityAlert.stories.js
  client/app/queue/caseDetails/utils.js
  client/test/app/queue/caseDetails/VsoVisibilityAlert.test.js
  client/test/app/queue/caseDetails/__snapshots__/VsoVisibilityAlert.test.js.snap
  client/test/app/queue/caseDetails/utils.test.js
  spec/feature/queue/case_details_spec.rb
Labels: Ready-to-Merge, Team: Echo 🐬

#16507 Limit VSO power of attorney users’ ability to view decision issues - test both reader appeal controller and user for appeal serializer
  app/controllers/reader/appeal_controller.rb
  app/models/serializers/work_queue/appeal_serializer.rb
  app/policies/appeal_decision_issues_policy.rb
  db/seeds.rb
  db/seeds/decision_issues.rb
  spec/controllers/reader/appeal_controller_spec.rb
  spec/factories/appeal.rb
  spec/feature/queue/ama_queue_spec.rb
  spec/models/serializers/work_queue/appeal_serializer_spec.rb
  spec/policies/appeal_decision_issues_policy_spec.rb
  spec/seeds/decision_issues_spec.rb
Labels: Ready-to-Merge

#16515 Snooze jquery warning for a week
  .security.yml
Labels: Ready-to-Merge

#16496 Unrecognized Appellant Edit: Submit and Notify Success - Integrate with UA API
  app/controllers/unrecognized_appellants_controller.rb
  client/app/intake/addClaimant/utils.js
  client/app/queue/editAppellantInformation/EditAppellantInformation.jsx
  client/app/queue/editAppellantInformation/editAppellantInformationSlice.js
  client/app/queue/editAppellantInformation/utils.js
  spec/factories/appeal.rb
  spec/feature/intake/non_veteran_claimants_spec.rb
  spec/feature/queue/unrecognized_appellant_spec.rb
Labels: Ready-to-Merge

#16516 IncompleteDistributionsJob: fix started Distributions
  app/controllers/api/v1/jobs_controller.rb
  app/jobs/incomplete_distributions_job.rb
  app/jobs/missed_job_sweeper_job.rb
  app/models/concerns/automatic_case_distribution.rb
  app/models/concerns/proportion_hash.rb
  spec/jobs/incomplete_distributions_job_spec.rb
  spec/jobs/missed_job_sweeper_job_spec.rb
Labels: Eng: Data Work Group, Ready-to-Merge

#16518 Add Loading State to EditClaimantForm Submission
  client/app/queue/editAppellantInformation/EditAppellantInformation.jsx
  client/test/app/queue/editAppellantInformation/__snapshots__/EditAppellantInformation.test.js.snap
Labels: Ready-to-Merge

#16523 reduce repetition in test hearing setup
  spec/mailers/hearing_mailer_spec.rb
Labels: Team: Tango 💃

#16517 IncompleteDistributionsJob: Remove old missed_job_sweeper job
  app/controllers/api/v1/jobs_controller.rb
Labels: Ready-to-Merge

#16526 [WIP] Set up success alert fro unrecognized appellant edit
  client/COPY.json
  client/app/queue/editAppellantInformation/EditAppellantInformation.jsx
  client/app/queue/editAppellantInformation/editAppellantInformationSlice.js
  spec/feature/queue/unrecognized_appellant_spec.rb
Labels: Ready-to-Merge

#16519 Edit unrecognized appellant edge cases
  client/COPY.json
  client/app/intake/addClaimant/ClaimantForm.jsx
  client/app/intake/addClaimant/utils.js
  client/app/queue/AppellantDetail.jsx
  client/app/queue/CaseDetailsView.jsx
  client/app/queue/constants.js
  client/app/queue/editAppellantInformation/EditAppellantInformation.jsx
  client/app/queue/editAppellantInformation/utils.js
  client/test/app/queue/editAppellantInformation/__snapshots__/EditAppellantInformation.test.js.snap
  client/test/app/queue/editAppellantInformation/utils.test.js
  spec/feature/queue/unrecognized_appellant_spec.rb
Labels: Ready-to-Merge

#16534 Disable save button when form is not valid
  client/app/queue/editAppellantInformation/EditAppellantInformation.jsx
  client/test/app/queue/editAppellantInformation/__snapshots__/EditAppellantInformation.test.js.snap
  spec/feature/queue/unrecognized_appellant_spec.rb
Labels: Ready-to-Merge

#16522 1521: make distribution tasks visible to VSOs, plus a spec.
  .reek.yml
  app/workflows/tasks_for_appeal.rb
  spec/workflows/tasks_for_appeal_spec.rb
Labels: Ready-to-Merge

#16527 Clarify in Emails to Representatives Which Appellant is Scheduled
  app/jobs/hearings/send_email.rb
  app/mailers/hearing_mailer.rb
  app/models/concerns/appeal_concern.rb
  app/views/hearing_mailer/_representative_confirmation.html.erb
  app/views/hearing_mailer/_representative_reminder.html.erb
  lib/tasks/emails.rake
  spec/jobs/hearings/send_email_spec.rb
  spec/mailers/hearing_mailer_spec.rb
Labels: Ready-to-Merge

#16529 Account for TZ in EvidenceSubmissionWindow End Date during Substitution
  client/app/queue/substituteAppellant/tasks/TaskSelectionTable.jsx
  client/app/queue/substituteAppellant/tasks/utils.js
  client/test/app/queue/substituteAppellant/__snapshots__/SubstituteAppellantTasksForm.test.js.snap
  client/test/app/queue/substituteAppellant/tasks/utils.test.js
  spec/feature/queue/substitute_appellant/shared_setup.rb
  spec/feature/queue/substitute_appellant/substitute_appellant_spec.rb
Labels: Ready-to-Merge, Team: Echo 🐬

#16536 suggested additional tests
  spec/models/hearings/hearing_email_recipient_spec.rb
Labels: Team: Tango 💃

#16535 Fix minor edit unrecognized appellant bug
  client/app/queue/editAppellantInformation/utils.js
Labels: Ready-to-Merge

#16537 Remove LegacyAppeal.veteran_date_of_birth attribute
  app/models/legacy_appeal.rb
  app/repositories/appeal_repository.rb
  client/app/queue/utils.js
  lib/fakes/data/appeal_data.rb
Labels: Ready-to-Merge

#16511 Create new email recipient tables
  app/jobs/hearings/send_email.rb
  app/mailers/hearing_mailer.rb
  app/models/concerns/has_hearing_email_recipients_concern.rb
  app/models/email_recipient_info.rb
  app/models/hearing.rb
  app/models/hearings/appellant_hearing_email_recipient.rb
  app/models/hearings/forms/base_hearing_update_form.rb
  app/models/hearings/hearing_email_recipient.rb
  app/models/hearings/judge_hearing_email_recipient.rb
  app/models/hearings/representative_hearing_email_recipient.rb
  app/models/hearings/sent_hearing_email_event.rb
  app/models/hearings/virtual_hearing.rb
  app/models/legacy_hearing.rb
  app/models/mail_recipient.rb
  app/repositories/virtual_hearing_repository.rb
  app/services/hearings/calendar_service.rb
  app/views/hearing_mailer/sections/_date_time.html.erb
  client/app/hearings/utils.js
  client/test/app/hearings/components/ScheduleVeteran.test.js
  config/initializers/immigrant.rb
  db/migrate/20210709145249_create_hearing_email_recipient.rb
  db/migrate/20210713161648_add_hearing_email_recipient_column_to_sent_hearing_email_events.rb
  db/schema.rb
  docs/schema/caseflow-belongs_to_erd-subclasses.svg
  docs/schema/caseflow-belongs_to_erd.svg
  docs/schema/caseflow-subclasses.svg
  docs/schema/caseflow.csv
  lib/tasks/emails.rake
  spec/controllers/hearings_controller_spec.rb
  spec/factories/hearing_email_recipient.rb
  spec/factories/sent_hearing_email_event.rb
  spec/factories/virtual_hearing.rb
  spec/feature/hearings/virtual_hearings/daily_docket_spec.rb
  spec/feature/hearings/virtual_hearings/hearing_details_spec.rb
  spec/jobs/hearings/send_email_spec.rb
  spec/jobs/hearings/send_reminder_emails_job_spec.rb
  spec/jobs/virtual_hearings/create_conference_job_spec.rb
  spec/jobs/virtual_hearings/delete_conferences_job_spec.rb
  spec/mailers/hearing_mailer_spec.rb
  spec/models/hearing_spec.rb
  spec/models/hearings/hearing_email_recipient_spec.rb
  spec/models/hearings/sent_hearing_email_event_spec.rb
  spec/models/legacy_hearing_spec.rb
  spec/models/tasks/assign_hearing_disposition_task_spec.rb
  spec/models/tasks/schedule_hearing_task_spec.rb
  spec/repositories/virtual_hearing_repository_spec.rb
  spec/services/hearing_time_service_spec.rb
Labels: Ready-to-Merge

#16524 CASEFLOW-1647 ScheduleHearingTask Alert for substitutions
  client/COPY.json
  client/app/queue/substituteAppellant/tasks/ScheduleHearingTaskAlert.jsx
  client/app/queue/substituteAppellant/tasks/ScheduleHearingTaskAlert.stories.js
  client/app/queue/substituteAppellant/tasks/SubstituteAppellantTasksForm.jsx
  client/app/queue/substituteAppellant/tasks/utils.js
  client/test/app/queue/substituteAppellant/tasks/ScheduleHearingTaskAlert.test.js
  client/test/app/queue/substituteAppellant/tasks/__snapshots__/ScheduleHearingTaskAlert.test.js.snap
  spec/feature/queue/substitute_appellant/shared_setup.rb
  spec/feature/queue/substitute_appellant/substitute_appellant_spec.rb
Labels: Ready-to-Merge, Team: Echo 🐬

#16500 StuckAppealsChecker: ignore active TrackVeteranTask
  app/queries/appeals_with_no_tasks_or_all_tasks_on_hold_query.rb
  spec/queries/appeals_with_no_tasks_or_all_tasks_on_hold_query_spec.rb
Labels: Eng: Data Work Group, Ready-to-Merge

#16521 Add comments to AppealsWithNoTasksOrAllTasksOnHoldQuery
  app/queries/appeals_with_no_tasks_or_all_tasks_on_hold_query.rb
Labels: Ready-to-Merge

#16505 Add EngineeringTask
  app/models/concerns/task_tree_render_module.rb
  app/models/task.rb
  app/models/tasks/engineering_task.rb
  spec/models/tasks/attorney_task_spec.rb
  spec/models/tasks/cavc_remand_processed_letter_response_window_task_spec.rb
  spec/models/tasks/engineering_task_spec.rb
  spec/models/tasks/mandate_hold_task_spec.rb
  spec/models/tasks/mdr_task_spec.rb
  spec/models/tasks/send_cavc_remand_processed_letter_task_spec.rb
  spec/models/tasks/task_shared_examples.rb
Labels: Ready-to-Merge

#16547 Bug Fix | Non-Dynamic Dates in substitute_appellant_spec
  spec/feature/queue/substitute_appellant/substitute_appellant_spec.rb
Labels: Ready-to-Merge

#16546 Properly access hearing disposition in tasks_visible_to_vso_employee
  app/workflows/tasks_for_appeal.rb
  spec/workflows/tasks_for_appeal_spec.rb
Labels: Ready-to-Merge

#16538 Delegate LegacyAppeal.veteran_gender to BGS instead of VACOLS
  app/models/legacy_appeal.rb
  app/repositories/appeal_repository.rb
  client/app/queue/VeteranDetail.jsx
  lib/fakes/data/appeal_data.rb
  spec/feature/queue/case_details_spec.rb
Labels: Ready-to-Merge

#16349 Upgrade Ruby from 2.5.3 to 2.7.3
  .circleci/config.yml
  .ruby-version
  Dockerfile
  Gemfile
  Gemfile.lock
  bin/setup
  ci-bin/circle_docker_container/Dockerfile
  ci-bin/circle_docker_container/build_and_push.sh
  spec/controllers/test/hearings_controller_spec.rb
  spec/factories/intake.rb
  spec/feature/queue/judge_assignment_spec.rb
Labels: Eng: Backend Work Group, Eng: Dependencies, Ready-to-Merge, Type: Tech-Improvement

#16551 Extend snooze for CVE-2020-11023 for 2 weeks
  .security.yml
Labels: Ready-to-Merge

#16554 Add filed-by-va-gov API enhancement
  app/models/appeal_intake.rb
  app/schemas/intakes_schemas.rb
  app/serializers/intake/decision_review_intake_serializer.rb
  db/migrate/20210727140419_add_filed_by_va_gov_to_intake_details.rb
  db/schema.rb
  docs/schema/caseflow.csv
Labels: Ready-to-Merge

#16484 `make clean` now removes log/logstasher.log
  Makefile.example
Labels: Ready-to-Merge

#16543 Explain page: add graph network visualization
  app/assets/javascripts/explain-appeal-network.js
  app/assets/javascripts/explain-appeal-timeline.js
  app/assets/stylesheets/explain_appeal.css
  app/assets/stylesheets/explain_appeal.scss
  app/assets/stylesheets/explain_appeal_timeline.scss
  app/controllers/concerns/explain_network_concern.rb
  app/controllers/concerns/explain_timeline_concern.rb
  app/controllers/explain_controller.rb
  app/views/explain/_details_pane.html.erb
  app/views/explain/_hearing_tree.html.erb
  app/views/explain/_intake_tree.html.erb
  app/views/explain/_legend_pane.html.erb
  app/views/explain/_menubar.html.erb
  app/views/explain/_narrative_table.html.erb
  app/views/explain/_network_graph.html.erb
  app/views/explain/_side_panel.html.erb
  app/views/explain/_task_tree.html.erb
  app/views/explain/_timeline_chart.html.erb
  app/views/explain/show.html.erb
  client/app/explain/components/ColumnBuilder.jsx
  client/package.json
  client/yarn.lock
  config/initializers/assets.rb
  spec/feature/explain_spec.rb
  spec/fixes/investigate_duplicate_judge_assign_task_spec.rb
Labels: Eng: Data Work Group, Ready-to-Merge

#16558 Pass empty string if names not present
  client/app/queue/editAppellantInformation/utils.js
  spec/feature/queue/unrecognized_appellant_spec.rb
Labels: Ready-to-Merge

#16481 CAMO Organization Queue
  app/models/organizations/vha_camo.rb
  app/models/queue_tabs/vha_camo_completed_tasks_tab.rb
  app/models/queue_tabs/vha_camo_in_progress_tasks_tab.rb
  client/COPY.json
  client/app/queue/QueueTableBuilder.jsx
  client/constants/QUEUE_CONFIG.json
  spec/feature/queue/camo_queue_spec.rb
Labels: Ready-to-Merge

#16562 ETL DB: remove decision issue's unique index
  db/etl/migrate/20210729124530_remove_etl_decision_issues_index.rb
  db/etl/migrate/20210729130353_add_etl_decision_issues_rating_issue_ref_id_index.rb
  db/etl/schema.rb
  docs/schema/caseflow-belongs_to_erd-subclasses.svg
  docs/schema/caseflow-belongs_to_erd.svg
  docs/schema/caseflow-subclasses.svg
  docs/schema/caseflow.csv
Labels: Ready-to-Merge, Source: Sentry Alert

#16563 ETLBuilderJob: send Slack message on error
  app/jobs/etl_builder_job.rb
  spec/jobs/etl_builder_job_spec.rb
Labels: Ready-to-Merge, Source: Bat Team

#16567 Make filed by va gov nullable
  db/migrate/20210729180404_make_filed_by_va_gov_nullable.rb
  db/schema.rb
  docs/schema/caseflow.csv
Labels: Ready-to-Merge

#16495 JSON Exporter: include organization admins in export
  lib/helpers/sanitized_json_configuration.rb
  spec/lib/helpers/sanitized_json_exporter_spec.rb
Labels: Ready-to-Merge

#16566 Add extra context to Sentry event for VBMS upload jobs
  app/controllers/idt/api/v1/upload_vbms_document_controller.rb
  app/jobs/upload_document_to_vbms_job.rb
  app/workflows/prepare_document_upload_to_vbms.rb
  spec/controllers/idt/api/v1/upload_vbms_document_controller_spec.rb
  spec/jobs/upload_document_to_vbms_job_spec.rb
Labels: Product: IDT, Ready-to-Merge, Source: Sentry Alert, Type: Tech-Improvement

#16509 Enable users with access to correct issues on a substitute appeal
  app/models/appellant_substitution.rb
  app/models/request_issue.rb
  client/app/intake/constants.js
  client/app/intake/pages/addIssues.jsx
  client/app/intakeEdit/IntakeEditFrame.jsx
  spec/feature/intake/higher_level_review/edit_spec.rb
  spec/models/appellant_substitution_spec.rb
  spec/models/request_issue_spec.rb
Labels: Ready-to-Merge

#16531 CASEFLOW-1499 - Do Not Allow User To Select Subsequent Hearings Docket Tasks
  client/app/queue/substituteAppellant/tasks/SubstituteAppellantTasksForm.jsx
  client/app/queue/substituteAppellant/tasks/TaskSelectionTable.jsx
  client/app/queue/substituteAppellant/tasks/utils.js
  client/test/app/queue/substituteAppellant/__snapshots__/SubstituteAppellantTasksForm.test.js.snap
  client/test/app/queue/substituteAppellant/tasks/utils.test.js
  client/test/data/queue/substituteAppellant/tasks.js
  db/seeds/sanitized_json/b5eba21a-9baf-41a3-ac1c-08470c2b79c4.json
  spec/factories/appeal.rb
Labels: Ready-to-Merge
