Repository department-of-veterans-affairs/caseflow, pull requests merged in 2021-10, with the labels that each got.

#16801 fix Update POA & Refresh POA render logic
  client/app/queue/CaseDetailsView.jsx
  client/app/queue/PowerOfAttorneyDetail.jsx
Labels: Team: Foxtrot 🦊, Ready-to-Merge

#16799 ForeignKeyPolymorphicAssociationJob: only examine VeteranClaimants
  app/jobs/foreign_key_polymorphic_association_job.rb
  app/models/appeal.rb
  app/models/concerns/belongs_to_polymorphic_appeal_concern.rb
  app/models/task.rb
  spec/jobs/foreign_key_polymorphic_association_job_spec.rb
  spec/lib/helpers/association_wrapper_spec.rb
  spec/lib/helpers/sanitized_json_exporter_spec.rb
  spec/models/concerns/belongs_to_polymorphic_appeal_concern_spec.rb
Labels: Ready-to-Merge

#16783 Updated travel board appeals to geomatch across state lines
  app/services/va_dot_gov_address_validator.rb
  client/app/hearings/components/assignHearings/AssignHearingsFields.jsx
  client/app/hearings/components/assignHearings/AssignHearingsTable.jsx
  client/app/hearings/components/scheduleHearing/TimeSlotDetail.jsx
  db/seeds/hearings.rb
  db/seeds/tasks.rb
  spec/feature/hearings/assign_hearings_table_spec.rb
  spec/jobs/hearings/geomatch_and_cache_appeal_job_spec.rb
  spec/services/va_dot_gov_address_validator_spec.rb
Labels: Team: Tango 💃, Ready-to-Merge

#16795 Docket appeal
  app/models/tasks/pre_docket/pre_docket_task.rb
  app/repositories/task_action_repository.rb
  client/COPY.json
  client/app/queue/QueueApp.jsx
  client/app/queue/components/CompleteTaskModal.jsx
  client/constants/TASK_ACTIONS.json
  spec/factories/user.rb
  spec/feature/queue/docket_switch_spec.rb
  spec/feature/queue/pre_docket_spec.rb
  spec/models/tasks/pre_docket_task_spec.rb
Labels: Ready-to-Merge, Team Victor

#16804 Add Additional Groups to POA Feature Release
  app/models/user.rb
  app/views/queue/index.html.erb
  client/app/queue/CaseDetailsView.jsx
  client/app/queue/QueueApp.jsx
  spec/models/user_spec.rb
Labels: Ready-to-Merge

#16798 tree renderer: show inactive org assignee
  app/models/concerns/task_tree_render_module.rb
  spec/models/concerns/task_tree_render_module_spec.rb
Labels: Ready-to-Merge

#16812 Create vha_predocket_workflow FeatureToggle
  app/models/tasks/pre_docket/vha_document_search_task.rb
  app/views/queue/index.html.erb
  spec/feature/queue/pre_docket_spec.rb
  spec/models/tasks/vha_document_search_task_spec.rb
Labels: Ready-to-Merge

#16814 Remove outdated caregiver labels
  app/controllers/api/docs/v3/decision_reviews.yaml
  client/constants/ISSUE_CATEGORIES.json
  client/constants/ISSUE_INFO.json
Labels: Ready-to-Merge

#16771 Set participant_id to empty string for OtherClaimants
  app/models/decision_review_intake.rb
  spec/models/appeal_intake_spec.rb
Labels: Ready-to-Merge

#16813 Explain page: enable using record id in URL
  app/controllers/explain_controller.rb
  spec/feature/explain_spec.rb
Labels: Ready-to-Merge

#16819 Add service method to get facility ids from va.gov
  app/services/external_api/va_dot_gov_service.rb
  app/services/external_api/va_dot_gov_service/facilities_ids_response.rb
  lib/fakes/va_dot_gov_service.rb
  spec/services/external_api/va_dot_gov_service_spec.rb
Labels: Ready-to-Merge

#16824 Limit CaseIssue.issdesc to 100 ASCII characters
  app/models/vacols/case_issue.rb
Labels: Ready-to-Merge

#16822 Explain page: add task versions (PaperTrail)
  app/controllers/explain_controller.rb
  app/models/task.rb
  app/views/explain/_task_versions.html.erb
  app/views/explain/show.html.erb
  spec/feature/explain_spec.rb
Labels: Ready-to-Merge

#16891 Caseflow-2289 | Do away with ACD#distribute_appeals
  app/models/concerns/automatic_case_distribution.rb
  app/models/dockets/legacy_docket.rb
  spec/models/distribution_spec.rb
  spec/models/dockets/legacy_docket_spec.rb
Labels: Ready-to-Merge

#16898 check_task_tree: check for unexpected parent and child tasks
  app/queries/appeals_with_no_tasks_or_all_tasks_on_hold_query.rb
  lib/helpers/check_task_tree.rb
  spec/lib/helpers/check_task_tree_spec.rb
Labels: Ready-to-Merge
