Repository department-of-veterans-affairs/caseflow, pull requests merged in 2021-02, with the labels that each got.

#15859 Limit VirtualHearing VACOLS query to 1000 for Performance
  app/repositories/virtual_hearing_repository.rb
Labels: Ready-to-Merge

#15849 Add date_of_death_reported_at to track when veteran date_of_death changes
  app/models/veteran.rb
  db/migrate/20210126194054_add_date_of_death_reported_at_to_veteran.rb
  db/schema.rb
  docs/schema/caseflow.csv
  spec/models/veteran_spec.rb
Labels: Feature: FNOD, Ready-to-Merge, Team: X-ray 💀

#15844 Optimize query in Reader::DocumentsController
  app/controllers/reader/documents_controller.rb
  spec/controllers/reader/documents_controller_spec.rb
  spec/services/document_fetcher_spec.rb
Labels: Eng: Performance, Product: caseflow-reader, Ready-to-Merge, Team: Echo 🐬

#15845 CASEFLOW-419 AddCavcDatesModal
  client/COPY.json
  client/app/queue/AddCavcDatesModal.jsx
  client/app/queue/AddCavcDatesModal.stories.js
  client/test/app/queue/AddCavcDatesModal.test.js
  client/test/app/queue/AddCavcRemandView.test.js
  client/test/app/queue/__snapshots__/AddCavcDatesModal.test.js.snap
Labels: Ready-to-Merge, Team: Echo 🐬

#15863 Allow 5 minutes for Reader page to load documents
  client/app/reader/ReaderLoadingScreen.jsx
Labels: Product: caseflow-reader, Ready-to-Merge

#15867 Refactor virtual hearing repository queries
  app/jobs/virtual_hearings/delete_conferences_job.rb
  app/repositories/virtual_hearing_repository.rb
  app/services/stuck_virtual_hearings_checker.rb
  spec/repositories/virtual_hearing_repository_spec.rb
Labels: Ready-to-Merge, Source: Bat Team, Team: Tango 💃

#15818 FactoryBot: randomize Veterans' last name
  lib/fakes/bgs_service_record_maker.rb
  spec/controllers/idt/api/appeals_controller_spec.rb
  spec/controllers/idt/api/veterans_controller_spec.rb
  spec/factories/veteran.rb
  spec/feature/hearings/postpone_hearing_spec.rb
  spec/feature/hearings/schedule_veteran/build_hearsched_spec.rb
  spec/feature/intake/veteran_name_caching_spec.rb
  spec/feature/queue/task_queue_spec.rb
  spec/jobs/virtual_hearings/send_email_spec.rb
  spec/models/veteran_spec.rb
Labels: Ready-to-Merge

#15850 Added condition to remove bullets for new virtual hearing links
  app/models/hearings/virtual_hearing.rb
  app/views/virtual_hearing_mailer/sections/_test_your_connection.html.erb
Labels: Ready-to-Merge

#15872 Change withdrawn back to cancelled
  client/app/hearings/constants.js
  client/constants/HEARING_DISPOSITION_TYPE_TO_LABEL_MAP.json
Labels: Ready-to-Merge

#15706 Fix logic for not sending cancellation emails if hearing is cancelled or postponed
  app/jobs/virtual_hearings/delete_conferences_job.rb
  app/models/concerns/hearing_concern.rb
  app/models/hearings/forms/base_hearing_update_form.rb
  spec/jobs/virtual_hearings/delete_conferences_job_spec.rb
Labels: Ready-to-Merge

#15846 Hide mandate and judgement date for MDR
  client/COPY.json
  client/app/queue/AddCavcRemandView.jsx
Labels: Ready-to-Merge, Team: Echo 🐬

#15866 Create IHP tasks when evidence submission window tasks are manually completed
  app/models/tasks/evidence_submission_window_task.rb
  spec/models/tasks/evidence_submission_window_task_spec.rb
Labels: Ready-to-Merge, Team: Echo 🐬

#15874 Refactor: clarify VACOLS user is judge but not acting judge
  app/models/queues/legacy_work_queue.rb
  app/models/user.rb
  app/repositories/user_repository.rb
  spec/models/user_spec.rb
Labels: Ready-to-Merge, Team: Echo 🐬

#15882 Prevent selection of current docket on DocketSwitchReviewRequestForm
  client/app/queue/docketSwitch/grant/DocketSwitchReviewRequestContainer.jsx
  client/app/queue/docketSwitch/grant/DocketSwitchReviewRequestForm.jsx
  client/app/queue/docketSwitch/grant/DocketSwitchReviewRequestForm.stories.js
  client/test/app/queue/docketSwitch/DocketSwitchReviewRequestForm.test.js
Labels: Ready-to-Merge, Team: Foxtrot 🦊

#15864 Save unlisted appellant data to DB
  app/models/attorney_claimant.rb
  app/models/claimant.rb
  app/models/decision_review_intake.rb
  app/models/dependent_claimant.rb
  app/models/other_claimant.rb
  app/models/unrecognized_appellant.rb
  app/models/unrecognized_party_detail.rb
  app/models/validators/other_claimant_validator.rb
  app/schemas/controller_schema.rb
  app/schemas/intakes_schemas.rb
  db/migrate/20210205194714_change_party_type_comment.rb
  db/schema.rb
  spec/factories/unrecognized_party_detail.rb
  spec/models/appeal_intake_spec.rb
  spec/models/other_claimant_spec.rb
  spec/models/unrecognized_appellant_spec.rb
  spec/models/unrecognized_party_detail_spec.rb
Labels: Ready-to-Merge

#15848 Implement Docket Switch Review/Confirm (Grant)
  app/models/serializers/work_queue/appeal_serializer.rb
  client/COPY.json
  client/app/queue/docketSwitch/grant/CheckoutButtons.jsx
  client/app/queue/docketSwitch/grant/DocketSwitchGrantContainer.jsx
  client/app/queue/docketSwitch/grant/DocketSwitchReviewConfirm.jsx
  client/app/queue/docketSwitch/grant/DocketSwitchReviewConfirm.stories.js
  client/app/queue/docketSwitch/grant/DocketSwitchReviewConfirmContainer.jsx
  client/app/queue/docketSwitch/grant/DocketSwitchReviewRequestForm.jsx
  client/package.json
  client/test/app/queue/docketSwitch/grant/DocketSwitchReviewConfirm.test.js
  client/test/app/queue/docketSwitch/grant/__snapshots__/DocketSwitchReviewConfirm.test.js.snap
  client/yarn.lock
  spec/feature/queue/docket_switch_spec.rb
Labels: Ready-to-Merge, Team: Foxtrot 🦊

#15856 Switch from React Hot Loader to React Refresh
  client/app/hearings/index.jsx
  client/app/index.js
  client/app/intake/IntakeFrame.jsx
  client/app/intakeEdit/IntakeEditFrame.jsx
  client/app/queue/QueueApp.jsx
  client/babel.config.js
  client/package.json
  client/webpack-hot-server.js
  client/webpack.config.js
  client/webpack.hot.config.js
  client/yarn.lock
Labels: Eng: Frontend Work Group, Ready-to-Merge, Type: Tech-Improvement

#15858 Add Nod Date Update Timeline Component to Case Timeline
  app/models/appeal.rb
  app/models/serializers/work_queue/appeal_serializer.rb
  client/COPY.json
  client/app/queue/components/EditNodDateModal.jsx
  client/app/queue/components/NodDateUpdateTimeline.jsx
  client/app/queue/components/NodDateUpdateTimeline.stories.js
  client/app/queue/components/NodDateUpdateTimeline.test.js
  client/app/queue/components/TaskRows.jsx
  client/app/queue/components/__snapshots__/NodDateUpdateTimeline.test.js.snap
  client/app/queue/utils.js
  spec/feature/queue/case_details_spec.rb
Labels: Feature: Edit NOD, Ready-to-Merge, Team: X-ray 💀

#15884 Update vc.va.gov test URL
  app/models/hearings/virtual_hearing.rb
  spec/models/hearings/virtual_hearing_spec.rb
Labels: Ready-to-Merge

#15883 Store original hearing request type on appeals and legacy appeals
  app/models/concerns/hearing_request_type_concern.rb
  app/models/tasks/change_hearing_request_type_task.rb
  app/models/tasks/schedule_hearing_task.rb
  app/services/cached_appeal_service.rb
  spec/models/legacy_appeal_spec.rb
Labels: Team: Tango 💃

#15875 Docket Switch | Edit Tasks w/o Existing Tasks
  client/COPY.json
  client/app/queue/docketSwitch/grant/DocketSwitchEditTasksForm.jsx
  client/app/queue/docketSwitch/grant/DocketSwitchEditTasksForm.stories.js
  client/test/app/queue/docketSwitch/DocketSwitchEditTasksForm.test.js
  client/test/app/queue/docketSwitch/__snapshots__/DocketSwitchEditTasksForm.test.js.snap
Labels: Ready-to-Merge, Team: Foxtrot 🦊

#15847 Added functionality to convert hearing requests between all types
  app/jobs/hearings/geomatch_and_cache_appeal_job.rb
  app/models/concerns/hearing_request_type_concern.rb
  app/models/tasks/change_hearing_request_type_task.rb
  app/models/tasks/schedule_hearing_task.rb
  app/repositories/appeal_repository.rb
  app/services/cached_appeal_service.rb
  client/COPY.json
  client/app/hearings/components/HearingTypeConversion.jsx
  client/app/hearings/components/HearingTypeConversionModal.jsx
  client/app/hearings/components/HearingTypeConversionModal.stories.js
  client/app/hearings/utils.js
  client/app/queue/QueueActions.js
  client/app/queue/QueueApp.jsx
  client/app/queue/constants.js
  client/app/queue/reducers.js
  client/constants/TASK_ACTIONS.json
  client/test/app/hearings/components/HearingTypeConversionModal.test.js
  client/test/app/hearings/components/__snapshots__/HearingTypeConversionModal.test.js.snap
  db/migrate/20210205182635_add_original_request_type_to_appeal.rb
  db/migrate/20210205182649_add_original_request_type_to_legacy_appeal.rb
  db/migrate/20210205183027_update_change_request_type_comments_on_legacy_appeals.rb
  db/schema.rb
  docs/schema/caseflow.csv
  spec/feature/hearings/convert_hearing_request_type/edit_hearsched_spec.rb
  spec/jobs/hearings/geomatch_and_cache_appeal_job_spec.rb
  spec/models/legacy_appeal_spec.rb
  spec/models/tasks/change_hearing_request_type_task_spec.rb
Labels: Ready-to-Merge, Team: Tango 💃

#15886 Remove Unused Hearings Code
  app/models/appeal.rb
  app/models/user.rb
  app/models/vacols/travel_board_schedule.rb
  app/repositories/hearing_repository.rb
  app/workflows/hearing_request_case_distributor.rb
Labels: Ready-to-Merge

#15888 Update Storybook for Fast Refresh
  client/.storybook/main.js
  client/.storybook/preview.js
  client/app/components/Actions.stories.js
  client/app/components/UserDropdownMenu.stories.js
  client/package.json
  client/webpack.config.js
  client/yarn.lock
Labels: Eng: Frontend Work Group, Ready-to-Merge, Type: Tech-Improvement

#15892 Remove additional unused hearings code
  app/models/appeal.rb
  app/models/legacy_appeal.rb
  app/models/worksheet_issue.rb
Labels: Ready-to-Merge, Team: Tango 💃

#15860 Adds the Remand Received action to MDR & MandateHold Tasks
  app/controllers/cavc_remands_controller.rb
  app/models/cavc_remand.rb
  app/models/tasks/mandate_hold_task.rb
  app/models/tasks/mdr_task.rb
  client/app/queue/AddCavcDatesModal.jsx
  client/app/queue/QueueApp.jsx
  client/constants/TASK_ACTIONS.json
  config/routes.rb
  lib/caseflow/error.rb
  spec/controllers/cavc_remands_controller_spec.rb
  spec/factories/cavc_remand.rb
  spec/models/cavc_remand_spec.rb
  spec/models/tasks/mandate_hold_task_spec.rb
  spec/models/tasks/mdr_task_spec.rb
Labels: Ready-to-Merge, Team: Echo 🐬

#15896 Remove unused method in UserReporter
  app/services/user_reporter.rb
Labels: Ready-to-Merge, Team: Echo 🐬

#15897 Remove wholly unused method in task.rb
  app/models/task.rb
Labels: Ready-to-Merge, Team: Echo 🐬

#15900 Upgrade Rails to 5.2.4.5 to address CVE-2021-22880
  Gemfile
  Gemfile.lock
Labels: Eng: Dependencies

#15895 more efficient appeals caching
  app/models/concerns/hearing_request_type_concern.rb
  app/models/tasks/change_hearing_request_type_task.rb
  app/services/cached_appeal_service.rb
  spec/models/legacy_appeal_spec.rb
Labels: Ready-to-Merge, Source: Bat Team, Team: Tango 💃

#15881 CASEFLOW-96 and -282 bugfixes
  client/COPY.json
  client/app/queue/AddCavcRemandView.jsx
  client/test/app/queue/AddCavcRemandView.test.js
Labels: Ready-to-Merge, Team: Echo 🐬

#15906 Update schema and docs
  db/schema.rb
  docs/schema/caseflow.csv
Labels: Ready-to-Merge

#15889 Fix case detail page crash for nod date timeline updates
  app/controllers/nod_date_updates_controller.rb
  app/models/serializers/work_queue/appeal_serializer.rb
  app/models/serializers/work_queue/nod_date_update_serializer.rb
  app/views/queue/index.html.erb
  client/app/queue/QueueActions.js
  client/app/queue/TaskSnapshot.jsx
  client/app/queue/components/EditNodDateModal.jsx
  client/app/queue/components/NodDateUpdateTimeline.jsx
  client/app/queue/components/NodDateUpdateTimeline.test.js
  client/app/queue/components/TaskRows.jsx
  client/app/queue/constants.js
  client/app/queue/reducers.js
  client/app/queue/utils.js
  spec/feature/queue/case_details_spec.rb
  spec/models/serializers/work_queue/nod_date_update_serializer_spec.rb
Labels: Feature: Edit NOD, Type: Bug

#15899 CASEFLOW-138 Propagate task instructions when task is bulk assigned
  app/workflows/bulk_task_assignment.rb
  spec/workflows/bulk_task_assignment_spec.rb
Labels: Ready-to-Merge, Team: Echo 🐬

#15885 CASEFLOW-808 Add more actions during CAVC-Remand-Processed-Letter Response Window task
  app/models/tasks/cavc_remand_processed_letter_response_window_task.rb
  app/models/tasks/send_cavc_remand_processed_letter_task.rb
  spec/factories/cavc_remand.rb
  spec/feature/queue/cavc_task_queue_spec.rb
  spec/models/tasks/cavc_remand_processed_letter_response_window_task_spec.rb
Labels: Ready-to-Merge, Team: Echo 🐬

#15904 CASEFLOW-676 CAVC input fields: show error on future date selection
  client/COPY.json
  client/app/queue/AddCavcDatesModal.jsx
  client/app/queue/AddCavcRemandView.jsx
  client/test/app/queue/AddCavcDatesModal.test.js
  client/test/app/queue/AddCavcRemandView.test.js
Labels: Ready-to-Merge, Team: Echo 🐬

#15907 Adds JMPR and MDR Feature tests
  spec/feature/queue/cavc_task_queue_spec.rb
Labels: Ready-to-Merge

#15908 Add date of death to FNOD badge
  client/app/queue/components/FnodBadge.jsx
  client/app/queue/components/FnodBadge.stories.js
  client/app/queue/components/FnodBadge.test.js
  client/app/queue/components/__snapshots__/FnodBadge.test.js.snap
Labels: Feature: FNOD, Ready-to-Merge, Team: X-ray 💀

#15911 Create DocketSwitchRulingTask on RootTask
  app/models/tasks/docket_switch/docket_switch_ruling_task.rb
  client/app/queue/docketSwitch/recommendDocketSwitch/RecommendDocketSwitchContainer.jsx
  spec/feature/queue/docket_switch_spec.rb
Labels: Ready-to-Merge

#15891 Non-Veteran Claimants | Ability to add an unlisted claimant's POA
  client/COPY.json
  client/app/intake/addPOA/AddPoaPage.jsx
  client/app/intake/addPOA/AddPoaPage.stories.js
  client/app/intake/addPOA/utils.js
  client/app/intake/components/IntakeProgressBar.jsx
  client/test/app/intake/components/AddPoaPage.test.js
  client/test/app/intake/components/__snapshots__/AddPoaPage.test.js.snap
  spec/feature/intake/non_veteran_claimants_spec.rb
Labels: Ready-to-Merge

#15916 Non-Veteran Claimants | Ability to add an unlisted claimant's POA
  client/app/intake/addPOA/AddPoaPage.jsx
  spec/feature/intake/non_veteran_claimants_spec.rb
Labels: Ready-to-Merge

#15913 Add Straight Reversal to CAVC Entry Form
  client/COPY.json
  client/app/queue/AddCavcRemandView.jsx
  client/test/app/queue/AddCavcRemandView.test.js
  client/test/app/queue/__snapshots__/AddCavcRemandView.test.js.snap
  spec/feature/queue/cavc_task_queue_spec.rb
Labels: Ready-to-Merge, Team: Echo 🐬

#15914 Refactor hearing request type concern
  app/models/concerns/hearing_request_type_concern.rb
  app/models/serializers/work_queue/appeal_serializer.rb
  app/models/serializers/work_queue/legacy_appeal_serializer.rb
  app/models/tasks/change_hearing_request_type_task.rb
  app/services/cached_appeal_service.rb
  spec/feature/queue/case_details_spec.rb
  spec/models/appeal_spec.rb
  spec/models/concerns/hearing_request_type_concern_spec.rb
  spec/models/legacy_appeal_spec.rb
Labels: Ready-to-Merge, Team: Tango 💃, Type: Tech-Improvement

#15862 Paula/Caseflow-535 Timeliness failure for edit NOD date
  app/controllers/nod_date_updates_controller.rb
  app/models/appeal.rb
  app/models/nod_date_update.rb
  client/COPY.json
  client/app/queue/components/EditNodDateModal.jsx
  client/test/app/queue/components/EditNodDateModal.test.js
  client/test/app/queue/components/__snapshots__/EditNodDateModal.test.js.snap
  spec/feature/queue/case_details_spec.rb
  spec/models/appeal_spec.rb
  spec/models/nod_date_update_spec.rb
Labels: Feature: Edit NOD, Ready-to-Merge, Team: X-ray 💀

#15917 Add analytics events for Schedule Veteran
  client/app/hearings/components/ScheduleVeteran.jsx
  client/test/app/jestSetup.js
Labels: Ready-to-Merge

#15909 Edit EP Claim Labels | Update Benefit Type
  app/models/claim_review.rb
  app/models/end_product_update.rb
  app/models/higher_level_review.rb
  client/test/app/queue/AddCavcDatesModal.test.js
  client/test/app/queue/AddCavcRemandView.test.js
  spec/factories/end_product_update.rb
  spec/models/end_product_update_spec.rb
  spec/models/validators/intake_start_validator_spec.rb
Labels: Ready-to-Merge, Team: Foxtrot 🦊

#15918 Create granted/deny task subtree under ruling task
  app/controllers/docket_switches_controller.rb
  app/models/docket_switch.rb
  app/models/organizations/clerk_of_the_board.rb
  app/models/tasks/docket_switch/docket_switch_abstract_attorney_task.rb
  app/schemas/docket_switches_schemas.rb
  app/workflows/docket_switch/address_ruling.rb
  app/workflows/docket_switch/task_handler.rb
  client/COPY.json
  client/app/queue/docketSwitch/judgeRuling/DocketSwitchRulingContainer.jsx
  client/app/queue/docketSwitch/judgeRuling/docketSwitchRulingSlice.js
  config/routes.rb
  spec/feature/queue/docket_switch_spec.rb
  spec/workflows/docket_switch_task_handler_spec.rb
Labels: Ready-to-Merge

#15901 Confirmation Modal for Add Claimant Process
  client/COPY.json
  client/app/components/AddressForm.jsx
  client/app/components/ProgressBar.jsx
  client/app/components/SearchableDropdown.jsx
  client/app/constants/AppConstants.js
  client/app/intake/actions/decisionReview.js
  client/app/intake/addClaimant/AddClaimantConfirmationModal.jsx
  client/app/intake/addClaimant/AddClaimantConfirmationModal.stories.js
  client/app/intake/addClaimant/AddClaimantForm.jsx
  client/app/intake/addClaimant/AddClaimantForm.stories.js
  client/app/intake/addClaimant/AddClaimantPage.jsx
  client/app/intake/addClaimant/AddressBlock.jsx
  client/app/intake/addClaimant/utils.js
  client/app/intake/addPOA/AddPoaPage.jsx
  client/app/intake/addPOA/utils.js
  client/app/intake/components/IntakeLayout.jsx
  client/app/intake/index.js
  client/app/intake/reducers/addClaimantSlice.js
  client/test/app/intake/components/__snapshots__/AddPoaPage.test.js.snap
  client/test/app/intake/components/addClaimants/AddClaimantConfirmationModal.test.js
  client/test/app/intake/components/addClaimants/AddClaimantForm.test.js
  client/test/app/intake/components/addClaimants/AddClaimantPage.test.js
  client/test/app/intake/components/addClaimants/__snapshots__/AddClaimantConfirmationModal.test.js.snap
  client/test/app/intake/components/addClaimants/__snapshots__/AddClaimantForm.test.js.snap
  client/test/app/intake/components/addClaimants/__snapshots__/AddClaimantPage.test.js.snap
  client/test/app/intake/components/addClaimants/testUtils.js
  client/test/data/intake/claimants.js
  spec/feature/intake/non_veteran_claimants_spec.rb
Labels: Ready-to-Merge, Team: Foxtrot 🦊

#15919 CASEFLOW-1021 update edit NOD date failure message
  client/COPY.json
  client/app/queue/components/EditNodDateModal.jsx
  spec/feature/queue/case_details_spec.rb
Labels: Feature: Edit NOD, Ready-to-Merge, Team: X-ray 💀

#15910 Intake | Docket Change | Docket switch success banner
  app/controllers/docket_switches_controller.rb
  app/models/docket_switch.rb
  client/COPY.json
  client/app/queue/docketSwitch/grant/DocketSwitchReviewConfirm.jsx
  client/app/queue/docketSwitch/grant/DocketSwitchReviewConfirmContainer.jsx
  client/test/app/queue/docketSwitch/grant/__snapshots__/DocketSwitchReviewConfirm.test.js.snap
  spec/feature/queue/docket_switch_spec.rb
Labels: Ready-to-Merge

#15616 Improves factories and seeds around MTV
  db/seeds/mtv.rb
  spec/factories/appeal.rb
  spec/seeds/mtv_spec.rb
Labels: Ready-to-Merge

#15923 cavc_remands table: add federal circuit boolean
  db/migrate/20210222214631_add_cavc_mdr_federal_circuit.rb
  db/schema.rb
  docs/schema/caseflow.csv
Labels: Ready-to-Merge, Team: Echo 🐬

#15924 CASEFLOW-942 Add Federal Circuit question to MDR CAVC entry form
  client/COPY.json
  client/app/queue/AddCavcRemandView.jsx
  spec/feature/queue/cavc_task_queue_spec.rb
Labels: Team: Echo 🐬

#15933 Updates timeliness check for edit NOD date
  app/models/request_issue.rb
  client/app/queue/components/EditNodDateModal.jsx
  spec/models/appeal_spec.rb
Labels: Feature: Edit NOD, Ready-to-Merge

#15928 CASEFLOW-942 Require Federal Circuit parameter for CAVC Remand controller and model
  app/controllers/cavc_remands_controller.rb
  app/models/cavc_remand.rb
  client/COPY.json
  client/app/queue/AddCavcRemandView.jsx
  client/app/queue/CavcDetail.jsx
  spec/controllers/cavc_remands_controller_spec.rb
  spec/factories/cavc_remand.rb
  spec/feature/queue/cavc_task_queue_spec.rb
  spec/models/cavc_remand_spec.rb
Labels: Ready-to-Merge, Team: Echo 🐬

#15915 Add smart date population of judgement and mandate dates for CAVC remands
  client/COPY.json
  client/app/queue/AddCavcRemandView.jsx
  client/test/app/queue/AddCavcRemandView.test.js
  client/test/app/queue/__snapshots__/AddCavcRemandView.test.js.snap
  spec/feature/queue/cavc_task_queue_spec.rb
Labels: Ready-to-Merge, Team: Echo 🐬

#15929 Misc Fixes for Add Claimant/POA Confirmation
  client/app/intake/addClaimant/AddClaimantConfirmationModal.jsx
  client/app/intake/addClaimant/AddClaimantForm.jsx
  client/app/intake/addClaimant/AddClaimantForm.stories.js
  client/app/intake/addClaimant/AddClaimantPage.jsx
  client/app/intake/addClaimant/AddClaimantPage.stories.js
  client/app/intake/addClaimant/AddressBlock.jsx
  client/app/intake/addClaimant/utils.js
  client/test/app/intake/components/addClaimants/AddClaimantConfirmationModal.test.js
Labels: Ready-to-Merge

#15927 Add panel/clerk/per curium options to AddCavcRemandView judge selector
  client/constants/CAVC_JUDGE_FULL_NAMES.json
  client/test/app/queue/__snapshots__/AddCavcRemandView.test.js.snap
Labels: Ready-to-Merge, Team: Echo 🐬

#15943 Correctly set new stream's docket type and redirect to it
  app/controllers/docket_switches_controller.rb
  app/models/docket_switch.rb
  app/models/serializers/work_queue/docket_switch_serializer.rb
  client/app/queue/docketSwitch/docketSwitchSlice.js
  client/app/queue/docketSwitch/grant/DocketSwitchReviewConfirmContainer.jsx
  spec/feature/queue/docket_switch_spec.rb
  spec/models/docket_switch_spec.rb
Labels: Ready-to-Merge
