Repository department-of-veterans-affairs/caseflow, pull requests merged in 2021-06, with the labels that each got.

#16311 Sanitized JSON Exporter: remove assigned_by_id when exporting Organizations
  lib/helpers/sanitized_json_configuration.rb
Labels: Ready-to-Merge

#16291 Refactor intake forms to add Yup validations
  client/app/intake/IntakeFrame.jsx
  client/app/intake/components/BenefitType.jsx
  client/app/intake/components/LegacyOptInApproved.jsx
  client/app/intake/components/SelectClaimant.jsx
  client/app/intake/constants.js
  client/app/intake/pages/appeal/review.jsx
  client/app/intake/pages/higherLevelReview/review.jsx
  client/app/intake/pages/rampElection/review.jsx
  client/app/intake/pages/rampRefiling/review.jsx
  client/app/intake/pages/receiptDateInput.jsx
  client/app/intake/pages/review.jsx
  client/app/intake/pages/supplementalClaim/review.jsx
  client/test/app/intake/pages/review.test.js
Labels: Ready-to-Merge

#16304 Add Decision Issue and End Product Establishment FK to Request Issues table
  db/migrate/20210601143548_add_decision_issue_end_product_establishment_foreign_keys_for_request_issues.rb
  db/migrate/20210601143622_validate_decision_issue_end_product_establishment_foreign_keys_for_request_issues.rb
  db/schema.rb
  lib/helpers/sanitized_json_configuration.rb
  spec/models/request_issue_spec.rb
Labels: Ready-to-Merge

#16312 Add intake form generator
  client/app/intake/pages/appeal/review.jsx
  client/app/intake/pages/formGenerator.jsx
  client/app/intake/pages/higherLevelReview/review.jsx
  client/app/intake/pages/review.jsx
Labels: Ready-to-Merge

#16313 Add foreign key to EndProductCodeUpdate table
  db/migrate/20210602145220_add_foreign_key_for_end_product_code_update.rb
  db/migrate/20210602145330_validate_foreign_key_for_end_product_code_update.rb
  db/schema.rb
Labels: Ready-to-Merge

#16303 Clear POA cache when attempting to refresh with button
  app/controllers/appeals_controller.rb
  spec/controllers/appeals_controller_spec.rb
  spec/feature/queue/case_details_spec.rb
Labels: Ready-to-Merge

#16329 Use plain JS to get the last element of vetName
  client/app/queue/components/TaskTableColumns.jsx
Labels: Ready-to-Merge

#16321 Add supplemental claim review
  client/app/intake/pages/review.jsx
  client/app/intake/pages/supplementalClaim/review.jsx
Labels: Ready-to-Merge

#16332 Fix broken TimeSlotCard Story
  client/app/hearings/components/assignHearings/LinkToAppeal.jsx
  client/app/hearings/components/assignHearings/TimeSlotCard.stories.js
Labels: Ready-to-Merge

#16327 Add Foreign Keys to DocketTracer, NonAvailability, UserQuota, and RampElectionRollback tables
  db/migrate/20210604133423_add_docket_tracer_non_availability_user_quota_ramp_election_rollback_fk.rb
  db/migrate/20210604133455_validate_docket_tracer_non_availability_user_quota_ramp_election_rollback_fk.rb
  db/schema.rb
Labels: Eng: Data Work Group

#16331 Allow death dismissal streamlining only when deceased veteran is appellant
  app/workflows/initial_tasks_factory.rb
  spec/workflows/initial_tasks_factory_spec.rb
Labels: Ready-to-Merge

#16325 Narrative: extract task data for table
  app/assets/stylesheets/explain_appeal.css
  app/controllers/concerns/explain/appeal_record_event_mapper.rb
  app/controllers/concerns/explain/decision_document_record_event_mapper.rb
  app/controllers/concerns/explain/decision_issue_record_event_mapper.rb
  app/controllers/concerns/explain/hearing_record_event_mapper.rb
  app/controllers/concerns/explain/intake_record_event_mapper.rb
  app/controllers/concerns/explain/record_event_mapper.rb
  app/controllers/concerns/explain/request_issue_record_event_mapper.rb
  app/controllers/concerns/explain/task_record_event_mapper.rb
  app/controllers/concerns/explain_appeal_events_concern.rb
  app/controllers/explain_controller.rb
  app/views/explain/show.html.erb
  spec/feature/explain_spec.rb
Labels: Eng: Data Work Group, Ready-to-Merge

#16335 Add method for AttorneyPowerOfAttorney to prevent noise on job
  app/models/attorney_power_of_attorney.rb
  app/models/unrecognized_power_of_attorney.rb
Labels: Ready-to-Merge

#16336 Explain endpoint: Replace jquery with non-jquery queries
  .gitignore
  app/assets/javascripts/explain-appeal.js
  app/views/explain/show.html.erb
Labels: Ready-to-Merge

#16333 Add reminder to check for missing foreign keys
  Gemfile
  Gemfile.lock
  Makefile.example
  PULL_REQUEST_TEMPLATE.md
  config/initializers/immigrant.rb
  lib/helpers/association_wrapper.rb
Labels: Ready-to-Merge

#16334 Use form generator for RAMP election form page
  client/app/intake/pages/formGenerator.jsx
  client/app/intake/pages/rampElection/review.jsx
  client/app/intake/pages/receiptDateInput.jsx
  client/app/intake/pages/review.jsx
Labels: Ready-to-Merge, Type: Tech-Improvement

#16342 Log info in BgsPowerOfAttorney after_save during attempted IHP task update
  app/models/bgs_power_of_attorney.rb
Labels: Ready-to-Merge, Team Victor

#16337 Narrative: improve presentation of events table
  app/assets/stylesheets/explain_appeal.css
  app/controllers/concerns/explain/appeal_record_event_mapper.rb
  app/controllers/concerns/explain/hearing_record_event_mapper.rb
  app/controllers/concerns/explain/record_event_mapper.rb
  app/controllers/explain_controller.rb
  app/views/explain/show.html.erb
Labels: Eng: Data Work Group, Ready-to-Merge

#16343 Remove sentry alert from BgsPowerOfAttorney#update_ihp_enabled
  app/models/bgs_power_of_attorney.rb
Labels: Ready-to-Merge

#16345 Block grants/remands for unrecognized appellants
  app/models/decision_document.rb
  spec/models/decision_document_spec.rb
Labels: Ready-to-Merge

#16340 Add form generator for ramp refiling
  client/app/intake/pages/formGenerator.jsx
  client/app/intake/pages/rampRefiling/review.jsx
  client/app/intake/pages/review.jsx
  spec/feature/intake/ramp_refiling_spec.rb
Labels: Ready-to-Merge

#16299 Mkerns/caseflow 1611 unrecognized appellant btn hide
  app/models/serializers/work_queue/appeal_serializer.rb
  client/app/queue/PowerOfAttorneyDetail.jsx
  client/app/queue/components/PoaRefresh.jsx
  client/app/queue/utils.js
  spec/feature/queue/case_details_spec.rb
Labels: Ready-to-Merge

#16350 Fetch IHP update appeals by claimant_participant_id
  app/models/bgs_power_of_attorney.rb
  spec/models/bgs_power_of_attorney_spec.rb
Labels: Ready-to-Merge

#16359 Open Narrative Table link in test
  app/views/explain/show.html.erb
  spec/feature/explain_spec.rb
Labels: Ready-to-Merge

#16297 Import some realistic appeals
  db/seeds.rb
  db/seeds/sanitized_json/appeal_ready_for_substitution_1.json
  db/seeds/sanitized_json/appeal_ready_for_substitution_2.json
  db/seeds/sanitized_json/appeal_ready_for_substitution_3.json
  db/seeds/sanitized_json/appeal_ready_for_substitution_4.json
  db/seeds/sanitized_json_seeds.rb
  lib/helpers/sanitized_json_configuration.rb
  spec/seeds/sanitized_json_seeds_spec.rb
Labels: Team: Echo 🐬

#16347 Update karma and version of frontend toolkit
  client/package.json
  client/yarn.lock
Labels: Eng: Dependencies

#16363 Post PushPriorityAppealsToJudgesJob error to Slack
  app/jobs/push_priority_appeals_to_judges_job.rb
  spec/jobs/push_priority_appeals_to_judges_job_spec.rb
Labels: Ready-to-Merge

#16366 Add Foreign Keys to hearing_appeals_stream_snapshot table
  db/migrate/20210615170231_add_appeal_stream_snapshot_f_ks.rb
  db/migrate/20210615170300_validate_appeal_stream_snapshot_f_ks.rb
  db/schema.rb
Labels: Eng: Data Work Group

#16370 Annotate PII columns in schema
  db/migrate/20210615221829_add_pii_comment_on_pii_columns.rb
  db/schema.rb
  docs/schema/caseflow.csv
  lib/helpers/sanitized_json_configuration.rb
  spec/lib/helpers/sanitized_json_exporter_spec.rb
Labels: Ready-to-Merge

#16364 Add CAMO org
  app/models/organizations/vha_camo.rb
Labels: Ready-to-Merge, Team Victor

#16373 Support claim label for SCs with issues decided > 1 year ago
  app/models/end_product.rb
  app/workflows/end_product_code_selector.rb
  client/constants/END_PRODUCT_CODES.json
  spec/workflows/end_product_code_selector_spec.rb
Labels: Ready-to-Merge

#16362 Confirm evidence submission window doesn't exceed 90 days
  app/models/bgs_power_of_attorney.rb
  client/app/queue/substituteAppellant/review/SubstituteAppellantReview.jsx
  client/app/queue/substituteAppellant/review/SubstituteAppellantReviewContainer.jsx
  client/app/queue/substituteAppellant/tasks/utils.js
  client/test/app/queue/substituteAppellant/tasks/utils.test.js
Labels: Ready-to-Merge

#16380 Adds claim label for SCs with issues decided > 1 year ago to json file
  client/constants/EP_CLAIM_TYPES.json
Labels: Ready-to-Merge

#16382 RSpec to replicate duplicate JudgeAssignTasks problem
  spec/fixes/investigate_duplicate_judge_assign_task_spec.rb
  spec/records/appeal-121304-dup_jatasks.json
Labels: Team: Echo 🐬

#16378 Adjust validation in SubstituteAppellantBasicsForm to enforce substitution date after both NOD date & date of death
  client/app/queue/substituteAppellant/basics/SubstituteAppellantBasicsForm.jsx
  client/app/queue/substituteAppellant/basics/SubstituteAppellantBasicsForm.stories.js
  client/app/queue/substituteAppellant/basics/SubstituteAppellantBasicsView.jsx
  client/test/app/queue/substituteAppellant/SubstituteAppellantBasicsForm.test.js
Labels: Ready-to-Merge, Team: Echo 🐬

#16384 Don't error when veteran is nil in API hearing serializer
  app/serializers/api/v2/hearing_serializer.rb
Labels: Ready-to-Merge, Team: Tango 💃, Type: Tech-Improvement

#16388 Explain endpoint: don't fail on legacy appeal
  app/controllers/concerns/explain/appeal_record_event_mapper.rb
  app/controllers/concerns/explain_appeal_events_concern.rb
  app/views/explain/show.html.erb
Labels: Ready-to-Merge

#16387 Add benefit type to issues list on intake
  client/app/intake/components/AddedIssue.jsx
Labels: Ready-to-Merge

#16315 Hearing Renderer
  .reek.yml
  lib/helpers/hearing_renderable.rb
  lib/helpers/hearing_renderer.rb
Labels: Ready-to-Merge

#16398 Add hearing renderer test coverage
  spec/lib/helpers/hearing_renderer_spec.rb
Labels: Eng: Data Work Group

#16397 Explain page: add hearing rendering for appeal
  app/controllers/explain_controller.rb
  app/views/explain/show.html.erb
  spec/controllers/explain_controller_spec.rb
  spec/feature/explain_spec.rb
  spec/fixes/investigate_duplicate_judge_assign_task_spec.rb
  spec/lib/helpers/hearing_renderer_spec.rb
Labels: Eng: Data Work Group, Ready-to-Merge

#16393 Remove unidentifiedIssueDecisionDate feature toggle references
  app/controllers/intakes_controller.rb
  app/views/appeals/edit.html.erb
  app/views/higher_level_reviews/edit.html.erb
  app/views/supplemental_claims/edit.html.erb
  client/app/intake/components/UnidentifiedIssuesModal.jsx
  client/app/intake/reducers/featureToggles.js
  client/test/karma/intake/UnidentifiedIssuesModal-test.js
  client/test/karma/intake/testData.js
Labels: Ready-to-Merge

#16386 Prevent Multiple Substitutions from Source Appeal
  app/models/appeal.rb
  app/models/serializers/work_queue/appeal_serializer.rb
  client/app/queue/CaseDetailsView.jsx
  client/app/queue/utils.js
  spec/feature/queue/substitute_appellant/shared_setup.rb
Labels: Ready-to-Merge

#16300 Improve legibility of Hearing Date dropdown
  app/controllers/regional_offices_controller.rb
  client/app/components/DataDropdowns/HearingDate.jsx
  client/app/hearings/components/ScheduleVeteranForm.jsx
  spec/feature/hearings/schedule_veteran/build_hearsched_spec.rb
Labels: Ready-to-Merge

#16390 POA not found controller error, refactoring
  app/controllers/appeals_controller.rb
  app/models/appeal.rb
  app/models/bgs_power_of_attorney.rb
  app/models/bgs_related_claimant.rb
  app/models/claimant.rb
  app/models/legacy_appeal.rb
  client/app/queue/PowerOfAttorneyDetail.jsx
  client/app/queue/components/PoaRefresh.jsx
  client/app/queue/components/PoaRefreshButton.jsx
  client/app/queue/components/PoaRefreshButton.stories.js
  spec/controllers/appeals_controller_spec.rb
  spec/feature/queue/case_details_spec.rb
  spec/models/claimant_spec.rb
Labels: Ready-to-Merge, Team Victor

#16367 Removed time slot validation when virtual days are 0
  .reek.yml
  app/services/hearing_schedule/validate_ro_spreadsheet.rb
  spec/services/hearing_schedule/validate_ro_spreadsheet_spec.rb
  spec/support/roInvalidNumberOfTimeSlots.xlsx
  spec/support/roInvalidTimeSlotLength.xlsx
  spec/support/roInvalidTimeSlotStartTime.xlsx
  spec/support/roMissingTimeSlotDetails.xlsx
Labels: Ready-to-Merge

#16399 Do not raise InvalidCountryNameError for 'US'
  app/services/timezone_service.rb
  spec/services/timezone_service_spec.rb
Labels: Ready-to-Merge

#16371 Automate documentation of table associations
  .gitignore
  .reek.yml
  Makefile.example
  docs/schema/caseflow-belongs_to_erd-subclasses.svg
  docs/schema/caseflow-belongs_to_erd.svg
  docs/schema/caseflow-subclasses.svg
  lib/helpers/association_wrapper.rb
  lib/helpers/sanitized_json_configuration.rb
  lib/tasks/doc.rake
  lib/tasks/support/erd_graph_styling.rb
  lib/tasks/support/erd_record_associations.rb
  spec/lib/helpers/association_wrapper_spec.rb
  spec/lib/helpers/sanitized_json_exporter_spec.rb
Labels: Eng: Data Work Group, Ready-to-Merge

#16191 Prioritize VSO users RO and reduce default days to 60 days out when displaying hearing days schedule
  app/controllers/hearings/hearing_day_controller.rb
  app/services/hearing_day_range.rb
  spec/controllers/hearings/hearing_day_controller_spec.rb
Labels: Ready-to-Merge

#16401 Fix alert type on POA response
  app/controllers/appeals_controller.rb
Labels: Ready-to-Merge, Team Victor

#16404 Move method to public method
  app/models/power_of_attorney.rb
Labels: Ready-to-Merge, Team Victor

#16403 Do not raise InvalidCountryNameError for nil appellant_address country
  app/models/concerns/appeal_concern.rb
  spec/models/serializers/work_queue/legacy_appeal_serializer_spec.rb
Labels: Ready-to-Merge

#16372 Mkerns/caseflow 1708 ihp parent task
  app/models/tasks/track_veteran_task.rb
  spec/feature/queue/case_details_spec.rb
  spec/models/tasks/track_veteran_task_spec.rb
Labels: Ready-to-Merge

#16361 CASEFLOW-1617 Remove Room Limits on Building Dockets And Old Build Schedule Algorithm
  app/mappers/hearing_day_mapper.rb
  app/models/regional_office.rb
  app/models/ro_schedule_period.rb
  app/services/hearing_schedule/generate_hearing_days_schedule.rb
  app/services/hearing_schedule/ro_allocation.rb
  app/services/hearing_schedule/ro_distribution.rb
  client/app/hearings/components/ReviewAssignments.jsx
  spec/factories/ro_schedule_period.rb
  spec/models/judge_schedule_period_spec.rb
  spec/models/regional_office_spec.rb
  spec/models/schedule_period_spec.rb
  spec/services/hearing_schedule/generate_hearing_days_schedule_spec.rb
  spec/services/hearing_schedule/ro_allocation_spec.rb
  spec/services/hearing_schedule/ro_distribution_spec.rb
  spec/support/q3fy21RealExampleRoSpreadsheet.xlsx
Labels: Ready-to-Merge

#16406 Add Jest Test for Button
  client/test/app/Button.test.js
  client/test/app/__snapshots__/Button.test.js.snap
  client/test/karma/components/Button-test.js
Labels: Ready-to-Merge

#16392 Add Jest Test for AutoSave
  client/app/components/AutoSave.stories.js
  client/test/app/components/AutoSave.test.js
  client/test/app/components/__snapshots__/AutoSave.test.js.snap
  client/test/karma/components/AutoSave-test.js
Labels: Ready-to-Merge

#16408 Allow nil on claimant representative partcipant ID
  app/models/claimant.rb
Labels: Ready-to-Merge

#16339 Add QueueTable component to explain#show
  app/assets/stylesheets/explain_appeal.css
  app/controllers/explain_controller.rb
  app/views/explain/show.html.erb
  client/COPY.json
  client/app/explain/components/ColumnBuilder.jsx
  client/app/explain/components/NarrativeTable.jsx
  client/app/explain/index.jsx
  client/app/index.js
  client/constants/EXPLAIN.json
  lib/helpers/intake_renderer.rb
  lib/helpers/sanitized_json_configuration.rb
Labels: Ready-to-Merge

#16389 Resolve POA information when Substitute Appellant does not have a POA
  app/controllers/appellant_substitutions_controller.rb
  app/controllers/claimants_controller.rb
  app/models/appellant_substitution.rb
  client/app/queue/substituteAppellant/review/SubstituteAppellantReviewContainer.jsx
  db/migrate/20210622145703_remove_non_null_constraint_from_poa_id.rb
  db/schema.rb
  docs/schema/caseflow.csv
  lib/fakes/bgs_service.rb
  spec/controllers/appellant_substitutions_controller_spec.rb
  spec/controllers/claimants_controller_spec.rb
  spec/models/appellant_substitution_spec.rb
Labels: Ready-to-Merge

#16407 Appellant Substitution | Show Alert on Source Appeal
  app/models/serializers/work_queue/appellant_substitution_serializer.rb
  client/COPY.json
  client/app/queue/CaseDetailsView.jsx
  client/app/queue/VeteranDetail.jsx
  client/app/queue/VeteranDetail.stories.js
  client/app/queue/substituteAppellant/caseDetails/AppealHasSubstitutionAlert.jsx
  client/app/queue/substituteAppellant/caseDetails/AppealHasSubstitutionAlert.stories.js
  client/test/app/queue/substituteAppellant/AppealHasSubstitutionAlert.test.js
  client/test/app/queue/substituteAppellant/__snapshots__/AppealHasSubstitutionAlert.test.js.snap
  spec/feature/queue/substitute_appellant/shared_setup.rb
Labels: Ready-to-Merge, Team: Echo 🐬

#16374 WIP: Resolve outstanding hearings-related 508 bugs
  client/app/components/Table.jsx
  client/app/components/ToggleButton.jsx
  client/app/hearings/components/ListSchedule.jsx
  client/app/queue/QueueTable.jsx
  client/app/reader/DocumentsCommentsButton.jsx
  client/app/reader/DocumentsTable.jsx
Labels: Ready-to-Merge

#16072 Validate that an appeal can have only one JudgeAssignTask active at a time
  app/models/task.rb
  app/models/tasks/judge_assign_task.rb
  app/workflows/judge_assign_task_creator.rb
  client/app/queue/PowerOfAttorneyDetail.jsx
  lib/caseflow/error.rb
  spec/feature/queue/ama_queue_spec.rb
  spec/fixes/investigate_duplicate_judge_assign_task_spec.rb
  spec/jobs/update_cached_appeals_attributes_job_spec.rb
  spec/models/appeal_spec.rb
  spec/models/concerns/task_tree_render_module_spec.rb
  spec/models/dockets/hearing_request_docket_spec.rb
  spec/models/task_spec.rb
  spec/models/tasks/judge_task_spec.rb
Labels: Ready-to-Merge

#16409 Explain page: ignore HLRs and SCs associated with the appeal
  app/assets/stylesheets/explain_appeal.css
  app/controllers/explain_controller.rb
  app/views/explain/show.html.erb
  lib/helpers/sanitized_json_configuration.rb
  spec/feature/explain_spec.rb
Labels: Eng: Data Work Group, Ready-to-Merge, Type: Bug

#16410 Reset Redux Store after Substitution
  client/app/queue/substituteAppellant/review/SubstituteAppellantReviewContainer.jsx
  client/app/queue/substituteAppellant/substituteAppellant.slice.js
Labels: Ready-to-Merge, Team: Echo 🐬

#16415 Fixed undefined label for Louisville RO
  client/app/hearings/utils.js
Labels: Ready-to-Merge

#16425 Strip leading/trailing whitespace from country names in TimezoneService
  app/services/timezone_service.rb
  spec/services/timezone_service_spec.rb
Labels: Ready-to-Merge

#16416 Resolve 'comparison of Date with nil failed' when calling /api/v2/appeals
  app/decorators/appeal_status_api_decorator.rb
  spec/decorators/appeal_status_api_decorator_spec.rb
Labels: Ready-to-Merge

#16419 Write migration to fix poa participant id column comment in appellant_substitutions table
  db/migrate/20210628174527_update_appellant_substitutions_poa_participant_id_comment.rb
  db/schema.rb
  docs/schema/caseflow.csv
Labels: Ready-to-Merge

#16429 Improve queries in BgsPowerOfAttorney model
  app/models/bgs_power_of_attorney.rb
Labels: Ready-to-Merge

#16430 New checker job to list tasks assigned to inactive users
  app/jobs/data_integrity_checks_job.rb
  app/services/tasks_assigned_to_inactive_users_checker.rb
  spec/services/tasks_assigned_to_inactive_users_checker_spec.rb
Labels: Eng: Data Work Group, Ready-to-Merge

#15498 Support for Accessing `history` from Any Thunk
  client/app/components/ReduxBase.jsx
  client/app/queue/QueueApp.jsx
  client/app/queue/index.jsx
  client/app/queue/mtv/mtvActions.js
Labels: Eng: Frontend Work Group, Ready-to-Merge, Type: Tech-Improvement

#16418 Enable Substitution for Hearing Appeals w/ Feature Toggle
  app/views/queue/index.html.erb
  client/app/queue/CaseDetailsView.jsx
  client/app/queue/substituteAppellant/caseDetails/utils.js
  client/test/app/queue/substituteAppellant/caseDetails/utils.test.js
  db/seeds/substitutions.rb
  spec/feature/queue/substitute_appellant/shared_setup.rb
  spec/feature/queue/substitute_appellant/substitute_appellant_spec.rb
Labels: Ready-to-Merge, Team: Echo 🐬

#16417 Fixed focus indicator on the schedule veteran page
  client/app/hearings/components/assignHearings/styles.jsx
  client/app/styles/hearings/_hearings.scss
  client/test/app/hearings/components/assignHearings/__snapshots__/HearingDaysNav.test.js.snap
Labels: Ready-to-Merge

#16438 Correct poa_auto_refresh feature toggle
  app/models/bgs_power_of_attorney.rb
Labels: Ready-to-Merge

#16437 Add date of birth column to unrecognized party details
  db/migrate/20210629174248_add_birthdate_to_unrecognized_party.rb
  db/schema.rb
  docs/schema/caseflow.csv
Labels: Ready-to-Merge

#16436 Explain page: handle decision issues with non-Appeal decision reviews
  app/controllers/concerns/explain_appeal_events_concern.rb
  spec/feature/explain_spec.rb
  spec/records/appeal-106435.json
Labels: Eng: Data Work Group

#16432 Appellant: "Edit Information" Button
  app/views/queue/index.html.erb
  client/COPY.json
  client/app/intakeEdit/components/EditAppellantInformation.jsx
  client/app/queue/CaseDetailsView.jsx
  client/app/queue/QueueApp.jsx
  spec/feature/intake/non_veteran_claimants_spec.rb
Labels: Ready-to-Merge

#16442 Table unrecognized_party_details: annotate PII columns in schema
  PULL_REQUEST_TEMPLATE.md
  db/migrate/20210630135428_add_pii_comment_on_unrecognized_party_details.rb
  db/schema.rb
  docs/schema/caseflow.csv
  lib/tasks/doc.rake
Labels: Eng: Data Work Group, Ready-to-Merge
