Repository department-of-veterans-affairs/caseflow, pull requests merged in 2021-05, with the labels that each got.

#16197 Fix test by prefixing single-digit month and day with '0'
  spec/feature/intake/add_issues_spec.rb
Labels: Eng: Flaky Test, Ready-to-Merge

#16179 Karinamzalez/caseflow 1325
  client/COPY.json
  client/app/components/AddressForm.jsx
  client/app/constants/AppConstants.js
  client/app/intake/addClaimant/AddClaimantForm.jsx
  client/app/intake/addClaimant/utils.js
  client/app/intake/addPOA/AddPoaPage.jsx
  client/app/intake/addPOA/utils.js
  client/test/app/intake/components/AddPoaPage.test.js
  client/test/app/intake/components/addClaimants/AddClaimantForm.test.js
  client/test/app/intake/components/addClaimants/AddClaimantPage.test.js
  client/test/app/intake/components/addClaimants/__snapshots__/AddClaimantForm.test.js.snap
  client/test/app/intake/components/addClaimants/testUtils.js
  spec/feature/intake/non_veteran_claimants_spec.rb
  spec/support/intake_helpers.rb
Labels: Ready-to-Merge

#16181 Install logstasher for better logging
  Gemfile
  Gemfile.lock
  config/application.rb
  config/environments/production.rb
  config/initializers/logstasher.rb
Labels: Ready-to-Merge

#16132 Add Power of Attorney Refresh Button to Case Details
  app/controllers/appeals_controller.rb
  app/models/appeal.rb
  app/models/bgs_power_of_attorney.rb
  app/models/claimant.rb
  app/models/legacy_appeal.rb
  app/models/power_of_attorney.rb
  app/views/queue/index.html.erb
  client/app/queue/PowerOfAttorneyDetail.jsx
  client/app/queue/components/PoaRefresh.jsx
  client/app/queue/components/PoaRefreshButton.jsx
  client/app/queue/components/PoaRefreshButton.stories.js
  client/app/queue/uiReducer/uiActions.js
  client/app/queue/uiReducer/uiConstants.js
  client/app/queue/uiReducer/uiReducer.js
  config/routes.rb
  spec/controllers/appeals_controller_spec.rb
  spec/feature/queue/case_details_spec.rb
Labels: Ready-to-Merge

#16213 Replace poa_sync_date with poa_refresh feature toggle
  app/views/queue/index.html.erb
  client/app/queue/components/PoaRefresh.jsx
  client/app/queue/components/PoaRefresh.stories.js
  spec/feature/queue/case_details_spec.rb
Labels: Ready-to-Merge

#16206 Replicate prod bug: Case Movement user cannot reassign task
  lib/helpers/sanitized_json_configuration.rb
  lib/helpers/sanitized_json_importer.rb
  spec/fixes/investigate_scm_cant_reassign_spec.rb
  spec/records/scm-cant-reassign.json
Labels: Ready-to-Merge, Stakeholder: BVA, Team: Echo 🐬, Type: Bug

#16215 Make listed attorney required
  client/app/intake/addPOA/utils.js
  spec/feature/intake/non_veteran_claimants_spec.rb
Labels: Ready-to-Merge, Team: Foxtrot 🦊, Type: Bug

#16219 Add comment to `receipt_date` field on `docket_switches` table
  db/migrate/20210506161524_add_receipt_date_comment_to_docket_switches.rb
  db/schema.rb
  docs/schema/caseflow.csv
Labels: Ready-to-Merge

#16184 CASEFLOW-1264 | Permissions on substitute appellant button
  app/views/queue/index.html.erb
  client/app/queue/CaseDetailsView.jsx
  client/app/queue/QueueApp.jsx
  client/app/queue/uiReducer/uiActions.js
  client/app/queue/uiReducer/uiConstants.js
  client/app/queue/uiReducer/uiReducer.js
  db/seeds/users.rb
  spec/factories/appeal.rb
  spec/feature/queue/case_details_spec.rb
  spec/feature/queue/substitute_appellant/shared_setup.rb
  spec/feature/queue/substitute_appellant/substitute_appellant_spec.rb
  spec/seeds/users_spec.rb
Labels: Ready-to-Merge, Team: Echo 🐬

#16167 filter out rolled back related remand issues
  app/models/issue.rb
  app/models/legacy_issue_optin.rb
  app/models/ramp_closed_appeal.rb
  spec/models/legacy_issue_optin_spec.rb
Labels: Ready-to-Merge, Source: Bat Team, Team: Foxtrot 🦊

#16223 Move logstash config into its own file and fix user
  config/application.rb
  config/initializers/logstasher.rb
  config/logstasher.yml
Labels: Ready-to-Merge

#16229 Substitution: Add columns to capture user's task selections
  app/controllers/appellant_substitutions_controller.rb
  app/models/appellant_substitution.rb
  db/migrate/20210507152437_add_selected_task_ids_to_appellant_substitution_table.rb
  db/schema.rb
  docs/schema/caseflow.csv
  spec/controllers/appellant_substitutions_controller_spec.rb
  spec/models/appellant_substitution_spec.rb
Labels: Ready-to-Merge, Team: Echo 🐬

#16245 Put death dismissal streamline behind a feature toggle
  app/workflows/initial_tasks_factory.rb
  spec/workflows/initial_tasks_factory_spec.rb
Labels: Ready-to-Merge

#16239 Correctly handle "reschedule hearing" action on transcription tasks that aren't descendants of hearing tasks
  app/models/tasks/hearing_task.rb
  app/models/tasks/transcription_task.rb
  client/COPY.json
  spec/models/tasks/transcription_task_spec.rb
Labels: Ready-to-Merge, Team: Tango 💃

#16192 Caseflow-1406 Substitute Appellant | Task Selection Table
  client/COPY.json
  client/app/queue/substituteAppellant/substituteAppellant.slice.js
  client/app/queue/substituteAppellant/tasks/SubstituteAppellantTasksForm.jsx
  client/app/queue/substituteAppellant/tasks/SubstituteAppellantTasksForm.stories.js
  client/app/queue/substituteAppellant/tasks/SubstituteAppellantTasksView.jsx
  client/app/queue/substituteAppellant/tasks/TaskSelectionTable.jsx
  client/app/queue/substituteAppellant/tasks/utils.js
  client/test/app/queue/substituteAppellant/SubstituteAppellantTasksForm.test.js
  client/test/app/queue/substituteAppellant/__snapshots__/SubstituteAppellantTasksForm.test.js.snap
  client/test/app/queue/substituteAppellant/tasks/__snapshots__/utils.test.js.snap
  client/test/app/queue/substituteAppellant/tasks/utils.test.js
  client/test/data/queue/substituteAppellant/tasks.js
  spec/feature/queue/substitute_appellant/shared_setup.rb
  spec/feature/queue/substitute_appellant/substitute_appellant_spec.rb
Labels: Ready-to-Merge, Team: Echo 🐬

#16242 CASEFLOW-1121 | Substitute Appellant | Show Case Timeline Event
  app/models/serializers/work_queue/appellant_substitution_serializer.rb
  client/COPY.json
  client/app/queue/components/NodDateUpdateTimeline.jsx
  client/app/queue/components/NodDateUpdateTimeline.test.js
  client/app/queue/components/TaskRows.jsx
  client/app/queue/substituteAppellant/timelineEvent/SubstituteAppellantTimelineEvent.jsx
  client/app/queue/substituteAppellant/timelineEvent/SubstituteAppellantTimelineEvent.stories.js
  client/app/queue/substituteAppellant/timelineEvent/SubstitutionProcessedTimelineEvent.jsx
  client/app/queue/substituteAppellant/timelineEvent/SubstitutionProcessedTimelineEvent.stories.js
  client/app/queue/utils.js
  client/test/app/queue/__snapshots__/utils.test.js.snap
  client/test/app/queue/utils.test.js
  spec/feature/queue/substitute_appellant/shared_setup.rb
  spec/feature/queue/substitute_appellant/substitute_appellant_spec.rb
Labels: Ready-to-Merge, Team: Echo 🐬

#16243 Change Timeslot defaults (CASEFLOW-1507)
  app/models/hearing_day.rb
  app/services/hearing_schedule/validate_ro_spreadsheet.rb
  client/app/hearings/utils.js
  client/test/app/hearings/components/scheduleHearing/TimeSlot.test.js
  client/test/app/hearings/components/scheduleHearing/__snapshots__/TimeSlot.test.js.snap
  spec/models/hearing_day_spec.rb
  spec/support/validRoNoRoomsSpreadsheet.xlsx
Labels: Ready-to-Merge

#16221 CASEFLOW-1070 - Custom Time Modal
  client/app/hearings/components/TimePicker.jsx
  client/app/hearings/components/modalForms/TimeModal.jsx
  client/app/hearings/components/modalForms/TimeModal.stories.js
  client/app/hearings/components/scheduleHearing/InfoAlert.jsx
  client/app/hearings/components/scheduleHearing/TimeSelect.jsx
  client/app/hearings/components/scheduleHearing/TimeSlot.jsx
  client/app/hearings/components/scheduleHearing/Timeslot.stories.js
  client/app/hearings/utils.js
  client/test/app/hearings/components/scheduleHearing/TimeModal.test.js
  client/test/app/hearings/components/scheduleHearing/TimeSlot.test.js
  client/test/app/hearings/components/scheduleHearing/__snapshots__/TimeModal.test.js.snap
  client/test/app/hearings/components/scheduleHearing/__snapshots__/TimeSlot.test.js.snap
  spec/feature/hearings/schedule_veteran/build_hearsched_spec.rb
Labels: Ready-to-Merge

#16248 Revert Video total_slots default to 12 and Central total_slots default to 10
  app/models/hearing_day.rb
  app/services/hearing_schedule/validate_ro_spreadsheet.rb
  spec/models/hearing_day_spec.rb
Labels: Ready-to-Merge

#16214 Add a review and confirmation page for substitution
  app/models/serializers/work_queue/task_serializer.rb
  client/app/intake/util/index.js
  client/app/queue/substituteAppellant/review/SubstituteAppellantReview.jsx
  client/app/queue/substituteAppellant/review/SubstituteAppellantReview.stories.js
  client/app/queue/substituteAppellant/review/SubstituteAppellantReviewContainer.jsx
  client/app/queue/substituteAppellant/styles.js
  client/app/queue/substituteAppellant/tasks/utils.js
  client/app/queue/utils.js
  client/test/app/queue/substituteAppellant/SubstituteAppellantReview.test.js
  client/test/app/queue/substituteAppellant/__snapshots__/SubstituteAppellantReview.test.js.snap
  client/test/app/queue/substituteAppellant/__snapshots__/SubstituteAppellantTasksForm.test.js.snap
  client/test/app/queue/substituteAppellant/tasks/__snapshots__/utils.test.js.snap
  client/test/app/queue/substituteAppellant/tasks/utils.test.js
  client/test/data/queue/substituteAppellant/tasks.js
  spec/controllers/tasks_controller_spec.rb
  spec/feature/queue/substitute_appellant/shared_setup.rb
  spec/models/serializers/work_queue/task_serializer_spec.rb
Labels: Ready-to-Merge, Team: Echo 🐬

#16252 Show unlisted claimant option for veterans without relations
  client/app/intake/components/SelectClaimant.jsx
  spec/feature/intake/non_veteran_claimants_spec.rb
Labels: Ready-to-Merge

#16202 Death dismissal task blocking tech spec
  docs/tech-specs/2021-04-19-HearingScheduleNoRoomsAlgorithm.md
  docs/tech-specs/2021-05-04-death-dismissal-task-blocking.md
  docs/tech-specs/2021-3-31-poa-refresh.md
Labels: Ready-to-Merge, Team: Foxtrot 🦊

#16208 Certification: Matching Dates list not read correctly
  client/app/components/ProgressBar.jsx
  client/app/components/ProgressBarSection.jsx
  client/test/app/intake/components/__snapshots__/AddPoaPage.test.js.snap
  client/test/app/intake/components/addClaimants/__snapshots__/AddClaimantPage.test.js.snap
Labels: Ready-to-Merge

#16244 Show substitution granted date; adds AppellantSubstitution factory
  client/app/queue/AppellantDetail.jsx
  client/app/queue/CaseDetailsView.jsx
  client/app/queue/utils.js
  spec/factories/appellant_substitution.rb
  spec/feature/queue/case_details_spec.rb
Labels: Ready-to-Merge, Team: Echo 🐬

#16266 Snooze puma CVE until next week, and upgrade nokogiri
  .security.yml
  Gemfile.lock
Labels: Ready-to-Merge

#16257 Add role prop to Button.jsx to allow CaseWorkerIndex to pass role=link
  client/app/components/Button.jsx
  client/app/containers/CaseWorker/CaseWorkerIndex.jsx
  client/test/app/containers/CaseWorker/CaseWorkerIndex.test.js
  client/test/app/containers/CaseWorker/__snapshots__/CaseWorkerIndex.test.js.snap
Labels: Ready-to-Merge

#16265 Show all nonrating comp issue categories with nonVeteranClaimants toggle
  client/app/intake/components/NonratingRequestIssueModal.jsx
Labels: Ready-to-Merge

#16264 create a new hearings seed user based in Oakland
  db/seeds/users.rb
  spec/seeds/users_spec.rb
Labels: Ready-to-Merge, Team: Tango 💃

#16233 Mkerns/caseflow 1384 ihp task cancellation
  app/models/bgs_power_of_attorney.rb
  app/models/tasks/informal_hearing_presentation_task.rb
  app/models/tasks/track_veteran_task.rb
  app/views/queue/index.html.erb
  spec/models/bgs_power_of_attorney_spec.rb
  spec/models/tasks/informal_hearing_presentation_task_spec.rb
Labels: Ready-to-Merge

#16276 Refactor available_actions method in IHP Task
  app/models/tasks/informal_hearing_presentation_task.rb
  spec/models/tasks/informal_hearing_presentation_task_spec.rb
Labels: Ready-to-Merge

#16273 CASEFLOW-1497: further limit availability of add substitute button
  client/app/queue/CaseDetailsView.jsx
  spec/feature/queue/case_details_spec.rb
Labels: Ready-to-Merge

#16279 Revert "Add foreign keys for hearings tables (Phase 6)"
  db/migrate/20210519184239_add_foreign_keys_for_appeals.rb
  db/migrate/20210519184436_validate_foreign_keys_for_appeals.rb
  db/migrate/20210520211935_add_hearings_related_foreign_keys.rb
  db/migrate/20210520212147_validate_hearings_related_foreign_keys.rb
  db/schema.rb
  spec/services/etl/hearing_syncer_spec.rb
  spec/services/etl/legacy_hearing_syncer_spec.rb
Labels: Ready-to-Merge

#16256 updating comments for docket switch
  app/models/tasks/mail_task.rb
Labels: Ready-to-Merge

#16193 Shalliburton/caseflow 1078 distribute hearing days evenly
  app/models/ro_schedule_period.rb
  app/services/hearing_schedule/generate_hearing_days_schedule.rb
  spec/services/hearing_schedule/generate_hearing_days_schedule_spec.rb
Labels: Ready-to-Merge

#16281 Add foreign keys for hearings tables (Phase 5b)
  db/migrate/20210520211935_add_hearings_related_foreign_keys.rb
  db/migrate/20210520212147_validate_hearings_related_foreign_keys.rb
  db/schema.rb
Labels: Eng: Data Work Group, Ready-to-Merge

#16263 Add foreign keys to appeals and legacy_appeals tables (Phase 5c)
  db/migrate/20210521184239_add_foreign_keys_for_appeals.rb
  db/migrate/20210521184436_validate_foreign_keys_for_appeals.rb
  db/schema.rb
  spec/services/etl/hearing_syncer_spec.rb
  spec/services/etl/legacy_hearing_syncer_spec.rb
Labels: Eng: Data Work Group

#16274 Define default and maximum time slots separately
  app/models/hearing_day.rb
  app/services/hearing_schedule/validate_ro_spreadsheet.rb
Labels: Ready-to-Merge, Team: Tango 💃

#16284 [Screenreader] Dispatch: New claim page
  client/app/containers/EstablishClaimPage/EstablishClaimDecision.jsx
Labels: Ready-to-Merge

#16251 Added file for seeding appellant substitutions
  db/seeds.rb
  db/seeds/substitutions.rb
  spec/seeds/substitutions_spec.rb
Labels: Ready-to-Merge

#16287 Extend snooze on CVE-2021-29509 one more day
  .security.yml
Labels: Eng: Backend Work Group, Ready-to-Merge

#16247 Rename poa_refresh feature toggle to poa_button_refresh
  app/views/queue/index.html.erb
  client/app/queue/components/PoaRefresh.jsx
  client/app/queue/components/PoaRefresh.stories.js
  client/app/queue/components/PoaRefreshButton.jsx
  client/app/queue/components/PoaRefreshButton.stories.js
  spec/feature/queue/case_details_spec.rb
Labels: Ready-to-Merge

#16217 Add IHP task cancel reason to timeline
  app/models/serializers/work_queue/task_serializer.rb
  client/COPY.json
  client/app/queue/components/TaskRows.jsx
  client/app/queue/utils.js
  spec/feature/queue/case_details_spec.rb
Labels: Ready-to-Merge

#16231 Make possible to delete claimant POA in AMA appeal. Ensure POA Last Synced Date is always shown.
  app/controllers/appeals_controller.rb
  app/models/bgs_power_of_attorney.rb
  client/COPY.json
  client/app/queue/PowerOfAttorneyDetail.jsx
  client/app/queue/components/PoaRefresh.jsx
  spec/controllers/appeals_controller_spec.rb
  spec/feature/queue/case_details_spec.rb
Labels: Ready-to-Merge

#16286 Appellant Substitution | Show Org Task Based on Corresponding User Task
  client/app/queue/substituteAppellant/tasks/utils.js
  client/test/app/queue/substituteAppellant/tasks/utils.test.js
Labels: Ready-to-Merge

#16183 Automatically update poa on page load
  app/models/bgs_power_of_attorney.rb
  app/views/queue/index.html.erb
  spec/models/bgs_power_of_attorney_spec.rb
Labels: Ready-to-Merge

#16280 Add front end validation to receipt date field
  client/app/intake/actions/intake.js
  client/app/intake/constants.js
  client/app/intake/pages/review.jsx
  client/app/intake/reducers/appeal.js
  client/test/app/intake/pages/review.test.js
  spec/feature/intake/review_page_spec.rb
Labels: Ready-to-Merge

#16292 Remove poa_refresh feature toggle
  app/views/queue/index.html.erb
Labels: Ready-to-Merge

#16261 Default to fetch legacy POA record by claimant_participant_id
  app/models/power_of_attorney.rb
  spec/models/legacy_appeal_spec.rb
Labels: Ready-to-Merge

#16269 Rename available actions dropdown on task
  client/app/queue/components/ActionsDropdown.jsx
Labels: Ready-to-Merge, Team: Foxtrot 🦊

#16209 CASEFLOW-1431 Create tasks for new Substitution appeal
  app/controllers/appellant_substitutions_controller.rb
  app/models/appeal.rb
  app/models/task.rb
  app/models/tasks/evidence_submission_window_task.rb
  app/workflows/initial_tasks_factory.rb
  client/app/queue/substituteAppellant/review/SubstituteAppellantReview.jsx
  client/app/queue/substituteAppellant/review/SubstituteAppellantReviewContainer.jsx
  client/app/queue/substituteAppellant/substituteAppellant.slice.js
  lib/helpers/sanitized_json_configuration.rb
  spec/models/appellant_substitution_spec.rb
  spec/records/appeal-140375.json
  spec/records/appeal-21430.json
  spec/records/appeal-90772.json
Labels: Team: Echo 🐬

#16250 Exporter: include inactive orgs in export
  lib/helpers/sanitized_json_configuration.rb
Labels: Eng: Data Work Group, Ready-to-Merge

#16296 Update to latest caseflow-frontend-toolkit
  client/package.json
  client/test/app/containers/CaseWorker/__snapshots__/CaseWorkerIndex.test.js.snap
  client/yarn.lock
Labels: Ready-to-Merge

#16226 Add convenience scopes to CachedAppeal
  app/models/cached_appeal.rb
  spec/jobs/update_cached_appeals_attributes_job_spec.rb
Labels: Ready-to-Merge

#16289 Video hearing days should not respect spreadsheet slot_count value
  app/models/ro_schedule_period.rb
Labels: Ready-to-Merge

#16262 Hide automated tasks from user who is selecting tasks for the substitution appeal
  client/app/queue/substituteAppellant/review/SubstituteAppellantReview.jsx
  client/app/queue/substituteAppellant/tasks/SubstituteAppellantTasksForm.stories.js
  client/app/queue/substituteAppellant/tasks/SubstituteAppellantTasksView.jsx
  client/app/queue/substituteAppellant/tasks/TaskSelectionTable.jsx
  client/app/queue/substituteAppellant/tasks/utils.js
  client/test/app/queue/substituteAppellant/__snapshots__/SubstituteAppellantReview.test.js.snap
  client/test/app/queue/substituteAppellant/__snapshots__/SubstituteAppellantTasksForm.test.js.snap
  client/test/app/queue/substituteAppellant/tasks/utils.test.js
  spec/factories/task.rb
  spec/feature/queue/substitute_appellant/shared_setup.rb
Labels: Ready-to-Merge

#16294 Make the context entry on the docket switch review form not required
  client/app/queue/docketSwitch/judgeRuling/DocketSwitchRulingForm.jsx
  client/test/app/queue/docketSwitch/DocketSwitchRulingForm.test.js
Labels: Ready-to-Merge

#16189 Time Slots - Add Lunch Break for Eastern Timezone ROs
  client/app/hearings/components/scheduleHearing/TimeSlot.jsx
  client/app/hearings/utils.js
  client/test/app/hearings/components/scheduleHearing/TimeSlot.test.js
Labels: Ready-to-Merge

#16277 Add foreign keys for request-issues-related tables (Phase 7)
  db/migrate/20210525143044_add_foreign_keys_for_request_issues.rb
  db/migrate/20210525143811_validate_request_issues_related_foreign_keys.rb
  db/schema.rb
Labels: Eng: Data Work Group

#16238 Remove unused edit contention text feature toggle
  app/controllers/intakes_controller.rb
  app/views/appeals/edit.html.erb
  app/views/higher_level_reviews/edit.html.erb
  app/views/supplemental_claims/edit.html.erb
  client/app/intake/components/IssueList.jsx
  client/app/intake/reducers/featureToggles.js
  client/test/karma/intake/testData.js
  spec/feature/intake/add_issues_spec.rb
  spec/feature/intake/higher_level_review/edit_spec.rb
  spec/feature/intake/supplemental_claim/edit_spec.rb
Labels: Ready-to-Merge
