Repository department-of-veterans-affairs/caseflow, pull requests merged in 2021-04, with the labels that each got.

#15940 Submission for unrecognized appellant appeals (with POA)
  app/models/attorney_power_of_attorney.rb
  app/models/claimant.rb
  app/models/decision_review.rb
  app/models/decision_review_intake.rb
  app/models/other_claimant.rb
  app/models/unrecognized_appellant.rb
  app/models/unrecognized_power_of_attorney.rb
  app/schemas/intakes_schemas.rb
  app/serializers/intake/decision_review_intake_serializer.rb
  app/serializers/intake/decision_review_serializer.rb
  client/app/components/AddressForm.jsx
  client/app/intake/addClaimant/AddClaimantConfirmationModal.jsx
  client/app/intake/addClaimant/AddClaimantForm.jsx
  client/app/intake/addClaimant/AddClaimantForm.stories.js
  client/app/intake/addClaimant/AddClaimantPage.jsx
  client/app/intake/addClaimant/AddressBlock.jsx
  client/app/intake/addClaimant/utils.js
  client/app/intake/addPOA/AddPoaPage.jsx
  client/app/intake/addPOA/utils.js
  client/app/intake/components/SelectClaimant.jsx
  client/app/intake/constants.js
  client/app/intake/pages/addIssues.jsx
  client/app/intake/reducers/addClaimantSlice.js
  client/app/intake/reducers/appeal.js
  client/app/intake/reducers/common.js
  client/app/intake/util/index.js
  client/app/intake/util/issues.js
  client/test/app/intake/components/__snapshots__/AddPoaPage.test.js.snap
  client/test/app/intake/components/addClaimants/AddClaimantForm.test.js
  client/test/app/intake/components/addClaimants/__snapshots__/AddClaimantConfirmationModal.test.js.snap
  client/test/app/intake/components/addClaimants/__snapshots__/AddClaimantForm.test.js.snap
  lib/fakes/bgs_service.rb
  spec/controllers/idt/api/veterans_controller_spec.rb
  spec/factories/veteran.rb
  spec/feature/intake/appeal_spec.rb
  spec/feature/intake/higher_level_review_spec.rb
  spec/feature/intake/non_veteran_claimants_spec.rb
  spec/feature/intake/supplemental_claim_spec.rb
  spec/feature/queue/case_details_spec.rb
  spec/models/appeal_intake_spec.rb
  spec/models/other_claimant_spec.rb
  spec/support/intake_helpers.rb
Labels: Team: Foxtrot 🦊

#16079 Add all possible US states/territories
  client/app/constants/AppConstants.js
Labels: Ready-to-Merge

#16051 Disable edit claim label button when editing issues
  client/app/intake/pages/addIssues.jsx
  spec/feature/intake/edit_ep_claim_labels_spec.rb
Labels: Ready-to-Merge

#16054 EP Claim Label Add success alert and redirect to Veteran Case Search after edit
  app/controllers/claim_review_controller.rb
  app/models/rating_request_issue.rb
  client/COPY.json
  client/app/intakeEdit/actions/edit.js
  client/app/queue/CaseListView.jsx
  spec/feature/intake/edit_ep_claim_labels_spec.rb
Labels: Ready-to-Merge, Team: Foxtrot 🦊

#16082 Edit Claim Labels | Disable edit on closed claims
  client/app/intake/pages/addIssues.jsx
  spec/feature/intake/edit_ep_claim_labels_spec.rb
Labels: Ready-to-Merge

#15967 Remove confusing copy on case details page
  client/COPY.json
Labels: Ready-to-Merge

#16087 Allow sending Docket Switches to OCB VLJs only
  app/repositories/task_action_repository.rb
  client/app/queue/docketSwitch/recommendDocketSwitch/RecommendDocketSwitchContainer.jsx
  spec/feature/queue/docket_switch_spec.rb
Labels: Ready-to-Merge

#16088 Docket Switch Bugs
  client/app/queue/docketSwitch/recommendDocketSwitch/RecommendDocketSwitchContainer.jsx
  client/test/app/queue/docketSwitch/RecommendDocketSwitchContainer.test.js
  client/test/app/queue/docketSwitch/__snapshots__/RecommendDocketSwitchContainer.test.js.snap
  spec/feature/queue/docket_switch_spec.rb
Labels: Ready-to-Merge

#16049 Add hearing to original_request_type/changed_request_type database fields and accompanying code
  app/models/concerns/hearing_request_type_concern.rb
  app/models/tasks/change_hearing_request_type_task.rb
  app/models/tasks/schedule_hearing_task.rb
  app/services/cached_appeal_service.rb
  client/app/hearings/components/HearingTypeConversion.jsx
  client/app/hearings/components/HearingTypeConversionModal.jsx
  db/migrate/20210324184347_rename_changed_request_type_to_changed_hearing_request_type.rb
  db/migrate/20210324184415_rename_original_request_type_to_original_hearing_request_type.rb
  db/schema.rb
  db/seeds/hearings.rb
  docs/schema/caseflow.csv
  spec/controllers/tasks_controller_spec.rb
  spec/feature/hearings/assign_hearings_table_spec.rb
  spec/jobs/update_cached_appeals_attributes_job_spec.rb
  spec/models/concerns/hearing_request_type_concern_spec.rb
  spec/models/legacy_appeal_spec.rb
  spec/models/tasks/change_hearing_request_type_task_spec.rb
  spec/services/cached_appeal_service_spec.rb
Labels: Ready-to-Merge, Team: Tango 💃, Type: Tech-Improvement

#16092 Refactored how hearing days seed data is generated
  db/seeds/hearings.rb
  spec/seeds/hearings_spec.rb
Labels: Ready-to-Merge

#16090 Update edit NOD permissions to just CoB
  app/models/user.rb
  spec/feature/queue/case_details_spec.rb
Labels: Ready-to-Merge

#16095 Rename granted substitution to appellant substitution
  .codeclimate.yml
  app/models/advance_on_docket_motion.rb
  app/models/appeal.rb
  app/models/appellant_substitution.rb
  app/models/cavc_remand.rb
  app/models/granted_substitution.rb
  client/constants/AMA_STREAM_TYPES.json
  db/migrate/20210406122353_rename_granted_substitutions.rb
  db/schema.rb
  docs/schema/caseflow.csv
  spec/models/appellant_substitution_spec.rb
Labels: Ready-to-Merge, Team: Echo 🐬

#16103 Don't allow future dates for 'remand' decision type
  client/app/queue/cavc/EditCavcRemandForm.jsx
Labels: Ready-to-Merge, Team: Echo 🐬

#16105 Caseflow Dispatch: fix seeding dev data
  app/controllers/test/users_controller.rb
Labels: Ready-to-Merge, Team: Echo 🐬

#16104 Add a COTB VLJ in database seeds
  db/seeds/users.rb
  spec/seeds/users_spec.rb
Labels: Ready-to-Merge

#16102 Remove name and join parameters from virtual hearing urls
  app/models/hearings/virtual_hearing.rb
  app/services/virtual_hearings/link_service.rb
  spec/factories/virtual_hearing.rb
  spec/jobs/virtual_hearings/create_conference_job_spec.rb
  spec/models/hearings/virtual_hearing_spec.rb
  spec/services/virtual_hearings/link_service_spec.rb
Labels: Ready-to-Merge, Team: Tango 💃

#16107 Make POA last synced at available to appeals
  app/controllers/appeals_controller.rb
  app/models/appeal.rb
  app/models/bgs_power_of_attorney.rb
  app/models/claimant.rb
  app/models/legacy_appeal.rb
  app/models/power_of_attorney.rb
Labels: Ready-to-Merge

#16111 Fix canceled change hearing request type task bug
  app/models/concerns/hearing_request_type_concern.rb
  spec/models/concerns/hearing_request_type_concern_spec.rb
Labels: Ready-to-Merge, Team: Tango 💃

#16038 Fix VACOLS::Staff.find_by_css_id
  app/models/vacols/staff.rb
  spec/models/vacols/staff_spec.rb
Labels: Ready-to-Merge, Team: Echo 🐬

#16108 Standard error handling when EP is not updated
  app/controllers/claim_review_controller.rb
  app/models/end_product_update.rb
  client/app/intake/pages/addIssues.jsx
  spec/feature/intake/edit_ep_claim_labels_spec.rb
Labels: Ready-to-Merge

#16119 Correctly identify if an appeal is active for correct issues permissions
  app/policies/appeal_request_issues_policy.rb
  spec/policies/appeal_request_issues_policy_spec.rb
Labels: Ready-to-Merge

#16114 Add missing foreign keys to Organization and User tables (Phase 2)
  db/migrate/20210412223749_add_foreign_keys_to_orgs_and_users_table.rb
  db/migrate/20210412224203_validate_foreign_keys_to_orgs_and_users_table.rb
  db/schema.rb
  spec/controllers/organizations/users_controller_spec.rb
  spec/models/organization_spec.rb
  spec/models/organizations_user_spec.rb
Labels: Eng: Data Work Group

#16126 update tests to improve coverage for StuckVirtualHearingsChecker
  spec/services/stuck_virtual_hearings_checker_spec.rb
Labels: Ready-to-Merge, Team: Tango 💃

#16121 use environment variables to construct the virtual hearing test link
  app/models/hearings/virtual_hearing.rb
  spec/models/hearings/virtual_hearing_spec.rb
Labels: Ready-to-Merge, Team: Tango 💃

#16081 Mkerns/caseflow 991 content headers
  app/views/layouts/application.html.erb
  client/app/components/CaseSearchLink.jsx
  client/app/hearings/components/details/DetailsHeader.jsx
  client/app/styles/_commons.scss
  client/package.json
  client/yarn.lock
  spec/feature/non_comp/dispositions_spec.rb
Labels: Ready-to-Merge

#16113 Refactor methods for fetching POA from cache or BGS
  app/models/attorney_claimant.rb
  app/models/bgs_power_of_attorney.rb
  app/models/claimant.rb
  app/models/power_of_attorney.rb
  app/models/veteran_claimant.rb
  spec/models/dependent_claimant_spec.rb
Labels: Ready-to-Merge

#16128 Update email address for incident team
  client/app/intake/pages/search.jsx
Labels: Ready-to-Merge, Team: Foxtrot 🦊

#16120 Add missing foreign keys to Task table (Phase 3)
  db/migrate/20210413191728_add_foreign_keys_to_task_table.rb
  db/migrate/20210413192533_validate_foreign_keys_to_tasks_table.rb
  db/schema.rb
  lib/helpers/sanitized_json_configuration.rb
  lib/helpers/sanitized_json_difference.rb
  lib/helpers/sanitized_json_exporter.rb
  spec/lib/helpers/sanitized_json_exporter_spec.rb
Labels: Eng: Data Work Group, Ready-to-Merge

#16124 Show POA on appeals edit page
  app/views/appeals/edit.html.erb
  spec/feature/intake/non_veteran_claimants_spec.rb
Labels: Ready-to-Merge

#16025 Rewrite Modal karma test
  client/test/app/components/Modal.test.js
  client/test/app/components/__snapshots__/Modal.test.js.snap
  client/test/app/intake/components/addClaimants/AddClaimantForm.test.js
  client/test/app/intake/components/addClaimants/AddClaimantPage.test.js
  client/test/karma/components/Modal-test.js
Labels: Ready-to-Merge, Type: Tech-Improvement

#16106 Remove VLJ ruling letter hyperlink field from docket switch
  client/COPY.json
  client/app/queue/docketSwitch/judgeRuling/DocketSwitchRulingContainer.jsx
  client/app/queue/docketSwitch/judgeRuling/DocketSwitchRulingForm.jsx
  client/test/app/queue/docketSwitch/DocketSwitchRulingContainer.test.js
  client/test/app/queue/docketSwitch/__snapshots__/DocketSwitchRulingContainer.test.js.snap
  client/test/app/queue/docketSwitch/__snapshots__/DocketSwitchRulingForm.test.js.snap
  spec/feature/queue/docket_switch_spec.rb
Labels: Ready-to-Merge

#16125 Paula/caseflow 1126 judge tabs
  app/models/queue_tabs/assigned_tasks_tab.rb
  app/models/queue_tabs/completed_tasks_tab.rb
  app/models/queue_tabs/on_hold_tasks_tab.rb
  app/models/user.rb
  spec/controllers/tasks_controller_spec.rb
  spec/feature/queue/task_queue_spec.rb
Labels: Ready-to-Merge, Team: Echo 🐬

#16130 Hide early morning slots and slots before scheduled hearings
  client/app/hearings/utils.js
  spec/feature/hearings/schedule_veteran/build_hearsched_spec.rb
Labels: Ready-to-Merge

#16099 Granted Substitution Basics Form
  app/controllers/appeals_controller.rb
  app/models/serializers/work_queue/veteran_serializer.rb
  app/views/queue/index.html.erb
  client/COPY.json
  client/app/components/DateSelector.jsx
  client/app/queue/CaseDetailsPostDispatchActions.jsx
  client/app/queue/CaseDetailsView.jsx
  client/app/queue/QueueApp.jsx
  client/app/queue/reducers.js
  client/app/queue/substituteAppellant/SubstituteAppellantContainer.jsx
  client/app/queue/substituteAppellant/basics/SubstituteAppellantBasicsForm.jsx
  client/app/queue/substituteAppellant/basics/SubstituteAppellantBasicsForm.stories.js
  client/app/queue/substituteAppellant/basics/SubstituteAppellantBasicsView.jsx
  client/app/queue/substituteAppellant/poa/SubstituteAppellantPoaForm.jsx
  client/app/queue/substituteAppellant/poa/SubstituteAppellantPoaView.jsx
  client/app/queue/substituteAppellant/review/SubstituteAppellantReview.jsx
  client/app/queue/substituteAppellant/review/SubstituteAppellantReviewContainer.jsx
  client/app/queue/substituteAppellant/routes.jsx
  client/app/queue/substituteAppellant/substituteAppellant.slice.js
  client/app/queue/substituteAppellant/tasks/SubstituteAppellantTasksForm.jsx
  client/app/queue/substituteAppellant/tasks/SubstituteAppellantTasksView.jsx
  client/test/app/queue/substituteAppellant/SubstituteAppellantBasicsForm.test.js
  client/test/app/queue/substituteAppellant/__snapshots__/SubstituteAppellantBasicsForm.test.js.snap
  spec/factories/relationship.rb
  spec/feature/queue/substitute_appellant/shared_setup.rb
  spec/feature/queue/substitute_appellant/substitute_appellant_spec.rb
Labels: Ready-to-Merge

#16117 Docket switch queue display updates
  app/services/bva_appeal_status.rb
  client/COPY.json
  client/app/queue/utils.js
  spec/feature/queue/docket_switch_spec.rb
  spec/models/docket_switch_spec.rb
Labels: Ready-to-Merge, Team: Foxtrot 🦊

#16134 Remove unnecessary and unused param
  client/app/hearings/utils.js
Labels: Ready-to-Merge

#16110 Revert "Allow sending Docket Switches to OCB VLJs only (#16087)"
  app/repositories/task_action_repository.rb
  client/app/queue/docketSwitch/recommendDocketSwitch/RecommendDocketSwitchContainer.jsx
  spec/feature/queue/docket_switch_spec.rb
Labels: Ready-to-Merge

#16089 CASEFLOW-1118 Submit Granted Substitution
  app/controllers/appellant_substitutions_controller.rb
  app/models/appeal.rb
  app/models/appellant_substitution.rb
  app/models/cavc_remand.rb
  app/workflows/initial_tasks_factory.rb
  client/COPY.json
  client/app/queue/substituteAppellant/review/SubstituteAppellantReview.jsx
  client/app/queue/substituteAppellant/review/SubstituteAppellantReviewContainer.jsx
  client/app/queue/substituteAppellant/substituteAppellant.slice.js
  config/routes.rb
  scripts/metabase_client.sh
  spec/controllers/appellant_substitutions_controller_spec.rb
  spec/controllers/cavc_remands_controller_spec.rb
  spec/feature/queue/substitute_appellant/shared_setup.rb
  spec/models/appellant_substitution_spec.rb
Labels: Ready-to-Merge, Team: Echo 🐬

#16139 Revert "Paula/caseflow 1126 judge tabs"
  app/models/queue_tabs/assigned_tasks_tab.rb
  app/models/queue_tabs/completed_tasks_tab.rb
  app/models/queue_tabs/on_hold_tasks_tab.rb
  app/models/user.rb
  spec/controllers/tasks_controller_spec.rb
  spec/feature/queue/task_queue_spec.rb
Labels: Ready-to-Merge

#16140 Reinstate "Allow sending Docket Switches to OCB VLJs only (#16087)" (revert #16110)
  app/repositories/task_action_repository.rb
  client/app/queue/docketSwitch/recommendDocketSwitch/RecommendDocketSwitchContainer.jsx
  spec/feature/queue/docket_switch_spec.rb
Labels: Ready-to-Merge

#16137 Add foreign keys for cavc_remands table (Phase 4)
  db/migrate/20210416191939_add_foreign_keys_to_cavc_remands_table.rb
  db/migrate/20210416192302_validate_new_foreign_keys_on_cavc_remands_table.rb
  db/schema.rb
Labels: Eng: Data Work Group, Ready-to-Merge

#16118 Add User.with_role scope
  app/models/user.rb
  spec/models/user_spec.rb
Labels: Ready-to-Merge, Source: Bat Team

#16123 Karinamzalez/1083 poa info case details
  app/models/unrecognized_power_of_attorney.rb
  client/COPY.json
  client/app/queue/CaseDetailsView.jsx
  client/app/queue/PowerOfAttorneyDetail.jsx
  client/test/app/hearings/components/Details.test.js
  spec/feature/queue/case_details_spec.rb
Labels: Ready-to-Merge

#16136 Updates to EditCavcRemandForm and Jest Tests
  client/app/queue/cavc/EditCavcRemandForm.jsx
  client/app/queue/cavc/EditCavcRemandForm.stories.js
  client/test/app/queue/cavc/EditCavcRemandForm.test.js
  client/test/app/queue/cavc/__snapshots__/EditCavcRemandForm.test.js.snap
Labels: Ready-to-Merge, Team: Echo 🐬

#16142 other_close_event_date no longer fails on nil last_synced_at
  app/models/supplemental_claim.rb
  spec/models/supplemental_claim_spec.rb
Labels: Ready-to-Merge, Source: Bat Team, Team: Echo 🐬

#16143 Additional Feature Tests for Editing CAVC Remands
  spec/feature/queue/cavc_task_queue_spec.rb
Labels: Ready-to-Merge, Team: Echo 🐬

#16145 capture RecipientIsDeceasedVeteran when sending emails in the CreateConferenceJob
  app/jobs/virtual_hearings/create_conference_job.rb
Labels: Ready-to-Merge, Source: Bat Team, Team: Tango 💃

#16109 Mkerns/caseflow 868 last updated poa
  app/views/queue/index.html.erb
  client/COPY.json
  client/app/components/Button.stories.js
  client/app/queue/PowerOfAttorneyDetail.jsx
  client/app/queue/components/PoaRefresh.jsx
  client/app/queue/components/PoaRefresh.stories.js
  client/test/app/queue/components/PoaRefresh.test.js
  client/test/app/queue/components/__snapshots__/PoaRefresh.test.js.snap
Labels: Ready-to-Merge

#16146 Unrecognized Appellant Bug - Confirmation Modal Data Formatting
  client/app/intake/addClaimant/AddClaimantConfirmationModal.jsx
  client/app/intake/addClaimant/AddressBlock.jsx
  client/test/app/intake/components/addClaimants/__snapshots__/AddClaimantConfirmationModal.test.js.snap
Labels: Ready-to-Merge

#16152 Return correct type for known representatives
  app/models/attorney_power_of_attorney.rb
  spec/models/other_claimant_spec.rb
Labels: Ready-to-Merge

#16156 Update tech spec documentation
  .github/ISSUE_TEMPLATE/tech-spec.md
  docs/tech-specs/README.md
Labels: Ready-to-Merge

#16158 correct syntax for Raven.capture_exception
  app/jobs/virtual_hearings/create_conference_job.rb
Labels: Ready-to-Merge, Source: Bat Team, Team: Tango 💃

#16154 Don't create BvaDispatchTask if QualityReviewTask is open
  app/models/tasks/bva_dispatch_task.rb
  app/workflows/complete_case_review.rb
  spec/feature/queue/judge_checkout_flow_spec.rb
  spec/models/tasks/bva_dispatch_task_spec.rb
  spec/records/appeal-dispatch_before_quality_review_complete.json
Labels: Ready-to-Merge, Team: Echo 🐬, Type: Bug

#16155 Remove 'substitution' appeal stream type
  app/models/appeal.rb
  app/models/appellant_substitution.rb
  app/models/serializers/work_queue/appeal_serializer.rb
  app/models/serializers/work_queue/appellant_substitution_serializer.rb
  app/queries/appeals_updated_since_query.rb
  app/workflows/initial_tasks_factory.rb
  client/constants/AMA_STREAM_TYPES.json
  spec/controllers/appellant_substitutions_controller_spec.rb
  spec/models/appellant_substitution_spec.rb
Labels: Ready-to-Merge, Team: Echo 🐬

#16141 CASEFLOW-1119 Create new appellant-substitute appeal matching original appeal
  app/models/appeal.rb
  app/models/appellant_substitution.rb
  app/workflows/initial_tasks_factory.rb
  spec/models/appellant_substitution_spec.rb
Labels: Ready-to-Merge, Team: Echo 🐬

#16166 Clear claimant data when submitting POA
  client/app/intake/addPOA/AddPoaPage.jsx
  spec/feature/intake/non_veteran_claimants_spec.rb
Labels: Ready-to-Merge, Team: Foxtrot 🦊

#16168 Additions to judge_queue_spec to support document IDs, etc
  spec/feature/queue/judge_queue_spec.rb
Labels: Ready-to-Merge

#16135 Fix state dropdown bugs on Add Claimant Page
  client/app/components/AddressForm.jsx
  client/app/constants/AppConstants.js
  client/app/intake/addClaimant/AddClaimantForm.jsx
  client/app/intake/addClaimant/utils.js
  client/test/app/intake/components/addClaimants/__snapshots__/AddClaimantForm.test.js.snap
  spec/feature/intake/non_veteran_claimants_spec.rb
Labels: Ready-to-Merge, Team: Foxtrot 🦊, Type: Bug

#16173 Revert "Allow sending Docket Switches to OCB VLJs only (#16087)" (#16110)" (#16140)"
  app/repositories/task_action_repository.rb
  client/app/queue/docketSwitch/recommendDocketSwitch/RecommendDocketSwitchContainer.jsx
  spec/feature/queue/docket_switch_spec.rb
Labels: Ready-to-Merge

#16098 Add keyboard shortcuts in reader for categories
  client/app/reader/PdfKeyboardInfo.jsx
  client/app/reader/PdfSidebar.jsx
  client/app/reader/SideBarCategories.jsx
Labels: Eng: Beginner Friendly, Priority: Low, Product: caseflow-reader, Ready-to-Merge, Stakeholder: BVA, Team: Echo 🐬, Type: Enhancement

#16172 Mkerns/caseflow 868 edge case
  spec/feature/queue/case_details_spec.rb
Labels: Ready-to-Merge

#16180 Update veteran date of death with correct date format
  app/models/veteran.rb
  lib/generators/veteran.rb
  spec/models/veteran_spec.rb
Labels: Ready-to-Merge

#16176 [PROD FIX] Restore decision doc on dispatched appeal
  lib/helpers/sanitation_transforms.rb
  lib/helpers/sanitized_json_configuration.rb
  spec/fixes/fixing_dispatched_appeal_spec.rb
  spec/lib/helpers/sanitized_json_exporter_spec.rb
  spec/records/appeal-no_decision_doc.json
Labels: Eng: Data Work Group, Source: Bat Team

#16177 Add redirects when page is reloaded on Add Claimant or Add POA pages
  client/app/intake/addClaimant/AddClaimantPage.jsx
  client/app/intake/addPOA/AddPoaPage.jsx
  client/app/intake/constants.js
  client/app/intake/selectors.js
  spec/feature/intake/non_veteran_claimants_spec.rb
Labels: Ready-to-Merge, Team: Foxtrot 🦊

#16178 Substitution: do not create typical initial tasks
  app/workflows/initial_tasks_factory.rb
  spec/models/appellant_substitution_spec.rb
Labels: Ready-to-Merge, Team: Echo 🐬

#16169 Use Task.of_type scope
  app/models/docket.rb
  app/models/docket_switch.rb
  app/models/task.rb
  app/workflows/bulk_task_reassignment.rb
  app/workflows/docket_switch/task_handler.rb
  app/workflows/judge_assign_task_creator.rb
  db/seeds/mtv.rb
  lib/helpers/sanitized_json_configuration.rb
  lib/tasks/fixes.rake
  spec/factories/appeal.rb
  spec/feature/hearings/schedule_veteran/build_hearsched_spec.rb
  spec/feature/queue/docket_switch_spec.rb
  spec/jobs/update_appellant_representation_job_spec.rb
  spec/lib/helpers/sanitized_json_exporter_spec.rb
  spec/models/concerns/hearing_request_type_concern_spec.rb
  spec/models/docket_switch_spec.rb
  spec/models/tasks/cavc_correspondence_mail_task_spec.rb
  spec/models/tasks/cavc_remand_processed_letter_response_window_task_spec.rb
  spec/models/tasks/docket_switch_mail_task_spec.rb
  spec/models/tasks/judge_task_spec.rb
  spec/models/tasks/schedule_hearing_task_spec.rb
  spec/models/tasks/send_cavc_remand_processed_letter_task_spec.rb
  spec/models/tasks/special_case_movement_shared_examples.rb
  spec/services/redistributed_case_spec.rb
  spec/services/va_dot_gov_address_validator_spec.rb
  spec/workflows/appeal_withdrawal_spec.rb
  spec/workflows/das_deprecation/case_distribution_spec.rb
  spec/workflows/docket_switch_task_handler_spec.rb
Labels: Ready-to-Merge

#16186 Snooze rexml warning
  .security.yml
Labels: Ready-to-Merge

#16174 Add new column to tasks table, add value for poa change to enum
  app/models/task.rb
  client/constants/TASK_CANCELLATION_REASONS.json
  db/migrate/20210426181017_add_cancellation_reason_to_tasks.rb
  db/schema.rb
  docs/schema/caseflow.csv
Labels: Ready-to-Merge, Team Victor

#16157 Substitute Appellant Tasks Page (Stage 1)
  client/COPY.json
  client/app/queue/colocatedTasks/AddAdminTaskForm/AddAdminTaskForm.jsx
  client/app/queue/colocatedTasks/AddAdminTaskForm/AddAdminTaskForm.stories.js
  client/app/queue/docketSwitch/grant/DocketSwitchEditTasksForm.jsx
  client/app/queue/substituteAppellant/SubstituteAppellantContainer.jsx
  client/app/queue/substituteAppellant/basics/SubstituteAppellantBasicsForm.jsx
  client/app/queue/substituteAppellant/poa/SubstituteAppellantPoaForm.jsx
  client/app/queue/substituteAppellant/review/SubstituteAppellantReview.jsx
  client/app/queue/substituteAppellant/styles.js
  client/app/queue/substituteAppellant/substituteAppellant.slice.js
  client/app/queue/substituteAppellant/tasks/KeyDetails.jsx
  client/app/queue/substituteAppellant/tasks/KeyDetails.stories.js
  client/app/queue/substituteAppellant/tasks/SubstituteAppellantTasksForm.jsx
  client/app/queue/substituteAppellant/tasks/SubstituteAppellantTasksForm.stories.js
  client/app/queue/substituteAppellant/tasks/SubstituteAppellantTasksView.jsx
  client/test/app/queue/colocatedTasks/AddAdminTaskForm/AddAdminTaskForm.test.js
  client/test/app/queue/colocatedTasks/AddAdminTaskForm/__snapshots__/AddAdminTaskForm.test.js.snap
  client/test/app/queue/substituteAppellant/KeyDetails.test.js
  client/test/app/queue/substituteAppellant/SubstituteAppellantTasksForm.test.js
  client/test/app/queue/substituteAppellant/__snapshots__/KeyDetails.test.js.snap
  client/test/app/queue/substituteAppellant/__snapshots__/SubstituteAppellantBasicsForm.test.js.snap
  client/test/app/queue/substituteAppellant/__snapshots__/SubstituteAppellantTasksForm.test.js.snap
  spec/feature/queue/substitute_appellant/shared_setup.rb
  spec/feature/queue/substitute_appellant/substitute_appellant_spec.rb
Labels: Ready-to-Merge

#16149 TimeSlot UI Fixes - Part of CASEFLOW-1115
  client/app/hearings/components/TimePicker.jsx
  client/app/hearings/components/scheduleHearing/TimeSlot.jsx
  client/app/hearings/components/scheduleHearing/TimeSlotButton.jsx
  client/app/hearings/utils.js
  client/test/app/hearings/components/scheduleHearing/TimeSlot.test.js
  client/test/app/hearings/components/scheduleHearing/__snapshots__/TimeSlot.test.js.snap
Labels: Ready-to-Merge

#16096 Decision review Routing – Subsequent Decision reviews Routed to Editing Station, Not Initial Intake Station
  app/models/appeal.rb
  app/models/claim_review.rb
  app/models/higher_level_review.rb
  app/models/request_issue.rb
  app/models/request_issues_update.rb
  app/models/supplemental_claim.rb
  spec/models/request_issues_update_spec.rb
Labels: Ready-to-Merge

#16187 Charley/caseflow 1115 use db values for timeslot calculation
  client/app/hearings/components/TimePicker.jsx
  client/app/hearings/components/scheduleHearing/TimeSlot.jsx
  client/app/hearings/utils.js
  client/test/app/hearings/components/scheduleHearing/TimeSlot.test.js
  client/test/app/hearings/components/scheduleHearing/__snapshots__/TimeSlot.test.js.snap
  client/test/app/hearings/utils.test.js
Labels: Ready-to-Merge

#16147 Add Slot Data to HearingDay - Caseflow-1115 backend changes
  app/controllers/regional_offices_controller.rb
  app/models/hearing_day.rb
  app/serializers/hearings/hearing_day_serializer.rb
  db/migrate/20210419200234_add_hearing_day_slot_columns.rb
  db/schema.rb
  docs/schema/caseflow.csv
  spec/models/hearing_day_spec.rb
Labels: Ready-to-Merge

#16188 Update KeyDetails test to use a non-dynamic date
  client/test/app/queue/substituteAppellant/KeyDetails.test.js
Labels: Ready-to-Merge

#16150 Only show slots for virtual hearing scheduling
  client/app/hearings/components/ScheduleVeteranForm.jsx
  spec/feature/hearings/schedule_veteran/build_hearsched_spec.rb
Labels: Ready-to-Merge

#16182 Add POA refresh tech spec
  docs/tech-specs/2021-3-31-poa-refresh
Labels: Ready-to-Merge

#16151 Moved Tech Spec from appeals-team
  docs/tech-specs/04-19-2021-HearingScheduleNoRoomsAlgorithm.md
Labels: Ready-to-Merge

#16171 Refresh POA from BGS after user selects a substitute appellant
  app/controllers/claimants_controller.rb
  client/COPY.json
  client/app/queue/CaseDetailsView.jsx
  client/app/queue/PowerOfAttorneyDetail.jsx
  client/app/queue/substituteAppellant/basics/SubstituteAppellantBasicsView.jsx
  client/app/queue/substituteAppellant/substituteAppellant.slice.js
  config/routes.rb
  spec/controllers/claimants_controller_spec.rb
  spec/feature/queue/case_details_spec.rb
  spec/feature/queue/substitute_appellant/shared_setup.rb
Labels: Ready-to-Merge, Team: Echo 🐬
