Repository department-of-veterans-affairs/caseflow, pull requests merged in 2021-08, with the labels that each got.

#16571 Make Issue description hash Sentry message more actionable
  app/models/issue.rb
Labels: Ready-to-Merge

#16572 Changed Hearings Scheduled column to display only scheduled hearings
  client/app/hearings/components/ListSchedule.jsx
  spec/feature/hearings/list_schedule/build_hearsched_spec.rb
Labels: Ready-to-Merge

#16565 Changed Docket request type label in HearingDayInfoButton
  client/app/hearings/components/assignHearings/HearingDayInfoButton.jsx
  client/app/hearings/constants.js
  client/test/app/hearings/components/HearingDayInfoButton.test.js
  client/test/app/hearings/components/__snapshots__/HearingDayInfoButton.test.js.snap
Labels: Ready-to-Merge

#16557 Remove CreateEstablishClaim service object
  app/services/create_establish_claim.rb
Labels: Eng: Backend Work Group, Ready-to-Merge, Type: Tech-Improvement

#16576 Implement AOD for unrecognized claimants
  app/models/attorney_claimant.rb
  app/models/other_claimant.rb
  spec/models/other_claimant_spec.rb
Labels: Ready-to-Merge, Source: Bat Team

#16569 Copy unrecognized appellant when copying claimants
  app/models/claimant.rb
  app/models/decision_review.rb
  app/models/unrecognized_appellant.rb
  spec/feature/queue/docket_switch_spec.rb
Labels: Ready-to-Merge

#16581 Fix setting of email_sent flags for recipients
  app/models/hearings/forms/base_hearing_update_form.rb
  spec/controllers/hearings_controller_spec.rb
Labels: Ready-to-Merge

#16584 Add nonformatted option to full name
  app/models/full_name.rb
  app/models/unrecognized_party_detail.rb
  spec/models/full_name_spec.rb
Labels: Ready-to-Merge

#16590 Fix bug where form being invalid on relationship change
  client/app/queue/editAppellantInformation/EditAppellantInformation.jsx
Labels: Ready-to-Merge

#16593 Fix bug in finding request issues without decision dates
  client/app/intake/pages/addIssues.jsx
  client/app/intake/reducers/appeal.js
  client/app/intake/reducers/supplementalClaim.js
  client/app/intake/util/issues.js
Labels: Ready-to-Merge, Source: Bat Team

#16583 Added Caregiver as an issue category
  Gemfile.lock
  app/controllers/api/docs/v3/decision_reviews.yaml
  client/constants/ISSUE_CATEGORIES.json
Labels: Ready-to-Merge

#16589 Don't create tmp/sql_tracker-*.json files in dev
  config/environments/development.rb
Labels: Ready-to-Merge

#16552 Indicate that intake form came from VA.gov
  client/app/intake/actions/decisionReview.js
  client/app/intake/components/BenefitType.jsx
  client/app/intake/constants.js
  client/app/intake/pages/appeal/review.jsx
  client/app/intake/pages/formGenerator.jsx
  client/app/intake/pages/receiptDateInput.jsx
  client/app/intake/reducers/appeal.js
  client/app/intake/reducers/common.js
  client/test/app/intake/pages/review.test.js
  spec/factories/appeal.rb
  spec/feature/intake/appeal_spec.rb
  spec/feature/intake/intake_spec.rb
  spec/feature/intake/non_veteran_claimants_spec.rb
  spec/feature/intake/time_zone_spec.rb
  spec/support/intake_helpers.rb
Labels: Ready-to-Merge

#16597 suggested changes for CASEFLOW-1618 stack
  app/controllers/hearings/schedule_periods_controller.rb
  app/services/hearing_schedule/assign_judges_to_hearing_days.rb
  app/services/hearing_schedule/validate_judge_spreadsheet.rb
  client/app/hearings/components/ReviewAssignments.jsx
  client/app/hearings/containers/BuildScheduleUploadContainer.jsx
  spec/controllers/hearings/schedule_periods_controller_spec.rb
  spec/feature/hearings/build_schedule/build_hearsched_spec.rb
  spec/repositories/user_repository_spec.rb
  spec/services/hearing_schedule/assign_judges_to_hearing_days_spec.rb
Labels: Team: Tango 💃

#16568 Explain page: improve usability and UX of the task tree and timeline
  app/assets/javascripts/explain-appeal-timeline.js
  app/models/concerns/task_tree_render_module.rb
  app/views/explain/_task_tree.html.erb
  app/views/explain/_timeline_chart.html.erb
Labels: Ready-to-Merge

#16601 Updated ColocatedTaskView test
  client/test/app/jestSetup.js
  client/test/app/queue/ColocatedTaskListView.test.js
  client/test/app/queue/__snapshots__/ColocatedTaskListView.test.js.snap
Labels: Ready-to-Merge

#16577 Updated display and added new columns for Judge assignment
  app/controllers/hearings/schedule_periods_controller.rb
  app/models/hearing_day.rb
  app/models/hearings/judge_non_availability.rb
  app/models/judge_schedule_period.rb
  app/models/schedule_period.rb
  app/serializers/hearings/hearing_day_serializer.rb
  app/services/cache_manager.rb
  app/services/hearing_schedule/assign_judges_to_hearing_days.rb
  app/services/hearing_schedule/get_spreadsheet_data.rb
  app/services/hearing_schedule/validate_judge_spreadsheet.rb
  app/services/user_reporter.rb
  client/COPY.json
  client/app/hearings/components/BuildSchedule.jsx
  client/app/hearings/components/BuildScheduleUpload.jsx
  client/app/hearings/components/ListSchedule.jsx
  client/app/hearings/components/ReviewAssignments.jsx
  client/app/hearings/constants.js
  client/app/hearings/containers/BuildScheduleUploadContainer.jsx
  client/app/hearings/containers/ListScheduleContainer.jsx
  client/app/hearings/containers/ReviewAssignmentsContainer.jsx
  client/test/karma/hearings/components/ReviewAssignments-test.js
  spec/controllers/hearings/schedule_periods_controller_spec.rb
  spec/factories/non_availability.rb
  spec/feature/hearings/build_schedule/build_hearsched_spec.rb
  spec/models/hearings/judge_non_availability_spec.rb
  spec/models/judge_schedule_period_spec.rb
  spec/repositories/user_repository_spec.rb
  spec/services/hearing_schedule/assign_judges_to_hearing_days_spec.rb
  spec/services/hearing_schedule/validate_judge_spreadsheet_spec.rb
  spec/support/judgeDuplicateDates.xlsx
  spec/support/judgeNotInDb.xlsx
  spec/support/judgeWrongDataType.xlsx
  spec/support/validJudgeSpreadsheet.xlsx
Labels: Ready-to-Merge

#16603 Extend snooze for CVE-2020-11023 for 1 week
  .security.yml
Labels: Ready-to-Merge

#16604 Fix BGS Participant ID lookup
  client/app/queue/LookupParticipantIdModal.jsx
Labels: Ready-to-Merge

#16574 Remove current blockers in the appeals process for unrecognized appellants
  app/models/decision_document.rb
  app/models/docket.rb
  app/models/tasks/bva_dispatch_task.rb
  spec/models/docket_spec.rb
  spec/models/tasks/bva_dispatch_task_spec.rb
Labels: Ready-to-Merge

#16600 Modify email copy for appellant and recipient when hearing is converted from virtual to video or central
  app/mailers/hearing_mailer.rb
  app/views/hearing_mailer/_appellant_location_changed.html.erb
  app/views/hearing_mailer/_representative_location_changed.html.erb
  lib/tasks/emails.rake
Labels: Ready-to-Merge

#16609 Board Grant Effectuation Bug Fix
  app/models/decision_document.rb
Labels: Ready-to-Merge

#16607 POA: Edit/Update Button
  app/models/serializers/work_queue/appeal_serializer.rb
  app/views/queue/index.html.erb
  client/COPY.json
  client/app/queue/CaseDetailsView.jsx
  client/app/queue/utils.js
  spec/feature/queue/unrecognized_appellant_spec.rb
Labels: Ready-to-Merge

#16564 Jcurcio/caseflow 1948 pre docket task behavior
  app/models/appeal.rb
  app/workflows/initial_tasks_factory.rb
  app/workflows/pre_docket_tasks_factory.rb
  client/constants/TASK_ACTIONS.json
  spec/workflows/initial_tasks_factory_spec.rb
Labels: Ready-to-Merge

#16595 Redirect to error page when user doesn't have sensitivity level
  app/controllers/claim_review_controller.rb
  app/controllers/errors_controller.rb
  app/views/errors/403.html.erb
  client/COPY.json
  client/app/errors/Error403.jsx
  client/app/index.js
  config/routes.rb
  spec/factories/supplemental_claim.rb
  spec/feature/intake/intake_spec.rb
  spec/feature/queue/case_details_spec.rb
Labels: Type: Tech-Improvement, Team: Foxtrot 🦊

#16592 Add methods for polymorphic associations to decision reviews
  Gemfile
  Gemfile.lock
  app/models/concerns/belongs_to_polymorphic_appeal_concern.rb
  app/models/decision_document.rb
  app/models/decision_issue.rb
  app/models/task.rb
  docs/schema/caseflow-belongs_to_erd-subclasses.svg
  docs/schema/caseflow-belongs_to_erd.svg
  docs/schema/caseflow-subclasses.svg
  lib/helpers/association_wrapper.rb
  lib/helpers/sanitized_json_configuration.rb
  lib/tasks/support/erd_record_associations.rb
  spec/lib/helpers/association_wrapper_spec.rb
  spec/lib/helpers/sanitized_json_exporter_spec.rb
  spec/models/concerns/belongs_to_polymorphic_appeal_concern_spec.rb
  spec/query_subscriber.rb
Labels: Ready-to-Merge

#16612 Explain page: use Organizations to allow additional access
  app/controllers/explain_controller.rb
  app/models/organizations/board_product_owners.rb
  app/models/organizations/caseflow_support.rb
  app/models/organizations/dvc_team.rb
  app/models/organizations/judge_team.rb
  spec/controllers/explain_controller_spec.rb
Labels: Ready-to-Merge

#16608 Update POA page
  client/COPY.json
  client/app/intake/addClaimant/ClaimantForm.jsx
  client/app/intake/addClaimant/utils.js
  client/app/queue/QueueApp.jsx
  client/app/queue/editPOAInformation/EditPOAInformation.jsx
  client/app/queue/editPOAInformation/utils.js
  spec/feature/queue/unrecognized_appellant_spec.rb
Labels: Ready-to-Merge

#16613 Put date of birth field behind feature toggle
  client/app/intake/IntakeFrame.jsx
  client/app/intake/addClaimant/AddClaimantPage.jsx
  client/app/intake/addClaimant/ClaimantForm.jsx
Labels: Ready-to-Merge

#16624 Add debt items to issue categories
  app/controllers/api/docs/v3/decision_reviews.yaml
  client/constants/ISSUE_CATEGORIES.json
Labels: Ready-to-Merge

#16622 update tab panel tab index for test users page
  client/app/components/TabWindow.jsx
  client/app/components/tabs/TabPanel.jsx
  client/app/components/tabs/Tabs.jsx
  client/app/test/TestUsers.jsx
  client/test/app/components/__snapshots__/TabWindow.test.js.snap
  client/test/app/components/tabs/Tabs.test.js
  client/test/app/components/tabs/__snapshots__/Tabs.test.js.snap
  client/test/app/queue/__snapshots__/ColocatedTaskListView.test.js.snap
Labels: Ready-to-Merge

#16630 Remaing changes for the update POA work
  app/views/queue/index.html.erb
  client/app/intake/addClaimant/ClaimantForm.jsx
  client/app/queue/CaseDetailsView.jsx
  client/app/queue/QueueApp.jsx
  spec/feature/queue/unrecognized_appellant_spec.rb
Labels: Ready-to-Merge

#16586 Expand the only_open_task_of_type validation to AttorneyTask and JudgeDecisionReviewTask
  app/models/task.rb
  app/models/tasks/attorney_task.rb
  app/models/tasks/docket_switch/docket_switch_abstract_attorney_task.rb
  app/models/tasks/judge_assign_task.rb
  app/models/tasks/judge_decision_review_task.rb
  spec/feature/queue/case_details_spec.rb
  spec/feature/queue/judge_assignment_spec.rb
  spec/feature/queue/task_queue_spec.rb
  spec/fixes/investigate_duplicate_judge_tasks_spec.rb
  spec/models/appeal_spec.rb
  spec/models/concerns/task_tree_render_module_spec.rb
  spec/models/tasks/attorney_task_spec.rb
  spec/models/tasks/colocated_task_spec.rb
  spec/models/tasks/judge_task_spec.rb
Labels: Ready-to-Merge

#16570 Foreign Key Polymorphic Association Job
  .reek.yml
  app/controllers/api/v1/jobs_controller.rb
  app/jobs/foreign_key_polymorphic_association_job.rb
  app/models/claimant.rb
  app/models/concerns/belongs_to_polymorphic_appeal_concern.rb
  app/models/concerns/belongs_to_polymorphic_hearing_concern.rb
  app/models/hearings/hearing_email_recipient.rb
  app/models/hearings/sent_hearing_email_event.rb
  app/models/special_issue_list.rb
  app/models/vbms_uploaded_document.rb
  config/initializers/immigrant.rb
  db/schema.rb
  spec/jobs/foreign_key_polymorphic_association_job_spec.rb
  spec/lib/helpers/sanitized_json_exporter_spec.rb
Labels: Ready-to-Merge

#16617 ETL DB: add judge_case_reviews and decision_documents tables
  app/models/appeal.rb
  app/models/etl/decision_document.rb
  app/models/etl/judge_case_review.rb
  app/models/etl/record.rb
  app/services/concerns/etl_classes.rb
  app/services/etl/decision_document_syncer.rb
  app/services/etl/judge_case_review_syncer.rb
  db/etl/migrate/20210810115309_create_etl_judge_case_review.rb
  db/etl/migrate/20210810115459_create_etl_decision_document.rb
  db/etl/schema.rb
  db/migrate/20210813122051_add_decision_document_comments.rb
  db/schema.rb
  docs/schema/caseflow-belongs_to_erd-subclasses.svg
  docs/schema/caseflow-belongs_to_erd.svg
  docs/schema/caseflow-subclasses.svg
  docs/schema/caseflow.csv
  docs/schema/etl.csv
  spec/services/etl/decision_document_syncer_spec.rb
  spec/services/etl/judge_case_review_syncer_spec.rb
  spec/services/etl/syncer_spec.rb
Labels: Ready-to-Merge

#16631 Skip creation of docket tasks for pre-docket appeals
  app/models/appeal.rb
  app/workflows/initial_tasks_factory.rb
  app/workflows/pre_docket_tasks_factory.rb
  spec/feature/queue/pre_docket_spec.rb
  spec/support/intake_helpers.rb
  spec/workflows/initial_tasks_factory_spec.rb
  spec/workflows/pre_docket_tasks_factory_spec.rb
Labels: Team Victor

#16623 Log, Dont Send, 7 & 3 Day Reminder Emails for Video/Central Hearings
  .reek.yml
  app/jobs/hearings/send_email.rb
  app/jobs/hearings/send_reminder_emails_job.rb
  app/repositories/hearing_repository.rb
  app/services/hearings/reminder_service.rb
  spec/jobs/hearings/send_reminder_emails_job_spec.rb
  spec/repositories/hearing_repository_spec.rb
  spec/services/hearings/reminder_service_spec.rb
Labels: Ready-to-Merge

#16588 Tests for CASEFLOW-1501
  spec/feature/queue/substitute_appellant/substitute_appellant_task_copy_spec.rb
  spec/models/appellant_substitution_spec.rb
Labels: Ready-to-Merge, Team: Echo 🐬

#16642 Don't re-initialize ErdRecordAssociations::EXCLUDED_ASSOCIATIONS constant
  lib/tasks/support/erd_record_associations.rb
Labels: Ready-to-Merge

#16632 Add Danger CI step back
  .circleci/config.yml
Labels: Ready-to-Merge

#16641 ForeignKeyPolymorphicAssociationJob: fix Slack message
  app/jobs/foreign_key_polymorphic_association_job.rb
  spec/jobs/foreign_key_polymorphic_association_job_spec.rb
Labels: Ready-to-Merge

#16649 Add a VHA Program Office section to the team management page
  app/controllers/team_management_controller.rb
  client/COPY.json
  client/app/queue/TeamManagement.jsx
  client/app/queue/teamManagement/reducers.js
  spec/feature/queue/team_management_spec.rb
Labels: Ready-to-Merge, Team Victor

#16637 Prevent outcode success if file number not match BGS
  app/workflows/ama_appeal_dispatch.rb
  lib/caseflow/error.rb
  spec/controllers/idt/api/appeals_controller_spec.rb
Labels: Ready-to-Merge

#16646 Add VHA Program Office DB seeds
  app/models/tasks/pre_docket/vha_document_search_task.rb
  db/seeds.rb
  db/seeds/veterans_health_administration.rb
  spec/feature/queue/pre_docket_spec.rb
  spec/models/organization_spec.rb
  spec/seeds/veterans_health_administration_spec.rb
  spec/workflows/pre_docket_tasks_factory_spec.rb
Labels: Ready-to-Merge, Team Victor

#16648 Intake renderer lint fixes
  lib/helpers/intake_renderer.rb
Labels: Ready-to-Merge

#16660 Send DoB field from backend and properly set it in frontend
  app/controllers/intakes_controller.rb
  client/app/intake/addClaimant/AddClaimantPage.jsx
Labels: Ready-to-Merge

#16639 Log but don't actually send 60 day reminder emails to only appellant for all types of hearing
  app/helpers/hearings/calendar_template_helper.rb
  app/helpers/virtual_hearings/link_helper.rb
  app/jobs/hearings/send_email.rb
  app/jobs/hearings/send_reminder_emails_job.rb
  app/mailers/hearing_mailer.rb
  app/repositories/hearing_repository.rb
  app/services/hearings/reminder_service.rb
  app/views/hearing_mailer/_appellant_location_changed.html.erb
  app/views/hearing_mailer/_appellant_reminder.html.erb
  app/views/hearing_mailer/sections/_additional_reminder_details.html.erb
  app/views/hearing_mailer/sections/_internal_use.html.erb
  app/views/hearing_mailer/sections/_rescheduling_or_canceling_your_hearing.erb
  app/views/hearing_mailer/sections/_test_your_connection.html.erb
  app/views/layouts/hearing_mailer.html.erb
  client/constants/DATADOG_METRICS.json
  lib/tasks/emails.rake
  spec/jobs/hearings/send_reminder_emails_job_spec.rb
  spec/mailers/hearing_mailer_spec.rb
  spec/repositories/hearing_repository_spec.rb
  spec/services/hearings/reminder_service_spec.rb
Labels: Ready-to-Merge

#16640 Use VACOLS name for VLJ assignment and validation
  app/models/cached_user.rb
  app/models/hearing_day.rb
  app/queries/hearing_day_judge_name_query.rb
  app/serializers/hearings/hearing_day_serializer.rb
  app/services/hearing_schedule/assign_judges_to_hearing_days.rb
  app/services/hearing_schedule/validate_judge_spreadsheet.rb
  spec/controllers/hearings/schedule_periods_controller_spec.rb
  spec/feature/hearings/build_schedule/build_hearsched_spec.rb
  spec/feature/hearings/list_schedule/vso_spec.rb
  spec/models/cached_user_spec.rb
  spec/queries/hearing_day_judge_name_query_spec.rb
  spec/services/hearing_schedule/assign_judges_to_hearing_days_spec.rb
  spec/services/hearing_schedule/validate_judge_spreadsheet_spec.rb
  spec/support/judgeNotInDb.xlsx
Labels: Team: Tango 💃, Ready-to-Merge

#16661 Attorney and Judge case reviews: associate directly with appeal record
  app/controllers/case_reviews_controller.rb
  app/jobs/foreign_key_polymorphic_association_job.rb
  app/models/appeal.rb
  app/models/appellant_substitution.rb
  app/models/attorney_case_review.rb
  app/models/concerns/appeal_concern.rb
  app/models/concerns/case_review_concern.rb
  app/models/judge_case_review.rb
  app/models/legacy_appeal.rb
  app/models/work_mode.rb
  app/queries/appeals_updated_since_query.rb
  db/migrate/20210820153715_add_appeal_association_to_case_reviews.rb
  db/schema.rb
  docs/schema/caseflow.csv
  spec/controllers/case_reviews_controller_spec.rb
  spec/factories/attorney_case_review.rb
  spec/factories/judge_case_review.rb
  spec/lib/helpers/sanitized_json_exporter_spec.rb
  spec/models/attorney_case_review_spec.rb
  spec/models/judge_case_review_spec.rb
Labels: Ready-to-Merge

#16633 Resolve interaction delays for Test Users dropdown
  client/app/components/SearchableDropdown.jsx
  client/app/test/TestUsers.jsx
Labels: Type: Tech-Improvement, Type: Bug, Ready-to-Merge

#16651 ETL: fix population of decision docs table
  app/models/etl/build.rb
  app/models/etl/decision_document.rb
  app/models/etl/judge_case_review.rb
  app/models/etl/record.rb
  app/models/etl/user.rb
  app/models/legacy_appeal.rb
  app/services/etl/builder.rb
  app/services/etl/syncer.rb
  spec/services/etl/builder_spec.rb
  spec/services/etl/decision_document_syncer_spec.rb
  spec/services/etl/syncer_spec.rb
  spec/services/etl/user_syncer_spec.rb
Labels: Ready-to-Merge, Eng: Data Work Group

#16596 Remove judge name from case details hearing section
  app/controllers/appeals_controller.rb
  app/models/serializers/work_queue/appeal_serializer.rb
  app/models/serializers/work_queue/legacy_appeal_serializer.rb
  app/serializers/hearings/appeal_hearing_serializer.rb
  app/serializers/helpers/appeal_hearing_helper.rb
  client/app/queue/CaseHearingsDetail.jsx
  client/test/app/queue/__snapshots__/CaseHearingsDetail.test.js.snap
  spec/serializers/appeal_hearing_serializer_spec.rb
Labels: Ready-to-Merge

#16658 1982: ama only push job testing
  spec/jobs/push_priority_appeals_to_judges_job_spec.rb
Labels: Ready-to-Merge

#16663 make docs: Don't update DB schema images by default
  lib/tasks/doc.rake
Labels: Ready-to-Merge

#16655 Prevent `JudgeAssignTask` from changing status from cancelled to completed
  app/controllers/judge_assign_tasks_controller.rb
  lib/caseflow/error.rb
  spec/fixes/investigate_duplicate_judge_tasks_spec.rb
Labels: Ready-to-Merge

#16653 Mkerns/caseflow 2066 add visn orgs
  client/constants/VISN_ORG_NAMES.json
  db/seeds/veterans_health_administration.rb
  spec/seeds/veterans_health_administration_spec.rb
Labels: Ready-to-Merge

#16634 Create CAMO PreDocket task
  app/models/tasks/pre_docket/assess_documentation_task.rb
  app/models/tasks/pre_docket/pre_docket_task.rb
  app/models/tasks/pre_docket/vha_document_search_task.rb
  app/models/tasks/pre_docket_task.rb
  app/workflows/pre_docket_tasks_factory.rb
  client/COPY.json
  spec/factories/task.rb
  spec/feature/queue/pre_docket_spec.rb
  spec/models/tasks/vha_document_search_task_spec.rb
  spec/workflows/pre_docket_tasks_factory_spec.rb
Labels: Ready-to-Merge, Team Victor

#16670 ETL case_review records: update association to appeals
  app/models/etl/attorney_case_review.rb
  app/models/etl/judge_case_review.rb
  spec/feature/queue/judge_checkout_flow_spec.rb
  spec/services/etl/judge_case_review_syncer_spec.rb
Labels: Ready-to-Merge

#16673 For attorney_case_reviews and judge_case_reviews, set polymorphic true
  app/models/concerns/appeal_concern.rb
Labels: Ready-to-Merge

#16647 Exclude contested claimants from list of legacy appeal representatives
  app/models/legacy_appeal.rb
  app/models/vacols/case.rb
  app/models/vacols/representative.rb
  spec/models/legacy_appeal_spec.rb
  spec/models/vacols/case_spec.rb
Labels: Ready-to-Merge

#16674 Add empty route for updating POA
  app/controllers/unrecognized_appellants_controller.rb
  config/routes.rb
  spec/controllers/unrecognized_appellant_controller_spec.rb
Labels: Ready-to-Merge

#16672 Fix NoMethodError in Hearings::SendEmail job
  app/jobs/hearings/send_email.rb
  app/jobs/hearings/send_reminder_emails_job.rb
  spec/jobs/hearings/send_email_spec.rb
Labels: Team: Tango 💃, Ready-to-Merge

#16678 Fixed test to show correct number of VISN Offices
  spec/seeds/veterans_health_administration_spec.rb
Labels: Ready-to-Merge

#16677 Add VHA Regional Office (VISN) team management page section
  app/controllers/team_management_controller.rb
  client/COPY.json
  client/app/queue/TeamManagement.jsx
  client/app/queue/teamManagement/reducers.js
  spec/feature/queue/team_management_spec.rb
Labels: Ready-to-Merge, Team Victor

#16682 Remove unneeded rake commands
  docker-bin/startup.sh
Labels: Ready-to-Merge

#16698 suggested changes for #16685
  app/services/external_api/gov_delivery_service.rb
  app/services/external_api/gov_delivery_service/response.rb
  config/initializers/gov_delivery.rb
  lib/fakes/gov_delivery_service.rb
  spec/services/external_api/gov_delivery_service_spec.rb
Labels: Team: Tango 💃

#16650 Skip Creation of VeteranRecordRequest Task on Pre-Docket Appeals
  app/models/request_issue.rb
  spec/models/appeal_spec.rb
Labels: Ready-to-Merge

#16692 Database Changes - Add SentHearingAdminEmailEvent
  app/models/hearings/sent_hearing_admin_email_event.rb
  app/models/hearings/sent_hearing_email_event.rb
  db/migrate/20210826144628_create_sent_hearing_admin_email_events.rb
  db/migrate/20210826145249_add_updated_status_columns_to_sent_hearing_email_events.rb
  db/schema.rb
  docs/schema/caseflow.csv
Labels: Team: Tango 💃, Ready-to-Merge

#16685 Shalliburton/caseflow 2216 govdelivery api service
  app/services/external_api/gov_delivery_service.rb
  app/services/external_api/gov_delivery_service/response.rb
  config/initializers/gov_delivery.rb
  lib/caseflow/error.rb
  lib/fakes/gov_delivery_service.rb
  spec/services/external_api/gov_delivery_service_spec.rb
Labels: Ready-to-Merge

#16680 Add Mailer and Sender Classes for Delivery Notification Emails
  .reek.yml
  app/helpers/hearings/calendar_template_helper.rb
  app/helpers/virtual_hearings/link_helper.rb
  app/jobs/hearings/send_sent_status_email.rb
  app/mailers/hearing_email_status_mailer.rb
  app/views/hearing_email_status_mailer/notification.html.erb
  app/views/layouts/hearing_email_status_mailer.html.erb
  client/constants/DATADOG_METRICS.json
  lib/tasks/emails.rake
  spec/factories/hearing.rb
  spec/factories/sent_hearing_admin_email_event.rb
  spec/jobs/hearings/send_sent_status_email_spec.rb
  spec/mailers/hearing_email_status_mailer_spec.rb
Labels: Team: Tango 💃, Ready-to-Merge

#16689 Add the "on hold" action to the Assess Documentation task
  app/models/tasks/pre_docket/assess_documentation_task.rb
  spec/factories/task.rb
  spec/models/organizations/vha_program_office_spec.rb
  spec/models/tasks/assess_documentation_task_spec.rb
Labels: Ready-to-Merge

#16696 Add filed by va.gov to HLRs
  app/controllers/intakes_controller.rb
  app/models/higher_level_review_intake.rb
  client/app/intake/constants.js
  client/app/intake/pages/formGenerator.jsx
  client/app/intake/pages/higherLevelReview/review.jsx
  client/app/intake/reducers/featureToggles.js
  client/app/intake/reducers/higherLevelReview.js
  spec/feature/intake/higher_level_review_spec.rb
Labels: Ready-to-Merge

#16708 Snooze jquery-rails again
  .security.yml
Labels: Ready-to-Merge

#16694 Batch caching of AMA appeal attributes
  app/jobs/update_cached_appeals_attributes_job.rb
Labels: Ready-to-Merge

#16695 Added SentHearingEmailEvent#handle_reported_status
  app/models/hearings/sent_hearing_email_event.rb
  spec/factories/sent_hearing_email_event.rb
  spec/models/hearings/sent_hearing_email_event_spec.rb
Labels: Team: Tango 💃, Ready-to-Merge

#16702 Fix refresh POA button visibility
  client/app/queue/PowerOfAttorneyDetail.jsx
  spec/feature/queue/unrecognized_appellant_spec.rb
Labels: Ready-to-Merge

#16684 Swap confirmation message depending on type of issues
  app/serializers/intake/request_issue_serializer.rb
  client/app/intake/pages/decisionReviewIntakeCompleted.jsx
  spec/feature/intake/appeal/edit_spec.rb
  spec/feature/intake/confirmation_page_spec.rb
  spec/feature/intake/higher_level_review/edit_spec.rb
  spec/support/intake_helpers.rb
Labels: Ready-to-Merge
