Repository department-of-veterans-affairs/caseflow, pull requests merged in 2021-12, with the labels that each got.

#17008 snooze security alerts a week
  .security.yml
Labels: Ready-to-Merge

#16979 Bug fix for IhpDaysWaitingTooltip and ContestedClaimBadge tooltip
  client/app/components/badges/ContestedBadge/ContestedClaimBadge.jsx
  client/app/queue/components/IhpDaysWaitingTooltip.jsx
  client/app/queue/components/TaskTableColumns.jsx
  client/test/app/queue/components/__snapshots__/IhpDaysWaitingTooltip.test.js.snap
Labels: Ready-to-Merge

#16978 Show Transcription task instructions and add Assigned By column
  app/models/queue_tabs/organization_unassigned_tasks_tab.rb
  app/models/serializers/work_queue/task_column_serializer.rb
  app/models/task_sorter.rb
  client/COPY.json
  client/app/queue/QueueTableBuilder.jsx
  client/app/queue/components/TaskTableColumns.jsx
  client/app/queue/components/TranscriptionTaskTooltip.jsx
  client/constants/QUEUE_CONFIG.json
  spec/models/queue_tabs/organization_unassigned_tasks_tab_spec.rb
Labels: Ready-to-Merge

#17001 Add foreign key on remand_reasons.decision_issue_id
  config/initializers/immigrant.rb
  db/migrate/20211130172246_add_foreign_key_on_remand_reasons_to_decision_issues.rb
  db/migrate/20211130172307_validate_foreign_key_on_remand_reasons_to_decision_issues.rb
  db/schema.rb
Labels: Ready-to-Merge

#17002 Add foreign key certification_cancellations.certification_id
  config/initializers/immigrant.rb
  db/migrate/20211130175218_add_foreign_key_on_certification_cancellation_to_certifications.rb
  db/migrate/20211130175237_validate_foreign_key_on_certification_cancellation_to_certifications.rb
  db/schema.rb
  spec/controllers/certification_cancellations_controller_spec.rb
Labels: Ready-to-Merge

#17010 LegacyAppealsWithNoVacolsCase: ignore cases backfilled for foreign key
  app/services/legacy_appeals_with_no_vacols_case.rb
  spec/services/legacy_appeals_with_no_vacols_case_spec.rb
Labels: Ready-to-Merge

#17007 Refactor Schedule Veterans page to fetch hearings separately
  client/app/hearings/components/assignHearings/AssignHearingsTabs.jsx
  client/app/hearings/components/assignHearings/UpcomingHearingsTable.jsx
  client/app/hearings/utils.js
  client/test/app/hearings/components/__snapshots__/HearingDayInfoButton.test.js.snap
  client/test/app/hearings/components/assignHearings/__snapshots__/HearingDaysNav.test.js.snap
Labels: Team: Tango 💃, Ready-to-Merge

#16994 Pagination Prep Hearings APP
  app/models/hearing_day.rb
  app/services/hearing_day_range.rb
Labels: Team: Tango 💃, Ready-to-Merge

#17005 Refactor schedule veteran page
  app/controllers/hearings/hearing_day_controller.rb
  app/controllers/hearings_controller.rb
  app/controllers/regional_offices_controller.rb
  app/jobs/warm_bgs_caches_job.rb
  app/services/hearing_day_range.rb
  client/app/hearings/components/assignHearings/AssignHearingsTabs.jsx
  client/app/hearings/components/assignHearings/UpcomingHearingsTable.jsx
  client/app/hearings/utils.js
  client/test/app/hearings/components/__snapshots__/HearingDayInfoButton.test.js.snap
  client/test/app/hearings/components/assignHearings/__snapshots__/HearingDaysNav.test.js.snap
  config/routes.rb
  spec/services/hearing_day_range_spec.rb
Labels: Team: Tango 💃, Ready-to-Merge

#17021 Change expected alert text to fix failing test
  spec/feature/hearings/hearing_details_spec.rb
Labels: Team: Tango 💃, Ready-to-Merge

#17011 Add badges attribute to AppealDetailsSerializer
  app/models/serializers/idt/v1/appeal_details_serializer.rb
  spec/models/serializers/idt/appeal_details_serializer_spec.rb
Labels: Ready-to-Merge

#17012 Jrobinson/add migrations to health status
  app/controllers/health_checks_controller.rb
Labels: Ready-to-Merge

#16993 Add BVA Intake Queue
  app/models/organizations/bva_intake.rb
  app/models/queue_tabs/bva_intake_completed_tab.rb
  app/models/queue_tabs/bva_intake_pending_tab.rb
  app/models/queue_tabs/bva_intake_ready_for_review_tab.rb
  app/models/serializers/work_queue/task_column_serializer.rb
  app/models/task.rb
  client/COPY.json
  client/app/queue/QueueTableBuilder.jsx
  client/app/queue/components/TaskTableColumns.jsx
  client/app/queue/utils.js
  client/constants/QUEUE_CONFIG.json
  spec/factories/bva_intake.rb
  spec/feature/queue/bva_intake_completed_tasks_tab_spec.rb
  spec/feature/queue/bva_intake_queue_spec.rb
  spec/feature/queue/bva_intake_ready_for_review_tasks_tab_spec.rb
Labels: Ready-to-Merge

#17009 NightlySyncsJob: account for dispatch_tasks
  app/jobs/nightly_syncs_job.rb
  app/models/dispatch/task.rb
  spec/jobs/nightly_syncs_job_spec.rb
Labels: Ready-to-Merge

#17025 Add test to verify old tasks remain
  spec/feature/queue/bva_intake_completed_tasks_tab_spec.rb
Labels: Ready-to-Merge

#16987 Create correct tasks during a same appeal substitution
  app/models/appellant_substitution.rb
  app/workflows/initial_tasks_factory.rb
  app/workflows/same_appeal_substitution_tasks_factory.rb
  client/app/queue/substituteAppellant/tasks/utils.js
  client/test/app/queue/substituteAppellant/tasks/utils.test.js
  spec/feature/queue/substitute_appellant/shared_setup.rb
  spec/workflows/same_appeal_substitution_tasks_factory_spec.rb
Labels: Ready-to-Merge

#17015 CheckTaskTree: check for multiple open root-children tasks
  lib/helpers/check_task_tree.rb
  spec/lib/helpers/check_task_tree_spec.rb
Labels: Ready-to-Merge

#17022 DataIntegrityChecksJob: detect multiple open root-child tasks
  app/jobs/data_integrity_checks_job.rb
  app/services/multiple_open_root_child_task_checker.rb
  lib/helpers/check_task_tree.rb
  spec/services/multiple_open_root_child_task_checker_spec.rb
Labels: Ready-to-Merge

#17026 Add aasm_state index on dispatch_tasks
  db/migrate/20211206223908_add_index_aasm_state_to_dispatch_tasks.rb
  db/schema.rb
Labels: Ready-to-Merge

#17033 Bug fix: VLJ Name Display Has Extra Symbols On Daily Docket
  client/app/hearings/components/dailyDocket/DailyDocket.jsx
Labels: Ready-to-Merge

#17032 Demo Data: Add Legacy Appeals for Hearing Scheduling
  db/seeds/tasks.rb
  spec/factories/vacols/case.rb
Labels: Ready-to-Merge

#17003 Rails console tweaks: add count_freq
  lib/helpers/finder_console_methods.rb
  lib/helpers/production_console_methods.rb
Labels: Ready-to-Merge

#17037 Snooze
  .security.yml
Labels: Ready-to-Merge

#17036 Add behavior for Bva Intake queue "Pending" tab
  app/models/organizations/bva_intake.rb
  app/models/queue_tabs/bva_intake_pending_tab.rb
  app/models/serializers/work_queue/task_column_serializer.rb
  client/COPY.json
  client/app/queue/QueueTableBuilder.jsx
  client/app/queue/components/TaskTableColumns.jsx
  client/app/queue/utils.js
  client/constants/QUEUE_CONFIG.json
  spec/factories/bva_intake.rb
  spec/models/queue_tabs/bva_intake_completed_tasks_tab_spec.rb
  spec/models/queue_tabs/bva_intake_pending_tasks_tab_spec.rb
  spec/models/queue_tabs/bva_intake_ready_for_review_tasks_tab_spec.rb
Labels: Ready-to-Merge

#17031 Update display name of CAMO document search parent task
  app/models/tasks/pre_docket/vha_document_search_task.rb
  client/COPY.json
  client/app/queue/selectors.js
  spec/feature/queue/pre_docket_spec.rb
  spec/models/tasks/vha_document_search_task_spec.rb
Labels: Ready-to-Merge

#17042 Add appeal index to AodMotions table
  db/migrate/20211213180551_add_appeal_index_to_aod_motions.rb
  db/schema.rb
Labels: Ready-to-Merge

#17029 BVA intake action to return predocket appeals to CAMO
  app/models/tasks/pre_docket/pre_docket_task.rb
  app/repositories/task_action_repository.rb
  client/COPY.json
  client/app/queue/AssignToView.jsx
  client/app/queue/QueueApp.jsx
  client/constants/TASK_ACTIONS.json
Labels: Ready-to-Merge, Team Victor

#17044 DataIntegrityChecksJob: add OpenTasksWithParentNotOnHold checker
  app/jobs/data_integrity_checks_job.rb
  app/services/open_tasks_with_closed_at_checker.rb
  app/services/open_tasks_with_parent_not_on_hold.rb
  lib/helpers/check_task_tree.rb
  spec/services/open_tasks_with_closed_at_checker_spec.rb
  spec/services/open_tasks_with_parent_not_on_hold_spec.rb
Labels: Ready-to-Merge

#17020 Test JudgeAssignTaskCreator call method
  spec/workflows/judge_assign_task_creator_spec.rb
Labels: Ready-to-Merge

#17048 Disable ITF when veteran has a reported date of death
  app/workflows/end_product_code_selector.rb
  spec/workflows/end_product_code_selector_spec.rb
Labels: Ready-to-Merge

#17039 Prevent log message: Overwriting existing method Dispatch::Task.open
  app/models/dispatch/task.rb
Labels: Ready-to-Merge

#17041 StuckAppealsChecker: ignore post-dispatch tasks when checking for open child tasks with closed RootTask
  app/queries/appeals_with_closed_root_task_open_children_query.rb
  app/services/open_tasks_with_parent_not_on_hold.rb
  app/services/stuck_appeals_checker.rb
  spec/services/stuck_appeals_checker_spec.rb
Labels: Ready-to-Merge

#17024 CASEFLOW-2460 - Display attorney notes on the Judge decision review task
  app/models/attorney_case_review.rb
  client/COPY.json
  spec/models/attorney_case_review_spec.rb
Labels: Ready-to-Merge

#17040 Cancel Defunct Hearing Tasks during Pending-Appeal Substitution
  app/models/task.rb
  app/workflows/same_appeal_substitution_tasks_factory.rb
  client/constants/TASK_CANCELLATION_REASONS.json
  spec/workflows/same_appeal_substitution_tasks_factory_spec.rb
Labels: Ready-to-Merge

#17027 Resolve Storybook not loading in production
  client/app/components/Table.stories.js
  client/app/queue/components/StartHoldModal.stories.js
Labels: Ready-to-Merge

#17059 Snooze Ruby package updates until next week
  .security.yml
Labels: Ready-to-Merge

#17049 Do not raise error when BGS returns no POAs in AppealsForPOA
  app/services/appeals_for_poa.rb
  spec/services/appeals_for_poa_spec.rb
Labels: Ready-to-Merge

#17057 Update CC indicator logic -- contested death claims
  app/models/appeal.rb
  spec/models/appeal_spec.rb
Labels: Ready-to-Merge

#17050 Replace Vocational Rehab benefit type
  client/app/constants/SpecialIssues.js
  client/app/intake/components/BenefitType.jsx
  client/constants/BENEFIT_TYPES.json
  spec/feature/intake/appeal_spec.rb
  spec/feature/intake/intake_spec.rb
Labels: Team: Foxtrot 🦊, Type: Bug, Ready-to-Merge

#17068 Snooze security alerts until after break
  .security.yml
Labels: Ready-to-Merge

#17046 Add validation to CAVC Court Decision, Mandate & Judgement Dates
  client/COPY.json
  client/app/queue/cavc/EditCavcRemandForm.jsx
  client/app/queue/cavc/EditCavcRemandForm.stories.js
  client/app/queue/cavc/utils.js
  client/test/app/queue/cavc/EditCavcRemandForm.test.js
  client/test/app/queue/cavc/__snapshots__/EditCavcRemandForm.test.js.snap
  client/test/data/queue/cavc/index.js
Labels: Ready-to-Merge

#17054 Fix Email Fallback and Duplicate/Orphan HearingEmailRecipients
  app/models/concerns/has_hearing_email_recipients_concern.rb
  app/services/hearing_time_service.rb
  spec/feature/hearings/hearing_details_spec.rb
Labels: Ready-to-Merge

#17045 Display end of 90-day submission window for VLJs
  app/assets/stylesheets/print/hearings_worksheet_overrides.scss
  app/models/concerns/hearing_concern.rb
  app/models/hearing.rb
  app/models/legacy_hearing.rb
  app/serializers/hearings/hearing_serializer.rb
  app/serializers/hearings/legacy_hearing_serializer.rb
  client/app/hearings/components/hearingWorksheet/WorksheetHeader.jsx
Labels: Ready-to-Merge

#17051 Add CAMO in progress tab
  app/models/organizations/vha_camo.rb
  app/models/queue_tabs/vha_camo_in_progress_tasks_tab.rb
  client/COPY.json
  client/constants/QUEUE_CONFIG.json
  spec/models/queue_tabs/vha_camo_in_progress_tasks_tab_spec.rb
Labels: Ready-to-Merge, Team Victor
