Repository department-of-veterans-affairs/caseflow, pull requests merged in 2021-03, with the labels that each got.

#15839 Fix alert banner overlap with "Switch views" button
  client/app/queue/QueueTableBuilder.jsx
  client/app/queue/components/QueueSelectorDropdown.jsx
Labels: Ready-to-Merge, Team: Echo 🐬

#15890 Add story for Boolean values for RadioField
  client/app/components/RadioField.stories.js
Labels: Ready-to-Merge

#15931 CASEFLOW-948 CAVC entry form: JMR/JMPR dynamic issue validation
  client/COPY.json
  client/app/queue/AddCavcRemandView.jsx
  client/test/app/queue/AddCavcRemandView.test.js
  client/test/app/queue/__snapshots__/AddCavcRemandView.test.js.snap
  spec/feature/queue/cavc_task_queue_spec.rb
Labels: Ready-to-Merge, Team: Echo 🐬

#15938 Docket Switch | Update Status on Tasks when Complete
  client/app/queue/docketSwitch/docketSwitchSlice.js
  client/app/queue/docketSwitch/judgeRuling/DocketSwitchRulingContainer.jsx
  client/app/queue/docketSwitch/judgeRuling/docketSwitchRulingSlice.js
  client/app/queue/docketSwitch/recommendDocketSwitch/RecommendDocketSwitchContainer.jsx
  client/app/queue/docketSwitch/recommendDocketSwitch/recommendDocketSwitchSlice.js
  spec/feature/queue/docket_switch_spec.rb
Labels: Ready-to-Merge

#15937 Cleanup AddCavcRemandView.jsx
  client/app/queue/AddCavcRemandView.jsx
Labels: Ready-to-Merge, Team: Echo 🐬

#15930 Backend data for time slots prototype
  app/controllers/hearings/hearing_day/filled_hearing_slots_controller.rb
  config/routes.rb
  spec/controllers/hearings/hearing_day/filled_hearing_slots_controller_spec.rb
Labels: Ready-to-Merge

#15945 Print expected order when task_sorter_spec test fails
  spec/models/task_sorter_spec.rb
Labels: Eng: Flaky Test, Ready-to-Merge

#15954 Add schema comment for Users.last_login_at
  db/migrate/20210302165940_add_comment_on_users_last_login_at.rb
  db/schema.rb
  docs/schema/caseflow.csv
Labels: Ready-to-Merge

#15951 Skip User.last_login_at saves up to 5 minutes after last write
  app/models/user.rb
  spec/models/user_spec.rb
Labels: Eng: Performance, Ready-to-Merge, Source: Bat Team, Type: Tech-Improvement

#15952 Use moment for timeslot calculation
  client/app/hearings/utils.js
  client/test/app/hearings/utils.test.js
Labels: Ready-to-Merge

#15944 Docket Switch | Repopulate Forms on Back
  client/app/queue/docketSwitch/docketSwitchSlice.js
  client/app/queue/docketSwitch/grant/DocketSwitchAddAdminTaskForm.jsx
  client/app/queue/docketSwitch/grant/DocketSwitchEditTasksContainer.jsx
  client/app/queue/docketSwitch/grant/DocketSwitchEditTasksForm.jsx
  client/app/queue/docketSwitch/grant/DocketSwitchEditTasksForm.stories.js
  client/app/queue/docketSwitch/grant/DocketSwitchReviewRequestContainer.jsx
  client/app/queue/docketSwitch/grant/DocketSwitchReviewRequestForm.jsx
  client/app/queue/docketSwitch/grant/DocketSwitchReviewRequestForm.stories.js
  client/test/app/queue/docketSwitch/DocketSwitchEditTasksForm.test.js
  client/test/app/queue/docketSwitch/DocketSwitchReviewRequestForm.test.js
  client/test/app/queue/docketSwitch/__snapshots__/DocketSwitchEditTasksForm.test.js.snap
  client/test/app/queue/docketSwitch/__snapshots__/DocketSwitchReviewRequestForm.test.js.snap
Labels: Ready-to-Merge

#15953 Case Distribution | Update legacy and direct review proportion levers based on the Board's request
  app/models/concerns/automatic_case_distribution.rb
  app/models/docket_coordinator.rb
  spec/models/distribution_spec.rb
  spec/models/docket_coordinator_spec.rb
Labels: Feature: auto-case-distribution, Ready-to-Merge, Team: Echo 🐬

#15946 CASEFLOW-977 Organization Assigned "CAVC Correspondence" Tasks should not be completable
  app/models/tasks/cavc_correspondence_mail_task.rb
  spec/models/tasks/cavc_correspondence_mail_task_spec.rb
Labels: Ready-to-Merge, Team: Echo 🐬

#15948 No "Mark complete" action for SendCavcRemandProcessedLetterTask that is assigned to an org
  app/models/tasks/send_cavc_remand_processed_letter_task.rb
Labels: Ready-to-Merge, Team: Echo 🐬

#15956 Persist unlisted POA or CorpDB POA to database
  app/models/decision_review_intake.rb
  app/models/other_claimant.rb
  app/schemas/intakes_schemas.rb
  spec/models/other_claimant_spec.rb
Labels: Ready-to-Merge

#15853 Check 'bgs_record_found?' before formatting the zip_code
  app/models/veteran.rb
  spec/models/veteran_spec.rb
Labels: Ready-to-Merge

#15947 DocketSwitch | Update Keyboard Focus Order in Admin Actions Form
  client/app/components/SearchableDropdown.jsx
  client/app/components/SearchableDropdown.stories.js
  client/app/queue/docketSwitch/grant/DocketSwitchAddAdminTaskForm.jsx
  client/test/app/queue/docketSwitch/DocketSwitchAddAdminTaskForm.test.js
  client/test/app/queue/docketSwitch/__snapshots__/DocketSwitchAddAdminTaskForm.test.js.snap
  client/test/app/queue/docketSwitch/__snapshots__/DocketSwitchEditTasksForm.test.js.snap
Labels: Ready-to-Merge, Team: Foxtrot 🦊

#15962 make treee prefer cached docket number for legacy appeals
  app/models/concerns/task_tree_render_module.rb
Labels: Ready-to-Merge, Type: Tech-Improvement

#15959 therubyracer needs a different libv8 on Catalina to install
  scripts/dev_env_setup_step2.sh
Labels: Ready-to-Merge

#15950 Move TimedHoldTask when assigning CAVC ResponseWindowTask to a user
  app/models/task.rb
  app/models/tasks/cavc_remand_processed_letter_response_window_task.rb
  spec/feature/queue/cavc_task_queue_spec.rb
  spec/models/tasks/cavc_remand_processed_letter_response_window_task_spec.rb
Labels: Ready-to-Merge, Team: Echo 🐬, Type: Bug

#15958 CASEFLOW-1060 Copy DocketSwitchGranted Task to New Appeal Stream
  app/models/docket_switch.rb
  spec/feature/queue/docket_switch_spec.rb
  spec/models/docket_switch_spec.rb
Labels: Ready-to-Merge, Team: Foxtrot 🦊

#15964 Implement Edit EP endpoint and call it from frontend
  app/controllers/claim_review_controller.rb
  app/controllers/concerns/validation_concern.rb
  app/schemas/claim_review_schemas.rb
  client/app/intake/pages/addIssues.jsx
  client/app/intakeEdit/actions/edit.js
  client/app/intakeEdit/constants.js
  config/routes.rb
  spec/feature/intake/edit_ep_claim_labels_spec.rb
Labels: Ready-to-Merge

#15966 "Per Curium" -> "Per curiam"
  client/constants/CAVC_JUDGE_FULL_NAMES.json
  client/test/app/queue/__snapshots__/AddCavcRemandView.test.js.snap
Labels: Ready-to-Merge, Team: Echo 🐬

#15960 Add receipt date validation to grant docket switch form
  client/COPY.json
  client/app/queue/docketSwitch/grant/DocketSwitchReviewRequestForm.jsx
  client/test/app/queue/docketSwitch/DocketSwitchReviewRequestForm.test.js
Labels: Team: Foxtrot 🦊, Type: Tech-Improvement

#15932 Mkerns/caseflow 859 nod form validation
  client/COPY.json
  client/app/queue/components/EditNodDateModal.jsx
  client/test/app/queue/components/EditNodDateModal.test.js
  client/test/app/queue/components/__snapshots__/EditNodDateModal.test.js.snap
  spec/feature/queue/case_details_spec.rb
Labels: Ready-to-Merge

#15968 Disable SqlTracker from creating extra files
  Gemfile.lock
  config/environments/test.rb
Labels: Ready-to-Merge

#15834 Scheduled hearing screen, fix sorting on Date/Room
  client/app/hearings/components/ListSchedule.jsx
Labels: Ready-to-Merge

#15972 Rewrite Alert karma test for jest
  client/test/app/components/Alert.test.js
  client/test/app/components/__snapshots__/Alert.test.js.snap
  client/test/karma/components/Alert-test.js
Labels: Type: Tech-Improvement

#15986 Correct empty snapshot for Edit Nod Date Modal
  client/test/app/queue/components/EditNodDateModal.test.js
  client/test/app/queue/components/__snapshots__/EditNodDateModal.test.js.snap
Labels: Team: X-ray 💀, Type: Bug

#15975 Fix flake with stochastic allocation of dockets
  spec/models/distribution_spec.rb
Labels: Ready-to-Merge

#15985 Fix Hearing Time related flaky tests
  spec/services/hearing_time_service_spec.rb
Labels: Ready-to-Merge

#15981 Jest Test for FilterOption
  client/app/components/FilterOption.stories.js
  client/test/app/components/FilterOption.test.js
  client/test/app/components/__snapshots__/FilterOption.test.js.snap
  client/test/karma/components/FilterOption-test.js
Labels: Ready-to-Merge

#15963 Create better hearings data for demo
  app/models/serializers/work_queue/legacy_appeal_serializer.rb
  db/seeds/hearings.rb
  db/seeds/tasks.rb
  db/seeds/users.rb
  lib/fakes/bgs_service.rb
  lib/fakes/bgs_service_poa.rb
  spec/factories/appeal.rb
  spec/seeds/hearings_spec.rb
Labels: Ready-to-Merge

#15989 Mkerns/karma rewrite document categories icons
  client/test/app/components/DocumentCategoryIcons.test.js
  client/test/karma/components/DocumentCategoryIcons-test.js
Labels: Ready-to-Merge, Type: Tech-Improvement

#15987 Jest Test for PaginationButton
  client/app/asyncableJobs/pages/JobsPage.jsx
  client/app/components/Pagination/EasyPagination.jsx
  client/app/components/Pagination/Pagination.jsx
  client/app/components/Pagination/PaginationButton.jsx
  client/app/components/PaginationButton.stories.js
  client/app/inbox/pages/InboxPage.jsx
  client/app/queue/QueueTable.jsx
  client/test/app/components/Pagination/PaginationButton.test.js
  client/test/app/components/Pagination/__snapshots__/PaginationButton.test.js.snap
  client/test/app/queue/QueueTable.test.js
  client/test/karma/components/PaginationButton-test.js
Labels: Ready-to-Merge

#15990 Save date of death to Postgres when BGS returns non-nil
  app/models/veteran.rb
  spec/models/veteran_spec.rb
Labels: Ready-to-Merge

#15991 Add Jest test for PdfUIPageNumInput
  client/app/reader/PdfUIPageNumInput.jsx
  client/app/reader/PdfUIPageNumInput.stories.js
  client/package.json
  client/test/app/reader/PdfUIPageNumInput.test.js
  client/test/app/reader/__snapshots__/PdfUIPageNumInput.test.js.snap
  client/test/karma/components/PdfUIPageNumInput-test.js
  client/yarn.lock
Labels: Type: Tech-Improvement

#15995 Add BGS last sync time column to veterans table
  db/migrate/20210311154002_add_bgs_sync_time_to_veterans.rb
  db/schema.rb
  docs/schema/caseflow.csv
Labels: Ready-to-Merge

#15992 LoadingDataDisplay component karma -> Jest
  client/COPY.json
  client/app/components/LoadingDataDisplay.jsx
  client/app/components/LoadingDataDisplay.stories.js
  client/test/app/components/LoadingDataDisplay.test.js
  client/test/app/components/__snapshots__/LoadingDataDisplay.test.js.snap
  client/test/karma/components/LoadingDataDisplay-test.js
Labels: Ready-to-Merge

#15998 Fix Pagination Button import in story
  client/app/components/PaginationButton.stories.js
Labels: Type: Bug

#15988 [Fix flaky] Editing Virtual Hearings from Hearing Details - cannot detect expected alert
  spec/feature/hearings/virtual_hearings/hearing_details_spec.rb
Labels: Eng: Flaky Test, Ready-to-Merge

#16000 [Fix flaky] Reschedule a virtual hearing scheduled in error - cannot find content "Schedule Veteran for a Hearing"
  spec/feature/hearings/hearing_scheduled_in_error_spec.rb
Labels: Eng: Flaky Test, Ready-to-Merge

#16004 Fixed daylight savings time bug for time slots
  spec/feature/hearings/schedule_veteran/build_hearsched_spec.rb
Labels: Ready-to-Merge

#16002 Fix Flake in Pushing Priority Appeals Tests
  spec/jobs/push_priority_appeals_to_judges_job_spec.rb
Labels: Ready-to-Merge

#16008 Fix median, and add test coverage
  app/services/concerns/reporter.rb
  spec/jobs/monthly_metrics_report_job_spec.rb
  spec/services/claim_review_async_stats_reporter_spec.rb
  spec/services/concerns/reporter_spec.rb
Labels: Ready-to-Merge

#16001 Paula/Overtime badge karma to jest conversion
  client/app/queue/components/OvertimeBadge.stories.js
  client/app/queue/components/OvertimeBadge.test.js
  client/app/queue/components/__snapshots__/OvertimeBadge.test.js.snap
  client/test/karma/components/OvertimeBadge-test.js
Labels: Ready-to-Merge, Type: Tech-Improvement

#16005 Rewrite Table component karma test
  client/test/app/components/Table.test.js
  client/test/app/components/__snapshots__/Table.test.js.snap
  client/test/karma/components/Table-test.js
Labels: Type: Tech-Improvement

#16013 Paula/Hearing Badge karma to jest conversion
  client/app/queue/components/HearingBadge.stories.js
  client/app/queue/components/HearingBadge.test.js
  client/app/queue/components/__snapshots__/HearingBadge.test.js.snap
  client/test/karma/components/HearingBadge-test.js
Labels: Ready-to-Merge, Type: Tech-Improvement

#16020 Storybook Story for Design Principles
  client/stories/0.5-DesignPrinciples.stories.mdx
Labels: Ready-to-Merge

#16017 [Fix flaky] Reschedule to a Virtual hearing without error - cannot detect expected alert
  spec/feature/hearings/hearing_scheduled_in_error_spec.rb
Labels: Ready-to-Merge

#16022 fix flakey test: Non-veteran claimants with non_veteran_claimants feature toggle allows selecting claimant not listed
  spec/feature/intake/non_veteran_claimants_spec.rb
Labels: Eng: Flaky Test, Ready-to-Merge, Type: Tech-Improvement

#16016 Remove tied to VLJ Requirement for Non-Legacy Hearing Cases
  app/models/vacols/case_docket.rb
  spec/models/vacols/case_docket_spec.rb
Labels: Ready-to-Merge, Team: Echo 🐬

#16021 Add Jest Test for NumberField
  client/app/components/InlineForm.stories.js
  client/app/components/NumberField.jsx
  client/app/components/NumberField.stories.js
  client/test/app/components/NumberField.test.js
  client/test/app/components/__snapshots__/NumberField.test.js.snap
  client/test/karma/components/NumberField-test.js
Labels: Ready-to-Merge, Type: Tech-Improvement

#16015 Fix docket switch task labels
  app/models/docket_switch.rb
  app/models/tasks/docket_switch/docket_switch_denied_task.rb
  app/models/tasks/docket_switch/docket_switch_granted_task.rb
  app/models/tasks/docket_switch/docket_switch_mail_task.rb
  app/models/tasks/docket_switch/docket_switch_ruling_task.rb
  app/workflows/docket_switch/task_handler.rb
  client/COPY.json
  spec/workflows/docket_switch_task_handler_spec.rb
Labels: Ready-to-Merge

#16027 rake script for changing legacy appeal VACOLS location in bulk
  lib/tasks/appeals.rake
  spec/lib/tasks/appeals_spec.rb
Labels: Eng: Backend Work Group, Ready-to-Merge, Team: Tango 💃

#16009 Jest Tests & Story for ColocatedTaskListView
  client/app/components/RenderFunctions.jsx
  client/app/queue/ColocatedTaskListView.jsx
  client/app/queue/ColocatedTaskListView.stories.js
  client/test/app/queue/ColocatedTaskListView.test.js
  client/test/app/queue/__snapshots__/ColocatedTaskListView.test.js.snap
  client/test/app/queue/__snapshots__/QueueTable.test.js.snap
  client/test/data/queue/taskLists/index.js
  client/test/karma/queue/ColocatedTaskListView-test.js
Labels: Ready-to-Merge, Type: Tech-Improvement

#16029 Switched from Karma to Jest Tests for MTVJudgeDisposition
  client/app/queue/mtv/MTVJudgeDisposition.jsx
  client/test/app/jestSetup.js
  client/test/app/queue/mtv/MTVJudgeDisposition.test.js
  client/test/app/queue/mtv/__snapshots__/MTVJudgeDisposition.test.js.snap
  client/test/data/tasks.js
  client/test/data/user.js
  client/test/karma/queue/mtv/MTVJudgeDisposition-test.js
Labels: Ready-to-Merge

#16030 Add Indices to "request_issues"
  db/migrate/20210322135622_add_indexes_to_request_issues.rb
  db/schema.rb
  docs/schema/caseflow.csv
Labels: Ready-to-Merge

#15974 Make external BGS call to perform EP edit
  .rubocop.yml
  app/models/end_product_update.rb
  app/services/external_api/bgs_service.rb
  lib/fakes/bgs_service.rb
  lib/generators/end_product.rb
  spec/models/end_product_update_spec.rb
Labels: Ready-to-Merge

#16028 Adds basic test for completed_hearing_on_previous_appeal?
  spec/models/legacy_appeal_spec.rb
Labels: Ready-to-Merge, Team: Echo 🐬

#16032 Add New Model for Granted Substitutions
  app/models/appeal.rb
  app/models/cavc_remand.rb
  app/models/granted_substitution.rb
  client/constants/AMA_STREAM_TYPES.json
  db/migrate/20210322174325_create_granted_substitutions.rb
  db/schema.rb
  docs/schema/caseflow.csv
  spec/models/granted_substitution_spec.rb
Labels: Ready-to-Merge, Team: Echo 🐬

#16036 Updated queue table to resolve 508 compliance issues
  client/app/components/TableFilter.jsx
  client/app/queue/QueueTable.jsx
  client/app/reader/DocumentsTable.jsx
  client/test/app/queue/__snapshots__/ColocatedTaskListView.test.js.snap
  client/test/app/queue/__snapshots__/QueueTable.test.js.snap
Labels: Ready-to-Merge

#16044 Updates Gemfile.lock to mimemagic 0.3.6
  Gemfile.lock
Labels: Eng: Backend Work Group, Ready-to-Merge

#16034 Add missing foreign keys to the users table (Phase 1)
  db/migrate/20210322215845_add_foreign_keys_to_users_table.rb
  db/migrate/20210322220713_validate_foreign_keys_to_users_table.rb
  db/schema.rb
  spec/models/task_spec.rb
Labels: Eng: Data Work Group, Ready-to-Merge

#15976 Tools to replicate sanitized real cases in dev/test environment
  .reek.yml
  lib/helpers/association_wrapper.rb
  lib/helpers/sanitation_transforms.rb
  lib/helpers/sanitized_json_configuration.rb
  lib/helpers/sanitized_json_difference.rb
  lib/helpers/sanitized_json_exporter.rb
  lib/helpers/sanitized_json_importer.rb
  spec/factories/cavc_remand.rb
  spec/lib/helpers/sanitized_json_exporter_spec.rb
Labels: Ready-to-Merge

#16046 Hide timeslots Before Scheduled Hearing Too
  client/app/hearings/utils.js
  client/test/app/hearings/utils.test.js
Labels: Ready-to-Merge

#16057 Add check for null tasks or nodDateUpdates
  client/app/queue/utils.js
Labels: Type: Bug

#16042 Bump Yup to 0.32.9
  client/package.json
  client/test/app/intake/components/addClaimants/AddClaimantPage.test.js
  client/test/app/queue/docketSwitch/DocketSwitchDenialForm.test.js
  client/yarn.lock
Labels: Ready-to-Merge

#16052 Improve stuck virtual hearings checker
  app/services/stuck_virtual_hearings_checker.rb
  spec/services/stuck_virtual_hearings_checker_spec.rb
Labels: Ready-to-Merge, Team: Tango 💃, Type: Tech-Improvement

#16058 Add Timezone Awareness to Timeslot Calculation + Display RO time first on TimeSlot Button
  client/app/hearings/components/scheduleHearing/TimeSlot.jsx
  client/app/hearings/utils.js
Labels: Ready-to-Merge

#16063 BUG: Receipt Date of Docket Switch on Docket Switch Confirmation Page Incorrect
  client/app/queue/docketSwitch/grant/DocketSwitchReviewConfirmContainer.jsx
  spec/feature/queue/docket_switch_spec.rb
Labels: Ready-to-Merge

#16067 Use loading button state after confirming docket switch
  client/app/queue/docketSwitch/grant/CheckoutButtons.jsx
  client/app/queue/docketSwitch/grant/DocketSwitchReviewConfirm.jsx
  client/app/queue/docketSwitch/grant/DocketSwitchReviewConfirmContainer.jsx
Labels: Ready-to-Merge

#16069 Task Handler not moving docket switchable tasks to new appeal stream
  app/workflows/docket_switch/task_handler.rb
  spec/feature/queue/docket_switch_spec.rb
  spec/workflows/docket_switch_task_handler_spec.rb
Labels: Ready-to-Merge

#16056 Only validate parent tasks on_create
  app/models/tasks/assign_hearing_disposition_task.rb
  app/models/tasks/cavc_extension_request_task.rb
  app/models/tasks/special_case_movement_task.rb
  app/models/tasks/timed_hold_task.rb
  app/models/tasks/transcription_task.rb
Labels: Ready-to-Merge, Team: Echo 🐬

#16066 Fix bug with EvidenceSubmissionWindowTask being created every few hours
  app/models/tasks/hearing_task.rb
  spec/factories/hearing.rb
  spec/models/tasks/evidence_submission_window_task_spec.rb
Labels: Ready-to-Merge
