Repository department-of-veterans-affairs/caseflow, pull requests merged in 2022-12, with the labels that each got.

#17752 APPEALS-9522
  app/jobs/fetch_all_active_ama_appeals_job.rb
  app/jobs/fetch_all_active_legacy_appeals_job.rb
  spec/jobs/fetch_all_active_ama_appeals_job_spec.rb
  spec/jobs/fetch_all_active_legacy_appeals_job_spec.rb
Labels: VA Notify, Team: Andromeda 🚀

#17757 akonhilas/APPEALS-9523
  app/jobs/fetch_all_active_ama_appeals_job.rb
  app/jobs/fetch_all_active_legacy_appeals_job.rb
  spec/jobs/fetch_all_active_ama_appeals_job_spec.rb
  spec/jobs/fetch_all_active_legacy_appeals_job_spec.rb
Labels: VA Notify

#17770 msteele/APPEALS-10453
  app/jobs/fetch_all_active_ama_appeals_job.rb
  app/jobs/fetch_all_active_legacy_appeals_job.rb
  spec/jobs/fetch_all_active_ama_appeals_job_spec.rb
  spec/jobs/fetch_all_active_legacy_appeals_job_spec.rb
Labels: VA Notify, Team: Andromeda 🚀

#17790 TYLERB/APPEALS-12440: VHA Claim Review Establishment Feature Toggle creation
  app/controllers/intakes_controller.rb
  client/app/intake/components/BenefitType.jsx
  client/app/intake/components/BenefitType.stories.js
  client/app/intake/pages/formGenerator.jsx
  client/app/intake/pages/formGenerator.stories.js
  client/app/intake/reducers/featureToggles.js
  client/test/app/intake/components/BenefitType.test.js
  spec/feature/intake/review_page_spec.rb
Labels: Product: caseflow-intake, Team: Saturn 🪐, Feature: VHA CR Establishment Requirement

#17810 Release/APPEALS-9391 Removal of CAVC Check Box from Special Issues Selections
  app/controllers/special_issues_controller.rb
  client/app/constants/SpecialIssues.js
  client/app/queue/SelectSpecialIssuesView.jsx
  spec/feature/queue/attorney_checkout_flow_spec.rb
  spec/feature/queue/judge_checkout_flow_spec.rb
Labels: Team: DarkMatter

#17776 akonhilas/APPEALS-10454
  app/jobs/fetch_all_active_ama_appeals_job.rb
  app/jobs/fetch_all_active_legacy_appeals_job.rb
  spec/jobs/fetch_all_active_ama_appeals_job_spec.rb
  spec/jobs/fetch_all_active_legacy_appeals_job_spec.rb
Labels: VA Notify

#17814 aaron/appeals-12007-v2
  app/jobs/quarterly_notifications_job.rb
  app/jobs/send_notification_job.rb
  app/models/appeal.rb
  app/models/prepend/va_notify/appeal_cancelled.rb
  app/models/prepend/va_notify/appellant_notification.rb
  app/models/vanotify/va_notify_send_message_template.rb
  app/services/external_api/va_notify_service.rb
  client/app/queue/CaseDetailsView.jsx
  client/constants/QUARTERLY_STATUSES.json
  lib/fakes/va_notify_service.rb
  spec/jobs/send_notification_job_spec.rb
  spec/services/external_api/va_notify_service_spec.rb
Labels: VA Notify, Team: Andromeda 🚀

#17835 aaron/APPEALS-12611
  app/jobs/send_notification_job.rb
  app/models/prepend/va_notify/appeal_cancelled.rb
  app/models/prepend/va_notify/appeal_docketed.rb
  app/models/prepend/va_notify/hearing_postponed.rb
  app/models/prepend/va_notify/hearing_scheduled.rb
  app/models/prepend/va_notify/hearing_scheduled_in_error.rb
  app/models/prepend/va_notify/hearing_withdrawn.rb
  app/models/prepend/va_notify/ihp_task_cancelled.rb
  app/models/prepend/va_notify/ihp_task_complete.rb
  app/models/prepend/va_notify/ihp_task_pending.rb
  app/models/prepend/va_notify/privacy_act_cancelled.rb
  app/models/prepend/va_notify/privacy_act_complete.rb
  db/migrate/20221215192716_add_sms_notification_content_to_notifications.rb
  db/migrate/20221215202259_add_email_notification_content_to_notifications.rb
  db/schema.rb
  spec/jobs/send_notification_job_spec.rb
Labels: VA Notify, Team: Andromeda 🚀

#17846 aaron/APPEALS-12611-v2
  app/jobs/fetch_all_active_ama_appeals_job.rb
  app/jobs/fetch_all_active_legacy_appeals_job.rb
  app/models/serializers/work_queue/notification_serializer.rb
  client/app/queue/CaseTitle.jsx
  client/app/queue/components/NotificationTable.jsx
Labels: VA Notify, Team: Andromeda 🚀

#17883 aaron/APPEALS-12683
  app/jobs/fetch_all_active_ama_appeals_job.rb
  app/jobs/fetch_all_active_legacy_appeals_job.rb
  app/jobs/quarterly_notifications_job.rb
  config/environments/development.rb
  config/environments/test.rb
  spec/jobs/fetch_all_active_ama_appeals_job_spec.rb
  spec/jobs/fetch_all_active_legacy_appeals_job_spec.rb
Labels: VA Notify, Team: Andromeda 🚀

#17891 aaron/APPEALS-12683-v2
  app/jobs/quarterly_notifications_job.rb
  app/jobs/send_notification_job.rb
Labels: VA Notify, Team: Andromeda 🚀

#17907 aaron/APPEALS-12943
  config/initializers/scheduled_jobs.rb
  db/migrate/20221215192716_add_sms_notification_content_to_notifications.rb
  db/migrate/20221215202259_add_email_notification_content_to_notifications.rb
Labels: VA Notify, Team: Andromeda 🚀

#17910 hotfix/APPEALS-12998 Removed Colored text from rails logger to fix issue whe…
  app/models/prepend/va_notify/privacy_act_pending.rb
Labels: VA Notify, Team: Andromeda 🚀

#17914 Hotfix: Add Safe-Navigation Operators to Claimant Calls
  app/models/decision_document.rb
  app/models/decision_review_intake.rb
  app/models/serializers/work_queue/appeal_serializer.rb
Labels: Team: Saturn 🪐, Feature: Unrecognized Claimant Intake - HLRs & SCs
