Repository department-of-veterans-affairs/caseflow, pull requests merged in 2022-01, with the labels that each got.

#17073 DataDogService: set default start_time value in case it is nil
  app/jobs/push_priority_appeals_to_judges_job.rb
  app/services/data_dog_service.rb
  spec/feature/queue/case_details_spec.rb
Labels: Ready-to-Merge

#17074 Fix test case_details_spec's later_nod_date to account for TimeCop
  spec/feature/queue/case_details_spec.rb
Labels: Ready-to-Merge

#17077 check_task_tree: quit if legacy appeal
  lib/helpers/check_task_tree.rb
  spec/lib/helpers/check_task_tree_spec.rb
Labels: Ready-to-Merge

#17066 Confirm appeal can't have multiple open tasks where "assigned_to" is a group
  app/models/tasks/assign_hearing_disposition_task.rb
  client/COPY.json
  spec/feature/hearings/change_hearing_disposition_spec.rb
  spec/models/tasks/assign_hearing_disposition_task_spec.rb
  spec/models/tasks/change_hearing_disposition_task_spec.rb
  spec/models/tasks/quality_review_task_spec.rb
Labels: Ready-to-Merge

#17006 Added columns
  app/models/organizations/vha_program_office.rb
  app/models/queue_tabs/vha_program_office_on_hold_tasks_tab.rb
  app/models/queue_tabs/vha_program_office_ready_for_review_tasks_tab.rb
  app/models/serializers/work_queue/task_column_serializer.rb
  client/COPY.json
  client/app/queue/QueueTableBuilder.jsx
  client/app/queue/components/TaskTableColumns.jsx
  client/app/util/DateUtil.js
  client/constants/QUEUE_CONFIG.json
  spec/models/queue_tabs/vha_program_office_assigned_tasks_tab_spec.rb
  spec/models/queue_tabs/vha_program_office_completed_tasks_tab_spec.rb
  spec/models/queue_tabs/vha_program_office_in_progress_tasks_tab_spec.rb
  spec/models/queue_tabs/vha_program_office_on_hold_tasks_tab_spec.rb
  spec/models/queue_tabs/vha_program_office_ready_for_review_tasks_tab_spec.rb
Labels: Ready-to-Merge

#17082 Bumping security warnings two more weeks
  .security.yml
Labels: Ready-to-Merge

#17081 Remove debt categories
  app/controllers/api/docs/v3/decision_reviews.yaml
  client/constants/ISSUE_CATEGORIES.json
Labels: Ready-to-Merge

#17079 Add stuck jobs reporter
  lib/helpers/stuck_jobs_reporter.rb
Labels: Ready-to-Merge

#17086 ETL: remove non-null constraint on appeals.docket_type
  db/etl/migrate/20220107125705_remove_non_null_constraint_on_appeal_docket_type.rb
  db/etl/schema.rb
  spec/services/etl/appeal_syncer_spec.rb
Labels: Ready-to-Merge

#17089 Fix Issue Preventing Selection of "All cases" for "Request More Cases Distribution"
  client/app/queue/teamManagement/OrgRow.jsx
  client/test/app/queue/teamManagement/OrgRow.test.js
Labels: Ready-to-Merge

#17091 ETL: remove non-null constraint on appeals.receipt_date
  db/etl/migrate/20220110143457_remove_non_null_constraint_on_appeal_receipt_date.rb
  db/etl/schema.rb
  spec/services/etl/appeal_syncer_spec.rb
Labels: Ready-to-Merge

#17088 make_docs GH Action: update to BAH person
  .github/workflows/make-docs.yml
Labels: Ready-to-Merge

#17084 claim_establishments table: add task_id index
  db/migrate/20220106201637_add_task_id_index_to_claim_establishments.rb
  db/schema.rb
Labels: Ready-to-Merge

#17085 distributed_cases table: add index on distribution_id
  db/migrate/20220106205609_add_distribution_id_index_to_distributed_cases.rb
  db/schema.rb
Labels: Ready-to-Merge

#17056 API-11905 Lighthouse supplemental claims contestable issues
  app/controllers/api/v3/decision_reviews/supplemental_claims/contestable_issues_controller.rb
  config/routes.rb
  spec/requests/api/v3/decision_reviews/supplemental_claims/contestable_issues_controller_spec.rb
  spec/support/shared_examples/requests/api/v3/decision_reviews/shared_examples_contestable_issues.rb
Labels: Integration: Lighthouse

#17072 Reopen ESW task during same-appeal substitution
  app/models/appeal.rb
  app/models/serializers/work_queue/appeal_serializer.rb
  app/workflows/concerns/tasks_factory_concern.rb
  app/workflows/initial_tasks_factory.rb
  app/workflows/same_appeal_substitution_tasks_factory.rb
  client/constants/TASKS_FOR_APPELLANT_SUBSTITUTION.json
  spec/workflows/same_appeal_substitution_tasks_factory_spec.rb
Labels: Ready-to-Merge

#17064 Create MPI Search page
  Gemfile
  Gemfile.lock
  app/controllers/mpi_controller.rb
  app/services/external_api/mpi_service.rb
  app/views/mpi/index.html.erb
  client/COPY.json
  client/app/components/AddressForm.jsx
  client/app/index.js
  client/app/intake/addClaimant/ClaimantForm.jsx
  client/app/intake/addPOA/AddPoaPage.jsx
  client/app/mpi/MPISearch.jsx
  client/test/app/intake/components/addClaimants/ClaimantForm.test.js
  client/test/app/intake/components/addClaimants/__snapshots__/ClaimantForm.test.js.snap
  client/test/app/intake/components/addClaimants/testUtils.js
  client/test/app/queue/editAppellantInformation/EditAppellantInformation.test.js
  client/test/app/queue/editAppellantInformation/__snapshots__/EditAppellantInformation.test.js.snap
  config/initializers/mpi.rb
  config/routes.rb
  lib/fakes/mpi_service.rb
Labels: Ready-to-Merge

#17097 Display Attorney Notes for Judge Decision Review for Legacy Appeals
  app/models/serializers/work_queue/legacy_task_serializer.rb
  client/app/queue/components/TaskRows.jsx
  client/app/queue/utils.js
  db/seeds/tasks.rb
  spec/controllers/tasks_controller_spec.rb
Labels: Ready-to-Merge

#17071 CASEFLOW-2669 | Affinity for legacy appeals with CAVC remands
  app/models/dockets/legacy_docket.rb
  app/models/vacols/case_docket.rb
  spec/models/vacols/case_docket_spec.rb
Labels: Ready-to-Merge

#17058 CAMO users can indicate that an appeal is recommended for cancellation
  app/repositories/task_action_repository.rb
  app/views/queue/index.html.erb
  client/COPY.json
  client/app/queue/components/CompleteTaskModal.jsx
  spec/factories/appeal.rb
  spec/feature/queue/camo_cancellation_spec.rb
  spec/feature/queue/pre_docket_spec.rb
Labels: Ready-to-Merge, Team Victor

#17105 Update puma and nokogiri
  .security.yml
  Gemfile.lock
Labels: Ready-to-Merge

#17083 Redo "Replace Vocational Rehab benefit type (#17050)"
  client/app/constants/SpecialIssues.js
  client/app/intake/components/BenefitType.jsx
  client/constants/BENEFIT_TYPES.json
  db/migrate/20220112170007_update_voc_rehab_name.rb
  spec/feature/intake/appeal_spec.rb
  spec/feature/intake/intake_spec.rb
Labels: Ready-to-Merge

#17110 Revert "CASEFLOW-2669 | Affinity for legacy appeals with CAVC remands (#17071)
  app/models/dockets/legacy_docket.rb
  app/models/vacols/case_docket.rb
  spec/models/vacols/case_docket_spec.rb
Labels: Ready-to-Merge
