Repository department-of-veterans-affairs/caseflow, pull requests merged in 2022-11, with the labels that each got.

#17637 Isaiah/appeals 9796 add total days worked
  client/COPY.json
  client/app/queue/caseEvaluation/EvaluateDecisionView.jsx
Labels: DAS Checkbox, Team: DarkMatter

#17654 Ki/appeals 9797
  client/COPY.json
  client/app/queue/AttorneyTaskTimeline.jsx
  client/app/queue/caseEvaluation/EvaluateDecisionView.jsx
  client/app/queue/components/AttorneyTaskRows.jsx
Labels: DAS Checkbox, Team: DarkMatter

#17656 eric/APPEALS-8490
  app/models/serializers/work_queue/appeal_serializer.rb
  app/models/serializers/work_queue/legacy_appeal_serializer.rb
  client/COPY.json
  client/app/queue/CaseDetailsView.jsx
  client/app/queue/CaseTitleDetails.jsx
  client/app/queue/utils.js
  client/test/app/containers/CaseWorker/__snapshots__/CaseWorkerIndex.test.js.snap
  client/test/app/queue/CaseDetailsView.test.js
  client/test/app/queue/__snapshots__/NotificationsView.test.js.snap
Labels: VA Notify

#17663 aaron/APPEALS-10522-v2
  app/controllers/appeals_controller.rb
  db/seeds.rb
  db/seeds/notifications.rb
  spec/controllers/appeals_controller_spec.rb
Labels: VA Notify, Team: Andromeda 🚀

#17620 msteele/APPEALS-10311
  Makefile.example
  db/scripts/audit/add_row_to_appeal_states_audit_table_function.rb
  db/scripts/audit/add_row_to_appeal_states_audit_table_function.sql
  db/scripts/audit/create_appeal_states_audit.rb
  db/scripts/audit/create_appeal_states_audit.sql
  db/scripts/audit/create_appeal_states_audit_trigger.rb
  db/scripts/audit/create_appeal_states_audit_trigger.sql
  db/scripts/audit/create_caseflow_audit_schema.rb
  db/scripts/audit/create_caseflow_audit_schema.sql
  db/scripts/audit/remove_caseflow_audit_schema.rb
  db/scripts/audit/remove_caseflow_audit_schema.sql
Labels: VA Notify

#17592 TYLERB/APPEALS-9138: Add Healthcare Provider option in dropdown in HLR flow
  app/models/concerns/has_unrecognized_party_detail.rb
  app/models/decision_review_intake.rb
  app/models/other_claimant.rb
  app/schemas/intakes_schemas.rb
  client/COPY.json
  client/app/components/AddressForm.jsx
  client/app/intake/actions/decisionReview.js
  client/app/intake/addClaimant/AddClaimantPage.jsx
  client/app/intake/addClaimant/AddClaimantPage.stories.js
  client/app/intake/addClaimant/AddressBlock.jsx
  client/app/intake/addClaimant/ClaimantForm.jsx
  client/app/intake/addClaimant/ClaimantForm.stories.js
  client/app/intake/addClaimant/utils.js
  client/app/intake/addPOA/AddPoaPage.jsx
  client/app/intake/components/CancelIntakeModal.jsx
  client/app/intake/constants.js
  client/app/intake/pages/ReviewAppealView.jsx
  client/test/app/intake/components/addClaimants/ClaimantForm.test.js
  client/test/app/intake/components/addClaimants/__snapshots__/AddClaimantConfirmationModal.test.js.snap
  client/test/app/intake/components/addClaimants/__snapshots__/ClaimantForm.test.js.snap
  client/test/app/intake/components/addClaimants/testUtils.js
  client/test/app/queue/editAppellantInformation/__snapshots__/EditAppellantInformation.test.js.snap
  client/test/app/queue/editPOAInformation/__snapshots__/EditPOAInformation.test.js.snap
  db/migrate/20221025172851_add_ssn_to_unrecognized_party_detail.rb
  db/schema.rb
  spec/feature/intake/hlr_sc_non_veteran_claimants_spec.rb
  spec/support/intake_helpers.rb
Labels: Product: caseflow-intake, Team: Saturn 🪐, Feature: Unrecognized Claimant Intake - HLRs & SCs

#17687 test data added for timeline date calculation changes
  db/seeds.rb
  db/seeds/static_test_data.rb
Labels: DAS Checkbox

#17688 APPEALS-11202 - Preliminary Timeline Selector
  client/app/queue/AttorneyTaskTimeline.jsx
  client/app/queue/caseEvaluation/EvaluateDecisionView.jsx
  client/app/queue/components/AttorneyTaskRows.jsx
  client/app/queue/selectors.js
  client/app/queue/utils.js
  client/app/styles/app.scss
  client/app/styles/queue/_evaluate_decision.scss
Labels: DAS Checkbox

#17691 Hotfix/appeals 11203 days worked correction
  client/app/queue/AttorneyDaysWorked.jsx
  client/app/queue/caseEvaluation/EvaluateDecisionView.jsx
Labels: DAS Checkbox

#17695 jshields/APPEALS-11293
  client/app/queue/CaseTitle.jsx
Labels: Product: caseflow-queue, Type: Bug

#17636 janet/APPEALS-10312 Update the Notification Appellant Prepend logic to save state changes
  app/models/concerns/created_and_updated_by_user_concern.rb
  app/models/prepend/va_notify/appeal_decision_mailed.rb
  app/models/prepend/va_notify/appeal_docketed.rb
  app/models/prepend/va_notify/appellant_notification.rb
  app/models/prepend/va_notify/docket_hearing_postponed.rb
  app/models/prepend/va_notify/docket_hearing_withdrawn.rb
  app/models/prepend/va_notify/hearing_postponed.rb
  app/models/prepend/va_notify/hearing_scheduled.rb
  app/models/prepend/va_notify/hearing_withdrawn.rb
  app/models/prepend/va_notify/ihp_task_complete.rb
  app/models/prepend/va_notify/ihp_task_pending.rb
  app/models/prepend/va_notify/privacy_act_complete.rb
  app/models/prepend/va_notify/privacy_act_pending.rb
  app/models/user.rb
  spec/factories/appeal.rb
  spec/factories/appeal_state.rb
  spec/lib/helpers/sanitized_json_exporter_spec.rb
  spec/models/appellant_notification_spec.rb
  spec/seeds/users_spec.rb
  spec/services/etl/builder_spec.rb
Labels: VA Notify, Team: Andromeda 🚀

#17571 APPEALS-8386 Calculation Functionality for Timely/Untimely Checkbox on DAS
  client/COPY.json
  client/app/queue/AttorneyDaysWorked.jsx
  client/app/queue/AttorneyTaskTimeline.jsx
  client/app/queue/caseEvaluation/EvaluateDecisionView.jsx
  client/app/queue/components/AttorneyTaskRows.jsx
  client/app/queue/selectors.js
  client/app/queue/utils.js
  client/app/styles/_table.scss
  client/app/styles/app.scss
  client/app/styles/queue/_evaluate_decision.scss
  client/test/app/queue/QueueLoadingScreen-test.js
  db/seeds.rb
  db/seeds/static_test_data.rb
  spec/seeds/static_test_data_spec.rb
Labels: DAS Checkbox, Team: DarkMatter

#17719 APPEALS-10645: added "pact_act" param to controller
  app/controllers/special_issues_controller.rb
Labels: Team: DarkMatter

#17721 Lianna/APPEALS -10818: System Check for VHA Business Line Membership
  app/controllers/intakes_controller.rb
  app/models/user.rb
  client/constants/BENEFIT_TYPES.json
  spec/models/user_spec.rb
Labels: Product: caseflow-intake, Team: Saturn 🪐, Feature: VHA CR Establishment Requirement

#17702 janet/APPEALS-10314 Update the Notification Appellant logic to track Privacy Act task cancellations
  app/models/prepend/va_notify/appellant_notification.rb
  app/models/prepend/va_notify/privacy_act_cancelled.rb
  app/models/task.rb
  spec/models/appellant_notification_spec.rb
Labels: VA Notify, Team: Andromeda 🚀

#17693 akonhilas/APPEALS-10315
  app/models/prepend/va_notify/appeal_cancelled.rb
  app/models/prepend/va_notify/appellant_notification.rb
  app/models/task.rb
  spec/models/appellant_notification_spec.rb
Labels: VA Notify

#17728 Feature/appeals 8386 part 3
  app/views/queue/index.html.erb
  client/app/queue/AttorneyDaysWorked.jsx
  client/app/queue/QueueApp.jsx
  client/app/queue/caseEvaluation/AttorneyDaysWorked.jsx
  client/app/queue/caseEvaluation/AttorneyTaskRows.jsx
  client/app/queue/caseEvaluation/AttorneyTaskTimeline.jsx
  client/app/queue/caseEvaluation/EvaluateDecisionView.jsx
  client/app/queue/selectors.js
  client/package.json
  client/yarn.lock
  db/seeds/static_test_data.rb
Labels: DAS Checkbox, Team: DarkMatter

#17734 APPEALS-8386 Calculation Functionality for Timely/Untimely Checkbox on DAS
  app/views/queue/index.html.erb
  client/COPY.json
  client/app/2.0/store/reader/selectors.js
  client/app/queue/QueueApp.jsx
  client/app/queue/caseEvaluation/AttorneyDaysWorked.jsx
  client/app/queue/caseEvaluation/AttorneyTaskRows.jsx
  client/app/queue/caseEvaluation/AttorneyTaskTimeline.jsx
  client/app/queue/caseEvaluation/EvaluateDecisionView.jsx
  client/app/queue/selectors.js
  client/app/queue/utils.js
  client/app/styles/app.scss
  client/app/styles/queue/_evaluate_decision.scss
  client/package.json
  client/test/app/queue/QueueLoadingScreen-test.js
  client/yarn.lock
  db/seeds.rb
  db/seeds/static_test_data.rb
  spec/seeds/static_test_data_spec.rb
Labels: DAS Checkbox

#17739 APPEALS-10647 - Commit Cleanup CSS Fix
  client/app/queue/SelectSpecialIssuesView.jsx
Labels: Team: DarkMatter

#17644 TYLERB/APPEALS-9185: Add an unrecognized claimant's POA (HLR)
  client/app/intake/addClaimant/AddClaimantPage.jsx
  client/app/intake/addPOA/AddPoaPage.jsx
  client/app/intake/addPOA/AddPoaPage.stories.js
  client/app/intake/addPOA/utils.js
  client/app/intake/components/CancelIntakeModal.jsx
  client/app/intake/pages/addIssues.jsx
  client/test/app/intake/components/AddPoaPage.test.js
  client/test/app/intake/components/__snapshots__/AddPoaPage.test.js.snap
  spec/feature/intake/appeal_spec.rb
  spec/feature/intake/higher_level_review_spec.rb
  spec/feature/intake/hlr_sc_non_veteran_claimants_spec.rb
  spec/feature/intake/intake_spec.rb
  spec/feature/intake/supplemental_claim_spec.rb
Labels: Product: caseflow-intake, Team: Saturn 🪐, Feature: Unrecognized Claimant Intake - HLRs & SCs

#17684 aaron/APPEALS-10313
  app/models/prepend/va_notify/appeal_docketed.rb
  app/models/prepend/va_notify/appellant_notification.rb
  app/models/prepend/va_notify/ihp_task_cancelled.rb
  app/models/prepend/va_notify/ihp_task_complete.rb
  app/models/prepend/va_notify/ihp_task_pending.rb
  app/models/task.rb
  db/seeds.rb
  spec/jobs/update_appellant_representation_job_spec.rb
  spec/models/appellant_notification_spec.rb
  spec/workflows/bulk_task_reassignment_spec.rb
Labels: VA Notify, Team: Andromeda 🚀

#17715 APPEALS-8930 Add a "PACT Act" checkbox option to the "Select Special Issue" screen within Caseflow
  app/controllers/special_issues_controller.rb
  client/app/constants/SpecialIssues.js
  client/app/queue/SelectSpecialIssuesView.jsx
  db/migrate/20221115202338_add_pact_act_to_special_issue_lists.rb
  db/schema.rb
Labels: Team: DarkMatter

#17756 aaron/APPEALS-8945
  app/jobs/fetch_all_active_ama_appeals_job.rb
  app/jobs/fetch_all_active_legacy_appeals_job.rb
  config/environments/development.rb
  config/environments/test.rb
  config/initializers/scheduled_jobs.rb
  spec/factories/appeal.rb
  spec/factories/legacy_appeal.rb
  spec/jobs/fetch_all_active_ama_appeals_job_spec.rb
  spec/jobs/fetch_all_active_legacy_appeals_job_spec.rb
Labels: VA Notify, Team: Andromeda 🚀

#17758 aaron/APPEALS-9524
  app/jobs/fetch_all_active_ama_appeals_job.rb
  app/jobs/fetch_all_active_legacy_appeals_job.rb
  spec/factories/appeal.rb
  spec/jobs/fetch_all_active_ama_appeals_job_spec.rb
  spec/jobs/fetch_all_active_legacy_appeals_job_spec.rb
Labels: VA Notify, Team: Andromeda 🚀

#17746 TYLERB/APPEALS-11755: Remove last name warning for unrecognized claimants in HLR/SC for listed attorneys
  client/app/intake/addClaimant/AddClaimantConfirmationModal.jsx
  client/app/intake/addClaimant/AddClaimantPage.jsx
  client/app/intake/addClaimant/ClaimantForm.jsx
  client/test/app/containers/CaseWorker/__snapshots__/CaseWorkerIndex.test.js.snap
  client/test/app/intake/components/addClaimants/AddClaimantConfirmationModal.test.js
  client/test/app/intake/components/addClaimants/__snapshots__/AddClaimantConfirmationModal.test.js.snap
  client/test/app/intake/components/addClaimants/__snapshots__/ClaimantForm.test.js.snap
  client/test/app/queue/editAppellantInformation/__snapshots__/EditAppellantInformation.test.js.snap
  client/test/data/intake/claimants.js
Labels: Product: caseflow-intake, Team: Saturn 🪐, Feature: Unrecognized Claimant Intake - HLRs & SCs

#17733 TYLERB/APPEALS-10820: HLR SC Permissions Change Banner Creation
  app/controllers/intakes_controller.rb
  client/COPY.json
  client/app/intake/IntakeFrame.jsx
  client/app/intake/components/AddIssuesModal.stories.js
  client/app/intake/components/BenefitType.stories.js
  client/app/intake/components/CancelIntakeModal.stories.js
  client/app/intake/components/IntakeProgressBar.stories.js
  client/app/intake/components/NonratingRequestIssueModal.stories.js
  client/app/intake/components/SelectClaimant.stories.js
  client/app/intake/index.js
  client/app/intake/pages/formGenerator.jsx
  client/app/intake/pages/formGenerator.stories.js
  client/app/intake/reducers/intake.js
  client/app/intake/reducers/userInformation.js
  client/test/app/containers/CaseWorker/__snapshots__/CaseWorkerIndex.test.js.snap
  spec/feature/intake/review_page_spec.rb
  spec/models/user_spec.rb
  spec/support/intake_helpers.rb
Labels: Product: caseflow-intake, Team: Saturn 🪐, Feature: VHA CR Establishment Requirement
