Repository department-of-veterans-affairs/caseflow, pull requests merged in 2022-03, with the labels that each got.

#17119 CASEFLOW-2913 Create a v2 IDT API endpoint for Outcode, and implement the new Dispatch Email Job in this endpoint
  app/controllers/idt/api/v2/appeals_controller.rb
  app/jobs/dispatch_email_job.rb
  app/mappers/address_mapper.rb
  app/models/bgs_power_of_attorney.rb
  app/services/bgs_address_service.rb
  client/constants/DATADOG_METRICS.json
  config/routes.rb
  lib/fakes/bgs_service.rb
  spec/controllers/appeals_controller_spec.rb
  spec/controllers/idt/api/v2/appeals_controller_spec.rb
  spec/feature/intake/add_issues_spec.rb
  spec/mailers/dispatch_mailer_spec.rb
  spec/mappers/address_mapper_spec.rb
Labels: stacked

#17118 CASEFLOW-2910 - Create a DispatchMailer class that inherits ActionMailer, with a methods to generate email from the template and send via GovDelivery
  app/controllers/idt/api/v2/appeals_controller.rb
  app/jobs/dispatch_email_job.rb
  app/mailers/dispatch_mailer.rb
  app/mappers/address_mapper.rb
  app/models/bgs_power_of_attorney.rb
  app/services/bgs_address_service.rb
  client/constants/DATADOG_METRICS.json
  config/routes.rb
  lib/fakes/bgs_service.rb
  spec/controllers/appeals_controller_spec.rb
  spec/controllers/idt/api/v2/appeals_controller_spec.rb
  spec/feature/intake/add_issues_spec.rb
  spec/jobs/dispatch_email_job_spec.rb
  spec/mailers/dispatch_mailer_spec.rb
  spec/mappers/address_mapper_spec.rb
Labels: stacked

#17133 db migration, added homelessness to appeals table
  .security.yml
  db/migrate/20220307213343_add_homelessness_to_appeals.rb
  db/schema.rb
Labels: Ready-to-Merge

#17146 CASEFLOW-3388: Create Hearing Type Field on Intake Add/Remove Issues Screen
  app/serializers/intake/appeal_intake_serializer.rb
  client/app/intake/reducers/appeal.js
  client/app/intake/util/issues.js
  client/test/app/intake/util/issues.test.js
  client/test/data/intake/intakes.js
  spec/feature/intake/add_issues_spec.rb
  spec/support/intake_helpers.rb
Labels: Product: caseflow-intake, User: BVA Intake

#17151 Caseflow 3383 add homelessness to intake review screen
  app/models/appeal.rb
  app/models/appeal_intake.rb
  app/schemas/intakes_schemas.rb
  app/serializers/intake/appeal_intake_serializer.rb
  client/COPY.json
  client/app/intake/actions/appeal.js
  client/app/intake/components/Homelessness.jsx
  client/app/intake/constants.js
  client/app/intake/pages/appeal/review.jsx
  client/app/intake/pages/formGenerator.jsx
  client/app/intake/reducers/appeal.js
  client/app/intake/reducers/common.js
  client/test/app/intake/pages/review.test.js
  spec/feature/intake/intake_spec.rb
  spec/models/appeal_intake_spec.rb
Labels: Product: caseflow-intake, User: BVA Intake
