Repository department-of-veterans-affairs/caseflow, pull requests merged in 2023-06, with the labels that each got.

#18676 APPEALS-23363: Case Timeline Entry Details: Editing Designation for AMA appeals during Decision Workflow
  app/controllers/case_reviews_controller.rb
  client/app/queue/components/TaskRows.jsx
Labels: MST/PACT

#18684 Ryan appeals 23327
  app/controllers/appeals_controller.rb
  app/controllers/case_reviews_controller.rb
  app/models/request_issues_update.rb
  app/models/tasks/issues_update_task.rb
  client/app/queue/components/TaskRows.jsx
  spec/controllers/appeals_controller_spec.rb
Labels: MST/PACT

#18688 Justin/APPEALS-23364
  app/controllers/issues_controller.rb
  app/models/serializers/work_queue/task_serializer.rb
Labels: MST/PACT

#18564 TYLERB/APPEALS-16535: Add Issue Type column to VHA CAMO user's Bulk Assign screen
  client/app/components/TableFilter.jsx
  client/app/queue/QueueTable.jsx
  client/app/queue/UnassignedCasesPage.jsx
  client/app/queue/UnassignedCasesPage.stories.js
  client/app/queue/components/TaskTableColumns.jsx
  client/constants/QUEUE_CONFIG.json
  client/test/data/camoAmaAppealsData.js
  client/test/data/camoAmaTasksData.js
  client/test/data/camoQueueConfigData.js
  spec/feature/queue/appeal_notifications_page_spec.rb
  spec/feature/queue/vha_camo_assignment_spec.rb
  spec/feature/queue/vha_camo_queue_spec.rb
  spec/models/organizations/vha_caregiver_support_spec.rb
  spec/models/organizations/vha_program_office_spec.rb
  spec/models/queue_tabs/vha_camo_assigned_tasks_tab_spec.rb
  spec/models/queue_tabs/vha_program_office_assigned_tasks_tab_spec.rb
  spec/models/queue_tabs/vha_program_office_completed_tasks_tab_spec.rb
  spec/models/queue_tabs/vha_program_office_in_progress_tasks_tab_spec.rb
  spec/models/queue_tabs/vha_program_office_on_hold_tasks_tab_spec.rb
  spec/models/queue_tabs/vha_program_office_ready_for_review_tasks_tab_spec.rb
Labels: Product: caseflow-queue, Stakeholder: VHA, Team: Saturn 🪐, Feature: VHA users can preview appeal issue types

#18670 Feature: Establishment Task during AMA Intake
  app/models/tasks/establishment_task.rb
  app/workflows/initial_tasks_factory.rb
  client/app/queue/components/TaskRows.jsx
Labels: MST/PACT

#18693 Bug Fix: cycle through array backwards when creating IssuesUpdateTasks
  app/models/request_issues_update.rb
Labels: MST/PACT

#18699 HunJerBAH/APPEALS 23467: Updated MST/PACT Edit AMA Appeal Success Banner
  app/controllers/appeals_controller.rb
  app/models/request_issues_update.rb
  client/app/nonComp/components/Alerts.jsx
Labels: MST/PACT

#18705 bugfix/APPEALS-23556 - Fix casing for PACT Act
  client/app/intake/components/IntakeRadioField.jsx
  spec/feature/intake/add_issues_spec.rb
Labels: MST/PACT

#18641 SeanC/APPEALS-18736 Navigation for Veterans Health Administration Decision Review Queue Link
  app/controllers/application_controller.rb
  client/app/components/NavigationBar.stories.js
  client/package.json
  client/yarn.lock
  spec/feature/switch_apps_spec.rb
Labels: Stakeholder: VHA, Team: Titan

#18690 Justin/APPEALS-23365
  app/controllers/appeals_controller.rb
Labels: MST/PACT

#18626 TYLERB/APPEALS-16541: Ability to Filter with the Issue Type Column in Conventional Queues
  app/controllers/decision_reviews_controller.rb
  app/controllers/organizations/tasks_controller.rb
  app/models/organizations/business_line.rb
  app/models/queue_column.rb
  app/models/queue_tabs/vha_camo_completed_tasks_tab.rb
  app/models/task_filter.rb
  app/services/cached_appeal_service.rb
  client/app/components/TableFilter.jsx
  client/app/nonComp/components/NonCompTabs.jsx
  client/app/queue/OrganizationQueueLoadingScreen.jsx
  client/app/queue/QueueActions.js
  client/app/queue/QueueDropdownFilter.jsx
  client/app/queue/QueueTable.jsx
  client/app/queue/QueueTableBuilder.jsx
  client/app/queue/UnassignedCasesPage.jsx
  client/app/queue/components/TaskTable.jsx
  client/app/queue/components/TaskTableColumns.jsx
  client/app/queue/selectors.js
  client/app/queue/uiReducer/uiActions.js
  client/app/queue/uiReducer/uiReducer.js
  client/constants/QUEUE_CONFIG.json
  client/test/app/queue/__snapshots__/QueueTable.test.js.snap
  db/migrate/20230508224138_add_issue_types_to_cached_appeal_attributes.rb
  db/schema.rb
  spec/controllers/organizations/tasks_controller_spec.rb
  spec/feature/non_comp/reviews_spec.rb
  spec/feature/queue/camo_queue_spec.rb
  spec/models/queue_column_spec.rb
  spec/models/task_filter_spec.rb
  spec/services/cached_appeal_service_spec.rb
Labels: Product: caseflow-queue, Stakeholder: VHA, Feature: pre-docket, Team: Saturn 🪐, Feature: VHA users can preview appeal issue types

#18714 LiannaN/APPEALS-16537
  .codeclimate.yml
  app/models/organizations/vha_regional_office.rb
  spec/feature/queue/vha_regional_queue_spec.rb
  spec/models/organizations/vha_regional_office_spec.rb
  spec/models/queue_tabs/vha_regional_office_assigned_tasks_tab_spec.rb
  spec/models/queue_tabs/vha_regional_office_completed_tasks_tab_spec.rb
  spec/models/queue_tabs/vha_regional_office_in_progress_tasks_tab_spec.rb
  spec/models/queue_tabs/vha_regional_office_on_hold_tasks_tab_spec.rb
Labels: Product: caseflow-queue, Stakeholder: VHA, Feature: VHA CSP Pre-Docket, Feature: VHA users can preview appeal issue types

#18736 JHoang/APPEALS-23663
  app/models/request_issues_update.rb
  client/app/queue/components/TaskRows.jsx
Labels: MST/PACT

#18740 VBMS generators using bgs_contention
  lib/fakes/bgs_service_record_maker.rb
Labels: MST/PACT

#18730 Deepak/appeals 23469
  client/app/intakeEdit/components/EditIntakeIssueModal.jsx
Labels: MST/PACT

#18733 Add Decisions Card Now Displays Special Issues
  client/app/queue/components/DecisionIssues.jsx
Labels: MST/PACT

#18668 Tracking PR for APPEALS-21133
  app/models/supplemental_claim_intake.rb
  app/models/user.rb
  client/app/intake/constants.js
  client/app/intake/pages/supplementalClaim/review.jsx
  client/app/intake/reducers/higherLevelReview.js
  client/app/intake/reducers/supplementalClaim.js
  config/environments/development.rb
  config/environments/test.rb
  spec/feature/intake/review_page_spec.rb
  spec/feature/intake/supplemental_claim_spec.rb
  spec/support/intake_helpers.rb
Labels: Product: caseflow-intake, Team: Andromeda 🚀

#18758 Special Issue Designation Checkboxes Now Persist: APPEALS - 23834
  client/app/queue/components/QueueFlowPage.jsx
Labels: MST/PACT

#18761 Fix: only users with edit privileges
  app/controllers/appeals_controller.rb
Labels: MST/PACT

#18737 HunJerBAH/APPEALS-7497 Feature Toggle Update
  app/controllers/appeals_controller.rb
  app/controllers/case_reviews_controller.rb
  app/controllers/issues_controller.rb
  app/models/legacy_appeal.rb
  app/models/request_issues_update.rb
  app/models/serializers/work_queue/legacy_appeal_serializer.rb
  app/policies/appeal_request_issues_policy.rb
  app/workflows/initial_tasks_factory.rb
  client/app/components/AmaIssueList.jsx
  client/app/intake/components/AddedIssue.jsx
  client/app/intake/components/IssueList.jsx
  client/app/queue/AddEditIssueView.jsx
  client/app/queue/CaseDetailsView.jsx
  client/app/queue/LegacySelectDispositionsView.jsx
  client/app/queue/QueueApp.jsx
  client/app/queue/SelectDispositionsView.jsx
  client/app/queue/components/CaseDetailsIssueList.jsx
  client/app/queue/components/LegacyIssueListItem.jsx
  client/app/queue/constants.js
  spec/feature/intake/add_issues_spec.rb
  spec/models/appeal_spec.rb
  spec/models/request_issue_spec.rb
  spec/workflows/initial_tasks_factory_spec.rb
Labels: MST/PACT

#18763 HunJerBAH/APPEALS-17497: Inactive User Fix
  app/controllers/appeals_controller.rb
  app/controllers/case_reviews_controller.rb
  app/controllers/issues_controller.rb
  app/models/organizations/special_issue_edit_team.rb
  app/models/request_issues_update.rb
  app/workflows/initial_tasks_factory.rb
Labels: MST/PACT

#18775 Fix: flash success message after legacy appeal MST/Pact update.
  app/controllers/appeals_controller.rb
Labels: MST/PACT

#18779 Destroy RequestIssuesUpdate instance if @error_code :no_changes
  app/models/request_issues_update.rb
Labels: MST/PACT

#18755 JHoang/APPEALS-23883
  client/app/queue/SelectDispositionsView.jsx
Labels: MST/PACT

#18708 [DOCUMENTATION] - Fix MAC_INTEL.md formatting and links
  MAC_INTEL.md
Labels: Type: Documentation

#18706 [DOCUMENTATION] - Update broken links and format of `WINDOWS_11.md`
  WINDOWS_11.md
Labels: Type: Documentation

#18794 Bugfix: Intake admin can't edit special issues designation
  client/app/intake/components/AddIssuesModal.jsx
  client/app/intakeEdit/components/EditIntakeIssueModal.jsx
Labels: MST/PACT

#18816 Khalin/appeals 24109
  client/app/components/AmaIssueList.jsx
  client/app/queue/components/CaseDetailsIssueList.jsx
  client/app/queue/components/DecisionIssues.jsx
Labels: MST/PACT

#18829 Fixed banner error on save edit issues
  app/controllers/appeals_controller.rb
Labels: MST/PACT

#18826 Will/appeals 24297
  client/app/intake/components/IntakeRadioField.jsx
Labels: MST/PACT

#18822 uncommented #validate before perform
  app/models/request_issues_update.rb
Labels: MST/PACT

#18709 b_reed/APPEALS-22837
  app/controllers/idt/api/v2/distributions_controller.rb
  config/routes.rb
  lib/fakes/pacman_service.rb
  spec/controllers/idt/api/v2/distributions_controller_spec.rb
Labels: Product: IDT, Feature: Caseflow-PacMan Integration

#18791 get vbms core contentions by participant id and updated bgs gem
  Gemfile
  Gemfile.lock
  app/models/rating.rb
  app/models/rating_issue.rb
  app/services/external_api/bgs_service.rb
  lib/fakes/bgs_service.rb
Labels: MST/PACT

#18849 Will/appeals 24407 IntakeRadioField pre-populate special issues from VBMS.
  client/app/intake/components/IntakeRadioField.jsx
Labels: MST/PACT

#18840 Will/appeals 24373
  app/controllers/case_reviews_controller.rb
Labels: MST/PACT

#18799 TYLERB/APPEALS-24057: Research Feasibility of Maintaining Filtering Across Queue Tabs
  app/models/organizations/business_line.rb
  app/models/queue_column.rb
  app/models/queue_tabs/bva_intake_pending_tab.rb
  app/models/queue_tabs/bva_intake_ready_for_review_tab.rb
  client/app/queue/QueueTableBuilder.jsx
  db/seeds/veterans_health_administration.rb
  spec/controllers/organizations/tasks_controller_spec.rb
  spec/feature/api/v2/appeals_spec.rb
  spec/models/organizations/vha_regional_office_spec.rb
  spec/models/queue_column_spec.rb
Labels: Product: caseflow-queue, Stakeholder: VHA, javascript, ruby, Team: Saturn 🪐, Product: Decision Review Queues, Feature: VHA users can preview appeal issue types

#18853 Ryan/appeals 24482
  lib/generators/vacols/case.rb
  lib/tasks/seed_legacy_appeals.rake
Labels: MST/PACT

#18858 JHoang/APPEALS-22481
  app/controllers/appeals_controller.rb
Labels: MST/PACT

#18868 Refactor format_description_text
  app/models/tasks/establishment_task.rb
Labels: MST/PACT

#18851 SeanC/APPEALS-24042 CSS Issue Queue Table Does not Fit Screen
  client/app/nonComp/components/TaskTableTab.jsx
  client/app/styles/_noncomp.scss
  client/app/styles/_table.scss
Labels: Product: caseflow-queue, Type: Bug, Team: Titan

#18887 Will/appeals 24129 benefit type
  app/controllers/appeals_controller.rb
  app/controllers/case_reviews_controller.rb
  app/controllers/issues_controller.rb
  app/models/request_issues_update.rb
  app/models/tasks/issues_update_task.rb
  client/app/queue/components/TaskRows.jsx
Labels: MST/PACT

#18890 Will/appeals 24663
  app/models/request_issues_update.rb
  app/models/tasks/establishment_task.rb
  client/app/queue/components/TaskRows.jsx
Labels: MST/PACT

#18814 hearings/APPEALS-21118 and APPEALS-21121 APPEALS-21123
  .rubocop.yml
  app/controllers/concerns/mail_package_concern.rb
  app/controllers/idt/api/v1/base_controller.rb
  app/controllers/idt/api/v1/upload_vbms_document_controller.rb
  app/controllers/idt/api/v2/distributions_controller.rb
  app/jobs/mail_request_job.rb
  app/jobs/upload_document_to_vbms_job.rb
  app/models/vbms_communication_package.rb
  app/models/vbms_distribution.rb
  app/models/vbms_distribution_destination.rb
  app/services/external_api/pacman_service.rb
  app/validators/mail_request_validator.rb
  app/workflows/mail_request.rb
  app/workflows/prepare_document_upload_to_vbms.rb
  app/workflows/upload_document_to_vbms.rb
  config/environments/test.rb
  config/initializers/pacman.rb
  lib/caseflow/error.rb
  lib/fakes/pacman_service.rb
  spec/controllers/idt/api/v1/upload_vbms_document_controller_spec.rb
  spec/controllers/idt/api/v2/distributions_controller_spec.rb
  spec/factories/mail_request.rb
  spec/factories/vbms_communication_package.rb
  spec/factories/vbms_distribution.rb
  spec/factories/vbms_distribution_destination.rb
  spec/jobs/mail_request_job_spec.rb
  spec/jobs/upload_document_to_vbms_job_spec.rb
  spec/models/vbms_communication_package_spec.rb
  spec/models/vbms_distribution_destination_spec.rb
  spec/models/vbms_distribution_spec.rb
  spec/services/external_api/pacman_service_spec.rb
  spec/workflows/mail_request_spec.rb
Labels: Team: Andromeda 🚀, Feature: Caseflow-PacMan Integration

#18748 HunJerBAH/APPEALS-23698
  app/controllers/appeals_controller.rb
  app/controllers/case_reviews_controller.rb
  app/controllers/issues_controller.rb
  app/models/appeal.rb
  app/models/concerns/issue_updater.rb
  app/models/request_issues_update.rb
  app/models/special_issue_change.rb
  app/models/tasks/establishment_task.rb
  db/migrate/20230609124110_create_special_issue_changes.rb
  db/migrate/20230609153757_add_change_category_to_special_issue_changes.rb
  db/migrate/20230609161731_update_special_issue_changes.rb
  db/migrate/20230629114954_add_decision_id_to_special_issue_changes.rb
  db/schema.rb
Labels: MST/PACT

#18901 JHoang/Appeals-22931
  client/app/components/AmaIssueList.jsx
  spec/feature/queue/attorney_checkout_flow_spec.rb
  spec/feature/queue/judge_checkout_flow_spec.rb
Labels: MST/PACT

#18904 Feature Tests Legacy Queue Workflow
  spec/feature/intake/appeal/edit_spec.rb
Labels: MST/PACT

#18906 Will/appeals 22928 vbms
  spec/feature/intake/add_issues_spec.rb
  spec/support/intake_helpers.rb
Labels: MST/PACT
