Repository department-of-veterans-affairs/caseflow, pull requests merged in 2023-01, with the labels that each got.

#17889 Decision Review Queue In-Progress Tasks Query Optimization
  app/controllers/decision_reviews_controller.rb
  app/models/organizations/business_line.rb
  app/models/serializers/work_queue/decision_review_task_serializer.rb
  app/models/serializers/work_queue/veteran_record_request_serializer.rb
  app/views/decision_reviews/index.html.erb
  spec/factories/higher_level_review.rb
  spec/factories/supplemental_claim.rb
  spec/factories/task.rb
  spec/models/business_line_spec.rb
  spec/models/serializers/work_queue/veteran_record_request_serializer_spec.rb
Labels: Team: Saturn 🪐, Product: Decision Review Queues, Feature: DR Query Optimization

#17888 MattT/APPEALS-12468: Modify Decision Review Queue Filtering Functionality to Account for Pagination + APPEALS-12480: Removal of References to Defunct Task Methods
  app/controllers/concerns/generic_task_pagination_concern.rb
  app/controllers/decision_reviews_controller.rb
  app/models/organizations/business_line.rb
  app/views/decision_reviews/index.html.erb
  app/views/decision_reviews/show.html.erb
  client/app/constants/SpecialIssues.js
  client/app/nonComp/actions/task.js
  client/app/nonComp/components/NonCompTabs.jsx
  client/app/nonComp/reducers/index.js
  client/app/nonComp/util/index.js
  client/app/queue/components/TaskRows.jsx
  client/app/queue/selectors.js
  client/test/app/nonComp/NonCompTabs.test.js
  client/test/app/nonComp/util/index.test.js
  client/test/data/taskFilterDetails.js
  spec/controllers/decision_reviews_controller_spec.rb
  spec/feature/intake/higher_level_review/edit_spec.rb
  spec/feature/intake/supplemental_claim/edit_spec.rb
  spec/feature/non_comp/board_grants_spec.rb
  spec/feature/non_comp/dispositions_spec.rb
  spec/feature/non_comp/record_requests_spec.rb
  spec/feature/non_comp/reviews_spec.rb
  spec/models/business_line_spec.rb
Labels: Team: Saturn 🪐, Product: Decision Review Queues, Feature: DR Queue Pagination, Feature: DR Query Optimization

#17769 Add Issue's Issue Category dropdown displays invalid value after changing Benefit type
  client/app/components/SearchableDropdown.jsx
  spec/feature/intake/appeal/edit_spec.rb
Labels: Product: caseflow-intake, Type: Bug, User: BVA Intake

#17906 TYLERB/APPEALS-12467: Modify decision review queue search functionality to account for pagination
  app/controllers/concerns/generic_task_pagination_concern.rb
  app/controllers/decision_reviews_controller.rb
  app/models/organizations/business_line.rb
  app/models/serializers/work_queue/decision_review_task_serializer.rb
  client/.storybook/middleware.js
  client/.storybook/utils.js
  client/app/nonComp/components/NonCompTabs.jsx
  client/app/nonComp/components/NonCompTabs.stories.js
  client/app/queue/QueueTable.jsx
  client/constants/QUEUE_CONFIG.json
  spec/controllers/decision_reviews_controller_spec.rb
  spec/feature/non_comp/record_requests_spec.rb
  spec/feature/non_comp/reviews_spec.rb
  spec/models/business_line_spec.rb
Labels: Team: Saturn 🪐, Product: Decision Review Queues, Feature: DR Queue Pagination

#17935 APPEALS-9653: Search capability label
  client/app/nonComp/components/NonCompTabs.jsx
  client/app/styles/_noncomp.scss
Labels: Team: Titan

#17954 hotfix/Sort Veteran Participant ID Column Numerically
  app/controllers/decision_reviews_controller.rb
  app/models/organizations/business_line.rb
  client/app/nonComp/components/NonCompTabs.jsx
  spec/feature/non_comp/reviews_spec.rb
Labels: Team: Saturn 🪐, Feature: DR Queue Pagination, Feature: DR Query Optimization

#17931 SeanC/APPEALS-9134
  app/models/serializers/work_queue/decision_review_task_serializer.rb
  client/app/nonComp/components/NonCompTabs.jsx
  client/app/nonComp/components/TaskTableColumns.jsx
  client/app/nonComp/util/index.js
  spec/feature/non_comp/board_grants_spec.rb
  spec/feature/non_comp/dispositions_spec.rb
  spec/feature/non_comp/record_requests_spec.rb
  spec/feature/non_comp/reviews_spec.rb
  spec/models/serializers/work_queue/decision_review_task_serializer_spec.rb
  spec/models/serializers/work_queue/veteran_record_request_serializer_spec.rb
Labels: Team: Titan

#17934 msteele/APPEALS-7229 PDF outline for notifications
  app/assets/stylesheets/notification_pdf_style.css
  app/views/templates/notification_report_pdf_template.html.erb
Labels: VA Notify, Team: Andromeda 🚀

#17938 hotfix/APPEALS-13759: Browser Deprecation of event.path
  client/app/components/DropdownButton.jsx
  client/package.json
  client/yarn.lock
Labels: Type: Bug

#17947 Decision Review Disposition Page Enhancements
  client/app/nonComp/components/Disposition.jsx
  client/app/styles/_noncomp.scss
  spec/feature/non_comp/dispositions_spec.rb
Labels: Team: Titan, Feature: DR Queue SSN Search Capability

#17966 hotfix/APPEALS-14468: Claimant Name sorting fixes
  app/models/organizations/business_line.rb
  app/models/serializers/work_queue/decision_review_task_serializer.rb
  client/app/nonComp/components/NonCompTabs.jsx
  client/app/nonComp/components/TaskTableColumns.jsx
  spec/feature/non_comp/reviews_spec.rb
Labels: Team: Saturn 🪐, Feature: DR Queue Pagination, Feature: DR Query Optimization

#17949 APPEALS-13122: Created models, migration, factories and updated specs
  app/models/membership_request.rb
  db/migrate/20230126230602_create_membership_requests.rb
  db/schema.rb
  spec/factories/membership_request.rb
  spec/models/membership_request_spec.rb
Labels: Team: Saturn 🪐, Feature: VHA Team Management

#17963 SeanC/APPEALS-13786
  app/views/decision_reviews/index.html.erb
  app/views/decision_reviews/show.html.erb
  client/.storybook/utils.js
  client/app/nonComp/components/NonCompTabs.jsx
  client/app/nonComp/components/NonCompTabs.stories.js
  client/app/nonComp/components/TaskTableTab.jsx
  client/app/nonComp/util/index.js
  client/test/app/nonComp/NonCompTabs.test.js
  spec/feature/non_comp/board_grants_spec.rb
  spec/feature/non_comp/dispositions_spec.rb
  spec/feature/non_comp/record_requests_spec.rb
  spec/feature/non_comp/reviews_spec.rb
  spec/models/serializers/work_queue/board_grant_effectuation_task_serializer_spec.rb
  spec/models/tasks/decision_review_task_spec.rb
Labels: Team: Titan, Feature: DR Queue SSN Search Capability
