Repository department-of-veterans-affairs/caseflow, pull requests merged in 2023-05, with the labels that each got.

#18485 hotfix/APPEALS-15457v2
  app/models/hearing.rb
  spec/models/hearing_spec.rb
Labels: Team: Andromeda 🚀

#18512 JHoang/appeals 17546
  client/app/queue/SelectDispositionsView.jsx
  client/app/queue/constants.js
  spec/feature/queue/attorney_checkout_flow_spec.rb
  spec/feature/queue/judge_checkout_flow_spec.rb
Labels: MST/PACT

#18523 HunJerBAH/APPEALS-17551
  app/models/request_issue.rb
  app/serializers/intake/request_issue_serializer.rb
  client/app/intake/util/issues.js
  spec/controllers/intakes_controller_spec.rb
  spec/models/request_issue_spec.rb
Labels: MST/PACT

#18524 APPEALS-17528 Create MST and PACT status method on Appeal model (AC 2-3/ AC 9.2.1)
  app/models/appeal.rb
  spec/factories/special_issue_list.rb
  spec/models/appeal_spec.rb
Labels: MST/PACT

#18517 APPEALS-17536 - Special Issues designation updated
  client/COPY.json
  client/app/intake/components/AddedIssue.jsx
  client/app/intake/components/NonratingRequestIssueModal.jsx
  client/app/intakeEdit/components/EditIntakeIssueModal.jsx
Labels: MST/PACT

#18545 Jhoang/appeals 21860
  client/app/queue/AddEditIssueView.jsx
  client/app/queue/utils.js
  spec/feature/queue/attorney_checkout_flow_spec.rb
  spec/feature/queue/judge_checkout_flow_spec.rb
Labels: MST/PACT

#18560 Jhoang/appeals 17545
  app/controllers/issues_controller.rb
  app/mappers/issue_mapper.rb
  client/app/queue/AddEditIssueView.jsx
  spec/controllers/issues_controller_spec.rb
  spec/mappers/issue_mapper_spec.rb
Labels: MST/PACT

#18568 b_reed/APPEALS-16193
  config/environments/test.rb
Labels: Integration: Lighthouse

#18533 redirect AMA appeals directly to Add Decisions page
  .github/workflows/workflow.yml
  app/repositories/task_action_repository.rb
  spec/feature/queue/ama_queue_spec.rb
Labels: MST/PACT

#18500 JonathanC/APPEALS-21142
  app/models/vbms_communication_package.rb
  app/models/vbms_distribution.rb
  app/models/vbms_distribution_destination.rb
  db/migrate/20230425144000_create_pacman_integration.rb
  db/schema.rb
  spec/models/vbms_communication_package_spec.rb
  spec/models/vbms_distribution_destination_spec.rb
  spec/models/vbms_distribution_spec.rb
Labels: Feature: Caseflow-PacMan Integration

#18573 Ryan appeals/17513 redo
  app/controllers/intakes_controller.rb
  app/models/contestable_issue.rb
  client/app/components/Checkbox.jsx
  client/app/components/RadioField.jsx
  client/app/intake/components/AddIssuesModal.jsx
  client/app/intake/components/IntakeRadioField.jsx
  client/app/intake/reducers/featureToggles.js
  lib/generators/veteran.rb
  spec/feature/intake/add_issues_spec.rb
Labels: MST/PACT

#18439 hotfix/APPEALS-19808
  app/jobs/va_notify_status_update_job.rb
  spec/jobs/va_notify_status_update_job_spec.rb
Labels: Team: Andromeda 🚀

#18580 APPEALS-21842 Add MST and PACT status method to LEGACY Appeal model
  app/models/issue.rb
  app/models/legacy_appeal.rb
Labels: MST/PACT

#18581 APPEALS-17536 - Hotfix for prop naming
  client/app/intake/components/AddedIssue.jsx
Labels: MST/PACT

#18585 Feature/appeals 17521/legacy edit issues
  app/controllers/appeals_controller.rb
  app/models/appeal.rb
  app/models/legacy_appeal.rb
  app/models/legacy_hearing.rb
  app/models/serializers/work_queue/legacy_appeal_serializer.rb
  app/serializers/intake/legacy_appeal_serializer.rb
  app/views/appeals/edit.html.erb
  client/app/intake/components/IssueList.jsx
  client/app/intake/pages/addIssues.jsx
  client/app/intake/util/issues.js
  client/app/intakeEdit/components/EditIntakeIssueModal.jsx
  client/app/intakeEdit/reducers/index.js
Labels: MST/PACT

#18583 Will/appeals 17561
  app/controllers/case_reviews_controller.rb
  db/schema.rb
  spec/controllers/case_reviews_controller_spec.rb
Labels: MST/PACT

#18598 Added MST and PACT reason for change label + data passing) (Re-do)
  app/models/tasks/issues_update_task.rb
  client/app/queue/components/TaskRows.jsx
  spec/feature/queue/ama_queue_spec.rb
  spec/models/issues_update_task_spec.rb
Labels: MST/PACT

#18547 Hotfix/appeals 15446
  client/COPY.json
  client/app/nonComp/components/Disposition.jsx
  client/app/nonComp/pages/TaskPage.stories.js
  client/test/app/util/DateUtil-test.js
  client/test/data/queue/nonCompTaskPage/nonCompTaskPageData.js
  spec/factories/higher_level_review.rb
  spec/feature/non_comp/dispositions_spec.rb
Labels: Team: Titan

#18520 TYLERB/APPEALS-16534: Add Issue Type column to VHA CAMO Pre-docket queue
  app/models/organizations/vha_camo.rb
  app/models/organizations/vha_caregiver_support.rb
  app/models/serializers/work_queue/task_column_serializer.rb
  client/app/queue/QueueTableBuilder.jsx
  client/app/queue/components/TaskTableColumns.jsx
  spec/feature/non_comp/reviews_spec.rb
  spec/feature/queue/camo_queue_spec.rb
  spec/feature/queue/caregiver_support_queue.rb
  spec/feature/queue/queue_shared_examples_spec.rb
  spec/feature/queue/vha_camo_assignment_spec.rb
  spec/feature/queue/vha_camo_cancellation_spec.rb
  spec/feature/queue/vha_camo_queue_spec.rb
  spec/feature/queue/vha_caregiver_support_queue.rb
  spec/models/organizations/vha_camo_spec.rb
  spec/models/queue_tabs/vha_camo_in_progress_tasks_tab_spec.rb
  spec/models/queue_tabs/vha_caregiver_support_completed_tasks_tab_spec.rb
  spec/models/queue_tabs/vha_caregiver_support_in_progress_tasks_tab_spec.rb
  spec/models/queue_tabs/vha_caregiver_support_unassigned_tasks_tab_spec.rb
Labels: Product: caseflow-queue, Stakeholder: VHA, Team: Saturn 🪐, Feature: VHA users can preview appeal issue types

#18637 b_reed/APPEALS-13386
  app/views/queue/index.html.erb
  client/app/queue/mtv/AddressMotionToVacateView.jsx
  client/app/queue/mtv/MTVJudgeDisposition.jsx
  client/test/app/queue/mtv/MTVJudgeDisposition.test.js
  scripts/enable_features_dev.rb
  spec/feature/queue/motion_to_vacate_spec.rb
Labels: Product: caseflow-queue, Team: Andromeda 🚀, Product: Decision Review Queues

#18649 fix checkbox not prepopulating on mst/pact issue legacy decision
  client/app/queue/AddEditIssueView.jsx
  client/app/queue/utils.js
Labels: MST/PACT

#18655 Justin/APPEALS-23333
  app/controllers/intakes_controller.rb
  client/app/intake/components/AddIssuesModal.jsx
  client/app/intake/components/IntakeRadioField.jsx
  client/app/intake/pages/addIssues.jsx
  client/app/intake/reducers/featureToggles.js
Labels: MST/PACT

#18653 Ricky/appeals 17558
  client/app/intake/actions/addIssues.js
  client/app/queue/SelectDispositionsView.jsx
Labels: MST/PACT

#18659 Ki/APPEALS-18872 - Create MST & PACT Conditional Rendering within BadgeArea (AC 2.3)
  app/models/appeal.rb
  app/models/serializers/idt/v1/appeal_details_serializer.rb
  app/models/serializers/work_queue/appeal_serializer.rb
  app/models/serializers/work_queue/legacy_appeal_serializer.rb
  app/models/serializers/work_queue/legacy_task_serializer.rb
  app/models/serializers/work_queue/task_column_serializer.rb
  app/models/serializers/work_queue/task_serializer.rb
  client/app/components/badges/MstBadge/MstBadge.jsx
  client/app/components/badges/PactBadge/PactBadge.jsx
  client/app/hearings/components/Details.jsx
  client/app/hearings/components/assignHearings/TimeSlotCard.jsx
  client/app/hearings/components/details/DetailsHeader.jsx
  client/app/hearings/components/scheduleHearing/AppealInformation.jsx
  client/app/hearings/components/scheduleHearing/TimeSlotDetail.jsx
  client/app/queue/CaseListTable.jsx
  client/app/queue/components/IssueRemandReasonsOptions.jsx
  client/app/queue/utils.js
Labels: MST/PACT

#18611 Lianna/APPEALS-16536
  app/models/organizations/vha_program_office.rb
  spec/models/organizations/vha_program_office_spec.rb
  spec/models/queue_tabs/vha_program_office_assigned_tasks_tab_spec.rb
  spec/models/queue_tabs/vha_program_office_completed_tasks_tab_spec.rb
  spec/models/queue_tabs/vha_program_office_in_progress_tasks_tab_spec.rb
  spec/models/queue_tabs/vha_program_office_on_hold_tasks_tab_spec.rb
  spec/models/queue_tabs/vha_program_office_ready_for_review_tasks_tab_spec.rb
Labels: Product: caseflow-queue, Stakeholder: VHA, Feature: pre-docket, Team: Saturn 🪐, Feature: VHA users can preview appeal issue types
