Repository department-of-veterans-affairs/caseflow, pull requests merged in 2023-07, with the labels that each got.

#18911 Will/appeals 24807
  app/controllers/appeals_controller.rb
  app/controllers/issues_controller.rb
  client/app/queue/components/TaskRows.jsx
Labels: MST/PACT

#18910 [DOCUMENTATION] - Fix .zshrc file settings in `MAC_M1.md`
  MAC_M1.md
Labels: Type: Documentation

#18924 Enable feature toggle in case_details_spec
  spec/feature/queue/case_details_spec.rb
Labels: MST/PACT

#18926 JHoang-17497 rspec fixes
  spec/feature/queue/bva_dispatch_return_flow_spec.rb
  spec/feature/queue/quality_review_flow_spec.rb
  spec/feature/withdrawn_request_issues_spec.rb
  spec/models/contestable_issue_spec.rb
  spec/models/decision_review_spec.rb
  spec/workflows/initial_tasks_factory_spec.rb
Labels: MST/PACT

#18929 Add issues spec updating failing feature tests.
  spec/feature/intake/add_issues_spec.rb
Labels: MST/PACT

#18931 HunJerBAH/CAVC Remand Pulls MST/PACT from Past Decisions
  app/models/decision_issue.rb
Labels: MST/PACT

#18943 removing skip and making test work
  spec/controllers/organizations/users_controller_spec.rb
Labels: Eng: Flaky Test

#18940 Request Issue Model spec test fix
  spec/models/request_issue_spec.rb
Labels: MST/PACT

#18945 JHoang/APPEALS-24984
  client/app/queue/utils.js
Labels: MST/PACT

#18946 All tests passing
  app/models/request_issues_update.rb
  spec/models/request_issues_update_spec.rb
Labels: MST/PACT

#18928 APPEALS-24103 - Fixing flake rspec tests - appeals_controller
  spec/controllers/appeals_controller_spec.rb
Labels: Eng: Flaky Test

#18825 APPEALS-24384: Searchable Dropdown click to close UI fix
  client/app/components/SearchableDropdown.jsx
  spec/models/concerns/appeal_concern_spec.rb
Labels: Type: Bug, javascript, Team: Saturn 🪐

#18955 APPEALS-24881
  app/controllers/appeals_controller.rb
  app/controllers/issues_controller.rb
Labels: MST/PACT

#18954 Appeals 24989 - MST/PACT Badge Rendering during Judge decision review process
  client/app/components/badges/MstBadge/MstBadge.jsx
  client/app/components/badges/PactBadge/PactBadge.jsx
Labels: MST/PACT

#18975 appeals 25076
  app/models/concerns/issue_updater.rb
  client/app/queue/components/TaskRows.jsx
Labels: MST/PACT

#18978 Fixed failing rspecs
  spec/models/end_product_establishment_spec.rb
Labels: MST/PACT

#18979 HunJerBAH/APPEALS-25276
  app/controllers/appeals_controller.rb
  app/controllers/issues_controller.rb
  app/models/concerns/issue_updater.rb
  app/models/request_issues_update.rb
  app/workflows/initial_tasks_factory.rb
Labels: MST/PACT

#18963 JHoang-17497-rspec-fixes-3
  app/models/legacy_hearing.rb
Labels: MST/PACT

#18968 Changed comparison to handle more than 10 records being present.
  spec/seeds/intake_spec.rb
Labels: MST/PACT

#18967 Fixed tests on ama_queue_spec.rb
  spec/feature/queue/ama_queue_spec.rb
Labels: MST/PACT

#18965 Removed redundant test because a more complete test for this exists i…
  spec/controllers/appeals_controller_spec.rb
Labels: MST/PACT

#18957 mock mst and pact on vacols_issue
  app/models/vacols/case_issue.rb
  spec/models/judge_case_review_spec.rb
Labels: MST/PACT

#18969 update the spec with decision review from response
  spec/controllers/case_reviews_controller_spec.rb
Labels: MST/PACT

#18985 Ratings fix
  app/models/rating.rb
Labels: MST/PACT

#18996 Error Handling for Nil, Single Contention, and Array of Contentions from Rating BGS Response
  app/models/rating.rb
Labels: MST/PACT

#18989 Khalin/appeals 22929
  spec/feature/queue/ama_queue_workflow_spec.rb
Labels: MST/PACT

#18994 JHoang/17497-rspec-fixes-4
  spec/feature/intake/appeal_spec.rb
  spec/feature/intake/supplemental_claim_spec.rb
Labels: MST/PACT

#19029 Appeals-26061: Auto tagging feature flag
  app/views/queue/index.html.erb
Labels: auto-tagging

#19017 Remove `disable_claim_establishment` FeatureToggle - APPEALS/19822
  app/jobs/decision_review_process_job.rb
  spec/feature/intake/higher_level_review_spec.rb
  spec/jobs/decision_review_process_job_spec.rb
  spec/models/higher_level_review_intake_spec.rb
Labels: Product: caseflow-intake, Stakeholder: VHA, Team: Saturn 🪐, Product: Decision Review Queues, Feature: VHA Enter No Decision Date

#19072 HunJerBAH APPEALS-26881: Reject Unknown Attributes in RatingDecisions Hash
  app/models/rating_decision.rb
Labels: MST/PACT

#19071 APPEALS-26881: MST and PACT Feature Toggle Update
  app/models/tasks/judge_decision_review_task.rb
  app/models/tasks/judge_dispatch_return_task.rb
  app/repositories/task_action_repository.rb
  client/app/constants/SpecialIssueFilters.js
  client/app/constants/SpecialIssues.js
  client/app/queue/QueueApp.jsx
  client/app/queue/SelectDispositionsView.jsx
  client/app/queue/SelectSpecialIssuesView.jsx
  client/app/queue/components/CaseDetailsIssueList.jsx
  client/app/queue/components/DecisionIssues.jsx
  client/constants/TASK_ACTIONS.json
Labels: MST/PACT

#19077 Deepak2/appeals 25079
  Gemfile
  Gemfile.lock
Labels: auto-tagging

#19035 Craig/appeals 26096
  app/models/serializers/work_queue/decision_review_task_serializer.rb
  client/app/intake/pages/addIssues.jsx
  db/seeds/intake.rb
  db/seeds/veterans_health_administration.rb
  spec/controllers/decision_reviews_controller_spec.rb
  spec/factories/claimant.rb
  spec/factories/higher_level_review.rb
  spec/factories/supplemental_claim.rb
  spec/factories/task.rb
  spec/feature/api/v2/appeals_spec.rb
  spec/feature/non_comp/dispositions_spec.rb
  spec/feature/non_comp/reviews_spec.rb
  spec/models/claim_review_intake_spec.rb
  spec/models/claim_review_spec.rb
  spec/models/claimant_spec.rb
  spec/models/higher_level_review_intake_spec.rb
  spec/models/request_issue_spec.rb
  spec/models/serializers/work_queue/appeal_serializer_spec.rb
  spec/models/serializers/work_queue/board_grant_effectuation_task_serializer_spec.rb
  spec/models/serializers/work_queue/decision_review_task_serializer_spec.rb
  spec/models/serializers/work_queue/veteran_record_request_serializer_spec.rb
  spec/models/supplemental_claim_intake_spec.rb
  spec/models/tasks/decision_review_task_spec.rb
  spec/workflows/end_product_code_selector_spec.rb
Labels: Stakeholder: VHA, Team: Titan, Feature: Appellant POA
